#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################


if [ -z "$localthorportbase" ]; then
  export localthorportbase=$THORSLAVEPORT
fi
if [ -z "$localthorportinc" ]; then
  export localthorportinc=2000
fi
rm -f thorgroup
lastslave=nop
for slave in $(cat slaves); do
 if [ "$slave" != "$lastslave" ]; then
  let "base = $localthorportbase";
 else
  let "base += $localthorportinc";
 fi;
 echo $slave:$base >> thorgroup
 lastslave=$slave;
done

