#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################


if [ -z "$localthorportinc" ]; then
  export localthorportinc=200
fi
rm -f thorgroup

function contains() {
    local n=$#
    local value=${!n}
    for ((i=1;i < ${n};i++)) {
        if [ "${!i}" == "${value}" ]; then
            echo "${i}"
            return 0
        fi
    }
    echo "0"
    return 1
}

declare -a ports_used
declare -a hosts
for slave in $(cat slaves); do
    p=$(contains "${hosts[@]}" "${slave}")
    if [ 0 == ${p} ]; then
        echo "${slave}:${THORSLAVEPORT}" >> thorgroup
        p=$((${#hosts[@]}+1))
        ports[${p}]=${THORSLAVEPORT}
        hosts=(${hosts[@]} $slave)
    else
        newport=$((${ports[${p}]}+${localthorportinc}))
        echo "${slave}:${newport}" >> thorgroup
        ports[${p}]=${newport}
    fi
done
