#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################

# Invoke the script to parse command line arguments and shift args
# past options.  Note that using $include or invoking the script without
# . does not set these variables.
# On exit, the variables cluster, thoruser and thorpassword are set.
. get_thor_options 

# -------------------------
while test "$thoruser" = ""
do
    read -p "Enter the username under which thor will run: " thoruser
    if test "$thoruser" = ""; then
        thoruser=(thor)
    fi
done
echo thor user=$thoruser

read -s -p "Enter password: " thorpasswd

#
read -p "Enter file name [slaves]: " fileName
if test "$fileName" == ""; then
    fileName=slaves
fi

COUNTER=1
for computer in `cat $fileName`; do
    echo sshing computer $COUNTER - $computer:
    echo ./pssh -o password=$THORPASSWD  $THORUSER@$computer $1
    ./pssh -o password=$THORPASSWD  $THORUSER@$computer $1
    let COUNTER=COUNTER+1
done

