#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

# Invoke the script to parse command line arguments and shift args
# past options.  Note that using $include or invoking the script without
# . does not set these variables.
# On exit, the variables cluster, thoruser and thorpassword are set.
. get_thor_options 

# -------------------------
while test "$thoruser" = ""
do
    read -p "Enter the username under which thor will run: " thoruser
    if test "$thoruser" = ""; then
        thoruser=(thor)
    fi
done
echo thor user=$thoruser

read -s -p "Enter password: " thorpasswd

#
read -p "Enter file name [slaves]: " fileName
if test "$fileName" == ""; then
    fileName=slaves
fi

echo

COUNTER=1
for computer in `cat $fileName`; do
    echo scping computer $COUNTER - $computer:
    echo pscp -o StrictHostKeyChecking=no -o password=$THORPASSWD  "$1" $THORUSER@$computer:"$2"
    pscp -o password=$THORPASSWD  "$1" $THORUSER@$computer:"$2"
    let COUNTER=COUNTER+1
done

