#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

export PATH=$PATH:.
if [ $# -lt 3 ]; then
    echo usage: $0 host rootpasswd nfsserver 
    exit 1
fi

HOSTADDR=$1
ROOTPASSWD=$2
NFSSERVER=$3

echo unmounting shared drive for $HOSTADDR...
pssh root@$HOSTADDR -o StrictHostKeyChecking=no -o password=$ROOTPASSWD "umount /thor; umount /mnt/lib; umount /mnt/usrlib; umount /mnt/bin; umount /mnt/usr/bin"

echo mounting directories /thor, /mnt/lib, /mnt/usr/lib ...
pssh root@$HOSTADDR -o StrictHostKeyChecking=no -o password=$ROOTPASSWD "mkdir /thor; mount $NFSSERVER:/thor /thor -o hard,intr; mkdir /mnt/lib; mount $NFSSERVER:/lib /mnt/lib -o hard,intr; mkdir /mnt/usrlib; mount $NFSSERVER:/usr/lib /mnt/usrlib -o hard,intr; mkdir /mnt/bin; mount $NFSSERVER:/bin /mnt/bin -o hard,intr; mkdir /mnt/usrbin; mount $NFSSERVER:/usr/bin /mnt/usrbin -o hard,intr;"

