#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

export PATH=$PATH:.
echo Enter the address nfsserver: 
read NFSSERVER 
if [ $NFSSERVER =  ]; then
    echo Please input nfsserver
    exit
fi
echo NFSSERVER=$NFSSERVER

echo -------------------------
echo Enter root password:
stty -echo
read ROOTPASSWD
stty echo

echo --------------------------
echo setup nfs for all thorslaves, continue? [n/y]
read yesno
if [ $yesno = 'y' ]; then
    for slave in $(cat slaves); do
        echo --------------------------
        echo slave $slave:
        setup_one_nfs $slave $ROOTPASSWD $NFSSERVER 
    done
fi

