#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

if [ $# -lt 1 ]; then
        echo usage: $0 thordeploydir 
        exit 1
fi

shift

export PATH_PRE=`type -path hpcc_setenv`
source ${PATH_PRE} ""
export PID_NAME="$PID/`basename $PWD`_master.pid" ## this needed when we use bash_init_system
export PID_NAME_BASE="$PID/`basename $PWD`.pid"

# this must match jsocket hard limit
export handlelimit=32768

# deploydir = where binaries and scripts live
if [ -z "$deploydir" ]; then
export deploydir=$(pwd -P)
fi
# instancedir = [cwd] - on legacy system would be same as deploydir
export instancedir=$(pwd -P)

. $instancedir/setvars


$deploydir/stop_thor $deploydir


# ----------------------------

ulimit -n $handlelimit
if [ `ulimit -n` -lt $handlelimit ]; then
    echo 'ulimit -n failed, aborting start_thor (perhaps you are not logged is as super user?)'
    exit 0
fi

if [ ! -z ${THORPRIMARY} ]; then
    export groupName=${THORPRIMARY}
else
    export groupName=${THORNAME}
fi
ln -s -f $deploydir/thormaster${LCR} thormaster_$THORNAME

ENV_DIR=`cat ${HPCC_CONFIG} | sed -n "/\[DEFAULT\]/,/\[/p" | grep "^configs=" | sed -e 's/^configs=//'`
export logdir=`updtdalienv $ENV_DIR/environment.xml -d log thor $THORNAME`
if [ -z "$logdir" ]; then
export logdir="./start_logs"
fi
mkdir -p $logdir
export logpthtail="`date +%m_%d_%Y_%H_%M_%S`"
$deploydir/run_thor >> $logdir/start_thor_$logpthtail.log 2>&1
