#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################

echo --------------------------
echo starting thorslaves ...

if [ "$localthor" = "true" ]; then
        ulimit -c unlimited
        ulimit -n 8192
        let "n = 1";
        for slave in $(cat $instancedir/thorgroup); do
            slaveport=${slave/*:/}
            if [ "$slaveport" = "" ]; then
                slaveport=$THORSLAVEPORT
            fi
            $deploydir/start_slave $n thorslave${LCR} $THORMASTER:$THORMASTERPORT $logdir $instancedir $slaveport $THORNAME $PATH_PRE $logdir/start_slave_$logpthtail.$n.log
            let "n += 1";
        done
else
        ## multislaves for bkwd compat. with old environments
        if [ ${slavespernode} -gt 1 ] || [ "$multislaves" = "true" ]; then
            let "n = 1";
            for slave in $(cat $instancedir/thorgroup); do
                ip=${slave/:*/}
                slaveport=${slave/*:/}
                if [ "$slaveport" = "" ]; then
                    slaveport=$THORSLAVEPORT
                fi
                logredirect="$logdir/start_slave_$logpthtail.$n.log"
                frunssh $ip "/bin/sh -c '$deploydir/start_slave $n thorslave${LCR} $THORMASTER:$THORMASTERPORT $logdir $instancedir $slaveport $THORNAME $PATH_PRE $logredirect'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries 2>&1 &
                let "n += 1";
            done
            wait
        else
            if [ -e $instancedir/thorgroup ]; then
                mv $instancedir/thorgroup $instancedir/thorgroup.local
            fi
            logredirect="$logdir/start_slave_$logpthtail.log"
            frunssh $instancedir/slaves "/bin/sh -c '$deploydir/start_slave %n thorslave${LCR} $THORMASTER:$THORMASTERPORT $logdir $instancedir $THORSLAVEPORT $THORNAME $PATH_PRE $logredirect'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries 2>&1
        fi
fi
echo thorslaves started

