#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################

slavenum=$1
prog=$2
master=$3
logpth=$4
instancedir=$5
slaveport=$6
hpcc_compname=$7
hpcc_setenv=$8
logredirect=$9

source ${hpcc_setenv}
PID_NAME="$PID/${hpcc_compname}_slave_${slavenum}.pid"

if [ $# -lt 9 ]; then
  echo usage: slavenum prog master logdir workingdir slaveport hpcc_compname hpcc_setenv logredirect
  exit 1
fi

sudo /etc/init.d/hpcc-init -c dafilesrv setup
mkdir -p $instancedir
mkdir -p `dirname $logredirect`
exec >>$logredirect 2>&1

cd $instancedir

echo "slave init `date`"

lckfile="$PID/start_slave_${hpcc_compname}_${slavenum}.pid"

# prevent two slaves starting together
while [ -e $lckfile ]; do
  echo waiting on lckfile: $lckfile
  oldpid=`cat $lckfile`
  if ps h $oldpid; then
     echo killing pid $oldpid start_slave
     kill -9 $oldpid
     rm $lckfile                   # just in case
     sleep 1
  else
     rm -f $lckfile
  fi
done
trap "rm -f $lckfile" exit
echo $$ > $lckfile

ulimit -c unlimited
ulimit -n 8192

echo "slave starting `date`"

echo $prog master=$master slave=.:$slaveport slavenum=$slavenum logDir=$logpth
$prog master=$master slave=.:$slaveport slavenum=$slavenum logDir=$logpth 2>/dev/null 1>/dev/null &
slavepid=$!
echo $slavepid > $PID_NAME
if [ "$slavepid" -eq "0" ]; then
  echo "failed to start at `date`"
else
  echo "slave pid $slavepid started `date`"
fi

