#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo --------------------------
echo starting thorslaves ...

if [ "$localthor" = "true" ]; then
        ulimit -c unlimited
        ulimit -n $handlelimit
        let "n = 1";
        for slave in $(cat $instancedir/thorgroup); do
            slaveport=${slave/*:/}
            if [ "$slaveport" = "" ]; then
                slaveport=$THORSLAVEPORT
            fi
            $deploydir/start_slave $n thorslave${LCR} $THORMASTER:$THORMASTERPORT $logdir $instancedir $slaveport $THORNAME $PATH_PRE $logdir/start_slave_$logpthtail.$n.log
            let "n += 1";
        done
else
        ## multislaves for bkwd compat. with old environments
        if [ ${slavespernode} -gt 1 ] || [ "$multislaves" = "true" ]; then
            let "n = 1";
            for slave in $(cat $instancedir/thorgroup); do
                ip=${slave/:*/}
                slaveport=${slave/*:/}
                if [ "$slaveport" = "" ]; then
                    slaveport=$THORSLAVEPORT
                fi
                logredirect="$logdir/start_slave_$logpthtail.$n.log"
                frunssh $ip "/bin/sh -c '$deploydir/start_slave $n thorslave${LCR} $THORMASTER:$THORMASTERPORT $logdir $instancedir $slaveport $THORNAME $PATH_PRE $logredirect'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries 2>&1 &
                let "n += 1";
            done
            wait
        else
            if [ -e $instancedir/thorgroup ]; then
                mv $instancedir/thorgroup $instancedir/thorgroup.local
            fi
            logredirect="$logdir/start_slave_$logpthtail.log"
            frunssh $instancedir/slaves "/bin/sh -c '$deploydir/start_slave %n thorslave${LCR} $THORMASTER:$THORMASTERPORT $logdir $instancedir $THORSLAVEPORT $THORNAME $PATH_PRE $logredirect'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries 2>&1
        fi
fi
echo thorslaves started

