#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

PATH_PRE=`type -path hpcc_setenv`
INSTALL_DIR=`dirname ${PATH_PRE}`/..
source  ${INSTALL_DIR}/etc/init.d/hpcc_common

source ${PATH_PRE} ""
export MASTER_PID_NAME="$PID/`basename $PWD`_master.pid" ## this needed when we use bash_init_system

which_pidof

if [ $# -lt 1 ]; then
    echo usage: $0 thordeploydir 
    exit 1
fi

export SENTINEL="thor.sentinel"

# deploydir = where binaries and scripts live
if [ -z "$deploydir" ]; then
export deploydir=$(pwd -P)
fi
# instancedir = [cwd] - on legacy system would be same as deploydir
export instancedir=$(pwd -P)

. $instancedir/setvars

if [ "$#" -lt "2" ] || [ "$2" != "keep_sentinel" ]; then
    echo removing sentinel file
    rm -f $instancedir/${SENTINEL}
    sleep 1
fi

masterpid=`cat ${MASTER_PID_NAME} 2> /dev/null`
if [ ! -z $masterpid ]; then
  while :
  do
    kill -0 $masterpid >& /dev/null
    masterRunning=$(( $? == 0 ? 1 : 0 ))
    if [ 0 == $masterRunning ]; then
      break
    fi
    echo --------------------------
    echo stopping thormaster $THORMASTER 
    kill $masterpid >& /dev/null
    sleep 8
    kill -9 $masterpid >& /dev/null
    sleep 1
  done
fi

echo --------------------------
echo stopping thor slaves 

SLAVE_PID_NAME="$PID/${hpcc_compname}_slave_${slavenum}.pid"
if [ "$localthor" = "true" ]; then
    slavepid=`cat ${SLAVE_PID_NAME} 2> /dev/null`
    kill -9 $slavepid > /dev/null
else
    # use 20 threads
    # timeout of 60 seconds (in case slave busy)
    # hard kill (called after master down anyway so going to stall)
    if [ ! -r $instancedir/slaves ]; then
        if [ ! -z ${THORPRIMARY} ]; then
            groupName=${THORPRIMARY}
        else
            groupName=${THORNAME}
        fi
        daliadmin $DALISERVER dfsgroup ${groupName} > $instancedir/slaves
        errcode=$?
        if [ 0 != ${errcode} ]; then
            echo 'failed to lookup dali group for $groupName'
            exit 1
        fi
    fi
    $deploydir/frunssh uniq $instancedir/slaves "/bin/sh -c '$deploydir/stop_slaves ${hpcc_compname} $PATH_PRE'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries 2>&1 | egrep -v "no process killed"
    echo slaves stopped
fi

