#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################

hpcc_compname=$1
hpcc_setenv=$2
master=$3

source ${hpcc_setenv}

echo PID=${PID}
echo hpcc_compname=${hpcc_compname}
echo master=${master}

for file in $(ls $PID/${hpcc_compname}_slave_*.pid)
do
  apid=`cat ${file}`
  echo pid = ${apid}
  slavecmdline=`cat /proc/${apid}/cmdline`
  psline=`echo ${slavecmdline} | grep ${master}`
  if [ ! -z "${psline}" ]
  then
    echo Process cmdline = `cat /proc/${apid}/cmdline`
    echo kill -9 ${apid}
    kill -9 ${apid} # > /dev/null
  fi
done
echo rm -f $PID/${hpcc_compname}_slave_*.pid
rm -f $PID/${hpcc_compname}_slave_*.pid
