#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

hpcc_compname=$1
hpcc_setenv=$2
master=$3

source ${hpcc_setenv}

echo PID=${PID}
echo hpcc_compname=${hpcc_compname}
echo master=${master}

for file in $(ls $PID/${hpcc_compname}_slave_*.pid)
do
  apid=`cat ${file}`
  echo pid = ${apid}
  slavecmdline=`cat /proc/${apid}/cmdline`
  psline=`echo ${slavecmdline} | grep ${master}`
  if [ ! -z "${psline}" ]
  then
    echo Process cmdline = `cat /proc/${apid}/cmdline`
    echo kill -9 ${apid}
    kill -9 ${apid} # > /dev/null
  fi
done
echo rm -f $PID/${hpcc_compname}_slave_*.pid
rm -f $PID/${hpcc_compname}_slave_*.pid
