{{- range $plane := .Values.planes -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s-pvc" $plane.name (include "hpcc-azurefile.fullname" $) }}
spec:
  accessModes:
    - {{ $plane.rwmany | default false | ternary "ReadWriteMany" "ReadWriteOnce" }}
  storageClassName: {{ include "hpcc-azurefile.SCName" (dict "root" $ "plane" $plane) | default "" | quote  }}
  resources:
    requests:
      storage: {{ $plane.size }}
{{ include "hpcc-azurefile.addPVSelector" (dict "root" $ "plane" $plane) | indent 2 }}
---
{{ end }}
