export = {
    Abort: "Prekinite",
    AbortedBy: "Prekinuto od strane",
    AbortedTime: "Vrijeme prekida",
    AbortSelectedWorkunits: "Želite li zaustaviti odabrane radne jedinice? Vaš ID za prijavu bit će zabilježen za ovu radnju unutar odabranih radnih jedinica.",
    About: "O Aplikaciji",
    AboutGraphControl: "O Grafičkoj Kontroli",
    AboutHPCCSystems: "O tvrtki HPCC Systems®",
    AboutHPCCSystemsGraphControl: "O Grafičkoj Kontroli HPCC Sistema",
    AboutToLoseSessionInformation: "Odjavit ćete se i izgubit ćete sve informacije o sesiji. Želite li nastaviti?",
    Account: "Račun",
    AccountDisabled: "Račun onemogućen. Kontaktirajte administratora sustava.",
    Action: "Akcija",
    Activate: "Aktivirajte",
    Activated: "Aktiviran",
    ActivateQuery: "Aktivirajte Upit",
    ActivateQueryDeletePrevious: "Aktivirajte upit, izbrišite prethodni",
    ActivateQuerySuspendPrevious: "Aktivirajte upit, obustavite prethodni",
    Active: "Aktivan",
    ActivePackageMap: "Aktivna Mapa Paketa",
    ActiveWorkunit: "Aktivna Radna Jedinica",
    Activities: "Aktivnosti",
    Activity: "Aktivnost",
    ActivityLabel: "Oznaka aktivnosti",
    ActivityMap: "Mapa Aktivnosti",
    ActualSize: "Tačna Veličina",
    Add: "Dodajte",
    AddAttributes: "Dodajte atribute/vrijednosti vašem metodu",
    AddAttributes2: "Dodajte Atribut(e)",
    AddBinding: "Dodajte Vezivanje",
    AddFile: "Dodajte Datoteku",
    AddGroup: "Dodajte Grupu",
    AdditionalResources: "Dodatni Resursi",
    AddPart: "Dodajte Dio",
    AddProcessMap: "Dodajte Mapu Paketa",
    AddResource: "Dodaj resurs",
    AddTheseFilesToDali: "Dodajte Te Datoteke Na Dali",
    AddtionalProcessesToFilter: "Dodatni Procesi Za Filtriranje",
    AddToExistingSuperfile: "Dodajte na postojeći superfile",
    AddToFavorites: "Dodaj u favorite",
    AddToSuperfile: "Dodajte na Superdatoteku",
    AddUser: "Dodajte Korisnika",
    Advanced: "Višeg Nivoa",
    Age: "Dob",
    All: "Svi",
    AllowAccess: "Dozvolite Pristup",
    AllowForeignFiles: "Dozvolite Korištenje  Datoteka Sa Drugih Klastera",
    AllowFull: "Dozvolite Potpun",
    AllowRead: "Dozvolite Čitanje",
    AllowWrite: "Dozvolite Pisanje",
    AllQueries: "Svi Upiti",
    AllQueuedItemsCleared: "Svi poslovi iz reda čekanja su očišćeni. Trenutno aktivni posao nastavnja sa izvršavanjem.",
    Analyze: "Analizirajte",
    ANY: "Bilo Koji",
    AnyAdditionalProcessesToFilter: "Ima li još procesa za filtriranje",
    Append: "Dodajte",
    AppendCluster: "Dodajte Klaster",
    Apply: "Primjenite",
    Apps: "Aplikacije",
    ArchiveDFUWorkunit: "Arhiviraj radnu jedinicu DFU",
    ArchivedOnly: "Samo Arhiviran",
    ArchivedWarning: "Upozorenje: koristite kratak vremenski period. Ako koristite duži vremenski period, pretraživanje radnih jedinica može trajati duže od dozviljenog vremena za pretraživanje .",
    ArchiveECLWorkunit: "Arhiviraj radnu jedinicu ECL",
    AreYouSureYouWantToResetTheme: "Jeste li sigurni da se želite vratiti na zadanu temu",
    Attach: "Prikačite",
    Attribute: "Atribut",
    AttributesAreRequired: "Atributi su potrebni",
    Audience: "Publika",
    Audit: "Provjera",
    AuditLogs: "Dnevnik Za Pregled",
    AutoRefresh: "Osvježi",
    AutoRefreshEvery: "Automatsko osvježivanje svakih x minuta",
    AutoRefreshIncrement: "Automatski korak osvježivanja",
    Back: "Natrag",
    BackupDFUWorkunit: "Sigurnosna DFU radna jedinica",
    BackupECLWorkunit: "Sigurnosna ECL radna jedinica", 
    BannerColor: "Boja Reklamnog Bloka",
    BannerColorTooltip: "Promijenite boju pozadine gornje navigacije",
    BannerMessage: "Poruka za Reklamni Blok",
    BannerMessageTooltip: 'Promijenite naslov prikazan u gornjoj navigaciji (default "ECL Watch")',
    BannerScroll: "Kretanje Reklamnog Bloka",
    BannerSize: "Veličina Reklamnog Bloka",
    BinaryInstalls: "Binarne Instalacije",
    Bind: "Vežite",
    Binding: "Vezivanje",
    BindingDeleted: "Vezivanje Obrisano",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefiks",
    Blobs: "Blobovi",
    Blooms: "Blums",
    Bottom: "Kraj",
    BoundBy: "ograničen sa:",
    Branches: "Grane",
    BrowserStats: "Statistika Preglednika",
    BuildDate: "Datum gradnje",
    Busy: "Zauzet",
    CallerID: "ID Pozivatelja",
    Cancel: "Poništite",
    CancelAll: "Ukinite Sve",
    CancelAllMessage: "Prekinite tekuće poslove i očistite red čekanja. Želite li nastaviti?",
    Category: "Kategorija",
    Channel: "Kanal",
    Chart: "Grafikon",
    CheckAllNodes: "Provjerite Sve Nodove/Čvorove",
    CheckFilePermissions: "Provjerite Dozvole za Pristup Datoteci",
    CheckSingleNode: "Provjerite Jedan Nod/Čvor",
    Class: "Klasa",
    Clear: "Očistite",
    ClearPermissionsCache: "Izbrišite Zapamćene Dozvole Za Pristup",
    ClearPermissionsCacheConfirm: "Da li ste sigurni da želite da izbrišete zapamćene dozvole za pristup na DALI i ESP? To može značajno usporiti izvršavanje radnih jedinica.",
    Client: "Klijent",
    Clone: "Klonirajte",
    ClonedWUID: "Klonirani WUID",
    CloneTooltip: "Kopirajte Radnu Jedinicu",
    Close: "Zatvorite",
    CloseModal: "Zatvori modal",
    Cluster: "Klaster",
    ClusterName: "Ime Klastera",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesi Na Klasteru",
    Code: "Kod",
    CodeGenerator: "Kod Generator",
    Col: "Kolona",
    CollapseAll: "Suzite sve",
    ColumnMode: "Način rada za stupce",
    Columns: "Kolone",
    Command: "Komanda",
    Comment: "Komentar",
    Compilation: "Kompilacija",
    CompileCost: "Trošak kompilacije",
    Compiled: "Kompajlirano",
    Compiling: "U procesu kompajliranja",
    Completed: "Kompletiran",
    ComplexityWarning: "Više od praga {threshold} aktivnosti ({activityCount}) - prekinite prikaz podataka?",
    Component: "Komponenta",
    ComponentLogs: "Dnevnik Komponenti",
    Components: "Komponente",
    Compress: "Sabijte",
    Compressed: "Komprimirani",
    CompressedFileSize: "Komprimirana Veličina Datoteke",
    CompressedSize: "Komprimirana veličina",
    Compression: "Kompresija",
    ComputerUpTime: "Vrijeme Rada Računala",
    Condition: "Uslov",
    Configuration: "Konfiguracija",
    ConfigureService: "Servis za Konfiguraciju",
    ConfirmPassword: "Potvrdite Lozinku",
    ConfirmRemoval: "Jeste li sigurni da to želite učiniti?",
    ConnectionID: "Identifikator Veze",
    ContactAdmin: "Ako želite promijeniti naziv ove grupe, kontaktirajte administratora LDAP.",
    Container: "Kontejner",
    ContainerName: "Naziv Kontejnera",
    Content: "Sadržaj",
    Contents: "Sadržaji",
    ContentType: "Vrsta Sadržaja",
    ContinueWorking: "Nastavite sa radom",
    Cookies: "Kolačići",
    CookiesAcceptButtonText: "Dopusti kolačiće",
    CookiesNoticeLinkText: "Naša obavijest o kolačićima",
    Copied: "Kopirano!",
    Copy: "Kopirajte",
    CopyLogicalFilename: "Kopirajte naziv logičke datoteke",
    CopyLogicalFiles: "Kopirajte logičke datoteke u međuspremnik",
    CopyOpenTelemetry: "Kopiraj otvorenu telemetriju",
    CopySelectionToClipboard: "Kopirajte odabir u međuspremnik",
    CopyToClipboard: "Kopirajte u međuspremnik",
    CopyURLToClipboard: "Kopirajte URL u međuspremnik",
    CopyWUID: "Kopirajte WUID",
    CopyWUIDs: "Kopiraj WUID-ove u međuspremnik",
    CopyWUIDToClipboard: "Kopirajte WUID u međuspremnik",
    Cost: "Cijena",
    Costs: "Cijena",
    Count: "Izbrojte",
    CountFailed: "Brojanje nije uspjelo",
    CountTotal: "Ukupan broj",
    CPULoad: "Učitavanje CPU-a",
    Create: "Izradite",
    CreateANewFile: "Kreirajte novi superfile",
    Created: "Proizveden",
    CreatedBy: "Autor",
    CreatedByWorkunit: "Kreiran sa Radnom Jedinicom",
    CreatedTime: "Vrijeme Izrade",
    Creating: "U procesu stvaranja",
    Critical: "Kritično",
    CrossTab: "Kros Tab",
    CSV: "CSV",
    CustomLogColumns: "Stupci za specijalizirane upise",
    Dali: "Dali",
    DaliAdmin: "Dali Administrator",
    DaliIP: "Dali IP Adresa",
    DaliPromptConfirm: "Jeste li sigurni? Dali Admin podnesci su trajni i ne mogu se poništiti.",
    Dashboard: "Nadzorna ploča",
    Data: "Podaci",
    DataPatterns: "Uzorci podataka",
    DataPatternsDefnNotFound: "Definicija datoteke nije pronađena. Uzorci podataka se ne mogu analizirati",
    DataPatternsNotStarted: "Rezultati analize nisu pronađeni. Za početak nove analize pritisnite dugme Analiza.",
    DataPatternsStarted: "Analiza je u toku. Po završetku kompletan izveštaj će biti ovdje prikazan.",
    dataset: ":=dataset*",
    Date: "Datum",
    Day: "Dan",
    Deactivate: "Isključite",
    Debug: "Otklonite Neispravnosti",
    DEF: "DEF",
    Default: "Zadano",
    Defaults: "Unaprijed Definisane Vrijednosti",
    Definition: "Definicija",
    DefinitionDeleted: "Definicija je izbrisana",
    DefinitionID: "ID",
    Definitions: "Definicije",
    DelayedReplication: "Odgođena replikacija",
    Delete: "Obrišite",
    DeleteBinding: "Izbrišite Vezivanje",
    Deleted: "Obrisan",
    DeletedBinding: "Izbrisano Vezivanje",
    DeleteDirectories: "Eliminišite prazne direktirije. Želite li nastaviti?",
    DeleteEmptyDirectories: "Želite li izbrisati prazne direktorije?",
    DeletePrevious: "Izbrišite Prethodni",
    DeleteSelectedDefinitions: "Želite izbrisati izabrane definicije?",
    DeleteSelectedFiles: "Obrišite Odabrane Datoteke?",
    DeleteSelectedGroups: "Obrišite odabranu(e) grupu(e)?",
    DeleteSelectedPackages: "Želite li izbrisati odabrane pakete?",
    DeleteSelectedPermissions: "Obrišite Odabrane Dozvole Za Pristup",
    DeleteSelectedQueries: "Obrišite Odabrane Zahtjeve?",
    DeleteSelectedUsers: "Obrišite Odabrane Korisnike?",
    DeleteSelectedWorkunits: "Obrišite Odabrane Radne Jedinice?",
    DeleteSuperfile: "Obrišite Superdatoteke?",
    DeleteSuperfile2: "Obrišite Super Datoteku",
    DeleteThisPackage: "Obrišite ovaj paket?",
    Delimited: "Razgraničen",
    DenyAccess: "Zabranite Pristup",
    DenyFull: "Zabranite Potpun",
    DenyRead: "Zabranite Čitanje",
    DenyWrite: "Zabranite Pisanje",
    Depth: "Dubina",
    DepthTooltip: "&lsquo;Najveća Dubina Podgrafa",
    Deschedule: "Izbacite Is Reda Za Izvršavanje",
    DescheduleSelectedWorkunits: "Izbacite Odabrane Radne Jedinice Is Reda Za Izvršavanje?",
    Description: "Opis",
    DESDL: "Dinamički ESDL",
    Despray: "Ponovo Objedinite Datoteku",
    Details: "Detalji",
    DFSCheck: "DFS provjera",
    DFSExists: "DFS postoji",
    DFSLS: "DFS LS",
    DFUServerName: "Ime DFU Servera",
    DFUWorkunit: "DFU RadnaJedinica",
    Directories: "Direktorije",
    Directory: "Direktorij",
    DisableScopeScanConfirm: "Da li ste sigurni da želite da onemogućite skaniranje opsega? Promjene će biti prihvaćene poslije restarta DALIja",
    DisableScopeScans: "Onemogućite Skaniranje Opsega",
    DiskSize: "Veličina diska",
    DiskUsage: "Iskorištenost Diska",
    Distance: "Razdaljina",
    DistanceTooltip: "Maksimalna Veličina Podgrafa Za Odabranu Aktivnost",
    Dll: "Dll",
    Documentation: "Dokumentacija",
    Domain: "Domen",
    DoNotActivateQuery: "Nemojte aktivirati upit",
    DoNotRepublish: "Nemojte ponoviti upit?",
    DOT: "DOT",
    DOTAttributes: "DOT Atributi",
    Down: "Neaktivan",
    Download: "Dobavite",
    Downloads: "Preuzimanje",
    DownloadSelectionAsCSV: "Preuzmite odabir kao CSV",
    DownloadToCSV: "Preuzmite u CSV formatu",
    DownloadToCSVNonFlatWarning: "Napomena: preuzimanje datoteka koje sadrže ugniježđene skupove podataka kao podatke odvojene zarezima možda neće biti formatirane kako se očekuje",
    DownloadToDOT: "Preuzmi na DOT",
    DropZone: "Zona Prijema",
    DueToInctivity: "Bit ćete odjavljeni iz svih ECL Watch sjednica za 3 minute zbog neaktivnosti.",
    Duration: "Trajanje",
    DynamicNoServicesFound: "Servisi Nisu Pronađeni",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWatchRequiresCookies: "ECL Watch zahtijeva da kolačići budu omogućeni za nastavak",
    ECLWatchSessionManagement: "Upravljanje ECL Watchom",
    ECLWatchVersion: "ECL Watch verzija",
    ECLWorkunit: "ECL RadnaJedinica",
    EdgeLabel: "Oznaka ruba",
    Edges: "Ivice",
    Edit: "Editujte",
    EditDOT: "Editujte DOT",
    EditGraphAttributes: "Editujte Atribute Grafova",
    EditXGMML: "Editujte XGMML",
    EmailBody: "Sadržaj e-pošte",
    EmailFrom: "Adresa e-pošte (pošiljatelj)",
    EmailSubject: "Predmet e-pošte",
    EmailTo: "Adresa e-pošte (primalac)",
    EmployeeID: "ID Zaposlenika",
    EmployeeNumber: "Broj Zaposlenika",
    Empty: "(Prazan)",
    Enable: "Omogućite",
    EnableBannerText: "Aktivirajte Tekst",
    EnableScopeScans: "Omogućite Skaniranje Opsega",
    EnableScopeScansConfirm: "Da li ste sigurni da želite da omogućite skaniranje opsega? Promjene će biti prihvaćene poslije restarta DALIja",
    EndPoint: "Krajnja točka",
    EndTime: "Vrijeme završetka",
    EnglishQ: "Engleski?",
    EnterAPercentage: "Unesite procenat",
    EnterAPercentageOrMB: "Unesite Procenat ili MB",
    EraseHistory: "Brišite Povijest",
    EraseHistoryQ: "Brišite Povijest Za",
    Error: "Greška",
    Errorparsingserverresult: "Greška u analizi rezultata sa servera",
    Errors: "Greške",
    ErrorsStatus: "Greške/Stanje",
    ErrorUploadingFile: "Pogreška prilikom prenosa datoteke(a). Pokušajte provjeriti dozvole za prenos.",
    ErrorWarnings: "Greška/Upozorenja",
    Escape: "Eskejp",
    ESPBindings: "ESP Veze",
    ESPBuildVersion: "ESP Trenutna Verzija",
    ESPNetworkAddress: "ESP Netvork Adresa",
    ESPProcessName: "Naziv ESP procesa",
    EventName: "Ime Događaja",
    EventNamePH: "imedogađaja",
    EventScheduler: "Raspoređivač Događaja",
    EventText: "Opis Događaja",
    EventTextPH: "Tekst O Događaju",
    Exception: "Neočekivani Problem",
    ExcludeIndexes: "Isključi indekse",
    ExecuteCost: "Cijena izvršenja",
    Executed: "Izvršeno",
    Executing: "U procesu izvršenja",
    ExpandAll: "Proširite sve",
    ExpirationDate: "Datum Isteka",
    ExpireDays: "Istječe za (u danima)",
    Export: "Izvezite",
    ExportSelectionsToList: "Izvezite Odabrane Stvari u Listu",
    FactoryReset: "Vraćanje na tvorničke postavke",
    FailIfNoSourceFile: "Neuspjeh Ukoliko Datoteka Ne Postoji",
    Fatal: "Fatalan",
    Favorites: "Favoriti",
    Fetched: "Preuzet",
    FetchingData: "U Procesu Dobavljnja Podataka...",
    fetchingresults: "dobijeni resultati",
    FieldNames: "Imena Stupaca",
    File: "Datoteka",
    FileAccessCost: "Cijena pristupa datoteci",
    FileCluster: "Klaster Datoteka",
    FileCostAtRest: "Cijena datoteke u mirovanju",
    FileCounts: "Broj Datoteka",
    FileName: "Ime Datoteke",
    FileParts: "Dio Datoteke",
    FilePath: "Lokacija Datoteke",
    FilePermission: "Dozvola Za Pristup Datoteci",
    FilePermissionError: "Došlo je do pogreške prilikom pristupa fajlu sa dozvolama",
    Files: "Datoteke",
    FileScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor Datoteka",
    FileScopes: "Skop Datoteka",
    FileSize: "Veličina Datoteke",
    FilesNoPackage: "Datoteke koje ne pripadaju paketu",
    FilesPending: "Datoteke na čekanju",
    FilesWarning: "Broj vraćenih datoteka je preveliki. Vraćeno je samo prvih 100.000 datoteka sortiranih po datumu / vremenu. Ako želite ograničiti rezultate, podesite filter.",
    FilesWithUnknownSize: "Datoteke Sa Nepoznatim Veličinama",
    FileType: "Tip Datoteke",
    FileUploader: "Proces za premiještanje Datoteke na Server (Uploader)",
    FileUploadStillInProgress: "Učitavanje Datoteka je u Toku",
    Filter: "Filter",
    FilterDetails: "Opis Filtera",
    FilterMetricsTooltip: "Ovo će se prema zadanim postavkama filtrirati na temelju stupca \"Scope\". Za filtriranje bilo kojeg drugog stupca upotrijebite naziv stupca kao prefiks za pretraživanje, npr.: \"Naziv datoteke: Spill\"",
    FilterSet: "Definisanje Filtera",
    Find: "Nađite",
    FindNext: "Nađite Slijedeći",
    FindPrevious: "Nađite Prethodni",
    Finished: "Završen",
    FirstN: "Prvih N",
    FirstName: "Ime",
    FirstNRows: "Prvih N Redova",
    FirstNSortBy: "Poredajte po",
    Fixed: "Fiksni",
    Folder: "Fascikla",
    Form: "Forma",
    Format: "Format",
    Forums: "Forumi",
    Forward: "Naprijed",
    FoundFile: "Datoteka je Pronađena",
    FoundFileMessage: "Pronađena datoteka ima sve svoje dijelove na disku, ali dijelovi nisu poznati Dali serveru. Svi dijelovi datoteke mogu biti dodani natrag na Dali server. Dijelovi mogu biti I obrisani sa klastera ako je to neophodno..",
    FromDate: "Od Datuma",
    FromSizes: "Od Veličine",
    FromTime: "Od Vremena",
    FullName: "Ime i Prezime",
    Generate: "Generirajte",
    GetDFSCSV: "DFS CSV",
    GetDFSMap: "DFS Mapa",
    GetDFSParents: "DFS Roditelji",
    GetLastServerMessage: "Dohvati posljednju poruku poslužitelja",
    GetLogicalFile: "Logička Datoteka",
    GetLogicalFilePart: "Logički Dio Datoteke",
    GetPart: "Dobavite Dio",
    GetProtectedList: "Zaštićeni Popis",
    GetSoftwareInformation: "Želite li dobiti informacije o softveru",
    GetValue: "Vrijednost",
    GetVersion: "Preuzmi verziju",
    Graph: "Graf",
    GraphControl: "Kontrola Grafikona",
    Graphs: "Grafikoni",
    GraphView: "Slika Grafikona",
    GridAbortMessage: "Grid prekida zastarjeli zahtjev",
    Group: "Grupa",
    GroupBy: "Grupišite Po",
    GroupDetails: "Detalji o Grupi",
    Grouping: "Grupisanje",
    GroupName: "Naziv Grupe",
    GroupPermissions: "Dozvole za Pristup Grupe",
    Groups: "Grupe",
    GZip: "GZip",
    help: "Ovdje je prikazan grafikon izvršavanja ove radne jedinice. Veličina i nijansa ukazuju na vrijeme izvršavanja svakog grafikona (Veći i tamniji grafikon uzima veći procenat cjelokupnog vremena izvrštavanja.)",
    Helper: "Pomoćnik",
    Helpers: "Pomagači",
    Hex: "Baza16",
    HideSpills: "Sakrijte Upotrebu Diska",
    High: "Visok",
    History: "Istorija",
    Homepage: "Početna stranica",
    Hotspots: "Pristupne Točke Internetu",
    HPCCSystems: "HPCC Systems®",
    HTML: "HTML",
    Icon: "Ikona",
    ID: "Identifikator",
    IFrameErrorMsg: "Podaci se ne mogu učitati, pokušajte ponovno.",
    IgnoreGlobalStoreOutEdges: "Zanemarite globalne rubove",
    Import: "Uvoz",
    Inactive: "Neaktivan",
    IncludePendingItems: "Uključi stavke na čekanju",
    IncludePerComponentLogs: "Uključite zapise po komponenti",
    IncludeRelatedLogs: "Uključite relevantne zapise",
    IncludeSlaveLogs: "Uključite Izvještaje Sa Nodova Izvršilaca",
    IncludeSubFileInfo: "Uključiti informacije o poddatoteci?",
    Index: "Indeks",
    Indexes: "Indeksi",
    IndexesOnly: "Samo Indeksi",
    Info: "Informacija",
    InfoDialog: "Dijalog Informacije",
    Informational: "Informativan",
    Infos: "Podaci",
    InheritedPermissions: "Naslijeđene Dozvole",
    Inputs: "Unosi",
    InUse: "U uporabi",
    InvalidResponse: "(Neispravan Odgovor)",
    InvalidUsernamePassword: "Nevažeće korisničko ime ili zaporka, pokušajte ponovo.",
    IP: "IP",
    IPAddress: "IP Adresa",
    IsCompressed: "Je li Komprimiran",
    IsLibrary: "Jeli Biblioteka",
    IsReplicated: "Repliciran",
    IssueReporting: "Izvještavanje o Problemima",
    JobID: "ID posla",
    JobName: "Naziv Radne Jedinice",
    Jobname: "Nazivradnejedinice",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    KeyFile: "Indeksirana Datoteka",
    KeyType: "Vrsta ključa",
    Label: "Etiketa",
    LandingZone: "Zona za Pretovar",
    LandingZones: "Zone za Pretovar",
    LanguageFiles: "Datoteke O Jeziku",
    Largest: "Najveći",
    LargestFile: "Najveća Datoteka",
    LargestSize: "Najveća veličina",
    LastAccessed: "Zadnji pristup",
    LastEdit: "Posljednja Izmjena",
    LastEditedBy: "Autor Zadnje Izmjene",
    LastEditTime: "Vrijeme Posljednje Izmjene",
    LastMessage: "Zadnja Poruka",
    LastName: "Prezime",
    LastNDays: "Poslijednjih N Dana",
    LastNHours: "Posljednjih N Sati",
    LastNRows: "Posljednjih N Redova",
    LastRun: "Zadnji Ran",
    LatestReleases: "Najnovija izdanja",
    Layout: "Raspored",
    LDAPWarning: "<b>Greška LDAP Servica:</b>  &lsquo;Previše korisnika&rsquo; - Molimo koristite filter.",
    LearnMore: "Naučite više",
    Leaves: "Listovi",
    LegacyForm: "Stari Prevaziđeni Formular",
    LegacyGraphLayout: "Stari grafički raspored",
    LegacyGraphWidget: "Stari grafički simbol",
    Legend: "Legenda",
    Length: "Duljina",
    LibrariesUsed: "Biblioteke u Korištenju",
    LibraryName: "Ime Biblioteke",
    Limit: "Ograniči",
    Line: "Linija",
    LineTerminators: "Krajevi Linija",
    Links: "Linkovi",
    Loading: "Učitavanje...",
    LoadingCachedLayout: "Učitavanje Keširane Strukture (Cached Layout)...",
    LoadingData: "Učitavanje Podataka...",
    loadingMessage: "...Učitavanje...",
    LoadPackageContentHere: "(Dobavite ovamo sadržaj paketa)",
    LoadPackageFromFile: "Dobavite Paket iz Datoteke",
    Local: "Lokalni",
    LocalFileSystemsOnly: "Samo Lokalni File Sistemi",
    Location: "Lokacija",
    Lock: "Zaključaj",
    log_analysis_1: "log_analysis_1*",
    Log: "Dnevnik (Log)",
    LogAccess_GenericException: "ws_logaccess::GetLogAccessInfo, dogodila se iznimka.",
    LogAccess_LoggingNotConfigured: "Stroj za bilježenje nije konfiguriran.",
    LogAccessType: "Vrsta pristupa zapisniku",
    LogDirectory: "Direktori za logiranje podataka",
    LogEventType: "Upišite vrstu događaja",
    LogFile: "Datoteka Aktivnosti",
    LogFilterComponentsFilterTooltip: "Uključite zapise samo iz odabrane komponente/kontejnera",
    LogFilterCustomColumnsTooltip: "Uključite navedene stupce dnevnika",
    LogFilterEndDateTooltip: "Uključite retke dnevnika u okviru datog vremenskog raspona",
    LogFilterEventTypeTooltip: "Uključite samo upise za dati tip događaja",
    LogFilterFormatTooltip: "Format log dnevnika: CSV, JSON ili XML",
    LogFilterLineLimitTooltip: "Broj redaka log dnevnika koji treba uključiti",
    LogFilterLineStartFromTooltip: "Uključite retke log dnevnika koji počinju od ovog broja reda",
    LogFilterRelativeTimeRangeTooltip: "Vremenski raspon koji okružuje vrijeme radne jedinice (WU), +/- (u sekundama)",
    LogFilters: "Filteri za log dnevnik",
    LogFilterSelectColumnModeTooltip: "Navedite koj stupci treba uključiti u log fajl",
    LogFilterSortByTooltip: "ASC - najstariji prvo, DESC - prvo najnoviji",
    LogFilterStartDateTooltip: "Uključite redke log dnevnika od početka datog vremenskog raspona",
    LogFilterTimeRequired: 'Odaberite ili "Od i do datuma" ili "Relativni vremenski raspon"',
    LogFilterWildcardFilterTooltip: "Tekst koje se koristi za filtriranje log dnevnika",
    LogFormat: "Format log dnevnika",
    LoggedInAs: "Prijavljen kao",
    LoggingOut: "Odjavljivanje",
    LogicalFile: "Logička Datoteka",
    LogicalFiles: "Logičke Datoteke",
    LogicalFilesAndSuperfiles: "Logičke Datoteke i Superdatoteke",
    LogicalFilesOnly: "Samo Logičke Datoteke",
    LogicalFileType: "Tip Logičke Datoteke",
    LogicalName: "Ime Logičke Datoteke",
    LogicalNameMask: "Maska Logičkog Imena",
    Login: "Prijavljivanje",
    LogLineLimit: "Ograničenje broja redaka log dnevnika",
    LogLineStartFrom: "Početni red za pisanje u log dnevnik",
    Logout: "Odjavite se",
    Logs: "Dnevnici",
    LogsDisabled: "Zapisivanje onemogućeno",
    LogVisualization: "Registrujte Vizuelizaciju",
    LogVisualizationUnconfigured: "Vizualizacija logotipa nije konfigurirana, provjerite kako je konfiguriran upravitelj konfiguracije",
    LostFile: "Izgubljena Datoteka",
    LostFile2: "Izgubljene Datoteke",
    LostFileMessage: "Logička datoteka kojoj nedostaje bar jedan dio ili na primarnoj ili na repliciranoj lokaciji na disku.  Logička datoteka je još uvijek pod kontrolom Dali servera. Brisanje datoteke uklanja kontrolu Dali servera nad datotekom kao i nad svim preostalim dijelovima datoteke na disku.",
    Low: "Nizak",
    MachineInformation: "Informacija o Mašini",
    Machines: "Mašine",
    Major: "Glavni",
    ManagedBy: "Upravljan",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Pritisnite Ctrl+C",
    ManualOverviewSelection: "Nophodno Je Selektirati Pregled",
    ManualTreeSelection: "Nophodno Je Selektirati Drvo",
    Mappings: "Mapiranja",
    Mask: "Maska",
    MatchCase: "Koordinirajte velika i mala slova",
    Max: "Maksimum",
    MaxConnections: "Maksimalni broj veza",
    MaximizeRestore: "Maksimiziraj/Povrati prethodno stanje",
    MaximumNumberOfSlaves: "Maksimalan Broj Izvršilaca",
    MaxNode: "Maksimalni Nod/čvor",
    MaxRecordLength: "Maksimalna Dužina Rekorda",
    MaxSize: "Maksimalna Veličina",
    MaxSkew: "Maksimalni Skju (Distorzija)",
    MaxSkewPart: "Maksimalan Skju Dio",
    Mean: "Srednja Vrijednost",
    MeanBytesOut: "Srednji broj bajtova",
    MemberOf: "Član Od",
    Members: "Članovi",
    MemorySize: "Veličina memorije",
    Message: "Poruke",
    MethodConfiguration: "Konfiguracija metode",
    Methods: "Metodi",
    MetricOptions: "Metričke opcije",
    Metrics: "Metrike",
    MetricsGraph: "Mjerni podaci / grafikon",
    MetricsSQL: "Mjerni podaci (SQL)",
    Min: "Minimum",
    Mine: "Moj",
    MinNode: "Minimalni Nod/čvor",
    Minor: "Minoran",
    MinSize: "Minimalna Veličina",
    MinSkew: "Minimalni Skju (Distorzija)",
    MinSkewPart: "Minimalan Skju Dio",
    Missing: "Nedostaje",
    MixedNodeStates: "Svi Nodovi Nemaju Isti Status",
    Modification: "Promijena",
    Modified: "Modifikovan",
    ModifiedUTCGMT: "Promijenjen (UTC/GMT)",
    Modify: "Promijeni",
    MonitorEventName: "Nadgledajte Ime Događaja",
    Monitoring: "Nadgledanje",
    MonitorShotLimit: "Nadgledajte Shot Limit",
    MonitorSub: "Nadgledajte Sub",
    Month: "Mjesec",
    More: "Nastavite",
    Move: "Premjestite",
    MustContainUppercaseAndSymbol: "Mora uključiti veliko slovo i simbol",
    NA: "N/A",
    Name: "Ime",
    NameOfEnvironment: "Ime Okruženja",
    NamePrefix: "Prefiks Imena",
    NamePrefixPlaceholder: "some::prefix",
    NetworkAddress: "Netvork Adresa",
    Newest: "Najnoviji",
    NewPassword: "Nova Lozinka",
    NextSelection: "Sljedeći Odabir",
    NextWorkunit: "Sljedeća radna jedinica",
    NoCommon: "Nema uobičajenog",
    NoContent: "(Bez sadržaja)",
    NoContentPleaseSelectItem: "Nema sadržaja - odaberite stavku",
    noDataMessage: "...Nema Redova...",
    Node: "Čvor (Node)",
    NodeGroup: "Grupa Čvorova",
    NoErrorFound: "Bez nađenih grešaka\n",
    NoFilterCriteriaSpecified: "Kriterij za filtriranje nije specificiran.",
    None: "Nijedan",
    NoPublishedSize: "nema objavljene veličina",
    NoRecentFiltersFound: "Nema filtera",
    Normal: "Normalan",
    NoScheduledEvents: "Nema Definisanih Događaja na Rasporedu.",
    NoSplit: "Nema Podijela (Split)",
    NotActive: "Nije Aktivan",
    NotAvailable: "Nije dostupno",
    NothingSelected: "Ništa Nije Izabrano...",
    NotInSuperfiles: "Nije Dio Superdatoteke",
    NotSuspended: "Nije Suspendirano",
    NotSuspendedbyUser: "Nije Suspendovan Od Strane Korisnika",
    NoWarningFound: "Poruke Upozorenja (warnings) nisu nađene\n",
    NumberOfNodes: "Broj čvorova",
    NumberofParts: "Broj Dijelova",
    NumberofSlaves: "Broj Izvršilaca",
    Of: "Od",
    Off: "Isključeno",
    OK: "OK",
    Oldest: "Najstariji",
    OldPassword: "Stara Lozinka",
    OmitSeparator: "Izostavite Separator",
    On: "Uključeno",
    Only1PackageFileAllowed: "Dozvoljen je samo jedan paket",
    Open: "Otvoren",
    OpenConfiguration: "Otvorite Konfiguraciju",
    OpenInNewPage: "Otvorite na Novoj Stranici",
    OpenInNewPageNoFrame: "Otvorite na Novoj Stranici",
    OpenLegacyECLWatch: "Otvorite Stari Prevaziđeni ECL Watch",
    OpenLegacyMode: "Otvorite Zastarjeli Mod",
    OpenModernECLWatch: "Otvorite modernu ECL kontrolnu stranicu",
    OpenNativeMode: "Otvorite Normalni Mod",
    OpenSafeMode: "Otvorite (sigurni mod)",
    OpenSource: "Otvoreni Kod",
    OpenTreeMode: "Otvorite (kao stablo)",
    Operation: "Operacija",
    Operations: "Operacije",
    Optimize: "Optimizirajte",
    Options: "Opcije",
    OriginalFile: "Originalna datoteka",
    OriginalSize: "Originalna veličina",
    OrphanFile: "Nepotrebne Datoteke",
    OrphanFile2: "Nepotrebna Datoteka",
    OrphanMessage: "Nepotrebna datoteka ima neke dijelove na disku. Ali ne postoje svi dijelovi datoteke na disku da bi se mogla kreirati kompletna logicka datoteka. Ne postoji referenca na te dijelove datoteke sa Dali servera.",
    OSStats: "Statistika OS-a",
    Other: "Drugi",
    Others: "Drugi",
    Outputs: "Izlazi",
    Overview: "Pregled",
    Overwrite: "Prepišite",
    OverwriteMessage: "Neke Datoteke već postoje. Da biste nastavili morate dozviliti pisanje preko postojećih datoteka",
    Owner: "Vlasnik",
    PackageContent: "Sadržaj Paketa",
    PackageContentNotSet: "Sadržaj Paketa nije definisan",
    PackageMap: "Mapa Paketa",
    PackageMaps: "Mape Paketa",
    PackagesNoQuery: "Paketi za koje nisu definisani upiti (queries)",
    PageSize: "Veličina stranice",
    ParameterXML: "Parametar XML",
    Part: "Dio",
    PartMask: "Dio Maske",
    PartName: "Naziv Dijela",
    PartNumber: "Broj Dijela",
    Parts: "Dijelovi",
    PartsFound: "Dijelovi Su Pronađeni",
    PartsLost: "Dijelovi Su Izgubljeni",
    Password: "Lozinka",
    PasswordExpiration: "Lozinka Istiće",
    PasswordExpired: "Vaša lozinka je istekla I mora biti promijenjena",
    PasswordExpirePostfix: "dan(a). Želite li je sada promijeniti?",
    PasswordExpirePrefix: "Vaša lozinka će isteći za",
    PasswordNeverExpires: "Lozinka nikad ne ističe",
    PasswordOpenZAP: "Unesite Lozinku Za ZAP (neobavezno)",
    PasswordsDoNotMatch: "Pogrešna Lozinka.",
    Path: "Put",
    PathAndNameOnly: "Samo put i ime?",
    PathMask: "Maska za Put",
    Pause: "Pauza",
    PauseNow: "Zaustavite Odmah",
    PctComplete: "% Kompletiran",
    PercentCompressed: "Procenat Kompresije",
    PercentCompression: "Postotak kompresije",
    PercentDone: "Procenat Završen",
    Percentile97: "97 procenata",
    Percentile97Estimate: "Procijena 97 procenata",
    PercentUsed: "Postotak upotrebe",
    PerformingLayout: "Izvršava Layout...",
    Permission: "Dozvola",
    PermissionName: "Naziv Dozvole Za Pristup",
    Permissions: "Dozvole za Pristup",
    PhysicalFiles: "Fizičke Datoteke",
    PhysicalMemory: "Fizička memorija",
    PlaceholderFindText: "Wuid, Korisnik, Dalje...",
    PlaceholderFirstName: "Jovan",
    PlaceholderLastName: "Smit",
    Platform: "Platforma",
    PlatformBuildIsNNNDaysOld: "Verzija platforme je stara NNN dana",
    Playground: "Igralište",
    PleaseEnableCookies: "ECL Watch zahtijeva da kolačići budu omogućeni za nastavak.",
    PleaseEnterANumber: "Unestite Broj 1 -",
    PleaseLogin: "Molimo prijavite se koristeći svoje korisničko ime i lozinku",
    PleaseLogIntoECLWatch: "Prijavite se na ECL Watch",
    PleasePickADefinition: "Izaberite Definiciju",
    PleaseSelectADynamicESDLService: "Izaberite Dinamički ESDL Servis",
    PleaseSelectAGroupToAddUser: "Izaberite grupu u koju želite da dodate ovog korisnika",
    PleaseSelectAServiceToBind: "Izaberite Servis za Upotrebu",
    PleaseSelectATopologyItem: "Izaberite ciljnu platformu, servis ili mašinu.",
    PleaseSelectAUserOrGroup: "Izaberite Korisnika ili Grupu zajedno sa Imenom Datoteke",
    PleaseSelectAUserToAdd: "Izaberite korisnika koga  želite da dodate",
    PleaseUpgradeToLaterPointRelease: "Molimo koristite noviji point rilis",
    Plugins: "Dodatci",
    PodName: "Naziv pod-a",
    Pods: "Grupe Kontejnera",
    PodsAccessError: "Nije moguće dohvatiti popis podova",
    Port: "Port",
    PotentialSavings: "Potencijalne uštede",
    Prefix: "Prefiks",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preflight: "Provjera prije isporuke",
    PreloadAllPackages: "Učitajte sve pakete",
    PreserveCompression: "Sačuvajte Kompresiju",
    PreserveParts: "Sačuvajte dijelove datoteke",
    PressCtrlCToCopy: "Pritisnite ctrl + c za kopiranje.",
    Preview: "Pregled",
    PreviousSelection: "Prethodni Odabir",
    PreviousWorkunit: "Prethodna radna jedinica",
    PrimaryLost: "Primarni Je Izgubljen",
    PrimaryMonitoring: "Primarni Nadzor",
    Priority: "Prioritet",
    Probability: "Vjerojatnost",
    Process: "Proces",
    Processes: "Procesi",
    ProcessesDown: "Neaktivni procesi",
    ProcessFilter: "Process&nbsp;Filter",
    ProcessID: "ID procesa",
    ProcessorInformation: "Informacija o Procesoru",
    ProgressMessage: "Poruka o Progresu",
    Properties: "Svojstva",
    Property: "Svojstvo",
    Protect: "Zaštitite",
    ProtectBy: "Zaštićeno",
    Protected: "Zašticen",
    Protocol: "Protokol",
    Publish: "Objavite",
    Published: "Objavljen",
    PublishedBy: "Objavljivač",
    PublishedByMe: "Moji Objavljeni Servisi",
    PublishedQueries: "Objavljeni Upiti",
    PushEvent: "Puš Događaj",
    Quarter: "Četvrtina",
    Queries: "Upiti",
    QueriesNoPackage: "Upiti bez odgovarajućeg paketa",
    Query: "Upit",
    QueryDetailsfor: "Detalji o Upitu",
    QueryID: "Identifikator Upita",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Naziv Upita",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Kolekcija Upita",
    Queue: "Red (Queue)",
    Quote: "Citat",
    QuotedTerminator: "Završni Karakter",
    RawData: "Neobrađeni Podatci",
    RawTextPage: "Neobrađen Tekst (Tekuća Stranica)",
    Ready: "Spreman",
    ReallyWantToRemove: "Zaista želite ukloniti?",
    ReAuthenticate: "Ponovo se prijavite koristeći svoje korisničko ime i lozinku",
    RecentFilters: "Upotrebljavani filteri",
    RecentFiltersTable: "Tabela upotrebljavanih filtera",
    RecordCount: "Broj Rekorda",
    RecordLength: "Dužina Rekorda",
    Records: "Rekordi",
    RecordSize: "Veličina Rekorda",
    RecordStructurePresent: "Struktura Rekorda Postoji",
    Recover: "Vratite Natrag",
    RecoverTooltip: "Pokrenite zaustavljenu radnu jedinicu",
    RecreateQuery: "Ponovo kreirajte upit",
    Recursively: "Rekurzivno?",
    Recycling: "Recikliranje",
    RedBook: "Crvena Knjiga",
    Refresh: "Osviježite",
    RelativeLogTimeRange: "Relativni vremenski raspon za upis log dnevnika",
    RelativeTimeRange: "Raspon relativnog vremena",
    ReleaseNotes: "Napomena o Izdanju",
    Reload: "Ponovo Učitajte",
    Remaining: "Preostali",
    RemoteCopy: "Kopija sa udaljenog servera",
    RemoteDali: "Daleki Dali",
    RemoteDaliIP: "Daleki&nbsp;Dali&nbsp;IP&nbsp;Adresa",
    RemoteStorage: "Udaljena pohrana",
    Remove: "Uklonite",
    RemoveAttributeQ: "Izabrani atribut će biti uklonjen. Da li ste sigurni da to želite?",
    RemoveAtttributes: "Uklonite Atribut(e)",
    RemoveFromFavorites: "Ukloni iz favorita",
    RemovePart: "Uklonite Dio",
    RemoveSubfiles: "Uklonite Pod-Datoteku",
    RemoveSubfiles2: "Da li želite ukloniti subfajl(ove)?",
    RemoveUser: "Uklonite Korisnika",
    Rename: "Preimenujte",
    RenderedSVG: "Donesene SVG",
    RenderSVG: "Donesite SVG",
    Replicate: "Replicirajte",
    ReplicatedLost: "Izgubljene Replikacije",
    ReplicateOffset: "Replicirajte Ofset",
    Report: "Izvješće",
    ReportAnError: "Prijavite grešku",
    ReportError: "Prijavite grešku",
    RepresentsASubset: "Predstavlja podskup od ukupnog broja uparenih rezultata .Promjena filtera može smanjiti broj uparenih rezultata",
    RequestSchema: "Shema Zahtjeva",
    RequiredForFixedSpray: "Potrebno za fiksni sprej",
    RequiredForXML: "Potrebno za distribuciju XML",
    Reschedule: "Ponovo Stavite Na Raspored",
    Reset: "Resetujte",
    ResetThisQuery: "Resetujte Tekući Upit",
    ResetUserSettings: "Poništi korisničke postavke",
    ResetViewToSelection: "Resetujte Odabrani Prikaz",
    Resource: "Resurs",
    Resources: "Resursi",
    ResponseSchema: "Shema Odgovora",
    Restart: "Ponovo Pokrenite",
    Restarted: "Ponovo Pokternut",
    Restarts: "Ponovno pokretanje",
    Restore: "Vratite na Staro Stanje",
    RestoreDFUWorkunit: "Vrati DFU radnu jedinicu",
    RestoreECLWorkunit: "Vrati ECL radnu jedinicu",
    Restricted: "Ograničen",
    Resubmit: "Ponovo Podnesite",
    Resubmitted: "Ponovo Poslat",
    ResubmitTooltip: "Reaktivirajte ovu radnu jedinicu",
    Results: "Rezultat(i)",
    Resume: "Nastavite",
    RetainSuperfileStructure: "Zadržite Strukturu Superdatoteke",
    RetainSuperfileStructureReason: "Opcija zadržite strukturu superfajla mora biti aktivirana kada postoji više od jednog podfajla",
    RetypePassword: "Ponovite Lozinku",
    Reverse: "Idite Unazad",
    RowPath: "Put Do Rekorda",
    Rows: "Redovi",
    RowTag: "Etiketa Reda",
    RoxieCluster: "Roxie Klaster",
    RoxieFileCopy: "Status Kopiranja Roxie Datoteka",
    RoxieState: "Roksi Stanje",
    RunningServerStrain: "Izvršavanje ovog procesa može potrajati dugo vremena i veoma optereti servere. Da li želite nastaviti?",
    Sample: "Primjer",
    SampleRequest: "Primjer Zahtjeva",
    SampleResponse: "Primjer Odgovora",
    Sasha: "Saša",
    Save: "Sačuvajte",
    SaveAs: "Spremi kao",
    Scope: "Područje",
    ScopeColumns: "Istražite kolone",
    ScopeTypes: "Istražite tipove",
    SearchResults: "Rezultati Pretraživanja",
    Seconds: "Sekunde",
    SecondsRemaining: "Preostalo Sekundi",
    Security: "Sigurnost",
    SecurityMessageHTML: "Gledajte HTML samo od pouzdanih korisnika. Ovu radnu jedinicu izradio je '{__placeholder__}'. Prikaži HTML?",
    SecurityWarning: "Sigurnosno Upozorenje",
    SeeConfigurationManager: "Pogledajte konfiguiraciju",
    SelectA: "Odaberite",
    SelectAnOption: "Odaberite opciju",
    Selected: "Odabran",
    SelectEllipsis: "Odaberite ...",
    SelectPackageFile: "Izaberi Paket",
    SelectValue: "Odaberite vrijednost",
    SendEmail: "Pošalji e-mail",
    Separators: "Seperatori",
    Sequence: "Sekvenca",
    Server: "Server",
    ServiceName: "Ime Servisa",
    Services: "Servisi",
    ServiceType: "Vrsta usluge",
    SetBanner: "Postavite Zastavicu",
    SetLogicalFileAttribute: "Postavite atribut logičke datoteke",
    SetProtected: "Postavite zaštićen",
    SetTextError: "Neuspješno prikazivanje teksta (da li je tekst predug?). Koristite &lsquo;pomagače&rsquo; za preuzimanje datoteka.",
    SetToFailed: "Postavite Na Neuspješan",
    SetToolbar: "Setujte tulbar",
    SetToolbarColor: "Postavi toolbar boju",
    SetUnprotected: "Postavite nezaštićen",
    SetValue: "Postavite vrijednost",
    Severity: "Ozbiljnost",
    ShareWorkunit: "Podijeli Workunit URL",
    Show: "Pokažite",
    ShowPassword: "Pokažite lozinku",
    ShowProcessesUsingFilter: "Prikažite procese koristeći filter",
    ShowSVG: "Pokažite SVG",
    Size: "Veličina",
    SizeEstimateInMemory: "Procjena veličine u memoriji",
    SizeMeanPeakMemory: "Prosječna veličina udarnih koristenja memorije",
    SizeOnDisk: "Veličina na disku",
    Skew: "Skju (Skew)",
    SkewNegative: "Skju(-)",
    SkewPositive: "Skju(+)",
    SLA: "SLA",
    SlaveLogs: "Izvjestaji Izvršilaca",
    SlaveNumber: "Broj Izvršilaca",
    Slaves: "Robovi (Slaves)",
    Smallest: "Najmanji",
    SmallestFile: "Najmanja Datoteka",
    SmallestSize: "Najmanja Veličina",
    SOAP: "SOAP",
    SomeDescription: "Neki*Opis",
    somefile: "*::nekifile*",
    Sort: "Sortirajte",
    Source: "Izvorna Verzija",
    SourceCode: "Izvorna Verzija Koda",
    SourceLogicalFile: "Ime Izvorne Datoteke",
    SourcePath: "Izvorna Verzija Puta (sa omogucenim *)",
    SourceProcess: "Izvorni Proces",
    Span: "Raspon",
    SparkThor: "SparkThor",
    Spill: "Zapis na Disk",
    SplitPrefix: "Split Prefiks",
    Spray: "Razbacajte (Spray)",
    SQL: "SQL",
    Start: "Počnite",
    Started: "Počeo",
    Starting: "Polazak",
    StartTime: "Vrijeme početka",
    State: "Stanje",
    Statistics: "Statistika",
    Stats: "Statistike",
    Status: "Status",
    Stopped: "Zaustavljen",
    Stopping: "Zaustavljanje",
    StorageInformation: "Informacija o prostoru",
    Subfiles: "Poddatoteke",
    Subgraph: "Pod-Graf",
    SubgraphLabel: "Oznaka podgrafa",
    Subgraphs: "Podgrafikon",
    Submit: "Podnesite",
    Subtype: "Pod-Vrsta",
    SuccessfullySaved: "Uspješno Spremljen",
    Summary: "Kratak Pregled",
    SummaryMessage: "Sažeta Poruka",
    SummaryStatistics: "Sažeta statistika",
    SuperFile: "Super Datoteka",
    Superfile: "Super Datoteka",
    SuperFiles: "Super Datoteke",
    Superfiles: "SuperDatoteke",
    SuperFilesBelongsTo: "Pripadnik Superdatoteke",
    SuperfilesOnly: "Samo Superdatoteke",
    SuperOwner: "Super Vlasnik",
    Suspend: "Suspendujte",
    Suspended: "Suspendovan",
    SuspendedBy: "Suspendovan Od",
    SuspendedByAnyNode: "Suspendira bilo koji čvor",
    SuspendedByCluster: "Suspendovan od strane klastera",
    SuspendedByFirstNode: "Suspendira prvi čvor",
    SuspendedByUser: "Suspendovan Od Strane Korisnika",
    SuspendedReason: "Razlog za Suspendovanje",
    SVGSource: "SVG Izvor",
    SyncSelection: "Sinhronizujte Sa Odabranim",
    Syntax: "Sintaksa",
    SystemServers: "Sistem Servera",
    Table: "Tabela",
    tag: "tag",
    Target: "Cilj",
    TargetClusters: "Ciljni Klasteri",
    TargetClustersLegacy: "Ciljni klaster (kao ranije)",
    TargetName: "Naziv Cilja",
    TargetNamePlaceholder: "neko::logicko::ime",
    TargetPlane: "Odrediste za rad",
    TargetRowTagRequired: "Morate označiti ciljni red u tabeli",
    Targets: "Ciljne Platforme",
    TargetScope: "Ciljni Opseg",
    TargetWuid: "Cilj/Wuid",
    TechPreview: "Tehnički pregled",
    Terminators: "Terminatori",
    TestPages: "Test Stranice",
    Text: "Tekst",
    Theme: "Tema",
    TheReturnedResults: "Vraćeni Rezultati",
    ThorMasterAddress: "Adresa Glavnog Thora",
    ThorNetworkAddress: "Netvork Adresa Thora",
    ThorProcess: "Tor Proces",
    ThreadID: "ID treda",
    Time: "Vrijeme",
    Timeline: "Vremenska Crta",
    TimeMaxTotalExecuteMinutes: "Maksimalno ukupno vrijeme izvršavanja u minutama",
    TimeMeanTotalExecuteMinutes: "Prosječno ukupno vrijeme izvršavanja u minutama",
    TimeMinTotalExecuteMinutes: "Minimalno ukupno vrijeme izvršavanja u minutama",
    TimePenalty: "Vremenska kazna",
    Timers: "Mjerači Vremena",
    TimeSeconds: "Vrijeme (Sekunde)",
    TimeStamp: "Vremenska Oznaka",
    TimeStarted: "Vrijeme Početka",
    TimeStopped: "Vrijeme Kraja",
    Timings: "Vremena",
    TimingsMap: "Mapa Vremena",
    title_ActiveGroupPermissions: "Dozvole Aktivne Grupe",
    title_ActivePermissions: "Aktivne Dozvole",
    title_Activity: "Aktivnosti",
    title_AvailableGroupPermissions: "Dostupne Dozvole Grupe",
    title_AvailablePermissions: "Dostupne Dozvole",
    title_BindingConfiguration: "Konfiguracija za Povezivanje",
    title_BindingDefinition: "Definicija Povezivanja",
    title_Blooms: "Blums",
    title_ClusterInfo: "Grupe",
    title_Clusters: "Klasteri",
    title_CodeGeneratorPermissions: "Dozvole Kod Generatora",
    title_DefinitionExplorer: "Istraživač Definicija",
    title_Definitions: "Definicije",
    title_DESDL: "Dinamičani ESDL",
    title_DFUQuery: "Logičke Datoteke",
    title_DFUWUDetails: "DFU Radna Jedinica",
    title_DirectoriesFor: "Direktoriji za",
    title_DiskUsage: "Iskorištenost Diska",
    title_ECLPlayground: "ECL Igralište",
    title_ErrorsWarnings: "Pogreške/Upozorenja za",
    title_EventScheduleWorkunit: "Respoređivač Događaja",
    title_FileScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor za Datoteke",
    title_FilesPendingCopy: "Datoteke na čekanju za kopiranje",
    title_FoundFilesFor: "Pronađena datoteka za",
    title_GetDFUWorkunits: "DFU Radne Jedinice",
    title_Graph: "Grafikon",
    title_GraphPage: "naslov",
    title_Graphs: "Grafikoni",
    title_GridDetails: "Promijeni Me",
    title_History: "Povijest",
    title_HPCCPlatformECL: "ECL Watch - Glavna Stranica",
    title_HPCCPlatformFiles: "ECL Watch - Datoteke",
    title_HPCCPlatformMain: "ECL Watch - Glavna Stranica",
    title_HPCCPlatformOps: "ECL Watch - Upravljnje",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Monitor - Dodatci",
    title_Inputs: "Unosi",
    title_LFDetails: "Detalji o Logičkol Datoteci",
    title_LibrariesUsed: "Biblioteke U Korištenju",
    title_Log: "Log Fajl",
    title_LostFilesFor: "Izgubljene Datoteke za",
    title_LZBrowse: "Zona za Pretovar",
    title_MemberOf: "Član Od",
    title_Members: "Članovi",
    title_Methods: "Metode",
    title_OrphanFilesFor: "Nepotrebne datoteke za",
    title_PackageParts: "Dijelovi paketa",
    title_Permissions: "Dozvole",
    title_Preflight: "Metrička vrijednost sistema",
    title_PreflightResults: "Rezultati Provjere",
    title_ProtectBy: "Zaštićeno",
    title_QuerySetDetails: "Detalji Upita",
    title_QuerySetErrors: "Greške",
    title_QuerySetLogicalFiles: "Logičke Datoteke",
    title_QuerySetQuery: "Upiti (Queries)",
    title_QuerySetSuperFiles: "Super Datoteke",
    title_QueryTest: "Super Datoteke",
    title_Result: "Acktivnost",
    title_Results: "Rezultati",
    title_SearchResults: "Rezultati Pretraživanja",
    title_SourceFiles: "Originalni Fajlovi",
    title_SystemServers: "Sistemski serveri",
    title_SystemServersLegacy: "Sistemski serveri (legat)",
    title_TargetClusters: "Ciljni Klasteri",
    title_Topology: "Topologija",
    title_TpThorStatus: "Stanje Thora",
    title_UserPermissions: "Korisničke Dozvile za Pristup",
    title_UserQuery: "Prava Pristupa",
    title_WorkunitScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor za Radne Jedinice",
    title_WUDetails: "ECL Detalji o Radnoj Jedinici",
    title_WUQuery: "ECL Radne Jedinice",
    TLS: "TLS",
    To: "Prema",
    ToDate: "Do Sada",
    Toenablegraphviews: "Da biste mogli vidjeli grafikone, moraćete instalisati Graph View Control plugin",
    Tooltip: "Savjet",
    TooManyFiles: "Previše Datoteka",
    Top: "Vrh",
    Topology: "Topologija",
    ToSizes: "Do Velićina",
    Total: "Ukupno",
    TotalClusterTime: "Ukupno Vrijeme Klastera",
    TotalParts: "Ukupan Broj Dijelova",
    TotalSize: "Totalna Veličina",
    TotalThorTime: "Ukupno Vrijeme Thor-a",
    ToTime: "Do vremena",
    Trace: "Otkrij",
    TransferRate: "Stopa Prijenosa",
    TransferRateAvg: "Prosjećna stopa prijenosa",
    TransitionGuide: "Vodič",
    Tree: "Drvo",
    Type: "Tip",
    UnavailableInContainerized: "Ovo nije dostupno u kontejnerskom okruženju.",
    Unbound: "Odvojen",
    undefined: "nedefinisan",
    Unknown: "Nepoznat",
    Unlock: "Otključajte",
    UnlockSDSLock: "Otključaj SDS Lock",
    Unprotect: "Ukinite Zaštitu",
    UnsupportedIE9FF: "Nisu Podržani (IE <= 9, FireFox)",
    Unsuspend: "Ukinite Suspenziju",
    Unsuspended: "Suspenzija Ukinuta",
    Up: "Na Gore",
    UpdateCloneFrom: "Ažurirajte Klon Koristeći",
    UpdateDFs: "Ažurirajte DFS",
    UpdateSuperFiles: "Ažurirajte Super Datoteke",
    Upload: "Učitajte",
    Uploading: "Učitavanje",
    UpTime: "Vrijeme Rada",
    URL: "URL",
    Usage: "Upotreba",
    Used: "Korišten",
    UsedByWorkunit: "Korišten sa Radnom Jedinicom",
    User: "Korisnik",
    UserDetails: "Detalji o Korisniku",
    UserID: "Korisnicki ID",
    UserLogin: "Prijavite se samo pomoću korisničkog imena",
    UserName: "Ime Korisnika",
    Username: "Imekorisnika",
    UserPermissions: "Dozvole za Korisnikov Pristup",
    Users: "Korisnici",
    UseSingleConnection: "Koristite Samo Jedan Priključak (Connection)",
    Validate: "Potvrdite",
    ValidateActivePackageMap: "Validirajte Mapu Aktivnog Paketa",
    ValidatePackageContent: "Validirajte Saržaj Paketa",
    ValidatePackageMap: "Potvrdite Mapu Paketa",
    ValidateResult: "=====Potvrdite Result=====\n\n",
    ValidateResultHere: "(Rezultati Validiranja)",
    Validating: "Provjeravanje...",
    ValidationErrorEnterNumber: "Unesite validan broj",
    ValidationErrorExpireDaysMinimum: "Ne bi trebao biti manji od jednog dana",
    ValidationErrorNamePrefix: "Trebalo bi odgovarati uzorku neki :: prefiks",
    ValidationErrorNumberGreater: "Ne može biti veći od",
    ValidationErrorNumberLess: "Ne može biti manji od",
    ValidationErrorRecordSizeNumeric: "Duljina rekorda treba biti broj",
    ValidationErrorRecordSizeRequired: "Potrebna je duljina rekorda",
    ValidationErrorRequired: "Ovo polje je obavezno",
    ValidationErrorTargetNameInvalid: "Nekorektan naziv datoteke",
    ValidationErrorTargetNameRequired: "Ime datoteke je potrebno",
    Value: "Vrijednost",
    Variable: "Varijabla",
    VariableBigendian: "Varijabla Big-endian",
    Variables: "Varijable",
    VariableSourceType: "Tip Izvora",
    Version: "Verzija",
    ViewByScope: "Pogled prema Skopu",
    Views: "Pogledi",
    ViewSparkClusterInfo: "Pogledajte Informacije o Spark Klasteru",
    Visualizations: "Vizualizacije",
    Visualize: "Visualizujte",
    WarnIfAvailableDiskSpaceIsUnder: "Upozori ako raspoloživi disk prostor spadne ispod",
    WarnIfAvailableMemoryIsUnder: "Upozori ako raspoloživa memorija spadne ispod",
    WarnIfCPUUsageIsOver: "Upozori ako je iskorištenost procesora preko",
    Warning: "Upozorenje",
    Warnings: "Upozorenje(a)",
    WarnOldGraphControl: "Upozorenje:  Stara Grafička Kontrola",
    What: "Šta",
    Where: "Gdje",
    Who: "Ko",
    Width: "Širina",
    WildcardFilter: "Filter zamjenskih znakova",
    Workflows: "Tokovi poslova",
    Workunit: "Radna Jedinica",
    WorkunitNotFound: "Radna jedinica nije pronađena",
    WorkunitOptions: "Opcije radne jedinice",
    Workunits: "Radne Jedinice",
    WorkUnitScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor za Radne Jedinice",
    Wrap: "Zamotajte",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Ne Može Biti Prazan.",
    WUSnapshot: "Snimak radne jedinice",
    WUSnapShot: "Trenutna Slika Radne Jedinice",
    WUSnapshots: "Snimke radnih jedinica",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Godina",
    YouAreAboutToBeLoggedOut: "Vi ćete biti odjavljeni",
    YouAreAboutToDeleteBinding: "Odabrano vezivanje/binding će biti izbrisano. Jeste li sigurni da želite to učiniti?",
    YouAreAboutToDeleteDefinition: "U tijeku je brisanje ove definicije. Jeste li sigurni da želite to učiniti?",
    YouAreAboutToDeleteThisFile: "Hoćete li izbrisati ovu datoteku",
    YouAreAboutToDeleteThisPart: "Hoćete li izbrisati ovaj dio",
    YouAreAboutToDeleteThisQueryset: "Hoćete li izbrisati ovaj skup upita",
    YouAreAboutToDeleteThisWorkunit: "Hoćete li izbrisati ovu radnu jedinicu",
    YouAreAboutToRemoveUserFrom: "Tražili ste da uklonite korisnika(e) iz ove grupe. Da li želite nastaviti?",
    YourBrowserMayNotSupport: "Vaš pretraživač možda ne podržava datoteku (e) ove veličine",
    YourScreenWasLocked: "ESP je zaključao vaš ekran. Podatci su zastarjeli.",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nema ni jedane Logičke Datoteke(provjerite filter)",
    Zip: "Zapakujte (Zip)",
    ZippedAnalysisPackage: "Zapakovani Paket sa Analizama",
    Zoom: "Zum",
    Zoom100Pct: "Zumirajte 100%",
    ZoomAll: "Zumirajte Sve",
    ZoomMinus: "Zum-",
    ZoomPlus: "Zum +",
    ZoomSelection: "Odabir zumiranja",
    ZoomWidth: "Zumirajte Širinu"
}