export = {
    Abort: "Annuler",
    AbortedBy: "Annulé par",
    AbortedTime: "L'heure d'annulation",
    About: "À propos",
    AboutGraphControl: "À propos de Graph Control",
    AboutHPCCSystems: "À propos de HPCC Systems®",
    AboutHPCCSystemsGraphControl: "À propos de HPCC Systems® Graph Control",
    AboutToLoseSessionInformation: "Vous êtres en train de vous disconnecter et perdre toutes les information de cette session. Aimeriez-vous procéder à cette action?",
    Account: "Compte",
    Action: "Action",
    Activate: "Activer",
    Activated: "Activé",
    ActivateQuery: "Activer la requête",
    ActivateQueryDeletePrevious: "Activer la requête, supprimer la précédente",
    ActivateQuerySuspendPrevious: "Activer la requête, suspendre la précédente",
    Active: "Activer",
    ActivePackageMap: "Plan du package actif",
    ActiveWorkunit: "Activer Workunit",
    Activities: "Activités",
    Activity: "Activité",
    ActivityMap: "Plan d'activité",
    ActualSize: "Dimension actuelle",
    Add: "Ajouter",
    AddAttributes: "Ajouter des attributs/valeurs à votre méthode",
    AddAttributes2: "Ajouter des attributs",
    AddBinding: "Ajouter une liaison",
    AddFile: "Ajouter le fichier",
    AddGroup: "Ajouter une groupe",
    AdditionalResources: "Resources supplémentaires",
    AddPart: "Ajouter une partie",
    AddProcessMap: "Ajouter le plan package",
    AddTheseFilesToDali: "Ajouter ces fichiers à Dali",
    AddtionalProcessesToFilter: "Processus supplémentaires à filtrer",
    AddToExistingSuperfile: "Ajouter à un actuel Superfichier",
    AddToSuperfile: "Ajouter au Superfichier",
    AddUser: "Ajouter un utilisateur",
    Advanced: "Avancé",
    All: "Tous",
    AllowAccess: "<center>Autoriser<br>l'accès</center>",
    AllowForeignFiles: "Autoriser des fichiers étrangers",
    AllowFull: "<center>Autoriser<br>plein</center>",
    AllowRead: "<center>Autoriser<br>à lire</center>",
    AllowWrite: "<center>Autoriser<br>à écrire</center>",
    AllQueries: "Toutes les requêtes",
    AllQueuedItemsCleared: "Tous les éléments en file d'attente ont été lus.",
    Analyze: "Analyser",
    ANY: "Tout",
    AnyAdditionalProcessesToFilter: "Tout processus supplémentaire à filter",
    Append: "Relier",
    AppendCluster: "Relier le cluster",
    Apply: "Appliquer",
    ArchivedOnly: "Seulement les archivés",
    ArchivedWarning: "Avertissement: Veuillez specifier une date courte. Sinon, récupérant le workunit peut prendre du temps.",
    AreYouSureYouWantToResetTheme: "Voulez-vous vraiment réinitialiser le thème par défaut?",
    Attach: "Attacher",
    Attribute: "Attribut",
    AttributesAreRequired: "Les attributs sont obligatoires",
    Audience: "Audience",
    AuditLogs: "Auditer Les Journaux",
    AutoRefresh: "Actualiser Automatiquement",
    AutoRefreshEvery: "Actualiser automatiquement toutes les x minutes",
    AutoRefreshIncrement: "Actualiser Automatiquement par incrément",
    Back: "Arrière",
    BannerColor: "Couleur de la bannière",
    BannerMessage: "Message de la bannière",
    BannerScroll: "Défilement de la bannière",
    BannerSize: "Dimension de la bannière",
    BinaryInstalls: "Installations Binaires",
    Bind: "Lier",
    Binding: "En cours de liaison",
    BindingDeleted: "Liaison annulée",
    Blob: "BLOB",
    BlobPrefix: "BLOB Préfix",
    Blooms: "Blooms",
    Bottom: "Bas",
    BoundBy: "Limiter par",
    BrowserStats: "Statistiques du navigateur",
    Busy: "Occupée",
    Cancel: "Annuler",
    CancelAll: "Annuler tous",
    CancelAllMessage: "Annuler les travaux en cours et videz la file d'attente. Souhaitez-vous continuer?",
    Channel: "Canal",
    Chart: "Graphique",
    CheckAllNodes: "Vérifier tous les nœuds",
    CheckFilePermissions: "Vérifier les autorisations des fichiers",
    CheckSingleNode: "Vérifier uniquement un nœud",
    Clear: "Effacer",
    ClearPermissionsCache: "Vider le cache des autorisations",
    ClearPermissionsCacheConfirm: "Voulez-vous vraiment effacer les caches d'autorisations DALI et ESP? L'exécution des workunits peut se dégrader considérablement jusqu'à ce que les caches aient été actualisés.",
    Client: "Client",
    Clone: "Cloner",
    ClonedWUID: "WUID clonés",
    CloneTooltip: "Dupliquer workunit",
    Close: "Fermer",
    Cluster: "Cluster",
    ClusterName: "Nom du cluster",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Processus du cluster",
    Code: "Code",
    CodeGenerator: "Générateur de code",
    Col: "Col",
    CollapseAll: "Réduire tout",
    Command: "Commander",
    Comment: "Commenter",
    Compiled: "Compilé",
    Compiling: "Compilant",
    Completed: "Terminé",
    ComplexityWarning: "Plus que {threshold} activités ({activityCount}) - supprimer l'affichage initial?",
    Component: "Composant",
    ComponentLogs: "Journal du composant",
    Compress: "Compresser",
    Compressed: "Compressé",
    CompressedFileSize: "Compresser la taille du fichier",
    ComputerUpTime: "Disponibilité de l'ordinateur",
    Condition: "Condition",
    Configuration: "Configuration",
    ConfigureService: "Configurer le service",
    ConfirmPassword: "Confirmer mot de passse",
    ConfirmRemoval: "Êtes-vous sûr de vouloir faire ça?",
    ContactAdmin: "Si vous souhaitez renommer ce groupe, veuillez contacter votre administrateur de LDAP.",
    Content: "Contenu",
    Contents: "Contenus",
    ContentType: "Type de contenu",
    ContinueWorking: "Continuer à travailler",
    Copied: "Copié",
    Copy: "Copier",
    CopyToClipboard: "Copier au presse-papier",
    CopyURLToClipboard: "Copier URL au presse-papier",
    CopyWUIDs: "Copier WUIDs au presse-papier",
    CopyWUIDToClipboard: "Copier WUID au presse-papier",
    Count: "Compter",
    CPULoad: "Charge de CPU",
    Create: "Créer",
    CreateANewFile: "Créer un nouveau superfichier",
    Created: "Créé",
    CreatedBy: "Créé par",
    CreatedByWorkunit: "Créé par workunit",
    CreatedTime: "L'heure de création",
    Creating: "En cours de création",
    Critical: "Critique",
    CSV: "CSV",
    Dali: "Dali",
    DaliIP: "DaliIP",
    DataPatterns: "Modèles de données",
    DataPatternsNotStarted: "Analyse introuvable. Pour commencer, appuyez sur le bouton Analyser ci-dessus.",
    DataPatternsStarted: "En cours d'analyse. Une fois le rapport complet affiché ici.",
    dataset: ":=dataset*",
    Date: "Date",
    Day: "Jour",
    Deactivate: "Désactiver",
    Debug: "Déboguer",
    DEF: "DEF",
    Defaults: "Défaut",
    Definition: "Définition",
    DefinitionDeleted: "Définition suprimée",
    DefinitionID: "ID de la définition",
    Definitions: "Définitions",
    DelayedReplication: "Réplication retardée",
    Delete: "Surprimer",
    DeleteBinding: "Surprimer la liaison",
    Deleted: "Surprimée",
    DeletedBinding: "Liaison surprimée",
    DeleteDirectories: "Supprimez les répertoires vides. Souhaitez-vous continuer?",
    DeleteEmptyDirectories: "Supprimer les répertoires vides?",
    DeletePrevious: "Supprimer Précédent",
    DeleteSelectedDefinitions: "Supprimer les définitions sélectionnées?",
    DeleteSelectedFiles: "Supprimer les fichiers sélectionnés?",
    DeleteSelectedGroups: "Supprimer les groupes sélectionnés?",
    DeleteSelectedPackages: "Supprimer les packages sélectionnés?",
    DeleteSelectedPermissions: "Supprimer les autorisations sélectionnées?",
    DeleteSelectedQueries: "Supprimer les requêtes sélectionnées?",
    DeleteSelectedUsers: "Supprimer les utilisateurs sélectionnés?",
    DeleteSelectedWorkunits: "Supprimer les workunits sélectionnées?",
    DeleteSuperfile: "Supprimer le Superfichier?",
    DeleteSuperfile2: "Supprimer le Superfichier",
    DeleteThisPackage: "Supprimer ce package?",
    Delimited: "Délimité",
    DenyAccess: "<center>Refuser<br>Accès</center>",
    DenyFull: "<center>Refuser<br>Tous</center>",
    DenyRead: "<center>Refuser<br>Lecture</center>",
    DenyWrite: "<center>Refuser<br>Écriture</center>",
    Depth: "Profondeur",
    DepthTooltip: "Profondeur maximale du sous-graphe",
    Deschedule: "Déprogrammer",
    DescheduleSelectedWorkunits: "Déprogrammer les workunits sélectionnées?",
    Description: "Description",
    DESDL: "ESDL Dynamique",
    Despray: "Amasser",
    Details: "Détails",
    DFUServerName: "Nom du serveur DFU",
    DFUWorkunit: "DFU Workunit",
    Directories: "Répertoires",
    Directory: "Répertoire",
    DisableScopeScanConfirm: "Êtes-vous sûr de vouloir désactiver les Scope Scans? Les modifications reviendront aux paramètres de configuration de DALI.",
    DisableScopeScans: "Désactiver Scope Scans",
    DiskUsage: "Utilisation du disque",
    Distance: "Distance",
    DistanceTooltip: "Activité maximale aux à l'entours",
    Dll: "Dll",
    Documentation: "Documentation",
    Domain: "Domaine",
    DoNotActivateQuery: "Ne pas activer la requête",
    DoNotRepublish: "Ne pas republier?",
    DOT: "DOT",
    DOTAttributes: "DOT Attributs",
    Down: "Vers le bas",
    Download: "Télécharger",
    Downloads: "Téléchargements",
    DownloadToCSV: "Télécharger à CSV",
    DropZone: "Zone de largage",
    DueToInctivity: "Vous serez déconnecté de toutes les sessions ECL Watch en 3 minutes en raison de l'inactivité.",
    Duration: "Duration",
    DynamicNoServicesFound: "Aucun service trouvé",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWatchRequiresCookies: "ECL Watch a besoin les cookies activités pour continuer.",
    ECLWatchSessionManagement: "Gestion des sessions de ECL Watch",
    ECLWorkunit: "ECL Workunit",
    Edges: "Bords",
    Edit: "Modifier",
    EditDOT: "Modifier le DOT",
    EditGraphAttributes: "Modifier les attributs du graphe",
    EditXGMML: "Modifier XGMML",
    EmailBody: "Corps de l'e-mail",
    EmailFrom: "Adresse e-mail (de)",
    EmailSubject: "Sujet du courriel",
    EmailTo: "Adresse e-mail (à)",
    EmployeeID: "ID de l'employé",
    EmployeeNumber: "Numéro de l'employé",
    Empty: "(Vide)",
    Enable: "Activer",
    EnableBannerText: "Activer le texte d'environnement",
    EnableScopeScans: "Activer les Scope Scans",
    EnableScopeScansConfirm: "Êtes-vous sûr de vouloir activer les Scope Scans? Les modifications reviendront aux paramètres de configuration de DALI.",
    EnglishQ: "Anglais?",
    EnterAPercentage: "Entrer un pourcentage",
    EnterAPercentageOrMB: "Entrer un pourcentage ou MB",
    EraseHistory: "Effacer l'historique",
    EraseHistoryQ: "Effacer l'historique pour:",
    Error: "Erreur",
    Errorparsingserverresult: "Erreur d'analyse le résultat du serveur",
    Errors: "Erreur(s)",
    ErrorsStatus: "Erreurs / Statut",
    ErrorUploadingFile: "Erreur lors du téléchargement du ou des fichiers. Essayez de vérifier les autorisations.",
    ErrorWarnings: "Erreur / avertissement (s)",
    Escape: "Échapper",
    ESPBindings: "Liaisons ESP",
    ESPBuildVersion: "Version ESP",
    ESPNetworkAddress: "Adresse du réseau de l'ESP",
    ESPProcessName: "Nom du processus de l'ESP",
    EventName: "Nom de l'événement",
    EventNamePH: "Nom de l'événement",
    EventScheduler: "Planificateur d'événements",
    EventText: "Texte d'événement",
    EventTextPH: "Texte d'événement",
    Exception: "Exception",
    Executed: "Exécuté",
    Executing: "En cours d'exécution",
    ExpandAll: "S'étendre tout",
    ExpireDays: "Expirer dans (jours)",
    Export: "Exportation",
    ExportSelectionsToList: "Exporter les sélections vers la liste",
    FailIfNoSourceFile: "Échec si aucune source de fichier est présente",
    Fatal: "Fatal",
    Fetched: "Récupéré",
    FetchingData: "En cours de recherche des données...",
    fetchingresults: "En cours de recherche des résultats",
    FieldNames: "Noms de champs",
    File: "Fichier",
    FileCluster: "Cluster de fichiers",
    FileCounts: "Nombre de fichiers",
    FileName: "Nom du fichier",
    FileParts: "Pièces de fichier",
    FilePath: "Chemin du fichier",
    FilePermission: "<b> Autorisation de fichier </b>",
    Files: "Fichiers",
    FileScopeDefaultPermissions: "Autorisations par défaut de l'étendue du fichier",
    FileScopes: "Étendues de fichier",
    FileSize: "Taille du fichier",
    FilesNoPackage: "Fichiers sans définitions de package correspondantes",
    FilesPending: "Fichiers en attente",
    FilesWarning: "Le nombre de fichiers renvoyés est trop grand. Seulement les 100 000 premiers fichiers triés par date / heure modifiée ont été renvoyés. Si vous souhaitez limiter les résultats, définissez un nouveau filtre.",
    FilesWithUnknownSize: "Fichiers de taille inconnue",
    FileType: "Type de fichier",
    FileUploader: "Téléchargeur de fichiers",
    FileUploadStillInProgress: "Téléchargement de fichier toujours en cours",
    Filter: "Filtre",
    FilterSet: "Série de filtres",
    Find: "Trouver",
    FindNext: "Rechercher ensuite",
    FindPrevious: "Rechercher précédent",
    Finished: "Fini",
    FirstN: "Premier N",
    FirstName: "Prénom",
    FirstNRows: "Premières lignes N",
    Fixed: "Fixé",
    Folder: "Dossier",
    Format: "Format",
    Forums: "Forums",
    Forward: "Vers l'avant",
    FoundFile: "Fichiers trouvés",
    FoundFileMessage: "Un fichier trouvé contient toutes ses parties sur le disque qui ne sont pas référencées sur le serveur Dali. Toutes les parties du fichier sont prises en compte afin de pouvoir être ajoutées au serveur Dali. Elles peuvent également être supprimées du cluster, si nécessaire. ",
    FromDate: "De la date",
    FromSizes: "De tailles",
    FromTime: "De l'heure",
    FullName: "Nom complet: ",
    Generate: "Produire",
    GetPart: "Obtenir la partie",
    GetSoftwareInformation: "Obtenir des informations sur le logiciel",
    Graph: "Graphe",
    GraphControl: "Graph Control",
    Graphs: "Graphes",
    GraphView: "Vue graphique",
    Group: "Groupe",
    GroupBy: "Grouper par",
    GroupDetails: "Détails du groupe",
    Grouping: "En train de grouper",
    GroupName: "Nom de groupe",
    GroupPermissions: "Autorisations de groupe",
    Groups: "Groupes",
    GZip: "GZip",
    help: "Cette zone affiche la carte des arbres des graphiques de ce workunit. La taille et la teinte indiquent la durée de chaque graphe (plus grande et plus sombre indique un pourcentage plus élevé du temps nécessaire.)",
    Helper: "Assistant",
    Helpers: "Annuler",
    Hex: "Hex",
    HideSpills: "Masquer les déversements",
    High: "Haut",
    History: "Histoire",
    HPCCSystems: "HPCC Systems®",
    Icon: "Icône",
    ID: "ID",
    Inactive: "Inactive",
    IncludeSlaveLogs: "Inclure les journaux esclaves",
    Index: "Indice",
    Info: "Info",
    InfoDialog: "Dialogue info",
    Informational: "Informatif",
    InheritedPermissions: "Autorisation héritée:",
    Inputs: "Entrées",
    InUse: "En usage",
    InvalidResponse: "(Réponse non valide)",
    InvalidUsernamePassword: "Nom d'utilisateur ou mot de passe invalide, réessayez.",
    IP: "IP",
    IPAddress: "Adresse IP",
    IsCompressed: "Est compressé",
    IsLibrary: "Est bibliothèque",
    IsReplicated: "Est répliqué",
    IssueReporting: "Signaler un problème",
    JobName: "Nom du travail",
    Jobname: "Nom du travail",
    jsmi: "jsmit",
    JSmith: "JSmit*",
    JSON: "JSON",
    KeyFile: "Fichier clé",
    KeyType: "Type de clé",
    Label: "Étiquette",
    LandingZone: "Zone d'atterrissage",
    LandingZones: "Zone d'atterrissages",
    LanguageFiles: "Fichiers de langue",
    Largest: "Le plus grand",
    LargestFile: "Plus gros fichier",
    LargestSize: "Plus grande taille",
    LastEdit: "Dernière modification",
    LastEditedBy: "Dernière modification par",
    LastEditTime: "Heure de la dernière modification",
    LastMessage: "Dernier message",
    LastName: "Nom de famille",
    LastNDays: "Les N dernier jours",
    LastNHours: "Les N dernières heures",
    LastNRows: "Les N dernières rangées",
    LastRun: "Dernière exécution",
    LDAPWarning: "<b>Erreur des services LDAP:</b>  &lsquo;Trop d'utilisateurs&rsquo; - Veuillez utiliser un filtre.",
    LearnMore: "Apprendre encore plus",
    LegacyForm: "Ancien formulaire",
    Legend: "Légende",
    LibrariesUsed: "Bibliothèques utilisées",
    LibraryName: "Nom de la bibliothèque",
    Limit: "Limite",
    Line: "Ligne",
    LineTerminators: "Terminateurs de ligne",
    Links: "Liens",
    Loading: "Chargement...",
    LoadingCachedLayout: "Chargement du plan de la mise en cache ...",
    LoadingData: "Chargement des données...",
    loadingMessage: "Chargement des données...",
    LoadPackageContentHere: "(Charger le contenu du package ici)",
    LoadPackageFromFile: "Charger le package à partir d'un fichier",
    Local: "Local",
    LocalFileSystemsOnly: "Systèmes de fichiers locaux uniquement",
    Location: "Location",
    Lock: "Fermer",
    Log: "Journal",
    log_analysis_1: "analyse_journal_1*",
    LogDirectory: "Répertoire des journaux",
    LogFile: "Fichier journal",
    LoggedInAs: "Connecté en tant que",
    LoggingOut: "Déconnecter",
    LogicalFile: "Fichier logique",
    LogicalFiles: "Fichiers logiques",
    LogicalFilesAndSuperfiles: "Fichiers logiques et Superfichiers",
    LogicalFilesOnly: "Fichiers logiques uniquement",
    LogicalFileType: "Type de fichier logique",
    LogicalName: "Nom logique",
    Login: "Se connecter",
    Logout: "Se déconnecter",
    Logs: "Annuler",
    LogVisualization: "Visualisation des journaux",
    LogVisualizationUnconfigured: "La visualisation des journaux n'est pas configurée, veuillez vérifier les paramètres de votre gestionnaire de configuration.",
    LostFile: "Fichiers perdus",
    LostFile2: "Fichiers perdus",
    LostFileMessage: "Un fichier logique qui manque au moins une partie de fichier sur les emplacements principal et répliqué dans le stockage. Le fichier logique est toujours référencé sur le serveur Dali. La suppression du fichier supprime la référence du serveur Dali et toutes les parties restantes sur le disque. ",
    Low: "Faible",
    MachineInformation: "Informations sur la machine",
    Machines: "Machines",
    Major: "Majeur",
    ManagedBy: "Gérée par",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=utilisateurs,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Appuyez sur Ctrl + C",
    ManualOverviewSelection: "(Une sélection manuelle de l'aperçu sera nécessaire)",
    ManualTreeSelection: "(Une sélection manuelle de l'arbre de sélection sera requise)",
    Mappings: "Mappages",
    Mask: "Masque",
    Max: "Max",
    MaximizeRestore: "Maximiser / Restaurer",
    MaximumNumberOfSlaves: "Numéro d'esclave",
    MaxNode: "Noeud maximum",
    MaxRecordLength: "Longueur d'enregistrement maximale",
    MaxSize: "Taille maximum",
    MaxSkew: "Inclinaison maximale",
    MaxSkewPart: "Partie asymétrique maximale",
    Mean: "Milieu",
    MemberOf: "Membre de",
    Members: "Membres",
    Message: "Message",
    MethodConfiguration: "Méthode de configuration",
    Methods: "Méthodes",
    Min: "Min",
    Mine: "Mien",
    MinNode: "Noeud minimum",
    Minor: "Mineur",
    MinSize: "Taille minimale",
    MinSkew: "Inclinaison minimale",
    MinSkewPart: "Partie d'inclinaison minimale",
    Missing: "Manquant",
    MixedNodeStates: "États de nœuds mixtes",
    Modification: "Modification",
    Modified: "Modifié",
    ModifiedUTCGMT: "Modifié (UTC / GMT)",
    Modify: "Modifier",
    MonitorEventName: "Surveiller le nom de l'événement",
    Monitoring: "Surveillance",
    MonitorShotLimit: "Surveiller la limite de lancement",
    MonitorSub: "Surveiller sous",
    Month: "Mois",
    More: "plus",
    MustContainUppercaseAndSymbol: "Doit contenir des majuscules et un symbole",
    NA: "Inapplicable",
    Name: "Nom",
    NameOfEnvironment: "Nom de l'environnement",
    NamePrefix: "Préfix de nom",
    NamePrefixPlaceholder: "certains :: préfixe",
    NetworkAddress: "Adresse de réseau",
    Newest: "Le plus récent",
    NewPassword: "Nouveau mot de passe",
    NoContent: "(Pas de contenu)",
    noDataMessage: "...Zéro lignes...",
    Node: "Noeud",
    NodeGroup: "Groupe de nœuds",
    NoErrorFound: "Aucune erreur trouvée \n",
    NoFilterCriteriaSpecified: "Aucun critère de filtre spécifié.",
    None: "Aucun",
    NoPublishedSize: "Aucune taille publiée",
    Normal: "Normal",
    NoScheduledEvents: "Aucun événement planifié.",
    NoSplit: "Pas de scission",
    NotActive: "Pas actif",
    NothingSelected: "Rien a été sélectionné",
    NotInSuperfiles: "Pas dans les Superfichiers",
    NotSuspended: "Pas suspendu",
    NotSuspendedbyUser: "Non suspendu par l'utilisateur",
    NoWarningFound: "Aucun avertissement trouvé \n",
    NumberofParts: "Nombre de parties",
    NumberofSlaves: "Nombre d'esclaves",
    OK: "Ok",
    Oldest: "Le plus ancien",
    OldPassword: "Ancien mot de passe",
    OmitSeparator: "Omettre le séparateur",
    Only1PackageFileAllowed: "Un seul fichier de package autorisé",
    Open: "Ouvrir",
    OpenConfiguration: "Ouvrir la configuration",
    OpenInNewPage: "Ouvrir dans une nouvelle page",
    OpenInNewPageNoFrame: "Ouvrir dans une nouvelle page (sans portée)",
    OpenLegacyECLWatch: "Ouvrir l'ancient ECL Watch",
    OpenLegacyMode: "Ouvrir (ancien)",
    OpenNativeMode: "Ouvrir (natif)",
    OpenSource: "Open source",
    Operation: "Opération",
    Operations: "Opérations",
    Optimize: "Optimiser",
    Options: "Options",
    OriginalFile: "Fichier original",
    OrphanFile: "Fichiers orphelins",
    OrphanFile2: "Fichiers orphelin",
    OrphanMessage: "Un fichier orphelin comporte des parties de fichier partielles sur le disque. Cependant, un lot complet de parties n'est pas disponible pour construire un fichier logique complet. Il n'y a aucune référence à ces parties de fichier sur le serveur Dali.",
    OSStats: "Statistiques du système d'exploitations",
    Outputs: "Sorties",
    Overview: "Aperçu",
    Overwrite: "Écraser",
    OverwriteMessage: "Certains fichiers existent déjà. Veuillez cocher la case écraser pour continuer.",
    Owner: "Propriétaire",
    PackageContent: "Contenu du package",
    PackageContentNotSet: "Contenu du package non défini",
    PackageMap: "Plan du package",
    PackageMaps: "Plans des packages",
    PackagesNoQuery: "Packages sans requêtes correspondantes",
    ParameterXML: "Paramètre XML",
    Part: "Partie",
    PartMask: "Masque de la partie",
    PartName: "Nom de la partie",
    Parts: "Parties",
    PartsFound: "Parties trouvées",
    PartsLost: "Parties perdues",
    Password: "Mot de passe",
    PasswordExpiration: "Expiration du mot de passe",
    PasswordExpired: "Votre mot de passe a expiré. Veuillez le modifier maintenant.",
    PasswordExpirePostfix: "jour (s). Voulez-vous le changer maintenant?",
    PasswordExpirePrefix: "Votre mot de passe expirera dans",
    PasswordOpenZAP: "Mot de passe pour ouvrir ZAP (optionnel)",
    PasswordsDoNotMatch: "Les mots de passe ne correspondent pas.",
    Path: "Chemin",
    PathMask: "Masque de chemin",
    Pause: "Pause",
    PauseNow: "Pause maintenant",
    PctComplete: "% terminée",
    PercentCompressed: "Pourcentage comprimé",
    PercentDone: "Pourcentage terminé",
    PercentUsed: "% Utilisé",
    PerformingLayout: "Exécution de la mise en page ...",
    Permission: "Autorisation",
    PermissionName: "Nom de l'autorisation",
    Permissions: "Autorisations",
    PhysicalFiles: "Fichiers physiques",
    PhysicalMemory: "Mémoire physique",
    PlaceholderFindText: "Wuid, Utilisateur, (ecl:*, fichier:*, dfu:*, requete:*)...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Platform: "Plate-forme",
    Playground: "Terrain de jeux",
    PleaseEnableCookies: "ECL Watch nécessite l'activation des cookies pour continuer.",
    PleaseEnterANumber: "Veuillez saisir un chiffre 1 -",
    PleaseLogin: "Veuillez vous connecter en utilisant votre nom d'utilisateur et votre mot de passe",
    PleaseLogIntoECLWatch: "Veuillez vous connecter à ECL Watch",
    PleasePickADefinition: "Veuillez choisir une définition",
    PleaseSelectADynamicESDLService: "Veuillez sélectionner un service ESDL dynamique",
    PleaseSelectAGroupToAddUser: "Veuillez sélectionner un groupe auquel ajouter l'utilisateur",
    PleaseSelectAServiceToBind: "Veuillez sélectionner un service à lier",
    PleaseSelectATopologyItem: "Veuillez sélectionner une cible, un service ou une machine.",
    PleaseSelectAUserOrGroup: "Veuillez sélectionner un utilisateur ou un groupe avec un nom de fichier",
    PleaseSelectAUserToAdd: "Veuillez sélectionner un utilisateur à ajouter",
    Plugins: "Plugins",
    Port: "Port",
    Prefix: "Préfixe",
    PrefixPlaceholder: "nom de fichier {: longueur}, taille de fichier {: [B | L] [1-8]}",
    Preflight: "Preflight",
    PreloadAllPackages: "Précharger tous les packages",
    PreserveCompression: "Conserver la compression",
    PressCtrlCToCopy: "Appuyez sur ctrl + c pour copier.",
    Preview: "Aperçu",
    PrimaryLost: "Primaire perdu",
    PrimaryMonitoring: "Surveillance primaire",
    Priority: "Priorité",
    Probability: "Probabilité",
    Process: "Processus",
    Processes: "Processus",
    ProcessesDown: "Processus en panne",
    ProcessFilter: "Filtre de processus",
    ProcessorInformation: "Informations sur le processeur",
    ProgressMessage: "Message d'avancement",
    Properties: "Propriétés",
    Property: "Propriété",
    Protect: "Protéger",
    Protected: "Protégé",
    Protocol: "Protocole",
    Publish: "Publier",
    Published: "Publié",
    PublishedBy: "Publié par",
    PublishedByMe: "Publié par moi",
    PublishedQueries: "Requêtes publiées",
    PushEvent: "Événement push",
    Quarter: "Trimestre",
    Queries: "Requêtes",
    QueriesNoPackage: "Requêtes sans package correspondant",
    Query: "Requête",
    QueryDetailsfor: "Détails de la requête pour",
    QueryID: "ID de requête",
    QueryIDPlaceholder: "som? q * ry.1",
    QueryName: "Nom de la requête",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Ensemble de requêtes",
    Queue: "File d'attente",
    Quote: "Citation",
    QuotedTerminator: "Terminateur cité",
    RawData: "Données brutes",
    RawTextPage: "Texte brut (page actuelle)",
    Ready: "Prêt",
    ReallyWantToRemove: "Voulez-vous vraiment supprimer?",
    ReAuthenticate: "Réauthentifier pour déverrouiller",
    RecordCount: "Nombre de registres",
    RecordLength: "Longueur du registre",
    Records: "Registres",
    RecordSize: "Taille du registre",
    RecordStructurePresent: "Structure de registre présente",
    Recover: "Récupérer",
    RecoverTooltip: "Redémarrer le workunit interrompu / bloqué",
    RecreateQuery: "Recréer la requête",
    Recycling: "Recyclage",
    RedBook: "Livre rouge",
    Refresh: "Rafraîchir",
    ReleaseNotes: "Notes de version",
    Reload: "Recharger",
    Remaining: "Remaining",
    RemoteCopy: "Copie à distance",
    RemoteDali: "Remote Dali",
    RemoteDaliIP: "Adresse IP de Dali à distance",
    Remove: "Supprimer",
    RemoveAttributeQ: "Vous êtes sur le point de supprimer cet attribut. Voulez-vous vraiment le faire?",
    RemoveAtttributes: "Supprimer les attributs",
    RemovePart: "Supprimer la partie",
    RemoveSubfiles: "Supprimer les sous-fichiers",
    RemoveSubfiles2: "Supprimer les sous-fichiers?",
    RemoveUser: "Vous êtes sur le point de vous retirer du groupe:",
    Rename: "Renommer",
    RenderedSVG: "SVG produit",
    RenderSVG: "Produire SVG",
    Replicate: "Reproduire",
    ReplicatedLost: "Répliqué est perdu",
    ReplicateOffset: "Répliquer le décalage",
    Report: "Rapport",
    RepresentsASubset: "représentent un sous-ensemble du nombre total de correspondances. L'utilisation d'un filtre correct peut réduire le nombre de correspondances.",
    RequestSchema: "Schéma de demande",
    RequiredForFixedSpray: "Nécessaire pour dispersion fixe",
    RequiredForXML: "Nécessaire pour disperser XML",
    Reschedule: "Replanifier",
    Reset: "Réinitialiser",
    ResetThisQuery: "Réinitialiser cette requête?",
    ResetViewToSelection: "Réinitialiser la vue à la sélection",
    Resource: "Ressource",
    Resources: "Ressources",
    ResponseSchema: "Schéma de réponse ",
    Restart: "Redémarrer",
    Restarted: "Redémarré",
    Restore: "Restaurer",
    Restricted: "Limité",
    Resubmit: "Renvoyer",
    Resubmitted: "Resoumis",
    ResubmitTooltip: "Soumettre à nouveau le workunit existant",
    Results: "Résultat(s)",
    Resume: "reprendre",
    RetainSuperfileStructure: "Conserver la structure du Superfichier",
    RetypePassword: "Retaper le mot de passe",
    Reverse: "Changer",
    RowPath: "Chemin d'accès à la ligne",
    Rows: "Ligne",
    RowTag: "Ligne d'étiquette",
    RoxieCluster: "Cluster de Roxie",
    RoxieFileCopy: "Statut de copie des fichiers Roxie",
    RoxieState: "Annuler",
    RunningServerStrain: "L'exécution de ce processus peut prendre du temps et entraîner une lourde pression sur les serveurs. Souhaitez-vous continuer?",
    Sample: "Échantillon",
    SampleRequest: "Demande d'échantillon",
    SampleResponse: "Exemple de réponse",
    Save: "Sauver",
    Scope: "Portée",
    SearchResults: "Résultats de recherche",
    SecondsRemaining: "Secondes restantes",
    Security: "Sécurité",
    SelectPackageFile: "Sélectionner un fichier de package",
    SendEmail: "Envoyer un e-mail",
    Separators: "Séparateurs",
    Server: "Serveur",
    ServiceName: "Nom du service",
    Services: "Services",
    ServiceType: "Type de service",
    SetBanner: "Définir la bannière",
    SetTextError: "Impossible d'afficher le texte (trop grand?). Utilisez &lsquo;helpers&rsquo; pour télécharger.",
    SetToFailed: "Définir comme étant échoué",
    SetToolbar: "Définir barre d'outils",
    Severity: "Sévérité",
    ShareWorkunit: "Partage l'URL du Workunit",
    Show: "Afficher",
    ShowProcessesUsingFilter: "Afficher les processus à l'aide d'un filtre",
    ShowSVG: "Afficher SVG",
    Size: "Taille",
    Skew: "Inclinaison",
    SkewNegative: "Inclinaison(-)",
    SkewPositive: "Inclinaison(+)",
    SLA: "SLA",
    SlaveLogs: "Journaux esclaves",
    SlaveNumber: "Numéro d'esclave",
    Slaves: "Esclaves",
    Smallest: "Le plus petit",
    SmallestFile: "Plus petit fichier",
    SmallestSize: "Taille la plus petite",
    SOAP: "SOAP",
    SomeDescription: "Certains * Description",
    somefile: "*::certainsfichier*",
    Source: "Source",
    SourceCode: "Code source",
    SourceLogicalFile: "Indiquer le nom logique",
    SourcePath: "Chemin de la source (caractère générique activé)",
    SourceProcess: "Processus source",
    SparkThor: "SparkThor",
    Spill: "Débordement",
    SplitPrefix: "Préfix divisé",
    Spray: "Disperser",
    Start: "Démarrer",
    Started: "Démarré",
    Starting: "En cours de démarrer",
    State: "État",
    Stats: "Statistiques",
    Status: "État",
    Stopped: "Arrêter",
    Stopping: "En cours d'arrêt",
    StorageInformation: "Stockage d'information",
    Subgraph: "Sous-graphe",
    Subgraphs: "Sous-graphes",
    Submit: "Soumettre",
    Subtype: "Sous-type",
    SuccessfullySaved: "Enregistré avec succès",
    Summary: "Sommaire",
    SummaryMessage: "Message récapitulatif",
    SuperFile: "Super Fichier",
    Superfile: "Superfichier",
    SuperFiles: "Super Fichiers",
    Superfiles: "Superfichiers",
    SuperFilesBelongsTo: "Membre de Superfichier (s)",
    SuperfilesOnly: "Superfichiers seulement",
    SuperOwner: "Super propriétaire",
    Suspend: "Suspendre",
    Suspended: "Suspendu",
    SuspendedBy: "Suspendu par",
    SuspendedByAnyNode: "Suspendu par n'importe quel nœud",
    SuspendedByCluster: "Suspendu par cluster",
    SuspendedByFirstNode: "Suspendu par le premier nœud",
    SuspendedByUser: "Suspendu par utilisateur",
    SuspendedReason: "Raison d'être suspendu",
    SVGSource: "Source SVG",
    SyncSelection: "Synchroniser avec la sélection",
    SystemServers: "Système de serveurs",
    Table: "Table",
    tag: "étiquette",
    Target: "Cible",
    TargetClusters: "Clusters de cibles",
    TargetClustersLegacy: "Clusters de cibles (ancien)",
    TargetName: "Nom du cible",
    TargetNamePlaceholder: "certains :: logique :: nom",
    TargetRowTagRequired: "Vous devez fournir un cible de ligne étiquette",
    Targets: "Cibles",
    TargetScope: "Cible de la portée",
    TargetWuid: "Cible/Wuid",
    Terminators: "Terminateurs",
    TestPages: "Tester les pages",
    Text: "Texte",
    TheReturnedResults: "Les résusltats retournés",
    ThorMasterAddress: "Adresse du maître Thor",
    ThorNetworkAddress: "Adresse réseau Thor",
    ThorProcess: "Thor Processus",
    Time: "Temps",
    Timers: "Minuteurs",
    TimeSeconds: "Temps (secondes)",
    TimeStamp: "Horodatage",
    TimeStarted: "Temps du démarrage",
    TimeStopped: "Temps d'arrêt",
    Timings: "Timings",
    TimingsMap: "Carte Timings",
    title_ActiveGroupPermissions: "Groupes de Permissions Actives",
    title_ActivePermissions: "Permissions Actives",
    title_Activity: "Activité",
    title_AvailableGroupPermissions: "Groupes Permissions Disponibles",
    title_AvailablePermissions: "Permissions Disponibles",
    title_BindingConfiguration: "Configuration de liaison",
    title_BindingDefinition: "Définition de liaison",
    title_Blooms: "Blooms",
    title_ClusterInfo: "Groupes",
    title_Clusters: "Clusters",
    title_CodeGeneratorPermissions: "Permissions de code générateur",
    title_DefinitionExplorer: "Explorateur de définition",
    title_Definitions: "Définitions",
    title_DESDL: "ESDL Dynamique",
    title_DFUQuery: "Fichiers logiques",
    title_DFUWUDetails: "Workunit de DFU",
    title_DirectoriesFor: "Répertoire pour",
    title_DiskUsage: "Utilisation de disk",
    title_ECLPlayground: "Terrain de jeu d'ECL",
    title_ErrorsWarnings: "Erreurs / Avertissements pour",
    title_EventScheduleWorkunit: "Planificateur d'événements",
    title_FileScopeDefaultPermissions: "Autorisations par défaut des fichiers",
    title_FilesPendingCopy: "Fichiers en attente de copie",
    title_FoundFilesFor: "Fichiers trouvés pour",
    title_GetDFUWorkunits: "Workunits de DFU",
    title_Graph: "Graphe",
    title_GraphPage: "Titre",
    title_Graphs: "Graphes",
    title_GridDetails: "Change moi",
    title_History: "Histoire",
    title_HPCCPlatformECL: "ECL Watch - Accueil",
    title_HPCCPlatformFiles: "ECL Watch - Fichiers",
    title_HPCCPlatformMain: "ECL Watch - Accueil",
    title_HPCCPlatformOps: "ECL Watch - Opérations",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
    title_Inputs: "Entrées",
    title_LFDetails: "Détails du fichier logique",
    title_LibrariesUsed: "Bibliothèques utilisées",
    title_Log: "Fichier journal",
    title_LostFilesFor: "Fichiers perdus pour",
    title_LZBrowse: "Zones d'atterrissage",
    title_MemberOf: "Membre de",
    title_Members: "Membres",
    title_Methods: "Méthodes",
    title_OrphanFilesFor: "Fichiers orphelins pour",
    title_PackageParts: "Parties de package",
    title_Permissions: "Permissions",
    title_Preflight: "Mesures du système",
    title_PreflightResults: "Résultats de Preflight",
    title_QuerySetDetails: "Détails de la requête",
    title_QuerySetErrors: "Erreurs",
    title_QuerySetLogicalFiles: "Fichiers logiques",
    title_QuerySetQuery: "Requêtes",
    title_QuerySetSuperFiles: "Super Fichiers",
    title_QueryTest: "Super Fichiers",
    title_Result: "Activités",
    title_Results: "Sorties",
    title_SearchResults: "Résultats de recherche",
    title_SourceFiles: "",
    title_SystemServers: "Système de serveurs",
    title_SystemServersLegacy: "Système de serveurs (ancien)",
    title_TargetClusters: "Clusters cibles",
    title_Topology: "Topologie",
    title_TpThorStatus: "L'état de Thor",
    title_UserPermissions: "Autorisations d'utilisateur",
    title_UserQuery: "Permissions",
    title_WorkunitScopeDefaultPermissions: "Autorisations par défaut des workunits",
    title_WUDetails: "Détails de workunit ECL",
    title_WUQuery: "Workunits ECL",
    To: "à",
    ToDate: "À ce jour",
    Toenablegraphviews: "Pour activer les vues graphiques, veuillez installer le plugin Graph View Control",
    Tooltip: "Info-bulle",
    TooManyFiles: "Trop de fichiers",
    Top: "Haut",
    Topology: "Topologie",
    ToSizes: "Aux tailles",
    Total: "Total",
    TotalClusterTime: "Temps total de cluster",
    TotalParts: "Parties Totales",
    TotalSize: "Taille totale",
    TransitionGuide: "Guide de transition",
    Tree: "Arbre",
    Type: "Type",
    Unbound: "non lié",
    undefined: "indéfini",
    Unknown: "Inconnu",
    Unlock: "Déverrouiller",
    Unprotect: "Annuler",
    UnsupportedIE9FF: "N'est pas supportée (IE <= 9, FireFox)",
    Unsuspend: "Annuler la suspension",
    Unsuspended: "Non suspendu",
    Up: "Up",
    UpdateCloneFrom: "Mettre à jour le clone depuis",
    UpdateDFs: "Mettre à jour DFS",
    UpdateSuperFiles: "Mettre à jour les super fichiers",
    Upload: "Télécharger",
    UpTime: "Durée de fonctionnement",
    URL: "URL",
    Usage: "Usage",
    Used: "Utilisé",
    UsedByWorkunit: "Utilisé par workunit",
    User: "Utilisateur",
    UserDetails: "Détails de l'utilisateur",
    UserID: "ID d'utilisateur",
    UserLogin: "Veuillez vous connecter en utilisant votre nom d'utilisateur uniquement",
    UserName: "Nom d'utilisateur",
    Username: "Nom d'utilisateur",
    UserPermissions: "Autorisations d'utilisateur",
    Users: "Utilisateurs",
    UseSingleConnection: "Utiliser une connexion unique",
    Validate: "Valider",
    ValidateActivePackageMap: "Valider la carte du package actif",
    ValidatePackageContent: "Valider le contenu du package",
    ValidatePackageMap: "Valider la carte des packages",
    ValidateResult: "===== Valider le résultat ===== \n\n",
    ValidateResultHere: "(Résultat de validation)",
    Validating: "En cours de valider",
    Value: "Valeur",
    Variable: "Variable",
    VariableBigendian: "Big-endian variable",
    Variables: "Variables",
    VariableSourceType: "Type de Source",
    Version: "Version",
    ViewByScope: "Afficher par portée",
    Views: "Vues",
    ViewSparkClusterInfo: "Afficher les informations du cluster Spark",
    Visualize: "Visualiser",
    WarnIfAvailableDiskSpaceIsUnder: "Avertir si l'espace disque disponible est insuffisant",
    WarnIfAvailableMemoryIsUnder: "Avertir si la mémoire disponible est insuffisante",
    WarnIfCPUUsageIsOver: "Avertir si l'utilisation du processeur est terminée",
    Warning: "Avertissement",
    Warnings: "Avertissement(s)",
    WarnOldGraphControl: "Avertissement: Ancien Graph Control",
    What: "Quoi",
    Where: "Où",
    Who: "Qui",
    Width: "Largeur",
    Workflows: "Flux de travail",
    Workunit: "Workunit",
    Workunits: "Workunits",
    WorkUnitScopeDefaultPermissions: "Autorisations par défaut de l'étendue du workunit",
    Wrap: "Emballage",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "WUID peut pas être vide.",
    WUSnapShot: "Snap Shot de WU",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Année",
    YouAreAboutToBeLoggedOut: "Vous êtes sur le point de vous déconnecter",
    YouAreAboutToDeleteBinding: "Vous êtes sur le point de supprimer cette liaison. Voulez-vous vraiment le faire?",
    YouAreAboutToDeleteDefinition: "Vous êtes sur le point de supprimer cette définition. Voulez-vous vraiment le faire?",
    YouAreAboutToDeleteThisFile: "Vous êtes sur le point de supprimer ce fichier. Voulez-vous vraiment le faire?",
    YouAreAboutToDeleteThisPart: "Vous êtes sur le point de supprimer cette ou ces parties. Voulez-vous vraiment le faire?",
    YouAreAboutToDeleteThisQueryset: "Vous êtes sur le point de supprimer cet ensemble de requêtes. Voulez-vous vraiment le faire?",
    YouAreAboutToDeleteThisWorkunit: "Vous êtes sur le point de supprimer cette unité de travail. Voulez-vous vraiment le faire?",
    YouAreAboutToRemoveUserFrom: "Vous êtes sur le point de supprimer un ou des utilisateurs de ce groupe. Voulez-vous continuer?",
    YourBrowserMayNotSupport: "Votre navigateur peut ne pas prendre en charge les fichiers de cette taille",
    YourScreenWasLocked: "Votre écran a été verrouillé par ESP. Veuillez récupérer vos données, car elles peuvent être périmées.",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Zéro fichier logique (vérifier le filtre)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Package d'analyse zippé",
    Zoom: "Zoom",
    Zoom100Pct: "Zoom 100%",
    ZoomAll: "Zoom tout",
    ZoomMinus: "Zoom -",
    ZoomPlus: "Zoom +",
    ZoomWidth: "Largeur du zoom"
}