define(
({
    Abort: "Abortar",
    AbortedBy: "Abortado pelo",
    AbortedTime: "Hora de Abortar",
    About: "Sobre Plataforma HPCC",
    AboutGraphControl: "Sobre Controle de Gráphico",
    AboutHPCCSystemsGraphControl: "Sobre Controle de Gráphico do HPCC Systems®",
    Account: "Conta",
    Action: "Ação",
    Activate: "Ativar",
    Activated: "Ativa",
    Active: "Ativa",
    ActivePackageMap: "Package Map Ativo",
    ActiveWorkunit: "Tarefa Ativa",
    Activities: "Atividades",
    Activity: "Atividade",
    ActivityMap: "Mapa de Atividade",
    ActualSize: "Tamanho Efectivo",
    Add: "Adicionar",
    AddAttributes2: "Adiciona atributos",
    AddAttributes: "Adiciona atributos/valores para seu métedo",
    AddBinding: "Adiciona ligação",
    AddFile: "Adicionar Arquivo",
    AddGroup: "Adicionar Grupo",
    AddPart: "Adicionar Parte",
    AdditionalResources: "Recursos Adicionais",
    AddProcessMap: "Adicionar Package Map",
    AddTheseFilesToDali: "Adicionar esses arquivos a Dali",
    AddtionalProcessesToFilter: "Processos adicionais para filtrar",
    AddToExistingSuperfile: "Adicionar a um superfile existente",
    AddToSuperfile: "Adicionar ao Superarquivo",
    AddUser: "Adicionar Usuário",
    Advanced: "Avançado",
    All: "Todos",
    AllowAccess: "Permitir Acesso",
    AllowForeignFiles: "Permitir Arquivos Remotos",
    AllowFull: "Permissão Total",
    AllowRead: "Permissão de Leitura",
    AllowWrite: "Permissão de Escrita",
    AllQueuedItemsCleared: "Todos os itens em fila foram apagados. O trabalho em execução atual continuará a ser rodado",
    ANY: "Qualquer",
    AnyAdditionalProcessesToFilter: "Quaisquer processos adicionais para filtrar",
    Append: "Anexar",
    AppendCluster: "Acrescentar o Cluster",
    Apply: "Aplicar",
    ArchivedOnly: "Apenas Arquivadas",
    Attach: "Anexar",
    ArchivedWarning: "Aviso: Por favor especifique intervalos de datas menore. Caso contrário, a operação para buscar workunits pode demorar causando um erro no navegador.",
    Attribute: "Attributo",
    AttributesAreRequired: "Atributos são necessários",
    AutoRefresh: "Recarregar Automático",
    AutoRefreshEvery: "Atualização automática a cada x minutos",
    AutoRefreshIncrement: "Auto Incrementar Atualização",
    Back: "voltar",
    BannerColor: "Cor da Faixa",
    BannerMessage: "Mensagem da Faixa",
    BannerScroll: "Faixa de Paginação",
    BannerSize: "Tamanho da Faixa",
    BinaryInstalls: "Instalação Binária",
    Binding: "Ligação",
    BindingDeleted: "Ligação deletado",
    Blob: "BLOB",
    BlobPrefix: "Prefixo do BLOB",
    Bottom: "fundo",
    Busy: "Ocupado",
    Cancel: "Cancelar",
    CancelAll: "Cancela tudo",
    CancelAllMessage: "Abortar trabalhos em execução e limpar a fila. Você deseja continuar?",
    CheckAllNodes: "Verifique Todos os Nós",
    CheckFilePermissions: "Verifique Permissão de Arquivo",
    CheckSingleNode: "Verifique Nó Singular",
    Clear: "Limpar",
    ClearPermissionsCache: "Limpar Cache de Permissões",
    ClearPermissionsCacheConfirm: "Tem certeza que você quer limpar todos os caches de permissões dos servidores DALI e ESP? Workunits em execução podem ter a performance significantemente prejudicadas até que os caches tenham sido recarregados.",
    Clone: "Clonar",
    ClonedWUID: "WUID clonado",
    CloneTooltip: "Unidade de Trabalho Duplicado",
    Close: "Fechar",
    Cluster: "Cluster (Aglomerado)",
    ClusterName: "Nome do Aglomerado (Cluster)",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Processos de Aglomerados",
    Code: "Código",
    CodeGenerator: "Gerador de Código",
    Col: "Col",
    CollapseAll: "Recolher Tudo",
    Command: "Comando",
    Comment: "Comentário",
    Completed: "Completo",
    ComplexityWarning: "Mais de {limite} atividades ({Contador de atividades}) - suprimir amostragem inicial?",
    Component: "Componente",
    Compress: "Compactar",
    Compressed: "Comprimido",
    CompressedFileSize: "Tamanho do Arquivo Comprimido",
    Condition: "Condição",
    Configuration: "Configuração",
    ConfirmPassword: "Confirmar Senha",
    ConfirmRemoval: "Tem certeza que quer fazer isso?",
    ContactAdmin: "Se você deseja renomear este grupo, por favor, entre em contato com o administrador do LDAP",
    Content: "Conteúdo",
    Contents: "Conteúdo",
    ContentType: "Tipo de Conteúdo",
    Copy: "Copiar",
    Count: "Conta",
    CreateANewFile: "Criar um novo superfile",
    Created: "Criado",
    Critical: "Crítico",
    CSV: "CVS",
    Dali: "Dali",
    DaliIP: "IP do Dali",
    dataset: ":=dataset*",
    Date: "Data",
    Day: "Dia",
    Deactivate: "Desativar",
    Debug: "Debug",
    DEF: "DEF",
    Defaults: "Padrões",
    Definition: "Definição",
    Definitions: "Definições",
    Delete: "Remover",
    DeleteBinding: "Apagar Ligação",
    Deleted: "Removido",
    DeletedBinding: "Ligação Apagado",
    DeleteDirectories: "Remover diretórios vazios. Você deseja continuar?",
    DeleteEmptyDirectories: "Excluir diretórios vazios?",
    DeletePrevious: "Apagar Anterior",
    DeleteSelectedFiles: "Apagar Arquivos Selecionados?",
    DeleteSelectedGroups: "Remover Grupos Selecionados",
    DeleteSelectedPermissions: "Remover Permissões Selecionadas",
    DeleteSelectedQueries: "Apagar Consultas Selecionadas?",
    DeleteSelectedUsers: "Remover Usuários Selecionados",
    DeleteSelectedWorkunits: "Apagar Tarefas Selecionadas?",
    DeleteSuperfile2: "Remover Super Arquivo",
    DeleteSuperfile: "Apagar Super Arquivo?",
    DeleteThisPackage: "Remover Este Pacote",
    Delimited: "Delimitado",
    DenyAccess: "Bloquear",
    DenyFull: "Bloquear Completamente",
    DenyRead: "Bloquear Leitura",
    DenyWrite: "Bloquear Escrita",
    Depth: "Profundidade",
    DepthTooltip: "Profundidade Máxima de Subgrafo",
    Deschedule: "Desagendar",
    DescheduleSelectedWorkunits: "Desagendar Unidades de Trabalho Selecionadas",
    Description: "Descrição",
    DESDL: "Dynamic ESDL",
    Despray: "Despray (Consolidar Dados dos Nós)",
    Details: "Detalhes",
    DFUServerName: "Nome do Servidor DFU",
    DFUWorkunit: "DFU Unidade de Trabalho",
    Directories: "Diretórios",
    Directory: "Diretório",
    DisableScopeScanConfirm: "Tem certeza que quer desabilitar busca de escopo? Alterações de configuração serão aplicadas quando DALI reiniciar.",
    DisableScopeScans: "Desabilitar busca de escopo",
    DiskUsage: "Uso de disco",
    Distance: "Distancia",
    DistanceTooltip: "Distância a vizinhança de máxima atividade",
    Dll: "Dll (Biblioteca de Vínculo Dinâmico)",
    DOT: "DOT",
    DOTAttributes: "Propriedades de DOT",
    Down: "Pra baixo",
    Download: "Baixar",
    Downloads: "Abaixamentos",
    DownloadToCSV: "Transferir para o CSV",
    DropZone: "Zona de entrada de arquivos",
    Duration: "Duração",
    DynamicNoServicesFound: "Nenhum Serviço Encontrado",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "ECL Unidade de Trabalho",
    Edges: "Bordas",
    Edit: "Alterar",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar Propriedades do Gráfico",
    EditXGMML: "Editar XGMML",
    EmployeeID: "ID do Empregado",
    Empty: "Vazio",
    Enable: "Ativar",
    EnableScopeScans: "Ativar busca de escopo",
    EnableScopeScansConfirm: "Tem certeza que gostaria de ativar busca de escopo? Alterações serão aplicadas quando DALI reiniciar.",
    EnglishQ: "Inglês?",
    EnterAPercentage: "Digite uma porcentagem",
    EnterAPercentageOrMB: "Digite uma porcentagem ou MB",
    EraseHistory: "Apagar História",
    EraseHistoryQ: "Apagar o histórico para",
    Error: "Error",
    Errorparsingserverresult: "Erro interpretando o resultado do servidor",
    Errors: "Erros",
    ErrorsStatus: "Erros/Estados",
    ErrorUploadingFile: "Erro ao carregar arquivos. Tente verificar permissões.",
    ErrorWarnings: "Error/Aviso(s)",
    Escape: "Escape",
    ESPBuildVersion: "Versão‎ do ESP",  // jshint ignore:line
    ESPNetworkAddress: "Endereço de Rede do ESP",
    EventName: "Nome do Evento",
    EventNamePH: "Nome do Evento",
    EventScheduler: "Gerenciador de Evento",
    EventText: "Texto do Evento",
    EventTextPH: "Texto do Evento",
    Exception: "Exceção",
    ExpandAll: "Expandir Tudo",
    Export: "Exportar",
    ExportSelectionsToList: "Exportar Seleções para Lista",
    FailIfNoSourceFile: "Falha em caso de arquivo sem fonte",
    Fatal: "Fatal",
    Fetched: "Buscado",
    FetchingData: "Buscando dados...",
    fetchingresults: "Buscando Resultados",
    File: "Arquivo",
    FileCluster: "Arquivos Cluster",
    FileCounts: "Número de Arquivos",
    FileName: "Nome do Arquivo",
    FileParts: "Partes do Arquivo",
    FilePath: "Caminho e nome do Arquivo",
    FilePermission: "Permissão de Arquivo",
    Files: "Arquivos",
    FileScopeDefaultPermissions: "Permissão Padrão de Arquivo Escopo",
    FileScopes: "Escopo de arquivos",
    FileSize: "Tamanho do Arquivo",
    FilesNoPackage: "Arquivos sem definição de pacotes.",
    FilesPending: "Arquivos pendentes",
    FilesWithUnknownSize: "Arquivos com tamanho desconhecido",
    FileType: "Tipo de Arquivo",
    FileUploader: "Uploader(Enviador) de Arquivo",
    FileUploadStillInProgress: "Carregamento de Arquivo em andamento",
    Filter: "Filtro",
    FilterSet: "Conjunto Filtro",
    Find: "Busca",
    FindNext: "Próxima Busca",
    FindPrevious: "Busca Anterior",
    Finished: "Completo",
    FirstName: "Primeiro Nome",
    FirstNRows: "Primeiras N Linhas",
    Fixed: "Fixo",
    Folder: "Pasta",
    Format: "Formato",
    Forums: "Bate Papos",
    Forward: "Avançar",
    FoundFile: "Arquivo Encontrado",
    FoundFileMessage: "Um arquivo encontrado tem todas as suas partes no disco que não são referenciadas no servidor Dali. Todas as partes do arquivo são contabilizadas para que possam ser adicionadas de volta ao servidor Dali. Eles também podem ser excluídos do cluster, se for necessário.",
    FromDate: "Data Inicial",
    FromSizes: "Tamanho Mínimo",
    FromTime: "Tempo inicial",
    FullName: "Nome Completo",
    Generate: "Gerar",
    GetPart: "Obter Parte",
    GetSoftwareInformation: "Obter Informações de Software",
    Graph: "Grafo",
    Graphs: "Gráficos",
    GraphView: "Visão Gráfica",
    Group: "Grupo",
    GroupBy: "Agrupado por",
    GroupDetails: "Detalhe de Grupo",
    Grouping: "Agrupar",
    GroupName: "Nome do Grupo",
    GroupPermissions: "Permissões de Grupo",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Essa area exibi o mapas de arvores (hierarquias) para o gráfico dessa tarefa. O tamanho e cor indicam a duração de cada gráfico (Quanto maior e mais escuro mais tempo levou)",
    Helper: "Ajudante",
    Helpers: "Ajudantes",
    Hex: "Hex",
    HexPreview: "Pré-visualização Hex",
    HideSpills: "Esconde Derramamentos",
    High: "Alto",
    History: "História",
    HPCCSystems: "HPCCSystems",
    Icon: "Ícone",
    ID: "ID",
    Inactive: "Inativo",
    IncludeSlaveLogs: "Incluie logs escravos",
    Index: "Índice",
    Info: "Info",
    InfoDialog: "Caixa de Informação",
    InheritedPermissions: "Permissão Herdada",
    Inputs: "Insumos",
    InvalidResponse: "(resposta inválida)",
    IP: "IP",
    IPAddress: "Endereço IP",
    IsCompressed: "É Comprimido",
    IsLibrary: "Biblioteca?",
    IsReplicated: "É Replica?",
    IssueReporting: "Reportagem de Problemas",
    Jobname: "Nome da Tarefa",
    JobName: "Nome da Tarefa",
    jsmi: "jsmi*",
    JSmith: "JSilva*",
    JSON: "JSON",
    KeyFile: "Arquivo Chave",
    Label: "Rótulo de Texto",
    LandingZone: "Zona de Entrada de Arquivos",
    LandingZones: "Zona de entrada de arquivos",
    LanguageFiles: "Arquivo de Línguas",
    Largest: "Maior",
    LargestFile: "Maior Arquivo",
    LargestSize: "Maior Tamanho",
    LastMessage: "Última Mensagem",
    LastName: "Sobrenome",
    LastNDays: "Ultimos N Dias",
    LastNHours: "Últimas N Horas",
    LastNRows: "Últimas N Filas",
    LastRun: "Última Rodada",
    LDAPWarning: "<b>Error do serviço de LDAP</b> &lsquo;Número de usuários excedido&rsquo;. Por favor use um filtro.",
    LegacyForm: "Formato Antigo",
    LibrariesUsed: "Usa Biblioteca?",
    LibraryName: "Nome da biblioteca",
    Line: "Linha",
    LineTerminators: "Terminador de linhas",
    Links: "Links",
    Loading: "Carregando",
    LoadingCachedLayout: "Carregando diagrama do cache",
    LoadingData: "Carragando Dados...",
    loadingMessage: "...carregando...",
    LoadPackageContentHere: "(Carregue conteúdo de pacote aqui)",
    LoadPackageFromFile: "Carregar pacote de arquivo",
    Local: "Local",
    LocalFileSystemsOnly: "Somente Sistemas de Arquivos Locais",
    Location: "Localização",
    Log: "Log",
    LogFile: "Arquivo de log",
    LoggedInAs: "Entrou no sistema como",
    LogicalFile: "Arquivo Lógico",
    LogicalFiles: "Arquivos Lógicos",
    LogicalFilesAndSuperfiles: "Arquivos (super e lógicos)",
    LogicalFilesOnly: "Somente arquivos lógicos",
    LogicalFileType: "Tipo de Arquivo Lógico",
    LogicalName: "Nome Lógico",
    Logs: "Logs",
    log_analysis_1: "log_analysis_1*",
    LostFile2: "Arquivos perdidos",
    LostFile: "Arquivo perdido",
    LostFileMessage: "Um arquivo lógico que está faltando pelo menos uma parte de arquivo em ambos os locais primário e replicado em armazenamento. O arquivo lógico ainda é referenciado no servidor Dali. A exclusão do arquivo remove a referência do servidor Dali e de quaisquer partes restantes no disco.",
    Low: "Baixo",
    MachineInformation: "Informação da máquina",
    Machines: "Máquinas",
    Major: "Principal",
    ManagedBy: "Gerenciado Por",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Pressione Ctrl+C",
    ManualOverviewSelection: "(Seleção manual será necessária)",
    ManualTreeSelection: "(Seleção manual de árvore será requerida)",
    Mappings: "Mapeamento",
    Mask: "Mask (bloqueador de caracteres)",
    Max: "Max",
    MaximumNumberOfSlaves: "Numero de esclavo",
    MaxNode: "Nó Max",
    MaxRecordLength: "Maximo tamanho do registro",
    MaxSize: "Tamanho máximo",
    MemberOf: "Membro de",
    Members: "Membros",
    Message: "Mensagem",
    MethodConfiguration: "Configuração do Método",
    Methods: "Métodos",
    Min: "Min",
    MinNode: "Nó Min",
    Minor: "Menor",
    MinSize: "Tamanho mínimo",
    Missing: "Não encontrado",
    MixedNodeStates: "Estados de Nós misturados",
    Modification: "Modificação",
    Modified: "Modificado",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nome do Evento do Monitorador",
    Monitoring: "Monitorador",
    MonitorShotLimit: "Limite do Monitorador",
    MonitorSub: "Sub do Monitorador",
    Month: "Mês",
    More: "Mais",
    MustContainUppercaseAndSymbol: "Deve conter símbolo e caracteres maiúsculos",
    NA: "N/A",
    Name: "Nome",
    NamePrefix: "Prefixo de nome",
    NamePrefixPlaceholder: "algum::prefixo",
    Newest: "Mais recente",
    NewPassword: "Senha Nova",
    NoContent: "(sem conteúdo)",
    noDataMessage: "... Zero linhas...",
    Node: "Nó (Node)",
    NodeGroup: "Grupo de Nós",
    NoErrorFound: "Nenhum Erro Encontrado",
    NoFilterCriteriaSpecified: "Filtro não especificado",
    None: "Nenhum",
    NoPublishedSize: "Nenhum tamanho publicado",
    Normal: "Normal",
    NoScheduledEvents: "Eventos agendados não encontrados",
    NoSplit: "Sem Separador",
    NotActive: "Inativo",
    NothingSelected: "Nada Selecionado",
    NotInSuperfiles: "Não encontrado em super arquivo",
    NotSuspendedbyUser: "Não suspenso por usuário",
    NoWarningFound: "Nenhuma Advertência Encontrada",
    NumberofParts: "Numero de Partes",
    NumberofSlaves: "Número de Escravos",
    OK: "Aceitar",
    Oldest: "Mais Antigo",
    OldPassword: "Senha antiga",
    OmitSeparator: "Omitir Separador",
    Only1PackageFileAllowed: "Somente one arquivo de pacote permitido",
    Open: "Abrir",
    OpenInNewPage: "Abrir em página nova",
    OpenInNewPageNoFrame: "Abrir em página nova (sem quadro)",
    OpenLegacyECLWatch: "Abrir Antigo ECL Watch",
    OpenLegacyMode: "Modo Legado Aberto",
    OpenNativeMode: "Modo Nativo Aberto",
    OpenSafeMode: "Abrir em Modo de Segurança",
    OpenSource: "Código Público",
    OpenTreeMode: "Abrir (modo árvore)",
    Operation: "Operação",
    Operations: "Operações",
    Options: "Opções",
    OriginalFile: "Arquivo Originál",
    OrphanFile2: "Arquivo órfão",
    OrphanFile: "Arquivos órfãos",
    OrphanMessage: "Um arquivo órfão tem partes de arquivo parcial no disco. No entanto, um conjunto completo de peças não está disponível para construir um arquivo lógico e completo. Isso não faz referência a essas partes de arquivo no servidor Dali.",
    Outputs: "Resultados",
    Overview: "Visão Geral",
    Overwrite: "Overwrite",
    OverwriteMessage: "Alguns arquivos já existem. Selecione opção de escrever por cima para continuar.",
    Owner: "Proprietário",
    PackageContent: "Conteúdo de pacote",
    PackageContentNotSet: "Conteúdo de pacote não definido",
    PackageMap: "Mapa de Pacotes",
    PackageMaps: "Mapas do Pacote de Dados",
    PackagesNoQuery: "Pacotes sem queries",
    ParameterXML: "Parametro XML",
    Part: "Parte",
    PartMask: "Parte Máscara",
    PartName: "Nome da Parte",
    Parts: "Partes",
    PartsFound: "Pedaços Encontradas",
    PartsLost: "Pedaços Perdidas",
    Password: "Senha",
    PasswordExpiration: "Validade da Senha",
    PasswordExpired: "Sua senha não é mais válida. Por favor altere agora.",
    PasswordExpirePostfix: "dia(s). Quer trocar agora?",
    PasswordExpirePrefix: "Senha válida até",
    PasswordOpenZAP: "Senha para abrir ZAP (opicional)",
    PasswordsDoNotMatch: "Senhas não são as mesmas",
    Path: "Caminho",
    PathMask: "Bloqueador do Caminho",
    Pause: "Pausar",
    PauseNow: "Pausar agora",
    PctComplete: "% Completo",
    PercentCompressed: "Percentagem Comprimida",
    PercentDone: "Percentual Completo",
    PerformingLayout: "Executando Layout...",
    Permission: "Permissão",
    PermissionName: "Nome da Permissão",
    Permissions: "Permissões",
    PhysicalFiles: "Arquivos Físicos",
    PlaceholderFindText: "Wuid, Usuário‎, Mais...",  // jshint ignore:line
    PlaceholderFirstName: "João",
    PlaceholderLastName: "da Silva",
    Playground: "Area de Recreio",
    PleaseEnterANumber: "Por favor digite o número 1 -",
    PleasePickADefinition: "Por favor, escolha uma definição",
    PleaseSelectADynamicESDLService: "Selecione um serviço ESDL dinâmico",
    PleaseSelectAGroupToAddUser: "Por favor, selecione um grupo para adicionar o usuário a",
    PleaseSelectATopologyItem: "Selecione um alvo, serviço ou máquina.",
    PleaseSelectAUserOrGroup: "Por favor selecione um usário ou grupo junto com um nome de arquivo",
    PleaseSelectAUserToAdd: "Por favor, selecione um usuário para adicionar",
    Plugins: "Plugins",
    Port: "Port",
    Prefix: "Prefixo",
    PrefixPlaceholder: "&lsquo;nomedoarquivo{:comprimento}, tamanho{:[B|L][1-8]}&rsquo;",
    Preflight: "Pré-vôo",
    PreloadAllPackages: "Precarregar Todos os Pacotes",
    PreserveCompression: "Manter Arquivo Comprimido",
    Preview: "Prévia",
    PrimaryLost: "Principal Perdido",
    PrimaryMonitoring: "Monitorador Principal",
    Priority: "Prioridade",
    Process: "Processo",
    Processes: "Processos",
    ProcessFilter: "Filtro de Processo",
    ProcessorInformation: "Informações do Processador",
    ProgressMessage: "Mensagem de Progresso",
    Properties: "Propriedades",
    Property: "Propriedade",
    Protect: "Proteger",
    Protected: "Protegido",
    Publish: "Publicado",
    Published: "Publicado",
    PublishedBy: "Publicado por",
    PublishedQueries: "Consultas de ECL Publicadas",
    PushEvent: "Evento de publicação",
    Quarter: "Quarto",
    Queries: "Consultas ECL",
    QueriesNoPackage: "Queries sem pacote",
    Query: "Query",
    QueryDetailsfor: "Detalhes para",
    QueryID: "Query ID",
    QueryIDPlaceholder: "some?q*ry.1",
    QueryName: "Nome da Query",
    QueryNamePlaceholder: "Minha?Su?erQ*ry",
    QuerySet: "Grupo de Consultas",
    Queue: "Fila",
    Quote: "Aspas",
    QuotedTerminator: "Terminador em Aspas",
    RawTextPage: "Texto original (página atual)",
    Ready: "Pronto",
    ReallyWantToRemove: "Realmente quer remover?",
    RecordCount: "Numero de Registros",
    RecordLength: "Tamanho do Registro",
    Records: "Registros",
    RecordSize: "Tamanho do Registro",
    RecordStructurePresent: "Estrutura de registro disponível",
    Recover: "Recuperar",
    RecoverTooltip: "Reniciar unidade de trabalho pausado / bloqueado",
    Recycling: "Reciclando",
    RedBook: "Red Book",
    Refresh: "Recarregar",
    ReleaseNotes: "Notas de Versão",
    Reload: "Recarregar",
    Remaining: "Faltando",
    RemoteCopy: "Cópia Remota",
    RemoteDali: "Dali Remota",
    RemoteDaliIP: "IP Dali Remoto",
    Remove: "Remover",
    RemoveAttributeQ: "Você está prestes a remover esse atributo. Você tem certeza de que quer fazer isso?",
    RemoveAtttributes: "Remover Atributo (s)",
    RemovePart: "Remover parte",
    RemoveSubfiles2: "Remover Subfile (s)?",
    RemoveSubfiles: "Remover sub-arquivo(s)",
    RemoveUser: "Você está próximo de remover-se do grupo",
    Rename: "Renomear",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Renderização SVG",
    Replicate: "Replicar",
    ReplicatedLost: "Replicado Perdido",
    ReplicateOffset: "Replicar o Deslocamento",
    RepresentsASubset: "Representar un subconjunto de todas los casamientos. Usando un filtro correcto puede reducir el numero de casamientos",
    RequestSchema: "Schema da Busca",
    RequiredForXML: "Manditório para spray de dados em XML",
    Reschedule: "Reagendar",
    Reset: "Limpar",
    ResetThisQuery: "Restaurar esta Pesquisa?",
    ResetViewToSelection: "Restaurar Visão da seleção",
    Resource: "Recurso",
    Resources: "Recursos",
    ResponseSchema: "Schema da Resposta",
    Restart: "Restart",
    Restarted: "Recomeçar",
    Restore: "Restaurar",
    Resubmit: "Resubmeter",
    Resubmitted: "Submeter de novo",
    ResubmitTooltip: "Submeter unidade de trabalho de novo",
    Results: "Resultado(s)",
    Resume: "Continue",
    RetainSuperfileStructure: "Preservar Estrutura do Super Arquivo",
    RetypePassword: "Digite senha de novo",
    Reverse: "Reverter",
    RowPath: "linha de acesso",
    Rows: "Linhas",
    RowTag: "Nome da Linha",
    RoxieCluster: "Roxie Cluster (Aglomerado)",
    RoxieFileCopy: "Estado de Cópia de Archivos Roxie",
    RunningServerStrain: "Executar este processo pode demorar muito tempo e vai sobrecarregar os servidores. Você quer continuar?",
    Sample: "Amostra",
    SampleRequest: "Amostra da Busca",
    SampleResponse: "Amostra de Resposta",
    Save: "Salvar",
    Scope: "Escopo",
    SearchResults: "Resultado da Busca",
    SecondsRemaining: "Segundos Restantes",
    Security: "Segurança",
    SelectPackageFile: "Selecione pacote que arquivos",
    Separators: "Seperadores",
    Services: "Serviços",
    Server: "Servidor",
    SetBanner: "Fixar Banner",
    SetTextError: "Erro para mostrar texto(muito longo?)  Use &lsquo;ajuda&rsquo; para baixar",
    SetToFailed: "Indicar como Falhado",
    Severity: "Severidade",
    Show: "Exibir",
    ShowProcessesUsingFilter: "Mostrar processos usando filtro",
    ShowSVG: "Mostrar SVG",
    Size: "Tamanho",
    Skew: "Distorção",
    SkewNegative: "Inclinar (-)",
    SkewPositive: "Inclinar (+)",
    SLA: "SLA",
    SlaveLogs: "Logs escravos",
    SlaveNumber: "Numero de esclavo",
    Slaves: "Escravos",
    Smallest: "Menor",
    SmallestFile: "Arquivo Menor",
    SmallestSize: "Menor tamanho",
    SOAP: "SOAP",
    SomeDescription: "Alguma descrição",
    somefile: "*::algum_arquivo*",
    Source: "Fonte",
    SourceCode: "Código Fonte",
    SourceLogicalFile: "Nome Lógica do arquivo Fonte",
    SourcePath: "fonte de acesso",
    SourceProcess: "fonte de processo",
    Spill: "Regar",
    SplitPrefix: "Prefixo de separação",
    Spray: "Spray (Distribuir aos Nós)",
    Start: "Começar",
    Started: "Início",
    Starting: "Iniciando",
    State: "Estado",
    Stats: "Estatísticas",
    Status: "estado",
    Stopped: "Parado",
    Stopping: "Parando",
    StorageInformation: "Informações de armazenamento",
    Subgraph: "Sugrafo",
    Subgraphs: "Subgráfico",
    Submit: "Submeter",
    Subtype: "Subtipo",
    SuccessfullySaved: "Guardado com sucesso",
    Summary: "Resumo",
    SummaryMessage: "Mensagem de Resumo",
    Superfile: "Super Arquivo",
    SuperFile: "Super Arquivo",
    Superfiles: "Super Arquivos",
    SuperFiles: "Super Arquivos",
    SuperFilesBelongsTo: "Membro do(s) Super Arquivo(s)",
    SuperfilesOnly: "Apenas Super Arquivos",
    SuperOwner: "Dono Super",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SuspendedByCluster: "Interrompido pelo Bloco",
    SuspendedByUser: "Interrompido pelo Usuário",
    SuspendedReason: "Razão para interrupção",
    SVGSource: "Fonte de SVG",
    Sync: "Sync",
    SyncSelection: "Sincronizar seleção",
    SystemServers: "Servidores do Sistema",
    tag: "tag",
    Target: "Destino",
    TargetClusters: "Aglomeragos de Destino(Alvos)",
    TargetName: "Nome do Destino",
    TargetNamePlaceholder: "algum::lógico::arquivo",
    TargetRowTagRequired: "Tag Obrigatório de Registro de Destino",
    Targets: "Alvos",
    TargetScope: "Escopo de Destino",
    TargetWuid: "Unidade de trabalho alvo",
    Terminators: "Terminadores",
    TestPages: "Páginas de Teste",
    Text: "Texto",
    TheReturnedResults: "Os Resultados Devolvidos",
    ThorMasterAddress: "Endereço de metre thor",
    ThorNetworkAddress: "Endereço de Rede do Thor",
    ThorProcess: "Processo de Thor",
    Time: "Tempo",
    Timers: "Controladores de tempo",
    TimeSeconds: "Tempo (Segundos)",
    TimeStamp: "Timestamp",
    TimeStarted: "Início",
    TimeStopped: "Fim",
    Timings: "Medidas de Tempo",
    TimingsMap: "Mapa das Medidas de Tempo",
    title_ActiveGroupPermissions: "Permissão de Grupo Ativo",
    title_ActivePermissions: "Permissão Ativo",
    title_Activity: "Atividate",
    title_AvailableGroupPermissions: "Permissão de Grupos Disponiveis",
    title_AvailablePermissions: "Permissão Disponiveis",
    title_ClusterInfo: "grupos",
    title_CodeGeneratorPermissions: "Permissões de Gerador de Código",
    title_Definitions: "Definições",
    title_DESDL: "ESDL dinâmica",
    title_DFUQuery: "Arquivos Lógicos",
    title_DFUWUDetails: "Tarefa DFU",
    title_DirectoriesFor: "Diretórios para",
    title_DiskUsage: "uso de disco",
    title_ECLPlayground: "ECL Playground",
    title_ErrorsWarnings: "Erros / Avisos para",
    title_EventScheduleWorkunit: "Escalonador de eventos",
    title_DefinitionExplorer: "Explorador de definição",
    title_FilesPendingCopy: "Arquivos pendentes de cópia",
    title_FileScopeDefaultPermissions: "Permissão Padrão de Arquivos",
    title_FoundFilesFor: "Arquivos encontrados para",
    title_GetDFUWorkunits: "Tarefas DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "Título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Change Me",
    title_History: "História",
    title_HPCCPlatformECL: "ECL Watch - Página Inicial",
    title_HPCCPlatformFiles: "ECL Watch - Arquivos",
    title_HPCCPlatformMain: "ECL Watch - Página Inicial",
    title_HPCCPlatformOps: "ECL Watch - Operações",
    title_HPCCPlatformOpsWidget: "ECL Watch - Operações",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Adaptadores",
    title_Inputs: "Entradas",
    title_LFDetails: "Detalhes dos Arquivos Lógicos",
    title_LibrariesUsed: "Bibliotecas usadas",
    title_Log: "arquivo de registro",
    title_LostFilesFor: "Arquivos perdidos para",
    title_LZBrowse: "Zona de Entrada de Arquivos",
    title_MemberOf: "Membros de",
    title_Members: "Membros",
    title_Methods: "Métodos",
    title_OrphanFilesFor: "Arquivos órfãos para",
    title_PackageParts: "Pacote de peças",
    title_Permissions: "Permissões",
    title_PreflightResults: "Resultados Pré-vôo",
    title_QuerySetDetails: "Detalhes da Consulta ECL",
    title_QuerySetErrors: "Erros",
    title_QuerySetLogicalFiles: "Arquivos Lógicos",
    title_QuerySetQuery: "Consultas ECL",
    title_QuerySetSuperFiles: "Super Arquivos",
    title_QueryTest: "Super Arquivos",
    title_Result: "Resultados",
    title_Results: "Atividade",
    title_SearchResults: "Resultados de busca",
    title_SourceFiles: "Arquivo(s) da Fonte",
    title_Topology: "Topologia",
    title_TpThorStatus: "Estado de Thor",
    title_UserPermissions: "Permissões de usuário",
    title_UserQuery: "Permissões",
    title_WorkunitScopeDefaultPermissions: "Permissão Padrão de Unidades de Trabalho",
    title_WUDetails: "Detalhes da Tarefa ECL",
    title_WUQuery: "Tarefas de ECL",
    To: "Para",
    ToDate: "Data Final",
    Toenablegraphviews: "Para ativar visão gráfica, por favor instalar o plugin",
    Tooltip: "Tooltip",
    TooManyFiles: "Inumeros Arquivos",
    Top: "Topo",
    Topology: "Topologia",
    ToSizes: "Tamanho Máximo",
    TotalClusterTime: "Tempo total do bloco",
    TotalParts: "Pedaços totais",
    TotalSize: "Tamanho total",
    TotalThorTime: "Tempo Total do Thor",
    TransitionGuide: "Guia de transição",
    Tree: "Árvore",
    Type: "Tipo",
    undefined: "undefined",
    Unknown: "Unknown",
    Unprotect: "Desprotege",
    UnsupportedIE9FF: "Não Supportado",
    Unsuspend: "Reativar",
    Unsuspended: "Reativado",
    Up: "Cima",
    UpdateSuperFiles: "Actualizar superfile",
    Upload: "Enviar",
    Usage: "Uso",
    Used: "Usado",
    User: "Usuário",
    UserDetails: "Detalhes do usuário",
    UserID: "Identificação do usurario",
    Username: "Nome do usuário",
    UserName: "Nome do usuário",
    UserPermissions: "Permissão do Usuário",
    Users: "Usuários",
    UseSingleConnection: "Usar Conexão Única",
    Validate: "Validar",
    ValidateActivePackageMap: "Validar pacote de mapa ativo",
    ValidatePackageContent: "Validar pacote de conteúdo",
    ValidatePackageMap: "Validar pacote de mapa",
    ValidateResult: "=====Validar Resultado=====\n\n",
    ValidateResultHere: "Validar resultados",
    Value: "Valor",
    Variable: "Variável",
    VariableBigendian: "Variavel Big-edian",
    Variables: "Variáveis",
    VariableSourceType: "Tipo de fonte",
    Version: "Versão",
    ViewByScope: "Visão por escopo",
    Views: "Visões",
    Visualize: "Visualize",
    WarnIfAvailableDiskSpaceIsUnder: "Avisar se o espaço disponível em disco estiver abaixo de",
    WarnIfAvailableMemoryIsUnder: "Avisar se a memória disponível está abaixo de",
    WarnIfCPUUsageIsOver: "Avisar se o uso da CPU está além",
    Warning: "Atenção",
    Warnings: "Avisos",
    WarnOldGraphControl: "Alerta: Controle de grafico velho",
    What: "O que",
    Where: "Onde",
    Who: "Quem",
    Width: "Largura",
    Workflows: "Fluxo de Trabalho",
    Workunit: "Tarefa",
    Workunits: "Tarefas",
    WorkUnitScopeDefaultPermissions: "Permisos por defect de alcaces de Workunit",
    Wrap: "Wrap",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid não pode estar vazia",
    WUSnapShot: "WU Snap Shot",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Ano",
    YouAreAboutToDeleteBinding: "Está prestes a eliminar esta ligação. Você tem certeza que quer fazer isso?",
    YouAreAboutToRemoveUserFrom: "Usted esta a punto de quitar un(os) usuario(s) de este grupo. ¿Desea continuar?",
    YourBrowserMayNotSupport: "O seu navegador provavelmente não supporta arquivo(s) deste tamanho",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nenhum Arquivo Lógico (verifique filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Pacote de Análise Zipped",
    Zoom100Pct: "Zoom 100%",
    Zoom: "Zoom",
    ZoomAll: "Zoom Completo",
    ZoomWidth: "comprimento do Zoom"
})
);
