define(
({
    Abort: "Abortar",
    About: "Sobre Plataforma HPCC",
    AboutGraphControl: "Sobre Controle de Gráphico",
    AboutHPCCSystemsGraphControl: "Sobre Controle de Gráphico do HPCC Systems®",
    Action: "Ação",
    Activate: "Ativar",
    Activated: "Ativa",
    Active: "Ativa",
    ActivePackageMap: "Package Map Ativo",
    ActiveWorkunit: "Tarefa Ativa",
    Activities: "Atividades",
    Activity: "Atividade",
    ActualSize: "Tamanho Efectivo",
    Add: "Adicionar",
    AddFile: "Adicionar Arquivo",
    AddGroup: "Adicionar Grupo",
    AdditionalResources: "Recursos Adicionais",
    AddProcessMap: "Adicionar Package Map",
    AddToSuperfile: "Adicionar ao Superarquivo",
    AddUser: "Adicionar Usuário",
    Advanced: "Avançado",
    All: "Todos",
    AllowAccess: "Permitir Acesso",
    AllowForeignFiles: "Permitir Arquivos Remotos",
    AllowFull: "Permissão Total",
    AllowRead: "Permissão de Leitura",
    AllowWrite: "Permissão de Escrita",
    ANY: "Qualquer",
    Append: "Anexar",
    Apply: "Aplicar",
    ArchivedOnly: "Apenas Arquivadas",
    ArchivedWarning: "Aviso: Por favor especifique intervalos de datas menore. Caso contrário, a operação para buscar workunits pode demorar causando um erro no navegador.",
    AutoRefresh: "Recarregar Automático",
    Back: "voltar",
    BannerColor: "Cor da Faixa",
    BannerMessage: "Mensagem da Faixa",
    BannerScroll: "Faixa de Paginação",
    BannerSize: "Tamanho da Faixa",
    BinaryInstalls: "Instalação Binária",
    Blob: "BLOB",
    BlobPrefix: "Prefixo do BLOB",
    Bottom: "fundo",
    Cancel: "Cancelar",
    Clear: "Limpar",
    ClearPermissionsCache: "Limpar Cache de Permissões",
    ClearPermissionsCacheConfirm: "Tem certeza que você quer limpar todos os caches de permissões dos servidores DALI e ESP? Workunits em execução podem ter a performance significantemente prejudicadas até que os caches tenham sido recarregados.",
    Clone: "Clonar",
    ClonedWUID: "WUID clonado",
    Close: "Fechar",
    Cluster: "Aglomerado (Cluster)",
    Cluster: "Cluster (Aglomerado)",
    ClusterName: "Nome do Aglomerado (Cluster)",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Processos de Aglomerados",
    Code: "Código",
    CodeGenerator: "Gerador de Código",
    Col: "Col",
    CollapseAll: "Recolher Tudo",
    Command: "Comando",
    Comment: "Comentário",
    Completed: "Completo",
    ComplexityWarning: "Mais de {limite} atividades ({Contador de atividades}) - suprimir amostragem inicial?",
    Component: "Componente",
    Compress: "Compactar",
    Compressed: "Comprimido",
    CompressedFileSize: "Tamanho do Arquivo Comprimido",
    Configuration: "Configuração",
    ConfirmPassword: "Confirmar Senha",
    ConfirmRemoval: "Tem certeza que quer fazer isso?",
    Content: "Conteúdo",
    Contents: "Conteúdo",
    ContentType: "Tipo de Conteúdo",
    Copy: "Copiar",
    Count: "Conta",
    Created: "Criado",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Data",
    Day: "Dia",
    Deactivate: "Desativar",
    Debug: "Debug",
    DEF: "DEF",
    Delete: "Remover",
    Deleted: "Removido",
    DeleteSelectedFiles: "Apagar Arquivos Selecionados?",
    DeleteSelectedGroups: "Remover Grupos Selecionados",
    DeleteSelectedPermissions: "Remover Permissões Selecionadas",
    DeleteSelectedQueries: "Apagar Consultas Selecionadas?",
    DeleteSelectedUsers: "Remover Usuários Selecionados",
    DeleteSelectedWorkunits: "Apagar Tarefas Selecionadas?",
    DeleteSuperfile2: "Remover Super Arquivo",
    DeleteSuperfile: "Apagar Super Arquivo?",
    DeleteThisPackage: "Remover Este Pacote",
    Delimited: "Delimitado",
    DenyAccess: "Bloquear",
    DenyFull: "Bloquear Completamente",
    DenyRead: "Bloquear Leitura",
    DenyWrite: "Bloquear Escrita",
    Depth: "Profundidade",
    DepthTooltip: "Profundidade Máxima de Subgrafo",
    Deschedule: "Desagendar",
    DescheduleSelectedWorkunits: "Desagendar Unidades de Trabalho Selecionadas",
    Description: "Descrição",
    Despray: "Despray (Consolidar Dados dos Nós)",
    Details: "Detalhes",
    DFUServerName: "Nome do Servidor DFU",
    DFUWorkunit: "DFU Unidade de Trabalho",
    Directory: "Diretório",
    DisableScopeScanConfirm: "Tem certeza que quer desabilitar busca de escopo? Alterações de configuração serão aplicadas quando DALI reiniciar.",
    DisableScopeScans: "Desabilitar busca de escopo",
    DiskUsage: "Uso de disco",
    Distance: "Distancia",
    DistanceTooltip: "Distância a vizinhança de máxima atividade",
    Dll: "Dll (Biblioteca de Vínculo Dinâmico)",
    DOT: "DOT",
    DOTAttributes: "Propriedades de DOT",
    Down: "Pra baixo",
    Download: "Baixar",
    DropZone: "Zona de entrada de arquivos",
    Duration: "Duração",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "ECL Unidade de Trabalho",
    Edges: "Bordas",
    Edit: "Alterar",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar Propriedades do Gráfico",
    EditXGMML: "Editar XGMML",
    Empty: "Vazio",
    Enable: "Ativar",
    EnableScopeScans: "Ativar busca de escopo",
    EnableScopeScansConfirm: "Tem certeza que gostaria de ativar busca de escopo? Alterações serão aplicadas quando DALI reiniciar.",
    EnglishQ: "Inglês?",
    Error: "Error",
    Errorparsingserverresult: "Erro interpretando o resultado do servidor",
    Errors: "Erros",
    ErrorsStatus: "Erros/Estados",
    ErrorWarnings: "Error/Aviso(s)",
    Escape: "Escape",
    ESPBuildVersion: "Versão‎ do ESP",
    ESPNetworkAddress: "Endereço de Rede do ESP",
    EventName: "Nome do Evento",
    EventNamePH: "Nome do Evento",
    EventScheduler: "Gerenciador de Evento",
    EventText: "Texto do Evento",
    EventTextPH: "Texto do Evento",
    Exception: "Exceção",
    ExpandAll: "Expandir Tudo",
    Export: "Exportar",
    FailIfNoSourceFile: "Falha em caso de arquivo sem fonte",
    FetchingData: "Buscando dados...",
    fetchingresults: "Buscando Resultados",
    File: "Arquivo",
    FileCounts: "Número de Arquivos",
    FileName: "Nome do Arquivo",
    FileParts: "Partes do Arquivo",
    FilePath: "Caminho e nome do Arquivo",
    Files: "Arquivos",
    FileScopes: "Escopo de arquivos",
    FileSize: "Tamanho do Arquivo",
    FilesNoPackage: "Arquivos sem definição de pacotes.",
    FilesWithUnknownSize: "Arquivos com tamanho desconhecido",
    FileType: "Tipo de Arquivo",
    FileUploader: "Uploader(Enviador) de Arquivo",
    FileUploadStillInProgress: "Carregamento de Arquivo em andamento",
    Filter: "Filtro",
    Find: "Busca",
    FindNext: "Próxima Busca",
    FindPrevious: "Busca Anterior",
    Finished: "Completo",
    FirstName: "Primeiro Nome",
    FirstNRows: "Primeiras N Linhas",
    Fixed: "Fixo",
    Folder: "Pasta",
    Format: "Formato",
    Forward: "Avançar",
    FromDate: "Data Inicial",
    FromSizes: "Tamanho Mínimo",
    FromTime: "Tempo inicial",
    FullName: "Nome Completo",
    Graph: "Grafo",
    Graphs: "Gráficos",
    GraphView: "Visão Gráfica",
    Group: "Grupo",
    GroupBy: "Agrupado por",
    GroupDetails: "Detalhe de Grupo",
    Grouping: "Agrupar",
    GroupName: "Nome do Grupo",
    GroupPermissions: "Permissões de Grupo",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Essa area exibi o mapas de arvores (hierarquias) para o gráfico dessa tarefa. O tamanho e cor indicam a duração de cada gráfico (Quanto maior e mais escuro mais tempo levou)",
    Helpers: "Ajudantes",
    Hex: "Hex",
    HexPreview: "Pré-visualização Hex",
    High: "Alto",
    History: "História",
    HPCCSystems: "HPCCSystems",
    ID: "ID",
    Inactive: "Inativo",
    Index: "Índice",
    Info: "Info",
    InfoDialog: "Caixa de Informação",
    Inputs: "Insumos",
    InvalidResponse: "(resposta inválida)",
    IP: "IP",
    IPAddress: "Endereço IP",
    IsLibrary: "Biblioteca?",
    IsReplicated: "É Replica?",
    Jobname: "Nome da Tarefa",
    JobName: "Nome da Tarefa",
    jsmi: "jsmi*",
    JSmith: "JSilva*",
    JSON: "JSON",
    Label: "Rótulo de Texto",
    LandingZone: "Zona de Entrada de Arquivos",
    LandingZones: "Zona de entrada de arquivos",
    LanguageFiles: "Arquivo de Línguas",
    Largest: "Maior",
    LargestFile: "Maior Arquivo",
    LargestSize: "Maior Tamanho",
    LastName: "Sobrenome",
    LastNDays: "Ultimos N Dias",
    LastNHours: "Últimas N Horas",
    LastNRows: "Últimas N Filas",
    LDAPWarning: "<b>Error do serviço de LDAP</b> 'Número de usuários excedido'. Por favor use um filtro.",
    LegacyForm: "Formato Antigo",
    LibrariesUsed: "Usa Biblioteca?",
    LibraryName: "Nome da biblioteca",
    Line: "Linha",
    LineTerminators: "Terminador de linhas",
    Links: "Links",
    Loading: "Carregando",
    LoadingCachedLayout: "Carregando diagrama do cache",
    LoadingData: "Carragando Dados...",
    loadingMessage: "...carregando...",
    LoadPackageContentHere: "(Carregue conteúdo de pacote aqui)",
    LoadPackageFromFile: "Carregar pacote de arquivo",
    Local: "Local",
    Log: "Log",
    LogFile: "Arquivo de log",
    LoggedInAs: "Entrou no sistema como",
    LogicalFile: "Arquivo Lógico",
    LogicalFiles: "Arquivos Lógicos",
    LogicalFilesAndSuperfiles: "Arquivos (super e lógicos)",
    LogicalFilesOnly: "Somente arquivos lógicos",
    LogicalFileType: "Tipo de Arquivo Lógico",
    LogicalName: "Nome Lógico",
    Logs: "Logs",
    log_analysis_1: "log_analysis_1*",
    Low: "Baixo",
    ManualCopy: "Pressione Ctrl+C",
    ManualOverviewSelection: "(Seleção manual será necessária)",
    ManualTreeSelection: "(Seleção manual de árvore será requerida)",
    Mappings: "Mapeamento",
    Mask: "Mask (bloqueador de caracteres)",
    Max: "Max",
    MaxRecordLength: "Maximo tamanho do registro",
    MemberOf: "Membro de",
    Members: "Membros",
    Message: "Mensagem",
    Min: "Min",
    Missing: "Não encontrado",
    MixedNodeStates: "Estados de Nós misturados",
    Modification: "Modificação",
    Modified: "Modificado",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nome do Evento do Monitorador",
    Monitoring: "Monitorador",
    MonitorShotLimit: "Limite do Monitorador",
    MonitorSub: "Sub do Monitorador",
    Month: "Mês",
    More: "Mais",
    MustContainUppercaseAndSymbol: "Deve conter símbolo e caracteres maiúsculos",
    NA: "N/A",
    Name: "Nome",
    NamePrefix: "Prefixo de nome",
    NamePrefixPlaceholder: "algum::prefixo",
    Newest: "Mais recente",
    NewPassword: "Senha Nova",
    NoContent: "(sem conteúdo)",
    noDataMessage: "... Zero linhas...",
    Node: "Nó (Node)",
    NodeGroup: "Grupo de Nós",
    NoErrorFound: "Nenhum Erro Encontrado",
    NoFilterCriteriaSpecified: "Filtro não especificado",
    None: "Nenhum",
    Normal: "Normal",
    NoScheduledEvents: "Eventos agendados não encontrados",
    NoSplit: "Sem Separador",
    NotActive: "Inativo",
    NothingSelected: "Nada Selecionado",
    NotInSuperfiles: "Não encontrado em super arquivo",
    NotSuspendedbyUser: "Não suspenso por usuário",
    NoWarningFound: "Nenhuma Advertência Encontrada",
    NumberofParts: "Numero de Partes",
    OK: "Aceitar",
    Oldest: "Mais Antigo",
    OldPassword: "Senha antiga",
    OmitSeparator: "Omitir Separador",
    Only1PackageFileAllowed: "Somente one arquivo de pacote permitido",
    Open: "Abrir",
    OpenInNewPage: "Abrir em página nova",
    OpenInNewPageNoFrame: "Abrir em página nova (sem quadro)",
    OpenLegacyECLWatch: "Abrir Antigo ECL Watch",
    OpenSafeMode: "Abrir em Modo de Segurança",
    OpenSource: "Código Público",
    OpenTreeMode: "Abrir (modo árvore)",
    Operations: "Operações",
    Options: "Opções",
    Outputs: "Resultados",
    Overview: "Visão Geral",
    Overwrite: "Overwrite",
    OverwriteMessage: "Alguns arquivos já existem. Selecione opção de escrever por cima para continuar.",
    Owner: "Proprietário",
    PackageContent: "Conteúdo de pacote",
    PackageContentNotSet: "Conteúdo de pacote não definido",
    PackageMap: "Mapa de Pacotes",
    PackageMaps: "Mapas do Pacote de Dados",
    PackagesNoQuery: "Pacotes sem queries",
    ParameterXML: "Parametro XML",
    Part: "Parte",
    Parts: "Partes",
    Password: "Senha",
    PasswordExpiration: "Validade da Senha",
    PasswordExpired: "Sua senha não é mais válida. Por favor altere agora.",
    PasswordExpirePostfix: "dia(s). Quer trocar agora?",
    PasswordExpirePrefix: "Senha válida até",
    PasswordOpenZAP: "Senha para abrir ZAP (opicional)",
    PasswordsDoNotMatch: "Senhas não são as mesmas",
    Path: "Caminho",
    PathMask: "Bloqueador do Caminho",
    Pause: "Pausar",
    PauseNow: "Pausar agora",
    PctComplete: "% Completo",
    PercentDone: "Percentual Completo",
    PerformingLayout: "Executando Layout...",
    PermissionName: "Nome da Permissão",
    Permissions: "Permissões",
    PlaceholderFindText: "Wuid, Usuário‎, Mais...",
    PlaceholderFirstName: "João",
    PlaceholderLastName: "da Silva",
    Playground: "Area de Recreio",
    Plugins: "Plugins",
    Port: "Port",
    Prefix: "Prefixo",
    PrefixPlaceholder: "'nomedoarquivo{:comprimento}, tamanho{:[B|L][1-8]}'",
    PreserveCompression: "Manter Arquivo Comprimido",
    Preview: "Prévia",
    PrimaryMonitoring: "Monitorador Principal",
    Priority: "Prioridade",
    Process: "Processo",
    ProcessFilter: "Filtro de Processo",
    ProgressMessage: "Mensagem de Progresso",
    Properties: "Propriedades",
    Property: "Propriedade",
    Protect: "Proteger",
    Protected: "Protegido",
    Publish: "Publicado",
    Published: "Publicado",
    PublishedBy: "Publicado por",
    PublishedQueries: "Consultas de ECL Publicadas",
    PushEvent: "Evento de publicação",
    Quarter: "Quarto",
    Queries: "Consultas ECL",
    QueriesNoPackage: "Queries sem pacote",
    Query: "Query",
    QueryDetailsfor: "Detalhes para",
    QueryID: "Query ID",
    QueryIDPlaceholder: "some?q*ry.1",
    QueryName: "Nome da Query",
    QueryNamePlaceholder: "Minha?Su?erQ*ry",
    QuerySet: "Grupo de Consultas",
    Queue: "Fila",
    Quote: "Aspas",
    QuotedTerminator: "Terminador em Aspas",
    RawTextPage: "Texto original (página atual)",
    RecordCount: "Numero de Registros",
    RecordLength: "Tamanho do Registro",
    Records: "Registros",
    RecordSize: "Tamanho do Registro",
    RecordStructurePresent: "Estrutura de registro disponível",
    Recover: "Recuperar",
    Refresh: "Recarregar",
    ReleaseNotes: "Notas de Versão",
    Reload: "Recarregar",
    Remaining: "Faltando",
    RemoteCopy: "Cópia Remota",
    RemoteDali: "Dali Remota",
    RemoteDaliIP: "IP Dali Remoto",
    Remove: "Remover",
    RemoveSubfiles: "Remover sub-arquivo(s)",
    RemoveUser: "Você está próximo de remover-se do grupo",
    Rename: "Renomear",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Renderização SVG",
    Replicate: "Replicar",
    RequestSchema: "Schema da Busca",
    Reschedule: "Reagendar",
    Reset: "Limpar",
    ResetThisQuery: "Restaurar esta Pesquisa?",
    ResetViewToSelection: "Restaurar Visão da seleção",
    Resource: "Recurso",
    Resources: "Recursos",
    ResponseSchema: "Schema da Resposta",
    Restart: "Restart",
    Restarted: "Recomeçar",
    Restore: "Restaurar",
    Resubmit: "Resubmeter",
    Resubmitted: "Submeter de novo",
    Results: "Resultado(s)",
    Resume: "Continue",
    RetainSuperfileStructure: "Preservar Estrutura do Super Arquivo",
    RetypePassword: "Digite senha de novo",
    Reverse: "Reverter",
    RowPath: "linha de acesso",
    Rows: "Linhas",
    RowTag: "Nome da Linha",
    RoxieCluster: "Roxie Cluster (Aglomerado)",
    Sample: "Amostra",
    SampleRequest: "Amostra da Busca",
    SampleResponse: "Amostra de Resposta",
    Save: "Salvar",
    Scope: "Escopo",
    SearchResults: "Resultado da Busca",
    SecondsRemaining: "Segundos Restantes",
    Security: "Segurança",
    SelectPackageFile: "Selecione pacote que arquivos",
    Separators: "Seperadores",
    SetBanner: "Fixar Banner",
    SetTextError: "Erro para mostrar texto(muito longo?)  Use 'ajuda' para baixar",
    SetToFailed: "Indicar como Falhado",
    Severity: "Severidade",
    Show: "Exibir",
    ShowSVG: "Mostrar SVG",
    Size: "Tamanho",
    Skew: "Distorção",
    SLA: "SLA",
    Slaves: "Slaves",
    Smallest: "Menor",
    SmallestFile: "Arquivo Menor",
    SmallestSize: "Menor tamanho",
    SOAP: "SOAP",
    SomeDescription: "Alguma descrição",
    somefile: "*::algum_arquivo*",
    somefile: "*::somefile",
    Source: "Fonte",
    SourceCode: "Código Fonte",
    SourcePath: "fonte de acesso",
    SourceProcess: "fonte de processo",
    SplitPrefix: "Prefixo de separação",
    Spray: "Spray (Distribuir aos Nós)",
    Start: "Começar",
    Started: "Início",
    State: "Estado",
    Stats: "Estatísticas",
    Status: "estado",
    Stopped: "Parado",
    Subgraphs: "Subgráfico",
    Submit: "Submeter",
    Subtype: "Subtipo",
    Summary: "Resumo",
    SummaryMessage: "Mensagem de Resumo",
    Superfile: "Super Arquivo",
    SuperFile: "Super Arquivo",
    Superfiles: "Super Arquivos",
    SuperFiles: "Super Arquivos",
    SuperFilesBelongsTo: "Membro do(s) Super Arquivo(s)",
    SuperfilesOnly: "Apenas Super Arquivos",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SuspendedByCluster: "Interrompido pelo Bloco",
    SuspendedByUser: "Interrompido pelo Usuário",
    SuspendedReason: "Razão para interrupção",
    SVGSource: "Fonte de SVG",
    Sync: "Sync",
    SyncSelection: "Sincronizar seleção",
    SystemServers: "Servidores do Sistema",
    tag: "tag",
    Target: "Destino",
    TargetClusters: "Aglomeragos de Destino(Alvos)",
    TargetName: "Nome do Destino",
    TargetNamePlaceholder: "algum::lógico::arquivo",
    TargetScope: "Escopo de Destino",
    TargetWuid: "Unidade de trabalho alvo",
    Terminators: "Terminadores",
    TestPages: "Páginas de Teste",
    Text: "Texto",
    ThorMasterAddress: "Endereço de metre thor",
    ThorNetworkAddress: "Endereço de Rede do Thor",
    Time: "Tempo",
    Timers: "Controladores de tempo",
    TimeSeconds: "Tempo (Segundos)",
    TimeStarted: "Início",
    TimeStopped: "Fim",
    Timings: "Medidas de Tempo",
    TimingsMap: "Mapa das Medidas de Tempo",
    title_Activity: "Atividate",
    title_ClusterInfo: "grupos",
    title_DFUQuery: "Arquivos Lógicos",
    title_DFUWUDetails: "Tarefa DFU",
    title_DiskUsage: "uso de disco",
    title_ECLPlayground: "ECL Playground",
    title_EventScheduleWorkunit: "Escalonador de eventos",
    title_GetDFUWorkunits: "Tarefas DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "Título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Change Me",
    title_HPCCPlatformECL: "ECL Watch - Página Inicial",
    title_HPCCPlatformFiles: "ECL Watch - Arquivos",
    title_HPCCPlatformMain: "ECL Watch - Página Inicial",
    title_HPCCPlatformOps: "ECL Watch - Operações",
    title_HPCCPlatformOpsWidget: "ECL Watch - Operações",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Adaptadores",
    title_Inputs: "Entradas",
    title_LFDetails: "Detalhes dos Arquivos Lógicos",
    title_LibrariesUsed: "Bibliotecas usadas",
    title_Log: "arquivo de registro",
    title_LZBrowse: "Zona de Entrada de Arquivos",
    title_MemberOf: "Membros de",
    title_Members: "Membros",
    title_QuerySetDetails: "Detalhes da Consulta ECL",
    title_QuerySetErrors: "Erros",
    title_QuerySetLogicalFiles: "Arquivos Lógicos",
    title_QuerySetQuery: "Consultas ECL",
    title_QuerySetSuperFiles: "Super Arquivos",
    title_QueryTest: "Super Arquivos",
    title_Result: "Resultados",
    title_Results: "Atividade",
    title_SearchResults: "Resultados de busca",
    title_SourceFiles: "Arquivo(s) da Fonte",
    title_Topology: "Topologia",
    title_TpThorStatus: "Estado de Thor",
    title_UserPermissions: "Permissões de usuário",
    title_UserQuery: "Permissões",
    title_WUDetails: "Detalhes da Tarefa ECL",
    title_WUQuery: "Tarefas de ECL",
    To: "Para",
    ToDate: "Data Final",
    Toenablegraphviews: "Para ativar visão gráfica, por favor instalar o plugin",
    Top: "Topo",
    Topology: "Topologia",
    ToSizes: "Tamanho Máximo",
    TotalClusterTime: "Tempo total do bloco",
    TotalSize: "Tamanho total",
    TotalThorTime: "Tempo Total do Thor",
    TransitionGuide: "Guia de transição",
    Tree: "Árvore",
    Type: "Tipo",
    undefined: "undefined",
    Unknown: "Unknown",
    Unprotect: "Desprotege",
    UnsupportedIE9FF: "Não Supportado",
    Unsuspend: "Reativar",
    Unsuspended: "Reativado",
    Up: "Cima",
    Upload: "Enviar",
    Usage: "Uso",
    Used: "Usado",
    User: "Usuário",
    UserDetails: "Detalhes do usuário",
    UserID: "Identificação do usurario",
    UserName: "Nome do usuário",
    Username: "Nome do usuário",
    UserPermissions: "Permissão do Usuário",
    Users: "Usuários",
    UseSingleConnection: "Usar Conexão Única",
    Validate: "Validar",
    ValidateActivePackageMap: "Validar pacote de mapa ativo",
    ValidatePackageContent: "Validar pacote de conteúdo",
    ValidatePackageMap: "Validar pacote de mapa",
    ValidateResult: "=====Validar Resultado=====\n\n",
    ValidateResultHere: "Validar resultados",
    Value: "Valor",
    Variable: "Variável",
    VariableBigendian: "Variavel Big-edian",
    Variables: "Variáveis",
    VariableSourceType: "Tipo de fonte",
    Version: "Versão",
    ViewByScope: "Visão por escopo",
    Views: "Visões",
    Visualize: "Visualize",
    Warnings: "Avisos",
    WarnOldGraphControl: "Alerta: Controle de grafico velho",
    What: "O que",
    Where: "Onde",
    Who: "Quem",
    Width: "Largura",
    Workflows: "Fluxo de Trabalho",
    Workunit: "Tarefa",
    Workunits: "Tarefas",
    Wrap: "Wrap",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid não pode estar vazia",
    WUSnapShot: "WU Snap Shot",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Ano",
    YourBrowserMayNotSupport: "O seu navegador provavelmente não supporta arquivo(s) deste tamanho",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nenhum Arquivo Lógico (verifique filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Pacote de Análise Zipped",
    Zoom: "Zoom",
    Zoom100Pct: "Zoom 100%",
    ZoomAll: "Zoom Completo",
    ZoomWidth: "comprimento do Zoom"
})
);
