define(
({
    Abort: "Abortar",
    About: "Sobre Plataforma HPCC",
    AboutGraphControl: "Sobre Controle de Gráphico",
    AboutHPCCSystemsGraphControl: "Sobre Controle de Gráphico do HPCC Systems",
    Action: "Ação",
    Activate: "Ativar",
    Activated: "Ativa",
    Active: "Ativa",
    ActiveWorkunit: "Tarefa Ativa",
    Activities: "Atividades",
    Activity: "Atividade",
    ActualSize: "Tamanho Efectivo",
    Add: "Adicionar",
    AddToSuperfile: "Adicionar ao Superarquivo",
    Advanced: "Avançado",
    Append: "Anexar",
    ArchivedOnly: "Apenas Arquivadas",
    BinaryInstalls: "Instalação Binária",
    Cancel: "Cancelar",
    Clone: "Clonar",
    Close: "Fechar",
    Cluster: "Aglomerado (Cluster)",
    Cluster: "Cluster (Aglomerado)",
    ClusterName: "Nome do Aglomerado (Cluster)",
    ClusterProcesses: "Processos de Aglomerados",
    Code: "Código",
    Col: "Col",
    Command: "Comando",
    Comment: "Comentário",
    Completed: "Completo",
    Component: "Componente",
    Compress: "Compactar",
    Contents: "Conteúdo",
    Copy: "Copiar",
    Count: "Conta",
    Created: "Criado",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Data",
    Deactivate: "Desativar",
    DEF: "DEF",
    DeleteSelectedFiles: "Apagar Arquivos Selecionados?",
    DeleteSelectedQueries: "Apagar Consultas Selecionadas?",
    DeleteSelectedWorkunits: "Apagar Tarefas Selecionadas?",
    DeleteSuperfile: "Apagar Super Arquivo?",
    Delimited: "Delimitado",
    Depth: "Profundidade",
    Deschedule: "Desagendar",
    Description: "Descrição",
    Despray: "Despray (Consolidar Dados dos Nós)",
    DFUServerName: "Nome do Servidor DFU",
    Directory: "Diretório",
    Distance: "Distancia",
    Dll: "Dll (Biblioteca de Vínculo Dinâmico)",
    DOT: "DOT",
    DOTAttributes: "Propriedades de DOT",
    Download: "Baixar",
    DropZone: "Zona de entrada de arquivos",
    Duration: "Duração",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "Bordas",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar Propriedades do Gráfico",
    EditXGMML: "Editar XGMML",
    Error: "Error",
    Errorparsingserverresult: "Erro interpretando o resultado do servidor",
    Errors: "Erros",
    ErrorsStatus: "Erros/Estados",
    ErrorWarnings: "Error/Aviso(s)",
    Escape: "Escape",
    ESPBuildVersion: "Versão‎ do ESP",
    ESPNetworkAddress: "Endereço de Rede do ESP",
    FetchingData: "Buscando dados...",
    fetchingresults: "Buscando Resultados",
    File: "Arquivo",
    FileName: "Nome do Arquivo",
    FileParts: "Partes do Arquivo",
    FilePath: "Caminho e nome do Arquivo",
    Files: "Arquivos",
    FileSize: "Tamanho do Arquivo",
    FileUploader: "Uploader(Enviador) de Arquivo",
    Find: "Busca",
    FindNext: "Próxima Busca",
    FindPrevious: "Busca Anterior",
    Fixed: "Fixo",
    Format: "Formato",
    FromDate: "Data Inicial",
    FromSizes: "Tamanho Mínimo",
    Graphs: "Gráficos",
    GraphView: "Visão Gráfica",
    Group: "Grupo",
    GroupName: "Nome do Grupo",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Essa area exibi o mapas de arvores (hierarquias) para o gráfico dessa tarefa. O tamanho e cor indicam a duração de cada gráfico (Quanto maior e mais escuro mais tempo levou)",
    Helpers: "Ajudantes",
    HexPreview: "Pré-visualização Hex",
    History: "História",
    ID: "ID",
    Info: "Info",
    InfoDialog: "Caixa de Informação",
    Inputs: "Insumos",
    IP: "IP",
    IPAddress: "Endereço IP",
    IsLibrary: "Biblioteca?",
    Jobname: "Nome da Tarefa",
    JobName: "Nome da Tarefa",
    jsmi: "jsmi*",
    JSmith: "JSilva*",
    JSON: "JSON",
    Label: "Rótulo de Texto",
    LandingZone: "Zona de Entrada de Arquivos",
    LandingZones: "Zona de entrada de arquivos",
    LastNDays: "Ultimos N Dias",
    LegacyForm: "Formato Antigo",
    LibrariesUsed: "Usa Biblioteca?",
    Line: "Linha",
    LineTerminators: "Terminador de linhas",
    Links: "Links",
    LoadingData: "Carragando Dados...",
    Local: "Local",
    LoggedInAs: "Entrou no sistema como",
    LogicalFile: "Arquivo Lógico",
    LogicalFiles: "Arquivos Lógicos",
    LogicalFileType: "Tipo de Arquivo Lógico",
    LogicalName: "Nome Lógico",
    log_analysis_1: "log_analysis_1*",
    Mappings: "Mapeamento",
    Mask: "Mask (bloqueador de caracteres)",
    Max: "Max",
    MaxRecordLength: "Maximo tamanho do registro",
    Message: "Mensagem",
    Min: "Min",
    Modification: "Modificação",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nome do Evento do Monitorador",
    MonitorShotLimit: "Limite do Monitorador",
    MonitorSub: "Sub do Monitorador",
    NA: "N/A",
    Name: "Nome",
    Node: "Nó (Node)",
    NoFilterCriteriaSpecified: "Filtro não especificado",
    NoSplit: "Sem Separador",
    NumberofParts: "Numero de Partes",
    OK: "Aceitar",
    OmitSeparator: "Omitir Separador",
    OpenLegacyECLWatch: "Abrir Antigo ECL Watch",
    OpenSafeMode: "Abrir em Modo de Segurança",
    Operations: "Operações",
    Options: "Opções",
    Outputs: "Resultados",
    Overview: "Visão Geral",
    Overwrite: "Overwrite",
    Owner: "Proprietário",
    PackageMaps: "Mapas do Pacote de Dados",
    ParameterXML: "Parametro XML",
    Parts: "Partes",
    Path: "Caminho",
    PathMask: "Bloqueador do Caminho",
    PctComplete: "% Completo",
    PercentDone: "Percentual Completo",
    PerformingLayout: "Executando Layout...",
    Permissions: "Permissões",
    PlaceholderFindText: "Wuid, Usuário‎, Mais...",
    Playground: "Area de Recreio",
    Prefix: "Prefixo",
    Priority: "Prioridade",
    ProgressMessage: "Mensagem de Progresso",
    Properties: "Propriedades",
    Property: "Propriedade",
    Protect: "Proteger",
    Protected: "Protegido",
    Publish: "Publicado",
    PublishedBy: "Publicado por",
    PublishedQueries: "Consultas de ECL Publicadas",
    Queries: "Consultas ECL",
    QueryDetailsfor: "Detalhes para",
    QuerySet: "Grupo de Consultas",
    Queue: "Fila",
    Quote: "Aspas",
    RecordCount: "Numero de Registros",
    RecordLength: "Tamanho do Registro",
    Records: "Registros",
    RecordSize: "Tamanho do Registro",
    ReleaseNotes: "Notas de Versão",
    RemoteDali: "Dali Remota",
    Remove: "Remover",
    Rename: "Renomear",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Renderização SVG",
    Replicate: "Replicar",
    RequestSchema: "Schema da Busca",
    Reschedule: "Reagendar",
    Reset: "Limpar",
    Resources: "Recursos",
    ResponseSchema: "Schema da Resposta",
    Restart: "Restart",
    Resubmit: "Resubmeter",
    Results: "Resultado(s)",
    RetainSuperfileStructure: "Preservar Estrutura do Super Arquivo",
    Rows: "Linhas",
    RowTag: "Nome da Linha",
    RoxieCluster: "Roxie Cluster (Aglomerado)",
    Sample: "Amostra",
    SampleRequest: "Amostra da Busca",
    SampleResponse: "Amostra de Resposta",
    Save: "Salvar",
    Scope: "Escopo",
    SearchResults: "Resultado da Busca",
    SecondsRemaining: "Segundos Restantes",
    Separators: "Seperadores",
    SetBanner: "Fixar Banner",
    SetToFailed: "Indicar como Falhado",
    Severity: "Severidade",
    Show: "Exibir",
    ShowSVG: "Mostrar SVG",
    Size: "Tamanho",
    Skew: "Distorção",
    Slaves: "Slaves",
    SOAP: "SOAP",
    somefile: "*::algum_arquivo*",
    somefile: "*::somefile",
    Source: "Fonte",
    SourceCode: "Código Fonte",
    SplitPrefix: "Prefixo de separação",
    Spray: "Spray (Distribuir aos Nós)",
    Start: "Começar",
    Started: "Início",
    State: "Estado",
    Stopped: "Parado",
    Subgraphs: "Subgráfico",
    Submit: "Submeter",
    Summary: "Resumo",
    SummaryMessage: "Mensagem de Resumo",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SVGSource: "Fonte de SVG",
    Sync: "Sync",
    SystemServers: "Servidores do Sistema",
    tag: "tag",
    Target: "Destino",
    TargetClusters: "Aglomeragos de Destino(Alvos)",
    TargetName: "Nome do Destino",
    Terminators: "Terminadores",
    TestPages: "Páginas de Teste",
    ThorNetworkAddress: "Endereço de Rede do Thor",
    Time: "Tempo",
    TimeSeconds: "Tempo (Segundos)",
    TimeStarted: "Início",
    TimeStopped: "Fim",
    Timings: "Medidas de Tempo",
    TimingsMap: "Mapa das Medidas de Tempo",
    title_Activity: "Atividate",
    title_DFUQuery: "Arquivos Lógicos",
    title_DFUWUDetails: "Tarefa DFU",
    title_ECLPlayground: "ECL Playground",
    title_GetDFUWorkunits: "Tarefas DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "Título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Change Me",
    title_HPCCPlatformECL: "Platforma HPCC - Página Inicial",
    title_HPCCPlatformFiles: "Platforma HPCC - Arquivos",
    title_HPCCPlatformMain: "Platforma HPCC - Página Inicial",
    title_HPCCPlatformOpsWidget: "Platforma HPCC - Operações",
    title_HPCCPlatformRoxie: "Platforma HPCC - Roxie",
    title_LFDetails: "Detalhes dos Arquivos Lógicos",
    title_LZBrowse: "Zona de Entrada de Arquivos",
    title_QuerySetDetails: "Detalhes da Consulta ECL",
    title_QuerySetErrors: "Erros",
    title_QuerySetLogicalFiles: "Arquivos Lógicos",
    title_QuerySetQuery: "Consultas ECL",
    title_QuerySetSuperFiles: "Super Arquivos",
    title_QueryTest: "Super Arquivos",
    title_Result: "Resultados",
    title_Results: "Atividade",
    title_WUDetails: "Detalhes da Tarefa ECL",
    title_WUQuery: "Tarefas de ECL",
    ToDate: "Data Final",
    Toenablegraphviews: "Para ativar visão gráfica, por favor instalar o plugin",
    ToSizes: "Tamanho Máximo",
    TotalThorTime: "Tempo Total do Thor",
    Type: "Tipo",
    undefined: "undefined",
    Unknown: "Unknown",
    Unprotect: "Desprotege",
    Unsuspend: "Reativar",
    Unsuspended: "Reativado",
    Upload: "Enviar",
    Used: "Usado",
    User: "Usuário",
    Users: "Usuários",
    UseSingleConnection: "Usar Conexão Única",
    Value: "Valor",
    Version: "Versão",
    Views: "Visões",
    Visualize: "Visualize",
    Warnings: "Avisos",
    Width: "Largura",
    Workunit: "Tarefa",
    Workunits: "Tarefas",
    Wrap: "Wrap",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid não pode estar vazia",
    WUSnapShot: "WU Snap Shot",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nenhum Arquivo Lógico (verifique filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Pacote de Análise Zipped",
    Zoom100Pct: "Zoom 100%",
    ZoomAll: "Zoom Completo",
    ZoomWidth: "comprimento do Zoom"
})
);
