/*##############################################################################

    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
############################################################################## */

import $;
C := $.files(__PLATFORM__, false);

set of string lines := [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE office:document-content PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "office.dtd">',
    '<office:document-content xmlns:office="http://openoffice.org/2000/office" xmlns:style="http://openoffice.org/2000/style" xmlns:text="http://openoffice.org/2000/text" xmlns:table="http://openoffice.org/2000/table" xmlns:draw="http://openoffice.org/2000/drawing" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:number="http://openoffice.org/2000/datastyle" xmlns:svg="http://www.w3.org/2000/svg" xmlns:chart="http://openoffice.org/2000/chart" xmlns:dr3d="http://openoffice.org/2000/dr3d" xmlns:math="http://www.w3.org/1998/Math/MathML" xmlns:form="http://openoffice.org/2000/form" xmlns:script="http://openoffice.org/2000/script" office:class="spreadsheet" office:version="1.0">',
    ' <office:script/>',
    ' <office:font-decls>',
    '  <style:font-decl style:name="Arial1" fo:font-family="Arial"/>',
    '  <style:font-decl style:name="Arial2" fo:font-family="Arial" style:font-family-generic="swiss"/>',
    '  <style:font-decl style:name="Helvetica" fo:font-family="Helvetica" style:font-family-generic="swiss"/>',
    '  <style:font-decl style:name="Lucida Sans Unicode" fo:font-family="&apos;Lucida Sans Unicode&apos;" style:font-pitch="variable"/>',
    '  <style:font-decl style:name="Tahoma" fo:font-family="Tahoma" style:font-pitch="variable"/>',
    '  <style:font-decl style:name="Arial" fo:font-family="Arial" style:font-family-generic="swiss" style:font-pitch="variable"/>',
    ' </office:font-decls>',
    ' <office:automatic-styles>',
    '  <style:style style:name="co1" style:family="table-column">',
    '   <style:properties fo:break-before="auto" style:column-width="1.967cm"/>',
    '  </style:style>',
    '  <style:style style:name="co2" style:family="table-column">',
    '   <style:properties fo:break-before="auto" style:column-width="8.62cm"/>',
    '  </style:style>',
    '  <style:style style:name="co3" style:family="table-column">',
    '   <style:properties fo:break-before="auto" style:column-width="1.801cm"/>',
    '  </style:style>',
    '  <style:style style:name="co4" style:family="table-column">',
    '   <style:properties fo:break-before="auto" style:column-width="1.757cm"/>',
    '  </style:style>',
    '  <style:style style:name="ro1" style:family="table-row">',
    '   <style:properties style:row-height="0.453cm" fo:break-before="auto" style:use-optimal-row-height="true"/>',
    '  </style:style>',
    '  <style:style style:name="ro2" style:family="table-row">',
    '   <style:properties style:row-height="0.473cm" fo:break-before="auto" style:use-optimal-row-height="true"/>',
    '  </style:style>',
    '  <style:style style:name="ta1" style:family="table" style:master-page-name="TAB_Apr04">',
    '   <style:properties table:display="true"/>',
    '  </style:style>',
    '  <style:style style:name="ta2" style:family="table" style:master-page-name="TAB_Mar04">',
    '   <style:properties table:display="true"/>',
    '  </style:style>',
    '  <number:date-style style:name="N36" style:family="data-style" number:automatic-order="true">',
    '   <number:day number:style="long"/>',
    '   <number:text>/</number:text>',
    '   <number:month number:style="long"/>',
    '   <number:text>/</number:text>',
    '   <number:year number:style="long"/>',
    '  </number:date-style>',
    '  <style:style style:name="ce1" style:family="table-cell" style:parent-style-name="Default">',
    '   <style:properties fo:border="none"/>',
    '  </style:style>',
    '  <style:style style:name="ce2" style:family="table-cell" style:parent-style-name="Default" style:data-style-name="N36">',
    '   <style:properties fo:border="none"/>',
    '  </style:style>',
    '  <style:style style:name="ce3" style:family="table-cell" style:parent-style-name="Default" style:data-style-name="N145">',
    '   <style:properties fo:border="none"/>',
    '  </style:style>',
    ' </office:automatic-styles>',
    ' <office:body>',
    '  <table:calculation-settings table:case-sensitive="false" table:use-regular-expressions="false"/>',
    '  <table:table table:name="Apr04" table:style-name="ta1">',
    '   <table:table-column table:style-name="co1" table:default-cell-style-name="ce1"/>',
    '   <table:table-column table:style-name="co2" table:default-cell-style-name="ce1"/>',
    '   <table:table-column table:style-name="co3" table:number-columns-repeated="2" table:default-cell-style-name="ce3"/>',
    '   <table:table-column table:style-name="co4" table:number-columns-repeated="252" table:default-cell-style-name="Default"/>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell>',
    '     <text:p>Date</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>Description</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>Amount</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-30">',
    '     <text:p>30/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WOOLWORTHS.CO.UK <text:s text:c="2"/>.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-79.99">',
    '     <text:p>-79.99 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-30">',
    '     <text:p>30/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.9">',
    '     <text:p>-11.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-30">',
    '     <text:p>30/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH BARCLAY APR30 23 HIGH STRE@11:37</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-30">',
    '     <text:p>30/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200181">',
    '     <text:p>200181</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-30">',
    '     <text:p>30/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200180">',
    '     <text:p>200180</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-64.98">',
    '     <text:p>-64.98 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-30">',
    '     <text:p>30/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200177">',
    '     <text:p>200177</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-29">',
    '     <text:p>29/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>ROYSIA SURGERY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="414.37">',
    '     <text:p>414.37 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-28">',
    '     <text:p>28/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>SPAR SAWSTON <text:s text:c="6"/>CAMBRIDGE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-35.86">',
    '     <text:p>-35.86 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-28">',
    '     <text:p>28/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>LEISURE CONNECTION CAMBRIDGE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-9.75">',
    '     <text:p>-9.75 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-28">',
    '     <text:p>28/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>THE TOWN HOUSE <text:s text:c="4"/>SAWSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-35.99">',
    '     <text:p>-35.99 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-28">',
    '     <text:p>28/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200179">',
    '     <text:p>200179</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-56.5">',
    '     <text:p>-56.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-27">',
    '     <text:p>27/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>JOHN LEWIS <text:s text:c="8"/>GIFT LIST.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-85">',
    '     <text:p>-85.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-27">',
    '     <text:p>27/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>MBNA VISA <text:s text:c="9"/>000000******1003</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-194.25">',
    '     <text:p>-194.25 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-27">',
    '     <text:p>27/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200178">',
    '     <text:p>200178</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-114">',
    '     <text:p>-114.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-26">',
    '     <text:p>26/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>SOLELY FOR CHILDRE SAFFRON WALDEN</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-29">',
    '     <text:p>-29.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-26">',
    '     <text:p>26/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>FLINT CROSS S/STN <text:s/>ROYSTON.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-30.73">',
    '     <text:p>-30.73 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-26">',
    '     <text:p>26/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BURY LANE FLOWERS <text:s/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-5.19">',
    '     <text:p>-5.19 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-26">',
    '     <text:p>26/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-83.74">',
    '     <text:p>-83.74 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-26">',
    '     <text:p>26/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CGNU LIFE ASS LTD</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-9.2">',
    '     <text:p>-9.20 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-26">',
    '     <text:p>26/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CHILDRENS SOCIETY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-75">',
    '     <text:p>-75.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-24">',
    '     <text:p>24/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH BARCLAY APR24 BARCLAYS BAN@13:07</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-23">',
    '     <text:p>23/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WOOLWORTHS.CO.UK <text:s text:c="2"/>.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-23.45">',
    '     <text:p>-23.45 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-23">',
    '     <text:p>23/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100212">',
    '     <text:p>100212</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-123">',
    '     <text:p>-123.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-23">',
    '     <text:p>23/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BROWN ENVELOPES LTD</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="2000">',
    '     <text:p>2,000.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-22">',
    '     <text:p>22/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CPRE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-3">',
    '     <text:p>-3.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-22">',
    '     <text:p>22/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>SUSTRANS</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-5">',
    '     <text:p>-5.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-21">',
    '     <text:p>21/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH RB SCOT APR21 RTRAK KINGS @13:38</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-21">',
    '     <text:p>21/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100213">',
    '     <text:p>100213</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-27.5">',
    '     <text:p>-27.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-20">',
    '     <text:p>20/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>POST OFFICE LTD <text:s text:c="3"/>BARLEY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-5.81">',
    '     <text:p>-5.81 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-20">',
    '     <text:p>20/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-76.2">',
    '     <text:p>-76.20 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-20">',
    '     <text:p>20/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200176">',
    '     <text:p>200176</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-12.28">',
    '     <text:p>-12.28 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-20">',
    '     <text:p>20/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100208">',
    '     <text:p>100208</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-2.17">',
    '     <text:p>-2.17 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-20">',
    '     <text:p>20/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>FAT BANANA SOCIETY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-62">',
    '     <text:p>-62.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-20">',
    '     <text:p>20/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>SCOTTISH PROVIDENT</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-28.84">',
    '     <text:p>-28.84 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-19">',
    '     <text:p>19/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>MR M DR S <text:s/>WILLIAMS <text:s/>HOLIDAY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-238.25">',
    '     <text:p>-238.25 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-19">',
    '     <text:p>19/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>MULAN RESTAURANT <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-42">',
    '     <text:p>-42.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-19">',
    '     <text:p>19/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO GARAGE 3989 <text:s/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-26.67">',
    '     <text:p>-26.67 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-19">',
    '     <text:p>19/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>MOTHERCARE COM INT WATFORD</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-8.95">',
    '     <text:p>-8.95 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-19">',
    '     <text:p>19/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-164.91">',
    '     <text:p>-164.91 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-16">',
    '     <text:p>16/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100211">',
    '     <text:p>100211</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-15">',
    '     <text:p>15/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH RB SCOT APR15 RTRAK KINGS @21:38</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-15">',
    '     <text:p>15/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100199">',
    '     <text:p>100199</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-109">',
    '     <text:p>-109.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>COUNTY INSURANCE <text:s text:c="2"/>KIDLINGTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-841.47">',
    '     <text:p>-841.47 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>THORNTONS/INTERNET DERBY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-17.5">',
    '     <text:p>-17.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>THORNTONS/INTERNET DERBY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-17.5">',
    '     <text:p>-17.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>MR M DR S <text:s/>WILLIAMS <text:s/>HOLIDAY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-365">',
    '     <text:p>-365.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100210">',
    '     <text:p>100210</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-14.95">',
    '     <text:p>-14.95 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100200">',
    '     <text:p>100200</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-28">',
    '     <text:p>-28.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100198">',
    '     <text:p>100198</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-13">',
    '     <text:p>13/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>UNITED BENEFICE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-08">',
    '     <text:p>08/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.9">',
    '     <text:p>-11.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-08">',
    '     <text:p>08/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO UPT 3989 <text:s text:c="4"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-30.8">',
    '     <text:p>-30.80 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-08">',
    '     <text:p>08/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-160.08">',
    '     <text:p>-160.08 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-08">',
    '     <text:p>08/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200166">',
    '     <text:p>200166</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-16.5">',
    '     <text:p>-16.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-08">',
    '     <text:p>08/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>STH CMBRIDGSHRE DC</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-183.49">',
    '     <text:p>-183.49 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-08">',
    '     <text:p>08/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>658027113761-CHB</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="107.95">',
    '     <text:p>107.95 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-07">',
    '     <text:p>07/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH NATWEST APR07 RTRAK KNGS C@14:26</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-06">',
    '     <text:p>06/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100197">',
    '     <text:p>100197</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-124.5">',
    '     <text:p>-124.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-06">',
    '     <text:p>06/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100196">',
    '     <text:p>100196</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-05">',
    '     <text:p>05/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100202">',
    '     <text:p>100202</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-7">',
    '     <text:p>-7.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-02">',
    '     <text:p>02/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BOI PAYPAL EUROPE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-18.01">',
    '     <text:p>-18.01 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-02">',
    '     <text:p>02/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.9">',
    '     <text:p>-11.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-02">',
    '     <text:p>02/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>POWERGEN ELEC</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-44">',
    '     <text:p>-44.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-02">',
    '     <text:p>02/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>RYL COLL OF JESTERS <text:s text:c="3"/>FIRST PAYMENT</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-01">',
    '     <text:p>01/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>LITTLE GREEN EARTH LEWES</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-16.2">',
    '     <text:p>-16.20 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-01">',
    '     <text:p>01/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>B.M.A</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-10.47">',
    '     <text:p>-10.47 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-01">',
    '     <text:p>01/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TEAR FUND LTD</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-75">',
    '     <text:p>-75.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-01">',
    '     <text:p>01/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CAMBRIDGE WATER</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-48.07">',
    '     <text:p>-48.07 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-01">',
    '     <text:p>01/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BARCLAYS</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-110">',
    '     <text:p>-110.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-04-01">',
    '     <text:p>01/04/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>HALLIDAY AA</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-110">',
    '     <text:p>-110.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1" table:number-rows-repeated="31928">',
    '    <table:table-cell table:number-columns-repeated="256"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:number-columns-repeated="256"/>',
    '   </table:table-row>',
    '  </table:table>',
    '  <table:table table:name="Mar04" table:style-name="ta2">',
    '   <table:table-column table:style-name="co1" table:default-cell-style-name="ce1"/>',
    '   <table:table-column table:style-name="co2" table:default-cell-style-name="ce1"/>',
    '   <table:table-column table:style-name="co3" table:number-columns-repeated="2" table:default-cell-style-name="ce3"/>',
    '   <table:table-column table:style-name="co4" table:number-columns-repeated="252" table:default-cell-style-name="Default"/>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell>',
    '     <text:p>Date</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>Description</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>Amount</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-31">',
    '     <text:p>31/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH NATWEST MAR31 RTRAK KNGS C@14:31</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-31">',
    '     <text:p>31/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>LEISURE CONNECTION CAMBRIDGE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-9.75">',
    '     <text:p>-9.75 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-31">',
    '     <text:p>31/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WOOLWORTHS PLC <text:s text:c="4"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-8">',
    '     <text:p>-8.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-31">',
    '     <text:p>31/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24.23">',
    '     <text:p>-24.23 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-31">',
    '     <text:p>31/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>AUTOMOBILE ASSN</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-64">',
    '     <text:p>-64.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>STAT. CUPBOARD <text:s text:c="4"/>ROYSTEN</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-5.35">',
    '     <text:p>-5.35 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>PEACOCK STORES <text:s text:c="4"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-6">',
    '     <text:p>-6.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BEAU-PORT LTD <text:s text:c="5"/>ALTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-299.99">',
    '     <text:p>-299.99 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200164">',
    '     <text:p>200164</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-243">',
    '     <text:p>-243.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100194">',
    '     <text:p>100194</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-452">',
    '     <text:p>-452.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BT DIRECT DEBITS</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-75.44">',
    '     <text:p>-75.44 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-30">',
    '     <text:p>30/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>ROYSIA SURGERY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="784.19">',
    '     <text:p>784.19 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-29">',
    '     <text:p>29/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>MERLIN MICA HARDWA ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-9.68">',
    '     <text:p>-9.68 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-29">',
    '     <text:p>29/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-64.3">',
    '     <text:p>-64.30 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-29">',
    '     <text:p>29/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO UPT 3989 <text:s text:c="4"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-29.01">',
    '     <text:p>-29.01 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-29">',
    '     <text:p>29/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-168.24">',
    '     <text:p>-168.24 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-29">',
    '     <text:p>29/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="4.94">',
    '     <text:p>4.94 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-26">',
    '     <text:p>26/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200165">',
    '     <text:p>200165</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-48">',
    '     <text:p>-48.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-26">',
    '     <text:p>26/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100195">',
    '     <text:p>100195</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-20">',
    '     <text:p>-20.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-25">',
    '     <text:p>25/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>HUGGABABY <text:s text:c="9"/>BRECON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.1">',
    '     <text:p>-11.10 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-25">',
    '     <text:p>25/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.9">',
    '     <text:p>-11.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-25">',
    '     <text:p>25/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CGNU LIFE ASS LTD</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-9.2">',
    '     <text:p>-9.20 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-25">',
    '     <text:p>25/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BROWN ENVELOPES LTD</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="2000">',
    '     <text:p>2,000.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-24">',
    '     <text:p>24/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>PAID IN AT 400407</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="75">',
    '     <text:p>75.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-24">',
    '     <text:p>24/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>LEISURE CONNECTION CAMBRIDGE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-9.75">',
    '     <text:p>-9.75 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-24">',
    '     <text:p>24/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100204">',
    '     <text:p>100204</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-12.5">',
    '     <text:p>-12.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-24">',
    '     <text:p>24/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CHILDRENS SOCIETY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-75">',
    '     <text:p>-75.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-22">',
    '     <text:p>22/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-146.12">',
    '     <text:p>-146.12 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-22">',
    '     <text:p>22/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100193">',
    '     <text:p>100193</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-447.19">',
    '     <text:p>-447.19 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-22">',
    '     <text:p>22/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>FAT BANANA SOCIETY</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-62">',
    '     <text:p>-62.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-22">',
    '     <text:p>22/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>SCOTTISH PROVIDENT</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-28.84">',
    '     <text:p>-28.84 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-22">',
    '     <text:p>22/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>SUSTRANS</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-5">',
    '     <text:p>-5.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-19">',
    '     <text:p>19/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO UPT 3989 <text:s text:c="4"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-33.74">',
    '     <text:p>-33.74 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-19">',
    '     <text:p>19/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-16.13">',
    '     <text:p>-16.13 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-19">',
    '     <text:p>19/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CPRE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-3">',
    '     <text:p>-3.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-18">',
    '     <text:p>18/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>WAGN RAILWAY LTD <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.9">',
    '     <text:p>-11.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-17">',
    '     <text:p>17/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>CASH RB SCOT MAR17 RTRAK KINGS @11:19</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-16">',
    '     <text:p>16/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100209">',
    '     <text:p>100209</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-15">',
    '     <text:p>15/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>AMAZON.CO.UK <text:s text:c="6"/>.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-11.76">',
    '     <text:p>-11.76 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-15">',
    '     <text:p>15/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>658027113751-CHB</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="107.2">',
    '     <text:p>107.20 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-12">',
    '     <text:p>12/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>LINDAM LTD <text:s text:c="8"/>HARROGATE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-4">',
    '     <text:p>-4.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-12">',
    '     <text:p>12/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-107.66">',
    '     <text:p>-107.66 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-12">',
    '     <text:p>12/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100207">',
    '     <text:p>100207</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-16.5">',
    '     <text:p>-16.50 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-10">',
    '     <text:p>10/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>UNITED BENEFICE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-50">',
    '     <text:p>-50.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-09">',
    '     <text:p>09/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="100192">',
    '     <text:p>100192</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-152">',
    '     <text:p>-152.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-05">',
    '     <text:p>05/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BIBLE</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-20">',
    '     <text:p>-20.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-03">',
    '     <text:p>03/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-43.13">',
    '     <text:p>-43.13 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-02">',
    '     <text:p>02/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TRAVELEX <text:s text:c="10"/>DOVER E DOCKS</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-201.66">',
    '     <text:p>-201.66 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-02">',
    '     <text:p>02/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200163">',
    '     <text:p>200163</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-152">',
    '     <text:p>-152.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-02">',
    '     <text:p>02/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200162">',
    '     <text:p>200162</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-24">',
    '     <text:p>-24.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-02">',
    '     <text:p>02/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="200161">',
    '     <text:p>200161</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-173.9">',
    '     <text:p>-173.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>AMAZON.CO.UK <text:s text:c="6"/>.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-25.07">',
    '     <text:p>-25.07 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>AMAZON.CO.UK <text:s text:c="6"/>.</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-12.47">',
    '     <text:p>-12.47 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO UPT 3989 <text:s text:c="4"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-32.9">',
    '     <text:p>-32.90 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>TESCO STORE 3108 <text:s text:c="2"/>ROYSTON</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-69.21">',
    '     <text:p>-69.21 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>B.M.A</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-10.47">',
    '     <text:p>-10.47 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>POWERGEN ELEC</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-44">',
    '     <text:p>-44.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>BARCLAYS</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-110">',
    '     <text:p>-110.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro2">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>HALLIDAY AAandZZ</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-2000">',
    '     <text:p>-2,000.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:style-name="ce2" table:value-type="date" table:date-value="2004-03-01">',
    '     <text:p>01/03/2004</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell>',
    '     <text:p>HALLIDAY AA</text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:value-type="float" table:value="-110">',
    '     <text:p>-110.00 </text:p>',
    '    </table:table-cell>',
    '    <table:table-cell table:number-columns-repeated="253"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1" table:number-rows-repeated="31938">',
    '    <table:table-cell table:number-columns-repeated="256"/>',
    '   </table:table-row>',
    '   <table:table-row table:style-name="ro1">',
    '    <table:table-cell table:number-columns-repeated="256"/>',
    '   </table:table-row>',
    '  </table:table>',
    ' </office:body>',
    '</office:document-content>'];

xmlSource := dataset(lines, { string line });
output(xmlSource,,C.DG_FileOut+'accountxml',csv,overwrite);
