if ("${VCPKG_DONE}" STREQUAL "")
  set (VCPKG_DONE 1)

set(VCPKG_FILES_DIR "${CMAKE_BINARY_DIR}" CACHE STRING "Folder for vcpkg download, build and installed files")
set(CMAKE_TOOLCHAIN_FILE ${HPCC_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake)
set(VCPKG_ROOT ${HPCC_SOURCE_DIR}/vcpkg)
set(VCPKG_INSTALLED_DIR "${VCPKG_FILES_DIR}/vcpkg_installed")
set(VCPKG_INSTALL_OPTIONS "--x-abi-tools-use-exact-versions;--downloads-root=${VCPKG_FILES_DIR}/vcpkg_downloads;--x-buildtrees-root=${VCPKG_FILES_DIR}/vcpkg_buildtrees;--x-packages-root=${VCPKG_FILES_DIR}/vcpkg_packages")
set(VCPKG_VERBOSE OFF)

if(WIN32)
    set(VCPKG_HOST_TRIPLET "x64-windows" CACHE STRING "host triplet")
    set(VCPKG_TARGET_TRIPLET "x64-windows" CACHE STRING "target triplet")
elseif(APPLE)
  if (CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
    set(VCPKG_HOST_TRIPLET "arm64-osx" CACHE STRING "host triplet")
    set(VCPKG_TARGET_TRIPLET "arm64-osx" CACHE STRING "target triplet")
  else()
    set(VCPKG_HOST_TRIPLET "x64-osx" CACHE STRING "host triplet")
    set(VCPKG_TARGET_TRIPLET "x64-osx" CACHE STRING "target triplet")
  endif()
elseif(UNIX)
    set(VCPKG_HOST_TRIPLET "x64-linux-dynamic" CACHE STRING "host triplet")
    set(VCPKG_TARGET_TRIPLET "x64-linux-dynamic" CACHE STRING "target triplet")
endif()
endif()