set (USE_OPENLDAP OFF)
set (USE_ICU ON)
find_package(ICU REQUIRED COMPONENTS data i18n io le lx tu uc)
set (USE_LIBXSLT ON)
find_package(LibXslt REQUIRED)
set (USE_OPENSSL ON)
find_package(OpenSSL REQUIRED)

set (USE_CBLAS OFF)
set (USE_ZLIB ON)
find_package(ZLIB REQUIRED)

set (USE_LIBARCHIVE OFF)
set (USE_BOOST_REGEX OFF)
# find_package(Boost REQUIRED COMPONENTS regex)

set (USE_APR OFF)
set (USE_AZURE OFF)
set (USE_AWS OFF)
set (WSSQL_SERVICE OFF)
set (USE_PYTHON3 OFF)
set (USE_PYTHON2 OFF)
set (USE_CASSANDRA OFF)
set (USE_TBB OFF)
set (USE_JAVA OFF)
set (USE_NATIVE_LIBRARIES ON)
set (INCLUDE_CONFIG_MANAGER OFF)
set (INCLUDE_TREEVIEW OFF)
set (CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

# Additional
option(BUILD_TESTS "Enable libgit2 tests (override libgit2 option)" ON)
set (BUILD_TESTS OFF)
set (USE_JWT OFF)

