#!/bin/sh
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

if [ ! -e ./dafscontrol ]; then
  echo "dafscontrol not found in current directory"
  exit 0
fi

export LD_LIBRARY_PATH=.
## following kludge as for some reason doesn't have execute rights on old deploys
chmod a+x ./dafscontrol
./dafscontrol checkver . quiet
if [ $? -eq 0 ]; then exit 0; fi
./stop_one_dafilesrv
export DAFSVER=`./dafscontrol myver`
export DAFSDIR=/c$/dafilesrv/ver_$DAFSVER
mkdir -p $DAFSDIR
rsync -tpgo *.so $DAFSDIR
rsync -tpgo dafilesrv $DAFSDIR
rsync -tpgo dafscontrol $DAFSDIR
rsync -tpgo start_one_dafilesrv $DAFSDIR
rsync -tpgo stop_one_dafilesrv $DAFSDIR
rsync -tpgo start_one_dafilesrv /c$/dafilesrv
rsync -tpgo stop_one_dafilesrv /c$/dafilesrv
echo "$DAFSDIR" > /c$/dafilesrv/CURRENT_VERSION
cd /c$/dafilesrv
./start_one_dafilesrv 
