define(
({
    title: "Logikai fájlok",

    Add: "Hozzáad",
    AddToSuperfile: "Superfile-hoz ad",
    Append: "Hozzáfűz",
    Cluster: "Klaszter",
    Compress: "Tömörít",
    DeleteSelectedFiles: "Töröljük a kiválasztott fájlokat?",
    Delimited: "Határolt",
    Description: "Leírás",
    Despray: "Összegyűjt",
    DropZone: "Gyűjtőhely",
    Escape: "Escape",
    Fixed: "Állandó rekordméret",
    Format: "Formátum",
    FromDate: "Dátumtól",
    FromSizes: "Mérettől",
    Group: "Csoport",
    IP: "IP",
    IPAddress: "IP cím",
    JSmith: "JSmit*",
    Label: "Címke",
    LastNDays: "Az utolsó N nap",
    LineTerminators: "Sorvég karakterek",
    LogicalFile: "Logikai fájl",
    LogicalName: "Logikai név",
    Mask: "Maszk",
    MaxRecordLength: "Maximális rekord méret",
    ModifiedUTCGMT: "Módosított (UTC/GMT)",
    NA: "N/A",
    Name: "Név",
    NoFilterCriteriaSpecified: "Nincs szűrőfeltétel megadva.",
    NoSplit: "Együtt tart",
    NoSplit: "Együtt tart",
    OmitSeparator: "Elválasztójel mellőzése",
    Options: "Opciók",
    Overwrite: "Fellülír",
    Owner: "Tulajdonos",
    Parts: "Részek",
    Path: "Útvonal",
    Prefix: "Előtag",
    Quote: "Idézőjel",
    RecordLength: "Rekord méret",
    Records: "Rekordok",
    RowTag: "Sor azonositó",
    Seperators: "Elválasztó jelek",
    Size: "Méret",
    somefile: "*::somefile*",
    Source: "Forrás",
    SplitPrefix: "Elválasztó előtag",
    Spray: "Szétoszt",
    tag: "tag",
    Target: "Cél",
    ToDate: "Dátumig",
    ToSizes: "Méretig",
    UseSingleConnection: "Egy kapcsolat használatával",
    XML: "XML",
    ZeroLogicalFilesCheckFilter: "Nincs a megadott feltételnek megfelelő adat! (A jó a szűrőfeltétel?)"
})
);
