define(
({
    title: "DFU munka",

    Abort: "Mgszakít",
    ClusterName: "Klaszter név",
    Command: "Parancs",
    Compress: "Tömörít",
    Dali: "Dali",
    DFUServerName: "DFU Szerver név",
    Directory: "Könyvtár",
    Escape: "Escape",
    FilePath: "Fájl útvonal",
    Format: "Formátum",
    GroupName: "Csoport név",
    ID: "ID",
    IP: "IP",
    JobName: "Munka azonosító",
    LogicalName: "Logikai név",
    Modify: "Módosít",
    MonitorEventName: "Monitor Event Name",
    MonitorShotLimit: "Monitor Shot Limit",
    MonitorSub: "Monitor Sub",
    NumberofParts: "Number of Parts",
    Overwrite: "Fellülír",
    PercentDone: "% kész",
    ProgressMessage: "Állapot",
    Protected: "Védett",
    Queue: "Sor",
    Quote: "Idézőjel",
    RecordSize: "Rekord méret",
    Replicate: "Másolat",
    Resubmit: "Újra küld",
    RowTag: "Sor azonositó",
    SecondsRemaining: "másodperc maradt",
    Seperators: "Elválasztó jelek",
    Source: "Forrás",
    State: "Állapot",
    Summary: "Összegzés",
    SummaryMessage: "Összegzés",
    Target: "Cél",
    Terminators: "Rekord lezáró jelek",
    TimeStarted: "Kezdés",
    TimeStopped: "Befejezés",
    User: "Felhasználó"
})
);
