define(
({
    title: "title",

    AboutGraphControl: "'Graph Control' információk",
    AboutHPCCSystemsGraphControl: "'HPCC Systems Graph Control' információk",
    Activities: "Tevékenységek",
    Advanced: "Haladó",
    Depth: "Mélység",
    Distance: "Távolság",
    DOT: "DOT",
    DOTAttributes: "DOT Attribútumok",
    ECL: "ECL",
    Edges: "Élek",
    EditDOT: "DOT szerkesztés",
    EditGraphAttributes: "Gráf attribútumok szerkesztése",
    EditXGMML: "XGMML szerkesztés",
    FetchingData: "Adat lekérdezés...",
    Find: "Keres",
    FindNext: "Következőt",
    FindPrevious: "Előzőt",
    ID: "ID",
    InfoDialog: "Információk",
    Label: "Címke",
    Local: "Helyi",
    Overview: "Áttekintés",
    PerformingLayout: "Performing Layout...",
    Properties: "Tulajdonságok",
    RenderedSVG: "Generált SVG",
    RenderSVG: "SVG generálás",
    ShowSVG: "SVG megjelenítés",
    Subgraphs: "Algráf",
    SVGSource: "SVG forrás",
    Sync: "Szinkronizálás",
    Timings: "Időzítések",
    TimingsMap: "Időzítés térkép",
    Version: "Verzió",
    XGMML: "XGMML"
})
);
