define(
({
    Abort: "Megszakít",
    About: "Névjegy",
    AboutGraphControl: "'Graph Control' információk",
    AboutHPCCSystemsGraphControl: "'HPCC Systems Graph Control' információk",
    Action: "Művelet",
    Activate: "Aktivál",
    Activated: "Aktivizált",
    Active: "Aktív",
    ActivePackageMap: "Active Package Map",
    ActiveWorkunit: "Aktív feladat",
    Activities: "Tevékenységek",
    Activity: "Tevékenység",
    ActualSize: "Aktuális méret",
    Add: "Hozzáad",
    AddGroup: "Add Group",
    AddProcessMap: "Add Package Map",
    AddToSuperfile: "Superfile-hoz ad",
    AddUser: "Add User",
    Advanced: "Haladó",
    AllowAccess: "<center>Allow<br>Access",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    ANY: "ANY",
    Append: "Hozzáfűz",
    Apply: "Alkalmaz",
    ArchivedOnly: "Csak tárolt.",
    BinaryInstalls: "Bináris telepítőkészlet",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefix",
    Cancel: "Mégsem",
    Clear: "Mezők törlése",
    Clone: "Klónozás",
    Close: "Bezárás",
    Cluster: "Klaszter",
    ClusterName: "Klaszter név",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Klaszter feldolgozások",
    Code: "Kód",
    Col: "Oszlop",
    Command: "Parancs",
    Comment: "Megjegyzés",
    Completed: "Kész",
    Component: "Komponens",
    Compress: "Tömörít",
    ConfirmPassword: "Confirm Password",
    Contents: "Tartalom",
    Copy: "Másolat",
    Count: "Darab (Count)",
    Created: "Létrehozva",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Dátum",
    Deactivate: "Hatástalanít",
    DEF: "DEF",
    Delete: "Törlés",
    DeleteSelectedFiles: "Töröljük a kiválasztott fájlokat?",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedQueries: "Töröljük a kiválasztott lekérdezéseket?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DeleteSelectedWorkunits: "Törölni akarja a kiválasztott feladatokat?",
    DeleteSuperfile: "Töröljük a Superfile-t?",
    DeleteThisPackage: "Delete this package?",
    Delimited: "Határolt",
    DenyAccess: "<center>Deny<br>Access",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Depth: "Mélység",
    Deschedule: "Ütemezés törlése",
    DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
    Description: "Leírás",
    Despray: "Összegyűjt",
    DFUServerName: "DFU Szerver név",
    Directory: "Könyvtár",
    Distance: "Távolság",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Attribútumok",
    Download: "Letöltés",
    DropZone: "Gyűjtőhely",
    Duration: "Időtartam",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "Élek",
    Edit: "Edit",
    EditDOT: "DOT szerkesztés",
    EditGraphAttributes: "Gráf attribútumok szerkesztése",
    EditXGMML: "XGMML szerkesztés",
    Empty: "(Empty)",
    Error: "Hiba",
    Errorparsingserverresult: "Hiba a szerver válasz feldolgozásban",
    Errors: "Error(s)",
    Errors: "Hibák",
    ErrorsStatus: "Hibák/Figyelmeztetések",
    ErrorWarnings: "Hiba/Figyelmeztetés",
    Escape: "Escape",
    ESPBuildVersion: "ESP Build verzió",
    ESPNetworkAddress: "ESP hálózati címe",
    EventName: "Event Name",
    EventNamePH: "eventname",
    EventScheduler: "Event Scheduler",
    EventText: "Event Text",
    Exception: "Exception",
    FetchingData: "Adat lekérdezés...",
    fetchingresults: "eredemény lekérdezés",
    File: "Fájl",
    FileName: "Fájl név",
    FileParts: "Fájl részek",
    FilePath: "Fájl útvonal",
    Files: "Fájlok",
    FileSize: "Fájl méret",
    FilesNoPackage: "Files without matching package definitions",
    FileType: "File Type",
    FileUploader: "Fájl feltöltő",
    Filter: "Szűrő",
    Find: "Keresés",
    FindNext: "Következőt",
    FindPrevious: "Előzőt",
    FirstName: "First Name",
    Fixed: "Állandó rekordméret",
    Format: "Formátum",
    FromDate: "Dátumtól",
    FromSizes: "Mérettől",
    FullName: "Full Name",
    Graphs: "Gráfok",
    GraphView: "Gráf nézet",
    Group: "Csoport",
    GroupDetails: "Group Details",
    GroupName: "Csoport név",
    GroupPermissions: "Group Permissions",
    Groups: "Csoportok",
    GZip: "GZip",
    help: "Ezen a területen a munkaegység gráfjai láthatók. Az egyes blokkok mérete és színe az adott blokk végrehajtási idejével arányos (a nagyobb es sötétebb terület a hosszabb időtartamot jelzi).",
    Helpers: "Segédletek",
    Hex: "Hexa nézet",
    History: "Történet",
    HPCCSystems: "HPCC Systems",
    ID: "ID",
    Import: "Import",
    Info: "Információ",
    InfoDialog: "Információk",
    Inputs: "Bemenet",
    InvalidResponse: "(Invalid response)",
    IP: "IP",
    IPAddress: "IP cím",
    IsLibrary: "Könyvtár?",
    Jobname: "Munka azonosító",
    JobName: "Munka azonosító",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Címke",
    LandingZone: "Lerakat",
    LandingZones: "Lerakatok",
    Largest: "Largest",
    LastName: "Last Name",
    LastNDays: "Az utolsó N nap",
    LegacyForm: "Örökölt űrlap (Legacy Form)",
    LibrariesUsed: "Használt könyvtárak",
    Line: "Sor",
    LineTerminators: "Sorvég karakterek",
    Links: "Linkek",
    Loading: "Betöltés",
    LoadingCachedLayout: "Loading Cached Layout...",
    LoadingData: "Adat betöltés...",
    loadingMessage: "Betöltés folyamatban...",
    Local: "Helyi",
    LoggedInAs: "Bejelentkezve mint ",
    LogicalFile: "Logikai fájl",
    LogicalFile: "Logikai fájl neve",
    LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
    LogicalFiles: "Logikai fájlok",
    LogicalFileType: "Logikai fájl típusa",
    LogicalName: "Logikai név",
    log_analysis_1: "log_analysis_1*",
    Mappings: "Leképezések",
    Mask: "Maszk",
    Max: "Maximum",
    MaxRecordLength: "Maximális rekord méret",
    MemberOf: "Member Of",
    Members: "Members",
    Message: "Üzenet",
    Min: "Minimum",
    Modification: "Módosítás",
    ModifiedUTCGMT: "Módosítva (UTC/GMT)",
    Modify: "Módosít",
    MonitorEventName: "Monitor Event Name",
    MonitorShotLimit: "Monitor Shot Limit",
    MonitorSub: "Monitor Sub",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    NA: "N/A",
    Name: "Név",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Newest",
    NewPassword: "New Password",
    NoContent: "(No content)",
    noDataMessage: "Nincs a feltételeknek megfelelő adat...",
    Node: "Csomópont",
    NoErrorFound: "No errors found\n",
    NoFilterCriteriaSpecified: "Nincs szűrőfeltétel megadva.",
    NoScheduledEvents: "No Scheduled Events.",
    NoSplit: "Együtt tart",
    NotActive: "Not active",
    NothingSelected: "Nothing Selected...",
    NotInSuperfiles: "Not in Superfiles",
    NoWarningFound: "No warnings found\n",
    NumberofParts: "Number of Parts",
    OK: "Rendben",
    Oldest: "Oldest",
    OmitSeparator: "Elválasztójel mellőzése",
    Only1PackageFileAllowed: "Only one package file allowed",
    Open: "Megnyitás",
    OpenInNewPage: "Megnyitás új lapon",
    OpenLegacyECLWatch: "Legacy ECL Watch megnyitása",
    OpenSafeMode: "Megnyitás (biztonságos módban)",
    Operations: "Műveletek",
    Options: "Opciók",
    Outputs: "Kimenet",
    Overview: "Áttekintés",
    Overwrite: "Fellülírás",
    Owner: "Tulajdonos",
    PackageContent: "Package Content",
    PackageContentNotSet: "Package content not set",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Packages without matching queries",
    ParameterXML: "Paraméter XML fájl",
    Parts: "Részek",
    Password: "Password",
    PasswordExpiration: "Password Expiration",
    PasswordsDoNotMatch: "Passwords do not match.",
    Path: "Útvonal",
    PathMask: "Útvonal maszk",
    PctComplete: "% kész",
    PercentDone: "% kész",
    PerformingLayout: "Elrendezés generálása...",
    Permissions: "Jogosultságok",
    PlaceholderFindText: "Wuid, felhasználók, egyebek...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "ECL teszt labor",
    Prefix: "Előtag",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preview: "Preview",
    Priority: "Prioritás",
    Process: "Process",
    ProcessFilter: "Process&nbsp;Filter",
    ProgressMessage: "Állapot",
    Properties: "Tulajdonságok",
    Property: "Tulajdonság",
    Protect: "Megvéd",
    Protected: "Védett",
    Publish: "Publikál",
    PublishedBy: "Közzétette",
    PublishedQueries: "Publikált lekérdezések",
    Queries: "Lekérdezések",
    QueriesNoPackage: "Queries without matching package",
    QueryDetailsfor: "A lekérdezés paraméterei",
    QuerySet: "Lekérdezés készlet",
    Queue: "Sor",
    Quote: "Idézőjel",
    RecordCount: "Rekord szám",
    RecordLength: "Rekord méret",
    Records: "Rekordok száma",
    RecordSize: "Rekord méret",
    Refresh: "Frissítés",
    ReleaseNotes: "Verzió információk (Release Notes)",
    Reload: "Reload",
    RemoteDali: "Távoli Dali hálózati címe",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "Eltávolít",
    Rename: "Átnevez",
    RenderedSVG: "Generált SVG",
    RenderSVG: "SVG generálás",
    Replicate: "Másolat",
    RequestSchema: "Igénylő séma (Request Schema)",
    Reschedule: "Újraütemez",
    Reset: "Forrás",
    Resource: "Resource",
    Resources: "Erőforrások",
    ResponseSchema: "Válasz séma (Response Schema)",
    Restart: "Újraindít",
    Resubmit: "Újraküld",
    Results: "Eredmény(ek)",
    RetainSuperfileStructure: "Superfile szerkezetének megőrzése",
    RetypePassword: "Retype Password",
    Rows: "Sor",
    RowTag: "Sor azonositó",
    RoxieCluster: "Roxie klaszter",
    Sample: "Minta",
    SampleRequest: "Minta igénylés (Sample Request)",
    SampleResponse: "Minta válasz (Sample Response)",
    Save: "Mentés",
    Scope: "Hatókör",
    SearchResults: "Keresések",
    SecondsRemaining: "másodperc maradt",
    SelectPackageFile: "Select Package File",
    Seperators: "Elválasztó jelek",
    SetBanner: "Fejléc megadása",
    SetToFailed: "Elront",
    Severity: "Probléma mértéke",
    Show: "Megjelenít",
    ShowSVG: "SVG megjelenítés",
    Size: "Méret",
    Skew: "Asszimmetrikus (Skew)",
    Slaves: "Kiszolgáló",
    Smallest: "Smallest",
    SOAP: "SOAP",
    somefile: "*::somefile",
    somefile: "*::somefile*",
    Source: "Forrás",
    SourceCode: "Forráskód",
    SourcePath: "Source Path (Wildcard Enabled)",
    SplitPrefix: "Elválasztó előtag",
    Spray: "Szétoszt",
    Start: "Start",
    Started: "Elindítva",
    State: "Állapot",
    Stopped: "Megállítva",
    Subgraphs: "Algráf",
    Submit: "Elküld",
    Summary: "Összegzés",
    SummaryMessage: "Összegzés",
    SuperFile: "Super File",
    SuperfilesOnly: "Superfiles Only",
    Suspend: "Felfüggeszt",
    Suspended: "Felfüggesztve",
    SuspendedBy: "Felfüggesztette",
    SVGSource: "SVG forrás",
    Sync: "Szinkronizálás",
    SystemServers: "Rendszer kiszolgálók",
    tag: "tag",
    Target: "Cél",
    TargetClusters: "Cél klaszterek",
    TargetName: "Target Name",
    TargetNamePlaceholder: "some::logical::name",
    TargetWuid: "Target/Wuid",
    Terminators: "Rekord lezáró jelek",
    TestPages: "Tesztlapok",
    ThorNetworkAddress: "Thor hálózati címe",
    Time: "Idő",
    TimeSeconds: "Idő (másodperc)",
    TimeStarted: "Kezdés",
    TimeStopped: "Befejezés",
    Timings: "Időzítések",
    TimingsMap: "Időzítés térkép",
    title_Activity: "Tevékenység",
    title_DFUQuery: "Logikai fájlok",
    title_DFUWUDetails: "DFU munka",
    title_ECLPlayground: "ECL teszt labor",
    title_EventScheduleWorkunit: "Event Scheduler",
    title_GetDFUWorkunits: "DFU feladatok",
    title_Graph: "Gráfok",
    title_GraphPage: "title",
    title_Graphs: "Gráfok",
    title_GridDetails: "Változtass meg!",
    title_HPCCPlatformECL: "HPCC Platform - Home",
    title_HPCCPlatformFiles: "HPCC Platform - Files",
    title_HPCCPlatformMain: "HPCC Platform - Home",
    title_HPCCPlatformOps: "HPCC Platform - Operations",
    title_HPCCPlatformRoxie: "HPCC Platform - Roxie",
    title_Inputs: "Inputs",
    title_LFDetails: "Logikai fájl információk",
    title_LZBrowse: "Lerakatok",
    title_MemberOf: "Member Of",
    title_Members: "Members",
    title_QuerySetDetails: "Lekérdezés paraméterei",
    title_QuerySetErrors: "Hibák",
    title_QuerySetLogicalFiles: "Logikai fájlok",
    title_QuerySetQuery: "Lekérdezések",
    title_QuerySetSuperFiles: "Szuper fájlok",
    title_QueryTest: "Szuper fájlok",
    title_Result: "Tevékenység",
    title_Results: "Kimenet",
    title_SearchResults: "Keresés eredménye",
    title_SourceFiles: "Forrás fájlok",
    title_UserQuery: "Permissions",
    title_UserPermissions: "User Permissions",
    title_WUDetails: "ECL feladat jellemzők",
    title_WUQuery: "ECL feladatok",
    ToDate: "Dátumig",
    Toenablegraphviews: "A gráfok megjelenítéshez telepiteni kell a 'Graph View Control' bővítményt.",
    ToSizes: "Méretig",
    TotalThorTime: "Összes Thor idő",
    Type: "Típus",
    undefined: "nem definiált",
    Unknown: "Ismeretlen",
    Unprotect: "Védelem nélkül",
    Unsuspend: "Folytat",
    Unsuspended: "Folytatva",
    Upload: "Feltöltés",
    Used: "Használva",
    User: "Felhasználó",
    UserDetails: "User Details",
    UserID: "User ID",
    Username: "Username",
    UserName: "User Name",
    UserPermissions: "User Permissions",
    Users: "Felhasználók",
    UseSingleConnection: "Egy kapcsolat használatával",
    Validate: "Validate",
    ValidatePackageMap: "Validate Package Map",
    ValidateResult: "=====Validate Result=====\n\n",
    Value: "Érték",
    Variable: "Variable",
    VariableBigendian: "Variable Big-endian",
    VariableSourceType: "Source Type",
    Version: "Verzió",
    Views: "Nézetek",
    Visualize: "Grafikus megjelenítés",
    Warnings: "Figyelmeztetések",
    WarnOldGraphControl: "Warning:  Old Graph Control",
    Width: "Szélesség",
    Workunit: "Feladat",
    Workunits: "Feladatok",
    Wrap: "Csomagol (Wrap)",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid megadása kötelező!",
    WUSnapShot: "WU pillanatfelvétel",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "Keresztreferencia (XRef)",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nincs a megadott feltételnek megfelelő adat! (A jó a szűrőfeltétel?)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Tömörített elemzési csomag",
    Zoom100Pct: "Nagyitás 100%-ra",
    ZoomAll: "Teljes gráf ablakba méretezése",
    ZoomWidth: "Gráf nagyítása az ablak szélességére"
})
);
