define(
({
    title: "Logikai fájl információk",

    ActualSize: "Aktuális méret",
    ClusterName: "Klaszter név",
    Compress: "Tömörít",
    Contents: "Tartalom",
    Copy: "Másolat",
    DEF: "DEF",
    Description: "Leírás",
    Despray: "Összegyűjt",
    Directory: "Könyvtár",
    DropZone: "Gyűjtőhely",
    ECL: "ECL",
    FileParts: "Fájl részek",
    FileSize: "Fájl méret",
    Group: "Csoport",
    IPAddress: "IP cím",
    JobName: "Munka azonosító",
    LogicalFile: "Logikai fájl neve",
    Modification: "Módosítás",
    NoSplit: "Együtt tart",
    Overwrite: "Fellülír",
    Owner: "Tulajdonos",
    Path: "Útvonal",
    PathMask: "Útvonal maszk",
    RecordCount: "Rekord szám",
    RecordSize: "Rekord méret",
    Rename: "Átnevez",
    RetainSuperfileStructure: "Superfile szerkezetének megőrzése",
    Source: "Forrás",
    SplitPrefix: "Elválasztó előtag",
    Summary: "Összegzés",
    Target: "Cél",
    UseSingleConnection: "Egy kapcsolat használatával",
    Workunit: "Feladat",
    Wrap: "Csomagol (Wrap)",
    XML: "XML"
})
);
