define(
({
    title: "Lerakatok",

    Compress: "Tömörít",
    Date: "Dátum",
    DeleteSelectedFiles: "Töröljük a kiválasztott fájlokat?",
    Delimited: "Határolt",
    Download: "Letöltés",
    Errorparsingserverresult: "Hiba a szerver válasz feldolgozásban",
    Escape: "Escape",
    FileUploader: "Fájl feltöltő",
    Fixed: "Állandó rekordméret",
    Format: "Formátum",
    Group: "Csoport",
    HexPreview: "Hexa előnézet",
    Label: "Címke",
    LandingZone: "Lerakat",
    LineTerminators: "Sorvég karakterek",
    Mask: "Maszk",
    MaxRecordLength: "Maximális rekord méret",
    Name: "Név",
    NoSplit: "Együtt tart",
    OmitSeparator: "Elválasztójel mellőzése",
    Options: "Opciók",
    Overwrite: "Fellülírás",
    Prefix: "Előtag",
    Quote: "Idézőjel",
    RecordLength: "Rekord méret",
    RowTag: "Sor azonosító",
    Seperators: "Elválasztó jelek",
    Size: "Méret",
    Source: "Forrás",
    Spray: "Szétoszt",
    SpraySourceType: "Szétosztandó forrás tipusa",
    Start: "Start",
    tag: "tag",
    Target: "Cél",
    Upload: "Feltöltés",
    XML: "XML"
})
);
