define(
({
    title: "Lekérdezés paraméterei",

    Activated: "Aktivizált",
    Comment: "Megjegyzés",
    DeleteSelectedWorkunits: "Töröljük a kiválasztott feladatokat?",
    Dll: "Dll",
    Errors: "Hibák",
    ErrorsStatus: "Hibák/Figyelmeztetések",
    Graphs: "Gráfok",
    IsLibrary: "Könyvtár?",
    LibrariesUsed: "Használt könyvtárak",
    LogicalFiles: "Logikai fájlok",
    LogicalFiles: "Logikai fájlok",
    Name: "Név",
    Priority: "Prioritás",
    PublishedBy: "Közzétette",
    QueryDetailsfor: "A lekérdezés paraméterei",
    QuerySet: "Lekérdezés készlet",
    Summary: "Összegzés",
    Suspended: "Felfüggesztve",
    SuspendedBy: "Felfüggesztette",
    TestPages: "Tesztlapok",
    Unsuspended: "Folytatva",
    Workunit: "Feladat",
    WUID: "WUID",
    WUSnapShot: "WU pillanatfelvétel",
})
);
