define(
({
    title: "ECL feladat jellemzők",

    Abort: "Megszakít",
    Action: "Művelet",
    Clone: "Klónozás",
    Cluster: "Klaszter",
    Description: "Leírás",
    Duration: "Időtartam",
    ECL: "ECL forrás",
    ESPBuildVersion: "ESP Build verzió",
    ESPNetworkAddress: "ESP hálózati címe",
    Graphs: "Gráf",
    Helpers: "Segédletek",
    History: "Történet",
    Inputs: "Bemenet",
    JobName: "Munka név",
    Outputs: "Kimenet",
    Owner: "Tulajdonos",
    Playground: "ECL teszt labor",
    Protected: "Védett",
    Publish: "Publikál",
    RemoteDali: "Távoli Dali hálózati címe",
    Restart: "Újraindít",
    Resubmit: "Újraküld",
    Scope: "Hatókör",
    SetToFailed: "Elront",
    State: "Állapot",
    Submit: "Elküld",
    Summary: "Összegzés",
    ThorNetworkAddress: "Thor hálózati címe",
    Timings: "Időzítések",
    Visualize: "Grafikus megjelenítés",
    WUID: "WUID",
    XML: "XML",
    ZAP: "Z.A.P",
    ZippedAnalysisPackage: "Tömörített elemzési csomag"
})
);
