application:
  name: eclwatch
  services:
   - WsSMC
   - WsWorkunits
   - WsTopology
   - WsDfu
   - WsDfuXRef
   - WsFileIO
   - WsPackageProcess
   - FileSpray
   - ws_elk
   - ws_access
   - ws_account
   - ws_esdlconfig
   - ws_store
   - ws_codesign
   - ws_resources
   - WSDali
   - WSSasha
   - ws_logaccess
   - WsCloud
