#!/bin/sh
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################


DESTDIR=`dirname $0`
cd $DESTDIR
rm -f saserver_sentinel*.txt

export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
export PATH=/mnt/usrbin:$PATH
pid=`pidof saserver`
if [ -n "$pid" ]; then
    ./sasha server=. action=stop
    I=1
    while [ -n "$pid" ] && [ $I -lt 30 ]; do
        echo "Waiting for saserver to stop"
        sleep 2
        pid=`pidof saserver`
        let I=I+1
        
    done
    if [ -n "$pid" ]; then
        kill -9 $pid
    fi
fi
exit 0

