#!/bin/bash -e
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by the remote unit leaving the relationship.
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT departed


JUJU_HPCC_DIR=/var/lib/HPCCSystems/charm
TMP_FILE=${JUJU_HPCC_DIR}/ip_file.tmp

LOCAL_IP_FILE=${JUJU_HPCC_DIR}/local_ip.txt
IP_FILE=${JUJU_HPCC_DIR}/ip_file.txt

[ -e ${LOCAL_IP_FILE} ] && echo "$(head -n 1  $LOCAL_IP_FILE);" > ${TMP_FILE}

TOTAL_UNITS=1
for UNIT in $(relation-list)
do
   UNIT_ADDRESS=`relation-get netAddress ${UNIT}`
   if [ -n "${UNIT_ADDRESS}" ]
   then
      TOTAL_UNITS=$(expr ${TOTAL_UNITS} \+ 1)
      echo "${UNIT_ADDRESS};" >> "${TMP_FILE}"
   fi
done

[  ${TOTAL_UNITS}  -eq 1 ] && exit 0




##
## Sort IPs
##
cat $TMP_FILE | sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4  > $IP_FILE

##
## DON'T HAVE A WAY TO CHECK IF CURRENT NODE IS LEAVING
## IF IT IS FOLLOWING WILL FAIL.
## For user need manually run  bin/config_hpcc.sh to reconfigure HPCC
## after destroy a unit.
##

#. ${CHARM_DIR}/hooks/hpcc-common

#auto_gen=$(config-get auto-gen)
#juju-log "auto_gen $auto_gen"
#[  ${auto_gen}  -eq 0 ] && exit

#if [ ${auto_gen} -eq 1 ]
#then
#   configure_cluster ${TOTAL_UNITS}
#else
#   get_envgen_configuration
#   configure_cluster
#fi
