/*##############################################################################

    HPCC SYSTEMS software Copyright (C) 2024 HPCC Systems®.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
############################################################################## */

//Tests derived from the python3 test suite

#OPTION('globalFold', FALSE);

regexTests := DATASET
    (
        [
            {0001, 'abc', 'abc', TRUE},
            {0002, 'abc', 'xbc', FALSE},
            {0003, 'abc', 'axc', FALSE},
            {0004, 'abc', 'abx', FALSE},
            {0005, 'abc', 'xabcy', TRUE},
            {0006, 'abc', 'ababc', TRUE},
            {0007, 'ab*c', 'abc', TRUE},
            {0008, 'ab*bc', 'abc', TRUE},
            {0009, 'ab*bc', 'abbc', TRUE},
            {0010, 'ab*bc', 'abbbbc', TRUE},
            {0011, '.{1}', 'abbbbc', TRUE},
            {0012, '.{3,4}', 'abbbbc', TRUE},
            {0013, 'ab{0,}bc', 'abbbbc', TRUE},
            {0014, 'ab+bc', 'abbc', TRUE},
            {0015, 'ab+bc', 'abc', FALSE},
            {0016, 'ab+bc', 'abq', FALSE},
            {0017, 'ab{1,}bc', 'abq', FALSE},
            {0018, 'ab+bc', 'abbbbc', TRUE},
            {0019, 'ab{1,}bc', 'abbbbc', TRUE},
            {0020, 'ab{1,3}bc', 'abbbbc', TRUE},
            {0021, 'ab{3,4}bc', 'abbbbc', TRUE},
            {0022, 'ab{4,5}bc', 'abbbbc', FALSE},
            {0023, 'ab?bc', 'abbc', TRUE},
            {0024, 'ab?bc', 'abc', TRUE},
            {0025, 'ab{0,1}bc', 'abc', TRUE},
            {0026, 'ab?bc', 'abbbbc', FALSE},
            {0027, 'ab?c', 'abc', TRUE},
            {0028, 'ab{0,1}c', 'abc', TRUE},
            {0029, '^abc$', 'abc', TRUE},
            {0030, '^abc$', 'abcc', FALSE},
            {0031, '^abc', 'abcc', TRUE},
            {0032, '^abc$', 'aabc', FALSE},
            {0033, 'abc$', 'aabc', TRUE},
            {0034, 'abc$', 'aabcd', FALSE},
            {0035, '^', 'abc', TRUE},
            {0036, '$', 'abc', TRUE},
            {0037, 'a.c', 'abc', TRUE},
            {0038, 'a.c', 'axc', TRUE},
            {0039, 'a\nc', 'abc', FALSE},
            {0040, 'a.*c', 'axyzc', TRUE},
            {0041, 'a\n*c', 'axyzc', FALSE},
            {0042, 'a.*c', 'axyzd', FALSE},
            {0043, 'a\n*c', 'axyzd', FALSE},
            {0044, 'a[bc]d', 'abc', FALSE},
            {0045, 'a[bc]d', 'abd', TRUE},
            {0046, 'a[b]d', 'abd', TRUE},
            {0047, '[a][b][d]', 'abd', TRUE},
            {0048, '.[b].', 'abd', TRUE},
            {0049, '.[b].', 'aBd', FALSE},
            {0050, '(?i:.[b].)', 'abd', TRUE},
            {0051, '(?i:\n[b]\n)', 'abd', FALSE},
            {0052, 'a[b-d]e', 'abd', FALSE},
            {0053, 'a[b-d]e', 'ace', TRUE},
            {0054, 'a[b-d]', 'aac', TRUE},
            {0055, 'a[-b]', 'a-', TRUE},
            {0056, 'a[b-]', 'a-', TRUE},
            {0057, 'a]', 'a]', TRUE},
            {0058, 'a[]]b', 'a]b', TRUE},
            {0059, 'a[^bc]d', 'aed', TRUE},
            {0060, 'a[^bc]d', 'abd', FALSE},
            {0061, 'a[^-b]c', 'adc', TRUE},
            {0062, 'a[^-b]c', 'a-c', FALSE},
            {0063, 'a[^]b]c', 'a]c', FALSE},
            {0064, 'a[^]b]c', 'adc', TRUE},
            {0065, '\\ba\\b', 'a-', TRUE},
            {0066, '\\ba\\b', '-a', TRUE},
            {0067, '\\ba\\b', '-a-', TRUE},
            {0068, '\\by\\b', 'xy', FALSE},
            {0069, '\\by\\b', 'yz', FALSE},
            {0070, '\\by\\b', 'xyz', FALSE},
            {0071, '\\Ba\\B', 'a-', FALSE},
            {0072, '\\Ba\\B', '-a', FALSE},
            {0073, '\\Ba\\B', '-a-', FALSE},
            {0074, '\\By\\b', 'xy', TRUE},
            {0075, '\\by\\B', 'yz', TRUE},
            {0076, '\\By\\B', 'xyz', TRUE},
            {0077, '\\w', 'a', TRUE},
            {0078, '\\w', '-', FALSE},
            {0079, '\\W', 'a', FALSE},
            {0080, '\\W', '-', TRUE},
            {0081, 'a\\sb', 'a b', TRUE},
            {0082, 'a\\sb', 'a-b', FALSE},
            {0083, 'a\\Sb', 'a b', FALSE},
            {0084, 'a\\Sb', 'a-b', TRUE},
            {0085, '\\d', '1', TRUE},
            {0086, '\\d', '-', FALSE},
            {0087, '\\D', '1', FALSE},
            {0088, '\\D', '-', TRUE},
            {0089, '[\\w]', 'a', TRUE},
            {0090, '[\\w]', '-', FALSE},
            {0091, '[\\W]', 'a', FALSE},
            {0092, '[\\W]', '-', TRUE},
            {0093, 'a[\\s]b', 'a b', TRUE},
            {0094, 'a[\\s]b', 'a-b', FALSE},
            {0095, 'a[\\S]b', 'a b', FALSE},
            {0096, 'a[\\S]b', 'a-b', TRUE},
            {0097, '[\\d]', '1', TRUE},
            {0098, '[\\d]', '-', FALSE},
            {0099, '[\\D]', '1', FALSE},
            {0100, '[\\D]', '-', TRUE},
            {0101, 'ab|cd', 'abc', TRUE},
            {0102, 'ab|cd', 'abcd', TRUE},
            {0103, '()ef', 'def', TRUE},
            {0104, '$b', 'b', FALSE},
            {0105, 'a\\(b', 'a(b', TRUE},
            {0106, 'a\\(*b', 'ab', TRUE},
            {0107, 'a\\(*b', 'a((b', TRUE},
            {0109, '((a))', 'abc', TRUE},
            {0110, '(a)b(c)', 'abc', TRUE},
            {0111, 'a+b+c', 'aabbabc', TRUE},
            {0112, 'a{1,}b{1,}c', 'aabbabc', TRUE},
            {0113, 'a.+?c', 'abcabc', TRUE},
            {0114, '(a+|b)*', 'ab', TRUE},
            {0115, '(a+|b){0,}', 'ab', TRUE},
            {0116, '(a+|b)+', 'ab', TRUE},
            {0117, '(a+|b){1,}', 'ab', TRUE},
            {0118, '(a+|b)?', 'ab', TRUE},
            {0119, '(a+|b){0,1}', 'ab', TRUE},
            {0120, '[^ab]*', 'cde', TRUE},
            {0121, '([abc])*d', 'abbbcd', TRUE},
            {0122, '([abc])*bcd', 'abcd', TRUE},
            {0123, 'a|b|c|d|e', 'e', TRUE},
            {0124, '(a|b|c|d|e)f', 'ef', TRUE},
            {0125, 'abcd*efg', 'abcdefg', TRUE},
            {0126, 'ab*', 'xabyabbbz', TRUE},
            {0127, 'ab*', 'xayabbbz', TRUE},
            {0128, '(ab|cd)e', 'abcde', TRUE},
            {0129, '[abhgefdc]ij', 'hij', TRUE},
            {0130, '^(ab|cd)e', 'abcde', FALSE},
            {0131, '(abc|)ef', 'abcdef', TRUE},
            {0132, '(a|b)c*d', 'abcd', TRUE},
            {0133, '(ab|ab*)bc', 'abc', TRUE},
            {0134, 'a([bc]*)c*', 'abc', TRUE},
            {0135, 'a([bc]*)(c*d)', 'abcd', TRUE},
            {0136, 'a([bc]+)(c*d)', 'abcd', TRUE},
            {0137, 'a([bc]*)(c+d)', 'abcd', TRUE},
            {0138, 'a[bcd]*dcdcde', 'adcdcde', TRUE},
            {0139, 'a[bcd]+dcdcde', 'adcdcde', FALSE},
            {0140, '(ab|a)b*c', 'abc', TRUE},
            {0141, '((a)(b)c)(d)', 'abcd', TRUE},
            {0142, '[a-zA-Z_][a-zA-Z0-9_]*', 'alpha', TRUE},
            {0143, '[_A-Z]', '}', FALSE},
            {0144, '^a(bc+|b[eh])g|.h$', 'abh', TRUE},
            {0145, '(bc+d$|ef*g.|h?i(j|k))', 'effgz', TRUE},
            {0146, '(bc+d$|ef*g.|h?i(j|k))', 'ij', TRUE},
            {0147, '(bc+d$|ef*g.|h?i(j|k))', 'effg', FALSE},
            {0148, '(bc+d$|ef*g.|h?i(j|k))', 'bcdd', FALSE},
            {0149, '(bc+d$|ef*g.|h?i(j|k))', 'reffgz', TRUE},
            {0150, '((((((((((a))))))))))', 'a', TRUE},
            {0151, '((((((((((a))))))))))\\10', 'aa', TRUE},
            {0154, '(((((((((a)))))))))', 'a', TRUE},
            {0155, '[89]+', '1((((((7(9))))))', TRUE},
            {0156, 'multiple words of text', 'uh-uh', FALSE},
            {0157, 'multiple words', 'multiple words, yeah', TRUE},
            {0158, '(.*)c(.*)', 'abcde', TRUE},
            {0159, '\\((.*), (.*)\\)', '(a, b)', TRUE},
            {0160, '[k]', 'ab', FALSE},
            {0161, 'abcd', 'abcd', TRUE},
            {0162, 'a(bc)d', 'abcd', TRUE},
            {0163, 'a[-]?c', 'ac', TRUE},
            {0164, '(abc)\\1', 'abcabc', TRUE},
            {0165, '([a-c]*)\\1', 'abcabc', TRUE},
            {0166, '(a)|\\1', 'a', TRUE},
            {0167, '(a)|\\1', 'x', FALSE},
            {0168, '(?:(b)?a)\\1', 'a', FALSE},
            {0169, '(([a-c])b*?\\2)*', 'ababbbcbc', TRUE},
            {0170, '(([a-c])b*?\\2){3}', 'ababbbcbc', TRUE},
            {0171, '((\\3|b)\\2(a)x)+', 'aaxabxbaxbbx', FALSE},
            {0172, '((\\3|b)\\2(a)x)+', 'aaaxabaxbaaxbbax', TRUE},
            {0173, '((\\3|b)\\2(a)){2,}', 'bbaababbabaaaaabbaaaabba', TRUE},
            {0174, '^((.)?a\\2)+$', 'babadad', FALSE},
            {0175, '(a)|(b)', 'b', TRUE},
            {0176, 'a(?!b).', 'abad', TRUE},
            {0177, 'a(?=d).', 'abad', TRUE},
            {0178, 'a(?=c|d).', 'abad', TRUE},
            {0179, 'a(?:b|c|d)(.)', 'ace', TRUE},
            {0180, 'a(?:b|c|d)*(.)', 'ace', TRUE},
            {0181, 'a(?:b|c|d)+?(.)', 'ace', TRUE},
            {0182, 'a(?:b|c|d)+?(.)', 'acdbcdbe', TRUE},
            {0183, 'a(?:b|c|d)+(.)', 'acdbcdbe', TRUE},
            {0184, 'a(?:b|c|d){2}(.)', 'acdbcdbe', TRUE},
            {0185, 'a(?:b|c|d){4,5}(.)', 'acdbcdbe', TRUE},
            {0186, 'a(?:b|c|d){4,5}?(.)', 'acdbcdbe', TRUE},
            {0187, '((foo)|(bar))*', 'foobar', TRUE},
            {0188, 'a(?:b|c|d){6,7}(.)', 'acdbcdbe', TRUE},
            {0189, 'a(?:b|c|d){6,7}?(.)', 'acdbcdbe', TRUE},
            {0190, 'a(?:b|c|d){5,6}(.)', 'acdbcdbe', TRUE},
            {0191, 'a(?:b|c|d){5,6}?(.)', 'acdbcdbe', TRUE},
            {0192, 'a(?:b|c|d){5,7}(.)', 'acdbcdbe', TRUE},
            {0193, 'a(?:b|c|d){5,7}?(.)', 'acdbcdbe', TRUE},
            {0194, 'a(?:b|(c|e){1,2}?|d)+?(.)', 'ace', TRUE},
            {0195, '^(.+)?B', 'AB', TRUE},
            {0196, '^([^a-z])|(\\^)$', '.', TRUE},
            {0197, '^[<>]&', '<&OUT', TRUE},
            {0198, '^(a\\1?){4}$', 'aaaaaaaaaa', TRUE},
            {0199, '^(a\\1?){4}$', 'aaaaaaaaa', FALSE},
            {0200, '^(a\\1?){4}$', 'aaaaaaaaaaa', FALSE},
            {0201, '^(a(?(1)\\1)){4}$', 'aaaaaaaaaa', TRUE},
            {0202, '^(a(?(1)\\1)){4}$', 'aaaaaaaaa', FALSE},
            {0203, '^(a(?(1)\\1)){4}$', 'aaaaaaaaaaa', FALSE},
            {0204, '((?(1)a|b))+', 'baaa', TRUE},
            {0205, '((?(1)aa|b))+', 'baaaa', TRUE},
            {0206, '((a{4})+)', 'aaaaaaaaa', TRUE},
            {0207, '(((aa){2})+)', 'aaaaaaaaaa', TRUE},
            {0208, '(((a{2}){2})+)', 'aaaaaaaaaa', TRUE},
            {0209, '(?:(f)(o)(o)|(b)(a)(r))*', 'foobar', TRUE},
            {0210, '(?<=a)b', 'ab', TRUE},
            {0211, '(?<=a)b', 'cb', FALSE},
            {0212, '(?<=a)b', 'b', FALSE},
            {0213, '(?<!c)b', 'ab', TRUE},
            {0214, '(?<!c)b', 'cb', FALSE},
            {0215, '(?<!c)b', 'b', TRUE},
            {0216, '(?:..)*a', 'aba', TRUE},
            {0217, '(?:..)*?a', 'aba', TRUE},
            {0218, '^(?:b|a(?=(.)))*\\1', 'abc', TRUE},
            {0219, '^(){3,5}', 'abc', TRUE},
            {0220, '^(a+)*ax', 'aax', TRUE},
            {0221, '^((a|b)+)*ax', 'aax', TRUE},
            {0222, '^((a|bc)+)*ax', 'aax', TRUE},
            {0223, '(a|x)*ab', 'cab', TRUE},
            {0224, '(a)*ab', 'cab', TRUE},
            {0225, '(?:(?i)a)b', 'ab', TRUE},
            {0226, '((?i)a)b', 'ab', TRUE},
            {0227, '(?:(?i)a)b', 'aB', FALSE},
            {0228, '((?i)a)b', 'aB', FALSE},
            {0229, '(?i:a)b', 'ab', TRUE},
            {0230, '((?i:a))b', 'ab', TRUE},
            {0231, '(?i:a)b', 'aB', FALSE},
            {0232, '((?i:a))b', 'aB', FALSE},
            {0233, '(?:c|d)(?:)(?:a(?:)(?:b)(?:b(?:))(?:b(?:)(?:b)))', 'cabbbb', TRUE},
            {0234, '(?:c|d)(?:)(?:aaaaaaaa(?:)(?:bbbbbbbb)(?:bbbbbbbb(?:))(?:bbbbbbbb(?:)(?:bbbbbbbb)))', 'caaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', TRUE},
            {0235, 'foo\\w*\\d{4}baz', 'foobar1234baz', TRUE},
            {0236, 'x(~~)*(?:(?:F)?)?', 'x~~', TRUE},
            {0237, '^a(?#xxx){3}c', 'aaac', TRUE},
            {0239, '(?<![cd])b', 'dbcb', FALSE},
            {0240, '(?<![cd])[ab]', 'dbaacb', TRUE},
            {0241, '(?<!(c|d))b', 'dbcb', FALSE},
            {0242, '(?<!(c|d))[ab]', 'dbaacb', TRUE},
            {0243, '(?<!cd)[ab]', 'cdaccb', TRUE},
            {0244, '^(?:a?b?)*$', 'a--', FALSE},
            {0245, '((?s)^a(.))((?m)^b$)', 'a\nb\nc\n', TRUE},
            {0246, '((?m)^b$)', 'a\nb\nc\n', TRUE},
            {0247, '(?m)^b', 'a\nb\n', TRUE},
            {0248, '(?m)^(b)', 'a\nb\n', TRUE},
            {0249, '((?m)^b)', 'a\nb\n', TRUE},
            {0250, '\n((?m)^b)', 'a\nb\n', TRUE},
            {0251, '((?s).)c(?!.)', 'a\nb\nc\n', TRUE},
            {0252, '((?s)b.)c(?!.)', 'a\nb\nc\n', TRUE},
            {0253, '((?s)b.)c(?!\n)', 'a\nb\nc\n', TRUE},
            {0255, '^b', 'a\nb\nc\n', FALSE},
            {0256, '()^b', 'a\nb\nc\n', FALSE},
            {0257, '((?m)^b)', 'a\nb\nc\n', TRUE},
            {0258, '(x)?(?(1)a|b)', 'a', FALSE},
            {0259, '(x)?(?(1)b|a)', 'a', TRUE},
            {0260, '()?(?(1)b|a)', 'a', TRUE},
            {0261, '()(?(1)b|a)', 'a', FALSE},
            {0262, '()?(?(1)a|b)', 'a', TRUE},
            {0263, '^(\\()?blah(?(1)(\\)))$', '(blah)', TRUE},
            {0264, '^(\\()?blah(?(1)(\\)))$', 'blah', TRUE},
            {0265, '^(\\()?blah(?(1)(\\)))$', 'blah)', FALSE},
            {0266, '^(\\()?blah(?(1)(\\)))$', '(blah', FALSE},
            {0267, '^(\\(+)?blah(?(1)(\\)))$', '(blah)', TRUE},
            {0268, '^(\\(+)?blah(?(1)(\\)))$', 'blah', TRUE},
            {0269, '^(\\(+)?blah(?(1)(\\)))$', 'blah)', FALSE},
            {0270, '^(\\(+)?blah(?(1)(\\)))$', '(blah', FALSE},
            {0271, '(?(?!a)a|b)', 'a', FALSE},
            {0272, '(?(?!a)b|a)', 'a', TRUE},
            {0273, '(?(?=a)b|a)', 'a', FALSE},
            {0274, '(?(?=a)a|b)', 'a', TRUE},
            {0275, '(?=(a+?))(\\1ab)', 'aaab', TRUE},
            {0276, '^(?=(a+?))\\1ab', 'aaab', FALSE},
            {0277, '(\\w+:)+', 'one:', TRUE},
            {0278, '$(?<=^(a))', 'a', TRUE},
            {0279, '([\\w:]+::)?(\\w+)$', 'abcd:', FALSE},
            {0280, '([\\w:]+::)?(\\w+)$', 'abcd', TRUE},
            {0281, '([\\w:]+::)?(\\w+)$', 'xy:z:::abcd', TRUE},
            {0282, '^[^bcd]*(c+)', 'aexycd', TRUE},
            {0283, '(a*)b+', 'caab', TRUE},
            {0284, '(>a+)ab', 'aaab', FALSE},
            {0285, '(?>a+)b', 'aaab', TRUE},
            {0286, '([[:alpha:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0287, '([[:alnum:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0288, '([[:cntrl:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0289, '([[:digit:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0290, '([[:graph:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0291, '([[:lower:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0292, '([[:print:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0293, '([[:punct:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0294, '([[:space:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0295, '([[:word:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0296, '([[:upper:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0297, '([[:xdigit:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0298, '([[:^alpha:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0299, '([[:^cntrl:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0300, '([[:^digit:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0301, '([[:^lower:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0302, '([[:^punct:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0303, '([[:^space:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0304, '([[:^upper:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0305, '([[:^xdigit:]]+)', 'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0307, '((?>a+)b)', 'aaab', TRUE},
            {0308, '(?>(a+))b', 'aaab', TRUE},
            {0309, '((?>[^()]+)|\\([^()]*\\))+', '((abc(ade)ufh()()x', TRUE},
            {0310, '\\z', 'a\nb\n', TRUE},
            {0311, '$', 'a\nb\n', TRUE},
            {0312, '\\z', 'b\na\n', TRUE},
            {0313, '$', 'b\na\n', TRUE},
            {0314, '\\z', 'b\na', TRUE},
            {0315, '$', 'b\na', TRUE},
            {0322, 'a\\z', 'a\nb\n', FALSE},
            {0323, 'a$', 'a\nb\n', FALSE},
            {0324, 'a\\Z', 'b\na\n', TRUE},
            {0325, 'a\\z', 'b\na\n', FALSE},
            {0326, 'a$', 'b\na\n', TRUE},
            {0327, 'a\\z', 'b\na', TRUE},
            {0328, 'a$', 'b\na', TRUE},
            {0336, 'aa\\z', 'aa\nb\n', FALSE},
            {0337, 'aa$', 'aa\nb\n', FALSE},
            {0338, 'aa\\Z', 'b\naa\n', TRUE},
            {0339, 'aa\\z', 'b\naa\n', FALSE},
            {0340, 'aa$', 'b\naa\n', TRUE},
            {0341, 'aa\\z', 'b\naa', TRUE},
            {0342, 'aa$', 'b\naa', TRUE},
            {0350, 'aa\\z', 'ac\nb\n', FALSE},
            {0351, 'aa$', 'ac\nb\n', FALSE},
            {0352, 'aa\\z', 'b\nac\n', FALSE},
            {0353, 'aa$', 'b\nac\n', FALSE},
            {0354, 'aa\\z', 'b\nac', FALSE},
            {0355, 'aa$', 'b\nac', FALSE},
            {0362, 'aa\\z', 'ca\nb\n', FALSE},
            {0363, 'aa$', 'ca\nb\n', FALSE},
            {0364, 'aa\\z', 'b\nca\n', FALSE},
            {0365, 'aa$', 'b\nca\n', FALSE},
            {0366, 'aa\\z', 'b\nca', FALSE},
            {0367, 'aa$', 'b\nca', FALSE},
            {0374, 'ab\\z', 'ab\nb\n', FALSE},
            {0375, 'ab$', 'ab\nb\n', FALSE},
            {0376, 'ab\\Z', 'b\nab\n', TRUE},
            {0377, 'ab\\z', 'b\nab\n', FALSE},
            {0378, 'ab$', 'b\nab\n', TRUE},
            {0379, 'ab\\z', 'b\nab', TRUE},
            {0380, 'ab$', 'b\nab', TRUE},
            {0388, 'ab\\z', 'ac\nb\n', FALSE},
            {0389, 'ab$', 'ac\nb\n', FALSE},
            {0390, 'ab\\z', 'b\nac\n', FALSE},
            {0391, 'ab$', 'b\nac\n', FALSE},
            {0392, 'ab\\z', 'b\nac', FALSE},
            {0393, 'ab$', 'b\nac', FALSE},
            {0400, 'ab\\z', 'ca\nb\n', FALSE},
            {0401, 'ab$', 'ca\nb\n', FALSE},
            {0402, 'ab\\z', 'b\nca\n', FALSE},
            {0403, 'ab$', 'b\nca\n', FALSE},
            {0404, 'ab\\z', 'b\nca', FALSE},
            {0405, 'ab$', 'b\nca', FALSE},
            {0412, 'abb\\z', 'abb\nb\n', FALSE},
            {0413, 'abb$', 'abb\nb\n', FALSE},
            {0414, 'abb\\Z', 'b\nabb\n', TRUE},
            {0415, 'abb\\z', 'b\nabb\n', FALSE},
            {0416, 'abb$', 'b\nabb\n', TRUE},
            {0417, 'abb\\z', 'b\nabb', TRUE},
            {0418, 'abb$', 'b\nabb', TRUE},
            {0426, 'abb\\z', 'ac\nb\n', FALSE},
            {0427, 'abb$', 'ac\nb\n', FALSE},
            {0428, 'abb\\z', 'b\nac\n', FALSE},
            {0429, 'abb$', 'b\nac\n', FALSE},
            {0430, 'abb\\z', 'b\nac', FALSE},
            {0431, 'abb$', 'b\nac', FALSE},
            {0438, 'abb\\z', 'ca\nb\n', FALSE},
            {0439, 'abb$', 'ca\nb\n', FALSE},
            {0440, 'abb\\z', 'b\nca\n', FALSE},
            {0441, 'abb$', 'b\nca\n', FALSE},
            {0442, 'abb\\z', 'b\nca', FALSE},
            {0443, 'abb$', 'b\nca', FALSE},
            {0451, '(^|x)(c)', 'ca', TRUE},
            {0452, 'a*abc?xyz+pqr{3}ab{2,}xy{4,5}pq{0,6}AB{0,}zz', 'x', FALSE},
            {0453, 'round\\(((?>[^()]+))\\)', '_I(round(xs * sz),1)', TRUE},
            {0456, 'foo.bart', 'foo.bart', TRUE},
            {0458, 'tt+$', 'xxxtt', TRUE},
            {0459, '\\GX.*X', 'aaaXbX', FALSE},
            {0460, '(\\d+\\.\\d+)', '3.1415926', TRUE},
            {0461, '(\\ba.{0,10}br)', 'have a web browser', TRUE},
            {0462, '^([a-z]:)', 'C:/', FALSE},
            {0464, '(^|a)b', 'ab', TRUE},
            {0465, '^([ab]*?)(b)?(c)$', 'abac', TRUE},
            {0466, '(\\w)?(abc)\\1b', 'abcab', FALSE},
            {0467, '^(?:.,){2}c', 'a,b,c', TRUE},
            {0468, '^(.,){2}c', 'a,b,c', TRUE},
            {0469, '^(?:[^,]*,){2}c', 'a,b,c', TRUE},
            {0470, '^([^,]*,){2}c', 'a,b,c', TRUE},
            {0471, '^([^,]*,){3}d', 'aaa,b,c,d', TRUE},
            {0472, '^([^,]*,){3,}d', 'aaa,b,c,d', TRUE},
            {0473, '^([^,]*,){0,3}d', 'aaa,b,c,d', TRUE},
            {0474, '^([^,]{1,3},){3}d', 'aaa,b,c,d', TRUE},
            {0475, '^([^,]{1,3},){3,}d', 'aaa,b,c,d', TRUE},
            {0476, '^([^,]{1,3},){0,3}d', 'aaa,b,c,d', TRUE},
            {0477, '^([^,]{1,},){3}d', 'aaa,b,c,d', TRUE},
            {0478, '^([^,]{1,},){3,}d', 'aaa,b,c,d', TRUE},
            {0479, '^([^,]{1,},){0,3}d', 'aaa,b,c,d', TRUE},
            {0480, '^([^,]{0,3},){3}d', 'aaa,b,c,d', TRUE},
            {0481, '^([^,]{0,3},){3,}d', 'aaa,b,c,d', TRUE},
            {0482, '^([^,]{0,3},){0,3}d', 'aaa,b,c,d', TRUE},
            {0484, '^(a(b)?)+$', 'aba', TRUE},
            {0485, '^(aa(bb)?)+$', 'aabbaa', TRUE},
            {0487, '^(a)?a$', 'a', TRUE},
            {0488, '^(a)?(?(1)a|b)+$', 'a', FALSE},
            {0489, '^(a\\1?)(a\\1?)(a\\2?)(a\\3?)$', 'aaaaaa', TRUE},
            {0490, '^(a\\1?){4}$', 'aaaaaa', TRUE},
            {0491, '^(0+)?(?:x(1))?', 'x1', TRUE},
            {0492, '^([0-9a-fA-F]+)(?:x([0-9a-fA-F]+)?)(?:x([0-9a-fA-F]+))?', '012cxx0190', TRUE},
            {0493, '^(b+?|a){1,2}c', 'bbbac', TRUE},
            {0494, '^(b+?|a){1,2}c', 'bbbbac', TRUE},
            {0495, '\\((\\w\\. \\w+)\\)', 'cd. (A. Tw)', TRUE},
            {0496, '((?:aaaa|bbbb)cccc)?', 'aaaacccc', TRUE},
            {0497, '((?:aaaa|bbbb)cccc)?', 'bbbbcccc', TRUE},
            {0498, '(a)?(a)+', 'a', TRUE},
            {0499, '(ab)?(ab)+', 'ab', TRUE},
            {0500, '(abc)?(abc)+', 'abc', TRUE},
            {0502, '\\ba', 'a', TRUE},
            {0503, 'ab(?i)cd', 'AbCd', FALSE},
            {0504, 'ab(?i)cd', 'abCd', TRUE},
            {0505, '(A|B)*(?(1)(CD)|(CD))', 'CD', TRUE},
            {0506, '(A|B)*(?(1)(CD)|(CD))', 'ABCD', TRUE},
            {0507, '(A|B)*?(?(1)(CD)|(CD))', 'CD', TRUE},
            {0508, '(A|B)*?(?(1)(CD)|(CD))', 'ABCD', TRUE},
            {0509, '(.*)\\d+\\1', 'abc12bc', TRUE},
            {0510, '(?m:(foo\\s*$))', 'foo\n bar', TRUE},
            {0511, '(.*)c', 'abcd', TRUE},
            {0512, '(.*)(?=c)', 'abcd', TRUE},
            {0513, '(.*)(?=c)c', 'abcd', TRUE},
            {0514, '(.*)(?=b|c)', 'abcd', TRUE},
            {0515, '(.*)(?=b|c)c', 'abcd', TRUE},
            {0516, '(.*)(?=c|b)', 'abcd', TRUE},
            {0517, '(.*)(?=c|b)c', 'abcd', TRUE},
            {0518, '(.*)(?=[bc])', 'abcd', TRUE},
            {0519, '(.*)(?=[bc])c', 'abcd', TRUE},
            {0520, '(.*)(?<=b)', 'abcd', TRUE},
            {0521, '(.*)(?<=b)c', 'abcd', TRUE},
            {0522, '(.*)(?<=b|c)', 'abcd', TRUE},
            {0523, '(.*)(?<=b|c)c', 'abcd', TRUE},
            {0524, '(.*)(?<=c|b)', 'abcd', TRUE},
            {0525, '(.*)(?<=c|b)c', 'abcd', TRUE},
            {0526, '(.*)(?<=[bc])', 'abcd', TRUE},
            {0527, '(.*)(?<=[bc])c', 'abcd', TRUE},
            {0528, '(.*?)c', 'abcd', TRUE},
            {0529, '(.*?)(?=c)', 'abcd', TRUE},
            {0530, '(.*?)(?=c)c', 'abcd', TRUE},
            {0531, '(.*?)(?=b|c)', 'abcd', TRUE},
            {0532, '(.*?)(?=b|c)c', 'abcd', TRUE},
            {0533, '(.*?)(?=c|b)', 'abcd', TRUE},
            {0534, '(.*?)(?=c|b)c', 'abcd', TRUE},
            {0535, '(.*?)(?=[bc])', 'abcd', TRUE},
            {0536, '(.*?)(?=[bc])c', 'abcd', TRUE},
            {0537, '(.*?)(?<=b)', 'abcd', TRUE},
            {0538, '(.*?)(?<=b)c', 'abcd', TRUE},
            {0539, '(.*?)(?<=b|c)', 'abcd', TRUE},
            {0540, '(.*?)(?<=b|c)c', 'abcd', TRUE},
            {0541, '(.*?)(?<=c|b)', 'abcd', TRUE},
            {0542, '(.*?)(?<=c|b)c', 'abcd', TRUE},
            {0543, '(.*?)(?<=[bc])', 'abcd', TRUE},
            {0544, '(.*?)(?<=[bc])c', 'abcd', TRUE},
            {0545, '2(]*)?$\\1', '2', TRUE},
            {0546, 'a(b)??', 'abc', TRUE},
            {0547, '(\\d{1,3}\\.){3,}', '128.134.142.8', TRUE},
            {0548, '^.{3,4}(.+)\\1\\z', 'foobarbar', TRUE},
            {0549, '^(?:f|o|b){3,4}(.+)\\1\\z', 'foobarbar', TRUE},
            {0550, '^.{3,4}((?:b|a|r)+)\\1\\z', 'foobarbar', TRUE},
            {0551, '^(?:f|o|b){3,4}((?:b|a|r)+)\\1\\z', 'foobarbar', TRUE},
            {0552, '^.{3,4}(.+?)\\1\\z', 'foobarbar', TRUE},
            {0553, '^(?:f|o|b){3,4}(.+?)\\1\\z', 'foobarbar', TRUE},
            {0554, '^.{3,4}((?:b|a|r)+?)\\1\\z', 'foobarbar', TRUE},
            {0555, '^(?:f|o|b){3,4}((?:b|a|r)+?)\\1\\z', 'foobarbar', TRUE},
            {0556, '^.{2,3}?(.+)\\1\\z', 'foobarbar', TRUE},
            {0557, '^(?:f|o|b){2,3}?(.+)\\1\\z', 'foobarbar', TRUE},
            {0558, '^.{2,3}?((?:b|a|r)+)\\1\\z', 'foobarbar', TRUE},
            {0559, '^(?:f|o|b){2,3}?((?:b|a|r)+)\\1\\z', 'foobarbar', TRUE},
            {0560, '^.{2,3}?(.+?)\\1\\z', 'foobarbar', TRUE},
            {0561, '^(?:f|o|b){2,3}?(.+?)\\1\\z', 'foobarbar', TRUE},
            {0562, '^.{2,3}?((?:b|a|r)+?)\\1\\z', 'foobarbar', TRUE},
            {0563, '^(?:f|o|b){2,3}?((?:b|a|r)+?)\\1\\z', 'foobarbar', TRUE},
            {0564, '.*a(?!(b|cd)*e).*f', '......abef', FALSE},
            {0565, '(WORDS|WORD)S', 'WORDS', TRUE},
            {0566, '(X.|WORDS|X.|WORD)S', 'WORDS', TRUE},
            {0567, '(WORDS|WORLD|WORD)S', 'WORDS', TRUE},
            {0568, '(X.|WORDS|WORD|Y.)S', 'WORDS', TRUE},
            {0569, '(foo|fool|x.|money|parted)$', 'fool', TRUE},
            {0570, '(x.|foo|fool|x.|money|parted|y.)$', 'fool', TRUE},
            {0571, '(foo|fool|money|parted)$', 'fool', TRUE},
            {0572, '(foo|fool|x.|money|parted)$', 'fools', FALSE},
            {0573, '(x.|foo|fool|x.|money|parted|y.)$', 'fools', FALSE},
            {0574, '(foo|fool|money|parted)$', 'fools', FALSE},
            {0575, '(a|aa|aaa||aaaa|aaaaa|aaaaaa)(b|c)', 'aaaaaaaaaaaaaaab', TRUE},
            {0576, '^(a*?)(?!(aa|aaaa)*$)', 'aaaaaaaaaaaaaaaaaaaa', TRUE},
            {0577, '^(a*?)(?!(aa|aaaa)*$)(?=a\\z)', 'aaaaaaaa', TRUE},
            {0578, '^(.)\\s+.$(?(1))', 'A B', TRUE},
            {0579, '(?:r?)*?r|(.{2,4})', 'abcde', TRUE},
            {0580, '(?!)+?|(.{2,4})', 'abcde', TRUE},
            {0581, '^(a*?)(?!(a{6}|a{5})*$)', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', TRUE},
            {0582, '^((?>(?:aa)?b)?)', 'aab', TRUE},
            {0583, '^((?:aa)*)(?:X+((?:\\d+|-)(?:X+(.+))?))?$', 'aaaaX5', TRUE},
            {0584, 'X(A|B||C|D)Y', 'XXXYYY', TRUE},
            {0585, '(?i:X([A]|[B]|y[Y]y|[D]|)Y)', 'XXXYYYB', TRUE},
            {0586, '^([a]{1})*$', 'aa', TRUE},
            {0587, 'a(?!b(?!c))(..)', 'abababc', TRUE},
            {0588, 'a(?!b(?=a))(..)', 'abababc', TRUE},
            {0589, 'a(?!b(?!c(?!d(?!e))))...(.)', 'abxabcdxabcde', TRUE},
            {0590, 'X(?!b+(?!(c+)*(?!(c+)*d))).*X', 'aXbbbbbbbcccccccccccccaaaX', TRUE},
            {0591, '^(XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0592, '^(XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQX:', TRUE},
            {0593, '^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0594, '^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQX:', TRUE},
            {0595, '^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', 'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0596, '^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', 'ZEQQQX:', TRUE},
            {0597, '^(XXX|YYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0598, '^(XXX|YYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQX:', TRUE},
            {0599, '^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0600, '^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P):', 'ZEQQQX:', TRUE},
            {0601, '^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', 'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0602, '^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', 'ZEQQQX:', TRUE},
            {0603, 'X(?:ABCF[cC]x*|ABCD|ABCF):(?:DIT|DID|DIM)', 'XABCFCxxxxxxxxxx:DIM', TRUE},
            {0604, '(((ABCD|ABCE|ABCF)))(A|B|C[xy]*):', 'ABCFCxxxxxxxxxx:DIM', TRUE},
            {0605, '(?=foo)', 'foo', TRUE},
            {0606, '(?=foo)', 'XfooY', TRUE},
            {0607, '.*(?=foo)', 'XfooY', TRUE},
            {0608, '(?=.*P)P', 'aP', TRUE},
            {0609, '(?<=foo)', 'foo', TRUE},
            {0610, '(?<=foo)', 'XfooY', TRUE},
            {0611, '.*(?<=foo)', 'foo', TRUE},
            {0612, '.*(?<=foo)', 'XfooY', TRUE},
            {0613, '(?<=foo)Y', 'XfooY', TRUE},
            {0614, 'o(?<=foo)Y', '..XfooY..', TRUE},
            {0615, 'X(?=foo)f', '..XfooY..', TRUE},
            {0616, 'X(?=foo)', '..XfooY..', TRUE},
            {0617, 'X(?<=foo.)[YZ]', '..XfooXY..', TRUE},
            {0618, '(?=XY*foo)', 'Xfoo', TRUE},
            {0619, '^(?=XY*foo)', 'Xfoo', TRUE},
            {0620, '^(<(?:[^<>]+|(?3)|(?1))*>)()(!>!>!>)$', '<<!>!>!>><>>!>!>!>', TRUE},
            {0621, '^(<(?:[^<>]+|(?1))*>)$', '<<><<<><>>>>', TRUE},
            {0622, '((?2)*)([fF]o+)', 'fooFoFoo', TRUE},
            {0623, '(<(?:[^<>]+|(?R))*>)', '<<><<<><>>>>', TRUE},
            {0624, '(?<n>foo|bar|baz)', 'snofooewa', TRUE},
            {0625, '(?<n>foo|bar|baz)(?<m>[ew]+)', 'snofooewa', TRUE},
            {0626, '(?<A>foo)?(?(<A>)bar|nada)', 'foobar', TRUE},
            {0627, '(?<A>foo)?(?(<A>)bar|nada)', 'foo-barnada', TRUE},
            {0628, '(?<A>foo)?(?(1)bar|nada)', 'foo-barnada', TRUE},
            {0629, '(?<A>foo(?(R)bar))?(?1)', 'foofoobar', TRUE},
            {0630, '(x)(?<A>foo(?(R&A)bar))?(?&A)', 'xfoofoobar', TRUE},
            {0631, '(x)(?<A>foo(?(R2)bar))?(?&A)', 'xfoofoobar', TRUE},
            {0632, '(?1)(?(DEFINE)(blah))', 'blah', TRUE},
            {0633, 'foo(?0)?bar', 'phoofoofoobarbarbarr', TRUE},
            {0634, 'foo(?R)?bar', 'phoofoofoobarbarbarr', TRUE},
            {0635, 'a++a', 'aaaaa', FALSE},
            {0636, 'a*+a', 'aaaaa', FALSE},
            {0637, 'a{1,5}+a', 'aaaaa', FALSE},
            {0638, 'a?+a', 'ab', FALSE},
            {0639, 'a++b', 'aaaaab', TRUE},
            {0640, 'a*+b', 'aaaaab', TRUE},
            {0641, 'a{1,5}+b', 'aaaaab', TRUE},
            {0642, 'a?+b', 'ab', TRUE},
            {0643, 'fooa++a', 'fooaaaaa', FALSE},
            {0644, 'fooa*+a', 'fooaaaaa', FALSE},
            {0645, 'fooa{1,5}+a', 'fooaaaaa', FALSE},
            {0646, 'fooa?+a', 'fooab', FALSE},
            {0647, 'fooa++b', 'fooaaaaab', TRUE},
            {0648, 'fooa*+b', 'fooaaaaab', TRUE},
            {0649, 'fooa{1,5}+b', 'fooaaaaab', TRUE},
            {0650, 'fooa?+b', 'fooab', TRUE},
            {0651, '(?:aA)++(?:aA)', 'aAaAaAaAaA', FALSE},
            {0652, '(aA)++(aA)', 'aAaAaAaAaA', FALSE},
            {0653, '(aA|bB)++(aA|bB)', 'aAaAbBaAbB', FALSE},
            {0654, '(?:aA|bB)++(?:aA|bB)', 'aAbBbBbBaA', FALSE},
            {0655, '(?:aA)*+(?:aA)', 'aAaAaAaAaA', FALSE},
            {0656, '(aA)*+(aA)', 'aAaAaAaAaA', FALSE},
            {0657, '(aA|bB)*+(aA|bB)', 'aAaAbBaAaA', FALSE},
            {0658, '(?:aA|bB)*+(?:aA|bB)', 'aAaAaAbBaA', FALSE},
            {0659, '(?:aA){1,5}+(?:aA)', 'aAaAaAaAaA', FALSE},
            {0660, '(aA){1,5}+(aA)', 'aAaAaAaAaA', FALSE},
            {0661, '(aA|bB){1,5}+(aA|bB)', 'aAaAbBaAaA', FALSE},
            {0662, '(?:aA|bB){1,5}+(?:aA|bB)', 'bBbBbBbBbB', FALSE},
            {0663, '(?:aA)?+(?:aA)', 'aAb', FALSE},
            {0664, '(aA)?+(aA)', 'aAb', FALSE},
            {0665, '(aA|bB)?+(aA|bB)', 'bBb', FALSE},
            {0666, '(?:aA|bB)?+(?:aA|bB)', 'aAb', FALSE},
            {0667, '(?:aA)++b', 'aAaAaAaAaAb', TRUE},
            {0668, '(aA)++b', 'aAaAaAaAaAb', TRUE},
            {0669, '(aA|bB)++b', 'aAbBaAaAbBb', TRUE},
            {0670, '(?:aA|bB)++b', 'aAbBbBaAaAb', TRUE},
            {0671, '(?:aA)*+b', 'aAaAaAaAaAb', TRUE},
            {0672, '(aA)*+b', 'aAaAaAaAaAb', TRUE},
            {0673, '(aA|bB)*+b', 'bBbBbBbBbBb', TRUE},
            {0674, '(?:aA|bB)*+b', 'bBaAbBbBaAb', TRUE},
            {0675, '(?:aA){1,5}+b', 'aAaAaAaAaAb', TRUE},
            {0676, '(aA){1,5}+b', 'aAaAaAaAaAb', TRUE},
            {0677, '(aA|bB){1,5}+b', 'bBaAbBaAbBb', TRUE},
            {0678, '(?:aA|bB){1,5}+b', 'aAbBaAbBbBb', TRUE},
            {0679, '(?:aA)?+b', 'aAb', TRUE},
            {0680, '(aA)?+b', 'aAb', TRUE},
            {0681, '(aA|bB)?+b', 'bBb', TRUE},
            {0682, '(?:aA|bB)?+b', 'bBb', TRUE},
            {0683, 'foo(?:aA)++(?:aA)', 'fooaAaAaAaAaA', FALSE},
            {0684, 'foo(aA)++(aA)', 'fooaAaAaAaAaA', FALSE},
            {0685, 'foo(aA|bB)++(aA|bB)', 'foobBbBbBaAaA', FALSE},
            {0686, 'foo(?:aA|bB)++(?:aA|bB)', 'fooaAaAaAaAaA', FALSE},
            {0687, 'foo(?:aA)*+(?:aA)', 'fooaAaAaAaAaA', FALSE},
            {0688, 'foo(aA)*+(aA)', 'fooaAaAaAaAaA', FALSE},
            {0689, 'foo(aA|bB)*+(aA|bB)', 'foobBaAbBaAaA', FALSE},
            {0690, 'foo(?:aA|bB)*+(?:aA|bB)', 'fooaAaAbBbBaA', FALSE},
            {0691, 'foo(?:aA){1,5}+(?:aA)', 'fooaAaAaAaAaA', FALSE},
            {0692, 'foo(aA){1,5}+(aA)', 'fooaAaAaAaAaA', FALSE},
            {0693, 'foo(aA|bB){1,5}+(aA|bB)', 'fooaAbBbBaAaA', FALSE},
            {0694, 'foo(?:aA|bB){1,5}+(?:aA|bB)', 'fooaAbBbBaAbB', FALSE},
            {0695, 'foo(?:aA)?+(?:aA)', 'fooaAb', FALSE},
            {0696, 'foo(aA)?+(aA)', 'fooaAb', FALSE},
            {0697, 'foo(aA|bB)?+(aA|bB)', 'foobBb', FALSE},
            {0698, 'foo(?:aA|bB)?+(?:aA|bB)', 'fooaAb', FALSE},
            {0699, 'foo(?:aA)++b', 'fooaAaAaAaAaAb', TRUE},
            {0700, 'foo(aA)++b', 'fooaAaAaAaAaAb', TRUE},
            {0701, 'foo(aA|bB)++b', 'foobBaAbBaAbBb', TRUE},
            {0702, 'foo(?:aA|bB)++b', 'fooaAaAbBaAaAb', TRUE},
            {0703, 'foo(?:aA)*+b', 'fooaAaAaAaAaAb', TRUE},
            {0704, 'foo(aA)*+b', 'fooaAaAaAaAaAb', TRUE},
            {0705, 'foo(aA|bB)*+b', 'foobBbBaAaAaAb', TRUE},
            {0706, 'foo(?:aA|bB)*+b', 'foobBaAaAbBaAb', TRUE},
            {0707, 'foo(?:aA){1,5}+b', 'fooaAaAaAaAaAb', TRUE},
            {0708, 'foo(aA){1,5}+b', 'fooaAaAaAaAaAb', TRUE},
            {0709, 'foo(aA|bB){1,5}+b', 'foobBaAaAaAaAb', TRUE},
            {0710, 'foo(?:aA|bB){1,5}+b', 'fooaAbBaAbBbBb', TRUE},
            {0711, 'foo(?:aA)?+b', 'fooaAb', TRUE},
            {0712, 'foo(aA)?+b', 'fooaAb', TRUE},
            {0713, 'foo(aA|bB)?+b', 'foobBb', TRUE},
            {0714, 'foo(?:aA|bB)?+b', 'foobBb', TRUE},
            {0715, '([^()]++|\\([^()]*\\))+', '((abc(ade)ufh()()x', TRUE},
            {0716, 'round\\(([^()]++)\\)', '_I(round(xs * sz),1)', TRUE},
            {0717, '(foo[1x]|bar[2x]|baz[3x])+y', 'foo1bar2baz3y', TRUE},
            {0718, '(foo[1x]|bar[2x]|baz[3x])*y', 'foo1bar2baz3y', TRUE},
            {0719, '([yX].|WORDS|[yX].|WORD)S', 'WORDS', TRUE},
            {0720, '([yX].|WORDS|WORD|[xY].)S', 'WORDS', TRUE},
            {0721, '(foo|fool|[zx].|money|parted)$', 'fool', TRUE},
            {0722, '([zx].|foo|fool|[zq].|money|parted|[yx].)$', 'fool', TRUE},
            {0723, '(foo|fool|[zx].|money|parted)$', 'fools', FALSE},
            {0724, '([zx].|foo|fool|[qx].|money|parted|[py].)$', 'fools', FALSE},
            {0725, '([yX].|WORDS|[yX].|WORD)+S', 'WORDS', TRUE},
            {0726, '(WORDS|WORLD|WORD)+S', 'WORDS', TRUE},
            {0727, '([yX].|WORDS|WORD|[xY].)+S', 'WORDS', TRUE},
            {0728, '(foo|fool|[zx].|money|parted)+$', 'fool', TRUE},
            {0729, '([zx].|foo|fool|[zq].|money|parted|[yx].)+$', 'fool', TRUE},
            {0730, '(foo|fool|[zx].|money|parted)+$', 'fools', FALSE},
            {0731, '([zx].|foo|fool|[qx].|money|parted|[py].)+$', 'fools', FALSE},
            {0732, '(x|y|z[QW])+(longish|loquatious|excessive|overblown[QW])+', 'xyzQzWlongishoverblownW', TRUE},
            {0733, '(x|y|z[QW])*(longish|loquatious|excessive|overblown[QW])*', 'xyzQzWlongishoverblownW', TRUE},
            {0734, '(x|y|z[QW]){1,5}(longish|loquatious|excessive|overblown[QW]){1,5}', 'xyzQzWlongishoverblownW', TRUE},
            {0735, '(x|y|z[QW])++(longish|loquatious|excessive|overblown[QW])++', 'xyzQzWlongishoverblownW', TRUE},
            {0736, '(x|y|z[QW])*+(longish|loquatious|excessive|overblown[QW])*+', 'xyzQzWlongishoverblownW', TRUE},
            {0737, '(x|y|z[QW]){1,5}+(longish|loquatious|excessive|overblown[QW]){1,5}+', 'xyzQzWlongishoverblownW', TRUE},
            {0738, 'a*(?!)', 'aaaab', FALSE},
            {0739, 'a*(*FAIL)', 'aaaab', FALSE},
            {0740, 'a*(*F)', 'aaaab', FALSE},
            {0741, '(A(A|B(*ACCEPT)|C)D)(E)', 'AB', TRUE},
            {0742, '(A(A|B(*ACCEPT)|C)D)(E)', 'ACDE', TRUE},
            {0743, '(a)(?:(?-1)|(?+1))(b)', 'aab', TRUE},
            {0744, '(a)(?:(?-1)|(?+1))(b)', 'abb', TRUE},
            {0745, '(a)(?:(?-1)|(?+1))(b)', 'acb', FALSE},
            {0746, '(foo)(\\g-2)', 'foofoo', TRUE},
            {0747, '(foo)(\\g-2)(foo)(\\g-2)', 'foofoofoofoo', TRUE},
            {0748, '(([abc]+) \\g-1)(([abc]+) \\g{-1})', 'abc abccba cba', TRUE},
            {0749, '(a)(b)(c)\\g1\\g2\\g3', 'abcabc', TRUE},
            {0750, '(?<=bar>)foo', 'bar>foo', TRUE},
            {0751, '(?<!bar>)foo', 'bar>foo', FALSE},
            {0752, '(?<=bar>ABC)foo', 'bar>ABCfoo', TRUE},
            {0753, '(?<!bar>ABC)foo', 'bar>ABCfoo', FALSE},
            {0754, '(?<bar>)foo', 'bar>ABCfoo', TRUE},
            {0755, '(?<bar>ABC)foo', 'bar>ABCfoo', TRUE},
            {0756, '(?<=abcd(?<=(aaaabcd)))', '..aaaabcd..', TRUE},
            {0757, '(?=xy(?<=(aaxy)))', '..aaxy..', TRUE},
            {0758, 'X(\\w+)(?=\\s)|X(\\w+)', 'Xab', TRUE},
            {0759, '(?|(a))', 'a', TRUE},
            {0760, '(?|a(.)b|d(.(o).)d|i(.)(.)j)(.)', 'd!o!da', TRUE},
            {0761, '(?|a(.)b|d(.(o).)d|i(.)(.)j)(.)', 'aabc', TRUE},
            {0762, '(?|a(.)b|d(.(o).)d|i(.)(.)j)(.)', 'ixyjp', TRUE},
            {0763, '(?|(?|(a)|(b))|(?|(c)|(d)))', 'a', TRUE},
            {0764, '(?|(?|(a)|(b))|(?|(c)|(d)))', 'b', TRUE},
            {0765, '(?|(?|(a)|(b))|(?|(c)|(d)))', 'c', TRUE},
            {0766, '(?|(?|(a)|(b))|(?|(c)|(d)))', 'd', TRUE},
            {0767, '(.)(?|(.)(.)x|(.)d)(.)', 'abcde', TRUE},
            {0768, '(\n)(?|(\n)(\n)x|(\n)d)(\n)', 'abcde', FALSE},
            {0769, '(?|(?<foo>x))', 'x', TRUE},
            {0770, '(?<bar>)(?|(?<foo>x))', 'x', TRUE},
            {0771, '(?|(b)|()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()(a))', 'a', TRUE},
            {0772, '(?(DEFINE)(?<A>(?&B)+)(?<B>a))(?&A)', 'a', TRUE},
            {0773, '(?(DEFINE)(?<A>(?&B)+)(?<B>a))(?&A)', 'aa', TRUE},
            {0774, 'foo(\r)bar', 'foo\r\nbar', TRUE},
            {0775, 'foo(\r)bar', 'foo\nbar', TRUE},
            {0776, 'foo(\r)bar', 'foo\rbar', TRUE},
            {0777, 'foo(\r+)bar', 'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0778, '(\\V+)(\r)', 'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0779, '(\r+)(\\V)', 'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0780, 'foo(\r)bar', 'foo\\x{85}bar', TRUE},
            {0781, '(\\V)(\r)', 'foo\\x{85}bar', TRUE},
            {0782, '(\r)(\\V)', 'foo\\x{85}bar', TRUE},
            {0783, '(\\V)(\r)', 'foo\r\nbar', TRUE},
            {0784, '(\r)(\\V)', 'foo\r\nbar', TRUE},
            {0785, '(\\V)(\r)', 'foo\rbar', TRUE},
            {0786, '(\r)(\\V)', 'foo\rbar', TRUE},
            {0787, '0|\r??\n0', '\n\n', FALSE},
            {0788, 'foo(\\v+)bar', 'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0789, '(\\v+)(\\V)', 'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0790, 'foo(\\v)bar', 'foo\\x{85}bar', TRUE},
            {0791, '(\\v)(\\V)', 'foo\\x{85}bar', TRUE},
            {0792, 'foo(\\v)bar', 'foo\rbar', TRUE},
            {0793, '(\\v)(\\V)', 'foo\rbar', TRUE},
            {0794, 'foo(\\h+)bar', 'foo\t\\x{A0}bar', TRUE},
            {0795, '(\\h+)(\\H)', 'foo\t\\x{A0}bar', TRUE},
            {0796, 'foo(\\h)bar', 'foo\\x{A0}bar', TRUE},
            {0797, '(\\h)(\\H)', 'foo\\x{A0}bar', TRUE},
            {0798, 'foo(\\h)bar', 'foo\tbar', TRUE},
            {0799, '(\\h)(\\H)', 'foo\tbar', TRUE},
            {0800, '.*\\z', 'foo\n', TRUE},
            {0801, '\n*\\z', 'foo\n', TRUE},
            {0802, '^(?:(\\d)x)?\\d$', '1', TRUE},
            {0803, '.*?(?:(\\w)|(\\w))x', 'abx', TRUE},
            {0804, '0{50}', '000000000000000000000000000000000000000000000000000', TRUE},
            {0805, '^a?(?=b)b', 'ab', TRUE},
            {0806, '^a*(?=b)b', 'ab', TRUE},
            {0807, '[\\s][\\S]', '\\x{a0}\\x{a0}', FALSE},
            {0808, 'abc\n\\{U+BEEF\\}', 'abc.{UBEEF}', TRUE},
            {0809, 'abc\n', 'abcd', TRUE},
            {0810, 'abc\n', 'abc\n', FALSE},
            {0811, '\\c@', '\\0', FALSE},
            {0812, '\\cA', '\\001', FALSE},
            {0813, '\\cB', '\\002', FALSE},
            {0814, '\\cC', '\\003', FALSE},
            {0815, '\\cI', '\\011', FALSE},
            {0816, '\\cJ', '\\012', FALSE},
            {0817, '\\cR', '\\022', FALSE},
            {0818, '\\cS', '\\023', FALSE},
            {0819, '\\cX', '\\030', FALSE},
            {0820, '\\cY', '\\031', FALSE},
            {0821, '\\cZ', '\\032', FALSE},
            {0822, '\\c[', '\\033', FALSE},
            {0823, '\\c\\X', '\\034X', FALSE},
            {0824, '\\c]', '\\035', FALSE},
            {0825, '\\c^', '\\036', FALSE},
            {0826, '\\c_', '\\037', FALSE},
            {0827, '\\o{120}', '\\x{50}', TRUE},
            {0828, '[a\\o{120}]', '\\x{50}', TRUE},
            {0829, '[\\006]', '\\006', TRUE},
            {0830, '[\\006]', '6\\000', FALSE},
            {0831, '[\\0005]', '\\0005', TRUE},
            {0832, '[\\0005]', '5\\000', TRUE},
            {0833, '[\\_]', '_', TRUE},
            {0834, '(q1|.)*(q2|.)*(x(a|bc)*y){2,}', 'xayxay', TRUE},
            {0835, '(q1|.)*(q2|.)*(x(a|bc)*y){2,3}', 'xayxay', TRUE},
            {0836, '(q1|z)*(q2|z)*z{15}-.*?(x(a|bc)*y){2,3}Z', 'zzzzzzzzzzzzzzzz-xayxayxayxayZ', TRUE},
            {0837, '(?:(?:)foo|bar|zot|rt78356)', 'foo', TRUE},
            {0838, '^m?(\\S)(.*)\\1$', 'aba', TRUE},
            {0839, '^m?(\\S)(.*)\\1$', '\tb\t', FALSE},
            {0840, '^m?(\\s)(.*)\\1$', '\tb\t', TRUE},
            {0841, '^m?(\\s)(.*)\\1$', 'aba', FALSE},
            {0842, '^m?(\\W)(.*)\\1$', ':b:', TRUE},
            {0843, '^m?(\\W)(.*)\\1$', 'aba', FALSE},
            {0844, '^m?(\\w)(.*)\\1$', 'aba', TRUE},
            {0845, '^m?(\\w)(.*)\\1$', ':b:', FALSE},
            {0846, '^m?(\\D)(.*)\\1$', 'aba', TRUE},
            {0847, '^m?(\\D)(.*)\\1$', '5b5', FALSE},
            {0848, '^m?(\\d)(.*)\\1$', '5b5', TRUE},
            {0849, '^m?(\\d)(.*)\\1$', 'aba', FALSE},
            {0850, '^_?[^\\W_0-9]\\w\\z', '\\xAA\\x{100}', TRUE},
            {0851, '(?#( (?{1+)a', 'a', TRUE},
            {0852, 'ab[(?{1]', 'ab1', TRUE},
            {0853, 'ab[(?{1\\](?{2]', 'ab2', TRUE},
            {0854, '[^\\p{Alphabetic}]', '\\x{100}', FALSE},
            {0855, '^(.)(?:(..)|B)[CX]', 'ABCDE', TRUE},
            {0856, '^(.)(?:BC(.)|B)[CX]', 'ABCDE', TRUE},
            {0857, '^(.)(?:(.)+)*[BX]', 'ABCDE', TRUE},
            {0858, '^(.)(BC)*', 'ABCDE', TRUE},
            {0859, '^(.)(BC)*[BX]', 'ABCDE', TRUE},
            {0860, '^(.)(B)*.[DX]', 'ABCDE', TRUE},
            {0861, '^(.)(B)*.[CX]', 'ABCDE', TRUE},
            {0862, '^(?:(X)?(\\d)|(X)?(\\d\\d))$', 'X12', TRUE},
            {0863, '^(?:(XX)?(\\d)|(XX)?(\\d\\d))$', 'XX12', TRUE},
            {0864, '\\A(?>\\[(?:(?:)(?:R){1}|T|V?|A)\\])\\z', '[A]', TRUE},
            {0865, '[^\n]+', '\nb', TRUE},
            {0866, '[^\n]+', 'a\n', TRUE},
            {0867, '\\w', '\\x{200C}', TRUE},
            {0868, '\\W', '\\x{200C}', FALSE},
            {0869, '\\w', '\\x{200D}', TRUE},
            {0870, '\\W', '\\x{200D}', FALSE},
            {0871, '^\r{2}$', '\r\n\r\n', TRUE},
            {0872, '\\Vn', '\\xFFn/', TRUE},
            {0873, '^_?[^\\S_0-9]\\w*\\z', '\t', TRUE},
            {0874, 'a?\\X', 'a\\x{100}', TRUE},
            {0875, 'a?\r', 'a\n', TRUE},
            {0876, '^a?\n$', 'a\n', TRUE},
            {0877, '\n?a', '\na', TRUE},
            {0878, '(A(*PRUNE)B|A(*PRUNE)C)', 'AC', FALSE},
            {0879, '(A(*PRUNE)B|A(*PRUNE)D|A(*PRUNE)C)', 'AC', FALSE},
            {0880, '(A(*PRUNE)B|A(*PRUNE)C|A(*PRUNE)D)', 'AC', FALSE},
            {0881, '((A(*PRUNE)B|A(*PRUNE)C))', 'AC', FALSE},
            {0882, '((A(*PRUNE)B|A(*PRUNE)D|A(*PRUNE)C))', 'AC', FALSE},
            {0883, '((A(*PRUNE)B|A(*PRUNE)C|A(*PRUNE)D))', 'AC', FALSE},
            {0884, 'A+?(*THEN)BC', 'AAABC', TRUE},
            {0885, 'A+?(*PRUNE)BC', 'AAABC', TRUE},
            {0886, 'A+(*THEN)BC', 'AAABC', TRUE},
            {0887, 'A+(*PRUNE)BC', 'AAABC', TRUE},
            {0888, '^(?=(a)){0}b(?1)', 'back', TRUE},
            {0889, '(?:(a(*SKIP)b)){0}(?:(?1)|ac)', 'x', FALSE},
            {0890, '(?1)(?:(b)){0}', 'b', TRUE},
            {0891, '(?<W>a)(?<BB>(?=(?&W))(?<=(?&W)))(?&BB)', 'aa', TRUE},
            {0892, '^x?abc?de', 'abcde', TRUE},
            {0895, '\\d<(.*?)>', 'a<>', FALSE},
            {0896, '[bcd].{2,3}aaaa', 'XbXaaaaa', TRUE},
            {0897, '[bcd].{2,3}aaaa', 'Xb\\x{100}aaaaa', TRUE},
            {0899, '^((?(?=x)xb|ya)z)', 'xbz', TRUE},
            {0900, '^((?(?=x)xb|ya)z)', 'yaz', TRUE},
            {0901, '^((?(?!y)xb|ya)z)', 'xbz', TRUE},
            {0902, '^((?(?!y)xb|ya)z)', 'yaz', TRUE},
            {0903, '^((?(?!)xb|ya)z)', 'xbz', FALSE},
            {0904, '^((?(?!)xb|ya)z)', 'yaz', TRUE},
            {0905, 'ab(?#Comment){2}c', 'abbc', TRUE},
            {0906, '(?:.||)(?|)000000000@', '000000000@', TRUE},
            {0907, 'aa$|a(?R)a|a', 'aaa', TRUE},
            {0908, '(?:\\1|a)([bcd])\\1(?:(?R)|e)\\1', 'abbaccaddedcb', TRUE},
            {0909, '(.*?(a(a)|i(i))n)', 'riiaan', TRUE},
            {0910, '(^(?:(\\d)x)?\\d$)', '1', TRUE},
            {0911, '(X{2,}[-X]{1,4}){3,}X{2,}', 'XXX-XXX-XXX--', FALSE},
            {0912, '^a?bcd\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', FALSE},
            {0913, '^Xaaa?Xaa', 'aaa\\x{400000}', FALSE},
            {0914, '^(\\d+)*?4X$', '1234X', TRUE},
            {0915, '\\A([\\x00-\\x7F]+)(.*)\\z', '\\007\\011\\012', TRUE},
            {0916, '^((\\w|<(\\s)*(?1)(?3)*>)(?:(?3)*\\+(?3)*(?2))*)(?3)*\\+', 'a + b + <c + d>', TRUE},
            {0917, '^((\\w|<(\\s)*(?1)(?3)*>)(?:(?3)*\\+(?3)*(?2))*)(?3)*\\+', 'a + <b> + c', TRUE},
            {0918, '(?<=(?<!yz)b)c', 'aabcdef', TRUE},
            {0919, '(?<=(?<!yz)b)c', 'abcdef', TRUE},
            {0920, '(?:a|xx){0,4}?b', 'aaaaab ', TRUE},
            {0921, '(?|(a)|(b))', 'b', TRUE},
            {0922, '(?|(a)|(b))', 'a', TRUE}
        ],
        {UNSIGNED4 testNum, UTF8 regex, UTF8 subject, BOOLEAN expected}
    );

res := PROJECT
    (
        NOFOLD(regexTests),
        TRANSFORM
            (
                {
                    RECORDOF(LEFT) - [regex, subject],
                    BOOLEAN actual
                },
                SELF.actual := REGEXFIND(LEFT.regex, LEFT.subject),
                SELF := LEFT
            )
    );

numTests := COUNT(regexTests);
testsPassed := res(expected = actual);
numTestsPassed := COUNT(testsPassed);
testsFailed := res(expected != actual);
numTestsFailed := COUNT(testsFailed);

MIN_PASS_PERCENTAGE := 0.95;

passedPercentage := numTestsPassed / numTests;
isSuccess := passedPercentage >= MIN_PASS_PERCENTAGE;
resultStr := IF(isSuccess, 'PASSED', 'FAILED');
fullResultStr := resultStr + ': ' + (STRING)(ROUND(passedPercentage * 100, 2));

// Output for unit test parsing
OUTPUT(resultStr, NAMED('result'));

// Uncomment the following to see details
// OUTPUT(numTests, NAMED('num_tests'));
// OUTPUT(numTestsPassed, NAMED('num_passed'));
// OUTPUT(numTestsFailed, NAMED('num_failed'));
// OUTPUT(fullResultStr, NAMED('result_desc'));
// OUTPUT(testsFailed, NAMED('failed_tests'), ALL);
