/*##############################################################################

    HPCC SYSTEMS software Copyright (C) 2024 HPCC Systems®.
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
############################################################################## */

//Tests derived from the python3 test suite

#OPTION('globalFold', FALSE);

regexTests := DATASET
    (
        [
            {0001, U'abc', U'abc', TRUE},
            {0002, U'abc', U'xbc', FALSE},
            {0003, U'abc', U'axc', FALSE},
            {0004, U'abc', U'abx', FALSE},
            {0005, U'abc', U'xabcy', TRUE},
            {0006, U'abc', U'ababc', TRUE},
            {0007, U'ab*c', U'abc', TRUE},
            {0008, U'ab*bc', U'abc', TRUE},
            {0009, U'ab*bc', U'abbc', TRUE},
            {0010, U'ab*bc', U'abbbbc', TRUE},
            {0011, U'.{1}', U'abbbbc', TRUE},
            {0012, U'.{3,4}', U'abbbbc', TRUE},
            {0013, U'ab{0,}bc', U'abbbbc', TRUE},
            {0014, U'ab+bc', U'abbc', TRUE},
            {0015, U'ab+bc', U'abc', FALSE},
            {0016, U'ab+bc', U'abq', FALSE},
            {0017, U'ab{1,}bc', U'abq', FALSE},
            {0018, U'ab+bc', U'abbbbc', TRUE},
            {0019, U'ab{1,}bc', U'abbbbc', TRUE},
            {0020, U'ab{1,3}bc', U'abbbbc', TRUE},
            {0021, U'ab{3,4}bc', U'abbbbc', TRUE},
            {0022, U'ab{4,5}bc', U'abbbbc', FALSE},
            {0023, U'ab?bc', U'abbc', TRUE},
            {0024, U'ab?bc', U'abc', TRUE},
            {0025, U'ab{0,1}bc', U'abc', TRUE},
            {0026, U'ab?bc', U'abbbbc', FALSE},
            {0027, U'ab?c', U'abc', TRUE},
            {0028, U'ab{0,1}c', U'abc', TRUE},
            {0029, U'^abc$', U'abc', TRUE},
            {0030, U'^abc$', U'abcc', FALSE},
            {0031, U'^abc', U'abcc', TRUE},
            {0032, U'^abc$', U'aabc', FALSE},
            {0033, U'abc$', U'aabc', TRUE},
            {0034, U'abc$', U'aabcd', FALSE},
            {0035, U'^', U'abc', TRUE},
            {0036, U'$', U'abc', TRUE},
            {0037, U'a.c', U'abc', TRUE},
            {0038, U'a.c', U'axc', TRUE},
            {0039, U'a\nc', U'abc', FALSE},
            {0040, U'a.*c', U'axyzc', TRUE},
            {0041, U'a\n*c', U'axyzc', FALSE},
            {0042, U'a.*c', U'axyzd', FALSE},
            {0043, U'a\n*c', U'axyzd', FALSE},
            {0044, U'a[bc]d', U'abc', FALSE},
            {0045, U'a[bc]d', U'abd', TRUE},
            {0046, U'a[b]d', U'abd', TRUE},
            {0047, U'[a][b][d]', U'abd', TRUE},
            {0048, U'.[b].', U'abd', TRUE},
            {0049, U'.[b].', U'aBd', FALSE},
            {0050, U'(?i:.[b].)', U'abd', TRUE},
            {0051, U'(?i:\n[b]\n)', U'abd', FALSE},
            {0052, U'a[b-d]e', U'abd', FALSE},
            {0053, U'a[b-d]e', U'ace', TRUE},
            {0054, U'a[b-d]', U'aac', TRUE},
            {0055, U'a[-b]', U'a-', TRUE},
            {0056, U'a[b-]', U'a-', TRUE},
            {0057, U'a]', U'a]', TRUE},
            {0058, U'a[]]b', U'a]b', TRUE},
            {0059, U'a[^bc]d', U'aed', TRUE},
            {0060, U'a[^bc]d', U'abd', FALSE},
            {0061, U'a[^-b]c', U'adc', TRUE},
            {0062, U'a[^-b]c', U'a-c', FALSE},
            {0063, U'a[^]b]c', U'a]c', FALSE},
            {0064, U'a[^]b]c', U'adc', TRUE},
            {0065, U'\\ba\\b', U'a-', TRUE},
            {0066, U'\\ba\\b', U'-a', TRUE},
            {0067, U'\\ba\\b', U'-a-', TRUE},
            {0068, U'\\by\\b', U'xy', FALSE},
            {0069, U'\\by\\b', U'yz', FALSE},
            {0070, U'\\by\\b', U'xyz', FALSE},
            {0071, U'\\Ba\\B', U'a-', FALSE},
            {0072, U'\\Ba\\B', U'-a', FALSE},
            {0073, U'\\Ba\\B', U'-a-', FALSE},
            {0074, U'\\By\\b', U'xy', TRUE},
            {0075, U'\\by\\B', U'yz', TRUE},
            {0076, U'\\By\\B', U'xyz', TRUE},
            {0077, U'\\w', U'a', TRUE},
            {0078, U'\\w', U'-', FALSE},
            {0079, U'\\W', U'a', FALSE},
            {0080, U'\\W', U'-', TRUE},
            {0081, U'a\\sb', U'a b', TRUE},
            {0082, U'a\\sb', U'a-b', FALSE},
            {0083, U'a\\Sb', U'a b', FALSE},
            {0084, U'a\\Sb', U'a-b', TRUE},
            {0085, U'\\d', U'1', TRUE},
            {0086, U'\\d', U'-', FALSE},
            {0087, U'\\D', U'1', FALSE},
            {0088, U'\\D', U'-', TRUE},
            {0089, U'[\\w]', U'a', TRUE},
            {0090, U'[\\w]', U'-', FALSE},
            {0091, U'[\\W]', U'a', FALSE},
            {0092, U'[\\W]', U'-', TRUE},
            {0093, U'a[\\s]b', U'a b', TRUE},
            {0094, U'a[\\s]b', U'a-b', FALSE},
            {0095, U'a[\\S]b', U'a b', FALSE},
            {0096, U'a[\\S]b', U'a-b', TRUE},
            {0097, U'[\\d]', U'1', TRUE},
            {0098, U'[\\d]', U'-', FALSE},
            {0099, U'[\\D]', U'1', FALSE},
            {0100, U'[\\D]', U'-', TRUE},
            {0101, U'ab|cd', U'abc', TRUE},
            {0102, U'ab|cd', U'abcd', TRUE},
            {0103, U'()ef', U'def', TRUE},
            {0104, U'$b', U'b', FALSE},
            {0105, U'a\\(b', U'a(b', TRUE},
            {0106, U'a\\(*b', U'ab', TRUE},
            {0107, U'a\\(*b', U'a((b', TRUE},
            {0109, U'((a))', U'abc', TRUE},
            {0110, U'(a)b(c)', U'abc', TRUE},
            {0111, U'a+b+c', U'aabbabc', TRUE},
            {0112, U'a{1,}b{1,}c', U'aabbabc', TRUE},
            {0113, U'a.+?c', U'abcabc', TRUE},
            {0114, U'(a+|b)*', U'ab', TRUE},
            {0115, U'(a+|b){0,}', U'ab', TRUE},
            {0116, U'(a+|b)+', U'ab', TRUE},
            {0117, U'(a+|b){1,}', U'ab', TRUE},
            {0118, U'(a+|b)?', U'ab', TRUE},
            {0119, U'(a+|b){0,1}', U'ab', TRUE},
            {0120, U'[^ab]*', U'cde', TRUE},
            {0121, U'([abc])*d', U'abbbcd', TRUE},
            {0122, U'([abc])*bcd', U'abcd', TRUE},
            {0123, U'a|b|c|d|e', U'e', TRUE},
            {0124, U'(a|b|c|d|e)f', U'ef', TRUE},
            {0125, U'abcd*efg', U'abcdefg', TRUE},
            {0126, U'ab*', U'xabyabbbz', TRUE},
            {0127, U'ab*', U'xayabbbz', TRUE},
            {0128, U'(ab|cd)e', U'abcde', TRUE},
            {0129, U'[abhgefdc]ij', U'hij', TRUE},
            {0130, U'^(ab|cd)e', U'abcde', FALSE},
            {0131, U'(abc|)ef', U'abcdef', TRUE},
            {0132, U'(a|b)c*d', U'abcd', TRUE},
            {0133, U'(ab|ab*)bc', U'abc', TRUE},
            {0134, U'a([bc]*)c*', U'abc', TRUE},
            {0135, U'a([bc]*)(c*d)', U'abcd', TRUE},
            {0136, U'a([bc]+)(c*d)', U'abcd', TRUE},
            {0137, U'a([bc]*)(c+d)', U'abcd', TRUE},
            {0138, U'a[bcd]*dcdcde', U'adcdcde', TRUE},
            {0139, U'a[bcd]+dcdcde', U'adcdcde', FALSE},
            {0140, U'(ab|a)b*c', U'abc', TRUE},
            {0141, U'((a)(b)c)(d)', U'abcd', TRUE},
            {0142, U'[a-zA-Z_][a-zA-Z0-9_]*', U'alpha', TRUE},
            {0143, U'[_A-Z]', U'}', FALSE},
            {0144, U'^a(bc+|b[eh])g|.h$', U'abh', TRUE},
            {0145, U'(bc+d$|ef*g.|h?i(j|k))', U'effgz', TRUE},
            {0146, U'(bc+d$|ef*g.|h?i(j|k))', U'ij', TRUE},
            {0147, U'(bc+d$|ef*g.|h?i(j|k))', U'effg', FALSE},
            {0148, U'(bc+d$|ef*g.|h?i(j|k))', U'bcdd', FALSE},
            {0149, U'(bc+d$|ef*g.|h?i(j|k))', U'reffgz', TRUE},
            {0150, U'((((((((((a))))))))))', U'a', TRUE},
            {0151, U'((((((((((a))))))))))\\10', U'aa', TRUE},
            {0154, U'(((((((((a)))))))))', U'a', TRUE},
            {0155, U'[89]+', U'1((((((7(9))))))', TRUE},
            {0156, U'multiple words of text', U'uh-uh', FALSE},
            {0157, U'multiple words', U'multiple words, yeah', TRUE},
            {0158, U'(.*)c(.*)', U'abcde', TRUE},
            {0159, U'\\((.*), (.*)\\)', U'(a, b)', TRUE},
            {0160, U'[k]', U'ab', FALSE},
            {0161, U'abcd', U'abcd', TRUE},
            {0162, U'a(bc)d', U'abcd', TRUE},
            {0163, U'a[-]?c', U'ac', TRUE},
            {0164, U'(abc)\\1', U'abcabc', TRUE},
            {0165, U'([a-c]*)\\1', U'abcabc', TRUE},
            {0166, U'(a)|\\1', U'a', TRUE},
            {0167, U'(a)|\\1', U'x', FALSE},
            {0168, U'(?:(b)?a)\\1', U'a', FALSE},
            {0169, U'(([a-c])b*?\\2)*', U'ababbbcbc', TRUE},
            {0170, U'(([a-c])b*?\\2){3}', U'ababbbcbc', TRUE},
            {0171, U'((\\3|b)\\2(a)x)+', U'aaxabxbaxbbx', FALSE},
            {0172, U'((\\3|b)\\2(a)x)+', U'aaaxabaxbaaxbbax', TRUE},
            {0173, U'((\\3|b)\\2(a)){2,}', U'bbaababbabaaaaabbaaaabba', TRUE},
            {0174, U'^((.)?a\\2)+$', U'babadad', FALSE},
            {0175, U'(a)|(b)', U'b', TRUE},
            {0176, U'a(?!b).', U'abad', TRUE},
            {0177, U'a(?=d).', U'abad', TRUE},
            {0178, U'a(?=c|d).', U'abad', TRUE},
            {0179, U'a(?:b|c|d)(.)', U'ace', TRUE},
            {0180, U'a(?:b|c|d)*(.)', U'ace', TRUE},
            {0181, U'a(?:b|c|d)+?(.)', U'ace', TRUE},
            {0182, U'a(?:b|c|d)+?(.)', U'acdbcdbe', TRUE},
            {0183, U'a(?:b|c|d)+(.)', U'acdbcdbe', TRUE},
            {0184, U'a(?:b|c|d){2}(.)', U'acdbcdbe', TRUE},
            {0185, U'a(?:b|c|d){4,5}(.)', U'acdbcdbe', TRUE},
            {0186, U'a(?:b|c|d){4,5}?(.)', U'acdbcdbe', TRUE},
            {0187, U'((foo)|(bar))*', U'foobar', TRUE},
            {0188, U'a(?:b|c|d){6,7}(.)', U'acdbcdbe', TRUE},
            {0189, U'a(?:b|c|d){6,7}?(.)', U'acdbcdbe', TRUE},
            {0190, U'a(?:b|c|d){5,6}(.)', U'acdbcdbe', TRUE},
            {0191, U'a(?:b|c|d){5,6}?(.)', U'acdbcdbe', TRUE},
            {0192, U'a(?:b|c|d){5,7}(.)', U'acdbcdbe', TRUE},
            {0193, U'a(?:b|c|d){5,7}?(.)', U'acdbcdbe', TRUE},
            {0194, U'a(?:b|(c|e){1,2}?|d)+?(.)', U'ace', TRUE},
            {0195, U'^(.+)?B', U'AB', TRUE},
            {0196, U'^([^a-z])|(\\^)$', U'.', TRUE},
            {0197, U'^[<>]&', U'<&OUT', TRUE},
            {0198, U'^(a\\1?){4}$', U'aaaaaaaaaa', TRUE},
            {0199, U'^(a\\1?){4}$', U'aaaaaaaaa', FALSE},
            {0200, U'^(a\\1?){4}$', U'aaaaaaaaaaa', FALSE},
            {0201, U'^(a(?(1)\\1)){4}$', U'aaaaaaaaaa', TRUE},
            {0202, U'^(a(?(1)\\1)){4}$', U'aaaaaaaaa', FALSE},
            {0203, U'^(a(?(1)\\1)){4}$', U'aaaaaaaaaaa', FALSE},
            {0204, U'((?(1)a|b))+', U'baaa', TRUE},
            {0205, U'((?(1)aa|b))+', U'baaaa', TRUE},
            {0206, U'((a{4})+)', U'aaaaaaaaa', TRUE},
            {0207, U'(((aa){2})+)', U'aaaaaaaaaa', TRUE},
            {0208, U'(((a{2}){2})+)', U'aaaaaaaaaa', TRUE},
            {0209, U'(?:(f)(o)(o)|(b)(a)(r))*', U'foobar', TRUE},
            {0210, U'(?<=a)b', U'ab', TRUE},
            {0211, U'(?<=a)b', U'cb', FALSE},
            {0212, U'(?<=a)b', U'b', FALSE},
            {0213, U'(?<!c)b', U'ab', TRUE},
            {0214, U'(?<!c)b', U'cb', FALSE},
            {0215, U'(?<!c)b', U'b', TRUE},
            {0216, U'(?:..)*a', U'aba', TRUE},
            {0217, U'(?:..)*?a', U'aba', TRUE},
            {0218, U'^(?:b|a(?=(.)))*\\1', U'abc', TRUE},
            {0219, U'^(){3,5}', U'abc', TRUE},
            {0220, U'^(a+)*ax', U'aax', TRUE},
            {0221, U'^((a|b)+)*ax', U'aax', TRUE},
            {0222, U'^((a|bc)+)*ax', U'aax', TRUE},
            {0223, U'(a|x)*ab', U'cab', TRUE},
            {0224, U'(a)*ab', U'cab', TRUE},
            {0225, U'(?:(?i)a)b', U'ab', TRUE},
            {0226, U'((?i)a)b', U'ab', TRUE},
            {0227, U'(?:(?i)a)b', U'aB', FALSE},
            {0228, U'((?i)a)b', U'aB', FALSE},
            {0229, U'(?i:a)b', U'ab', TRUE},
            {0230, U'((?i:a))b', U'ab', TRUE},
            {0231, U'(?i:a)b', U'aB', FALSE},
            {0232, U'((?i:a))b', U'aB', FALSE},
            {0233, U'(?:c|d)(?:)(?:a(?:)(?:b)(?:b(?:))(?:b(?:)(?:b)))', U'cabbbb', TRUE},
            {0234, U'(?:c|d)(?:)(?:aaaaaaaa(?:)(?:bbbbbbbb)(?:bbbbbbbb(?:))(?:bbbbbbbb(?:)(?:bbbbbbbb)))', U'caaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', TRUE},
            {0235, U'foo\\w*\\d{4}baz', U'foobar1234baz', TRUE},
            {0236, U'x(~~)*(?:(?:F)?)?', U'x~~', TRUE},
            {0237, U'^a(?#xxx){3}c', U'aaac', TRUE},
            {0239, U'(?<![cd])b', U'dbcb', FALSE},
            {0240, U'(?<![cd])[ab]', U'dbaacb', TRUE},
            {0241, U'(?<!(c|d))b', U'dbcb', FALSE},
            {0242, U'(?<!(c|d))[ab]', U'dbaacb', TRUE},
            {0243, U'(?<!cd)[ab]', U'cdaccb', TRUE},
            {0244, U'^(?:a?b?)*$', U'a--', FALSE},
            {0245, U'((?s)^a(.))((?m)^b$)', U'a\nb\nc\n', TRUE},
            {0246, U'((?m)^b$)', U'a\nb\nc\n', TRUE},
            {0247, U'(?m)^b', U'a\nb\n', TRUE},
            {0248, U'(?m)^(b)', U'a\nb\n', TRUE},
            {0249, U'((?m)^b)', U'a\nb\n', TRUE},
            {0250, U'\n((?m)^b)', U'a\nb\n', TRUE},
            {0251, U'((?s).)c(?!.)', U'a\nb\nc\n', TRUE},
            {0252, U'((?s)b.)c(?!.)', U'a\nb\nc\n', TRUE},
            {0253, U'((?s)b.)c(?!\n)', U'a\nb\nc\n', TRUE},
            {0255, U'^b', U'a\nb\nc\n', FALSE},
            {0256, U'()^b', U'a\nb\nc\n', FALSE},
            {0257, U'((?m)^b)', U'a\nb\nc\n', TRUE},
            {0258, U'(x)?(?(1)a|b)', U'a', FALSE},
            {0259, U'(x)?(?(1)b|a)', U'a', TRUE},
            {0260, U'()?(?(1)b|a)', U'a', TRUE},
            {0261, U'()(?(1)b|a)', U'a', FALSE},
            {0262, U'()?(?(1)a|b)', U'a', TRUE},
            {0263, U'^(\\()?blah(?(1)(\\)))$', U'(blah)', TRUE},
            {0264, U'^(\\()?blah(?(1)(\\)))$', U'blah', TRUE},
            {0265, U'^(\\()?blah(?(1)(\\)))$', U'blah)', FALSE},
            {0266, U'^(\\()?blah(?(1)(\\)))$', U'(blah', FALSE},
            {0267, U'^(\\(+)?blah(?(1)(\\)))$', U'(blah)', TRUE},
            {0268, U'^(\\(+)?blah(?(1)(\\)))$', U'blah', TRUE},
            {0269, U'^(\\(+)?blah(?(1)(\\)))$', U'blah)', FALSE},
            {0270, U'^(\\(+)?blah(?(1)(\\)))$', U'(blah', FALSE},
            {0271, U'(?(?!a)a|b)', U'a', FALSE},
            {0272, U'(?(?!a)b|a)', U'a', TRUE},
            {0273, U'(?(?=a)b|a)', U'a', FALSE},
            {0274, U'(?(?=a)a|b)', U'a', TRUE},
            {0275, U'(?=(a+?))(\\1ab)', U'aaab', TRUE},
            {0276, U'^(?=(a+?))\\1ab', U'aaab', FALSE},
            {0277, U'(\\w+:)+', U'one:', TRUE},
            {0278, U'$(?<=^(a))', U'a', TRUE},
            {0279, U'([\\w:]+::)?(\\w+)$', U'abcd:', FALSE},
            {0280, U'([\\w:]+::)?(\\w+)$', U'abcd', TRUE},
            {0281, U'([\\w:]+::)?(\\w+)$', U'xy:z:::abcd', TRUE},
            {0282, U'^[^bcd]*(c+)', U'aexycd', TRUE},
            {0283, U'(a*)b+', U'caab', TRUE},
            {0284, U'(>a+)ab', U'aaab', FALSE},
            {0285, U'(?>a+)b', U'aaab', TRUE},
            {0286, U'([[:alpha:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0287, U'([[:alnum:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0288, U'([[:cntrl:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0289, U'([[:digit:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0290, U'([[:graph:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0291, U'([[:lower:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0292, U'([[:print:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0293, U'([[:punct:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0294, U'([[:space:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0295, U'([[:word:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0296, U'([[:upper:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0297, U'([[:xdigit:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0298, U'([[:^alpha:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0299, U'([[:^cntrl:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0300, U'([[:^digit:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0301, U'([[:^lower:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0302, U'([[:^punct:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0303, U'([[:^space:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0304, U'([[:^upper:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0305, U'([[:^xdigit:]]+)', U'ABcd01Xy__--  ${nulnul}${ffff}', TRUE},
            {0307, U'((?>a+)b)', U'aaab', TRUE},
            {0308, U'(?>(a+))b', U'aaab', TRUE},
            {0309, U'((?>[^()]+)|\\([^()]*\\))+', U'((abc(ade)ufh()()x', TRUE},
            {0310, U'\\z', U'a\nb\n', TRUE},
            {0311, U'$', U'a\nb\n', TRUE},
            {0312, U'\\z', U'b\na\n', TRUE},
            {0313, U'$', U'b\na\n', TRUE},
            {0314, U'\\z', U'b\na', TRUE},
            {0315, U'$', U'b\na', TRUE},
            {0322, U'a\\z', U'a\nb\n', FALSE},
            {0323, U'a$', U'a\nb\n', FALSE},
            {0324, U'a\\Z', U'b\na\n', TRUE},
            {0325, U'a\\z', U'b\na\n', FALSE},
            {0326, U'a$', U'b\na\n', TRUE},
            {0327, U'a\\z', U'b\na', TRUE},
            {0328, U'a$', U'b\na', TRUE},
            {0336, U'aa\\z', U'aa\nb\n', FALSE},
            {0337, U'aa$', U'aa\nb\n', FALSE},
            {0338, U'aa\\Z', U'b\naa\n', TRUE},
            {0339, U'aa\\z', U'b\naa\n', FALSE},
            {0340, U'aa$', U'b\naa\n', TRUE},
            {0341, U'aa\\z', U'b\naa', TRUE},
            {0342, U'aa$', U'b\naa', TRUE},
            {0350, U'aa\\z', U'ac\nb\n', FALSE},
            {0351, U'aa$', U'ac\nb\n', FALSE},
            {0352, U'aa\\z', U'b\nac\n', FALSE},
            {0353, U'aa$', U'b\nac\n', FALSE},
            {0354, U'aa\\z', U'b\nac', FALSE},
            {0355, U'aa$', U'b\nac', FALSE},
            {0362, U'aa\\z', U'ca\nb\n', FALSE},
            {0363, U'aa$', U'ca\nb\n', FALSE},
            {0364, U'aa\\z', U'b\nca\n', FALSE},
            {0365, U'aa$', U'b\nca\n', FALSE},
            {0366, U'aa\\z', U'b\nca', FALSE},
            {0367, U'aa$', U'b\nca', FALSE},
            {0374, U'ab\\z', U'ab\nb\n', FALSE},
            {0375, U'ab$', U'ab\nb\n', FALSE},
            {0376, U'ab\\Z', U'b\nab\n', TRUE},
            {0377, U'ab\\z', U'b\nab\n', FALSE},
            {0378, U'ab$', U'b\nab\n', TRUE},
            {0379, U'ab\\z', U'b\nab', TRUE},
            {0380, U'ab$', U'b\nab', TRUE},
            {0388, U'ab\\z', U'ac\nb\n', FALSE},
            {0389, U'ab$', U'ac\nb\n', FALSE},
            {0390, U'ab\\z', U'b\nac\n', FALSE},
            {0391, U'ab$', U'b\nac\n', FALSE},
            {0392, U'ab\\z', U'b\nac', FALSE},
            {0393, U'ab$', U'b\nac', FALSE},
            {0400, U'ab\\z', U'ca\nb\n', FALSE},
            {0401, U'ab$', U'ca\nb\n', FALSE},
            {0402, U'ab\\z', U'b\nca\n', FALSE},
            {0403, U'ab$', U'b\nca\n', FALSE},
            {0404, U'ab\\z', U'b\nca', FALSE},
            {0405, U'ab$', U'b\nca', FALSE},
            {0412, U'abb\\z', U'abb\nb\n', FALSE},
            {0413, U'abb$', U'abb\nb\n', FALSE},
            {0414, U'abb\\Z', U'b\nabb\n', TRUE},
            {0415, U'abb\\z', U'b\nabb\n', FALSE},
            {0416, U'abb$', U'b\nabb\n', TRUE},
            {0417, U'abb\\z', U'b\nabb', TRUE},
            {0418, U'abb$', U'b\nabb', TRUE},
            {0426, U'abb\\z', U'ac\nb\n', FALSE},
            {0427, U'abb$', U'ac\nb\n', FALSE},
            {0428, U'abb\\z', U'b\nac\n', FALSE},
            {0429, U'abb$', U'b\nac\n', FALSE},
            {0430, U'abb\\z', U'b\nac', FALSE},
            {0431, U'abb$', U'b\nac', FALSE},
            {0438, U'abb\\z', U'ca\nb\n', FALSE},
            {0439, U'abb$', U'ca\nb\n', FALSE},
            {0440, U'abb\\z', U'b\nca\n', FALSE},
            {0441, U'abb$', U'b\nca\n', FALSE},
            {0442, U'abb\\z', U'b\nca', FALSE},
            {0443, U'abb$', U'b\nca', FALSE},
            {0451, U'(^|x)(c)', U'ca', TRUE},
            {0452, U'a*abc?xyz+pqr{3}ab{2,}xy{4,5}pq{0,6}AB{0,}zz', U'x', FALSE},
            {0453, U'round\\(((?>[^()]+))\\)', U'_I(round(xs * sz),1)', TRUE},
            {0456, U'foo.bart', U'foo.bart', TRUE},
            {0458, U'tt+$', U'xxxtt', TRUE},
            {0459, U'\\GX.*X', U'aaaXbX', FALSE},
            {0460, U'(\\d+\\.\\d+)', U'3.1415926', TRUE},
            {0461, U'(\\ba.{0,10}br)', U'have a web browser', TRUE},
            {0462, U'^([a-z]:)', U'C:/', FALSE},
            {0464, U'(^|a)b', U'ab', TRUE},
            {0465, U'^([ab]*?)(b)?(c)$', U'abac', TRUE},
            {0466, U'(\\w)?(abc)\\1b', U'abcab', FALSE},
            {0467, U'^(?:.,){2}c', U'a,b,c', TRUE},
            {0468, U'^(.,){2}c', U'a,b,c', TRUE},
            {0469, U'^(?:[^,]*,){2}c', U'a,b,c', TRUE},
            {0470, U'^([^,]*,){2}c', U'a,b,c', TRUE},
            {0471, U'^([^,]*,){3}d', U'aaa,b,c,d', TRUE},
            {0472, U'^([^,]*,){3,}d', U'aaa,b,c,d', TRUE},
            {0473, U'^([^,]*,){0,3}d', U'aaa,b,c,d', TRUE},
            {0474, U'^([^,]{1,3},){3}d', U'aaa,b,c,d', TRUE},
            {0475, U'^([^,]{1,3},){3,}d', U'aaa,b,c,d', TRUE},
            {0476, U'^([^,]{1,3},){0,3}d', U'aaa,b,c,d', TRUE},
            {0477, U'^([^,]{1,},){3}d', U'aaa,b,c,d', TRUE},
            {0478, U'^([^,]{1,},){3,}d', U'aaa,b,c,d', TRUE},
            {0479, U'^([^,]{1,},){0,3}d', U'aaa,b,c,d', TRUE},
            {0480, U'^([^,]{0,3},){3}d', U'aaa,b,c,d', TRUE},
            {0481, U'^([^,]{0,3},){3,}d', U'aaa,b,c,d', TRUE},
            {0482, U'^([^,]{0,3},){0,3}d', U'aaa,b,c,d', TRUE},
            {0484, U'^(a(b)?)+$', U'aba', TRUE},
            {0485, U'^(aa(bb)?)+$', U'aabbaa', TRUE},
            {0487, U'^(a)?a$', U'a', TRUE},
            {0488, U'^(a)?(?(1)a|b)+$', U'a', FALSE},
            {0489, U'^(a\\1?)(a\\1?)(a\\2?)(a\\3?)$', U'aaaaaa', TRUE},
            {0490, U'^(a\\1?){4}$', U'aaaaaa', TRUE},
            {0491, U'^(0+)?(?:x(1))?', U'x1', TRUE},
            {0492, U'^([0-9a-fA-F]+)(?:x([0-9a-fA-F]+)?)(?:x([0-9a-fA-F]+))?', U'012cxx0190', TRUE},
            {0493, U'^(b+?|a){1,2}c', U'bbbac', TRUE},
            {0494, U'^(b+?|a){1,2}c', U'bbbbac', TRUE},
            {0495, U'\\((\\w\\. \\w+)\\)', U'cd. (A. Tw)', TRUE},
            {0496, U'((?:aaaa|bbbb)cccc)?', U'aaaacccc', TRUE},
            {0497, U'((?:aaaa|bbbb)cccc)?', U'bbbbcccc', TRUE},
            {0498, U'(a)?(a)+', U'a', TRUE},
            {0499, U'(ab)?(ab)+', U'ab', TRUE},
            {0500, U'(abc)?(abc)+', U'abc', TRUE},
            {0502, U'\\ba', U'a', TRUE},
            {0503, U'ab(?i)cd', U'AbCd', FALSE},
            {0504, U'ab(?i)cd', U'abCd', TRUE},
            {0505, U'(A|B)*(?(1)(CD)|(CD))', U'CD', TRUE},
            {0506, U'(A|B)*(?(1)(CD)|(CD))', U'ABCD', TRUE},
            {0507, U'(A|B)*?(?(1)(CD)|(CD))', U'CD', TRUE},
            {0508, U'(A|B)*?(?(1)(CD)|(CD))', U'ABCD', TRUE},
            {0509, U'(.*)\\d+\\1', U'abc12bc', TRUE},
            {0510, U'(?m:(foo\\s*$))', U'foo\n bar', TRUE},
            {0511, U'(.*)c', U'abcd', TRUE},
            {0512, U'(.*)(?=c)', U'abcd', TRUE},
            {0513, U'(.*)(?=c)c', U'abcd', TRUE},
            {0514, U'(.*)(?=b|c)', U'abcd', TRUE},
            {0515, U'(.*)(?=b|c)c', U'abcd', TRUE},
            {0516, U'(.*)(?=c|b)', U'abcd', TRUE},
            {0517, U'(.*)(?=c|b)c', U'abcd', TRUE},
            {0518, U'(.*)(?=[bc])', U'abcd', TRUE},
            {0519, U'(.*)(?=[bc])c', U'abcd', TRUE},
            {0520, U'(.*)(?<=b)', U'abcd', TRUE},
            {0521, U'(.*)(?<=b)c', U'abcd', TRUE},
            {0522, U'(.*)(?<=b|c)', U'abcd', TRUE},
            {0523, U'(.*)(?<=b|c)c', U'abcd', TRUE},
            {0524, U'(.*)(?<=c|b)', U'abcd', TRUE},
            {0525, U'(.*)(?<=c|b)c', U'abcd', TRUE},
            {0526, U'(.*)(?<=[bc])', U'abcd', TRUE},
            {0527, U'(.*)(?<=[bc])c', U'abcd', TRUE},
            {0528, U'(.*?)c', U'abcd', TRUE},
            {0529, U'(.*?)(?=c)', U'abcd', TRUE},
            {0530, U'(.*?)(?=c)c', U'abcd', TRUE},
            {0531, U'(.*?)(?=b|c)', U'abcd', TRUE},
            {0532, U'(.*?)(?=b|c)c', U'abcd', TRUE},
            {0533, U'(.*?)(?=c|b)', U'abcd', TRUE},
            {0534, U'(.*?)(?=c|b)c', U'abcd', TRUE},
            {0535, U'(.*?)(?=[bc])', U'abcd', TRUE},
            {0536, U'(.*?)(?=[bc])c', U'abcd', TRUE},
            {0537, U'(.*?)(?<=b)', U'abcd', TRUE},
            {0538, U'(.*?)(?<=b)c', U'abcd', TRUE},
            {0539, U'(.*?)(?<=b|c)', U'abcd', TRUE},
            {0540, U'(.*?)(?<=b|c)c', U'abcd', TRUE},
            {0541, U'(.*?)(?<=c|b)', U'abcd', TRUE},
            {0542, U'(.*?)(?<=c|b)c', U'abcd', TRUE},
            {0543, U'(.*?)(?<=[bc])', U'abcd', TRUE},
            {0544, U'(.*?)(?<=[bc])c', U'abcd', TRUE},
            {0545, U'2(]*)?$\\1', U'2', TRUE},
            {0546, U'a(b)??', U'abc', TRUE},
            {0547, U'(\\d{1,3}\\.){3,}', U'128.134.142.8', TRUE},
            {0548, U'^.{3,4}(.+)\\1\\z', U'foobarbar', TRUE},
            {0549, U'^(?:f|o|b){3,4}(.+)\\1\\z', U'foobarbar', TRUE},
            {0550, U'^.{3,4}((?:b|a|r)+)\\1\\z', U'foobarbar', TRUE},
            {0551, U'^(?:f|o|b){3,4}((?:b|a|r)+)\\1\\z', U'foobarbar', TRUE},
            {0552, U'^.{3,4}(.+?)\\1\\z', U'foobarbar', TRUE},
            {0553, U'^(?:f|o|b){3,4}(.+?)\\1\\z', U'foobarbar', TRUE},
            {0554, U'^.{3,4}((?:b|a|r)+?)\\1\\z', U'foobarbar', TRUE},
            {0555, U'^(?:f|o|b){3,4}((?:b|a|r)+?)\\1\\z', U'foobarbar', TRUE},
            {0556, U'^.{2,3}?(.+)\\1\\z', U'foobarbar', TRUE},
            {0557, U'^(?:f|o|b){2,3}?(.+)\\1\\z', U'foobarbar', TRUE},
            {0558, U'^.{2,3}?((?:b|a|r)+)\\1\\z', U'foobarbar', TRUE},
            {0559, U'^(?:f|o|b){2,3}?((?:b|a|r)+)\\1\\z', U'foobarbar', TRUE},
            {0560, U'^.{2,3}?(.+?)\\1\\z', U'foobarbar', TRUE},
            {0561, U'^(?:f|o|b){2,3}?(.+?)\\1\\z', U'foobarbar', TRUE},
            {0562, U'^.{2,3}?((?:b|a|r)+?)\\1\\z', U'foobarbar', TRUE},
            {0563, U'^(?:f|o|b){2,3}?((?:b|a|r)+?)\\1\\z', U'foobarbar', TRUE},
            {0564, U'.*a(?!(b|cd)*e).*f', U'......abef', FALSE},
            {0565, U'(WORDS|WORD)S', U'WORDS', TRUE},
            {0566, U'(X.|WORDS|X.|WORD)S', U'WORDS', TRUE},
            {0567, U'(WORDS|WORLD|WORD)S', U'WORDS', TRUE},
            {0568, U'(X.|WORDS|WORD|Y.)S', U'WORDS', TRUE},
            {0569, U'(foo|fool|x.|money|parted)$', U'fool', TRUE},
            {0570, U'(x.|foo|fool|x.|money|parted|y.)$', U'fool', TRUE},
            {0571, U'(foo|fool|money|parted)$', U'fool', TRUE},
            {0572, U'(foo|fool|x.|money|parted)$', U'fools', FALSE},
            {0573, U'(x.|foo|fool|x.|money|parted|y.)$', U'fools', FALSE},
            {0574, U'(foo|fool|money|parted)$', U'fools', FALSE},
            {0575, U'(a|aa|aaa||aaaa|aaaaa|aaaaaa)(b|c)', U'aaaaaaaaaaaaaaab', TRUE},
            {0576, U'^(a*?)(?!(aa|aaaa)*$)', U'aaaaaaaaaaaaaaaaaaaa', TRUE},
            {0577, U'^(a*?)(?!(aa|aaaa)*$)(?=a\\z)', U'aaaaaaaa', TRUE},
            {0578, U'^(.)\\s+.$(?(1))', U'A B', TRUE},
            {0579, U'(?:r?)*?r|(.{2,4})', U'abcde', TRUE},
            {0580, U'(?!)+?|(.{2,4})', U'abcde', TRUE},
            {0581, U'^(a*?)(?!(a{6}|a{5})*$)', U'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', TRUE},
            {0582, U'^((?>(?:aa)?b)?)', U'aab', TRUE},
            {0583, U'^((?:aa)*)(?:X+((?:\\d+|-)(?:X+(.+))?))?$', U'aaaaX5', TRUE},
            {0584, U'X(A|B||C|D)Y', U'XXXYYY', TRUE},
            {0585, U'(?i:X([A]|[B]|y[Y]y|[D]|)Y)', U'XXXYYYB', TRUE},
            {0586, U'^([a]{1})*$', U'aa', TRUE},
            {0587, U'a(?!b(?!c))(..)', U'abababc', TRUE},
            {0588, U'a(?!b(?=a))(..)', U'abababc', TRUE},
            {0589, U'a(?!b(?!c(?!d(?!e))))...(.)', U'abxabcdxabcde', TRUE},
            {0590, U'X(?!b+(?!(c+)*(?!(c+)*d))).*X', U'aXbbbbbbbcccccccccccccaaaX', TRUE},
            {0591, U'^(XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0592, U'^(XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQX:', TRUE},
            {0593, U'^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0594, U'^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQX:', TRUE},
            {0595, U'^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', U'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0596, U'^([TUV]+|XXXXXXXXXX|YYYYYYYYYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', U'ZEQQQX:', TRUE},
            {0597, U'^(XXX|YYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0598, U'^(XXX|YYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQX:', TRUE},
            {0599, U'^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0600, U'^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P):', U'ZEQQQX:', TRUE},
            {0601, U'^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', U'ZEQQQQQQQQQQQQQQQQQQP:', TRUE},
            {0602, U'^([TUV]+|XXX|YYY|Z.Q*X|Z[TE]Q*P|[MKJ]):', U'ZEQQQX:', TRUE},
            {0603, U'X(?:ABCF[cC]x*|ABCD|ABCF):(?:DIT|DID|DIM)', U'XABCFCxxxxxxxxxx:DIM', TRUE},
            {0604, U'(((ABCD|ABCE|ABCF)))(A|B|C[xy]*):', U'ABCFCxxxxxxxxxx:DIM', TRUE},
            {0605, U'(?=foo)', U'foo', TRUE},
            {0606, U'(?=foo)', U'XfooY', TRUE},
            {0607, U'.*(?=foo)', U'XfooY', TRUE},
            {0608, U'(?=.*P)P', U'aP', TRUE},
            {0609, U'(?<=foo)', U'foo', TRUE},
            {0610, U'(?<=foo)', U'XfooY', TRUE},
            {0611, U'.*(?<=foo)', U'foo', TRUE},
            {0612, U'.*(?<=foo)', U'XfooY', TRUE},
            {0613, U'(?<=foo)Y', U'XfooY', TRUE},
            {0614, U'o(?<=foo)Y', U'..XfooY..', TRUE},
            {0615, U'X(?=foo)f', U'..XfooY..', TRUE},
            {0616, U'X(?=foo)', U'..XfooY..', TRUE},
            {0617, U'X(?<=foo.)[YZ]', U'..XfooXY..', TRUE},
            {0618, U'(?=XY*foo)', U'Xfoo', TRUE},
            {0619, U'^(?=XY*foo)', U'Xfoo', TRUE},
            {0620, U'^(<(?:[^<>]+|(?3)|(?1))*>)()(!>!>!>)$', U'<<!>!>!>><>>!>!>!>', TRUE},
            {0621, U'^(<(?:[^<>]+|(?1))*>)$', U'<<><<<><>>>>', TRUE},
            {0622, U'((?2)*)([fF]o+)', U'fooFoFoo', TRUE},
            {0623, U'(<(?:[^<>]+|(?R))*>)', U'<<><<<><>>>>', TRUE},
            {0624, U'(?<n>foo|bar|baz)', U'snofooewa', TRUE},
            {0625, U'(?<n>foo|bar|baz)(?<m>[ew]+)', U'snofooewa', TRUE},
            {0626, U'(?<A>foo)?(?(<A>)bar|nada)', U'foobar', TRUE},
            {0627, U'(?<A>foo)?(?(<A>)bar|nada)', U'foo-barnada', TRUE},
            {0628, U'(?<A>foo)?(?(1)bar|nada)', U'foo-barnada', TRUE},
            {0629, U'(?<A>foo(?(R)bar))?(?1)', U'foofoobar', TRUE},
            {0630, U'(x)(?<A>foo(?(R&A)bar))?(?&A)', U'xfoofoobar', TRUE},
            {0631, U'(x)(?<A>foo(?(R2)bar))?(?&A)', U'xfoofoobar', TRUE},
            {0632, U'(?1)(?(DEFINE)(blah))', U'blah', TRUE},
            {0633, U'foo(?0)?bar', U'phoofoofoobarbarbarr', TRUE},
            {0634, U'foo(?R)?bar', U'phoofoofoobarbarbarr', TRUE},
            {0635, U'a++a', U'aaaaa', FALSE},
            {0636, U'a*+a', U'aaaaa', FALSE},
            {0637, U'a{1,5}+a', U'aaaaa', FALSE},
            {0638, U'a?+a', U'ab', FALSE},
            {0639, U'a++b', U'aaaaab', TRUE},
            {0640, U'a*+b', U'aaaaab', TRUE},
            {0641, U'a{1,5}+b', U'aaaaab', TRUE},
            {0642, U'a?+b', U'ab', TRUE},
            {0643, U'fooa++a', U'fooaaaaa', FALSE},
            {0644, U'fooa*+a', U'fooaaaaa', FALSE},
            {0645, U'fooa{1,5}+a', U'fooaaaaa', FALSE},
            {0646, U'fooa?+a', U'fooab', FALSE},
            {0647, U'fooa++b', U'fooaaaaab', TRUE},
            {0648, U'fooa*+b', U'fooaaaaab', TRUE},
            {0649, U'fooa{1,5}+b', U'fooaaaaab', TRUE},
            {0650, U'fooa?+b', U'fooab', TRUE},
            {0651, U'(?:aA)++(?:aA)', U'aAaAaAaAaA', FALSE},
            {0652, U'(aA)++(aA)', U'aAaAaAaAaA', FALSE},
            {0653, U'(aA|bB)++(aA|bB)', U'aAaAbBaAbB', FALSE},
            {0654, U'(?:aA|bB)++(?:aA|bB)', U'aAbBbBbBaA', FALSE},
            {0655, U'(?:aA)*+(?:aA)', U'aAaAaAaAaA', FALSE},
            {0656, U'(aA)*+(aA)', U'aAaAaAaAaA', FALSE},
            {0657, U'(aA|bB)*+(aA|bB)', U'aAaAbBaAaA', FALSE},
            {0658, U'(?:aA|bB)*+(?:aA|bB)', U'aAaAaAbBaA', FALSE},
            {0659, U'(?:aA){1,5}+(?:aA)', U'aAaAaAaAaA', FALSE},
            {0660, U'(aA){1,5}+(aA)', U'aAaAaAaAaA', FALSE},
            {0661, U'(aA|bB){1,5}+(aA|bB)', U'aAaAbBaAaA', FALSE},
            {0662, U'(?:aA|bB){1,5}+(?:aA|bB)', U'bBbBbBbBbB', FALSE},
            {0663, U'(?:aA)?+(?:aA)', U'aAb', FALSE},
            {0664, U'(aA)?+(aA)', U'aAb', FALSE},
            {0665, U'(aA|bB)?+(aA|bB)', U'bBb', FALSE},
            {0666, U'(?:aA|bB)?+(?:aA|bB)', U'aAb', FALSE},
            {0667, U'(?:aA)++b', U'aAaAaAaAaAb', TRUE},
            {0668, U'(aA)++b', U'aAaAaAaAaAb', TRUE},
            {0669, U'(aA|bB)++b', U'aAbBaAaAbBb', TRUE},
            {0670, U'(?:aA|bB)++b', U'aAbBbBaAaAb', TRUE},
            {0671, U'(?:aA)*+b', U'aAaAaAaAaAb', TRUE},
            {0672, U'(aA)*+b', U'aAaAaAaAaAb', TRUE},
            {0673, U'(aA|bB)*+b', U'bBbBbBbBbBb', TRUE},
            {0674, U'(?:aA|bB)*+b', U'bBaAbBbBaAb', TRUE},
            {0675, U'(?:aA){1,5}+b', U'aAaAaAaAaAb', TRUE},
            {0676, U'(aA){1,5}+b', U'aAaAaAaAaAb', TRUE},
            {0677, U'(aA|bB){1,5}+b', U'bBaAbBaAbBb', TRUE},
            {0678, U'(?:aA|bB){1,5}+b', U'aAbBaAbBbBb', TRUE},
            {0679, U'(?:aA)?+b', U'aAb', TRUE},
            {0680, U'(aA)?+b', U'aAb', TRUE},
            {0681, U'(aA|bB)?+b', U'bBb', TRUE},
            {0682, U'(?:aA|bB)?+b', U'bBb', TRUE},
            {0683, U'foo(?:aA)++(?:aA)', U'fooaAaAaAaAaA', FALSE},
            {0684, U'foo(aA)++(aA)', U'fooaAaAaAaAaA', FALSE},
            {0685, U'foo(aA|bB)++(aA|bB)', U'foobBbBbBaAaA', FALSE},
            {0686, U'foo(?:aA|bB)++(?:aA|bB)', U'fooaAaAaAaAaA', FALSE},
            {0687, U'foo(?:aA)*+(?:aA)', U'fooaAaAaAaAaA', FALSE},
            {0688, U'foo(aA)*+(aA)', U'fooaAaAaAaAaA', FALSE},
            {0689, U'foo(aA|bB)*+(aA|bB)', U'foobBaAbBaAaA', FALSE},
            {0690, U'foo(?:aA|bB)*+(?:aA|bB)', U'fooaAaAbBbBaA', FALSE},
            {0691, U'foo(?:aA){1,5}+(?:aA)', U'fooaAaAaAaAaA', FALSE},
            {0692, U'foo(aA){1,5}+(aA)', U'fooaAaAaAaAaA', FALSE},
            {0693, U'foo(aA|bB){1,5}+(aA|bB)', U'fooaAbBbBaAaA', FALSE},
            {0694, U'foo(?:aA|bB){1,5}+(?:aA|bB)', U'fooaAbBbBaAbB', FALSE},
            {0695, U'foo(?:aA)?+(?:aA)', U'fooaAb', FALSE},
            {0696, U'foo(aA)?+(aA)', U'fooaAb', FALSE},
            {0697, U'foo(aA|bB)?+(aA|bB)', U'foobBb', FALSE},
            {0698, U'foo(?:aA|bB)?+(?:aA|bB)', U'fooaAb', FALSE},
            {0699, U'foo(?:aA)++b', U'fooaAaAaAaAaAb', TRUE},
            {0700, U'foo(aA)++b', U'fooaAaAaAaAaAb', TRUE},
            {0701, U'foo(aA|bB)++b', U'foobBaAbBaAbBb', TRUE},
            {0702, U'foo(?:aA|bB)++b', U'fooaAaAbBaAaAb', TRUE},
            {0703, U'foo(?:aA)*+b', U'fooaAaAaAaAaAb', TRUE},
            {0704, U'foo(aA)*+b', U'fooaAaAaAaAaAb', TRUE},
            {0705, U'foo(aA|bB)*+b', U'foobBbBaAaAaAb', TRUE},
            {0706, U'foo(?:aA|bB)*+b', U'foobBaAaAbBaAb', TRUE},
            {0707, U'foo(?:aA){1,5}+b', U'fooaAaAaAaAaAb', TRUE},
            {0708, U'foo(aA){1,5}+b', U'fooaAaAaAaAaAb', TRUE},
            {0709, U'foo(aA|bB){1,5}+b', U'foobBaAaAaAaAb', TRUE},
            {0710, U'foo(?:aA|bB){1,5}+b', U'fooaAbBaAbBbBb', TRUE},
            {0711, U'foo(?:aA)?+b', U'fooaAb', TRUE},
            {0712, U'foo(aA)?+b', U'fooaAb', TRUE},
            {0713, U'foo(aA|bB)?+b', U'foobBb', TRUE},
            {0714, U'foo(?:aA|bB)?+b', U'foobBb', TRUE},
            {0715, U'([^()]++|\\([^()]*\\))+', U'((abc(ade)ufh()()x', TRUE},
            {0716, U'round\\(([^()]++)\\)', U'_I(round(xs * sz),1)', TRUE},
            {0717, U'(foo[1x]|bar[2x]|baz[3x])+y', U'foo1bar2baz3y', TRUE},
            {0718, U'(foo[1x]|bar[2x]|baz[3x])*y', U'foo1bar2baz3y', TRUE},
            {0719, U'([yX].|WORDS|[yX].|WORD)S', U'WORDS', TRUE},
            {0720, U'([yX].|WORDS|WORD|[xY].)S', U'WORDS', TRUE},
            {0721, U'(foo|fool|[zx].|money|parted)$', U'fool', TRUE},
            {0722, U'([zx].|foo|fool|[zq].|money|parted|[yx].)$', U'fool', TRUE},
            {0723, U'(foo|fool|[zx].|money|parted)$', U'fools', FALSE},
            {0724, U'([zx].|foo|fool|[qx].|money|parted|[py].)$', U'fools', FALSE},
            {0725, U'([yX].|WORDS|[yX].|WORD)+S', U'WORDS', TRUE},
            {0726, U'(WORDS|WORLD|WORD)+S', U'WORDS', TRUE},
            {0727, U'([yX].|WORDS|WORD|[xY].)+S', U'WORDS', TRUE},
            {0728, U'(foo|fool|[zx].|money|parted)+$', U'fool', TRUE},
            {0729, U'([zx].|foo|fool|[zq].|money|parted|[yx].)+$', U'fool', TRUE},
            {0730, U'(foo|fool|[zx].|money|parted)+$', U'fools', FALSE},
            {0731, U'([zx].|foo|fool|[qx].|money|parted|[py].)+$', U'fools', FALSE},
            {0732, U'(x|y|z[QW])+(longish|loquatious|excessive|overblown[QW])+', U'xyzQzWlongishoverblownW', TRUE},
            {0733, U'(x|y|z[QW])*(longish|loquatious|excessive|overblown[QW])*', U'xyzQzWlongishoverblownW', TRUE},
            {0734, U'(x|y|z[QW]){1,5}(longish|loquatious|excessive|overblown[QW]){1,5}', U'xyzQzWlongishoverblownW', TRUE},
            {0735, U'(x|y|z[QW])++(longish|loquatious|excessive|overblown[QW])++', U'xyzQzWlongishoverblownW', TRUE},
            {0736, U'(x|y|z[QW])*+(longish|loquatious|excessive|overblown[QW])*+', U'xyzQzWlongishoverblownW', TRUE},
            {0737, U'(x|y|z[QW]){1,5}+(longish|loquatious|excessive|overblown[QW]){1,5}+', U'xyzQzWlongishoverblownW', TRUE},
            {0738, U'a*(?!)', U'aaaab', FALSE},
            {0739, U'a*(*FAIL)', U'aaaab', FALSE},
            {0740, U'a*(*F)', U'aaaab', FALSE},
            {0741, U'(A(A|B(*ACCEPT)|C)D)(E)', U'AB', TRUE},
            {0742, U'(A(A|B(*ACCEPT)|C)D)(E)', U'ACDE', TRUE},
            {0743, U'(a)(?:(?-1)|(?+1))(b)', U'aab', TRUE},
            {0744, U'(a)(?:(?-1)|(?+1))(b)', U'abb', TRUE},
            {0745, U'(a)(?:(?-1)|(?+1))(b)', U'acb', FALSE},
            {0746, U'(foo)(\\g-2)', U'foofoo', TRUE},
            {0747, U'(foo)(\\g-2)(foo)(\\g-2)', U'foofoofoofoo', TRUE},
            {0748, U'(([abc]+) \\g-1)(([abc]+) \\g{-1})', U'abc abccba cba', TRUE},
            {0749, U'(a)(b)(c)\\g1\\g2\\g3', U'abcabc', TRUE},
            {0750, U'(?<=bar>)foo', U'bar>foo', TRUE},
            {0751, U'(?<!bar>)foo', U'bar>foo', FALSE},
            {0752, U'(?<=bar>ABC)foo', U'bar>ABCfoo', TRUE},
            {0753, U'(?<!bar>ABC)foo', U'bar>ABCfoo', FALSE},
            {0754, U'(?<bar>)foo', U'bar>ABCfoo', TRUE},
            {0755, U'(?<bar>ABC)foo', U'bar>ABCfoo', TRUE},
            {0756, U'(?<=abcd(?<=(aaaabcd)))', U'..aaaabcd..', TRUE},
            {0757, U'(?=xy(?<=(aaxy)))', U'..aaxy..', TRUE},
            {0758, U'X(\\w+)(?=\\s)|X(\\w+)', U'Xab', TRUE},
            {0759, U'(?|(a))', U'a', TRUE},
            {0760, U'(?|a(.)b|d(.(o).)d|i(.)(.)j)(.)', U'd!o!da', TRUE},
            {0761, U'(?|a(.)b|d(.(o).)d|i(.)(.)j)(.)', U'aabc', TRUE},
            {0762, U'(?|a(.)b|d(.(o).)d|i(.)(.)j)(.)', U'ixyjp', TRUE},
            {0763, U'(?|(?|(a)|(b))|(?|(c)|(d)))', U'a', TRUE},
            {0764, U'(?|(?|(a)|(b))|(?|(c)|(d)))', U'b', TRUE},
            {0765, U'(?|(?|(a)|(b))|(?|(c)|(d)))', U'c', TRUE},
            {0766, U'(?|(?|(a)|(b))|(?|(c)|(d)))', U'd', TRUE},
            {0767, U'(.)(?|(.)(.)x|(.)d)(.)', U'abcde', TRUE},
            {0768, U'(\n)(?|(\n)(\n)x|(\n)d)(\n)', U'abcde', FALSE},
            {0769, U'(?|(?<foo>x))', U'x', TRUE},
            {0770, U'(?<bar>)(?|(?<foo>x))', U'x', TRUE},
            {0771, U'(?|(b)|()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()(a))', U'a', TRUE},
            {0772, U'(?(DEFINE)(?<A>(?&B)+)(?<B>a))(?&A)', U'a', TRUE},
            {0773, U'(?(DEFINE)(?<A>(?&B)+)(?<B>a))(?&A)', U'aa', TRUE},
            {0774, U'foo(\r)bar', U'foo\r\nbar', TRUE},
            {0775, U'foo(\r)bar', U'foo\nbar', TRUE},
            {0776, U'foo(\r)bar', U'foo\rbar', TRUE},
            {0777, U'foo(\r+)bar', U'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0778, U'(\\V+)(\r)', U'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0779, U'(\r+)(\\V)', U'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0780, U'foo(\r)bar', U'foo\\x{85}bar', TRUE},
            {0781, U'(\\V)(\r)', U'foo\\x{85}bar', TRUE},
            {0782, U'(\r)(\\V)', U'foo\\x{85}bar', TRUE},
            {0783, U'(\\V)(\r)', U'foo\r\nbar', TRUE},
            {0784, U'(\r)(\\V)', U'foo\r\nbar', TRUE},
            {0785, U'(\\V)(\r)', U'foo\rbar', TRUE},
            {0786, U'(\r)(\\V)', U'foo\rbar', TRUE},
            {0787, U'0|\r??\n0', U'\n\n', FALSE},
            {0788, U'foo(\\v+)bar', U'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0789, U'(\\v+)(\\V)', U'foo\r\n\\x{85}\r\n\nbar', TRUE},
            {0790, U'foo(\\v)bar', U'foo\\x{85}bar', TRUE},
            {0791, U'(\\v)(\\V)', U'foo\\x{85}bar', TRUE},
            {0792, U'foo(\\v)bar', U'foo\rbar', TRUE},
            {0793, U'(\\v)(\\V)', U'foo\rbar', TRUE},
            {0794, U'foo(\\h+)bar', U'foo\t\\x{A0}bar', TRUE},
            {0795, U'(\\h+)(\\H)', U'foo\t\\x{A0}bar', TRUE},
            {0796, U'foo(\\h)bar', U'foo\\x{A0}bar', TRUE},
            {0797, U'(\\h)(\\H)', U'foo\\x{A0}bar', TRUE},
            {0798, U'foo(\\h)bar', U'foo\tbar', TRUE},
            {0799, U'(\\h)(\\H)', U'foo\tbar', TRUE},
            {0800, U'.*\\z', U'foo\n', TRUE},
            {0801, U'\n*\\z', U'foo\n', TRUE},
            {0802, U'^(?:(\\d)x)?\\d$', U'1', TRUE},
            {0803, U'.*?(?:(\\w)|(\\w))x', U'abx', TRUE},
            {0804, U'0{50}', U'000000000000000000000000000000000000000000000000000', TRUE},
            {0805, U'^a?(?=b)b', U'ab', TRUE},
            {0806, U'^a*(?=b)b', U'ab', TRUE},
            {0807, U'[\\s][\\S]', U'\\x{a0}\\x{a0}', FALSE},
            {0808, U'abc\n\\{U+BEEF\\}', U'abc.{UBEEF}', TRUE},
            {0809, U'abc\n', U'abcd', TRUE},
            {0810, U'abc\n', U'abc\n', FALSE},
            {0811, U'\\c@', U'\\0', FALSE},
            {0812, U'\\cA', U'\\001', FALSE},
            {0813, U'\\cB', U'\\002', FALSE},
            {0814, U'\\cC', U'\\003', FALSE},
            {0815, U'\\cI', U'\\011', FALSE},
            {0816, U'\\cJ', U'\\012', FALSE},
            {0817, U'\\cR', U'\\022', FALSE},
            {0818, U'\\cS', U'\\023', FALSE},
            {0819, U'\\cX', U'\\030', FALSE},
            {0820, U'\\cY', U'\\031', FALSE},
            {0821, U'\\cZ', U'\\032', FALSE},
            {0822, U'\\c[', U'\\033', FALSE},
            {0823, U'\\c\\X', U'\\034X', FALSE},
            {0824, U'\\c]', U'\\035', FALSE},
            {0825, U'\\c^', U'\\036', FALSE},
            {0826, U'\\c_', U'\\037', FALSE},
            {0827, U'\\o{120}', U'\\x{50}', TRUE},
            {0828, U'[a\\o{120}]', U'\\x{50}', TRUE},
            {0829, U'[\\006]', U'\\006', TRUE},
            {0830, U'[\\006]', U'6\\000', FALSE},
            {0831, U'[\\0005]', U'\\0005', TRUE},
            {0832, U'[\\0005]', U'5\\000', TRUE},
            {0833, U'[\\_]', U'_', TRUE},
            {0834, U'(q1|.)*(q2|.)*(x(a|bc)*y){2,}', U'xayxay', TRUE},
            {0835, U'(q1|.)*(q2|.)*(x(a|bc)*y){2,3}', U'xayxay', TRUE},
            {0836, U'(q1|z)*(q2|z)*z{15}-.*?(x(a|bc)*y){2,3}Z', U'zzzzzzzzzzzzzzzz-xayxayxayxayZ', TRUE},
            {0837, U'(?:(?:)foo|bar|zot|rt78356)', U'foo', TRUE},
            {0838, U'^m?(\\S)(.*)\\1$', U'aba', TRUE},
            {0839, U'^m?(\\S)(.*)\\1$', U'\tb\t', FALSE},
            {0840, U'^m?(\\s)(.*)\\1$', U'\tb\t', TRUE},
            {0841, U'^m?(\\s)(.*)\\1$', U'aba', FALSE},
            {0842, U'^m?(\\W)(.*)\\1$', U':b:', TRUE},
            {0843, U'^m?(\\W)(.*)\\1$', U'aba', FALSE},
            {0844, U'^m?(\\w)(.*)\\1$', U'aba', TRUE},
            {0845, U'^m?(\\w)(.*)\\1$', U':b:', FALSE},
            {0846, U'^m?(\\D)(.*)\\1$', U'aba', TRUE},
            {0847, U'^m?(\\D)(.*)\\1$', U'5b5', FALSE},
            {0848, U'^m?(\\d)(.*)\\1$', U'5b5', TRUE},
            {0849, U'^m?(\\d)(.*)\\1$', U'aba', FALSE},
            {0850, U'^_?[^\\W_0-9]\\w\\z', U'\\xAA\\x{100}', TRUE},
            {0851, U'(?#( (?{1+)a', U'a', TRUE},
            {0852, U'ab[(?{1]', U'ab1', TRUE},
            {0853, U'ab[(?{1\\](?{2]', U'ab2', TRUE},
            {0854, U'[^\\p{Alphabetic}]', U'\\x{100}', FALSE},
            {0855, U'^(.)(?:(..)|B)[CX]', U'ABCDE', TRUE},
            {0856, U'^(.)(?:BC(.)|B)[CX]', U'ABCDE', TRUE},
            {0857, U'^(.)(?:(.)+)*[BX]', U'ABCDE', TRUE},
            {0858, U'^(.)(BC)*', U'ABCDE', TRUE},
            {0859, U'^(.)(BC)*[BX]', U'ABCDE', TRUE},
            {0860, U'^(.)(B)*.[DX]', U'ABCDE', TRUE},
            {0861, U'^(.)(B)*.[CX]', U'ABCDE', TRUE},
            {0862, U'^(?:(X)?(\\d)|(X)?(\\d\\d))$', U'X12', TRUE},
            {0863, U'^(?:(XX)?(\\d)|(XX)?(\\d\\d))$', U'XX12', TRUE},
            {0864, U'\\A(?>\\[(?:(?:)(?:R){1}|T|V?|A)\\])\\z', U'[A]', TRUE},
            {0865, U'[^\n]+', U'\nb', TRUE},
            {0866, U'[^\n]+', U'a\n', TRUE},
            {0867, U'\\w', U'\\x{200C}', TRUE},
            {0868, U'\\W', U'\\x{200C}', FALSE},
            {0869, U'\\w', U'\\x{200D}', TRUE},
            {0870, U'\\W', U'\\x{200D}', FALSE},
            {0871, U'^\r{2}$', U'\r\n\r\n', TRUE},
            {0872, U'\\Vn', U'\\xFFn/', TRUE},
            {0873, U'^_?[^\\S_0-9]\\w*\\z', U'\t', TRUE},
            {0874, U'a?\\X', U'a\\x{100}', TRUE},
            {0875, U'a?\r', U'a\n', TRUE},
            {0876, U'^a?\n$', U'a\n', TRUE},
            {0877, U'\n?a', U'\na', TRUE},
            {0878, U'(A(*PRUNE)B|A(*PRUNE)C)', U'AC', FALSE},
            {0879, U'(A(*PRUNE)B|A(*PRUNE)D|A(*PRUNE)C)', U'AC', FALSE},
            {0880, U'(A(*PRUNE)B|A(*PRUNE)C|A(*PRUNE)D)', U'AC', FALSE},
            {0881, U'((A(*PRUNE)B|A(*PRUNE)C))', U'AC', FALSE},
            {0882, U'((A(*PRUNE)B|A(*PRUNE)D|A(*PRUNE)C))', U'AC', FALSE},
            {0883, U'((A(*PRUNE)B|A(*PRUNE)C|A(*PRUNE)D))', U'AC', FALSE},
            {0884, U'A+?(*THEN)BC', U'AAABC', TRUE},
            {0885, U'A+?(*PRUNE)BC', U'AAABC', TRUE},
            {0886, U'A+(*THEN)BC', U'AAABC', TRUE},
            {0887, U'A+(*PRUNE)BC', U'AAABC', TRUE},
            {0888, U'^(?=(a)){0}b(?1)', U'back', TRUE},
            {0889, U'(?:(a(*SKIP)b)){0}(?:(?1)|ac)', U'x', FALSE},
            {0890, U'(?1)(?:(b)){0}', U'b', TRUE},
            {0891, U'(?<W>a)(?<BB>(?=(?&W))(?<=(?&W)))(?&BB)', U'aa', TRUE},
            {0892, U'^x?abc?de', U'abcde', TRUE},
            {0895, U'\\d<(.*?)>', U'a<>', FALSE},
            {0896, U'[bcd].{2,3}aaaa', U'XbXaaaaa', TRUE},
            {0897, U'[bcd].{2,3}aaaa', U'Xb\\x{100}aaaaa', TRUE},
            {0899, U'^((?(?=x)xb|ya)z)', U'xbz', TRUE},
            {0900, U'^((?(?=x)xb|ya)z)', U'yaz', TRUE},
            {0901, U'^((?(?!y)xb|ya)z)', U'xbz', TRUE},
            {0902, U'^((?(?!y)xb|ya)z)', U'yaz', TRUE},
            {0903, U'^((?(?!)xb|ya)z)', U'xbz', FALSE},
            {0904, U'^((?(?!)xb|ya)z)', U'yaz', TRUE},
            {0905, U'ab(?#Comment){2}c', U'abbc', TRUE},
            {0906, U'(?:.||)(?|)000000000@', U'000000000@', TRUE},
            {0907, U'aa$|a(?R)a|a', U'aaa', TRUE},
            {0908, U'(?:\\1|a)([bcd])\\1(?:(?R)|e)\\1', U'abbaccaddedcb', TRUE},
            {0909, U'(.*?(a(a)|i(i))n)', U'riiaan', TRUE},
            {0910, U'(^(?:(\\d)x)?\\d$)', U'1', TRUE},
            {0911, U'(X{2,}[-X]{1,4}){3,}X{2,}', U'XXX-XXX-XXX--', FALSE},
            {0912, U'^a?bcd\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff', U'ABCDEFGHIJKLMNOPQRSTUVWXYZ', FALSE},
            {0913, U'^Xaaa?Xaa', U'aaa\\x{400000}', FALSE},
            {0914, U'^(\\d+)*?4X$', U'1234X', TRUE},
            {0915, U'\\A([\\x00-\\x7F]+)(.*)\\z', U'\\007\\011\\012', TRUE},
            {0916, U'^((\\w|<(\\s)*(?1)(?3)*>)(?:(?3)*\\+(?3)*(?2))*)(?3)*\\+', U'a + b + <c + d>', TRUE},
            {0917, U'^((\\w|<(\\s)*(?1)(?3)*>)(?:(?3)*\\+(?3)*(?2))*)(?3)*\\+', U'a + <b> + c', TRUE},
            {0918, U'(?<=(?<!yz)b)c', U'aabcdef', TRUE},
            {0919, U'(?<=(?<!yz)b)c', U'abcdef', TRUE},
            {0920, U'(?:a|xx){0,4}?b', U'aaaaab ', TRUE},
            {0921, U'(?|(a)|(b))', U'b', TRUE},
            {0922, U'(?|(a)|(b))', U'a', TRUE},
            // Unicode Property Names
            {2000, U'^\\p{L}+$', U'abc', TRUE},
            {2001, U'^\\p{L}+$', U'abc123', FALSE},
            {2002, U'^\\p{Ll}+$', U'abc', TRUE},
            {2003, U'^\\p{Ll}+$', U'abcABC', FALSE},
            {2004, U'^\\p{Lu}+$', U'ABC', TRUE},
            {2005, U'^\\p{Lu}+$', U'abcABC', FALSE},
            {2006, U'\\p{N}+', U'abc', FALSE},
            {2007, U'\\p{N}+', U'abc123', TRUE},
            {2008, U'\\p{Sc}\\p{Nd}*[,.]\\p{Nd}{2}', U'$1.23', TRUE}
        ],
        {UNSIGNED4 testNum, UNICODE regex, UNICODE subject, BOOLEAN expected}
    );

res := PROJECT
    (
        NOFOLD(regexTests),
        TRANSFORM
            (
                {
                    RECORDOF(LEFT) - [regex, subject],
                    BOOLEAN actual
                },
                SELF.actual := REGEXFIND(LEFT.regex, LEFT.subject),
                SELF := LEFT
            )
    );

numTests := COUNT(regexTests);
testsPassed := res(expected = actual);
numTestsPassed := COUNT(testsPassed);
testsFailed := res(expected != actual);
numTestsFailed := COUNT(testsFailed);

MIN_PASS_PERCENTAGE := 0.95;

passedPercentage := numTestsPassed / numTests;
isSuccess := passedPercentage >= MIN_PASS_PERCENTAGE;
resultStr := IF(isSuccess, 'PASSED', 'FAILED');
fullResultStr := resultStr + ': ' + (STRING)(ROUND(passedPercentage * 100, 2));

// Output for unit test parsing
OUTPUT(resultStr, NAMED('result'));

// Uncomment the following to see details
// OUTPUT(numTests, NAMED('num_tests'));
// OUTPUT(numTestsPassed, NAMED('num_passed'));
// OUTPUT(numTestsFailed, NAMED('num_failed'));
// OUTPUT(fullResultStr, NAMED('result_desc'));
// OUTPUT(testsFailed, NAMED('failed_tests'), ALL);
