define(
({
    Abort: "Прекините",
    About: "О Апликацији",
    AboutGraphControl: "О Графичкој Контроли",
    AboutHPCCSystemsGraphControl: "О Графичкој Контроли ХПЦЦ Система",
    Action: "Акција",
    Activate: "Активирајте",
    Activated: "Активиран",
    Active: "Активан",
    ActivePackageMap: "Активна Мапа Пакета",
    ActiveWorkunit: "Активна Радна Јединица",
    Activities: "Активности",
    Activity: "Активност",
    ActualSize: "Тачна Величина",
    Add: "Додајте",
    AddGroup: "Додајте Групу",
    AddProcessMap: "Додајте Мапу Пакета",
    AddToSuperfile: "Додајте на Супердатотеку",
    AddUser: "Додајте Корисника",
    Advanced: "Вишег Нивоа",
    AllowAccess: "<center>Дозволите<br>Приступ",
    AllowFull: "<center>Дозволите<br>Потпун</center>",
    AllowRead: "<center>Дозволите<br>Читање</center>",
    AllowWrite: "<center>Дозволите<br>Писање</center>",
    ANY: "Било Који",
    Append: "Додајте",
    Apply: "Примените",
    ArchivedOnly: "Само Архивиран",
    BinaryInstalls: "Бинарне Инсталације",
    Blob: "БЛОБ",
    BlobPrefix: "БЛОБ Префикс",
    Cancel: "Поништите",
    Clear: "Очистите",
    Clone: "Клонирајте",
    Close: "Затворите",
    Cluster: "Кластер",
    ClusterName: "Име Кластера",
    ClusterPH: "r?x*",
    ClusterProcesses: "Процеси На Кластеру",
    Code: "Код",
    Col: "Колона",
    Command: "Команда",
    Comment: "Коментар",
    Completed: "Комплетиран",
    Component: "Компонента",
    Compress: "Сабијте",
    ConfirmPassword: "Потврдите Лозинку",
    Contents: "Садржаји",
    Copy: "Копирајте",
    Count: "Избројте",
    Created: "Произведен",
    Dali: "Дали",
    dataset: ":=датасет*",
    Date: "Датум",
    Deactivate: "Искљућите",
    DEF: "ДЕФ",
    Delete: "Обришите",
    DeleteSelectedFiles: "Обришите Одабране Датотеке?",
    DeleteSelectedGroups: "Обришите одабрану(е) групу(е)?",
    DeleteSelectedQueries: "Обришите Одабране Захтјеве?",
    DeleteSelectedUsers: "Обришите Одабране Кориснике?",
    DeleteSelectedWorkunits: "Обришите Одабране Радне Јединице?",
    DeleteSuperfile: "Обришите Супердатотеке?",
    DeleteThisPackage: "Обришите Овај Пакет?",
    Delimited: "Разграничен",
    DenyAccess: "<center>Забраните<br>Приступ",
    DenyFull: "<center>Забраните<br>Потпун</center>",
    DenyRead: "<center>Забраните<br>Читање</center>",
    DenyWrite: "<center>Забраните<br>Писање</center>",
    Depth: "Дубина",
    Deschedule: "Избаците Ис Реда За Извршавање",
    DescheduleSelectedWorkunits: "Избаците Одабране Радне Јединице Из Реда За Извршавање?",
    Description: "Опис",
    Despray: "Поново Обjедините Датотеку",
    DFUServerName: "Име ДФУ Сервера",
    Directory: "Директориј",
    Distance: "Раздаљина",
    Dll: "Длл",
    DOT: "ДОТ",
    DOTAttributes: "ДОТ Атрибути",
    Download: "Добавите",
    DropZone: "Зона Пријема",
    Duration: "Трајање",
    EBCDIC: "ЕБЦДИK",
    ECL: "ЕЦЛ",
    Edges: "Ивице",
    Edit: "Едитујте",
    EditDOT: "Едитујте ДОТ",
    EditGraphAttributes: "Едитујте Атрибуте Графова",
    EditXGMML: "Едитујте XГММЛ",
    Empty: "(Празан)",
    Error: "Грешка",
    Errorparsingserverresult: "Грешка у анализи резултата са сервера",
    Errors: "Грешка(e)",
    Errors: "Грешкe",
    ErrorsStatus: "Грешкe/Стање",
    ErrorWarnings: "Грешка/Упозорења",
    Escape: "Ескејп",
    ESPBuildVersion: "ЕСП Тренутна Верзија",
    ESPNetworkAddress: "ЕСП Нетворк Адреса",
    EventName: "Име Догађаја",
    EventNamePH: "имедогађаја",
    EventScheduler: "Распоређивач Догађаја",
    EventText: "Опис Догађаја",
    Exception: "Неочекивани Проблем",
    FetchingData: "У Процесу Добављња Података...",
    fetchingresults: "добијени ресултати",
    File: "Датотека",
    FileName: "Име Датотеке",
    FileParts: "Дио Датотеке",
    FilePath: "Локација Датотеке",
    Files: "Датотеке",
    FileSize: Величина Датотеке",
    FilesNoPackage: "Датотеке које не припадају пакету",
    FileType: "Тип Датотеке",
    FileUploader: "Процес за премештање Датотеке на Сервер (Aплоyдер)",
    Filter: "Филтер",
    Find: "Нађите",
    FindNext: "Нађите Следећи",
    FindPrevious: "Нађите Претходни",
    FirstName: "Име",
    Fixed: "Фиксни",
    Format: "Формат",
    FromDate: "Од Датума",
    FromSizes: "Од Величине",
    FullName: "Име и Презиме",
    Graphs: "Графикони",
    GraphView: "Слика Графикона",
    Group: "Група",
    GroupDetails: "Детаљи о Групи",
    GroupName: "Назив Групе",
    GroupPermissions: "Дозволе за Приступ Групе",
    Groups: "Групе",
    GZip: "ГЗип",
    help: "Овdе је приказан графикон извршавања ове радне јединице. Величина и нијанса указују на време извршавања сваког графикона (Већи и тамнији графикон узима већи проценат cелокупног времена извршавања.)",
    Helpers: "Помагаћи",
    Hex: "База16",
    History: "Историја",
    HPCCSystems: "ХПЦЦ Системс",
    ID: "Идентификатор",
    Import: "Увоз",
    Info: "Информација",
    InfoDialog: "Диалог Информације",
    Inputs: "Уноси",
    InvalidResponse: "(Неисправан Одговор)",
    IP: "ИП",
    IPAddress: "ИП Адреса",
    IsLibrary: "Је Библиотека",
    Jobname: "Називраднејединице",
    JobName: "Назив Радне Јединице",
    jsmi: "јсми*",
    JSmith: "ЈСмит*",
    JSON: "ЈСОН",
    Label: "Етикета",
    LandingZone: "Зона за Претовар",
    LandingZones: "Зонe за Претовар",
    Largest: "Највећи",
    LastName: "Презиме",
    LastNDays: "Последњих Н Дана",
    LegacyForm: "Стари Превазиђени Формулар",
    LibrariesUsed: "Библиотеке у Кориштењу",
    Line: "Линија",
    LineTerminators: "Крајеви Линија",
    Links: "Линкови",
    Loading: "Учитавање...",
    LoadingCachedLayout: "Учитавање Кеширане Структуре...",
    LoadingData: "Учитавање Података...",
    loadingMessage: "...Учитавање...",
    Local: "Локални",
    LoggedInAs: "Пријављен као",
    LogicalFile: "Логичка Датотека",
    LogicalFiles: "Логичке Датотеке",
    LogicalFilesAndSuperfiles: "Логичке Датотеке и Супердатотеке",
    LogicalFilesOnly: "Само Логичке Датотеке",
    LogicalFileType: "Тип Логичке Датотеке",
    LogicalName: "Име Логичке Датотеке",
    log_analysis_1: "лог_аналисис_1*",
    Mappings: "Мапирања",
    Mask: "Маска",
    Max: "Максимум",
    MaxRecordLength: "Максимална Дужина Рекорда",
    MemberOf: "Члан Од",
    Members: "Чланови",
    Message: "Поруке",
    Min: "Минимум",
    Modification: "Промена",
    ModifiedUTCGMT: "Промењен (УТЦ/ГМТ)",
    Modify: "Промени",
    MonitorEventName: "Надгледајте Име Догађаја",
    MonitorShotLimit: "Надгледајте Шот Лимит",
    MonitorSub: "Надгледајте Суб",
    MustContainUppercaseAndSymbol: "Мораte укључити велико слово и симбол",
    NA: "Н/A",
    Name: "Име",
    NamePrefix: "Префикс Имена",
    NamePrefixPlaceholder: "неки::префиks",
    Newest: "Најнивији",
    NewPassword: "Нова Лозинка",
    NoContent: "(Без садржаја)",
    noDataMessage: "...Нема Редова...",
    Node: "Чвор (Нод)",
    NoErrorFound: "Без нађених грешака\n",
    NoFilterCriteriaSpecified: "Критериј за филтрирање није специфициран.",
    NoScheduledEvents: "Нема Дефинисаних Догађаја (ивентс) на Распореду.",
    NoSplit: "Нема Подијела (Сплит)",
    NotActive: "Није Активан",
    NothingSelected: "Ништа Није Изабрано...",
    NotInSuperfiles: "Није Дио Супердатотеке",
    NoWarningFound: "Поруке Упозорења (вoрнингс) нису нађене\n",
    NumberofParts: "Број Делова",
    OK: "OK",
    Oldest: "Најстарији",
    OmitSeparator: "Изоставите Сепаратор",
    Only1PackageFileAllowed: "Дозвољен је само један пакет",
    Open: "Отворен",
    OpenInNewPage: "Отворите на Новој Страници",
    OpenLegacyECLWatch: "Отворите Стари Превазиђени ЕЦЛ Вoч",
    OpenSafeMode: "Отворите (сигурни мод)",
    Operations: "Операције",
    Options: "Опције",
    Outputs: "Излази",
    Overview: "Преглед",
    Overwrite: "Препишите",
    Owner: "Власник",
    PackageContent: "Садржај Пакета",
    PackageContentNotSet: "Садржај Пакета није дефинисан",
    PackageMap: "Мапа Пакета",
    PackageMaps: "Мапe Пакета",
    PackagesNoQuery: "Пакети за које нису дефинисани упити (kуериз)",
    ParameterXML: "Параметар XМЛ",
    Parts: "Делови",
    Password: "Лозинка",
    PasswordExpiration: "Лозинка Истиће",
    PasswordsDoNotMatch: "Погрешна Лозинка.",
    Path: "Пут",
    PathMask: "Маска за Пут",
    PctComplete: "% Комплетиран",
    PercentDone: "Проценат Завршен",
    PerformingLayout: "Извршава Лejaут...",
    Permissions: "Дозволе за Приступ",
    PlaceholderFindText: "Pjид (Wuid), Корисник, Даље...",
    PlaceholderFirstName: "Џон",
    PlaceholderLastName: "Смит",
    Playground: "Игралиште",
    Prefix: "Префикс",
    PrefixPlaceholder: "имедатотеке{:дужина}, величинадатотеке{:[B|L][1-8]}",
    Preview: "Преглед",
    Priority: "Приоритет",
    Process: "Процес",
    ProcessFilter: "Процес&nbsp;Филтер",
    ProgressMessage: "Порука о Прогресу",
    Properties: "Својства",
    Property: "Својствo",
    Protect: "Заштитите",
    Protected: "Заштићен",
    Publish: "Објавите",
    PublishedBy: "Објављивач",
    PublishedQueries: "Објављени Упити",
    Queries: "Упити",
    QueriesNoPackage: "Упити без одговарајућег пакета",
    QueryDetailsfor: "Детаљи о Упиту",
    QuerySet: "Колекција Упита",
    Queue: "Ред (Kjу)",
    Quote: "Цитат",
    RecordCount: "Број Рекорда",
    RecordLength: "Дужина Рекорда",
    Records: "Рекорди",
    RecordSize: "Величина Рекорда",
    Refresh: "Освежите",
    ReleaseNotes: "Напомена о Издању",
    Reload: "Поново Учитајте",
    RemoteDali: "Далеки Дали",
    RemoteDaliIP: "Далеки&nbsp;Дали&nbsp;ИП&nbsp;Адреса",
    Remove: "Уклоните",
    Rename: "Преименујте",
    RenderedSVG: "Донесене СВГ",
    RenderSVG: "Донесите СВГ",
    Replicate: "Реплицирајте",
    RequestSchema: "Шема Захтева",
    Reschedule: "Поново Ставите На Распоред",
    Reset: "Ресетујте",
    Resource: "Ресурс",
    Resources: "Ресурси",
    ResponseSchema: "Шема Одговора",
    Restart: "Поново Покрените",
    Resubmit: "Поново Поднесите",
    Results: "Резултат(и)",
    RetainSuperfileStructure: "Задржите Структуру Супердатотеке",
    RetypePassword: "Поновите Лозинку",
    Rows: "Редови",
    RowTag: "Етикета Реда",
    RoxieCluster: "Роkcи Кластер",
    Sample: "Пример",
    SampleRequest: "Пример Захтева",
    SampleResponse: "Пример Одговора",
    Save: "Сачувајте",
    Scope: "Подручје",
    SearchResults: "Резултати Претраживања",
    SecondsRemaining: "Преостало Секунди",
    SelectPackageFile: "Изаберитe Пакет",
    Seperators: "Сеператори",
    SetBanner: "Поставите Заставицу",
    SetToFailed: "Поставите На Неуспешан",
    Severity: "Озбиљност",
    Show: "Прокажите",
    ShowSVG: "Прокажите СВГ",
    Size: "Величина",
    Skew: "Скју",
    Slaves: "Робови (Слejвс)",
    Smallest: "Најмањи",
    SOAP: "СОАП",
    SomeDescription: "Неки*Опис",
    somefile: "*::некифajл*",
    Source: "Изворна Верзија",
    SourceCode: "Изворна Верзија Кода",
    SourcePath: "Изворна Верзија Пута (са омогућеним *)",
    SplitPrefix: "Сплит Префикс",
    Spray: "Разбацајте (Спрej)",
    Start: "Почните",
    Started: "Почео",
    State: "Стање",
    Stopped: "Заустављен",
    Subgraphs: "Подграфикон",
    Submit: "Поднесите",
    Summary: "Кратак Преглед",
    SummaryMessage: "Сажета Порука",
    SuperFile: "Супер Датотека",
    SuperfilesOnly: "Само Супердатотеке",
    Suspend: "Суспендујте",
    Suspended: "Суспендован",
    SuspendedBy: "Суспендован Од",
    SVGSource: "СВГ Извор",
    SyncSelection: "Синхронизујте Са Одабраним",
    SystemServers: "Систем Сервера",
    tag: "таг",
    Target: "Циљ",
    TargetClusters: "Циљни Кластери",
    TargetName: "Назив Циља",
    TargetNamePlaceholder: "неко::логићко::име",
    TargetWuid: "Циљ/Pjид",
    Terminators: "Терминатори",
    TestPages: "Тест Странице",
    ThorNetworkAddress: "Нетворк Адреса Торa",
    Time: "Време",
    TimeSeconds: "Време (Секунде)",
    TimeStarted: "Време Почетка",
    TimeStopped: "Време Краја",
    Timings: "Времена",
    TimingsMap: "Мапа Времена",
    title_Activity: "Активности",
    title_DFUQuery: "Логичке Датотеке",
    title_DFUWUDetails: "ДФУ Радна Јединица",
    title_ECLPlayground: "ЕЦЛ Игралиште",
    title_EventScheduleWorkunit: "Распоређивач Догађаја",
    title_GetDFUWorkunits: "ДФУ Радне Јединице",
    title_Graph: "Графикон",
    title_GraphPage: "наслов",
    title_Graphs: "Графикони",
    title_GridDetails: "Промени Ме",
    title_HPCCPlatformECL: "ХПЦЦ Платформ - Главна Страница",
    title_HPCCPlatformFiles: "ХПЦЦ Платформ - Датотеке",
    title_HPCCPlatformMain: "ХПЦЦ Платформ - Главна Страница",
    title_HPCCPlatformOps: "ХПЦЦ Платформ - Управљње",
    title_HPCCPlatformRoxie: "ХПЦЦ Платформ - Роkcи",
    title_LFDetails: "Детаљи о Логичкоj Датотеци",
    title_LZBrowse: "Зона за Претовар",
    title_QuerySetDetails: "Детаљи Упита",
    title_QuerySetErrors: "Грешке",
    title_QuerySetLogicalFiles: "Логичке Датотеке",
    title_QuerySetQuery: "Упити (Kуериз)",
    title_QuerySetSuperFiles: "Супер Датотеке",
    title_QueryTest: "Супер Датотеке",
    title_Result: "Ацктивност",
    title_Results: "Резултати",
    title_SearchResults: "Резултати Претраживања",
    title_SourceFiles: "Оригиналне Датотеке",
    title_UserQuery: "Права Приступа",
    title_WUDetails: "ЕЦЛ Детаљи о Радној Јединици",
    title_WUQuery: "ЕЦЛ Радне Јединице",
    ToDate: "До Сада",
    Toenablegraphviews: "Да бисте могли видети графиконе, мораћете инсталисати Граф Вjу Kонтрол плaгин",
    ToSizes: "До Величина",
    TotalThorTime: "Укупно Време Тора",
    Type: "Тип",
    undefined: "недефинисан",
    Unknown: "Непознат",
    Unprotect: "Укините Заштиту",
    Unsuspend: "Укините Суспензију",
    Unsuspended: "Суспензија Укинута",
    Upload: "Aплоyд",
    Used: "Кориштен",
    User: "Корисник",
    UserDetails: "Детаљи о Кориснику",
    UserID: "Корисницки ИД",
    Username: "Имекорисника",
    UserName: "Име Корисника",
    UserPermissions: "Дозволе за Корисников Приступ",
    Users: "Корисници",
    UseSingleConnection: "Користите Само Једaн Прикључак (конекшн)",
    Validate: "Потврдите",
    ValidatePackageMap: "Потврдите Мапу Пакета",
    ValidateResult: "=====Потврдите Резултaт=====\n\n",
    Value: "Вредност",
    Variable: "Варијабла",
    VariableBigendian: "Варијабла Биг-ендиан",
    VariableSourceType: "Тип Извора",
    Version: "Верзија",
    Views: "Погледи",
    Visualize: "Визуализујте",
    Warnings: "Упозорење(а)",
    WarnOldGraphControl: "Упозорење:  Стара Графичка Контрола",
    Width: "Ширина",
    Workunit: "Радна Јединица",
    Workunits: "Радне Јединице",
    Wrap: "Замотајте",
    WSDL: "WSDL",
    WUID: "PJИД",
    Wuidcannotbeempty: "Pjид Не Може Бити Празан.",
    WUSnapShot: "Тренутна Слика Радне Јединице",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Нема ни једане Логичке Датотеке(проверите филтер)",
    Zip: "Запакујте (Зип)",
    ZippedAnalysisPackage: "Запаковани Пакет са Анализама",
    Zoom100Pct: "Зумирајте 100%",
    ZoomAll: "Зумирајте Све",
    ZoomWidth: "Зумирајте Ширину"
})
);
