#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2019 HPCC Systems®.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################


SCRIPT_DIR=$(dirname $0)

function usage()
{

 cat <<EOF
    Usage: $(basename $0) <options>
      <options>:
      -D: run sshd with "-D"
      -e: environment, such as kube, swarm, azure, gce, etc. Only kube and swarm are currently supported.
      -h: print this help

EOF
   exit 2
}

environment=swarm
run_sshd_foreground=false

# Process command-line parameters
while getopts "*De:h" arg
do
   case $arg in
      D) run_sshd_foreground=true
         ;;
      e) environment=${OPTARG}
         ;;
      h) usage
         ;;
      ?)
         echo "Unknown option $OPTARG"
         usage
         ;;
   esac
done


[ ! -e ~/.ssh/id_rsa ] && cp -r /home/hpcc/.ssh ~/
if [ "${run_sshd_foreground}" = "true" ]
then
  /usr/sbin/sshd -D
else
  service ssh start
  if [ "${environment}" = "kube" ]
  then
     ${SCRIPT_DIR}/kube/events_watcher.py

  fi
fi
