{{- range $plane := .Values.planes -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s-pv" $plane.name (include "hpcc-localfile.fullname" $) }}
  labels:
    store: {{ printf "%s-%s-pv" $plane.name (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: "manual"
  capacity:
    storage: {{ $plane.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ $plane.rwmany | default false | ternary "ReadWriteMany" "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: Directory
    path: {{ printf "%s%s%s" $.Values.common.hostpath (regexMatch ".*/$" $.Values.common.hostpath | ternary "" "/") $plane.subPath | quote }}
---
{{ end }}
