{{- range $plane := .Values.planes -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s-pvc" $plane.name (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: "manual"
  volumeName: {{ printf "%s-%s-pv" $plane.name (include "hpcc-localfile.fullname" $) }}
  accessModes:
    - {{ $plane.rwmany | default false | ternary "ReadWriteMany" "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $plane.size }}
  selector:
    matchLabels:
      store: {{ printf "%s-%s-pv" $plane.name (include "hpcc-localfile.fullname" $) }}
---
{{ end }}
