define({root:
({
    Abort: "Abort",
    AbortedBy: "Aborted by",
    AbortedTime: "Aborted time",
    About: "About",
    AboutGraphControl: "About Graph Control",
    AboutHPCCSystemsGraphControl: "About HPCC Systems® Graph Control",
    Account: "Account",
    Action: "Action",
    Activate: "Activate",
    Activated: "Activated",
    Active: "Active",
    ActivePackageMap: "Active Package Map",
    ActiveWorkunit: "Active Workunit",
    Activities: "Activities",
    Activity: "Activity",
    ActivityMap: "Activity Map",
    ActualSize: "Actual Size",
    Add: "Add",
    AddAttributes: "Add attributes/values to your method",
    AddAttributes2: "Add Attribute(s)",
    AddBinding: "Add Binding",
    AddFile: "Add File",
    AddGroup: "Add Group",
    AddtionalProcessesToFilter: "Addtional Processes To Filter",
    AdditionalResources: "Additional Resources",
    AddProcessMap: "Add Package Map",
    AddTheseFilesToDali: "Add these files to Dali?",
    AddToSuperfile: "Add To Superfile",
    AddToExistingSuperfile: "Add to an existing superfile",
    AddUser: "Add User",
    Advanced: "Advanced",
    All: "All",
    AllowAccess: "<center>Allow<br>Access</center>",
    AllowForeignFiles: "Allow Foreign Files",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    AllQueuedItemsCleared: "All Queued items have been cleared. The current running job will continue to execute.",
    ANY: "ANY",
    AnyAdditionalProcessesToFilter: "Any Addtional Processes To Filter",
    Append: "Append",
    Apply: "Apply",
    ArchivedOnly: "Archived Only",
    ArchivedWarning: "Warning: please specify a small date range. If not, it may take some time to retrieve the workunits and the browser may be timed out.",
    Attach: "Attach",
    BinaryInstalls: "Binary Installs",
    Attribute: "Attribute",
    AttributesAreRequired: "Attributes are required",
    AutoRefresh: "Auto Refresh",
    AutoRefreshIncrement: "Auto Refresh Increment",
    AutoRefreshEvery: "Auto refresh every x minutes",
    Back: "Back",
    BannerColor: "Banner Colour",
    BannerMessage: "Banner Message",
    BannerScroll: "Banner Scroll",
    BannerSize: "Banner Size",
    Binding: "Binding",
    BindingDeleted: "Binding Deleted",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefix",
    Bottom: "Bottom",
    Busy: "Busy",
    Cancel: "Cancel",
    CancelAll: "Cancel All",
    CancelAllMessage: "Abort running jobs and clear queue. Do you wish to continue?",
    CheckAllNodes: "Check All Nodes",
    CheckFilePermissions: "Check File Permissions",
    CheckSingleNode: "Check Single Node",
    Clear: "Clear",
    Clone: "Clone",
    CloneTooltip: "Duplicate workunit",
    Close: "Close",
    Cluster: "Cluster",
    ClusterName: "Cluster Name",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Cluster Processes",
    Code: "Code",
    CodeGenerator: "Code Generator",
    Col: "Col",
    CollapseAll: "Collapse All",
    Command: "Command",
    Comment: "Comment",
    Completed: "Completed",
    ComplexityWarning: "More than {threshold} activities ({activityCount}) - suppress initial display?",
    CompressedFileSize: "Compressed File Size",
    Component: "Component",
    Compress: "Compress",
    Compressed: "Compressed",
    Condition: "Condition",
    Configuration: "Configuration",
    ConfirmPassword: "Confirm Password",
    ConfirmRemoval: "Are you sure you want to do this?",
    ContactAdmin: "If you wish to rename this group, please contact your LDAP admin.",
    Content: "Content",
    Contents: "Contents",
    ContentType: "Content Type",
    Copy: "Copy",
    Count: "Count",
    CreateANewFile: "Create a new superfile",
    Created: "Created",
    Critical: "Critical",
    ClearPermissionsCache: "Clear Permissions Cache",
    ClearPermissionsCacheConfirm: "Are you sure you want to clear the DALI and ESP permissions caches? Running workunit performance might degrade significantly until the caches have been refreshed.",
    ClonedWUID: "Cloned WUID",
    CSV: "CSV",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Date",
    Day: "Day",
    Deactivate: "Deactivate",
    Debug: "Debug",
    DEF: "DEF",
    Defaults: "Defaults",
    Definition: "Definition",
    Delete: "Delete",
    DeleteBinding: "Delete Binding",
    DeletedBinding: "Deleted Binding",
    Deleted: "Deleted",
    DeleteEmptyDirectories: "Delete empty directories?",
    DeleteDirectories: "Remove empty directories. Do you wish to continue?",
    DeleteSelectedFiles: "Delete Selected Files?",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedPermissions: "Delete selected permission(s)?",
    DeleteSelectedQueries: "Delete Selected Queries?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DeleteSelectedWorkunits: "Delete Selected Workunits?",
    DeleteSuperfile: "Delete Superfile?",
    DeleteSuperfile2: "Delete Superfile",
    DeleteThisPackage: "Delete this package?",
    Delimited: "Delimited",
    DenyAccess: "<center>Deny<br>Access</center>",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Depth: "Depth",
    DepthTooltip: "Maximum Subgraph Depth",
    Deschedule: "Deschedule",
    DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
    Description: "Description",
    DESDL: "Dynamic ESDL",
    Despray: "Despray",
    Details: "Details",
    DFUServerName: "DFU Server Name",
    DFUWorkunit: "DFU Workunit",
    Directories: "Directories",
    Directory: "Directory",
    DisableScopeScans: "Disable Scope Scans",
    DisableScopeScanConfirm: "Are you sure you want to disable Scope Scans?  Changes will revert to configuration settings on DALI reboot.",
    DiskUsage: "Disk Usage",
    Distance: "Distance",
    DistanceTooltip: "Maximum Activity Neighbourhood Distance",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Attributes",
    Down: "Down",
    Download: "Download",
    Downloads: "Downloads",
    DownloadToCSV: "Download to CSV",
    DropZone: "Drop Zone",
    Duration: "Duration",
    DynamicNoServicesFound: "No services found",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "ECL Workunit",
    Edges: "Edges",
    Edit: "Edit",
    EditDOT: "Edit DOT",
    EditGraphAttributes: "Edit Graph Attributes",
    EditXGMML: "Edit XGMML",
    EmployeeID: "Employee ID",
    Empty: "(Empty)",
    Enable: "Enable",
    EnableScopeScans: "Enable Scope Scans",
    EnableScopeScansConfirm: "Are you sure you want to enable Scope Scans? Changes will revert to configuration settings on DALI reboot.",
    EnglishQ: "English?",
    EnterAPercentage: "Enter a percentage",
    EnterAPercentageOrMB: "Enter A Percentage or MB",
    Error: "Error",
    Errorparsingserverresult: "Error parsing server result",
    Errors: "Error(s)",
    ErrorsStatus: "Errors/Status",
    ErrorUploadingFile: "Error uploading file(s). Try checking permissions.",
    ErrorWarnings: "Error/Warning(s)",
    Escape: "Escape",
    ESPBuildVersion: "ESP Build Version",
    ESPNetworkAddress: "ESP Network Address",
    EventName: "Event Name",
    EventNamePH: "Event Name",
    EventScheduler: "Event Scheduler",
    EventText: "Event Text",
    EventTextPH: "Event Text",
    Exception: "Exception",
    FailIfNoSourceFile:"Fail If No Source File",
    Fatal: "Fatal",
    Fetched: "Fetched",
    FetchingData: "Fetching Data...",
    fetchingresults: "fetching results",
    ExpandAll: "Expand All",
    Export: "Export",
    ExportSelectionsToList: "Export Selections to List",
    File: "File",
    FileCluster: "File Cluster",
    FileCounts: "File Counts",
    FileName: "File Name",
    FileParts: "File Parts",
    FilePath: "File Path",
    Files: "Files",
    FilesPending: "Files pending",
    FileScopes: "File Scopes",
    FileScopeDefaultPermissions: "File Scope Default Permissions",
    FileSize: "File Size",
    FilesNoPackage: "Files without matching package definitions",
    FilePermission: "<b>File Permission</b>",
    FilesWithUnknownSize: "Files With Unknown Size",
    FileType: "File Type",
    FileUploader: "File Uploader",
    FileUploadStillInProgress: "File upload still in progress",
    Filter: "Filter",
    FilterSet: "Filter Set",
    Find: "Find",
    Finished: "Finished",
    FindNext: "Find Next",
    FindPrevious: "Find Previous",
    FirstName: "First Name",
    FirstNRows: "First N Rows",
    Fixed: "Fixed",
    Folder: "Folder",
    Format: "Format",
    Forums: "Forums",
    Forward: "Forward",
    FoundFile: "Found File",
    FoundFileMessage: "A found file has all of its parts on disk that are not referenced in the Dali server. All the file parts are accounted for so they can be added back to the Dali server. They can also be deleted from the cluster, if required.",
    FromDate: "From Date",
    FromSizes: "From Sizes",
    FromTime: "From Time",
    FullName: "Full Name",
    Generate: "Generate",
    GetSoftwareInformation: "Get Software Information",
    Graph: "Graph",
    Graphs: "Graphs",
    GraphView: "Graph View",
    Group: "Group",
    GroupBy: "Group By",
    Grouping: "Grouping",
    GroupDetails: "Group Details",
    GroupName: "Group Name",
    GroupPermissions: "Group Permissions",
    Groups: "Groups",
    GZip: "GZip",
    help: "This area displays the treemap for the graph(s) in this workunit. The size and hue indicate the duration of each graph (Larger and darker indicates a greater percentage of the time taken.)",
    Helper: "Helper",
    Helpers: "Helpers",
    Hex: "Hex",
    HideSpills: "Hide Spills",
    High: "High",
    History: "History",
    HPCCSystems: "HPCC Systems®",
    Icon: "Icon",
    ID: "ID",
    Inactive: "Inactive",
    IncludeSlaveLogs: "Include slave logs",
    Index: "Index",
    Info: "Info",
    InfoDialog: "Info Dialog",
    InheritedPermissions: "Inherited permission:",
    Inputs: "Inputs",
    InvalidResponse: "(Invalid response)",
    IP: "IP",
    IPAddress: "IP Address",
    IsCompressed: "Is Compressed",
    IsLibrary: "Is Library",
    IsReplicated: "Is Replicated",
    IssueReporting: "Issue Reporting",
    Jobname: "Jobname",
    JobName: "Job Name",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    KeyFile: "Key File",
    Label: "Label",
    LandingZone: "Landing Zone",
    LandingZones: "Landing Zones",
    LanguageFiles: "Language Files",
    Largest: "Largest",
    LargestFile: "Largest File",
    LargestSize: "Largest Size",
    LastMessage: "Last Message",
    LastName: "Last Name",
    LastNDays: "Last N Days",
    LastNHours: "Last N Hours",
    LastNRows: "Last N Rows",
    LastRun: "Last Run",
    LegacyForm: "Legacy Form",
    LDAPWarning: "<b>LDAP Services Error:</b>  &lsquo;Too Many Users&rsquo; - Please use a Filter.",
    LibrariesUsed: "Libraries Used",
    LibraryName: "Library Name",
    Line: "Line",
    LineTerminators: "Line Terminators",
    Links: "Links",
    LoadPackageContentHere: "(Load package content here)",
    LoadPackageFromFile: "Load Package from a file",
    Loading: "Loading...",
    LoadingCachedLayout: "Loading Cached Layout...",
    LoadingData: "Loading Data...",
    loadingMessage: "...Loading...",
    Local: "Local",
    LocalFileSystemsOnly: "Local File Systems Only",
    Location: "Location",
    LogFile: "Log File",
    LoggedInAs: "Logged in as",
    LogicalFile: "Logical File",
    LogicalFiles: "Logical Files",
    LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
    LogicalFilesOnly: "Logical Files Only",
    LogicalFileType: "Logical File Type",
    LogicalName: "Logical Name",
    Log: "Log",
    Logs: "Logs",
    log_analysis_1: "log_analysis_1*",
    LostFile: "Lost File",
    LostFile2: "Lost Files",
    LostFileMessage: "A logical file that is missing at least one file part on both the primary and replicated locations in storage. The logical file is still referenced in the Dali server. Deleting the file removes the reference from the Dali server and any remaining parts on disk.",
    Low: "Low",
    Machines: "Machines",
    MachineInformation: "Machine Information",
    Major: "Major",
    ManagedBy: "Managed By",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Press Ctrl+C",
    ManualOverviewSelection: "(Manual overview selection will be required)",
    ManualTreeSelection: "(Manual tree selection will be required)",
    Mappings: "Mappings",
    Mask: "Mask",
    Max: "Max",
    MaxNode: "Max Node",
    MaxSize: "Max Size",
    MaximumNumberOfSlaves: "Slave Number",
    MaxRecordLength: "Max Record Length",
    MemberOf: "Member Of",
    Members: "Members",
    Message: "Message",
    Methods: "Methods",
    Min: "Min",
    MinNode: "Min Node",
    MinSize: "Min Size",
    Minor: "Minor",
    Missing: "Missing",
    MixedNodeStates: "Mixed Node States",
    Modified: "Modified",
    Modification: "Modification",
    ModifiedUTCGMT: "Modified (UTC/GMT)",
    Modify: "Modify",
    Monitoring: "Monitoring",
    MonitorEventName: "Monitor Event Name",
    MonitorShotLimit: "Monitor Shot Limit",
    MonitorSub: "Monitor Sub",
    Month: "Month",
    More: "more",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    NA: "N/A",
    Name: "Name",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Newest",
    NewPassword: "New Password",
    NoContent: "(No content)",
    noDataMessage: "...Zero Rows...",
    Node: "Node",
    NodeGroup: "Node Group",
    None: "None",
    NoErrorFound: "No errors found\n",
    NoFilterCriteriaSpecified: "No filter criteria specified.",
    NoPublishedSize: "No published size",
    NoScheduledEvents: "No Scheduled Events.",
    NoSplit: "No Split",
    NotActive: "Not active",
    NothingSelected: "Nothing Selected...",
    NotInSuperfiles: "Not in Superfiles",
    Normal: "Normal",
    NotSuspendedbyUser: "Not Suspended By User",
    NoWarningFound: "No warnings found\n",
    NumberofParts: "Number of Parts",
    NumberofSlaves: "Number of Slaves",
    OK: "OK",
    Oldest: "Oldest",
    OldPassword: "Old Password",
    OmitSeparator: "Omit Separator",
    Only1PackageFileAllowed: "Only one package file allowed",
    Open: "Open",
    OpenInNewPage: "Open in New Page",
    OpenInNewPageNoFrame: "Open in New Page (No Frame)",
    OpenLegacyECLWatch: "Open Legacy ECL Watch",
    OpenLegacyMode: "Open (legacy)",
    OpenNativeMode: "Open (native)",
    OpenSource: "Open Source",
    Operations: "Operations",
    Options: "Options",
    OriginalFile: "Original File",
    OrphanFile: "Orphan Files",
    OrphanFile2: "Orphan File",
    OrphanMessage: "An orphan file has partial file parts on disk. However, a full set of parts is not available to construct a complete logical file. There is no reference to these file parts in the Dali server.",
    Outputs: "Outputs",
    Overview: "Overview",
    Overwrite: "Overwrite",
    OverwriteMessage: "Some file(s) already exist. Please check overwrite box to continue.",
    Owner: "Owner",
    PackageContent: "Package Content",
    PackageContentNotSet: "Package content not set",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Packages without matching queries",
    ParameterXML: "Parameter XML",
    Part: "Part",
    PartMask: "Part Mask",
    Parts: "Parts",
    PartsFound: "Parts Found",
    PartsLost: "Parts Lost",
    Password: "Password",
    PasswordExpiration: "Password Expiration",
    PasswordOpenZAP: "Password to open ZAP (optional)",
    PasswordsDoNotMatch: "Passwords do not match.",
    PasswordExpired: "Your password has expired.  Please change now.",
    PasswordExpirePrefix: "Your password will expire in ",
    PasswordExpirePostfix: " day(s). Do you want to change it now?",
    Path: "Path",
    PathMask: "Path Mask",
    Pause: "Pause",
    PauseNow: "Pause Now",
    PctComplete: "% Complete",
    PercentDone: "Percent Done",
    PerformingLayout: "Performing Layout...",
    PermissionName: "Permission Name",
    Permission: "Permission",
    Permissions: "Permissions",
    PhysicalFiles: "Physical Files",
    PlaceholderFindText: "Wuid, User, (ecl:*, file:*, dfu:*, query:*)...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Playground",
    PleasePickADefinition: "Please pick a definition",
    PleaseSelectAGroupToAddUser: "Please select a group to add the user to",
    PleaseSelectAUserOrGroup: "Please select a user or a group along with a file name",
    PleaseSelectAUserToAdd: "Please select a user to add",
    PleaseSelectADynamicESDLService: "Please select a dynamic ESDL service",
    PleaseSelectATopologyItem: "Please select a target, service or machine.",
    Plugins: "Plugins",
    PleaseEnterANumber: "Please enter a number 1 - ",
    Port: "Port",
    Prefix: "Prefix",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preflight: "Preflight",
    PreserveCompression: "Preserve Compression",
    Preview: "Preview",
    PrimaryLost: "Primary Lost",
    PrimaryMonitoring: "Primary Monitoring",
    Priority: "Priority",
    Process: "Process",
    ProcessFilter: "Process Filter",
    ProcessorInformation: "Processor Information",
    ProgressMessage: "Progress Message",
    Properties: "Properties",
    Property: "Property",
    Protect: "Protect",
    Protected: "Protected",
    Publish: "Publish",
    Published: "Published",
    PublishedBy: "Published By",
    PublishedQueries: "Published Queries",
    PushEvent: "Push Event",
    Quarter: "Quarter",
    Queries: "Queries",
    QueriesNoPackage: "Queries without matching package",
    Query: "Query",
    QueryDetailsfor: "Query Details for",
    QueryID: "Query ID",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Query Name",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Query Set",
    Queue: "Queue",
    Quote: "Quote",
    QuotedTerminator: "Quoted Terminator",
    RawTextPage: "Raw Text (Current Page)",
    Ready: "Ready",
    ReallyWantToRemove: "Really want to remove?",
    RecordCount: "Record Count",
    RecordLength: "Record Length",
    Records: "Records",
    RecordSize: "Record Size",
    RecordStructurePresent: "Record Structure Present",
    Recover: "Recover",
    RecoverTooltip: "Restart paused / stalled workunit",
    Recycling: "Recycling",
    RedBook: "Red Book",
    Refresh: "Refresh",
    ReleaseNotes: "Release Notes",
    Reload: "Reload",
    Remaining: "Remaining",
    RemoteCopy: "Remote Copy",
    RemoteDali: "Remote Dali",
    RemoteDaliIP: "Remote Dali IP Address",
    Remove: "Remove",
    RemoveAtttributes: "Remove Attribute(s)",
    RemoveAttributeQ: "You are about to remove this attribute. Are you sure you want to do this?",
    RemoveSubfiles: "Remove Subfile(s)",
    RemoveSubfiles2: "Remove Subfile(s)?",
    RemoveUser: "You are about to remove yourself from the group:",
    Rename: "Rename",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Render SVG",
    Replicate: "Replicate",
    ReplicatedLost: "Replicated Lost",
    ReplicateOffset: "Replicate Offset",
    RepresentsASubset: "represent a subset of the total number of matches. Using a correct filter may reduce the number of matches.",
    RequestSchema: "Request Schema",
    RequiredForXML: "Required for spraying XML",
    Reschedule: "Reschedule",
    Reset: "Reset",
    ResetThisQuery: "Reset This Query?",
    ResetViewToSelection: "Reset View to Selection",
    Resource: "Resource",
    Resources: "Resources",
    ResponseSchema: "Response Schema",
    Restart: "Restart",
    Restarted: "Restarted",
    Restore: "Restore",
    Resubmit: "Resubmit",
    ResubmitTooltip: "Resubmit existing workunit",
    Resubmitted: "Resubmitted",
    Results: "Result(s)",
    Resume: "Resume",
    RetainSuperfileStructure: "Retain Superfile Structure",
    RetypePassword: "Retype Password",
    Reverse: "Reverse",
    RoxieFileCopy: "Roxie Files Copy Status",
    Rows: "Rows",
    RowPath: "Row Path",
    RowTag: "Row Tag",
    RoxieCluster: "Roxie Cluster",
    RunningServerStrain: "Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?",
    Sample: "Sample",
    SampleRequest: "Sample Request",
    SampleResponse: "Sample Response",
    Save: "Save",
    Scope: "Scope",
    SearchResults: "Search Results",
    SecondsRemaining: "Seconds Remaining",
    Security: "Security",
    SelectPackageFile: "Select Package File",
    Separators: "Separators",
    Services: "Services",
    SetBanner: "Set Banner",
    SetTextError: "Failed to display text (too large?).  Use &lsquo;helpers&rsquo; to download.",
    SetToFailed: "Set To Failed",
    Severity: "Severity",
    Show: "Show",
    ShowProcessesUsingFilter: "Show Processes Using Filter",
    ShowSVG: "Show SVG",
    Size: "Size",
    Skew: "Skew",
    SkewNegative: "Skew(-)",
    SkewPositive: "Skew(+)",
    SLA: "SLA",
    Slaves: "Slaves",
    SlaveLogs: "Slave Logs",
    SlaveNumber: "Slave Number",
    Smallest: "Smallest",
    SmallestFile: "Smallest File",
    SmallestSize: "Smallest Size",
    SOAP: "SOAP",
    SomeDescription: "Some*Description",
    somefile: "*::somefile*",
    Source: "Source",
    SourceCode: "Source Code",
    SourceLogicalFile: "Source Logical Name",
    SourcePath: "Source Path (Wildcard Enabled)",
    SourceProcess: "Source Process",
    Spill: "Spill",
    SplitPrefix: "Split Prefix",
    Spray: "Spray",
    Start: "Start",
    Starting: "Starting",
    Started: "Started",
    State: "State",
    Status: "Status",
    Stats: "Stats",
    Stopped: "Stopped",
    Stopping: "Stopping",
    StorageInformation: "Storage Information",
    Subgraph: "Subgraph",
    Subgraphs: "Subgraphs",
    Submit: "Submit",
    Subtype: "Subtype",
    Summary: "Summary",
    SummaryMessage: "Summary Message",
    Superfile: "Superfile",
    Superfiles: "Superfiles",
    SuperFile: "Super File",
    SuperFiles: "Super Files",
    SuperFilesBelongsTo: "Member of Superfile(s)",
    SuperfilesOnly: "Superfiles Only",
    SuperOwner: "Super Owner",
    Suspend: "Suspend",
    Suspended: "Suspended",
    SuspendedBy: "Suspended By",
    SuspendedByCluster: "Suspended By Cluster",
    SuspendedByUser: "Suspended By User",
    SuspendedReason: "Suspended Reason",
    SVGSource: "SVG Source",
    SyncSelection: "Sync To Selection",
    SystemServers: "System Servers",
    tag: "tag",
    Target: "Target",
    Targets: "Targets",
    TargetClusters: "Target Clusters",
    TargetName: "Target Name",
    TargetNamePlaceholder: "some::logical::name",
    TargetRowTagRequired: "You must supply a target row tag",
    TargetScope: "Target Scope",
    TargetWuid: "Target/Wuid",
    Terminators: "Terminators",
    TestPages: "Test Pages",
    TheReturnedResults: "The returned results",
    ThorNetworkAddress: "Thor Network Address",
    ThorMasterAddress: "Thor Master Address",
    ThorProcess: "Thor Process",
    Time: "Time",
    TimeSeconds: "Time (Seconds)",
    TimeStarted: "Time Started",
    TimeStopped: "Time Stopped",
    Timers: "Timers",
    Timings: "Timings",
    TimingsMap: "Timings Map",
    title_Activity: "Activity",
    title_ActivePermissions: "Active Permissions",
    title_ActiveGroupPermissions: "Active Group Permissions",
    title_AvailablePermissions: "Available Permissions",
    title_AvailableGroupPermissions: "Available Group Permissions",
    title_ClusterInfo: "Groups",
    title_CodeGeneratorPermissions: "Code Generator Permissions",
    title_DirectoriesFor: "Directories for",
    title_DESDL: "Dynamic ESDL",
    title_DFUQuery: "Logical Files",
    title_DFUWUDetails: "DFU Workunit",
    title_DiskUsage: "Disk Usage",
    title_ECLPlayground: "ECL Playground",
    title_ErrorsWarnings: "Errors/Warnings for",
    title_EventScheduleWorkunit: "Event Scheduler",
    title_FileScopeDefaultPermissions: "Default permissions of files",
    title_FilesPendingCopy: "Files pending copy",
    title_FoundFilesFor: "Found files for",
    title_GetDFUWorkunits: "DFU Workunits",
    title_Graph: "Graph",
    title_GraphPage: "title",
    title_Graphs: "Graphs",
    title_GridDetails: "Change Me",
    title_HPCCPlatformECL: "ECL Watch - Home",
    title_HPCCPlatformFiles: "ECL Watch - Files",
    title_HPCCPlatformMain: "ECL Watch - Home",
    title_HPCCPlatformOps: "ECL Watch - Operations",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
    title_Inputs: "Inputs",
    title_Log: "Log File",
    title_LFDetails: "Logical File Details",
    title_LZBrowse: "Landing Zones",
    title_MemberOf: "Member Of",
    title_Members: "Members",
    title_LostFilesFor: "Lost files for",
    title_LibrariesUsed: "Libraries Used",
    title_OrphanFilesFor: "Orphan files for",
    title_Permissions: "Permissions",
    title_QuerySetDetails: "Query Details",
    title_QuerySetErrors: "Errors",
    title_QuerySetLogicalFiles: "Logical Files",
    title_QuerySetQuery: "Queries",
    title_QuerySetSuperFiles: "Super Files",
    title_QueryTest: "Super Files",
    title_Result: "Activity",
    title_Results: "Outputs",
    title_PreflightResults: "Preflight Results",
    title_SearchResults: "Search Results",
    title_SourceFiles: "",
    title_Topology: "Topology",
    title_TpThorStatus: "Thor Status",
    title_UserQuery: "Permissions",
    title_UserPermissions: "User Permissions",
    title_WUDetails: "ECL Workunit Details",
    title_WorkunitScopeDefaultPermissions: "Default permissions of workunits",
    title_WUQuery: "ECL Workunits",
    To: "To",
    ToDate: "To Date",
    Toenablegraphviews: "To enable graph views, please install the Graph View Control plugin",
    Tooltip: "Tooltip",
    TooManyFiles: "Too many files",
    Top: "Top",
    Topology: "Topology",
    ToSizes: "To Sizes",
    TotalParts: "Total Parts",
    TotalSize: "Total Size",
    TotalClusterTime: "Total Cluster Time",
    TransitionGuide: "Transition Guide",
    Text: "Text",
    Tree: "Tree",
    Type: "Type",
    undefined: "undefined",
    Unknown: "Unknown",
    Unprotect: "Unprotect",
    UnsupportedIE9FF: "Unsupported (IE <= 9, FireFox)",
    Unsuspend: "Unsuspend",
    Unsuspended: "Unsuspended",
    Up: "Up",
    UpdateSuperFiles: "Update Super Files",
    Upload: "Upload",
    URL: "URL",
    Usage: "Usage",
    Used: "Used",
    User: "User",
    UserDetails: "User Details",
    UserID: "User ID",
    Username: "Username",
    UserName: "User Name",
    UserPermissions: "User Permissions",
    Users: "Users",
    UseSingleConnection: "Use Single Connection",
    Validate: "Validate",
    ValidateActivePackageMap: "Validate Active Package Map",
    ValidatePackageContent: "Validate Package Content",
    ValidatePackageMap: "Validate Package Map",
    ValidateResult: "=====Validate Result=====\n\n",
    ValidateResultHere: "(Validation result)",
    Value: "Value",
    Variable: "Variable",
    Variables: "Variables",
    VariableBigendian: "Variable Big-endian",
    VariableSourceType: "Source Type",
    Version: "Version",
    ViewByScope: "View By Scope",
    Views: "Views",
    Visualize: "Visualize",
    Warning: "Warning",
    Warnings: "Warning(s)",
    WarnIfCPUUsageIsOver: "Warn if CPU usage is over",
    WarnIfAvailableMemoryIsUnder: "Warn if available memory is under",
    WarnIfAvailableDiskSpaceIsUnder: "Warn if available disk space is under",
    WarnOldGraphControl: "Warning:  Old Graph Control",
    What: "What",
    Where: "Where",
    Who: "Who",
    Width: "Width",
    Workflows: "Workflows",
    Workunit: "Workunit",
    Workunits: "Workunits",
    WorkUnitScopeDefaultPermissions: "Workunit Scope Default Permissions",
    Wrap: "Wrap",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Cannot Be Empty.",
    WUSnapShot: "WU Snap Shot",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Year",
    YouAreAboutToRemoveUserFrom: "You are about to remove a user(s) from this group. Do you wish to continue?",
    YouAreAboutToDeleteBinding: "You are about to delete this binding. Are you sure you want to do this?",
    YouAreAboutToDeleteThisFile: "You are about to delete this file. Are you sure you want to do this?",
    YouAreAboutToDeleteThisQueryset: "You are about to delete this query set. Are you sure you want to do this?",
    YouAreAboutToDeleteThisWorkunit: "You are about to delete this workunit. Are you sure you want to do this?",
    YourBrowserMayNotSupport: "Your browser may not support file(s) of this size",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Zipped Analysis Package",
    Zoom: "Zoom",
    Zoom100Pct: "Zoom 100%",
    ZoomAll: "Zoom All",
    ZoomWidth: "Zoom Width"
}),
"bs": true,
"es": true,
"hu": true,
"hr": true,
"pt-br": true,
"sr": true,
"zh": true
});