define({root:
({
    Abort: "Abort",
    About: "About",
    AboutGraphControl: "About Graph Control",
    AboutHPCCSystemsGraphControl: "About HPCC Systems Graph Control",
    Action: "Action",
    Activate: "Activate",
    Activated: "Activated",
    Active: "Active",
    ActivePackageMap: "Active Package Map",
    ActiveWorkunit: "Active Workunit",
    Activities: "Activities",
    Activity: "Activity",
    ActualSize: "Actual Size",
    Add: "Add",
    AddFile: "Add File",
    AddGroup: "Add Group",
    AdditionalResources: "Additional Resources",
    AddProcessMap: "Add Package Map",
    AddToSuperfile: "Add To Superfile",
    AddUser: "Add User",
    Advanced: "Advanced",
    All: "All",
    AllowAccess: "<center>Allow<br>Access</center>",
    AllowForeignFiles: "Allow Foreign Files",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    ANY: "ANY",
    Append: "Append",
    Apply: "Apply",
    ArchivedOnly: "Archived Only",
    ArchivedWarning: "Warning: please specify a small date range. If not, it may take some time to retrieve the workunits and the browser may be timed out.",
    BinaryInstalls: "Binary Installs",
    AutoRefresh: "Auto Refresh",
    Back: "Back",
    BannerColor: "Banner Colour",
    BannerMessage: "Banner Message",
    BannerScroll: "Banner Scroll",
    BannerSize: "Banner Size",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefix",
    Bottom: "Bottom",
    Cancel: "Cancel",
    Clear: "Clear",
    Clone: "Clone",
    Close: "Close",
    Cluster: "Cluster",
    ClusterName: "Cluster Name",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Cluster Processes",
    Code: "Code",
    CodeGenerator: "Code Generator",
    Col: "Col",
    CollapseAll: "Collapse All",
    Command: "Command",
    Comment: "Comment",
    Completed: "Completed",
    ComplexityWarning: "More than {threshold} activities ({activityCount}) - suppress initial display?",
    CompressedFileSize: "Compressed File Size",
    Component: "Component",
    Compress: "Compress",
    Compressed: "Compressed",
    Configuration: "Configuration",
    ConfirmPassword: "Confirm Password",
    ConfirmRemoval: "Are you sure you want to do this?",
    Content: "Content",
    Contents: "Contents",
    ContentType: "Content Type",
    Copy: "Copy",
    Count: "Count",
    Created: "Created",
    ClearPermissionsCache: "Clear Permissions Cache",
    ClearPermissionsCacheConfirm: "Are you sure you want to clear the DALI and ESP permissions caches? Running workunit performance might degrade significantly until the caches have been refreshed.",
    ClonedWUID: "Cloned WUID",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Date",
    Day: "Day",
    Deactivate: "Deactivate",
    Debug: "Debug",
    DEF: "DEF",
    Delete: "Delete",
    Deleted: "Deleted",
    DeleteSelectedFiles: "Delete Selected Files?",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedPermissions: "Delete selected permission(s)?",
    DeleteSelectedQueries: "Delete Selected Queries?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DeleteSelectedWorkunits: "Delete Selected Workunits?",
    DeleteSuperfile: "Delete Superfile?",
    DeleteSuperfile2: "Delete Superfile",
    DeleteThisPackage: "Delete this package?",
    Delimited: "Delimited",
    DenyAccess: "<center>Deny<br>Access</center>",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Depth: "Depth",
    DepthTooltip: "Maximum Subgraph Depth",
    Deschedule: "Deschedule",
    DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
    Description: "Description",
    Despray: "Despray",
    Details: "Details",
    DFUServerName: "DFU Server Name",
    DFUWorkunit: "DFU Workunit",
    Directory: "Directory",
    DisableScopeScans: "Disable Scope Scans",
    DisableScopeScanConfirm: "Are you sure you want to disable Scope Scans?  Changes will revert to configuration settings on DALI reboot.",
    DiskUsage: "Disk Usage",
    Distance: "Distance",
    DistanceTooltip: "Maximum Activity Neighbourhood Distance",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Attributes",
    Down: "Down",
    Download: "Download",
    DropZone: "Drop Zone",
    Duration: "Duration",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "ECL Workunit",
    Edges: "Edges",
    Edit: "Edit",
    EditDOT: "Edit DOT",
    EditGraphAttributes: "Edit Graph Attributes",
    EditXGMML: "Edit XGMML",
    Empty: "(Empty)",
    Enable: "Enable",
    EnableScopeScans: "Enable Scope Scans",
    EnableScopeScansConfirm: "Are you sure you want to enable Scope Scans? Changes will revert to configuration settings on DALI reboot.",
    EnglishQ: "English?",
    Error: "Error",
    Errorparsingserverresult: "Error parsing server result",
    Errors: "Error(s)",
    ErrorsStatus: "Errors/Status",
    ErrorWarnings: "Error/Warning(s)",
    Escape: "Escape",
    ESPBuildVersion: "ESP Build Version",
    ESPNetworkAddress: "ESP Network Address",
    EventName: "Event Name",
    EventNamePH: "Event Name",
    EventScheduler: "Event Scheduler",
    EventText: "Event Text",
    EventTextPH: "Event Text",
    Exception: "Exception",
    FailIfNoSourceFile:"Fail If No Source File",
    FetchingData: "Fetching Data...",
    fetchingresults: "fetching results",
    ExpandAll: "Expand All",
    Export: "Export",
    File: "File",
    FileCounts: "File Counts",
    FileName: "File Name",
    FileParts: "File Parts",
    FilePath: "File Path",
    Files: "Files",
    FileScopes: "File Scopes",
    FileSize: "File Size",
    FilesNoPackage: "Files without matching package definitions",
    FilesWithUnknownSize: "Files With Unknown Size",
    FileType: "File Type",
    FileUploader: "File Uploader",
    FileUploadStillInProgress: "File upload still in progress",
    Filter: "Filter",
    Find: "Find",
    Finished: "Finished",
    FindNext: "Find Next",
    FindPrevious: "Find Previous",
    FirstName: "First Name",
    FirstNRows: "First N Rows",
    Fixed: "Fixed",
    Folder: "Folder",
    Format: "Format",
    Forward: "Forward",
    FromDate: "From Date",
    FromSizes: "From Sizes",
    FromTime: "From Time",
    FullName: "Full Name",
    Graph: "Graph",
    Graphs: "Graphs",
    GraphView: "Graph View",
    Group: "Group",
    GroupBy: "Group By",
    Grouping: "Grouping",
    GroupDetails: "Group Details",
    GroupName: "Group Name",
    GroupPermissions: "Group Permissions",
    Groups: "Groups",
    GZip: "GZip",
    help: "This area displays the treemap for the graph(s) in this workunit. The size and hue indicate the duration of each graph (Larger and darker indicates a greater percentage of the time taken.)",
    Helpers: "Helpers",
    Hex: "Hex",
    High: "High",
    History: "History",
    HPCCSystems: "HPCC Systems",
    ID: "ID",
    Inactive: "Inactive",
    Index: "Index",
    Info: "Info",
    InfoDialog: "Info Dialog",
    Inputs: "Inputs",
    InvalidResponse: "(Invalid response)",
    IP: "IP",
    IPAddress: "IP Address",
    IsLibrary: "Is Library",
    IsReplicated: "Is Replicated",
    Jobname: "Jobname",
    JobName: "Job Name",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Label",
    LandingZone: "Landing Zone",
    LandingZones: "Landing Zones",
    LanguageFiles: "Language Files",
    Largest: "Largest",
    LargestFile: "Largest File",
    LargestSize: "Largest Size",
    LastName: "Last Name",
    LastNDays: "Last N Days",
    LastNHours: "Last N Hours",
    LastNRows: "Last N Rows",
    LegacyForm: "Legacy Form",
    LDAPWarning: "<b>LDAP Services Error:</b>  'Too Many Users' - Please use a Filter.",
    LibrariesUsed: "Libraries Used",
    LibraryName: "Library Name",
    Line: "Line",
    LineTerminators: "Line Terminators",
    Links: "Links",
    LoadPackageContentHere: "(Load package content here)",
    LoadPackageFromFile: "Load Package from a file",
    Loading: "Loading...",
    LoadingCachedLayout: "Loading Cached Layout...",
    LoadingData: "Loading Data...",
    loadingMessage: "...Loading...",
    Local: "Local",
    LogFile: "Log File",
    LoggedInAs: "Logged in as",
    LogicalFile: "Logical File",
    LogicalFiles: "Logical Files",
    LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
    LogicalFilesOnly: "Logical Files Only",
    LogicalFileType: "Logical File Type",
    LogicalName: "Logical Name",
    Log: "Log",
    Logs: "Logs",
    log_analysis_1: "log_analysis_1*",
    Low: "Low",
    ManualCopy: "Press Ctrl+C",
    ManualOverviewSelection: "(Manual overview selection will be required)",
    ManualTreeSelection: "(Manual tree selection will be required)",
    Mappings: "Mappings",
    Mask: "Mask",
    Max: "Max",
    MaxRecordLength: "Max Record Length",
    MemberOf: "Member Of",
    Members: "Members",
    Message: "Message",
    Min: "Min",
    Missing: "Missing",
    MixedNodeStates: "Mixed Node States",
    Modified: "Modified",
    Modification: "Modification",
    ModifiedUTCGMT: "Modified (UTC/GMT)",
    Modify: "Modify",
    MonitorEventName: "Monitor Event Name",
    MonitorShotLimit: "Monitor Shot Limit",
    MonitorSub: "Monitor Sub",
    Month: "Month",
    More: "more",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    NA: "N/A",
    Name: "Name",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Newest",
    NewPassword: "New Password",
    NoContent: "(No content)",
    noDataMessage: "...Zero Rows...",
    Node: "Node",
    NodeGroup: "Node Group",
    None: "None",
    NoErrorFound: "No errors found\n",
    NoFilterCriteriaSpecified: "No filter criteria specified.",
    NoScheduledEvents: "No Scheduled Events.",
    NoSplit: "No Split",
    NotActive: "Not active",
    NothingSelected: "Nothing Selected...",
    NotInSuperfiles: "Not in Superfiles",
    Normal: "Normal",
    NotSuspendedbyUser: "Not Suspended By User",
    NoWarningFound: "No warnings found\n",
    NumberofParts: "Number of Parts",
    OK: "OK",
    Oldest: "Oldest",
    OldPassword: "Old Password",
    OmitSeparator: "Omit Separator",
    Only1PackageFileAllowed: "Only one package file allowed",
    Open: "Open",
    OpenInNewPage: "Open in New Page",
    OpenInNewPageNoFrame: "Open in New Page (No Frame)",
    OpenLegacyECLWatch: "Open Legacy ECL Watch",
    OpenSafeMode: "Open (safe mode)",
    OpenTreeMode: "Open (tree mode)",
    OpenSource: "Open Source",
    Operations: "Operations",
    Options: "Options",
    Outputs: "Outputs",
    Overview: "Overview",
    Overwrite: "Overwrite",
    OverwriteMessage: "Some file(s) already exist. Please check overwrite box to continue.",
    Owner: "Owner",
    PackageContent: "Package Content",
    PackageContentNotSet: "Package content not set",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Packages without matching queries",
    ParameterXML: "Parameter XML",
    Part: "Part",
    Parts: "Parts",
    Password: "Password",
    PasswordExpiration: "Password Expiration",
    PasswordOpenZAP: "Password to open ZAP (optional)",
    PasswordsDoNotMatch: "Passwords do not match.",
    PasswordExpired: "Your password has expired.  Please change now.",
    PasswordExpirePrefix: "Your password will expire in ",
    PasswordExpirePostfix: " day(s). Do you want to change it now?",
    Path: "Path",
    PathMask: "Path Mask",
    Pause: "Pause",
    PauseNow: "Pause Now",
    PctComplete: "% Complete",
    PercentDone: "Percent Done",
    PerformingLayout: "Performing Layout...",
    PermissionName: "Permission Name",
    Permissions: "Permissions",
    PlaceholderFindText: "Wuid, User, (ecl:*, file:*, dfu:*, query:*)...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Playground",
    Plugins: "Plugins",
    Port: "Port",
    Prefix: "Prefix",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    PreserveCompression: "Preserve Compression",
    Preview: "Preview",
    Priority: "Priority",
    Process: "Process",
    ProcessFilter: "Process Filter",
    ProgressMessage: "Progress Message",
    Properties: "Properties",
    Property: "Property",
    Protect: "Protect",
    Protected: "Protected",
    Publish: "Publish",
    Published: "Published",
    PublishedBy: "Published By",
    PublishedQueries: "Published Queries",
    PushEvent: "Push Event",
    Quarter: "Quarter",
    Queries: "Queries",
    QueriesNoPackage: "Queries without matching package",
    Query: "Query",
    QueryDetailsfor: "Query Details for",
    QueryID: "Query ID",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Query Name",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Query Set",
    Queue: "Queue",
    Quote: "Quote",
    QuotedTerminator: "Quoted Terminator",
    RawTextPage: "Raw Text (Current Page)",
    RecordCount: "Record Count",
    RecordLength: "Record Length",
    Records: "Records",
    RecordSize: "Record Size",
    RecordStructurePresent: "Record Structure Present",
    Recover: "Recover",
    Refresh: "Refresh",
    ReleaseNotes: "Release Notes",
    Reload: "Reload",
    Remaining: "Remaining",
    RemoteCopy: "Remote Copy",
    RemoteDali: "Remote Dali",
    RemoteDaliIP: "Remote Dali IP Address",
    Remove: "Remove",
    RemoveSubfiles: "Remove Subfile(s)",
    RemoveUser: "You are about to remove yourself from the group:",
    Rename: "Rename",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Render SVG",
    Replicate: "Replicate",
    RequestSchema: "Request Schema",
    Reschedule: "Reschedule",
    Reset: "Reset",
    ResetThisQuery: "Reset This Query?",
    ResetViewToSelection: "Reset View to Selection",
    Resource: "Resource",
    Resources: "Resources",
    ResponseSchema: "Response Schema",
    Restart: "Restart",
    Restarted: "Restarted",
    Restore: "Restore",
    Resubmit: "Resubmit",
    Resubmitted: "Resubmitted",
    Results: "Result(s)",
    Resume: "Resume",
    RetainSuperfileStructure: "Retain Superfile Structure",
    RetypePassword: "Retype Password",
    Reverse: "Reverse",
    Rows: "Rows",
    RowPath: "Row Path",
    RowTag: "Row Tag",
    RoxieCluster: "Roxie Cluster",
    Sample: "Sample",
    SampleRequest: "Sample Request",
    SampleResponse: "Sample Response",
    Save: "Save",
    Scope: "Scope",
    SearchResults: "Search Results",
    SecondsRemaining: "Seconds Remaining",
    Security: "Security",
    SelectPackageFile: "Select Package File",
    Separators: "Separators",
    SetBanner: "Set Banner",
    SetTextError: "Failed to display text (too large?).  Use 'helpers' to download.",
    SetToFailed: "Set To Failed",
    Severity: "Severity",
    Show: "Show",
    ShowSVG: "Show SVG",
    Size: "Size",
    Skew: "Skew",
    SLA: "SLA",
    Slaves: "Slaves",
    Smallest: "Smallest",
    SmallestFile: "Smallest File",
    SmallestSize: "Smallest Size",
    SOAP: "SOAP",
    SomeDescription: "Some*Description",
    somefile: "*::somefile*",
    Source: "Source",
    SourceCode: "Source Code",
    SourcePath: "Source Path (Wildcard Enabled)",
    SourceProcess: "Source Process",
    SplitPrefix: "Split Prefix",
    Spray: "Spray",
    Start: "Start",
    Started: "Started",
    State: "State",
    Status: "Status",
    Stats: "Stats",
    Stopped: "Stopped",
    Subgraph: "Subgraph",
    Subgraphs: "Subgraphs",
    Submit: "Submit",
    Subtype: "Subtype",
    Summary: "Summary",
    SummaryMessage: "Summary Message",
    Superfile: "Superfile",
    Superfiles: "Superfiles",
    SuperFile: "Super File",
    SuperFiles: "Super Files",
    SuperFilesBelongsTo: "Member of Superfile(s)",
    SuperfilesOnly: "Superfiles Only",
    Suspend: "Suspend",
    Suspended: "Suspended",
    SuspendedBy: "Suspended By",
    SuspendedByCluster: "Suspended By Cluster",
    SuspendedByUser: "Suspended By User",
    SuspendedReason: "Suspended Reason",
    SVGSource: "SVG Source",
    SyncSelection: "Sync To Selection",
    SystemServers: "System Servers",
    tag: "tag",
    Target: "Target",
    TargetClusters: "Target Clusters",
    TargetName: "Target Name",
    TargetNamePlaceholder: "some::logical::name",
    TargetWuid: "Target/Wuid",
    Terminators: "Terminators",
    TestPages: "Test Pages",
    ThorNetworkAddress: "Thor Network Address",
    ThorMasterAddress: "Thor Master Address",
    Time: "Time",
    TimeSeconds: "Time (Seconds)",
    TimeStarted: "Time Started",
    TimeStopped: "Time Stopped",
    Timers: "Timers",
    Timings: "Timings",
    TimingsMap: "Timings Map",
    title_Activity: "Activity",
    title_ClusterInfo: "Groups",
    title_DFUQuery: "Logical Files",
    title_DFUWUDetails: "DFU Workunit",
    title_DiskUsage: "Disk Usage",
    title_ECLPlayground: "ECL Playground",
    title_EventScheduleWorkunit: "Event Scheduler",
    title_GetDFUWorkunits: "DFU Workunits",
    title_Graph: "Graph",
    title_GraphPage: "title",
    title_Graphs: "Graphs",
    title_GridDetails: "Change Me",
    title_HPCCPlatformECL: "ECL Watch - Home",
    title_HPCCPlatformFiles: "ECL Watch - Files",
    title_HPCCPlatformMain: "ECL Watch - Home",
    title_HPCCPlatformOps: "ECL Watch - Operations",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
    title_Inputs: "Inputs",
    title_Log: "Log File",
    title_LFDetails: "Logical File Details",
    title_LZBrowse: "Landing Zones",
    title_MemberOf: "Member Of",
    title_Members: "Members",
    title_LibrariesUsed: "Libraries Used",
    title_QuerySetDetails: "Query Details",
    title_QuerySetErrors: "Errors",
    title_QuerySetLogicalFiles: "Logical Files",
    title_QuerySetQuery: "Queries",
    title_QuerySetSuperFiles: "Super Files",
    title_QueryTest: "Super Files",
    title_Result: "Activity",
    title_Results: "Outputs",
    title_SearchResults: "Search Results",
    title_SourceFiles: "",
    title_Topology: "Topology",
    title_TpThorStatus: "Thor Status",
    title_UserQuery: "Permissions",
    title_UserPermissions: "User Permissions",
    title_WUDetails: "ECL Workunit Details",
    title_WUQuery: "ECL Workunits",
    To: "To",
    ToDate: "To Date",
    Toenablegraphviews: "To enable graph views, please install the Graph View Control plugin",
    Top: "Top",
    Topology: "Topology",
    ToSizes: "To Sizes",
    TotalSize: "Total Size",
    TotalClusterTime: "Total Cluster Time",
    TransitionGuide: "Transition Guide",
    Text: "Text",
    Tree: "Tree",
    Type: "Type",
    undefined: "undefined",
    Unknown: "Unknown",
    Unprotect: "Unprotect",
    UnsupportedIE9FF: "Unsupported (IE <= 9, FireFox)",
    Unsuspend: "Unsuspend",
    Unsuspended: "Unsuspended",
    Up: "Up",
    Upload: "Upload",
    Usage: "Usage",
    Used: "Used",
    User: "User",
    UserDetails: "User Details",
    UserID: "User ID",
    Username: "Username",
    UserName: "User Name",
    UserPermissions: "User Permissions",
    Users: "Users",
    UseSingleConnection: "Use Single Connection",
    Validate: "Validate",
    ValidateActivePackageMap: "Validate Active Package Map",
    ValidatePackageContent: "Validate Package Content",
    ValidatePackageMap: "Validate Package Map",
    ValidateResult: "=====Validate Result=====\n\n",
    ValidateResultHere: "(Validation result)",
    Value: "Value",
    Variable: "Variable",
    Variables: "Variables",
    VariableBigendian: "Variable Big-endian",
    VariableSourceType: "Source Type",
    Version: "Version",
    ViewByScope: "View By Scope",
    Views: "Views",
    Visualize: "Visualize",
    Warnings: "Warning(s)",
    WarnOldGraphControl: "Warning:  Old Graph Control",
    What: "What",
    Where: "Where",
    Who: "Who",
    Width: "Width",
    Workflows: "Workflows",
    Workunit: "Workunit",
    Workunits: "Workunits",
    Wrap: "Wrap",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Cannot Be Empty.",
    WUSnapShot: "WU Snap Shot",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Year",
    YourBrowserMayNotSupport: "Your browser may not support file(s) of this size",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Zipped Analysis Package",
    Zoom: "Zoom",
    Zoom100Pct: "Zoom 100%",
    ZoomAll: "Zoom All",
    ZoomWidth: "Zoom Width"
}),
"bs": true,
"es": true,
"hu": true,
"hr": true,
"pt-br": true,
"sr": true,
"zh": true
});
