define({root:
({
    Abort: "Abort",
    About: "About",
    AboutGraphControl: "About Graph Control",
    AboutHPCCSystemsGraphControl: "About HPCC Systems Graph Control",
    Action: "Action",
    Activate: "Activate",
    Activated: "Activated",
    Active: "Active",
    ActivePackageMap: "Active Package Map",
    ActiveWorkunit: "Active Workunit",
    Activities: "Activities",
    Activity: "Activity",
    ActualSize: "Actual Size",
    Add: "Add",
    AddGroup: "Add Group",
    AdditionalResources: "Additional Resources",
    AddProcessMap: "Add Package Map",
    AddToSuperfile: "Add To Superfile",
    AddUser: "Add User",
    Advanced: "Advanced",
    All: "All",
    AllowAccess: "<center>Allow<br>Access",
    AllowForeignFiles: "Allow Foreign Files",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    ANY: "ANY",
    Append: "Append",
    Apply: "Apply",
    ArchivedOnly: "Archived Only",
    ArchivedWarning: "Warning: please specify a small date range. If not, it may take some time to retrieve the workunits and the browser may be timed out.",
    BinaryInstalls: "Binary Installs",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefix",
    Cancel: "Cancel",
    Clear: "Clear",
    Clone: "Clone",
    Close: "Close",
    Cluster: "Cluster",
    ClusterName: "Cluster Name",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Cluster Processes",
    Code: "Code",
    Col: "Col",
    Command: "Command",
    Comment: "Comment",
    Completed: "Completed",
    Component: "Component",
    Compress: "Compress",
    Configuration: "Configuration",
    ConfirmPassword: "Confirm Password",
    Contents: "Contents",
    ContentType: "Content Type",
    Copy: "Copy",
    Count: "Count",
    Created: "Created",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Date",
    Day: "Day",
    Deactivate: "Deactivate",
    Debug: "Debug",
    DEF: "DEF",
    Delete: "Delete",
    DeleteSelectedFiles: "Delete Selected Files?",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedQueries: "Delete Selected Queries?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DeleteSelectedWorkunits: "Delete Selected Workunits?",
    DeleteSuperfile: "Delete Superfile?",
    DeleteThisPackage: "Delete this package?",
    Delimited: "Delimited",
    DenyAccess: "<center>Deny<br>Access",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Depth: "Depth",
    Deschedule: "Deschedule",
    DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
    Description: "Description",
    Despray: "Despray",
    Details: "Details",
    DFUServerName: "DFU Server Name",
    Directory: "Directory",
    DiskUsage: "Disk Usage",
    Distance: "Distance",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Attributes",
    Download: "Download",
    DropZone: "Drop Zone",
    Duration: "Duration",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "Edges",
    Edit: "Edit",
    EditDOT: "Edit DOT",
    EditGraphAttributes: "Edit Graph Attributes",
    EditXGMML: "Edit XGMML",
    Empty: "(Empty)",
    EnglishQ: "English?",
    Error: "Error",
    Errorparsingserverresult: "Error parsing server result",
    Errors: "Error(s)",
    Errors: "Errors",
    ErrorsStatus: "Errors/Status",
    ErrorWarnings: "Error/Warning(s)",
    Escape: "Escape",
    ESPBuildVersion: "ESP Build Version",
    ESPNetworkAddress: "ESP Network Address",
    EventName: "Event Name",
    EventNamePH: "eventname",
    EventScheduler: "Event Scheduler",
    EventText: "Event Text",
    Exception: "Exception",
    FailIfNoSourceFile:"Fail If No Source File",
    FetchingData: "Fetching Data...",
    fetchingresults: "fetching results",
    File: "File",
    FileCounts: "File Counts",
    FileName: "File Name",
    FileParts: "File Parts",
    FilePath: "File Path",
    Files: "Files",
    FileSize: "File Size",
    FilesNoPackage: "Files without matching package definitions",
    FilesWithUnknownSize: "Files With Unknown Size",
    FileType: "File Type",
    FileUploader: "File Uploader",
    Filter: "Filter",
    Find: "Find",
    FindNext: "Find Next",
    FindPrevious: "Find Previous",
    FirstName: "First Name",
    Fixed: "Fixed",
    Format: "Format",
    FromDate: "From Date",
    FromSizes: "From Sizes",
    FullName: "Full Name",
    Graphs: "Graphs",
    GraphView: "Graph View",
    Group: "Group",
    GroupBy: "Group By",
    Grouping: "Grouping",
    GroupDetails: "Group Details",
    GroupName: "Group Name",
    GroupPermissions: "Group Permissions",
    Groups: "Groups",
    GZip: "GZip",
    help: "This area displays the treemap for the graph(s) in this workunit. The size and hue indicate the duration of each graph (Larger and darker indicates a greater percentage of the time taken.)",
    Helpers: "Helpers",
    Hex: "Hex",
    High: "High",
    History: "History",
    HPCCSystems: "HPCC Systems",
    ID: "ID",
    Import: "Import",
    Inactive: "Inactive",
    Info: "Info",
    InfoDialog: "Info Dialog",
    Inputs: "Inputs",
    InvalidResponse: "(Invalid response)",
    IP: "IP",
    IPAddress: "IP Address",
    IsLibrary: "Is Library",
    Jobname: "Jobname",
    JobName: "Job Name",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Label",
    LandingZone: "Landing Zone",
    LandingZones: "Landing Zones",
    LanguageFiles: "Language Files",
    Largest: "Largest",
    LargestFile: "Largest File",
    LargestSize: "Largest Size",
    LastName: "Last Name",
    LastNDays: "Last N Days",
    LegacyForm: "Legacy Form",
    LibrariesUsed: "Libraries Used",
    Line: "Line",
    LineTerminators: "Line Terminators",
    Links: "Links",
    Loading: "Loading...",
    LoadingCachedLayout: "Loading Cached Layout...",
    LoadingData: "Loading Data...",
    loadingMessage: "...Loading...",
    Local: "Local",
    LoggedInAs: "Logged in as",
    LogicalFile: "Logical File",
    LogicalFiles: "Logical Files",
    LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
    LogicalFilesOnly: "Logical Files Only",
    LogicalFileType: "Logical File Type",
    LogicalName: "Logical Name",
    log_analysis_1: "log_analysis_1*",
    Low: "Low",
    ManualCopy: "Press Ctrl+C",
    Mappings: "Mappings",
    Mask: "Mask",
    Max: "Max",
    MaxRecordLength: "Max Record Length",
    MemberOf: "Member Of",
    Members: "Members",
    Message: "Message",
    Min: "Min",
    Missing: "Missing",
    Modified: "Modified",
    Modification: "Modification",
    ModifiedUTCGMT: "Modified (UTC/GMT)",
    Modify: "Modify",
    MonitorEventName: "Monitor Event Name",
    MonitorShotLimit: "Monitor Shot Limit",
    MonitorSub: "Monitor Sub",
    Month: "Month",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    NA: "N/A",
    Name: "Name",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Newest",
    NewPassword: "New Password",
    NoContent: "(No content)",
    noDataMessage: "...Zero Rows...",
    Node: "Node",
    None: "None",
    NoErrorFound: "No errors found\n",
    NoFilterCriteriaSpecified: "No filter criteria specified.",
    NoScheduledEvents: "No Scheduled Events.",
    NoSplit: "No Split",
    NotActive: "Not active",
    NothingSelected: "Nothing Selected...",
    NotInSuperfiles: "Not in Superfiles",
    NotSuspendedbyUser: "Not Suspended By User",
    NoWarningFound: "No warnings found\n",
    NumberofParts: "Number of Parts",
    OK: "OK",
    Oldest: "Oldest",
    OmitSeparator: "Omit Separator",
    Only1PackageFileAllowed: "Only one package file allowed",
    Open: "Open",
    OpenInNewPage: "Open in New Page",
    OpenLegacyECLWatch: "Open Legacy ECL Watch",
    OpenSafeMode: "Open (safe mode)",
    Operations: "Operations",
    Options: "Options",
    Outputs: "Outputs",
    Overview: "Overview",
    Overwrite: "Overwrite",
    Owner: "Owner",
    PackageContent: "Package Content",
    PackageContentNotSet: "Package content not set",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Packages without matching queries",
    ParameterXML: "Parameter XML",
    Parts: "Parts",
    Password: "Password",
    PasswordExpiration: "Password Expiration",
    PasswordsDoNotMatch: "Passwords do not match.",
    Path: "Path",
    PathMask: "Path Mask",
    PctComplete: "% Complete",
    PercentDone: "Percent Done",
    PerformingLayout: "Performing Layout...",
    Permissions: "Permissions",
    PlaceholderFindText: "Wuid, User, (ecl:*, file:*, dfu:*)...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Playground",
    Prefix: "Prefix",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preview: "Preview",
    Priority: "Priority",
    Process: "Process",
    ProcessFilter: "Process Filter",
    ProgressMessage: "Progress Message",
    Properties: "Properties",
    Property: "Property",
    Protect: "Protect",
    Protected: "Protected",
    Publish: "Publish",
    PublishedBy: "Published By",
    PublishedQueries: "Published Queries",
    Quarter: "Quarter",
    Queries: "Queries",
    QueriesNoPackage: "Queries without matching package",
    QueryDetailsfor: "Query Details for",
    QuerySet: "Query Set",
    Queue: "Queue",
    Quote: "Quote",
    RecordCount: "Record Count",
    RecordLength: "Record Length",
    Records: "Records",
    RecordSize: "Record Size",
    RecordStructurePresent: "Record Structure Present",
    Refresh: "Refresh",
    ReleaseNotes: "Release Notes",
    Reload: "Reload",
    RemoteDali: "Remote Dali",
    RemoteDaliIP: "Remote Dali IP Address",
    Remove: "Remove",
    Rename: "Rename",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Render SVG",
    Replicate: "Replicate",
    RequestSchema: "Request Schema",
    Reschedule: "Reschedule",
    Reset: "Reset",
    Resource: "Resource",
    Resources: "Resources",
    ResponseSchema: "Response Schema",
    Restart: "Restart",
    Restore: "Restore",
    Resubmit: "Resubmit",
    Results: "Result(s)",
    RetainSuperfileStructure: "Retain Superfile Structure",
    RetypePassword: "Retype Password",
    Rows: "Rows",
    RowTag: "Row Tag",
    RoxieCluster: "Roxie Cluster",
    Sample: "Sample",
    SampleRequest: "Sample Request",
    SampleResponse: "Sample Response",
    Save: "Save",
    Scope: "Scope",
    SearchResults: "Search Results",
    SecondsRemaining: "Seconds Remaining",
    SelectPackageFile: "Select Package File",
    Seperators: "Seperators",
    SetBanner: "Set Banner",
    SetTextError: "Failed to display text (too large?).  Use 'helpers' to download.",
    SetToFailed: "Set To Failed",
    Severity: "Severity",
    Show: "Show",
    ShowSVG: "Show SVG",
    Size: "Size",
    Skew: "Skew",
    SLA: "SLA",
    Slaves: "Slaves",
    Smallest: "Smallest",
    SmallestFile: "Smallest File",
    SmallestSize: "Smallest Size",
    SOAP: "SOAP",
    SomeDescription: "Some*Description",
    somefile: "*::somefile*",
    Source: "Source",
    SourceCode: "Source Code",
    SourcePath: "Source Path (Wildcard Enabled)",
    SourceProcess: "Source Process",
    SplitPrefix: "Split Prefix",
    Spray: "Spray",
    Start: "Start",
    Started: "Started",
    State: "State",
    Stopped: "Stopped",
    Subgraphs: "Subgraphs",
    Submit: "Submit",
    Summary: "Summary",
    SummaryMessage: "Summary Message",
    SuperFile: "Super File",
    SuperFiles: "Super Files",
    SuperfilesOnly: "Superfiles Only",
    Suspend: "Suspend",
    Suspended: "Suspended",
    SuspendedBy: "Suspended By",
    SuspendedByUser: "Suspended By User",
    SuspendedReason: "Suspended Reason",
    SVGSource: "SVG Source",
    SyncSelection: "Sync To Selection",
    SystemServers: "System Servers",
    tag: "tag",
    Target: "Target",
    TargetClusters: "Target Clusters",
    TargetName: "Target Name",
    TargetNamePlaceholder: "some::logical::name",
    TargetWuid: "Target/Wuid",
    Terminators: "Terminators",
    TestPages: "Test Pages",
    ThorNetworkAddress: "Thor Network Address",
    Time: "Time",
    TimeSeconds: "Time (Seconds)",
    TimeStarted: "Time Started",
    TimeStopped: "Time Stopped",
    Timers: "Timers",
    Timings: "Timings",
    TimingsMap: "Timings Map",
    title_Activity: "Activity",
    title_DFUQuery: "Logical Files",
    title_DFUWUDetails: "DFU Workunit",
    title_DiskUsage: "Disk Usage",
    title_ECLPlayground: "ECL Playground",
    title_EventScheduleWorkunit: "Event Scheduler",
    title_GetDFUWorkunits: "DFU Workunits",
    title_Graph: "Graph",
    title_GraphPage: "title",
    title_Graphs: "Graphs",
    title_GridDetails: "Change Me",
    title_HPCCPlatformECL: "HPCC Platform - Home",
    title_HPCCPlatformFiles: "HPCC Platform - Files",
    title_HPCCPlatformMain: "HPCC Platform - Home",
    title_HPCCPlatformOps: "HPCC Platform - Operations",
    title_HPCCPlatformRoxie: "HPCC Platform - Roxie",
    title_Inputs: "Inputs",
    title_LFDetails: "Logical File Details",
    title_LZBrowse: "Landing Zones",
    title_MemberOf: "Member Of",
    title_Members: "Members",
    title_QuerySetDetails: "Query Details",
    title_QuerySetErrors: "Errors",
    title_QuerySetLogicalFiles: "Logical Files",
    title_QuerySetQuery: "Queries",
    title_QuerySetSuperFiles: "Super Files",
    title_QueryTest: "Super Files",
    title_Result: "Activity",
    title_Results: "Outputs",
    title_SearchResults: "Search Results",
    title_SourceFiles: "",
    title_UserQuery: "Permissions",
    title_UserPermissions: "User Permissions",
    title_WUDetails: "ECL Workunit Details",
    title_WUQuery: "ECL Workunits",
    ToDate: "To Date",
    Toenablegraphviews: "To enable graph views, please install the Graph View Control plugin",
    ToSizes: "To Sizes",
    TotalSize: "Total Size",
    TotalThorTime: "Total Thor Time",
    Tree: "Tree",
    Type: "Type",
    undefined: "undefined",
    Unknown: "Unknown",
    Unprotect: "Unprotect",
    Unsuspend: "Unsuspend",
    Unsuspended: "Unsuspended",
    Upload: "Upload",
    Used: "Used",
    User: "User",
    UserDetails: "User Details",
    UserID: "User ID",
    Username: "Username",
    UserName: "User Name",
    UserPermissions: "User Permissions",
    Users: "Users",
    UseSingleConnection: "Use Single Connection",
    Validate: "Validate",
    ValidatePackageMap: "Validate Package Map",
    ValidateResult: "=====Validate Result=====\n\n",
    Value: "Value",
    Variable: "Variable",
    Variables: "Variables",
    VariableBigendian: "Variable Big-endian",
    VariableSourceType: "Source Type",
    Version: "Version",
    Views: "Views",
    Visualize: "Visualize",
    Warnings: "Warning(s)",
    WarnOldGraphControl: "Warning:  Old Graph Control",
    What: "What",
    Where: "Where",
    Who: "Who",
    Width: "Width",
    Workunit: "Workunit",
    Workunits: "Workunits",
    Wrap: "Wrap",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Cannot Be Empty.",
    WUSnapShot: "WU Snap Shot",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Year",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Zipped Analysis Package",
    Zoom100Pct: "Zoom 100%",
    ZoomAll: "Zoom All",
    ZoomWidth: "Zoom Width"
}),
"bs": true,
"es": true,
"hu": true,
"hr": true,
"sr": true,
"zh": true
});
