define(
({
    title: "DFU工作单元",

    Abort: "终止",
    ClusterName: "计算机集群名",
    Command: "指令",
    Compress: "压缩",
    Dali: "Dali",
    DFUServerName: "DFU服务器名",
    Directory: "文件目录",
    Escape: "换码",
    FilePath: "文件路径",
    Format: "格式",
    GroupName: "组名",
    ID: "标识",
    IP: "IP",
    JobName: "任务名",
    LogicalName: "逻辑文件名",
    Modify: "修改",
    MonitorEventName: "监视事件名",
    MonitorShotLimit: "监视发射限制",
    MonitorSub: "监视子文件",
    NumberofParts: "文件分块数量",
    Overwrite: "覆盖",
    PercentDone: "任务完成%",
    ProgressMessage: "进展信息",
    Protected: "已保护",
    Queue: "队列",
    Quote: "引用",
    RecordSize: "记录长度",
    Replicate: "复制",
    Resubmit: "重新提交",
    RowTag: "行标记",
    SecondsRemaining: "剩余时间(秒)",
    Seperators: "分割符",
    Source: "文件源",
    State: "状态",
    Summary: "总结",
    SummaryMessage: "总结信息",
    Target: "目标",
    Terminators: "终止符",
    TimeStarted: "起始时间",
    TimeStopped: "终止时间",
    User: "用户"
})
);
