define(
({
    title: "标题",

    AboutGraphControl: "图形控制器简介",
    AboutHPCCSystemsGraphControl: "HPCC系统图形控制器简介",
    Activities: "活动",
    Advanced: "高级",
    Depth: "深度",
    Distance: "距离",
    DOT: "DOT",
    DOTAttributes: "DOT属性",
    ECL: "ECL",
    Edges: "连接",
    EditDOT: "编辑DOT",
    EditGraphAttributes: "编辑图形属性",
    EditXGMML: "编辑XGMML",
    FetchingData: "提取数据...",
    Find: "查找",
    FindNext: "查找下一个",
    FindPrevious: "查找前一个",
    ID: "标识",
    InfoDialog: "信息对话窗",
    Label: "标识",
    Local: "局部",
    Overview: "覆盖",
    PerformingLayout: "图形布局中...",
    Properties: "特性",
    RenderedSVG: "渲染的SVG",
    RenderSVG: "渲染SVG",
    ShowSVG: "显示SVG",
    Subgraphs: "子图",
    SVGSource: "SVG原始数据",
    Sync: "同步",
    Timings: "时间表",
    TimingsMap: "时间图",
    Version: "版本",
    XGMML: "XGMML"
})
);
