define(
({
    Abort: "终止",
    About: "本系统简介",
    AboutGraphControl: "图形控制器简介",
    AboutHPCCSystemsGraphControl: "HPCC系统图形控制器简介",
    Action: "操作",
    Activate: "激活",
    Activated: "已激活",
    Active: "已激活",
    ActivePackageMap: "Active Package Map",
    ActiveWorkunit: "工作单元",
    Activities: "活动",
    Activity: "活动",
    ActualSize: "实际长度",
    Add: "Add",
    Add: "添加",
    AddProcessMap: "Add Package Map",
    AddToSuperfile: "加入文件集",
    AddUser: "Add User",
    Advanced: "高级",
    AllowAccess: "<center>Allow<br>Access",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    ANY: "ANY",
    Append: "添加",
    Apply: "使用",
    ArchivedOnly: "仅限已存档的工作单元",
    BinaryInstalls: "安装图形控制器",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefix",
    Cancel: "撤消",
    Clear: "清除",
    Clone: "复制",
    Close: "关闭",
    Cluster: "计算机集群",
    ClusterName: "计算机集群名",
    ClusterName: "计算机集群名称",
    ClusterPH: "r?x*",
    ClusterProcesses: "计算机集群进程",
    Code: "代码",
    Col: "列",
    Command: "指令",
    Comment: "注释",
    Completed: "完成",
    Component: "组成部分",
    Compress: "压缩",
    ConfirmPassword: "Confirm Password",
    Contents: "内容",
    Copy: "复制",
    Count: "数量",
    Created: "已创建",
    Dali: "Dali",
    dataset: ":=数据集*",
    Date: "日期",
    Deactivate: "失效",
    DEF: "DEF",
    Delete: "删除",
    DeleteSelectedFiles: "删除所选择的文件?",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedQueries: "删除所选择的查询程序?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DeleteSelectedWorkunits: "删除所选择的工作单元?",
    DeleteSuperfile: "删除文件集?",
    DeleteThisPackage: "Delete this package?",
    Delimited: "定界的",
    DenyAccess: "<center>Deny<br>Access",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Depth: "深度",
    Deschedule: "取消运行计划",
    DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
    Description: "说明",
    Despray: "复合原文件",
    DFUServerName: "DFU服务器名",
    Directory: "文件目录",
    Distance: "距离",
    Dll: "动态联接库",
    DOT: "DOT",
    DOTAttributes: "DOT属性",
    Download: "下载",
    DropZone: "文件停放区",
    Duration: "时间段",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "连接",
    Edit: "Edit",
    EditDOT: "编辑DOT",
    EditGraphAttributes: "编辑图形属性",
    EditXGMML: "编辑XGMML",
    Empty: "(Empty)",
    Error: "错误",
    Errorparsingserverresult: "服务器结果解析错误",
    Errors: "Error(s)",
    Errors: "错误",
    ErrorsStatus: "错误状态",
    ErrorWarnings: "错误/警告",
    Escape: "换码",
    ESPBuildVersion: "ESP构建版本",
    ESPNetworkAddress: "ESP网址",
    EventName: "Event Name",
    EventNamePH: "eventname",
    EventScheduler: "事件计划",
    EventText: "Event Text",
    Exception: "Exception",
    FetchingData: "提取数据...",
    fetchingresults: "提取结果",
    File: "文件",
    FileName: "文件名称",
    FileParts: "文件分块",
    FilePath: "文件路径",
    Files: "文件",
    FileSize: "文件长度",
    FilesNoPackage: "Files without matching package definitions",
    FileType: "File Type",
    FileUploader: "文件上传",
    Filter: "过滤器",
    Find: "查找",
    FindNext: "查找下一个",
    FindPrevious: "查找前一个",
    FirstName: "First Name",
    Fixed: "定长的",
    Format: "格式",
    FromDate: "起始日期",
    FromSizes: "最小文件长度",
    FullName: "Full Name",
    Graphs: "图形",
    GraphView: "图形阅读",
    Group: "组",
    GroupDetails: "Group Details",
    GroupName: "组名",
    GroupPermissions: "Group Permissions",
    Groups: "用户组",
    GZip: "GZip",
    help: "本区域显示工作单元的树状图.一个图形的大小和颜色表明该图形所代表的活动的时间跨度 (较大的图形和较暗的颜色表明该图形所代表的活动时间较长.)",
    Helpers: "辅助文件",
    Hex: "十六进制预览",
    History: "历史",
    HPCCSystems: "HPCC系统",
    ID: "标识",
    Import: "Import",
    Info: "信息",
    InfoDialog: "信息对话窗",
    Inputs: "输入",
    InvalidResponse: "(Invalid response)",
    IP: "IP",
    IPAddress: "IP地址",
    IsLibrary: "程序库",
    Jobname: "任务名",
    JobName: "任务名",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "标识",
    LandingZone: "文件停放区",
    LandingZones: "文件停放区",
    Largest: "Largest",
    LastName: "Last Name",
    LastNDays: "过去若干天以内",
    LegacyForm: "旧式表格",
    LibrariesUsed: "使用程序库",
    Line: "行",
    LineTerminators: "行终止符",
    Links: "联接",
    Loading: "加载",
    LoadingCachedLayout: "Loading Cached Layout...",
    LoadingData: "加载数据...",
    loadingMessage: "加载...",
    Local: "局部",
    LoggedInAs: "登录用户",
    LogicalFile: "逻辑文件",
    LogicalFiles: "逻辑文件",
    LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
    LogicalFilesOnly: "Logical Files Only",
    LogicalFileType: "逻辑文件类型",
    LogicalName: "逻辑文件名",
    log_analysis_1: "log_analysis_1*",
    Mappings: "映像",
    Mask: "掩码",
    Max: "最大",
    MaxRecordLength: "最大记录长度",
    MemberOf: "Member Of",
    Members: "Members",
    Message: "信息",
    Min: "最小",
    Modification: "修改",
    ModifiedUTCGMT: "修改时间(UTC/GMT)",
    Modify: "修改",
    MonitorEventName: "监视事件名",
    MonitorShotLimit: "监视发射限制",
    MonitorSub: "监视子文件",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    NA: "不适用",
    Name: "名称",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Newest",
    NewPassword: "New Password",
    NoContent: "(No content)",
    noDataMessage: "零行...",
    Node: "节点",
    NoErrorFound: "No errors found\n",
    NoFilterCriteriaSpecified: "没有指定筛选规则",
    NoScheduledEvents: "No Scheduled Events.",
    NoSplit: "不分割",
    NotActive: "Not active",
    NothingSelected: "Nothing Selected...",
    NotInSuperfiles: "Not in Superfiles",
    NoWarningFound: "No warnings found\n",
    NumberofParts: "文件分块数量",
    OK: "认可",
    Oldest: "Oldest",
    OmitSeparator: "忽略分割符",
    Only1PackageFileAllowed: "Only one package file allowed",
    Open: "打开",
    OpenInNewPage: "在新页里打开",
    OpenLegacyECLWatch: "打开旧版本的ECLWatch",
    OpenSafeMode: "打开 (安全模式)",
    Operations: "操作",
    Options: "选项",
    Outputs: "输出",
    Overview: "覆盖",
    Overwrite: "覆盖",
    Owner: "拥有者",
    PackageContent: "Package Content",
    PackageContentNotSet: "Package content not set",
    PackageMap: "Package Map",
    PackageMaps: "查询程序文件包",
    PackagesNoQuery: "Packages without matching queries",
    ParameterXML: "参数XML",
    Parts: "文件分块",
    Password: "Password",
    PasswordExpiration: "Password Expiration",
    PasswordsDoNotMatch: "Passwords do not match.",
    Path: "路径",
    PathMask: "路径掩码",
    PctComplete: "任务完成%",
    PercentDone: "任务完成%",
    PerformingLayout: "图形布局中...",
    Permissions: "使用权限",
    PlaceholderFindText: "工作单元标识,用户名,等等",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "操作平台",
    Prefix: "前缀",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preview: "Preview",
    Priority: "优先级",
    Process: "Process",
    ProcessFilter: "Process&nbsp;Filter",
    ProcessFilter: "Process Filter",
    ProgressMessage: "进展信息",
    Properties: "特性",
    Property: "特性",
    Protect: "保护",
    Protected: "已保护",
    Publish: "公布",
    PublishedBy: "公布者",
    PublishedQueries: "已公布的查询程序",
    Queries: "查询程序",
    QueriesNoPackage: "Queries without matching package",
    QueryDetailsfor: "查询程序的详细说明",
    QuerySet: "查询程序集",
    Queue: "队列",
    Quote: "引用",
    RecordCount: "记录数量",
    RecordLength: "记录长度",
    Records: "记录",
    RecordSize: "记录长度",
    Refresh: "更新",
    ReleaseNotes: "版本说明",
    Reload: "Reload",
    RemoteDali: "远程Dali",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "删除",
    Rename: "更名",
    RenderedSVG: "渲染的SVG",
    RenderSVG: "渲染SVG",
    Replicate: "复制",
    RequestSchema: "请求格式",
    Reschedule: "再次加入运行计划",
    Reset: "设置更新",
    Resource: "Resource",
    Resources: "资源",
    ResponseSchema: "响应格式",
    Restart: "再启动",
    Resubmit: "再提交",
    Resubmit: "重新提交",
    Results: "结果",
    RetainSuperfileStructure: "保留文件集的结构",
    RetypePassword: "Retype Password",
    Rows: "行",
    RowTag: "行标记",
    roxie: "r?x*",
    RoxieCluster: "Roxie集群",
    Sample: "样本",
    SampleRequest: "请求的样本",
    SampleResponse: "响应的样本",
    Save: "保存",
    Scope: "范围",
    SearchResults: "查询结果",
    SecondsRemaining: "剩余时间(秒)",
    SelectPackageFile: "Select Package File",
    Seperators: "分割符",
    SetBanner: "标语设置",
    SetToFailed: "设为失误状态",
    Severity: "严重性",
    Show: "显示",
    ShowSVG: "显示SVG",
    Size: "文件长度",
    Size: "长度",
    Skew: "偏差",
    Slaves: "从属服务器",
    Smallest: "Smallest",
    SOAP: "SOAP",
    SomeDescription: "Some*Description",
    somefile: "*::文件名*",
    Source: "文件源",
    SourceCode: "原代码",
    SourcePath: "Source Path (Wildcard Enabled)",
    SplitPrefix: "分割前缀",
    Spray: "分布",
    Start: "开始",
    Started: "已开始",
    State: "状态",
    Stopped: "已结束",
    Subgraphs: "子图",
    Submit: "提交",
    Summary: "总结",
    SummaryMessage: "总结信息",
    SuperFile: "Super File",
    SuperfilesOnly: "Superfiles Only",
    Suspend: "暂停使用",
    Suspended: "已暂停使用",
    SuspendedBy: "暂停使用者",
    SVGSource: "SVG原始数据",
    SyncSelection: "Sync To Selection",
    SystemServers: "系统服务器",
    tag: "标记",
    Target: "目标",
    Target: "系统",
    Target: "集群系统",
    TargetClusters: "计算机集群服务器",
    TargetWuid: "Target/Wuid",
    Terminators: "终止符",
    TestPages: "测试页面",
    ThorNetworkAddress: "Thor网址",
    Time: "时间",
    TimeSeconds: "时间(秒)",
    TimeStarted: "起始时间",
    TimeStopped: "终止时间",
    Timings: "时间表",
    TimingsMap: "时间图",
    title_Activity: "当前活动",
    title_DFUQuery: "逻辑文件",
    title_DFUWUDetails: "DFU工作单元",
    title_ECLPlayground: "ECL操作平台",
    title_EventScheduleWorkunit: "Event Scheduler",
    title_GetDFUWorkunits: "DFU工作单元",
    title_Graph: "图形",
    title_GraphPage: "标题",
    title_Graphs: "图形",
    title_GridDetails: "修改",
    title_HPCCPlatformECL: "HPCC平台 - 首页",
    title_HPCCPlatformFiles: "HPCC平台 - 文件",
    title_HPCCPlatformMain: "HPCC平台 - 首页",
    title_HPCCPlatformOps: "HPCC平台 - 运行",
    title_HPCCPlatformRoxie: "HPCC平台 - Roxie",
    title_Inputs: "Inputs",
    title_LFDetails: "逻辑文件的详细说明",
    title_LZBrowse: "文件停放区",
    title_MemberOf: "Member Of",
    title_Members: "Members",
    title_QuerySetDetails: "查询程序的详细说明",
    title_QuerySetErrors: "错误",
    title_QuerySetLogicalFiles: "逻辑文件",
    title_QuerySetQuery: "查询程序",
    title_QuerySetSuperFiles: "文件集",
    title_QueryTest: "文件集",
    title_result: "活动",
    title_Results: "输出",
    title_SearchResults: "",
    title_SourceFiles: "",
    title_UserQuery: "Permissions",
    title_UserPermissions: "User Permissions",
    title_WUDetails: "ECL工作单元的详细说明",
    title_WUQuery: "ECL工作单元",
    ToDate: "截止日期",
    ToDate: "终止日期",
    Toenablegraphviews: "在使用图形阅读器前,请先安装图形控制器",
    ToSizes: "最大文件长度",
    TotalThorTime: "在Thor上的时间",
    Type: "类型",
    Unknown: "未知",
    Unprotect: "取消保护",
    Unsuspend: "未暂停使用",
    Unsuspended: "未暂停使用",
    Upload: "上传",
    Used: "已使用",
    User: "用户",
    UserDetails: "User Details",
    UserID: "User ID",
    Username: "Username",
    UserName: "User Name",
    UserPermissions: "User Permissions",
    Users: "用户",
    UseSingleConnection: "使用单一联接",
    Validate: "Validate",
    ValidatePackageMap: "Validate Package Map",
    ValidateResult: "=====Validate Result=====\n\n",
    Value: "值",
    Variable: "Variable",
    VariableBigendian: "Variable Big-endian",
    VariableSourceType: "Source Type",
    Version: "版本",
    Views: "显示",
    Visualize: "可视化",
    Warnings: "Warning(s)",
    Warnings: "警告",
    WarnOldGraphControl: "Warning:  Old Graph Control",
    Width: "宽度",
    Workunit: "工作单元",
    Workunits: "工作单元",
    Wrap: "自动换行",
    WSDL: "WSDL",
    WUID: "工作单元标识",
    Wuidcannotbeempty: "工作单元标识不可空缺.",
    WUSnapShot: "工作单元简单印象",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "无逻辑文件(请检查筛选规则)",
    Zip: "Zip",
    ZippedAnalysisPackage: "压缩后的分析信息包",
    Zoom100Pct: "缩放100%",
    ZoomAll: "整体缩放",
    ZoomWidth: "宽度缩放"
})
);