define(
({
    title: "逻辑文件的详细说明",

    ActualSize: "实际长度",
    ClusterName: "计算机集群名称",
    Compress: "压缩",
    Contents: "内容",
    Copy: "复制",
    DEF: "DEF",
    Description: "说明",
    Despray: "复合原文件",
    Directory: "文件目录",
    DropZone: "文件停放区",
    ECL: "ECL",
    FileParts: "文件分块",
    FileSize: "文件长度",
    Group: "组",
    IPAddress: "IP地址",
    JobName: "任务名",
    LogicalFile: "逻辑文件",
    Modification: "修改",
    NoSplit: "不分割",
    Overwrite: "覆盖",
    Owner: "拥有者",
    Path: "路径",
    PathMask: "路径掩码",
    RecordCount: "记录数量",
    RecordSize: "记录长度",
    Rename: "更名",
    RetainSuperfileStructure: "保留文件集的结构",
    Source: "文件源",
    SplitPrefix: "分割前缀",
    Summary: "总结",
    Target: "目标",
    UseSingleConnection: "使用单一联接",
    Workunit: "工作单元",
    Wrap: "自动换行",
    XML: "XML"
})
);
