define(
({
    title: "文件停放区",

    Compress: "压缩",
    Date: "日期",
    DeleteSelectedFiles: "删除所选择的文件?",
    Delimited: "定界的",
    Download: "下载",
    Errorparsingserverresult: "服务器结果解析错误",
    Escape: "换码",
    FileUploader: "文件上传",
    Fixed: "定长的",
    Format: "格式",
    Group: "组",
    HexPreview: "十六进制预览",
    Label: "标识",
    LandingZone: "文件停放区",
    LineTerminators: "行终止符",
    Mask: "掩码",
    MaxRecordLength: "最大记录长度",
    Name: "名称",
    NoSplit: "不分割",
    OmitSeparator: "忽略分割符",
    Options: "选项",
    Overwrite: "覆盖",
    Prefix: "前缀",
    Quote: "引用",
    RecordLength: "记录长度",
    RowTag: "行标记",
    Seperators: "分割符",
    Size: "长度",
    Source: "文件源",
    Spray: "分布",
    SpraySourceType: "分布文件源类型",
    Start: "开始",
    tag: "标记",
    Target: "目标",
    Upload: "上传",
    XML: "XML"
})
);
