define(
({
    ANY: "任选",
    Activate: "激活",
    Active: "已激活",
    Add: "添加",
    AddProcessMap: "添加文件包",
    Code: "代码",
    Deactivate: "失效",
    Description: "说明",
    Exception: "错误",
    ID: "标识",
    InvalidResponse: "(无效响应)",
    Message: "信息",
    NoContent: "(无内容)",
    Only1PackageFileAllowed: "仅允许一个文件包文件",
    Open: "打开",
    OverWrite: "覆盖",
    PackageMap: "文件包",
    PackageMaps: "文件包",
    Process: "进程",
    ProcessFilter: "进程过滤器",
    Reload: "重新加载",
    RemoteDaliIP: "外部Dali的IP地址",
    SelectPackageFile: "选择文件包文件",
    Submit: "提交",
    Target: "集群系统",
    ValidatePackageMap: "检查文件包"
})
);
