define(
({
    title: "ECL工作单元的详细说明",

    Abort: "终止",
    Action: "操作",
    Clone: "复制",
    Cluster: "计算机集群",
    Description: "说明",
    Duration: "时间段",
    ECL: "ECL",
    ESPBuildVersion: "ESP构建版本",
    ESPNetworkAddress: "ESP网址",
    Graphs: "图形",
    Helpers: "辅助文件",
    History: "历史",
    Inputs: "输入",
    JobName: "任务名",
    Outputs: "输出",
    Owner: "拥有者",
    Playground: "操作平台",
    Protected: "已保护",
    Publish: "公布",
    RemoteDali: "远程Dali",
    Restart: "再启动",
    Resubmit: "再提交",
    Scope: "范围",
    SetToFailed: "设为失误状态",
    State: "状态",
    Submit: "提交",
    Summary: "总结",
    ThorNetworkAddress: "Thor网址",
    Timings: "时间表",
    Visualize: "可视化",
    WUID: "工作单元标识",
    XML: "XML",
    ZAP: "Z.A.P",
    ZippedAnalysisPackage: "压缩后的分析信息包"
})
);
