define(
({
    title: "ECL Workunit Details",

    Abort: "Abort",
    Action: "Action",
    Clone: "Clone",
    Cluster: "Cluster",
    Description: "Description",
    Duration: "Duration",
    ECL: "ECL",
    ESPBuildVersion: "ESP Build Version",
    ESPNetworkAddress: "ESP Network Address",
    Graphs: "Graphs",
    Helpers: "Helpers",
    History: "History",
    Inputs: "Inputs",
    JobName: "Job Name",
    Outputs: "Outputs",
    Owner: "Owner",
    Playground: "Playground",
    Protected: "Protected",
    Publish: "Publish",
    RemoteDali: "Remote Dali",
    Restart: "Restart",
    Resubmit: "Resubmit",
    Scope: "Scope",
    SetToFailed: "Set To Failed",
    State: "State",
    Submit: "Submit",
    Summary: "Summary",
    ThorNetworkAddress: "Thor Network Address",
    Timings: "Timings",
    Visualize: "Visualize",
    WUID: "WUID",
    XML: "XML",
    ZAP: "Z.A.P",
    ZippedAnalysisPackage: "Zipped Analysis Package"
})
);
