export = {
    Abort: "Megszakít",
    AbortedBy: "Megszakította",
    AbortedTime: "A megszakítás időpontja",
    AbortSelectedWorkunits: "Megszakítja a munkaegység(ek) végrehajtását? Igen válasz esetén az Ön bejelentkezési azonosítója rögzítésre kerül a megszakított munkaegység(ek)ben.",
    About: "Névjegy",
    AboutGraphControl: "&lsquo;Graph Control&rsquo; információk",
    AboutHPCCSystems: "HPCC Systems® névjegye",
    AboutHPCCSystemsGraphControl: "HPCC Systems® Graph Control névjegye",
    AboutToLoseSessionInformation: "Ön arra készül, hogy kilépjen a rendszerből és ezzel elveszti az összes aktív folyamatra vonatkozó információt. Kívánja folytatni?",
    Account: "Felhasználói fiók",
    Action: "Művelet",
    Activate: "Aktivál",
    Activated: "Aktivizált",
    ActivateQuery: "Lekérdezés aktiválása",
    ActivateQueryDeletePrevious: "Lekérdezés aktiválása és az előző törlése",
    ActivateQuerySuspendPrevious: "Lekérdezés aktiválása és az előző felfüggesztése",
    Active: "Aktív",
    ActivePackageMap: "Aktív csomagtérkép",
    ActiveWorkunit: "Aktív feladat",
    Activities: "Tevékenységek",
    Activity: "Tevékenység",
    ActivityLabel: "Tevékenység címke",
    ActivityMap: "Aktivitás-térkép",
    ActualSize: "Aktuális méret",
    Add: "Hozzáad",
    AddAttributes: "Attribútumok/értékek hozzáadása az eljáráshoz",
    AddAttributes2: "Attribútum(ok) hozzáadása",
    AddBinding: "Kötés hozzáadása",
    AddFile: "Fájl hozzáadás",
    AddGroup: "Csoport hozzáadás",
    AdditionalResources: "További erőforrások",
    AddPart: "Fájl rész hozzáadás",
    AddProcessMap: "Csomagtérkép hozzáadás",
    AddTheseFilesToDali: "Kiválasztott fájlok hozzáadása a Dali szerverhez",
    AddtionalProcessesToFilter: "Járulékos szűrő eljárás",
    AddToExistingSuperfile: "Hozzáadás létező szuper-fájlhoz",
    AddToFavorites: "Hozzáadás a kedvencekhez",
    AddToSuperfile: "Superfile-hoz ad",
    AddUser: "Felhasználó hozzáadás",
    Advanced: "Haladó",
    Age: "Kora",
    All: "Összes",
    AllowAccess: "Hozzáférés Engedélyezés",
    AllowForeignFiles: "Idegen fájlok engedélyezése",
    AllowFull: "Teljes Hozzáférés",
    AllowRead: "Olvasás Engedélyezés",
    AllowWrite: "Írás Engedélyezés",
    AllQueries: "Az összes lekérdezés",
    AllQueuedItemsCleared: "A várakozási sorban levő elemek törlésre kerülnek. Az aktuális feldolgozás folytatódik",
    Analyze: "Analizál",
    ANY: "Bármelyik",
    AnyAdditionalProcessesToFilter: "További járulékos szűrő eljárások?",
    Append: "Hozzáfűz",
    AppendCluster: "Cluster hozzáadás",
    Apply: "Alkalmaz",
    Apps: "Applikáció",
    ArchivedOnly: "Csak tárolt.",
    ArchivedWarning: "Figyelem: Adjon meg rövidebb időintervallumot! Ellenkező esetben a feladatok lekérdezése hosszabb ideig tarthat, mint amit az Ön bőngésző programja engedélyez.",
    AreYouSureYouWantToResetTheme: "Biztos abban, hogy vissza akarja állítani az alapértelmezett téma beállításokat?",
    Attach: "Csatolás",
    Attribute: "Attribútum",
    AttributesAreRequired: "Kötelező attribútumok",
    Audience: "Közönség",
    AuditLogs: "Ellenőrzés napló",
    AutoRefresh: "Automatikus frissítés",
    AutoRefreshEvery: "Automatikus frissítés minden x percben.",
    AutoRefreshIncrement: "Automatikus frissítés növelése",
    Back: "Vissza",
    BannerColor: "Fejléc szín",
    BannerMessage: "Fejléc szövege",
    BannerScroll: "Fejléc görgetés",
    BannerSize: "Fejléc méret",
    BinaryInstalls: "Bináris telepítőkészlet",
    Bind: "Összekapcsol",
    Binding: "Kötés",
    BindingDeleted: "A kötés törölve",
    Blob: "BLOB",
    BlobPrefix: "BLOB előtag",
    Blobs: "Bináris objektumok",
    Blooms: "Bloom szűrők",
    Bottom: "Legalsó",
    BoundBy: "bekötötte:",
    Branches: "Ágak",
    BrowserStats: "Böngésző statisztika",
    Busy: "Foglalt",
    CallerID: "Hívó azonosító",
    Cancel: "Mégsem",
    CancelAll: "Az összes megszakítása",
    CancelAllMessage: "A folyamatban levő feldolgozások megszakítása és a várakozási sor törlése. Kívánja folytatni?",
    Category: "Kategória",
    Channel: "Csatorna",
    Chart: "Grafikon",
    CheckAllNodes: "Ellenőrizze az összes csomopontot",
    CheckFilePermissions: "Ellenőrizze a fájl hozzáférési jogokat",
    CheckSingleNode: "Ellenörizze a csomópontot",
    Class: "Osztály",
    Clear: "Mezők törlése",
    ClearPermissionsCache: "Törli a hozzáférés engedélyek gyorsítótárát",
    ClearPermissionsCacheConfirm: "Biztos, hogy törölni akarja a DALI és az ESP hozzáférési engedélyek gyorsítótárát? A futó feladatok teljesítménye jelentősen csökkenhet, amig a gyorsítótárak tartalma újratöltődik.",
    Client: "Ügyfél",
    Clone: "Klónozás",
    ClonedWUID: "Klónozott WUID",
    CloneTooltip: "Feladat duplikálás",
    Close: "Bezárás",
    CloseModal: "Előugró ablak bezárás",
    Cluster: "Klaszter",
    ClusterName: "Klaszter név",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Klaszter feldolgozások",
    Code: "Kód",
    CodeGenerator: "Kód generátor",
    Col: "Oszlop",
    CollapseAll: "Összes bezárása",
    Columns: "Oszlopok",
    Command: "Parancs",
    Comment: "Megjegyzés",
    CompileCost: "Fordítási költség",
    Compiled: "Fordítás kész",
    Compiling: "Fordítás folyamatban",
    Completed: "Kész",
    ComplexityWarning: "Több mint {threshold} aktivitás ({activityCount}) - elnyomjuk a kezdeti megjelenítést?",
    Component: "Komponens",
    ComponentLogs: "Alrendszer naplók",
    Compress: "Tömörít",
    Compressed: "Tömörített",
    CompressedFileSize: "Tömörített fájl méret",
    CompressedSize: "Tömörített méret",
    Compression: "Tömörítés",
    ComputerUpTime: "A számítógép újraindítása óta eltelt idő",
    Condition: "Feltétel",
    Configuration: "Beállítások",
    ConfigureService: "Szolgáltatás konfigurálása",
    ConfirmPassword: "Jelszó jóváhagyás",
    ConfirmRemoval: "Biztos, hogy ezt akarja csinálni?",
    ContactAdmin: "Amennyiben át akarja nevezni ezt a csoportot, lépjen kapcsolatba az LDAP adminisztrátorral.",
    Container: "Konténer",
    ContainerName: "Konténer neve",
    Content: "Tartalom",
    Contents: "Tartalom",
    ContentType: "Tartalom típusa",
    ContinueWorking: "Munka folytatása",
    CookiesAcceptButtonText: "Sütik (Cookies) engedélyezése",
    CookiesNoticeLinkText: "Süti (Cookie)-nyilatkozatunk",
    Copied: "Lemásolva",
    Copy: "Másolat",
    CopyLogicalFilename: "Logikai fájl másolás",
    CopyLogicalFiles: "Logikai fájlok másolása a vágólapra",
    CopySelectionToClipboard: "A kiválasztottak másolása a vágólapra",
    CopyToClipboard: "Vágólapra másolás",
    CopyURLToClipboard: "URL másolása a vágólapra",
    CopyWUID: "WUID másolása",
    CopyWUIDs: "WUID(ek) másolása a vágólapra",
    CopyWUIDToClipboard: "WUID másolása a vágólapra",
    Cost: "Költség",
    Count: "Darab (Count)",
    CountFailed: "A sikertelenek száma",
    CountTotal: "Összesen",
    CPULoad: "Processzor terhelés",
    Create: " Létrehoz",
    CreateANewFile: "Új szuper-fájl létrehozása.",
    Created: "Létrehozva",
    CreatedBy: "Létrehozta",
    CreatedByWorkunit: "Munkaegység által generált",
    CreatedTime: "Létrehozás időpontja",
    Creating: "Létrehoz",
    Critical: "Kritikus",
    CrossTab: "Lekérdezések közötti kapcsolatok",
    CSV: "CSV",
    Dali: "Dali",
    DaliAdmin: "Dali adminisztrátor",
    DaliIP: "Dali IP címe",
    Dashboard: "Kezelőfelület",
    Data: "Adat",
    DataPatterns: "Adat minták",
    DataPatternsDefnNotFound: "Fájl definíció nem található, így az Adatminta keresés sem indítható.",
    DataPatternsNotStarted: "Az analízis eredménye nem található. Létrehozásához nyomja meg a fent lévő “Analízis” gombot.",
    DataPatternsStarted: "Analizálás folyamatban. A folyamat végeztével az eredmény itt lesz látható.",
    dataset: ":=dataset*",
    Date: "Dátum",
    Day: "Nap",
    Deactivate: "Hatástalanít",
    Debug: "Hibakeresés",
    DEF: "DEF",
    Defaults: "Alapértelmezés",
    Definition: "Definíció",
    DefinitionDeleted: "Definíció törölve",
    DefinitionID: "Definíció azonosító",
    Definitions: "Definíciók",
    DelayedReplication: "Késleltetett másolás",
    Delete: "Törlés",
    DeleteBinding: "Kötések törlése",
    Deleted: "Törölt",
    DeletedBinding: "Törölt kötések",
    DeleteDirectories: "Az üres könyvtárak törlése. Kívánja folytatni?",
    DeleteEmptyDirectories: "Töröljük az összes könyvtárakat?",
    DeletePrevious: "Előző törlése",
    DeleteSelectedDefinitions: "Kívánja törölni az összes kiválasztott definíciót?",
    DeleteSelectedFiles: "Töröljük a kiválasztott fájlokat?",
    DeleteSelectedGroups: "Törölni akarja a kijelölt csoporto(ka)t?",
    DeleteSelectedPackages: "Töröljük a kiválasztott csomagokat?",
    DeleteSelectedPermissions: "Törli a kiválasztott hozzáférési engedélyeket?",
    DeleteSelectedQueries: "Töröljük a kiválasztott lekérdezéseket?",
    DeleteSelectedUsers: "Törölni akarja a kijelölt felhasználó(ka)t?",
    DeleteSelectedWorkunits: "Törölni akarja a kiválasztott feladatokat?",
    DeleteSuperfile: "Töröljük a Superfile-t?",
    DeleteSuperfile2: "Szuper-fájl törlése",
    DeleteThisPackage: "Törölni akarja ezt a csomagot?",
    Delimited: "Határolt",
    DenyAccess: "Hozzáférés Tiltása",
    DenyFull: "Műveletek Tiltása",
    DenyRead: "Olvasás Tiltása",
    DenyWrite: "Írás Tiltása",
    Depth: "Mélység",
    DepthTooltip: "Maximális al-gráf mélység",
    Deschedule: "Ütemezés törlése",
    DescheduleSelectedWorkunits: "Megszűnteti a kijelőlt feladat ütemezését?",
    Description: "Leírás",
    DESDL: "DESDL",
    Despray: "Összegyűjt",
    Details: "Részletek",
    DFSCheck: "DFS ellenőrzés",
    DFSExists: "DFS kilépés",
    DFSLS: "DFS LS",
    DFUServerName: "DFU Szerver név",
    DFUWorkunit: "DFU-munkaegység",
    Directories: "Könyvtárak",
    Directory: "Könyvtár",
    DisableScopeScanConfirm: "Biztos, hogy letíltja a hatókör vizsgálatot? DALI újraíndításakor ezek a változtatások elvesznek.",
    DisableScopeScans: "Hatókör vizsgálat letiltása",
    DiskSize: "Diszk méret",
    DiskUsage: "Lemez használat",
    Distance: "Távolság",
    DistanceTooltip: "Legnagyobb aktivitás-szomszéd távolság",
    Dll: "Dll",
    Documentation: "Dokumentáció",
    Domain: "Terület",
    DoNotActivateQuery: "Ne aktiválja a kiválasztott lekérdezést",
    DoNotRepublish: "Ne publikáljuk újra?",
    DOT: "DOT",
    DOTAttributes: "DOT Attribútumok",
    Down: "Le",
    Download: "Letöltés",
    Downloads: "Letöltés",
    DownloadSelectionAsCSV: "A kiválasztottak letöltése CSV formátumban.",
    DownloadToCSV: "Letöltés CSV fájlba",
    DownloadToCSVNonFlatWarning: "Figyelem, amennyiben egymásbaágyazott adatszerkezeteket tölt le, vesszővel elválasztott (CSV) formában, úgy az adatok formátuma eltérő lehet a várttól.",
    DropZone: "Gyűjtőhely",
    DueToInctivity: "Aktivitás hiányában a rendszer 3 percen belül kilépteti Önt az ECLWatch kapcsolatból.",
    Duration: "Időtartam",
    DynamicNoServicesFound: "A szolgáltatás nem található",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWatchRequiresCookies: "A folytatáshoz szükséges a sütik engedélyezése",
    ECLWatchSessionManagement: "ECLWatch kapcsolat menedzsment",
    ECLWorkunit: "ECL-munkaegység",
    EdgeLabel: "Él-címke",
    Edges: "Élek",
    Edit: "Szerkesztés",
    EditDOT: "DOT szerkesztés",
    EditGraphAttributes: "Gráf attribútumok szerkesztése",
    EditXGMML: "XGMML szerkesztés",
    EmailBody: "Email szövege",
    EmailFrom: "Feladó email címe",
    EmailSubject: "Email tárgya",
    EmailTo: "Címzett email címe",
    EmployeeID: "Alkalmazott azonosítója",
    EmployeeNumber: "Dolgozó azonosító",
    Empty: "(Üres)",
    Enable: "Engedélyezés",
    EnableBannerText: "Környezet engedélyezése",
    EnableScopeScans: "Hatókör vizsgálat engedélyezése",
    EnableScopeScansConfirm: "Biztos, hogy engedélyezi a hatókör vizsgálatot? DALI újraíndításakor ezek a változtatások elvesznek.",
    EndPoint: "Végpont",
    EndTime: "Befejezés ideje",
    EnglishQ: "Angolul?",
    EnterAPercentage: "Adjon meg egy százalékos arányt",
    EnterAPercentageOrMB: "Adjon meg egy százalékos arányt vagy méretet MB-ban",
    EraseHistory: "Előzmények törlése",
    EraseHistoryQ: "Előzményeinek törlése",
    Error: "Hiba",
    Errorparsingserverresult: "Hiba a szerver válasz feldolgozásban",
    Errors: "Hibák",
    ErrorsStatus: "Hibák/Figyelmeztetések",
    ErrorUploadingFile: "Hiba a fájl(ok) feltöltésénél. Ellenőrizze a hozzáférési jogosultságokat.",
    ErrorWarnings: "Hiba/Figyelmeztetés",
    Escape: "Megszakít",
    ESPBindings: "ESP szerver kötések",
    ESPBuildVersion: "ESP Build verzió",
    ESPNetworkAddress: "ESP hálózati címe",
    ESPProcessName: "ESP feldolgozás neve",
    EventName: "Esemény neve",
    EventNamePH: "eventname",
    EventScheduler: "Esemény ütemező",
    EventText: "Esemény szövege",
    EventTextPH: "Esemény szövege",
    Exception: "Kivétel",
    ExcludeIndexes: "Indexek kizárása",
    ExecuteCost: "Végrehajtási költség",
    Executed: "Végrehajtva",
    Executing: "Végrehajtás alatt",
    ExpandAll: "Összes kinyitása",
    ExpirationDate: "Lejárat dátuma",
    ExpireDays: "Lejár (nap)",
    Export: "Exportálás",
    ExportSelectionsToList: "A kijelöltek listába mentése",
    FailIfNoSourceFile: "Hibajelzés, ha nincs bemeneti file",
    Fatal: "Végzetes",
    Favorites: "Kedvencek",
    Fetched: "Hozott",
    FetchingData: "Adat lekérdezés...",
    fetchingresults: "eredemény lekérdezés",
    FieldNames: "Mezőnevek",
    File: "Fájl",
    FileAccessCost: "Fájl hozzáférési költség",
    FileCluster: "Fájl csomópont",
    FileCostAtRest: "Inaktív fájl tárolási költsége",
    FileCounts: "Fájlok száma",
    FileName: "Fájl név",
    FileParts: "Fájl részek",
    FilePath: "Fájl útvonal",
    FilePermission: "Fájl hozzáférési jogok",
    Files: "Fájlok",
    FileScopeDefaultPermissions: "Alapértelmezett fájl-hatókör hozzáférési jogok",
    FileScopes: "Fájl keresési hatókörök",
    FileSize: "Fájl méret",
    FilesNoPackage: "Csomagdefiníció nélküli fájlok",
    FilesPending: "Folyamatban lévő fájlok",
    FilesWarning: "Az eredmény túl sok fájlt tartalmaz. Csak az első 100.000 fájl kerül rendezésre dátum/hozzáférés dátuma alapján. Ha korlátozni szeretné az eredmény méretét, állítson be egy szűrőfeltételt.",
    FilesWithUnknownSize: "Ismeretlen méretű fájlok",
    FileType: "Fájl típus",
    FileUploader: "Fájl feltöltő",
    FileUploadStillInProgress: "Fájl feltöltés folyamatban",
    Filter: "Szűrő",
    FilterDetails: "Szűrő információk",
    FilterSet: "Szűrőfeltétel",
    Find: "Keresés",
    FindNext: "Következőt",
    FindPrevious: "Előzőt",
    Finished: "Befejezett",
    FirstN: "Az első N",
    FirstName: "Keresztnév",
    FirstNRows: "Első N rekord",
    FirstNSortBy: "Szerinti rendezés",
    Fixed: "Állandó rekordméret",
    Folder: "Könyvtár",
    Form: "Űrlap",
    Format: "Formátum",
    Forums: "Fórum",
    Forward: "Előre",
    FoundFile: "Megtalált fájl",
    FoundFileMessage: "A megtalált fájlhoz tartozó fizikai részek nincsenek regisztrálva a Dali szerverben. A részek ellenőrzöttek, így visszaállíthatók a szerverben. Igény eseten törölhetők a",
    FromDate: "Dátumtól",
    FromSizes: "Mérettől",
    FromTime: "Időponttól",
    FullName: "Teljes név",
    Generate: "Generálás",
    GetDFSCSV: "DFS lekérdezése CSV formátumban",
    GetDFSMap: "DFS térkép",
    GetDFSParents: "DFS ősei",
    GetLogicalFile: "Logikai fájl",
    GetLogicalFilePart: "Logikai fájl rész",
    GetPart: "Fájl rész elérés",
    GetProtectedList: "Védett lista",
    GetSoftwareInformation: "Szoftver információ lekérdezés",
    GetValue: "Értéke",
    Graph: "Gráf",
    GraphControl: "Graph Control",
    Graphs: "Gráfok",
    GraphView: "Gráf nézet",
    Group: "Csoport",
    GroupBy: "Csoportosítva",
    GroupDetails: "Csoport jellemzők",
    Grouping: "Csoportosítás",
    GroupName: "Csoport név",
    GroupPermissions: "Csoport engedélyek",
    Groups: "Csoportok",
    GZip: "GZip",
    help: "Ezen a területen a munkaegység gráfjai láthatók. Az egyes blokkok mérete és színe az adott blokk végrehajtási idejével arányos (a nagyobb es sötétebb terület a hosszabb időtartamot jelzi).",
    Helper: "Segítő",
    Helpers: "Segédletek",
    Hex: "Hexa nézet",
    HideSpills: "Rendszer-munkafájl elrejtése",
    High: "Magas",
    History: "Történet",
    Homepage: "Honlap",
    Hotspots: "Forró pont",
    HPCCSystems: "HPCC Systems®",
    HTML: "HTML",
    Icon: "Ikon",
    ID: "Azonosító",
    IFrameErrorMsg: "A keret nem tölthető be, próbálja újra!",
    IgnoreGlobalStoreOutEdges: "A 'Global Storage Out Edges' metrika figyelmen kívül hagyása",
    Import: "Import",
    Inactive: "Inaktív",
    IncludeSlaveLogs: "Slave logok hozzáadása",
    IncludeSubFileInfo: "Hozzáadjuk az al-fájl információkat is?",
    Index: "Index",
    Indexes: "Indexek",
    IndexesOnly: "Csak az indexek",
    Info: "Információ",
    InfoDialog: "Információk",
    Informational: "Tájékoztató",
    Infos: "Információ(k)",
    InheritedPermissions: "Örökölt hozzáférési jogok",
    Inputs: "Bemenet",
    InUse: "Használatban van",
    InvalidResponse: "(Érvénytelen válasz)",
    InvalidUsernamePassword: "Hibás felhasználói név vagy jelszó. Próbálja újra.",
    IP: "IP",
    IPAddress: "IP cím",
    IsCompressed: "Tömörített?",
    IsLibrary: "Könyvtár?",
    IsReplicated: "Készült másodpéldány?",
    IssueReporting: "Probléma jelentés",
    JobID: "Munka azonosító",
    JobName: "Munka azonosító",
    Jobname: "Munka azonosító",
    jsmi: "jkis*",
    JSmith: "JKis*",
    JSON: "JSON",
    KeyFile: "Kulcs fájl",
    KeyType: "Kulcs típus",
    Label: "Címke",
    LandingZone: "Lerakat",
    LandingZones: "Lerakatok",
    LanguageFiles: "Nyelvi fájlok",
    Largest: "Legnagyobb",
    LargestFile: "Legnagyobb fájl",
    LargestSize: "Legnagyobb méret",
    LastEdit: "Utolsó szerkesztés",
    LastEditedBy: "Utoljára szerkesztette:",
    LastEditTime: "Utolsó szerkesztés ideje",
    LastMessage: "Utolsó üzenet",
    LastName: "Vezetéknév",
    LastNDays: "Az utolsó N nap",
    LastNHours: "Utolsó N óra",
    LastNRows: "Utolsó N rekord",
    LastRun: "Utolsó futás",
    Layout: "Elrendezés",
    LDAPWarning: "<b>LDAP szolgáltatás hiba:</b>  &lsquo;Túl sok felhasználó&rsquo; - Kérem, használjon szűrést!",
    LearnMore: "További ismeretek",
    Leaves: "(fa)levelek",
    LegacyForm: "Örökölt űrlap (Legacy Form)",
    LegacyGraphLayout: "Graph elrendezés (előző verzió)",
    LegacyGraphWidget: "Graph kisalkalmazás (előző verzió)",
    Legend: "Jelmagyarázat",
    Length: "Hossz",
    LibrariesUsed: "Használt könyvtárak",
    LibraryName: "Library név",
    Limit: "Korlát",
    Line: "Sor",
    LineTerminators: "Sorvég karakterek",
    Links: "Linkek",
    Loading: "Betöltés",
    LoadingCachedLayout: "Tárolt elrendezés betöltése",
    LoadingData: "Adat betöltés...",
    loadingMessage: "Betöltés folyamatban...",
    LoadPackageContentHere: "(Csomag tartalmának betöltése erre a helyre)",
    LoadPackageFromFile: "Csomag betöltése fájlból",
    Local: "Helyi",
    LocalFileSystemsOnly: "Csak helyi fájlrendszerbe",
    Location: "Elhelyezkedés",
    Lock: "Lezár",
    log_analysis_1: "log_elemzés_1*",
    Log: "Log",
    LogAccessType: "Log hozzáférés típusa",
    LogDirectory: "Log könyvtár",
    LogFile: "Log fájl",
    LoggedInAs: "Bejelentkezve mint",
    LoggingOut: "Kijelentkezés",
    LogicalFile: "Logikai fájl neve",
    LogicalFiles: "Logikai fájlok",
    LogicalFilesAndSuperfiles: "Logikai és szuper fájlok",
    LogicalFilesOnly: "Csak a logikai fájlokat",
    LogicalFileType: "Logikai fájl típusa",
    LogicalName: "Logikai név",
    LogicalNameMask: "Logikai fájl maszk",
    Login: "Bejelentkezés",
    Logout: "Kijelentkezés",
    Logs: "Logok",
    LogVisualization: "Log megjelenítés",
    LogVisualizationUnconfigured: "Log megjelenítés nincs konfigurálva. Ellenőrizze a konfigurációs beállításokat.",
    LostFile: "Elveszett fájl",
    LostFile2: "Elveszett fájlok",
    LostFileMessage: "Az elveszett logikai fájl legalább egy fizikai része megtalálható mind az elsődleges mind a másolati tároló helyen. A logikai fájl referencia megtalálható a Dali szerverben. A fájl törlése eltávolítja a hivatkozást a Dali szerverből valamint az összes fizika részt a lemezről.",
    Low: "Alacsony",
    MachineInformation: "Gépek",
    Machines: "Gép",
    Major: "Fő",
    ManagedBy: "Által kezelt",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Használja a Ctr+C-t",
    ManualOverviewSelection: "Gyorsnézet manuális kiválasztása szükséges",
    ManualTreeSelection: "Manuális fa kiválasztás szükséges",
    Mappings: "Leképezések",
    Mask: "Maszk",
    Max: "Maximum",
    MaxConnections: "A kapcsolatok maximális száma",
    MaximizeRestore: "Maximalizál/visszaállít",
    MaximumNumberOfSlaves: "Slave-ek maximális száma",
    MaxNode: "Maximális csomópont szám",
    MaxRecordLength: "Maximális rekord méret",
    MaxSize: "Maximális méret",
    MaxSkew: "Maximális elcsúszás",
    MaxSkewPart: "Legjobban elcsúszott rész",
    Mean: "Átlag",
    MeanBytesOut: "Kimeneti bájtok számának átlaga",
    MemberOf: "Tagja a",
    Members: "Tagok",
    MemorySize: "Memória méret",
    Message: "Üzenet",
    MethodConfiguration: "Módszer konfiguráció",
    Methods: "Eljárások",
    Metrics: "Metrika",
    MetricsGraph: "Metrika/Grafikus megjelenítés",
    Min: "Minimum",
    Mine: "Az én",
    MinNode: "Minimális csomópont szám",
    Minor: "Al",
    MinSize: "Minimális méret",
    MinSkew: "Minimális elcsúszás",
    MinSkewPart: "Legkevésbé elcsúszott rész",
    Missing: "Hiányzó",
    MixedNodeStates: "Több komponenst tartalmazó csomópont állapota",
    Modification: "Módosítás",
    Modified: "Módosított",
    ModifiedUTCGMT: "Módosítva (UTC/GMT)",
    Modify: "Módosít",
    MonitorEventName: "Monitor esemény név",
    Monitoring: "Felügyelet",
    MonitorShotLimit: "Monitor találatok limitje",
    MonitorSub: "Almonitor",
    Month: "Hónap",
    More: "Tovább",
    Move: "Mozgatás",
    MustContainUppercaseAndSymbol: "Csak nagybetűket és jeleket tartalmazhat",
    NA: "N/A",
    Name: "Név",
    NameOfEnvironment: "Környezet neve",
    NamePrefix: "Név előtag",
    NamePrefixPlaceholder: "valamilyen::előtag",
    NetworkAddress: "Hálózati cím",
    Newest: "Legújabb",
    NewPassword: "Új jelszó",
    NextSelection: "Következő kiválasztott",
    NoCommon: "Nem közös",
    NoContent: "(Nincs tartalom)",
    noDataMessage: "Nincs a feltételeknek megfelelő adat...",
    Node: "Csomópont",
    NodeGroup: "Node csoport",
    NoErrorFound: "Nincs hiba",
    NoFilterCriteriaSpecified: "Nincs szűrőfeltétel megadva.",
    None: "Semmi",
    NoPublishedSize: "Nincs publikált méret",
    NoRecentFiltersFound: "Még nem használt szűrőket.",
    Normal: "Normál",
    NoScheduledEvents: "Nincs ütmezett esemény",
    NoSplit: "Együtt tart",
    NotActive: "Nem aktív",
    NotAvailable: "Nem hozzáférhető",
    NothingSelected: "Nincs kiválasztva…",
    NotInSuperfiles: "Nincs a szuper fájlban",
    NotSuspended: "Nincs felfüggesztve",
    NotSuspendedbyUser: "Nem a felhasználó által felfüggesztett",
    NoWarningFound: "Nincs figyelmeztetés",
    NumberOfNodes: "Csomópontok száma",
    NumberofParts: "Részek száma",
    NumberofSlaves: "Slave-ok száma",
    Of: "Of",
    Off: "Kikapcsolt",
    OK: "Rendben",
    Oldest: "Legrégebbi",
    OldPassword: "Régi jelszó",
    OmitSeparator: "Elválasztójel mellőzése",
    On: "Bekapcsolt",
    Only1PackageFileAllowed: "Csak egy csomagfájl engedélyezett",
    Open: "Megnyitás",
    OpenConfiguration: "Konfiguráció megnyitása",
    OpenInNewPage: "Megnyitás új lapon",
    OpenInNewPageNoFrame: "Megnyitás új lapon (nem keretben)",
    OpenLegacyECLWatch: "Legacy ECL Watch megnyitása",
    OpenLegacyMode: "Megnyitás (hagyományos módon)",
    OpenModernECLWatch: "Modern ECLWatch megnyitása",
    OpenNativeMode: "Megnyitás (alapértelmezett módon)",
    OpenSafeMode: "Megnyitás (biztonságos módban)",
    OpenSource: "Nyílt forráskódú",
    OpenTreeMode: "Nyitva (fa nézetben)",
    Operation: "Művelet",
    Operations: "Műveletek",
    Optimize: "Optimalizál",
    Options: "Opciók",
    OriginalFile: "Eredtei fájl",
    OriginalSize: "Eredeti méret",
    OrphanFile: "Elhagyott, árva fájlok",
    OrphanFile2: "Elhagyott, árva fájl",
    OrphanMessage: "Az elhagyott, árva file összes fizikai része nem található meg a lemezen. Ezek hiányában a logikai fájl csak részlegesen állítható vissza a Dali szerverben.",
    OSStats: "OS statisztika",
    Other: "Egyéb",
    Others: "Egyebek",
    Outputs: "Kimenet",
    Overview: "Áttekintés",
    Overwrite: "Fellülírás",
    OverwriteMessage: "Néhány fájl már létezik! A folytatáshoz engedélyezze a fellülírást!",
    Owner: "Tulajdonos",
    PackageContent: "Csomag tartalma",
    PackageContentNotSet: "Csomag tartalma nincs megadva",
    PackageMap: "Csomagtérkép",
    PackageMaps: "Csomagtérképek",
    PackagesNoQuery: "Csomagok hozzátartozó lekérdezés nélkül",
    PageSize: "Lap méret",
    ParameterXML: "Paraméter XML fájl",
    Part: "Rész",
    PartMask: "Fizikai fájl név maszk",
    PartName: "Fájl rész név",
    PartNumber: "Fájl rész sorszám",
    Parts: "Részek",
    PartsFound: "Megtalált fizikai fájl részek",
    PartsLost: "Elveszett fizikai fájl részek",
    Password: "Jelszó",
    PasswordExpiration: "Jelszó lejár",
    PasswordExpired: "A jelszava lejárt! Adjon meg újat!",
    PasswordExpirePostfix: "napon bellül. Meg akarja változtatni?",
    PasswordExpirePrefix: "Jelszava lejár",
    PasswordOpenZAP: "Jelszó a ZAP megnyitásához (opciónális)",
    PasswordsDoNotMatch: "Jelszó nem egyezik",
    Path: "Útvonal",
    PathAndNameOnly: "Csak az útvonal és a fájl neve?",
    PathMask: "Útvonal maszk",
    Pause: "Szüneteltetés",
    PauseNow: "Azonnali felfüggesztés",
    PctComplete: "% kész",
    PercentCompressed: "Százalék tömörített",
    PercentCompression: "Tömörítési arány",
    PercentDone: "% kész",
    Percentile97: "97%-os osztály",
    Percentile97Estimate: "97%-os osztály becslés",
    PercentUsed: "%-ban használt",
    PerformingLayout: "Elrendezés generálása...",
    Permission: "Hozzáférési jog",
    PermissionName: "Hozzáférési jog megnevezése",
    Permissions: "Jogosultságok",
    PhysicalFiles: "Fizikai fájlok",
    PhysicalMemory: "Fizikai memória méret",
    PlaceholderFindText: "Wuid, felhasználók, egyebek...",
    PlaceholderFirstName: "József",
    PlaceholderLastName: "Kiss",
    Platform: "Platform",
    Playground: "ECL teszt labor",
    PleaseEnableCookies: "A folytatáshoz szükséges a sütik engedélyezése",
    PleaseEnterANumber: "Adjon meg egy számot",
    PleaseLogin: "Kérem jelentkezzen be a felhasználói nevével és jelszavával",
    PleaseLogIntoECLWatch: "Az ECLWatch használatához be kell jelentkeznie.",
    PleasePickADefinition: "Válasszon egyet a definíciók közül",
    PleaseSelectADynamicESDLService: "Válasszon egyet a dinamikus ESDL szolgáltatások közül.",
    PleaseSelectAGroupToAddUser: "Kérem válasszon csoportot a felhasználó számára",
    PleaseSelectAServiceToBind: "Kérem válasszon egy bekötendő szolgáltatást",
    PleaseSelectATopologyItem: "Válasszon egy célt, szolgáltatást vagy gépet",
    PleaseSelectAUserOrGroup: "A fájlnévvel együtt adjon meg egy felhasználó vagy csoport azonosítót",
    PleaseSelectAUserToAdd: "Válasszon egy felhasználót a hozzáadáshoz.",
    Plugins: "Betölthető modulok",
    Pods: "Pod-ok",
    PodsAccessError: "A POD-ok listája nem elérhető",
    Port: "Port",
    Prefix: "Előtag",
    PrefixPlaceholder: "fájlnév{:hossz}, fájlméret{:[B|L][1-8]}",
    Preflight: "Előkészítés",
    PreloadAllPackages: "Az összes csomag előzetes betöltése",
    PreserveCompression: "Tartalom tömörtés megőrzése",
    PreserveParts: "Fájl részek megőrzése",
    PressCtrlCToCopy: "A másoláshoz nyomja meg a <Ctrl>-<c> gombokat.",
    Preview: "Előnézet",
    PreviousSelection: "Előző kiválasztott",
    PrimaryLost: "Elveszett az elsődleges változat",
    PrimaryMonitoring: "Elsődleges felügyelet",
    Priority: "Prioritás",
    Probability: "Valószínűség",
    Process: "Feldolgozás",
    Processes: "Folyamatok",
    ProcessesDown: "A feldolgozás megállt",
    ProcessFilter: "Process&nbsp;Filter",
    ProcessID: "Feldolgozás azonosító",
    ProcessorInformation: "Processzor információk",
    ProgressMessage: "Állapot",
    Properties: "Tulajdonságok",
    Property: "Tulajdonság",
    Protect: "Megvéd",
    ProtectBy: "Által védett",
    Protected: "Védett",
    Protocol: "Protokoll",
    Publish: "Publikál",
    Published: "Közzétett",
    PublishedBy: "Közzétette",
    PublishedByMe: "Általam publikált",
    PublishedQueries: "Publikált lekérdezések",
    PushEvent: "Push event",
    Quarter: "Negyed",
    Queries: "Lekérdezések",
    QueriesNoPackage: "Lekérdezések hozzátartozó csomag nélkül",
    Query: "Lekérdezés",
    QueryDetailsfor: "A lekérdezés paraméterei",
    QueryID: "Lekérdezés azonosító",
    QueryIDPlaceholder: "som?q*ry.1&rsquo;",
    QueryName: "Lekérdezés név",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Lekérdezés készlet",
    Queue: "Sor",
    Quote: "Idézőjel",
    QuotedTerminator: "A fájl idézőjelek közötti rekordhatároló karaktert tartalmaz",
    RawData: "Feldolgozatlan adat",
    RawTextPage: "Formázatlan szöveg (aktuális lap)",
    Ready: "Kész",
    ReallyWantToRemove: "Biztosan el akarja távolítani?",
    ReAuthenticate: "A folytatáshoz újra azonosítania kell magát",
    RecentFilters: "Utoljára használt szűrők",
    RecentFiltersTable: "Az utoljára használt szűrők listája",
    RecordCount: "Rekord szám",
    RecordLength: "Rekord méret",
    Records: "Rekordok száma",
    RecordSize: "Rekord méret",
    RecordStructurePresent: "CSV rekord struktúra definiált az fájl első sorában",
    Recover: "Helyreállít",
    RecoverTooltip: "Felfüggesztett/megakadt feldolgozás újraindítása",
    RecreateQuery: "Lekérdezés újrakészítése",
    Recursively: "Rekurzívan",
    Recycling: "Újrahasznosítás",
    RedBook: "Referencia kézikönyv (Red Book)",
    Refresh: "Frissítés",
    ReleaseNotes: "Verzió információk (Release Notes)",
    Reload: "Újratölt",
    Remaining: "Hátralévő",
    RemoteCopy: "Távoli másolat",
    RemoteDali: "Távoli Dali hálózati címe",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "Eltávolít",
    RemoveAttributeQ: "Törölni készül egy attribútumot. Biztos, hogy folytatni akarja?",
    RemoveAtttributes: "Attribútum(ok) eltávolítása",
    RemoveFromFavorites: "Eltávolítás a kedvencekből",
    RemovePart: "Fájl rész eltávolítás",
    RemoveSubfiles: "Al-fájl(ok) eltávolítása",
    RemoveSubfiles2: "Töröljük az al-fájlokat?",
    RemoveUser: "Arra készül, hogy eltávolítsa a felhasználói nevét a csoportból!",
    Rename: "Átnevez",
    RenderedSVG: "Generált SVG",
    RenderSVG: "SVG generálás",
    Replicate: "Másolat",
    ReplicatedLost: "Elveszett a másolat",
    ReplicateOffset: "Másodpéldány eltolás (csomópontok között)",
    Report: "Jelentés",
    ReportAnError: "Egy hiba bejelentése",
    ReportError: "Hiba bejelentése",
    RepresentsASubset: "Az összes találat egy részhalmaza került megjelenítésre. Specifkusabb feltéttel megadásával csökkentheti a találatok számát.",
    RequestSchema: "Igénylő séma (Request Schema)",
    RequiredForFixedSpray: "Szükséges a 'fixed spray' művelthez",
    RequiredForXML: "Szükséges az XML formátumú importáláshoz",
    Reschedule: "Újraütemez",
    Reset: "Forrás",
    ResetThisQuery: "Vissza akarja állítani ezt a lekérdezést az allapállapotába?",
    ResetViewToSelection: "Vissza akarja állítani ezt a nézetet a kiválasztott elemekre?",
    Resource: "Erőforrás",
    Resources: "Erőforrások",
    ResponseSchema: "Válasz séma (Response Schema)",
    Restart: "Újraindít",
    Restarted: "Újraindított",
    Restarts: "Újraindítás",
    Restore: "Visszaállítás",
    Restricted: "Korlátozott",
    Resubmit: "Újraküld",
    Resubmitted: "Újraküldött",
    ResubmitTooltip: "Létező feldolgozás újraindítása",
    Results: "Eredmény(ek)",
    Resume: "Tovább folytat",
    RetainSuperfileStructure: "Superfile szerkezetének megőrzése",
    RetainSuperfileStructureReason: "Amennyiben több mint egy file tartozik a szuper-filehoz, engedélyezni kell a szuper-file struktúra megőrzését.",
    RetypePassword: "Jelszó mégegyszer",
    Reverse: "Visszafelé",
    RowPath: "Rekord útvonal",
    Rows: "Sor",
    RowTag: "Sor azonositó",
    RoxieCluster: "Roxie klaszter",
    RoxieFileCopy: "Roxie fájl másolás állapot",
    RoxieState: "Roxie állapot",
    RunningServerStrain: "Ez a feldolgozás sokig futhat és nagy terhelés okozhat a rendszerben. Kívánja folytatni?",
    Sample: "Minta",
    SampleRequest: "Minta igénylés (Sample Request)",
    SampleResponse: "Minta válasz (Sample Response)",
    Save: "Mentés",
    Scope: "Hatókör",
    SearchResults: "Keresések",
    SecondsRemaining: "másodperc maradt",
    Security: "Biztonság",
    SecurityMessageHTML: "Csak megbízható felhasználóktól származó HTML tekinthető meg.  Ezt a munkaegységet '{__placeholder__}' hozta létre. HTML megjelenítése?",  
    SecurityWarning: "Biztonsági figyelmeztetés",
    SeeConfigurationManager: "Lásd Konfigurációs Manager",
    SelectA: "Válasszon egy",
    SelectEllipsis: "Válasszon ...",
    SelectPackageFile: "Csomagfájl választás",
    SelectValue: "Válasszon egy értéket",
    SendEmail: "Email küldés",
    Separators: "Elválasztó jelek",
    Sequence: "Sorozat",
    Server: "Szerver",
    ServiceName: "Szolgáltatás megnevezése",
    Services: "Szolgáltatások",
    ServiceType: "Szolgáltatás típusa",
    SetBanner: "Fejléc megadása",
    SetTextError: "Nem sikerült a szöveget megjeleníteni. Lehetséges, hogy túl hosszú. Használja a &lsquo;segédleteket&rsquo; a letöltéshez.",
    SetToFailed: "Elront",
    SetToolbar: "Eszközkészlet beállítása",
    SetToolbarColor: "Eszköztár szín beállítása",
    Severity: "Probléma mértéke",
    ShareWorkunit: "A megosztásra kerülő munkaegység URL-je",
    Show: "Megjelenít",
    ShowPassword: "Jelszó megjelenítése",
    ShowProcessesUsingFilter: "Feldolgozások  megjelenítése szűréssel",
    ShowSVG: "SVG megjelenítés",
    Size: "Méret",
    SizeEstimateInMemory: "Becsült méret a memóriában",
    SizeMeanPeakMemory: "Tevékenység csúcsmemória-használata az összes csomópontra átlagolva",
    SizeOnDisk: "Méret a lemezen",
    Skew: "Asszimmetrikus (Skew)",
    SkewNegative: "Negatív elcsúszás",
    SkewPositive: "Pozitív elcsúszás",
    SLA: "SLA",
    SlaveLogs: "Slave logs",
    SlaveNumber: "Slave-ek száma",
    Slaves: "Kiszolgáló",
    Smallest: "Legkisebb",
    SmallestFile: "Legkisebb fájl",
    SmallestSize: "Legkisebb méret",
    SOAP: "SOAP",
    SomeDescription: "Valamennyi leírás",
    somefile: "*::valamilyen_fájl*",
    Source: "Forrás",
    SourceCode: "Forráskód",
    SourceLogicalFile: "Forrás logikai fájl neve",
    SourcePath: "Forrás útvonal (joker karakter engedélyezett)",
    SourceProcess: "Forrás feldolgozás",
    SparkThor: "SparkThor",
    Spill: "Rendszer-munkafájl",
    SplitPrefix: "Elválasztó előtag",
    Spray: "Szétoszt",
    Start: "Indítás",
    Started: "Elindítva",
    Starting: "Kezdés",
    StartTime: "Indítás ideje",
    State: "Állapot",
    Stats: "Statisztika",
    Status: "Állapot",
    Stopped: "Megállítva",
    Stopping: "Megállás",
    StorageInformation: "Tárolási információk",
    Subfiles: "Alfájlok",
    Subgraph: "Al-gráf",
    SubgraphLabel: "Rész-gráf címke",
    Subgraphs: "Algráf",
    Submit: "Elküld",
    Subtype: "Altípus",
    SuccessfullySaved: "Sikeresen mentve",
    Summary: "Összegzés",
    SummaryMessage: "Összegzés",
    SummaryStatistics: "Összegzett statisztika",
    SuperFile: "Szuperfájl",
    Superfile: "Szuperfájl",
    SuperFiles: "Szuperfájlok",
    Superfiles: "Szuperfájlok",
    SuperFilesBelongsTo: "Szuperfájl(ok)hoz tartozik",
    SuperfilesOnly: "Kizárólag szuperfájl",
    SuperOwner: "Szuperfájl tulajdonos",
    Suspend: "Felfüggeszt",
    Suspended: "Felfüggesztve",
    SuspendedBy: "Felfüggesztette",
    SuspendedByAnyNode: "Valamelyik csomópont által felfüggesztve",
    SuspendedByCluster: "A klaszter által felfüggesztett",
    SuspendedByFirstNode: "Az első csomópont által felfüggesztve",
    SuspendedByUser: "Felhansználó által felfüggesztett",
    SuspendedReason: "A felfüggesztés oka",
    SVGSource: "SVG forrás",
    Sync: "Szinkronizálás",
    SyncSelection: "Szinkronizálás a kiválasztottakhoz",
    SystemServers: "Rendszer kiszolgálók",
    Table: "Táblázat",
    tag: "jel",
    Target: "Cél",
    TargetClusters: "Cél klaszterek",
    TargetClustersLegacy: "Cél csoport (előző verzió)",
    TargetName: "Cél neve",
    TargetNamePlaceholder: "valamilyen::logikai::fájlnév",
    TargetRowTagRequired: "Meg kell adnia az XML rekord azonositó cimkét",
    Targets: "Célok",
    TargetScope: "Cél hatókör",
    TargetWuid: "Cél/WUID",
    TechPreview: "Technikai előzetes",
    Terminators: "Rekord lezáró jelek",
    TestPages: "Tesztlapok",
    Text: "Szöveg",
    TheReturnedResults: "Az eredmény",
    ThorMasterAddress: "Thor Master hálózati címe",
    ThorNetworkAddress: "Thor hálózati címe",
    ThorProcess: "Thor feldolgozás",
    ThreadID: "Szál azonosító",
    Time: "Idő",
    Timeline: "Idővonal",
    TimeMaxTotalExecuteMinutes: "Maximális futási idők összege (perc)",
    TimeMeanTotalExecuteMinutes: "Átlagos futási idők  összege (perc)",
    TimeMinTotalExecuteMinutes: "Minimális futási idők összege (perc)",
    Timers: "Időzítések",
    TimeSeconds: "Idő (másodperc)",
    TimeStamp: "Időbélyeg",
    TimeStarted: "Kezdés",
    TimeStopped: "Befejezés",
    Timings: "Időzítések",
    TimingsMap: "Időzítés térkép",
    title_ActiveGroupPermissions: "Érvényes csoport hozzáférési jogok",
    title_ActivePermissions: "Érvényes jogok",
    title_Activity: "Tevékenység",
    title_AvailableGroupPermissions: "Rendelkezésre álló csoportjogok",
    title_AvailablePermissions: "Rendelkezésre álló jogok",
    title_BindingConfiguration: "Kapcsolat konfiguráció",
    title_BindingDefinition: "Kapcsolat definíció",
    title_Blooms: "Bloom szűrők",
    title_ClusterInfo: "Csoportok",
    title_Clusters: "Csoportok",
    title_CodeGeneratorPermissions: "Kód-generátor hozzáfárási jogok",
    title_DefinitionExplorer: "Definíció böngésző",
    title_Definitions: "Definíciók",
    title_DESDL: "Dinamikus ESDL",
    title_DFUQuery: "Logikai fájlok",
    title_DFUWUDetails: "DFU munka",
    title_DirectoriesFor: "Könyvtárak a(z)",
    title_DiskUsage: "Lemez használat",
    title_ECLPlayground: "ECL teszt labor",
    title_ErrorsWarnings: "Hibák/figyelmeztetések a(z)",
    title_EventScheduleWorkunit: "Esemény ütemező",
    title_FileScopeDefaultPermissions: "Alapértelmezett fájl hozzáférési jogok",
    title_FilesPendingCopy: "Fájlok másolása folyamatban",
    title_FoundFilesFor: "Megtalált fájljai a(z)",
    title_GetDFUWorkunits: "DFU feladatok",
    title_Graph: "Gráfok",
    title_GraphPage: "Cím",
    title_Graphs: "Gráfok",
    title_GridDetails: "Változtass meg!",
    title_History: "Előzmények",
    title_HPCCPlatformECL: "ECL Watch - Kezdőlap",
    title_HPCCPlatformFiles: "ECL Watch - Fájlok",
    title_HPCCPlatformMain: "ECL Watch - Kezdőlap",
    title_HPCCPlatformOps: "ECL Watch - Műveletek",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch betölthető modulok",
    title_Inputs: "Bementek",
    title_LFDetails: "Logikai fájl információk",
    title_LibrariesUsed: "Felhasznált kódkönyvtárak",
    title_Log: "Log fájl",
    title_LostFilesFor: "Elveszett fájljai a(z)",
    title_LZBrowse: "Lerakatok",
    title_MemberOf: "Tagja a",
    title_Members: "Tagok",
    title_Methods: "Módszerek",
    title_OrphanFilesFor: "Elhagyott, árva fájljai a(z)",
    title_PackageParts: "Csomag részek",
    title_Permissions: "Hozzáférési jogok",
    title_Preflight: "Rendszer jellemzők",
    title_PreflightResults: "Az előkészítés eredménye",
    title_ProtectBy: "Által védett",
    title_QuerySetDetails: "Lekérdezés paraméterei",
    title_QuerySetErrors: "Hibák",
    title_QuerySetLogicalFiles: "Logikai fájlok",
    title_QuerySetQuery: "Lekérdezések",
    title_QuerySetSuperFiles: "Szuper fájlok",
    title_QueryTest: "Szuper fájlok",
    title_Result: "Tevékenység",
    title_Results: "Kimenet",
    title_SearchResults: "Keresés eredménye",
    title_SourceFiles: "Forrás fájlok",
    title_SystemServers: "Rendszer kiszolgálók",
    title_SystemServersLegacy: "Rendszer kiszolgálók (régebbi verzió)",
    title_TargetClusters: "Cél csoport",
    title_Topology: "Topológia",
    title_TpThorStatus: "Thor állapot",
    title_UserPermissions: "Felhasználó engedélyei",
    title_UserQuery: "Engedélyek",
    title_WorkunitScopeDefaultPermissions: "Alapértelmezett feladat hozzáfáresi jogok",
    title_WUDetails: "ECL feladat jellemzők",
    title_WUQuery: "ECL feladatok",
    TLS: "TLS",
    To: "-ig",
    ToDate: "Dátumig",
    Toenablegraphviews: "A gráfok megjelenítéshez telepiteni kell a &lsquo;Graph View Control&rsquo; bővítményt.",
    Tooltip: "Tipp",
    TooManyFiles: "Túl sok fájl",
    Top: "Felső",
    Topology: "Topológia",
    ToSizes: "Méretig",
    Total: "Összesen",
    TotalClusterTime: "Teljes cluster idő",
    TotalParts: "Az összes rész",
    TotalSize: "Összméret",
    TotalThorTime: "Összes Thor idő",
    ToTime: "Időre",
    TransitionGuide: "Átmenet útmutató",
    Tree: "Fa",
    Type: "Típus",
    Unbound: "bekötetlen",
    undefined: "nem definiált",
    Unknown: "Ismeretlen",
    Unlock: "Feloldott",
    Unprotect: "Védelem nélkül",
    UnsupportedIE9FF: "Nem támogatott böngészőprogram (IE <= 9, FireFox )",
    Unsuspend: "Folytat",
    Unsuspended: "Folytatva",
    Up: "Fel",
    UpdateCloneFrom: "Duplikátum frissítés forrása",
    UpdateDFs: "DFS frissítés",
    UpdateSuperFiles: "Szuper-fájl frissítés",
    Upload: "Feltöltés",
    Uploading: "Feltöltés",
    UpTime: "Az újraindítása óta eltelt idő",
    URL: "URL",
    Usage: "Használat",
    Used: "Használva",
    UsedByWorkunit: "Munkaegység által használt",
    User: "Felhasználó",
    UserDetails: "Felhasználó adatai",
    UserID: "Felhasználó azonosítója",
    UserLogin: "Kérem jelentkezzen be a felhasználói nevével",
    UserName: "Felhasználó neve",
    Username: "Felhasználó neve",
    UserPermissions: "Felhasználó engedélyei",
    Users: "Felhasználók",
    UseSingleConnection: "Egy kapcsolat használatával",
    Validate: "Ellenőriz",
    ValidateActivePackageMap: "Csomag-térkép ellenőrzés",
    ValidatePackageContent: "Csomag tartalom ellenőrzés",
    ValidatePackageMap: "Csomagtérkép ellenőrzés",
    ValidateResult: " =====Eredmény ellenőrzés=====",
    ValidateResultHere: "(Az ellenőrzés eredménye)",
    Validating: "Ellenőrzés folyamatban",
    ValidationErrorEnterNumber: "Adjon meg numerikus értéket",
    ValidationErrorExpireDaysMinimum: "Nem lehet kisebb, mint 1 nap",
    ValidationErrorNamePrefix: "Csak a 'valamilyen::előtag' használata engedélyezetett",
    ValidationErrorNumberGreater: "Nem lehet nagyobb, mint",
    ValidationErrorNumberLess: "Nem lehet kisebb, mint",
    ValidationErrorRecordSizeNumeric: "A rekord méret csak numerikus érték lehet",
    ValidationErrorRecordSizeRequired: "A rekord méret megadása kötelező",
    ValidationErrorRequired: "A mező használata kötelező",
    ValidationErrorTargetNameInvalid: "Érvénytelen fájl név",
    ValidationErrorTargetNameRequired: "Fájl név megadása kötelező",
    Value: "Érték",
    Variable: "Változó",
    VariableBigendian: "Big-endián változó",
    Variables: "Változók",
    VariableSourceType: "Forrás típus",
    Version: "Verzió",
    ViewByScope: "Megjelenítés hatókör szerint",
    Views: "Nézetek",
    ViewSparkClusterInfo: "Spark csoport információk",
    Visualizations: "Vizualizációk",
    Visualize: "Grafikus megjelenítés",
    WarnIfAvailableDiskSpaceIsUnder: "Figyelmeztetés, ha a szabad lemezkapacitás kevesebb mint",
    WarnIfAvailableMemoryIsUnder: "Figyelmeztetés, ha a rendelkezésre álló memória kevesebb mint",
    WarnIfCPUUsageIsOver: "Figyelmeztetés, ha a CPU használat magasabb mint",
    Warning: "Figyelmeztetés",
    Warnings: "Figyelmeztetések",
    WarnOldGraphControl: "Figyelem: A Graph Control modul elavult!",
    What: "Mit?",
    Where: "Hol?",
    Who: "Ki?",
    Width: "Szélesség",
    Workflows: "Munkafolyamat",
    Workunit: "Feladat",
    Workunits: "Feladatok",
    WorkUnitScopeDefaultPermissions: "Alapértelmezett feldolgozás-hatókör hozzáférési jogok",
    Wrap: "Csomagol (Wrap)",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid megadása kötelező!",
    WUSnapShot: "WU pillanatfelvétel",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "Keresztreferencia (XRef)",
    Year: "Év",
    YouAreAboutToBeLoggedOut: "Ön arra készül, hogy kilépjen a rendszerből",
    YouAreAboutToDeleteBinding: "Törölni készül egy kötést. Biztos, hogy folytatni akarja?",
    YouAreAboutToDeleteDefinition: "Ön ennek a definíciónak a törlésére készül. Biztos, hogy folytatni akarja?",
    YouAreAboutToDeleteThisFile: "Ennek a fájlnak a törlésére készül. Folytatja?",
    YouAreAboutToDeleteThisPart: "Ennek/ezeknek a fájl részeknek a törlésére készül. Folytatja?",
    YouAreAboutToDeleteThisQueryset: "Ennek a lekérdezés készletnek a törlésére készül. Folytatja?",
    YouAreAboutToDeleteThisWorkunit: "Ennek a munkaegységnek a törlésére készül. Folytatja?",
    YouAreAboutToRemoveUserFrom: "Ön felhasználó(k) csoportból való törlésére készül. Kívánja folytatni?",
    YourBrowserMayNotSupport: "Előfordulhat, hogy az Ön böngészőprogramja nem támogatja az ekkora méretű fájlokat.",
    YourScreenWasLocked: "Az ESP server befagyasztotta az ön képernyőjét. Kérem frissítsen.",
    ZAP: "Z.A.P.",
    ZeroLogicalFilesCheckFilter: "Nincs a megadott feltételnek megfelelő adat! (A jó a szűrőfeltétel?)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Tömörített elemzési csomag",
    Zoom: "Nagyítás",
    Zoom100Pct: "Nagyítás 100%-ra",
    ZoomAll: "Teljes gráf ablakba méretezése",
    ZoomMinus: "Kicsinyítés",
    ZoomPlus: "Nagyítás",
    ZoomSelection: "Nagyítás kiválasztása",
    ZoomWidth: "Gráf nagyítása az ablak szélességére"
}