define(
({
    Abort: "Prekinite",
    About: "O Aplikaciji",
    AboutGraphControl: "O Grafičkoj Kontroli",
    AboutHPCCSystemsGraphControl: "O Grafičkoj Kontroli HPCC Sistema",
    Action: "Akcija",
    Activate: "Aktivirajte",
    Activated: "Aktiviran",
    Active: "Aktivan",
    ActivePackageMap: "Aktivna Mapa Paketa",
    ActiveWorkunit: "Aktivna Radna Jedinica",
    Activities: "Aktivnosti",
    Activity: "Aktivnost",
    ActualSize: "Tačna Veličina",
    Add: "Dodajte",
    AddGroup: "Dodajte Grupu",
    AdditionalResources: "Dodatni Resursi",
    AddProcessMap: "Dodajte Mapu Paketa",
    AddToSuperfile: "Dodajte na Superdatoteku",
    AddUser: "Dodajte Korisnika",
    Advanced: "Višeg Nivoa",
    All: "Svi",
    AllowAccess: "<center>Dozvolite<br>Pristup</center>",
    AllowForeignFiles: "Dozvolite Korištenje  Datoteka Sa Drugih Klastera",
    AllowFull: "<center>Dozvolite<br>Potpun</center>",
    AllowRead: "<center>Dozvolite<br>Čitanje</center>",
    AllowWrite: "<center>Dozvolite<br>Pisanje</center>",
    ANY: "Bilo Koji",
    Append: "Dodajte",
    Apply: "Primjenite",
    ArchivedOnly: "Samo Arhiviran",
    ArchivedWarning: "Upozorenje: koristite kratak vremenski period. Ako koristite duži vremenski period, pretraživanje radnih jedinica može trajati duže od dozviljenog vremena za pretraživanje .",
    BinaryInstalls: "Binarne Instalacije",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefiks",
    Bottom: "Kraj",
    Cancel: "Poništite",
    Clear: "Očistite",
    ClearPermissionsCache: "Izbrišite Zapamćene Dozvole Za Pristup",
    ClearPermissionsCacheConfirm: "Da li ste sigurni da želite da izbrišete zapamćene dozvole za pristup na DALI i ESP? To može značajno usporiti izvršavanje radnih jedinica.",
    Clone: "Klonirajte",
    Close: "Zatvorite",
    Cluster: "Klaster",
    ClusterName: "Ime Klastera",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesi Na Klasteru",
    Code: "Kod",
    Col: "Kolona",
    CollapseAll: "Suzite sve",
    Command: "Komanda",
    Comment: "Komentar",
    Completed: "Kompletiran",
    Component: "Komponenta",
    Compress: "Sabijte",
    Compressed: "Komprimirani",
    Configuration: "Konfiguracija",
    ConfirmPassword: "Potvrdite Lozinku",
    Content: "Sadržaj",
    Contents: "Sadržaji",
    ContentType: "Vrsta Sadržaja",
    Copy: "Kopirajte",
    Count: "Izbrojte",
    Created: "Proizveden",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Datum",
    Day: "Dan",
    Deactivate: "Isključite",
    Debug: "Otklonite Neispravnosti",
    DEF: "DEF",
    Delete: "Obrišite",
    DeleteSelectedFiles: "Obrišite Odabrane Datoteke?",
    DeleteSelectedGroups: "Obrišite odabranu(e) grupu(e)?",
    DeleteSelectedPermissions: "Obrišite Odabrane Dozvole Za Pristup",
    DeleteSelectedQueries: "Obrišite Odabrane Zahtjeve?",
    DeleteSelectedUsers: "Obrišite Odabrane Korisnike?",
    DeleteSelectedWorkunits: "Obrišite Odabrane Radne Jedinice?",
    DeleteSuperfile: "Obrišite Superdatoteke?",
    DeleteThisPackage: "Obrišite ovaj paket?",
    Delimited: "Razgraničen",
    DenyAccess: "<center>Zabranite<br>Pristup</center>",
    DenyFull: "<center>Zabranite<br>Potpun</center>",
    DenyRead: "<center>Zabranite<br>Čitanje</center>",
    DenyWrite: "<center>Zabranite<br>Pisanje</center>",
    Depth: "Dubina",
    Deschedule: "Izbacite Is Reda Za Izvršavanje",
    DescheduleSelectedWorkunits: "Izbacite Odabrane Radne Jedinice Is Reda Za Izvršavanje?",
    Description: "Opis",
    Despray: "Ponovo Objedinite Datoteku",
    Details: "Detalji",
    DFUServerName: "Ime DFU Servera",
    Directory: "Direktorij",
    DisableScopeScanConfirm: "Da li ste sigurni da želite da onemogućite skaniranje opsega? Promjene će biti prihvaćene poslije restarta DALIja",
    DisableScopeScans: "Onemogućite Skaniranje Opsega",
    DiskUsage: "Iskorištenost Diska",
    Distance: "Razdaljina",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Atributi",
    Down: "Neaktivan",
    Download: "Dobavite",
    DropZone: "Zona Prijema",
    Duration: "Trajanje",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "Ivice",
    Edit: "Editujte",
    EditDOT: "Editujte DOT",
    EditGraphAttributes: "Editujte Atribute Grafova",
    EditXGMML: "Editujte XGMML",
    Empty: "(Prazan)",
    EnableScopeScans: "Omogućite Skaniranje Opsega",
    EnableScopeScansConfirm: "Da li ste sigurni da želite da omogućite skaniranje opsega? Promjene će biti prihvaćene poslije restarta DALIja",
    EnglishQ: "Engleski?",
    Error: "Greška",
    Errorparsingserverresult: "Greška u analizi rezultata sa servera",
    Errors: "Greška(e)",
    Errors: "Greške",
    ErrorsStatus: "Greške/Stanje",
    ErrorWarnings: "Greška/Upozorenja",
    Escape: "Escape",
    ESPBuildVersion: "ESP Trenutna Verzija",
    ESPNetworkAddress: "ESP Netvork Adresa",
    EventName: "Ime Događaja",
    EventNamePH: "imedogađaja",
    EventScheduler: "Raspoređivač Događaja",
    EventText: "Opis Događaja",
    EventTextPH: "Tekst O Događaju",
    Exception: "Neočekivani Problem",
    ExpandAll: "Proširite sve",
    FailIfNoSourceFile: "Neuspjeh Ukoliko Datoteka Ne Postoji",
    FetchingData: "U Procesu Dobavljnja Podataka...",
    fetchingresults: "dobijeni resultati",
    File: "Datoteka",
    FileCounts: "Broj Datoteka",
    FileName: "Ime Datoteke",
    FileParts: "Dio Datoteke",
    FilePath: "Lokacija Datoteke",
    Files: "Datoteke",
    FileSize: "Veličina Datoteke",
    FilesNoPackage: "Datoteke koje ne pripadaju paketu",
    FilesWithUnknownSize: "Datoteke Sa Nepoznatim Veličinama",
    FileType: "Tip Datoteke",
    FileUploader: "Proces za premiještanje Datoteke na Server (Uploader)",
    FileUploadStillInProgress: "Učitavanje Datoteka je u Toku",
    Filter: "Filter",
    Find: "Nađite",
    FindNext: "Nađite Slijedeći",
    FindPrevious: "Nađite Prethodni",
    FirstName: "Ime",
    Fixed: "Fiksni",
    Format: "Format",
    FromDate: "Od Datuma",
    FromSizes: "Od Veličine",
    FullName: "Ime i Prezime",
    Graph: "Graf",
    Graphs: "Grafikoni",
    GraphView: "Slika Grafikona",
    Group: "Grupa",
    GroupBy: "Grupišite Po",
    GroupDetails: "Detalji o Grupi",
    Grouping: "Grupisanje",
    GroupName: "Naziv Grupe",
    GroupPermissions: "Dozvole za Pristup Grupe",
    Groups: "Grupe",
    GZip: "GZip",
    help: "Ovdje je prikazan grafikon izvršavanja ove radne jedinice. Veličina i nijansa ukazuju na vrijeme izvršavanja svakog grafikona (Veći i tamniji grafikon uzima veći procenat cjelokupnog vremena izvrštavanja.)",
    Helpers: "Pomagači",
    Hex: "Baza16",
    High: "Visok",
    History: "Istorija",
    HPCCSystems: "HPCC Systems",
    ID: "Identifikator",
    Inactive: "Neaktivan",
    Index: "Indeks",
    Info: "Informacija",
    InfoDialog: "Dijalog Informacije",
    Inputs: "Unosi",
    InvalidResponse: "(Neispravan Odgovor)",
    IP: "IP",
    IPAddress: "IP Adresa",
    IsLibrary: "Jeli Biblioteka",
    Jobname: "Nazivradnejedinice",
    JobName: "Naziv Radne Jedinice",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Etiketa",
    LandingZone: "Zona za Pretovar",
    LandingZones: "Zone za Pretovar",
    LanguageFiles: "Datoteke O Jeziku",
    Largest: "Najveći",
    LargestFile: "Najveća Datoteka",
    LargestSize: "Najveća veličina",
    LastName: "Prezime",
    LastNDays: "Poslijednjih N Dana",
    LegacyForm: "Stari Prevaziđeni Formular",
    LibrariesUsed: "Biblioteke u Korištenju",
    Line: "Linija",
    LineTerminators: "Krajevi Linija",
    Links: "Linkovi",
    Loading: "Učitavanje...",
    LoadingCachedLayout: "Učitavanje Keširane Strukture (Cached Layout)...",
    LoadingData: "Učitavanje Podataka...",
    loadingMessage: "...Učitavanje...",
    Local: "Lokalni",
    LogFile: "Datoteka Aktivnosti",
    LoggedInAs: "Prijavljen kao",
    LogicalFile: "Logička Datoteka",
    LogicalFiles: "Logičke Datoteke",
    LogicalFilesAndSuperfiles: "Logičke Datoteke i Superdatoteke",
    LogicalFilesOnly: "Samo Logičke Datoteke",
    LogicalFileType: "Tip Logičke Datoteke",
    LogicalName: "Ime Logičke Datoteke",
    log_analysis_1: "log_analysis_1*",
    Low: "Nizak",
    ManualCopy: "Pritisnite Ctrl+C",
    Mappings: "Mapiranja",
    Mask: "Maska",
    Max: "Maksimum",
    MaxRecordLength: "Maksimalna Dužina Rekorda",
    MemberOf: "Član Od",
    Members: "Članovi",
    Message: "Poruke",
    Min: "Minimum",
    Missing: "Nedostaje",
    Modification: "Promijena",
    Modified: "Modifikovan",
    ModifiedUTCGMT: "Promijenjen (UTC/GMT)",
    Modify: "Promijeni",
    MonitorEventName: "Nadgledajte Ime Događaja",
    MonitorShotLimit: "Nadgledajte Shot Limit",
    MonitorSub: "Nadgledajte Sub",
    Month: "Mjesec",
    MustContainUppercaseAndSymbol: "Mora uključiti veliko slovo i simbol",
    NA: "N/A",
    Name: "Ime",
    NamePrefix: "Prefiks Imena",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Najnoviji",
    NewPassword: "Nova Lozinka",
    NoContent: "(Bez sadržaja)",
    noDataMessage: "...Nema Redova...",
    Node: "Čvor (Node)",
    NodeGroup: "Grupa Čvorova",
    NoErrorFound: "Bez nađenih grešaka\n",
    NoFilterCriteriaSpecified: "Kriterij za filtriranje nije specificiran.",
    None: "Nijedan",
    Normal: "Normalan",
    NoScheduledEvents: "Nema Definisanih Događaja na Rasporedu.",
    NoSplit: "Nema Podijela (Split)",
    NotActive: "Nije Aktivan",
    NothingSelected: "Ništa Nije Izabrano...",
    NotInSuperfiles: "Nije Dio Superdatoteke",
    NotSuspendedbyUser: "Nije Suspendovan Od Strane Korisnika",
    NoWarningFound: "Poruke Upozorenja (warnings) nisu nađene\n",
    NumberofParts: "Broj Dijelova",
    OK: "OK",
    Oldest: "Najstariji",
    OmitSeparator: "Izostavite Separator",
    Only1PackageFileAllowed: "Dozvoljen je samo jedan paket",
    Open: "Otvoren",
    OpenInNewPage: "Otvorite na Novoj Stranici",
    OpenInNewPageNoFrame: "Otvorite na Novoj Stranici",
    OpenLegacyECLWatch: "Otvorite Stari Prevaziđeni ECL Watch",
    OpenSafeMode: "Otvorite (sigurni mod)",
    OpenTreeMode: "Otvorite (kao stablo)",
    OpenSource: "Otvoreni Kod",
    Operations: "Operacije",
    Options: "Opcije",
    Outputs: "Izlazi",
    Overview: "Pregled",
    Overwrite: "Prepišite",
    Owner: "Vlasnik",
    PackageContent: "Sadržaj Paketa",
    PackageContentNotSet: "Sadržaj Paketa nije definisan",
    PackageMap: "Mapa Paketa",
    PackageMaps: "Mape Paketa",
    PackagesNoQuery: "Paketi za koje nisu definisani upiti (queries)",
    ParameterXML: "Parametar XML",
    Part: "Dio",
    Parts: "Dijelovi",
    Password: "Lozinka",
    PasswordExpiration: "Lozinka Istiće",
    PasswordExpirePostfix: "dan(a). Želite li je sada promijeniti?",
    PasswordExpirePrefix: "Vaša lozinka će isteći za",
    PasswordsDoNotMatch: "Pogrešna Lozinka.",
    Path: "Put",
    PathMask: "Maska za Put",
    Pause: "Pauza",
    PctComplete: "% Kompletiran",
    PercentDone: "Procenat Završen",
    PerformingLayout: "Izvršava Layout...",
    PermissionName: "Naziv Dozvole Za Pristup",
    Permissions: "Dozvole za Pristup",
    PlaceholderFindText: "Wuid, Korisnik, Dalje...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Igralište",
    Port: "Port",
    Prefix: "Prefiks",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preview: "Pregled",
    Priority: "Prioritet",
    Process: "Proces",
    ProcessFilter: "Process&nbsp;Filter",
    ProgressMessage: "Poruka o Progresu",
    Properties: "Svojstva",
    Property: "Svojstvo",
    Protect: "Zaštitite",
    Protected: "Zašticen",
    Publish: "Objavite",
    PublishedBy: "Objavljivač",
    PublishedQueries: "Objavljeni Upiti",
    PushEvent: "Puš Događaj",
    Quarter: "Četvrtina",
    Queries: "Upiti",
    QueriesNoPackage: "Upiti bez odgovarajućeg paketa",
    QueryDetailsfor: "Detalji o Upitu",
    QuerySet: "Kolekcija Upita",
    Queue: "Red (Queue)",
    Quote: "Citat",
    RecordCount: "Broj Rekorda",
    RecordLength: "Dužina Rekorda",
    Records: "Rekordi",
    RecordSize: "Veličina Rekorda",
    RecordStructurePresent: "Struktura Rekorda Postoji",
    Refresh: "Osviježite",
    ReleaseNotes: "Napomena o Izdanju",
    Reload: "Ponovo Učitajte",
    Remaining: "Preostali",
    RemoteDali: "Daleki Dali",
    RemoteDaliIP: "Daleki&nbsp;Dali&nbsp;IP&nbsp;Adresa",
    Remove: "Uklonite",
    Rename: "Preimenujte",
    RenderedSVG: "Donesene SVG",
    RenderSVG: "Donesite SVG",
    Replicate: "Replicirajte",
    RequestSchema: "Shema Zahtjeva",
    Reschedule: "Ponovo Stavite Na Raspored",
    Reset: "Resetujte",
    Resource: "Resurs",
    Resources: "Resursi",
    ResponseSchema: "Shema Odgovora",
    Restart: "Ponovo Pokrenite",
    Restore: "Vratite na Staro Stanje",
    Resubmit: "Ponovo Podnesite",
    Results: "Rezultat(i)",
    Resume: "Nastavite",
    RetainSuperfileStructure: "Zadržite Strukturu Superdatoteke",
    RetypePassword: "Ponovite Lozinku",
    Rows: "Redovi",
    RowTag: "Etiketa Reda",
    RoxieCluster: "Roxie Klaster",
    Sample: "Primjer",
    SampleRequest: "Primjer Zahtjeva",
    SampleResponse: "Primjer Odgovora",
    Save: "Sačuvajte",
    Scope: "Područje",
    SearchResults: "Rezultati Pretraživanja",
    SecondsRemaining: "Preostalo Sekundi",
    SelectPackageFile: "Izaberi Paket",
    Seperators: "Seperatori",
    SetBanner: "Postavite Zastavicu",
    SetTextError: "Neuspješno prikazivanje teksta (da li je tekst predug?). Koristite 'pomagače' za preuzimanje datoteka.",
    SetToFailed: "Postavite Na Neuspješan",
    Severity: "Ozbiljnost",
    Show: "Pokažite",
    ShowSVG: "Pokažite SVG",
    Size: "Veličina",
    Skew: "Skju (Skew)",
    SLA: "SLA",
    Slaves: "Robovi (Slaves)",
    Smallest: "Najmanji",
    SmallestFile: "Najmanja Datoteka",
    SmallestSize: "Najmanja Veličina",
    SOAP: "SOAP",
    SomeDescription: "Neki*Opis",
    somefile: "*::nekifile*",
    Source: "Izvorna Verzija",
    SourceCode: "Izvorna Verzija Koda",
    SourcePath: "Izvorna Verzija Puta (sa omogucenim *)",
    SourceProcess: "Izvorni Proces",
    SplitPrefix: "Split Prefiks",
    Spray: "Razbacajte (Spray)",
    Start: "Počnite",
    Started: "Počeo",
    State: "Stanje",
    Stopped: "Zaustavljen",
    Subgraph: "Pod-Graf",
    Subgraphs: "Podgrafikon",
    Submit: "Podnesite",
    Subtype: "Pod-Vrsta",
    Summary: "Kratak Pregled",
    SummaryMessage: "Sažeta Poruka",
    SuperFile: "Super Datoteka",
    Superfile: "Super Datoteka",
    SuperFiles: "Super Datoteke",
    SuperfilesOnly: "Samo Superdatoteke",
    Suspend: "Suspendujte",
    Suspended: "Suspendovan",
    SuspendedBy: "Suspendovan Od",
    SuspendedByUser: "Suspendovan Od Strane Korisnika",
    SuspendedReason: "Razlog za Suspendovanje",
    SVGSource: "SVG Izvor",
    SyncSelection: "Sinhronizujte Sa Odabranim",
    SystemServers: "Sistem Servera",
    tag: "tag",
    Target: "Cilj",
    TargetClusters: "Ciljni Klasteri",
    TargetName: "Naziv Cilja",
    TargetNamePlaceholder: "neko::logicko::ime",
    TargetWuid: "Cilj/Wuid",
    Terminators: "Terminatori",
    TestPages: "Test Stranice",
    ThorMasterAddress: "Adresa Glavnog Thora",
    ThorNetworkAddress: "Netvork Adresa Thora",
    Time: "Vrijeme",
    Timers: "Mjerači Vremena",
    TimeSeconds: "Vrijeme (Sekunde)",
    TimeStarted: "Vrijeme Početka",
    TimeStopped: "Vrijeme Kraja",
    Timings: "Vremena",
    TimingsMap: "Mapa Vremena",
    title_Activity: "Aktivnosti",
    title_ClusterInfo: "Grupe",
    title_DFUQuery: "Logičke Datoteke",
    title_DFUWUDetails: "DFU Radna Jedinica",
    title_DiskUsage: "Iskorištenost Diska",
    title_ECLPlayground: "ECL Igralište",
    title_EventScheduleWorkunit: "Respoređivač Događaja",
    title_GetDFUWorkunits: "DFU Radne Jedinice",
    title_Graph: "Grafikon",
    title_GraphPage: "naslov",
    title_Graphs: "Grafikoni",
    title_GridDetails: "Promijeni Me",
    title_HPCCPlatformECL: "HPCC Platform - Glavna Stranica",
    title_HPCCPlatformFiles: "HPCC Platform - Datoteke",
    title_HPCCPlatformMain: "HPCC Platform - Glavna Stranica",
    title_HPCCPlatformOps: "HPCC Platform - Upravljnje",
    title_HPCCPlatformRoxie: "HPCC Platform - Roxie",
    title_Inputs: "Unosi",
    title_LFDetails: "Detalji o Logičkol Datoteci",
    title_LZBrowse: "Zona za Pretovar",
    title_MemberOf: "Član Od",
    title_Members: "Članovi",
    title_QuerySetDetails: "Detalji Upita",
    title_QuerySetErrors: "Greške",
    title_QuerySetLogicalFiles: "Logičke Datoteke",
    title_QuerySetQuery: "Upiti (Queries)",
    title_QuerySetSuperFiles: "Super Datoteke",
    title_QueryTest: "Super Datoteke",
    title_Result: "Acktivnost",
    title_Results: "Rezultati",
    title_SearchResults: "Rezultati Pretraživanja",
    title_SourceFiles: "",
    title_SourceFiles: "",
    title_TpThorStatus: "Stanje Thora",
    title_UserPermissions: "Korisničke Dozvile za Pristup",
    title_UserQuery: "Prava Pristupa",
    title_WUDetails: "ECL Detalji o Radnoj Jedinici",
    title_WUQuery: "ECL Radne Jedinice",
    ToDate: "Do Sada",
    Toenablegraphviews: "Da biste mogli vidjeli grafikone, moraćete instalisati Graph View Control plugin",
    Top: "Vrh",
    ToSizes: "Do Velićina",
    TotalSize: "Totalna Veličina",
    TotalThorTime: "Ukupno Vrijeme Thor-a",
    Tree: "Drvo",
    Type: "Tip",
    undefined: "nedefinisan",
    Unknown: "Nepoznat",
    Unprotect: "Ukinite Zaštitu",
    Unsuspend: "Ukinite Suspenziju",
    Unsuspended: "Suspenzija Ukinuta",
    Up: "Na Gore",
    Upload: "Upload",
    Usage: "Upotreba",
    Used: "Korišten",
    User: "Korisnik",
    UserDetails: "Detalji o Korisniku",
    UserID: "Korisnicki ID",
    Username: "Imekorisnika",
    UserName: "Ime Korisnika",
    UserPermissions: "Dozvole za Korisnikov Pristup",
    Users: "Korisnici",
    UseSingleConnection: "Koristite Samo Jedan Priključak (Connection)",
    Validate: "Potvrdite",
    ValidatePackageMap: "Potvrdite Mapu Paketa",
    ValidateResult: "=====Potvrdite Result=====\n\n",
    Value: "Vrijednost",
    Variable: "Varijabla",
    VariableBigendian: "Varijabla Big-endian",
    Variables: "Varijable",
    VariableSourceType: "Tip Izvora",
    Version: "Verzija",
    Views: "Pogledi",
    Visualize: "Visualizujte",
    Warnings: "Upozorenje(a)",
    WarnOldGraphControl: "Upozorenje:  Stara Grafička Kontrola",
    What: "Šta",
    Where: "Gdje",
    Who: "Ko",
    Width: "Širina",
    Workflows: "Tokovi poslova",
    Workunit: "Radna Jedinica",
    Workunits: "Radne Jedinice",
    Wrap: "Zamotajte",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Ne Može Biti Prazan.",
    WUSnapShot: "Trenutna Slika Radne Jedinice",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Godina",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nema ni jedane Logičke Datoteke(provjerite filter)",
    Zip: "Zapakujte (Zip)",
    ZippedAnalysisPackage: "Zapakovani Paket sa Analizama",
    Zoom100Pct: "Zumirajte 100%",
    ZoomAll: "Zumirajte Sve",
    ZoomWidth: "Zumirajte Širinu"
})
);
