# Overrides for efs storage in hpcc, using custom StorageClass'
# NB: The "hpcc-efs" helm charts should be installed 1st.
# The "hpcc-efs" helm chart provisions and creates the
# PVC's required by HPCC.
# The pvc names are dynamic based on the install name.
# In this example the install name was "awsstorage"

storage:
  planes:
  - name: dali
    pvc: dali-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/dalistorage"
    category: dali

  - name: dll
    pvc: dll-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/queries"
    category: dll

  - name: sasha
    pvc: sasha-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/sasha"
    category: sasha

  - name: data
    pvc: data-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/hpcc-data"
    category: data

  - name: mydropzone
    pvc: mydropzone-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/mydropzone"
    category: lz

sasha:
  wu-archiver:
    plane: sasha
  dfuwu-archiver:
    plane: sasha
