# Overrides for efs storage in hpcc, using custom StorageClass'
# NB: The "hpcc-efs" helm charts should be installed 1st.
# The "hpcc-efs" helm chart provisions and creates the
# PVC's required by HPCC.
# The pvc names are dynamic based on the install name.
# In this example the install name was "awsstorage"

storage:
  planes:
  - name: dali
    pvc: dali-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/dalistorage"
    labels:
    - dali

  - name: dll
    pvc: dll-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/queries"
    labels:
    - dll

  - name: sasha
    pvc: sasha-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/sasha"
    labels:
    - sasha

  - name: data
    pvc: data-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/hpcc-data"
    labels:
    - data # NB: if not set, this would be the default

  - name: dropzone
    pvc: dropzone-awsstorage-hpcc-efs-pvc
    prefix: "/var/lib/HPCCSystems/dropzone"
    labels:
    - lz # NB: if not set, this would be the default


  dllStorage:
    plane: dll

  daliStorage:
    plane: dali

  dataStorage:
    plane: data

  dropzoneStorage:
    plane: dropzone

sasha:
  wu-archiver:
    storage:
      plane: sasha
  dfuwu-archiver:
    storage:
      plane: sasha
