export = {
    Abort: "Abortar",
    AbortedBy: "Abortado pelo",
    AbortedTime: "Hora de Abortar",
    AbortSelectedWorkunits: "Abortar unidade(s) de trabalho selecionada(s)? Seu ID de login será registrado para esta ação no(s) WU(s).",
    About: "Sobre Plataforma HPCC",
    AboutGraphControl: "Sobre Controle de Gráphico",
    AboutHPCCSystems: "Sobre HPCC Systems",
    AboutHPCCSystemsGraphControl: "Sobre Controle de Gráphico do HPCC Systems®",
    AboutToLoseSessionInformation: "Você está prestes a sair e perder todas as informações da sessão. Você deseja continuar?",
    Account: "Conta",
    Action: "Ação",
    Activate: "Ativar",
    Activated: "Ativa",
    ActivateQuery: "Ativar Consulta",
    ActivateQueryDeletePrevious: "Ativar consulta, excluir anterior",
    ActivateQuerySuspendPrevious: "Ativar consulta, suspender anterior",
    Active: "Ativa",
    ActivePackageMap: "Package Map Ativo",
    ActiveWorkunit: "Tarefa Ativa",
    Activities: "Atividades",
    Activity: "Atividade",
    ActivityLabel: "Etiqueta de atividade",
    ActivityMap: "Mapa de Atividade",
    ActualSize: "Tamanho Efectivo",
    Add: "Adicionar",
    AddAttributes: "Adiciona atributos/valores para seu métedo",
    AddAttributes2: "Adiciona atributos",
    AddBinding: "Adiciona ligação",
    AddFile: "Adicionar Arquivo",
    AddGroup: "Adicionar Grupo",
    AdditionalResources: "Recursos Adicionais",
    AddPart: "Adicionar Parte",
    AddProcessMap: "Adicionar Package Map",
    AddTheseFilesToDali: "Adicionar esses arquivos a Dali",
    AddtionalProcessesToFilter: "Processos adicionais para filtrar",
    AddToExistingSuperfile: "Adicionar a um superfile existente",
    AddToFavorites: "Adicionar aos favoritos",
    AddToSuperfile: "Adicionar ao Superarquivo",
    AddUser: "Adicionar Usuário",
    Advanced: "Avançado",
    Age: "Idade",
    All: "Todos",
    AllowAccess: "Permitir Acesso",
    AllowForeignFiles: "Permitir Arquivos Remotos",
    AllowFull: "Permissão Total",
    AllowRead: "Permissão de Leitura",
    AllowWrite: "Permissão de Escrita",
    AllQueries: "Todas as Consultas",
    AllQueuedItemsCleared: "Todos os itens em fila foram apagados. O trabalho em execução atual continuará a ser rodado",
    Analyze: "Analisar",
    ANY: "Qualquer",
    AnyAdditionalProcessesToFilter: "Quaisquer processos adicionais para filtrar",
    Append: "Anexar",
    AppendCluster: "Acrescentar o Cluster",
    Apply: "Aplicar",
    Apps: "Apps",
    ArchivedOnly: "Apenas Arquivadas",
    ArchivedWarning: "Aviso: Por favor especifique intervalos de datas menore. Caso contrário, a operação para buscar workunits pode demorar causando um erro no navegador.",
    AreYouSureYouWantToResetTheme: "Tem certeza de que deseja redefinir o tema padrão?",
    Attach: "Anexar",
    Attribute: "Attributo",
    AttributesAreRequired: "Atributos são necessários",
    Audience: "Público",
    AuditLogs: "Registro de auditoria",
    AutoRefresh: "Recarregar Automático",
    AutoRefreshEvery: "Atualização automática a cada x minutos",
    AutoRefreshIncrement: "Auto Incrementar Atualização",
    Back: "voltar",
    BannerColor: "Cor da Faixa",
    BannerMessage: "Mensagem da Faixa",
    BannerScroll: "Faixa de Paginação",
    BannerSize: "Tamanho da Faixa",
    BinaryInstalls: "Instalação Binária",
    Bind: "Ligar",
    Binding: "Ligação",
    BindingDeleted: "Ligação deletado",
    Blob: "BLOB",
    BlobPrefix: "Prefixo do BLOB",
    Blobs: "BLOBS",
    Blooms: "Blooms",
    Bottom: "fundo",
    BoundBy: "vinculado pela:",
    Branches: "Galhos",
    BrowserStats: "Estatísticas do navegador",
    Busy: "Ocupado",
    CallerID: "Identidade de chamador",
    Cancel: "Cancelar",
    CancelAll: "Cancela tudo",
    CancelAllMessage: "Abortar trabalhos em execução e limpar a fila. Você deseja continuar?",
    Category: "Categoria",
    Channel: "Canal",
    Chart: "Gráfico",
    CheckAllNodes: "Verifique Todos os Nós",
    CheckFilePermissions: "Verifique Permissão de Arquivo",
    CheckSingleNode: "Verifique Nó Singular",
    Class: "Classe",
    Clear: "Limpar",
    ClearPermissionsCache: "Limpar Cache de Permissões",
    ClearPermissionsCacheConfirm: "Tem certeza que você quer limpar todos os caches de permissões dos servidores DALI e ESP? Workunits em execução podem ter a performance significantemente prejudicadas até que os caches tenham sido recarregados.",
    Client: "Cliente",
    Clone: "Clonar",
    ClonedWUID: "WUID clonado",
    CloneTooltip: "Unidade de Trabalho Duplicado",
    Close: "Fechar",
    CloseModal: "Fechar modal popup",
    Cluster: "Cluster (Aglomerado)",
    ClusterName: "Nome do Aglomerado (Cluster)",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Processos de Aglomerados",
    Code: "Código",
    CodeGenerator: "Gerador de Código",
    Col: "Col",
    CollapseAll: "Recolher Tudo",
    Columns: "Colunas",
    Command: "Comando",
    Comment: "Comentário",
    CompileCost: "Custo de compilação",
    Compiled: "Compilado",
    Compiling: "Compilando",
    Completed: "Completo",
    ComplexityWarning: "Mais de {limite} atividades ({Contador de atividades}) - suprimir amostragem inicial?",
    Component: "Componente",
    ComponentLogs: "Log de componentes",
    Compress: "Compactar",
    Compressed: "Comprimido",
    CompressedFileSize: "Tamanho do Arquivo Comprimido",
    CompressedSize: "Tamanho comprimido",
    Compression: "Compressão",
    ComputerUpTime: "Tempo do Computador Ativo",
    Condition: "Condição",
    Configuration: "Configuração",
    ConfigureService: "Configurar serviço",
    ConfirmPassword: "Confirmar Senha",
    ConfirmRemoval: "Tem certeza que quer fazer isso?",
    ContactAdmin: "Se você deseja renomear este grupo, por favor, entre em contato com o administrador do LDAP",
    Container: "Pacote",
    ContainerName: "Nome do Pacote",
    Content: "Conteúdo",
    Contents: "Conteúdo",
    ContentType: "Tipo de Conteúdo",
    ContinueWorking: "Contínua Trabalhando",
    CookiesAcceptButtonText: "Permitir Cookies",
    CookiesNoticeLinkText: "Nossa notificação de cookies",
    Copied: "Copiado!",
    Copy: "Copiar",
    CopyLogicalFilename: "Copiar Nome do Arquivo Lógico",
    CopyLogicalFiles: "Copiar arquivos lógicos para a área de transferência",
    CopySelectionToClipboard: "Copiar seleção para a área de transferência",
    CopyToClipboard: "Copiar para área de transferência",
    CopyURLToClipboard: "Copiar URL para a área de transferência",
    CopyWUID: "Copiar WUID",
    CopyWUIDs: "Copiar WUIDs para a área de transferência",
    CopyWUIDToClipboard: "Copiar WUID para a área de transferência",
    Cost: "Custo",
    Count: "Conta",
    CountFailed: "Contagem Falhou",
    CountTotal: "Contagem Total",
    CPULoad: "Carga do CPU ",
    Create: "Criar",
    CreateANewFile: "Criar um novo superfile",
    Created: "Criado",
    CreatedBy: "Criado Por",
    CreatedByWorkunit: "Criado por workunit",
    CreatedTime: "Tempo Criado",
    Creating: "Criando",
    Critical: "Crítico",
    CrossTab: "Tabulação Cruzada",
    CSV: "CVS",
    Dali: "Dali",
    DaliAdmin: "Administrador de Dali",
    DaliIP: "IP do Dali",
    Dashboard: "Painel",
    Data: "Dados",
    DataPatterns: "Padrões de Dados",
    DataPatternsDefnNotFound: "Definição de arquivo não encontrada. Os padrões de dados não podem ser iniciados",
    DataPatternsNotStarted: "Análise não encontrada. Para começar, pressione o botão Analisar acima.",
    DataPatternsStarted: "Analisando. Quando o relatório for completo, vai ser exibido aqui.",
    dataset: ":=dataset*",
    Date: "Data",
    Day: "Dia",
    Deactivate: "Desativar",
    Debug: "Debug",
    DEF: "DEF",
    Defaults: "Padrões",
    Definition: "Definição",
    DefinitionDeleted: "Definição deletada",
    DefinitionID: "Identidade de definição",
    Definitions: "Definições",
    DelayedReplication: "Replicação atrasada",
    Delete: "Remover",
    DeleteBinding: "Apagar Ligação",
    Deleted: "Removido",
    DeletedBinding: "Ligação Apagado",
    DeleteDirectories: "Remover diretórios vazios. Você deseja continuar?",
    DeleteEmptyDirectories: "Excluir diretórios vazios?",
    DeletePrevious: "Apagar Anterior",
    DeleteSelectedDefinitions: "Deletar definições selecionadas?",
    DeleteSelectedFiles: "Apagar Arquivos Selecionados?",
    DeleteSelectedGroups: "Remover Grupos Selecionados",
    DeleteSelectedPackages: "Excluir pacotes selecionados?",
    DeleteSelectedPermissions: "Remover Permissões Selecionadas",
    DeleteSelectedQueries: "Apagar Consultas Selecionadas?",
    DeleteSelectedUsers: "Remover Usuários Selecionados",
    DeleteSelectedWorkunits: "Apagar Tarefas Selecionadas?",
    DeleteSuperfile: "Apagar Super Arquivo?",
    DeleteSuperfile2: "Remover Super Arquivo",
    DeleteThisPackage: "Remover Este Pacote",
    Delimited: "Delimitado",
    DenyAccess: "Bloquear",
    DenyFull: "Bloquear Completamente",
    DenyRead: "Bloquear Leitura",
    DenyWrite: "Bloquear Escrita",
    Depth: "Profundidade",
    DepthTooltip: "Profundidade Máxima de Subgrafo",
    Deschedule: "Desagendar",
    DescheduleSelectedWorkunits: "Desagendar Unidades de Trabalho Selecionadas",
    Description: "Descrição",
    DESDL: "Dynamic ESDL",
    Despray: "Despray (Consolidar Dados dos Nós)",
    Details: "Detalhes",
    DFSCheck: "Verificação DFS",
    DFSExists: "DFS existe",
    DFSLS: "DFS LS",
    DFUServerName: "Nome do Servidor DFU",
    DFUWorkunit: "DFU Unidade de Trabalho",
    Directories: "Diretórios",
    Directory: "Diretório",
    DisableScopeScanConfirm: "Tem certeza que quer desabilitar busca de escopo? Alterações de configuração serão aplicadas quando DALI reiniciar.",
    DisableScopeScans: "Desabilitar busca de escopo",
    DiskSize: "Tamanho do disco",
    DiskUsage: "Uso de disco",
    Distance: "Distancia",
    DistanceTooltip: "Distância a vizinhança de máxima atividade",
    Dll: "Dll (Biblioteca de Vínculo Dinâmico)",
    Documentation: "Documentação",
    Domain: "Domínio",
    DoNotActivateQuery: "Não ative a consulta",
    DoNotRepublish: "Não republicar?",
    DOT: "DOT",
    DOTAttributes: "Propriedades de DOT",
    Down: "Pra baixo",
    Download: "Baixar",
    Downloads: "Abaixamentos",
    DownloadSelectionAsCSV: "Baixar seleção como CSV",
    DownloadToCSV: "Transferir para o CSV",
    DownloadToCSVNonFlatWarning: "Observação: o download de arquivos CVS pode não ser formatado como esperado",
    DropZone: "Zona de entrada de arquivos",
    DueToInctivity: "Você será desconectado de todas as sessões do ECL Watch em 3 minutos devido a inatividade.",
    Duration: "Duração",
    DynamicNoServicesFound: "Nenhum Serviço Encontrado",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWatchRequiresCookies: "O ECL Watch requer cookies habilitados para continuar.",
    ECLWatchSessionManagement: "Gerenciamento de sessão do ECL Watch",
    ECLWorkunit: "ECL Unidade de Trabalho",
    EdgeLabel: "Rótulo de Borda",
    Edges: "Bordas",
    Edit: "Alterar",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar Propriedades do Gráfico",
    EditXGMML: "Editar XGMML",
    EmailBody: "Corpo do email",
    EmailFrom: "Endereço de email (de)",
    EmailSubject: "Assunto do email",
    EmailTo: "Endereço de email (para)",
    EmployeeID: "ID do Empregado",
    EmployeeNumber: "Número de empregado",
    Empty: "Vazio",
    Enable: "Ativar",
    EnableBannerText: "Ativar Texto do Ambiente",
    EnableScopeScans: "Ativar busca de escopo",
    EnableScopeScansConfirm: "Tem certeza que gostaria de ativar busca de escopo? Alterações serão aplicadas quando DALI reiniciar.",
    EndPoint: "Ponto Final",
    EndTime: "Fim do Tempo",
    EnglishQ: "Inglês?",
    EnterAPercentage: "Digite uma porcentagem",
    EnterAPercentageOrMB: "Digite uma porcentagem ou MB",
    EraseHistory: "Apagar História",
    EraseHistoryQ: "Apagar o histórico para",
    Error: "Erro",
    Errorparsingserverresult: "Erro interpretando o resultado do servidor",
    Errors: "Erros",
    ErrorsStatus: "Erros/Estados",
    ErrorUploadingFile: "Erro ao carregar arquivos. Tente verificar permissões.",
    ErrorWarnings: "Error/Aviso(s)",
    Escape: "Escapar",
    ESPBindings: "Ligações ESP",
    ESPBuildVersion: "Versão‎ do ESP",  // jshint ignore:line
    ESPNetworkAddress: "Endereço de Rede do ESP",
    ESPProcessName: "Nome do Processo ESP",
    EventName: "Nome do Evento",
    EventNamePH: "Nome do Evento",
    EventScheduler: "Gerenciador de Evento",
    EventText: "Texto do Evento",
    EventTextPH: "Texto do Evento",
    Exception: "Exceção",
    ExcludeIndexes: "Excluir índices",
    ExecuteCost: "Custo de Execução",
    Executed: "Executado",
    Executing: "Executando",
    ExpandAll: "Expandir Tudo",
    ExpirationDate: "Data de validade",
    ExpireDays: "Expira em (dias)",
    Export: "Exportar",
    ExportSelectionsToList: "Exportar Seleções para Lista",
    FailIfNoSourceFile: "Falha em caso de arquivo sem fonte",
    Fatal: "Fatal",
    Favorites: "Favoritos",
    Fetched: "Buscado",
    FetchingData: "Buscando dados...",
    fetchingresults: "Buscando Resultados",
    FieldNames: "Nomes dos Campos",
    File: "Arquivo",
    FileAccessCost: "Custo de Acesso ao Arquivo",
    FileCluster: "Arquivos Cluster",
    FileCostAtRest: "Custo do Arquivo em Repouso",
    FileCounts: "Número de Arquivos",
    FileName: "Nome do Arquivo",
    FileParts: "Partes do Arquivo",
    FilePath: "Caminho e nome do Arquivo",
    FilePermission: "Permissão de Arquivo",
    Files: "Arquivos",
    FileScopeDefaultPermissions: "Permissão Padrão de Arquivo Escopo",
    FileScopes: "Escopo de arquivos",
    FileSize: "Tamanho do Arquivo",
    FilesNoPackage: "Arquivos sem definição de pacotes.",
    FilesPending: "Arquivos pendentes",
    FilesWarning: "O número de arquivos retornados é muito grande. Apenas os primeiros 100.000 arquivos classificados por data / hora modificados foram retornados. Se você deseja limitar os resultados, defina um filtro.",
    FilesWithUnknownSize: "Arquivos com tamanho desconhecido",
    FileType: "Tipo de Arquivo",
    FileUploader: "Uploader(Enviador) de Arquivo",
    FileUploadStillInProgress: "Carregamento de Arquivo em andamento",
    Filter: "Filtro",
    FilterDetails: "Detalhes do Filtro",
    FilterSet: "Conjunto Filtro",
    Find: "Busca",
    FindNext: "Próxima Busca",
    FindPrevious: "Busca Anterior",
    Finished: "Completo",
    FirstN: "Primeiro N",
    FirstName: "Primeiro Nome",
    FirstNRows: "Primeiras N Linhas",
    FirstNSortBy: "Ordenar por",
    Fixed: "Fixo",
    Folder: "Pasta",
    Form: "Formulário",
    Format: "Formato",
    Forums: "Bate Papos",
    Forward: "Avançar",
    FoundFile: "Arquivo Encontrado",
    FoundFileMessage: "Um arquivo encontrado tem todas as suas partes no disco que não são referenciadas no servidor Dali. Todas as partes do arquivo são contabilizadas para que possam ser adicionadas de volta ao servidor Dali. Eles também podem ser excluídos do cluster, se for necessário.",
    FromDate: "Data Inicial",
    FromSizes: "Tamanho Mínimo",
    FromTime: "Tempo inicial",
    FullName: "Nome Completo",
    Generate: "Gerar",
    GetDFSCSV: "DFS CSV",
    GetDFSMap: "Mapa DFS",
    GetDFSParents: "Parentes DFS",
    GetLogicalFile: "Arquivo Lógico",
    GetLogicalFilePart: "Parte do Arquivo Lógico",
    GetPart: "Obter Parte",
    GetProtectedList: "Lista Protegida",
    GetSoftwareInformation: "Obter Informações de Software",
    GetValue: "Valor",
    Graph: "Grafo",
    GraphControl: "Controle Gráfico",
    Graphs: "Gráficos",
    GraphView: "Visão Gráfica",
    Group: "Grupo",
    GroupBy: "Agrupado por",
    GroupDetails: "Detalhe de Grupo",
    Grouping: "Agrupar",
    GroupName: "Nome do Grupo",
    GroupPermissions: "Permissões de Grupo",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Essa area exibi o mapas de arvores (hierarquias) para o gráfico dessa tarefa. O tamanho e cor indicam a duração de cada gráfico (Quanto maior e mais escuro mais tempo levou)",
    Helper: "Ajudante",
    Helpers: "Ajudantes",
    Hex: "Hex",
    HexPreview: "Pré-visualização Hex",
    HideSpills: "Esconde Derramamentos",
    High: "Alto",
    History: "História",
    Homepage: "Pagina Inicial",
    Hotspots: "Pontos Ativos",
    HPCCSystems: "HPCCSystems",
    HTML: "HTML",
    Icon: "Ícone",
    ID: "Identidade",
    IFrameErrorMsg: "Não foi possível carregar o quadro, tente novamente.",
    IgnoreGlobalStoreOutEdges: "Ignorar Global Store Out Edges",
    Import: "Importar",
    Inactive: "Inativo",
    IncludeSlaveLogs: "Incluie logs escravos",
    IncludeSubFileInfo: "Incluir informações de subarquivo?",
    Index: "Índice",
    Indexes: "Índices",
    IndexesOnly: "Somente Índices",
    Info: "Info",
    InfoDialog: "Caixa de Informação",
    Informational: "Informativo",
    Infos: "Informação(s)",
    InheritedPermissions: "Permissão Herdada",
    Inputs: "Insumos",
    InUse: "Em uso",
    InvalidResponse: "(resposta inválida)",
    InvalidUsernamePassword: "Nome de usuário ou senha inválidos, tente novamente.",
    IP: "IP",
    IPAddress: "Endereço IP",
    IsCompressed: "É Comprimido",
    IsLibrary: "Biblioteca?",
    IsReplicated: "É Replica?",
    IssueReporting: "Reportagem de Problemas",
    JobID: "ID de trabalho",
    Jobname: "Nome da Tarefa",
    JobName: "Nome da Tarefa",
    jsmi: "jsmi*",
    JSmith: "JSilva*",
    JSON: "JSON",
    KeyFile: "Arquivo Chave",
    KeyType: "Tipo de Chave",
    Label: "Rótulo de Texto",
    LandingZone: "Zona de Entrada de Arquivos",
    LandingZones: "Zona de entrada de arquivos",
    LanguageFiles: "Arquivo de Línguas",
    Largest: "Maior",
    LargestFile: "Maior Arquivo",
    LargestSize: "Maior Tamanho",
    LastEdit: "Última Edição",
    LastEditedBy: "Última Edição Por:",
    LastEditTime: "Última Hora de Edição",
    LastMessage: "Última Mensagem",
    LastName: "Sobrenome",
    LastNDays: "Ultimos N Dias",
    LastNHours: "Últimas N Horas",
    LastNRows: "Últimas N Filas",
    LastRun: "Última Rodada",
    Layout: "Leiaute",
    LDAPWarning: "<b>Error do serviço de LDAP</b> &lsquo;Número de usuários excedido&rsquo;. Por favor use um filtro.",
    LearnMore: "Saber Mais",
    Leaves: "Folhas",
    LegacyForm: "Formato Antigo",
    LegacyGraphLayout: "Formato de Gráfico Antigo",
    LegacyGraphWidget: "Widget de Gráfico Antigo",
    Legend: "Lenda",
    Length: "Comprimento",
    LibrariesUsed: "Usa Biblioteca?",
    LibraryName: "Nome da biblioteca",
    Limit: "Limite",
    Line: "Linha",
    LineTerminators: "Terminador de linhas",
    Links: "Ligações",
    Loading: "Carregando",
    LoadingCachedLayout: "Carregando diagrama do cache",
    LoadingData: "Carragando Dados...",
    loadingMessage: "...carregando...",
    LoadPackageContentHere: "(Carregue conteúdo de pacote aqui)",
    LoadPackageFromFile: "Carregar pacote de arquivo",
    Local: "Local",
    LocalFileSystemsOnly: "Somente Sistemas de Arquivos Locais",
    Location: "Localização",
    Lock: "Bloquear",
    log_analysis_1: "log_analysis_1*",
    Log: "Registro",
    LogAccessType: "Tipo de acesso ao registro",
    LogDirectory: "Diretório de Log",
    LogFile: "Arquivo de log",
    LoggedInAs: "Entrou no sistema como",
    LoggingOut: "Fazendo um Logout",
    LogicalFile: "Arquivo Lógico",
    LogicalFiles: "Arquivos Lógicos",
    LogicalFilesAndSuperfiles: "Arquivos (super e lógicos)",
    LogicalFilesOnly: "Somente arquivos lógicos",
    LogicalFileType: "Tipo de Arquivo Lógico",
    LogicalName: "Nome Lógico",
    LogicalNameMask: "Mask de Nome lógico",
    Login: "Fazer um Login",
    Logout: "Fazer um Logout",
    Logs: "Registros",
    LogVisualization: "Visualização de Log",
    LogVisualizationUnconfigured: "Visualização de Registro não está configurado, por favor, verifique as configurações do gerenciador de confguração",
    LostFile: "Arquivo perdido",
    LostFile2: "Arquivos perdidos",
    LostFileMessage: "Um arquivo lógico que está faltando pelo menos uma parte de arquivo em ambos os locais primário e replicado em armazenamento. O arquivo lógico ainda é referenciado no servidor Dali. A exclusão do arquivo remove a referência do servidor Dali e de quaisquer partes restantes no disco.",
    Low: "Baixo",
    MachineInformation: "Informação da máquina",
    Machines: "Máquinas",
    Major: "Principal",
    ManagedBy: "Gerenciado Por",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=usuários,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Pressione Ctrl+C",
    ManualOverviewSelection: "(Seleção manual será necessária)",
    ManualTreeSelection: "(Seleção manual de árvore será requerida)",
    Mappings: "Mapeamento",
    Mask: "Mask (bloqueador de caracteres)",
    Max: "Max",
    MaxConnections: "Conexões máximas",
    MaximizeRestore: "Maximizar/Restaurar",
    MaximumNumberOfSlaves: "Numero de esclavo",
    MaxNode: "Nó Max",
    MaxRecordLength: "Maximo tamanho do registro",
    MaxSize: "Tamanho máximo",
    MaxSkew: "Viás Max",
    MaxSkewPart: "Pedaço Viás Max",
    Mean: "Média",
    MeanBytesOut: "Bytes médios de saída",
    MemberOf: "Membro de",
    Members: "Membros",
    MemorySize: "Tamanho da memória",
    Message: "Mensagem",
    MethodConfiguration: "Configuração do Método",
    Methods: "Métodos",
    Metrics: "Métricas",
    MetricsGraph: "Métricas / Gráfico",
    Min: "Min",
    Mine: "Meu",
    MinNode: "Nó Min",
    Minor: "Menor",
    MinSize: "Tamanho mínimo",
    MinSkew: "Viás Min",
    MinSkewPart: "Pedaço Viás Min",
    Missing: "Não encontrado",
    MixedNodeStates: "Estados de Nós misturados",
    Modification: "Modificação",
    Modified: "Modificado",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nome do Evento do Monitorador",
    Monitoring: "Monitorador",
    MonitorShotLimit: "Limite do Monitorador",
    MonitorSub: "Sub do Monitorador",
    Month: "Mês",
    More: "Mais",
    Move: "Mover",
    MustContainUppercaseAndSymbol: "Deve conter símbolo e caracteres maiúsculos",
    NA: "Não Aplicável",
    Name: "Nome",
    NameOfEnvironment: "Nome do Ambiente",
    NamePrefix: "Prefixo de nome",
    NamePrefixPlaceholder: "algum::prefixo",
    NetworkAddress: "Endereço de Rede",
    Newest: "Mais recente",
    NewPassword: "Senha Nova",
    NextSelection: "Próxima Seleção",
    NoCommon: "Incomum",
    NoContent: "(sem conteúdo)",
    noDataMessage: "... Zero linhas...",
    Node: "Nó (Node)",
    NodeGroup: "Grupo de Nós",
    NoErrorFound: "Nenhum Erro Encontrado",
    NoFilterCriteriaSpecified: "Filtro não especificado",
    None: "Nenhum",
    NoPublishedSize: "Nenhum tamanho publicado",
    NoRecentFiltersFound: "Nenhum filtro recente encontrado.",
    Normal: "Normal",
    NoScheduledEvents: "Eventos agendados não encontrados",
    NoSplit: "Sem Separador",
    NotActive: "Inativo",
    NotAvailable: "Não disponível",
    NothingSelected: "Nada Selecionado",
    NotInSuperfiles: "Não encontrado em super arquivo",
    NotSuspended: "Não Suspenso",
    NotSuspendedbyUser: "Não suspenso por usuário",
    NoWarningFound: "Nenhuma Advertência Encontrada",
    NumberOfNodes: "Número de nós",
    NumberofParts: "Numero de Partes",
    NumberofSlaves: "Número de Escravos",
    Of: "de",
    Off: "Desligado",
    OK: "Aceitar",
    Oldest: "Mais Antigo",
    OldPassword: "Senha antiga",
    OmitSeparator: "Omitir Separador",
    On: "Ligado",
    Only1PackageFileAllowed: "Somente one arquivo de pacote permitido",
    Open: "Abrir",
    OpenConfiguration: "Abrir Configuração",
    OpenInNewPage: "Abrir em página nova",
    OpenInNewPageNoFrame: "Abrir em página nova (sem quadro)",
    OpenLegacyECLWatch: "Abrir Antigo ECL Watch",
    OpenLegacyMode: "Modo Legado Aberto",
    OpenModernECLWatch: "Abrir ECL Watch Moderno",
    OpenNativeMode: "Modo Nativo Aberto",
    OpenSafeMode: "Abrir em Modo de Segurança",
    OpenSource: "Código Público",
    OpenTreeMode: "Abrir (modo árvore)",
    Operation: "Operação",
    Operations: "Operações",
    Optimize: "Otimizar",
    Options: "Opções",
    OriginalFile: "Arquivo Originál",
    OriginalSize: "Tamanho original",
    OrphanFile: "Arquivos órfãos",
    OrphanFile2: "Arquivo órfão",
    OrphanMessage: "Um arquivo órfão tem partes de arquivo parcial no disco. No entanto, um conjunto completo de peças não está disponível para construir um arquivo lógico e completo. Isso não faz referência a essas partes de arquivo no servidor Dali.",
    OSStats: "Estatísticas do SO",
    Other: "Outro",
    Others: "Outros",
    Outputs: "Resultados",
    Overview: "Visão Geral",
    Overwrite: "Sobrescrever",
    OverwriteMessage: "Alguns arquivos já existem. Selecione opção de escrever por cima para continuar.",
    Owner: "Proprietário",
    PackageContent: "Conteúdo de pacote",
    PackageContentNotSet: "Conteúdo de pacote não definido",
    PackageMap: "Mapa de Pacotes",
    PackageMaps: "Mapas do Pacote de Dados",
    PackagesNoQuery: "Pacotes sem queries",
    PageSize: "Tamanho da Página",
    ParameterXML: "Parametro XML",
    Part: "Parte",
    PartMask: "Parte Máscara",
    PartName: "Nome da Parte",
    PartNumber: "Número da Peça",
    Parts: "Partes",
    PartsFound: "Pedaços Encontradas",
    PartsLost: "Pedaços Perdidas",
    Password: "Senha",
    PasswordExpiration: "Validade da Senha",
    PasswordExpired: "Sua senha não é mais válida. Por favor altere agora.",
    PasswordExpirePostfix: "dia(s). Quer trocar agora?",
    PasswordExpirePrefix: "Senha válida até",
    PasswordOpenZAP: "Senha para abrir ZAP (opicional)",
    PasswordsDoNotMatch: "Senhas não são as mesmas",
    Path: "Caminho",
    PathAndNameOnly: "Só caminho e nome?",
    PathMask: "Bloqueador do Caminho",
    Pause: "Pausar",
    PauseNow: "Pausar agora",
    PctComplete: "% Completo",
    PercentCompressed: "Percentagem Comprimida",
    PercentCompression: "Compressão Percentual",
    PercentDone: "Percentual Completo",
    Percentile97: "Percentual 97",
    Percentile97Estimate: "Estimativa do Percentual 97",
    PercentUsed: "% Usado",
    PerformingLayout: "Executando Layout...",
    Permission: "Permissão",
    PermissionName: "Nome da Permissão",
    Permissions: "Permissões",
    PhysicalFiles: "Arquivos Físicos",
    PhysicalMemory: "Memória Física",
    PlaceholderFindText: "Wuid, Usuário‎, Mais...",  // jshint ignore:line
    PlaceholderFirstName: "João",
    PlaceholderLastName: "da Silva",
    Platform: "Plataforma",
    Playground: "Area de Recreio",
    PleaseEnableCookies: "O ECL Watch requer cookies habilitados para continuar.",
    PleaseEnterANumber: "Por favor digite o número 1 -",
    PleaseLogin: "Por favor, faça o login usando seu nome de usuário e senha",
    PleaseLogIntoECLWatch: "Por favor, faça o login no ECL Watch",
    PleasePickADefinition: "Por favor, escolha uma definição",
    PleaseSelectADynamicESDLService: "Selecione um serviço ESDL dinâmico",
    PleaseSelectAGroupToAddUser: "Por favor, selecione um grupo para adicionar o usuário a",
    PleaseSelectAServiceToBind: "Por favor, selecione um serviço para ligar",
    PleaseSelectATopologyItem: "Selecione um alvo, serviço ou máquina.",
    PleaseSelectAUserOrGroup: "Por favor selecione um usário ou grupo junto com um nome de arquivo",
    PleaseSelectAUserToAdd: "Por favor, selecione um usuário para adicionar",
    Plugins: "Plugins",
    Pods: "Pods",
    PodsAccessError: "Não é possível recuperar a lista de pods",
    Port: "Porta",
    Prefix: "Prefixo",
    PrefixPlaceholder: "&lsquo;nomedoarquivo{:comprimento}, tamanho{:[B|L][1-8]}&rsquo;",
    Preflight: "Pré-vôo",
    PreloadAllPackages: "Precarregar Todos os Pacotes",
    PreserveCompression: "Manter Arquivo Comprimido",
    PreserveParts: "Preservar partes do arquivo",
    PressCtrlCToCopy: "Pressione ctrl + c para copiar.",
    Preview: "Prévia",
    PreviousSelection: "Seleção Anterior",
    PrimaryLost: "Principal Perdido",
    PrimaryMonitoring: "Monitorador Principal",
    Priority: "Prioridade",
    Probability: "Probabilidade",
    Process: "Processo",
    Processes: "Processos",
    ProcessesDown: "Processos Desativados",
    ProcessFilter: "Filtro de Processo",
    ProcessID: "ID de Processo",
    ProcessorInformation: "Informações do Processador",
    ProgressMessage: "Mensagem de Progresso",
    Properties: "Propriedades",
    Property: "Propriedade",
    Protect: "Proteger",
    ProtectBy: "Protegida Pela",
    Protected: "Protegido",
    Protocol: "Protocolo",
    Publish: "Publicado",
    Published: "Publicado",
    PublishedBy: "Publicado por",
    PublishedByMe: "Publicado por mim",
    PublishedQueries: "Consultas de ECL Publicadas",
    PushEvent: "Evento de publicação",
    Quarter: "Quarto",
    Queries: "Consultas ECL",
    QueriesNoPackage: "Queries sem pacote",
    Query: "Consulta",
    QueryDetailsfor: "Detalhes para",
    QueryID: "Identidade de Consulta",
    QueryIDPlaceholder: "some?q*ry.1",
    QueryName: "Nome da Query",
    QueryNamePlaceholder: "Minha?Su?erQ*ry",
    QuerySet: "Grupo de Consultas",
    Queue: "Fila",
    Quote: "Aspas",
    QuotedTerminator: "Terminador em Aspas",
    RawData: "Dados não Tratados",
    RawTextPage: "Texto original (página atual)",
    Ready: "Pronto",
    ReallyWantToRemove: "Realmente quer remover?",
    ReAuthenticate: "Reautenticar para desbloquear",
    RecentFilters: "Filtros Recentes",
    RecentFiltersTable: "Tabela de Filtros Recentes",
    RecordCount: "Numero de Registros",
    RecordLength: "Tamanho do Registro",
    Records: "Registros",
    RecordSize: "Tamanho do Registro",
    RecordStructurePresent: "Estrutura de registro disponível",
    Recover: "Recuperar",
    RecoverTooltip: "Reniciar unidade de trabalho pausado / bloqueado",
    RecreateQuery: "Recriar consulta",
    Recursively: "Recursivamente?",
    Recycling: "Reciclando",
    RedBook: "Livro Vermelho",
    Refresh: "Recarregar",
    ReleaseNotes: "Notas de Versão",
    Reload: "Recarregar",
    Remaining: "Faltando",
    RemoteCopy: "Cópia Remota",
    RemoteDali: "Dali Remota",
    RemoteDaliIP: "IP Dali Remoto",
    Remove: "Remover",
    RemoveAttributeQ: "Você está prestes a remover esse atributo. Você tem certeza de que quer fazer isso?",
    RemoveAtttributes: "Remover Atributo (s)",
    RemoveFromFavorites: "Remover dos favoritos'",
    RemovePart: "Remover parte",
    RemoveSubfiles: "Remover sub-arquivo(s)",
    RemoveSubfiles2: "Remover sub-arquivo(s)?",
    RemoveUser: "Você está próximo de remover-se do grupo",
    Rename: "Renomear",
    RenderedSVG: "Rendered SVG",
    RenderSVG: "Renderização SVG",
    Replicate: "Replicar",
    ReplicatedLost: "Replicado Perdido",
    ReplicateOffset: "Replicar o Deslocamento",
    Report: "Relatório",
    ReportAnError: "Comunicar um Erro",
    ReportError: "Reportar Erro",
    RepresentsASubset: "Representar un subconjunto de todas los casamientos. Usando un filtro correcto puede reducir el numero de casamientos",
    RequestSchema: "Schema da Busca",
    RequiredForFixedSpray: "Necessário para spray fixo",
    RequiredForXML: "Manditório para spray de dados em XML",
    Reschedule: "Reagendar",
    Reset: "Limpar",
    ResetThisQuery: "Restaurar esta Pesquisa?",
    ResetViewToSelection: "Restaurar Visão da seleção",
    Resource: "Recurso",
    Resources: "Recursos",
    ResponseSchema: "Schema da Resposta",
    Restart: "Reiniciar",
    Restarted: "Recomeçar",
    Restarts: "Reinicia",
    Restore: "Restaurar",
    Restricted: "Restrito",
    Resubmit: "Resubmeter",
    Resubmitted: "Submeter de novo",
    ResubmitTooltip: "Submeter unidade de trabalho de novo",
    Results: "Resultado(s)",
    Resume: "Continue",
    RetainSuperfileStructure: "Preservar Estrutura do Super Arquivo",
    RetainSuperfileStructureReason: "Reter Estrutura de Superfile deve ser ativado quando existir mais de 1 subarquivo",
    RetypePassword: "Digite senha de novo",
    Reverse: "Reverter",
    RowPath: "linha de acesso",
    Rows: "Linhas",
    RowTag: "Nome da Linha",
    RoxieCluster: "Roxie Cluster (Aglomerado)",
    RoxieFileCopy: "Estado de Cópia de Archivos Roxie",
    RoxieState: "Estado de Roxie",
    RunningServerStrain: "Executar este processo pode demorar muito tempo e vai sobrecarregar os servidores. Você quer continuar?",
    Sample: "Amostra",
    SampleRequest: "Amostra da Busca",
    SampleResponse: "Amostra de Resposta",
    Save: "Salvar",
    Scope: "Escopo",
    SearchResults: "Resultado da Busca",
    SecondsRemaining: "Segundos Restantes",
    Security: "Segurança",
    SecurityMessageHTML: "Visualizar apenas HTML de usuários confiáveis. Este workunit foi criada por ‘{__placeholder__}’. Renderizar HTML?",
    SecurityWarning: "Aviso de Segurança",
    SeeConfigurationManager: "Ver Gerenciador de Configuração",
    SelectA: "Selecione uma",
    SelectEllipsis: "Selecione ...",
    SelectPackageFile: "Selecione pacote que arquivos",
    SelectValue: "Selecione um valor",
    SendEmail: "Enviar email",
    Separators: "Seperadores",
    Sequence: "Seqüência",
    Server: "Servidor",
    ServiceName: "Nome do Serviço",
    Services: "Serviços",
    ServiceType: "Tipo de serviço",
    SetBanner: "Fixar Banner",
    SetTextError: "Erro para mostrar texto(muito longo?)  Use &lsquo;ajuda&rsquo; para baixar",
    SetToFailed: "Indicar como Falhado",
    SetToolbar: "Definir Barra de Ferramentas",
    SetToolbarColor: "Definir cor da Barra de Ferramentas",
    Severity: "Severidade",
    ShareWorkunit: "Compartilhar URL do Workunit",
    Show: "Exibir",
    ShowPassword: "Mostrar Senha",
    ShowProcessesUsingFilter: "Mostrar processos usando filtro",
    ShowSVG: "Mostrar SVG",
    Size: "Tamanho",
    SizeEstimateInMemory: "Estimativa de tamanho na memória",
    SizeMeanPeakMemory: "Tamanho da Memória de Pico Médio",
    SizeOnDisk: "Tamanho no disco",
    Skew: "Distorção",
    SkewNegative: "Inclinar (-)",
    SkewPositive: "Inclinar (+)",
    SLA: "SLA",
    SlaveLogs: "Logs escravos",
    SlaveNumber: "Numero de esclavo",
    Slaves: "Escravos",
    Smallest: "Menor",
    SmallestFile: "Arquivo Menor",
    SmallestSize: "Menor tamanho",
    SOAP: "SOAP",
    SomeDescription: "Alguma descrição",
    somefile: "*::algum_arquivo*",
    Source: "Fonte",
    SourceCode: "Código Fonte",
    SourceLogicalFile: "Nome Lógica do arquivo Fonte",
    SourcePath: "fonte de acesso",
    SourceProcess: "fonte de processo",
    SparkThor: "SparkThor",
    Spill: "Regar",
    SplitPrefix: "Prefixo de separação",
    Spray: "Spray (Distribuir aos Nós)",
    Start: "Começar",
    Started: "Início",
    Starting: "Iniciando",
    StartTime: "Hora de Início",
    State: "Estado",
    Stats: "Estatísticas",
    Status: "estado",
    Stopped: "Parado",
    Stopping: "Parando",
    StorageInformation: "Informações de armazenamento",
    Subfiles: "Subarquivos",
    Subgraph: "Sugrafo",
    SubgraphLabel: "Rótulo Subgráfico",
    Subgraphs: "Subgráfico",
    Submit: "Submeter",
    Subtype: "Subtipo",
    SuccessfullySaved: "Guardado com sucesso",
    Summary: "Resumo",
    SummaryMessage: "Mensagem de Resumo",
    SummaryStatistics: "Estatísticas Resumidas",
    Superfile: "Super Arquivo",
    SuperFile: "Super Arquivo",
    Superfiles: "Super Arquivos",
    SuperFiles: "Super Arquivos",
    SuperFilesBelongsTo: "Membro do(s) Super Arquivo(s)",
    SuperfilesOnly: "Apenas Super Arquivos",
    SuperOwner: "Dono Super",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SuspendedByAnyNode: "Suspenso Por Qualquer Nó",
    SuspendedByCluster: "Interrompido pelo Bloco",
    SuspendedByFirstNode: "Suspenso Pelo Primeiro Nó",
    SuspendedByUser: "Interrompido pelo Usuário",
    SuspendedReason: "Razão para interrupção",
    SVGSource: "Fonte de SVG",
    Sync: "Sync",
    SyncSelection: "Sincronizar seleção",
    SystemServers: "Servidores do Sistema",
    Table: "Tabela",
    tag: "tag",
    Target: "Destino",
    TargetClusters: "Aglomeragos de Destino(Alvos)",
    TargetClustersLegacy: "Clusters de Alvo (legacy)",
    TargetName: "Nome do Destino",
    TargetNamePlaceholder: "algum::lógico::arquivo",
    TargetRowTagRequired: "Tag Obrigatório de Registro de Destino",
    Targets: "Alvos",
    TargetScope: "Escopo de Destino",
    TargetWuid: "Unidade de trabalho alvo",
    TechPreview: "Visualização Técnica",
    Terminators: "Terminadores",
    TestPages: "Páginas de Teste",
    Text: "Texto",
    TheReturnedResults: "Os Resultados Devolvidos",
    ThorMasterAddress: "Endereço de metre thor",
    ThorNetworkAddress: "Endereço de Rede do Thor",
    ThorProcess: "Processo de Thor",
    ThreadID: "ID do Tópico",
    Time: "Tempo",
    Timeline: "Linha de tempo",
    TimeMaxTotalExecuteMinutes: "Tempo Máximo Total de Minutos de Execução",
    TimeMeanTotalExecuteMinutes: "Tempo Médio Total de Minutos de Execução",
    TimeMinTotalExecuteMinutes: "Tempo Min, Total de Minutos de Execução",
    Timers: "Controladores de tempo",
    TimeSeconds: "Tempo (Segundos)",
    TimeStamp: "Timestamp",
    TimeStarted: "Início",
    TimeStopped: "Fim",
    Timings: "Medidas de Tempo",
    TimingsMap: "Mapa das Medidas de Tempo",
    title_ActiveGroupPermissions: "Permissão de Grupo Ativo",
    title_ActivePermissions: "Permissão Ativo",
    title_Activity: "Atividate",
    title_AvailableGroupPermissions: "Permissão de Grupos Disponiveis",
    title_AvailablePermissions: "Permissão Disponiveis",
    title_BindingConfiguration: "Configuração de Ligação",
    title_BindingDefinition: "Definição de Ligação",
    title_Blooms: "Blooms",
    title_ClusterInfo: "grupos",
    title_Clusters: "Clusters",
    title_CodeGeneratorPermissions: "Permissões de Gerador de Código",
    title_DefinitionExplorer: "Explorador de definição",
    title_Definitions: "Definições",
    title_DESDL: "ESDL dinâmica",
    title_DFUQuery: "Arquivos Lógicos",
    title_DFUWUDetails: "Tarefa DFU",
    title_DirectoriesFor: "Diretórios para",
    title_DiskUsage: "uso de disco",
    title_ECLPlayground: "ECL Playground",
    title_ErrorsWarnings: "Erros / Avisos para",
    title_EventScheduleWorkunit: "Escalonador de eventos",
    title_FileScopeDefaultPermissions: "Permissão Padrão de Arquivos",
    title_FilesPendingCopy: "Arquivos pendentes de cópia",
    title_FoundFilesFor: "Arquivos encontrados para",
    title_GetDFUWorkunits: "Tarefas DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "Título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Mude-me",
    title_History: "História",
    title_HPCCPlatformECL: "ECL Watch - Página Inicial",
    title_HPCCPlatformFiles: "ECL Watch - Arquivos",
    title_HPCCPlatformMain: "ECL Watch - Página Inicial",
    title_HPCCPlatformOps: "ECL Watch - Operações",
    title_HPCCPlatformOpsWidget: "ECL Watch - Operações",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Adaptadores",
    title_Inputs: "Entradas",
    title_LFDetails: "Detalhes dos Arquivos Lógicos",
    title_LibrariesUsed: "Bibliotecas usadas",
    title_Log: "arquivo de registro",
    title_LostFilesFor: "Arquivos perdidos para",
    title_LZBrowse: "Zona de Entrada de Arquivos",
    title_MemberOf: "Membros de",
    title_Members: "Membros",
    title_Methods: "Métodos",
    title_OrphanFilesFor: "Arquivos órfãos para",
    title_PackageParts: "Pacote de peças",
    title_Permissions: "Permissões",
    title_Preflight: "Métricas do Sistema",
    title_PreflightResults: "Resultados Pré-vôo",
    title_ProtectBy: "Protegida Pela",
    title_QuerySetDetails: "Detalhes da Consulta ECL",
    title_QuerySetErrors: "Erros",
    title_QuerySetLogicalFiles: "Arquivos Lógicos",
    title_QuerySetQuery: "Consultas ECL",
    title_QuerySetSuperFiles: "Super Arquivos",
    title_QueryTest: "Super Arquivos",
    title_Result: "Resultados",
    title_Results: "Atividade",
    title_SearchResults: "Resultados de busca",
    title_SourceFiles: "Arquivo(s) da Fonte",
    title_SystemServers: "Servidores do sistema",
    title_SystemServersLegacy: "Servidores do sistema (herdados)",
    title_TargetClusters: "Clusters de Alvo",
    title_Topology: "Topologia",
    title_TpThorStatus: "Estado de Thor",
    title_UserPermissions: "Permissões de usuário",
    title_UserQuery: "Permissões",
    title_WorkunitScopeDefaultPermissions: "Permissão Padrão de Unidades de Trabalho",
    title_WUDetails: "Detalhes da Tarefa ECL",
    title_WUQuery: "Tarefas de ECL",
    TLS: "TLS",
    To: "Para",
    ToDate: "Data Final",
    Toenablegraphviews: "Para ativar visão gráfica, por favor instalar o plugin",
    Tooltip: "Dica de Ferramenta",
    TooManyFiles: "Inumeros Arquivos",
    Top: "Topo",
    Topology: "Topologia",
    ToSizes: "Tamanho Máximo",
    Total: "Total",
    TotalClusterTime: "Tempo total do bloco",
    TotalParts: "Pedaços totais",
    TotalSize: "Tamanho total",
    TotalThorTime: "Tempo Total do Thor",
    ToTime: "para Hora",
    TransitionGuide: "Guia de transição",
    Tree: "Árvore",
    Type: "Tipo",
    Unbound: "Desvinculado",
    undefined: "Indefinido",
    Unknown: "Desconhecido",
    Unlock: "Desbloquear",
    Unprotect: "Desprotege",
    UnsupportedIE9FF: "Não Supportado",
    Unsuspend: "Reativar",
    Unsuspended: "Reativado",
    Up: "Cima",
    UpdateCloneFrom: "Atualizar clone de",
    UpdateDFs: "Atualizar o DFS",
    UpdateSuperFiles: "Actualizar superfile",
    Upload: "Enviar",
    Uploading: "Enviando",
    UpTime: "Tempo de atividade",
    URL: "URL",
    Usage: "Uso",
    Used: "Usado",
    UsedByWorkunit: "Usado pela workunit",
    User: "Usuário",
    UserDetails: "Detalhes do usuário",
    UserID: "Identificação do usurario",
    UserLogin: "Por favor, faça o login usando apenas o seu nome de usuário",
    Username: "Nome do usuário",
    UserName: "Nome do usuário",
    UserPermissions: "Permissão do Usuário",
    Users: "Usuários",
    UseSingleConnection: "Usar Conexão Única",
    Validate: "Validar",
    ValidateActivePackageMap: "Validar pacote de mapa ativo",
    ValidatePackageContent: "Validar pacote de conteúdo",
    ValidatePackageMap: "Validar pacote de mapa",
    ValidateResult: "=====Validar Resultado=====\n\n",
    ValidateResultHere: "Validar resultados",
    Validating: "Validando...",
    ValidationErrorEnterNumber: "Digite um número válido",
    ValidationErrorExpireDaysMinimum: "Não deve ser inferior a 1 dia",
    ValidationErrorNamePrefix: "Deve corresponder ao padrão 'algum : prefixo'",
    ValidationErrorNumberGreater: "Não pode ser maior que",
    ValidationErrorNumberLess: "Não pode ser menor que",
    ValidationErrorRecordSizeNumeric: "O Comprimento do Registro deve ser um número",
    ValidationErrorRecordSizeRequired: "Comprimento do Registro é obrigatório",
    ValidationErrorRequired: "Este campo é obrigatório",
    ValidationErrorTargetNameInvalid: "Nome de arquivo inválido",
    ValidationErrorTargetNameRequired: "O nome do arquivo é obrigatório",
    Value: "Valor",
    Variable: "Variável",
    VariableBigendian: "Variavel Big-edian",
    Variables: "Variáveis",
    VariableSourceType: "Tipo de fonte",
    Version: "Versão",
    ViewByScope: "Visão por escopo",
    Views: "Visões",
    ViewSparkClusterInfo: "Exibir informações do cluster do Spark",
    Visualizations: "Visualizações",
    Visualize: "Visualizar",
    WarnIfAvailableDiskSpaceIsUnder: "Avisar se o espaço disponível em disco estiver abaixo de",
    WarnIfAvailableMemoryIsUnder: "Avisar se a memória disponível está abaixo de",
    WarnIfCPUUsageIsOver: "Avisar se o uso da CPU está além",
    Warning: "Atenção",
    Warnings: "Avisos",
    WarnOldGraphControl: "Alerta: Controle de grafico velho",
    What: "O que",
    Where: "Onde",
    Who: "Quem",
    Width: "Largura",
    Workflows: "Fluxo de Trabalho",
    Workunit: "Tarefa",
    Workunits: "Tarefas",
    WorkUnitScopeDefaultPermissions: "Permisos por defect de alcaces de Workunit",
    Wrap: "Embrulho",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid não pode estar vazia",
    WUSnapShot: "Instantâneo de WU",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Ano",
    YouAreAboutToBeLoggedOut: "Você está prestes a ser desconectado",
    YouAreAboutToDeleteBinding: "Está prestes a eliminar esta ligação. Você tem certeza que quer fazer isso?",
    YouAreAboutToDeleteDefinition: "Você está prestes a deletar essa definição. Você tem certeza de que quer fazer isso?",
    YouAreAboutToDeleteThisFile: "Você está prestes a excluir este arquivo. Você tem certeza de que quer fazer isso?",
    YouAreAboutToDeleteThisPart: "Você está prestes a excluir esta(s) parte(s). Você tem certeza de que quer fazer isso?",
    YouAreAboutToDeleteThisQueryset: "Você está prestes a excluir este conjunto de consultas. Você tem certeza de que quer fazer isso?",
    YouAreAboutToDeleteThisWorkunit: "Você está prestes a excluir esta workunit. Você tem certeza de que quer fazer isso?",
    YouAreAboutToRemoveUserFrom: "Usted esta a punto de quitar un(os) usuario(s) de este grupo. ¿Desea continuar?",
    YourBrowserMayNotSupport: "O seu navegador provavelmente não supporta arquivo(s) deste tamanho",
    YourScreenWasLocked: "Sua tela foi bloqueada por ESP. Por favor re-busque seus dados, pois pode ser obsoleto.",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nenhum Arquivo Lógico (verifique filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Pacote de Análise Zipped",
    Zoom: "Ampliar",
    Zoom100Pct: "Ampliar 100%",
    ZoomAll: "Zoom Completo",
    ZoomMinus: "Ampliar -",
    ZoomPlus: "Ampliar +",
    ZoomSelection: "Seleção de Zoom",
    ZoomWidth: "comprimento do Zoom"
}