export = {
    root: {
        Abort: "Abort",
        AbortedBy: "Aborted by",
        AbortedTime: "Aborted time",
        AbortSelectedWorkunits: "Abort Selected Workunit(s)? Your login ID will be recorded for this action within the WU(s).",
        About: "About",
        AboutGraphControl: "About Graph Control",
        AboutHPCCSystems: "About HPCC Systems®",
        AboutHPCCSystemsGraphControl: "About HPCC Systems® Graph Control",
        AboutToLoseSessionInformation: "You are about to log out and lose all session information. Do you wish to continue?",
        Account: "Account",
        AccountDisabled: "Account Disabled. Contact system administrator.",
        AccountType: "Account Type",
        Action: "Action",
        Activate: "Activate",
        Activated: "Activated",
        ActivateQuery: "Activate Query",
        ActivateQueryDeletePrevious: "Activate query, delete previous",
        ActivateQuerySuspendPrevious: "Activate query, suspend previous",
        Active: "Active",
        ActivePackageMap: "Active Package Map",
        ActiveWorkunit: "Active Workunit",
        Activities: "Activities",
        Activity: "Activity",
        ActivityLabel: "Activity Label",
        ActivityMap: "Activity Map",
        ActualSize: "Actual Size",
        Add: "Add",
        AddAttributes: "Add attributes/values to your method",
        AddAttributes2: "Add Attribute(s)",
        AddBinding: "Add Binding",
        AddFile: "Add File",
        AddGroup: "Add Group",
        AdditionalResources: "Additional Resources",
        AddPart: "Add Part",
        AddProcessMap: "Add Package Map",
        AddResource: "Add Resource",
        AddTheseFilesToDali: "Add these files to Dali?",
        AddtionalProcessesToFilter: "Addtional Processes To Filter",
        AddToExistingSuperfile: "Add to an existing superfile",
        AddToFavorites: "Add to favorites",
        AddToSuperfile: "Add To Superfile",
        AddUser: "Add User",
        Advanced: "Advanced",
        Age: "Age",
        All: "All",
        AllowAccess: "Allow Access",
        AllowForeignFiles: "Allow Foreign Files",
        AllowFull: "Allow Full",
        AllowRead: "Allow Read",
        AllowWrite: "Allow Write",
        AllQueries: "All Queries",
        AllQueuedItemsCleared: "All Queued items have been cleared. The current running job will continue to execute.",
        Analyze: "Analyze",
        ANY: "ANY",
        AnyAdditionalProcessesToFilter: "Any Addtional Processes To Filter",
        Append: "Append",
        AppendCluster: "Append Cluster",
        Apply: "Apply",
        Apps: "Apps",
        ArchiveDFUWorkunit: "Archive DFU Workunit",
        ArchivedOnly: "Archived Only",
        ArchivedWarning: "Warning: please specify a small date range. If not, it may take some time to retrieve the workunits and the browser may be timed out.",
        ArchiveECLWorkunit: "Archive ECL Workunit",
        AreYouSureYouWantToResetTheme: "Are you sure you want to reset to the default theme?",
        Attach: "Attach",
        Attribute: "Attribute",
        AttributesAreRequired: "Attributes are required",
        Audience: "Audience",
        Audit: "Audit",
        AuditLogs: "Audit Log",
        AutoRefresh: "Auto Refresh",
        AutoRefreshEvery: "Auto refresh every x minutes",
        AutoRefreshIncrement: "Auto Refresh Increment",
        Back: "Back",
        BannerColor: "Banner Color",
        BannerColorTooltip: "Change the background color of the top navigation",
        BannerMessage: "Banner Message",
        BannerMessageTooltip: "Change the title displayed in the top navigation (default \"ECL Watch\")",
        BannerScroll: "Banner Scroll",
        BannerSize: "Banner Size (in pixels)",
        BinaryInstalls: "Binary Installs",
        Bind: "Bind",
        Binding: "Binding",
        BindingDeleted: "Binding Deleted",
        Blob: "BLOB",
        BlobPrefix: "BLOB Prefix",
        Blobs: "Blobs",
        Blooms: "Blooms",
        Bottom: "Bottom",
        BoundBy: "bound by:",
        Branches: "Branches",
        BrowserStats: "Browser Stats",
        Bug: "Bug",
        BuildDate: "Build Date",
        Busy: "Busy",
        CallerID: "Caller ID",
        Cancel: "Cancel",
        CancelAll: "Cancel All",
        CancelAllMessage: "Abort running jobs and clear queue. Do you wish to continue?",
        CannotDisplayBinaryData: "Cannot display binary data.",
        Category: "Category",
        CausedBy: "caused by",
        Channel: "Channel",
        Chart: "Chart",
        CheckAllNodes: "Check All Nodes",
        CheckFilePermissions: "Check File Permissions",
        CheckSingleNode: "Check Single Node",
        ChooseProblemNature: "Choose problem nature, fill details once, then submit to JIRA or GitHub.",
        Class: "Class",
        Clear: "Clear",
        ClearPermissionsCache: "Clear Permissions Cache",
        ClearPermissionsCacheConfirm: "Are you sure you want to clear the DALI and ESP permissions caches? Running workunit performance might degrade significantly until the caches have been refreshed.",
        Client: "Client",
        Clone: "Clone",
        ClonedWUID: "Cloned WUID",
        CloneTooltip: "Duplicate workunit",
        Close: "Close",
        CloseModal: "Close popup modal",
        Cluster: "Cluster",
        ClusterName: "Cluster Name",
        ClusterPlaceholder: "r?x*",
        ClusterProcesses: "Cluster Processes",
        Code: "Code",
        CodeGenerator: "Code Generator",
        Col: "Col",
        CollapseAll: "Collapse All",
        ColumnMode: "Column Mode",
        Columns: "Columns",
        Command: "Command",
        Comment: "Comment",
        Compilation: "Compilation",
        CompileCost: "Compile Cost",
        Compiled: "Compiled",
        Compiling: "Compiling",
        Completed: "Completed",
        ComplexityWarning: "More than {threshold} activities ({activityCount}) - suppress initial display?",
        Component: "Component",
        ComponentLogs: "Component Log",
        Components: "Components",
        ComponentsPlaceholder: "e.g. 'Thor', 'Roxie', 'ECL Watch UI'",
        Compress: "Compress",
        Compressed: "Compressed",
        CompressedFileSize: "Compressed File Size",
        CompressedSize: "Compressed Size",
        Compression: "Compression",
        ComputerUpTime: "Computer Up Time",
        Condition: "Condition",
        Configuration: "Configuration",
        ConfigureService: "Configure service",
        ConfirmPassword: "Confirm Password",
        ConfirmRemoval: "Are you sure you want to do this?",
        ConnectionID: "Connection ID",
        ContactAdmin: "If you wish to rename this group, please contact your LDAP admin.",
        Container: "Container",
        ContainerName: "Container Name",
        Content: "Content",
        Contents: "Contents",
        ContentType: "Content Type",
        ContinueWorking: "Continue Working",
        Cookies: "Cookies",
        CookiesAcceptButtonText: "Allow Cookies",
        CookiesNoticeLinkText: "Our Cookie Notice",
        Copied: "Copied!",
        Copy: "Copy",
        CopyLogicalFilename: "Copy Logical Filename",
        CopyLogicalFiles: "Copy Logical Files to clipboard",
        CopyOpenTelemetry: "Copy Open Telemetry",
        CopySelectionToClipboard: "Copy selection to clipboard",
        CopyToClipboard: "Copy to clipboard",
        CopyURLToClipboard: "Copy URL to clipboard",
        CopyWUID: "Copy WUID",
        CopyWUIDs: "Copy WUIDs to clipboard",
        CopyWUIDToClipboard: "Copy WUID to clipboard",
        Cost: "Cost",
        Costs: "Cost(s)",
        Count: "Count",
        CountFailed: "Count Failed",
        CountTotal: "Count Total",
        CPULoad: "CPU Load",
        Create: "Create",
        CreateANewFile: "Create a new superfile",
        Created: "Created",
        CreatedBy: "Created By",
        CreatedByWorkunit: "Created by workunit",
        CreatedTime: "Created Time",
        CreateInGitHub: "Create in GitHub",
        CreateInJIRA: "Create in JIRA",
        CreateIssueFromWU: "Create Issue from Workunit",
        Creating: "Creating",
        Critical: "Critical",
        CrossTab: "Cross Tab",
        CSV: "CSV",
        CustomLogColumns: "Custom Log Columns",
        CustomRange: "Custom Range",
        Dali: "Dali",
        DaliAdmin: " Dali Admin",
        DaliExportConfirm: "Are you sure you want to export the Dali file system? Files can be large and take time to export.",
        DaliExportPathConfirm: "Your path \" / \" is broad and may take a long time to export. Are you sure you want to continue?",
        DaliIP: "DaliIP",
        DaliPromptConfirm: "Are you sure? Dali Admin submissions are permanent and cannot be undone.",
        Dashboard: "Dashboard",
        Data: "Data",
        DataPatterns: "Data Patterns",
        DataPatternsDefnNotFound: "File Definition not found. Data Patterns cannot be started.",
        DataPatternsNotStarted: "Analysis not found.  To start, press Analyze button above.",
        DataPatternsStarted: "Analyzing.  Once complete report will display here.",
        dataset: ":=dataset*",
        Date: "Date",
        Day: "Day",
        Days: "Days",
        Deactivate: "Deactivate",
        Debug: "Debug",
        DEF: "DEF",
        Default: "Default",
        Defaults: "Defaults",
        Definition: "Definition",
        DefinitionDeleted: "Definition deleted",
        DefinitionID: "Definition ID",
        Definitions: "Definitions",
        DelayedReplication: "Delayed replication",
        Delete: "Delete",
        DeleteBinding: "Delete Binding",
        Deleted: "Deleted",
        DeletedBinding: "Deleted Binding",
        DeleteDirectories: "Remove empty directories. Do you wish to continue?",
        DeleteEmptyDirectories: "Delete empty directories?",
        DeletePrevious: "Delete Previous",
        DeleteSelectedDefinitions: "Delete selected definitions?",
        DeleteSelectedFiles: "Delete Selected Files?",
        DeleteSelectedGroups: "Delete selected group(s)?",
        DeleteSelectedPackages: "Delete selected packages?",
        DeleteSelectedPermissions: "Delete selected permission(s)?",
        DeleteSelectedQueries: "Delete Selected Queries?",
        DeleteSelectedUsers: "Delete selected user(s)?",
        DeleteSelectedWorkunits: "Delete Selected Workunits?",
        DeleteSuperfile: "Delete Superfile?",
        DeleteSuperfile2: "Delete Superfile",
        DeleteThisPackage: "Delete this package?",
        Delimited: "Delimited",
        DenyAccess: "Deny Access",
        DenyFull: "Deny Full",
        DenyRead: "Deny Read",
        DenyWrite: "Deny Write",
        Depth: "Depth",
        DepthTooltip: "Maximum Subgraph Depth",
        Deschedule: "Deschedule",
        DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
        DescribeProblem: "Describe the problem, expected vs. actual results, and steps to reproduce.",
        Description: "Description",
        DESDL: "Dynamic ESDL",
        DeselectAll: "Deselect All",
        Despray: "Despray",
        Details: "Details",
        DFSCheck: "DFS Check",
        DFSExists: "DFS Exists",
        DFSLS: "DFS LS",
        DFUServerName: "DFU Server Name",
        DFUWorkunit: "DFU Workunit",
        Directories: "Directories",
        Directory: "Directory",
        DisableScopeScanConfirm: "Are you sure you want to disable Scope Scans?  Changes will revert to configuration settings on DALI reboot.",
        DisableScopeScans: "Disable Scope Scans",
        DiskSize: "Disk Size",
        DiskUsage: "Disk Usage",
        dismiss: "dismiss",
        dismissAll: "dismiss all",
        Distance: "Distance",
        DistanceTooltip: "Maximum Activity Neighbourhood Distance",
        Dll: "Dll",
        Documentation: "Documentation",
        Domain: "Domain",
        Done: "Done",
        DoNotActivateQuery: "Do not activate query",
        DoNotRepublish: "Do not republish?",
        DOT: "DOT",
        DOTAttributes: "DOT Attributes",
        Down: "Down",
        Download: "Download",
        Downloads: "Downloads",
        DownloadSelectionAsCSV: "Download selection as CSV",
        DownloadToCSV: "Download to CSV",
        DownloadToCSVNonFlatWarning: "Please note: downloading files containing nested datasets as comma-separated data may not be formatted as expected",
        DownloadToDOT: "Download to DOT",
        DropZone: "Drop Zone",
        DueToInctivity: "You will be logged out of all ECL Watch sessions in 3 minutes due to inactivity.",
        Duration: "Duration",
        DynamicNoServicesFound: "No services found",
        EBCDIC: "EBCDIC",
        ECL: "ECL",
        ECLWatchRequiresCookies: "ECL Watch requires cookies enabled to continue.",
        ECLWatchSessionManagement: "ECL Watch session management",
        ECLWatchVersion: "ECL Watch Version",
        ECLWorkunit: "ECL Workunit",
        EdgeLabel: "Edge Label",
        Edges: "Edges",
        Edit: "Edit",
        EditDOT: "Edit DOT",
        EditGraphAttributes: "Edit Graph Attributes",
        EditXGMML: "Edit XGMML",
        EmailBody: "Email Body",
        EmailFrom: "Email Address (From)",
        EmailSubject: "Email Subject",
        EmailTo: "Email Address (To)",
        EmployeeID: "Employee ID",
        EmployeeNumber: "Employee Number",
        Empty: "(Empty)",
        Enable: "Enable",
        EnableBannerText: "Enable Environment Text",
        EnableScopeScans: "Enable Scope Scans",
        EnableScopeScansConfirm: "Are you sure you want to enable Scope Scans? Changes will revert to configuration settings on DALI reboot.",
        EndPoint: "End Point",
        EndTime: "End Time",
        EnglishQ: "English?",
        EnterAPercentage: "Enter a percentage",
        EnterAPercentageOrMB: "Enter A Percentage or MB",
        EraseHistory: "Erase History",
        EraseHistoryQ: "Erase history for:",
        Error: "Error",
        Errorparsingserverresult: "Error parsing server result",
        Errors: "Error(s)",
        ErrorsStatus: "Errors/Status",
        ErrorUploadingFile: "Error uploading file(s). Try checking permissions.",
        ErrorWarnings: "Error/Warning(s)",
        Escape: "Escape",
        ESPBindings: "ESP Bindings",
        ESPBuildVersion: "ESP Build Version",
        ESPNetworkAddress: "ESP Network Address",
        ESPProcessName: "ESP Process Name",
        EventName: "Event Name",
        EventNamePH: "Event Name",
        EventScheduler: "Event Scheduler",
        EventText: "Event Text",
        EventTextPH: "Event Text",
        Exception: "Exception",
        ExcludeIndexes: "Exclude Indexes",
        ExecuteCost: "Execution Cost",
        Executed: "Executed",
        Executing: "Executing",
        ExpandAll: "Expand All",
        ExpirationDate: "Expiration Date",
        ExpireDays: "Expire in (days)",
        Export: "Export",
        ExportSelectionsToList: "Export Selections to List",
        FactoryReset: "Factory Reset",
        Failed: "Failed",
        FailedJob: "Failed Job",
        FailedToReadLinks: "Failed to read existing issue links",
        FailedToSaveLink: "Failed to save issue link",
        FailIfNoSourceFile: "Fail If No Source File",
        Fatal: "Fatal",
        Favorites: "Favorites",
        Fetched: "Fetched",
        FetchingData: "Fetching Data...",
        FetchingErrorDetails: "Fetching error details",
        fetchingresults: "fetching results",
        FieldNames: "Field Names",
        File: "File",
        FileAccessCost: "File Access Cost",
        FileCluster: "File Cluster",
        FileCostAtRest: "File Cost At Rest",
        FileCounts: "File Counts",
        FileName: "File Name",
        FileParts: "File Parts",
        FilePath: "File Path",
        FilePermission: "File Permission",
        FilePermissionError: "Error occurred while fetching file permissions.",
        Files: "Files",
        FileScopeDefaultPermissions: "File Scope Default Permissions",
        FileScopes: "File Scopes",
        FileSize: "File Size",
        FilesNoPackage: "Files without matching package definitions",
        FilesPending: "Files pending",
        FilesWarning: "The number of files returned is too large. Only the first 100,000 files sorted by date/time modified were returned. If you wish to limit results, set a filter.",
        FilesWithUnknownSize: "Files With Unknown Size",
        FileType: "File Type",
        FileUploader: "File Uploader",
        FileUploadStillInProgress: "File upload still in progress",
        Filter: "Filter",
        FilterDetails: "Filter Details",
        FilterMetricsTooltip: "This will filter based upon the \"Scope\" column by default. To filter on any other column, use the column name as a prefix to your search, eg: \"Filename:spill\"",
        FilterSet: "Filter Set",
        Find: "Find",
        FindNext: "Find Next",
        FindPrevious: "Find Previous",
        Finished: "Finished",
        FirstN: "First N",
        FirstName: "First Name",
        FirstNRows: "First N Rows",
        FirstNSortBy: "Sort By",
        Fixed: "Fixed",
        Folder: "Folder",
        Form: "Form",
        Format: "Format",
        Forums: "Forums",
        Forward: "Forward",
        FoundFile: "Found Files",
        FoundFileMessage: "A found file has all of its parts on disk that are not referenced in the Dali server. All the file parts are accounted for so they can be added back to the Dali server. They can also be deleted from the cluster, if required.",
        From: "From",
        FromDate: "From Date",
        FromSizes: "From Sizes",
        FromTime: "From Time",
        FullName: "Full Name",
        Generate: "Generate",
        GetDFSCSV: "DFS CSV",
        GetDFSMap: "DFS Map",
        GetDFSParents: "DFS Parents",
        GetLastServerMessage: "Get Last Server Message",
        GetLogicalFile: "Logical File",
        GetLogicalFilePart: "Logical File Part",
        GetPart: "Get Part",
        GetProtectedList: "Protected List",
        GetSoftwareInformation: "Get Software Information",
        GetValue: "Value",
        GetVersion: "Get Version",
        Graph: "Graph",
        GraphControl: "Graph Control",
        Graphs: "Graphs",
        GraphView: "Graph View",
        GridAbortMessage: "Grid aborting stale request",
        Group: "Group",
        GroupBy: "Group By",
        GroupDetails: "Group Details",
        Grouping: "Grouping",
        GroupName: "Group Name",
        GroupPermissions: "Group Permissions",
        Groups: "Groups",
        GZip: "GZip",
        help: "This area displays the treemap for the graph(s) in this workunit. The size and hue indicate the duration of each graph (Larger and darker indicates a greater percentage of the time taken.)",
        Helper: "Helper",
        Helpers: "Helpers",
        Hex: "Hex",
        HideSpills: "Hide Spills",
        High: "High",
        History: "History",
        Homepage: "Homepage",
        Hotspots: "Hot spots",
        Hour: "Hour",
        Hours: "Hours",
        HPCCSystems: "HPCC Systems®",
        HTML: "HTML",
        Icon: "Icon",
        ID: "ID",
        IFrameErrorMsg: "Frame could not be loaded, try again.",
        IgnoreGlobalStoreOutEdges: "Ignore Global Store Out Edges",
        Import: "Import",
        Inactive: "Inactive",
        Incident: "Incident",
        IncludePendingItems: "Include pending items",
        IncludePerComponentLogs: "Include per-component logs",
        IncludeRelatedLogs: "Include related logs",
        IncludeSlaveLogs: "Include worker logs",
        IncludeSubFileInfo: "Include sub file info?",
        IncludeWUContext: "Include WU context (WUID/Owner/Cluster/State) in description",
        Index: "Index",
        Indexes: "Indexes",
        IndexesOnly: "Indexes Only",
        Info: "Info",
        InfoDialog: "Info Dialog",
        Informational: "Informational",
        Infos: "Info(s)",
        InheritedPermissions: "Inherited permission:",
        Inputs: "Inputs",
        InstanceNumber: "Instance Number",
        InUse: "In Use",
        InvalidResponse: "(Invalid response)",
        InvalidUsernamePassword: "Invalid username or password, try again.",
        IP: "IP",
        IPAddress: "IP Address",
        IsCompressed: "Is Compressed",
        IsLibrary: "Is Library",
        IsReplicated: "Is Replicated",
        IssueReport: "Issue report",
        IssueReporting: "Issue Reporting",
        JobID: "Job ID",
        JobName: "Job Name",
        Jobname: "Jobname",
        jsmi: "jsmi*",
        JSmith: "JSmit*",
        JSON: "JSON",
        KeyFile: "Key File",
        KeyType: "Key Type",
        Label: "Label",
        LandingZone: "Landing Zone",
        LandingZones: "Landing Zones",
        LanguageFiles: "Language Files",
        Largest: "Largest",
        LargestFile: "Largest File",
        LargestSize: "Largest Size",
        Last: "Last",
        LastAccessed: "Last Accessed (UTC/GMT)",
        LastAccessedLocalTime: "Last Accessed (Local Time)",
        LastEdit: "Last Edit",
        LastEditedBy: "Last Edited By",
        LastEditTime: "Last Edit Time",
        LastMessage: "Last Message",
        LastName: "Last Name",
        LastNDays: "Last N Days",
        LastNHours: "Last N Hours",
        LastNRows: "Last N Rows",
        LastRun: "Last Run",
        LatestReleases: "Latest Releases",
        Layout: "Layout",
        LDAPWarning: "<b>LDAP Services Error:</b>  &lsquo;Too Many Users&rsquo; - Please use a Filter.",
        LearnMore: "Learn More",
        Leaves: "Leaves",
        LegacyForm: "Legacy Form",
        LegacyGraphLayout: "Legacy Graph Layout",
        LegacyGraphWidget: "Legacy Graph Widget",
        Legend: "Legend",
        Length: "Length",
        LibrariesUsed: "Libraries Used",
        LibraryName: "Library Name",
        Limit: "Limit",
        Line: "Line",
        LineTerminators: "Line Terminators",
        Links: "Links",
        ListDFUWorkunit: "List DFU Workunit",
        ListECLWorkunit: "List ECL Workunit",
        Loading: "Loading...",
        LoadingCachedLayout: "Loading Cached Layout...",
        LoadingData: "Loading Data...",
        loadingMessage: "...Loading...",
        LoadPackageContentHere: "(Load package content here)",
        LoadPackageFromFile: "Load Package from a file",
        Local: "Local",
        LocalFileSystemsOnly: "Local File Systems Only",
        Location: "Location",
        Lock: "Lock",
        log_analysis_1: "log_analysis_1*",
        Log: "Log",
        LogAccess_GenericException: "ws_logaccess::GetLogAccessInfo, an exception has occurred.",
        LogAccess_LoggingNotConfigured: "A logging engine has not been configured.",
        LogAccessType: "Log Access Type",
        LogDirectory: "Log Directory",
        LogEventType: "Log Event Type",
        LogFile: "Log File",
        LogFilterComponentsFilterTooltip: "Only include logs from the selected component/container",
        LogFilterCustomColumnsTooltip: "Include the specified log columns",
        LogFilterEndDateTooltip: "Include log lines up to time range end",
        LogFilterEventTypeTooltip: "Only include entries for specified log event type",
        LogFilterFormatTooltip: "Format of log file: CSV, JSON, or XML",
        LogFilterLineLimitTooltip: "The number of log lines to be included",
        LogFilterLineStartFromTooltip: "Include log lines starting at this line number",
        LogFilterRelativeTimeRangeTooltip: "A time range surrounding the WU time, +/- (in seconds)",
        LogFilters: "Log Filters",
        LogFilterSelectColumnModeTooltip: "Specify which columns to include in log file",
        LogFilterSortByTooltip: "ASC - oldest first, DESC - newest first",
        LogFilterStartDateTooltip: "Include log lines from time range start",
        LogFiltersUnavailable: "Log Filters are unavailable",
        LogFilterTimeRequired: "Choose either \"From and To Date\" or \"Relative Log Time Buffer\"",
        LogFilterWildcardFilterTooltip: "A string of text upon which to filter log messages",
        LogFormat: "Log Format",
        LoggedInAs: "Logged in as",
        LoggingOut: "Logging out",
        LogicalFile: "Logical File",
        LogicalFiles: "Logical Files",
        LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
        LogicalFilesOnly: "Logical Files Only",
        LogicalFileType: "Logical File Type",
        LogicalName: "Logical Name",
        LogicalNameMask: "Logical Name Mask",
        Login: "Login",
        LogLineLimit: "Log Line Limit",
        LogLineStartFrom: "Log Line Start From",
        Logout: "Log Out",
        Logs: "Logs",
        LogsDisabled: "Logs Disabled",
        LogVisualization: "Log Visualization",
        LogVisualizationUnconfigured: "Log Visualization is not configured, please check your configuration manager settings.",
        LostFile: "Lost Files",
        LostFile2: "Lost Files",
        LostFileMessage: "A logical file that is missing at least one file part on both the primary and replicated locations in storage. The logical file is still referenced in the Dali server. Deleting the file removes the reference from the Dali server and any remaining parts on disk.",
        Low: "Low",
        MachineInformation: "Machine Information",
        Machines: "Machines",
        Major: "Major",
        ManagedBy: "Managed By",
        ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
        ManualCopy: "Press Ctrl+C",
        ManualOverviewSelection: "(Manual overview selection will be required)",
        ManualTreeSelection: "(Manual tree selection will be required)",
        Mappings: "Mappings",
        Mask: "Mask",
        MatchCase: "Match Case",
        MatchWholeWord: "Match Whole Word",
        Max: "Max",
        MaxConnections: "Max Connections",
        MaximizeRestore: "Maximize/Restore",
        MaximumNumberOfSlaves: "Worker Number",
        MaxNode: "Max Node",
        MaxRecordLength: "Max Record Length",
        MaxSize: "Max Size",
        MaxSkew: "Max Skew",
        MaxSkewPart: "Max Skew Part",
        Mean: "Mean",
        MeanBytesOut: "Mean Bytes Out",
        MemberOf: "Member Of",
        Members: "Members",
        MemorySize: "Memory Size",
        Message: "Message",
        MethodConfiguration: "Method Configuration",
        Methods: "Methods",
        MetricOptions: "Metric Options",
        Metrics: "Metrics",
        MetricsGraph: "Metrics/Graph",
        MetricsSQL: "Metrics (SQL)",
        Min: "Min",
        Mine: "Mine",
        MinimumCompileCost: "Minimum Compile Cost",
        MinimumExecuteCost: "Minimum Execute Cost",
        MinimumFileAccessCost: "Minimum File Access Cost",
        MinNode: "Min Node",
        Minor: "Minor",
        MinSize: "Min Size",
        MinSkew: "Min Skew",
        MinSkewPart: "Min Skew Part",
        Minute: "Minute",
        Minutes: "Minutes",
        Missing: "Missing",
        MixedNodeStates: "Mixed Node States",
        Modification: "Modification",
        Modified: "Modified",
        ModifiedLocalTime: "Modified (Local Time)",
        ModifiedUTCGMT: "Modified (UTC/GMT)",
        Modify: "Modify",
        MonitorEventName: "Monitor Event Name",
        Monitoring: "Monitoring",
        MonitorShotLimit: "Monitor Shot Limit",
        MonitorSub: "Monitor Sub",
        Month: "Month",
        More: "more",
        Move: "Move",
        MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
        NA: "N/A",
        Name: "Name",
        NameOfEnvironment: "Name Of Environment",
        NamePrefix: "Name Prefix",
        NamePrefixPlaceholder: "some::prefix",
        NavWide: "Navigation Wide Mode",
        NetworkAddress: "Network Address",
        Newest: "Newest",
        NewPassword: "New Password",
        NextSelection: "Next Selection",
        NextWorkunit: "Next Workunit",
        NoCommon: "No Common",
        NoContent: "(No content)",
        NoContentPleaseSelectItem: "No content - please select an item",
        noDataMessage: "...Zero Rows...",
        Node: "Node",
        NodeGroup: "Node Group",
        NoErrorFound: "No errors found\n",
        NoFilterCriteriaSpecified: "No filter criteria specified.",
        None: "None",
        NoPublishedSize: "No published size",
        NoRecentFiltersFound: "No recent filters found.",
        Normal: "Normal",
        NoScheduledEvents: "No Scheduled Events.",
        NoSplit: "No Split",
        NotActive: "Not active",
        NotAvailable: "Not available",
        NothingSelected: "Nothing Selected...",
        NotInSuperfiles: "Not in Superfiles",
        NotSuspended: "Not Suspended",
        NotSuspendedbyUser: "Not Suspended By User",
        NoWarningFound: "No warnings found\n",
        NumberOfNodes: "Number of Nodes",
        NumberofParts: "Number of Parts",
        NumberofSlaves: "Number of Workers",
        Of: "Of",
        of: "of",
        Off: "Off",
        OK: "OK",
        Oldest: "Oldest",
        OldPassword: "Old Password",
        OmitSeparator: "Omit Separator",
        On: "On",
        Only1PackageFileAllowed: "Only one package file allowed",
        Open: "Open",
        OpenConfiguration: "Open Configuration",
        OpenInNewPage: "Open in New Page",
        OpenInNewPageNoFrame: "Open in New Page (No Frame)",
        OpenLegacyECLWatch: "Open Legacy ECL Watch",
        OpenLegacyMode: "Open (legacy)",
        OpenModernECLWatch: "Open Modern ECL Watch",
        OpenNativeMode: "Open (native)",
        OpenSource: "Open Source",
        Operation: "Operation",
        Operations: "Operations",
        Optimize: "Optimize",
        Options: "Options",
        OriginalFile: "Original File",
        OriginalSize: "Original Size",
        OrphanFile: "Orphan Files",
        OrphanFile2: "Orphan File",
        OrphanMessage: "An orphan file has partial file parts on disk. However, a full set of parts is not available to construct a complete logical file. There is no reference to these file parts in the Dali server.",
        OSStats: "OS Stats",
        Other: "Other",
        Others: "Other(s)",
        Outputs: "Outputs",
        Overview: "Overview",
        Overwrite: "Overwrite",
        OverwriteMessage: "Some file(s) already exist. Please check overwrite box to continue.",
        Owner: "Owner",
        PackageContent: "Package Content",
        PackageContentNotSet: "Package content not set",
        PackageMap: "Package Map",
        PackageMaps: "Package Maps",
        PackagesNoQuery: "Packages without matching queries",
        PageSize: "Page Size",
        ParameterXML: "Parameter XML",
        Part: "Part",
        PartMask: "Part Mask",
        PartName: "Part Name",
        PartNumber: "Part Number",
        Parts: "Parts",
        PartsFound: "Parts Found",
        PartsLost: "Parts Lost",
        Password: "Password",
        PasswordExpiration: "Password Expiration",
        PasswordExpired: "Your password has expired.  Please change now.",
        PasswordExpirePostfix: " day(s). Do you want to change it now?",
        PasswordExpirePrefix: "Your password will expire in ",
        PasswordNeverExpires: "Password never expires",
        PasswordOpenZAP: "Password to open ZAP (optional)",
        PasswordsDoNotMatch: "Passwords do not match.",
        PasteIssueURL: "Paste the final created issue URL here (after submission) to store on this WU",
        Path: "Path",
        PathAndNameOnly: "Path and name only?",
        PathMask: "Path Mask",
        Pause: "Pause",
        PauseNow: "Pause Now",
        PctComplete: "% Complete",
        PercentCompressed: "Percent Compressed",
        PercentCompression: "Percent Compression",
        PercentDone: "Percent Done",
        Percentile97: "Percentile 97",
        Percentile97Estimate: "Percentile 97 Estimate",
        PercentUsed: "% Used",
        PerformingLayout: "⚡Performing Layout⚡",
        PerformingLayoutFailed: "❌Layout Failed❌ Pick a different ⬆️root⬆️",
        PerformingLayoutLongRunning: "⏳Performing Layout⏳ Impatient? Pick a different ⬆️root⬆️",
        Permission: "Permission",
        PermissionName: "Permission Name",
        Permissions: "Permissions",
        PhysicalFiles: "Physical Files",
        PhysicalMemory: "Physical Memory",
        PlaceholderFindText: "Wuid, User, (ecl:*, file:*, dfu:*, query:*)...",
        PlaceholderFirstName: "John",
        PlaceholderLastName: "Smith",
        Platform: "Platform",
        PlatformBuildIsNNNDaysOld: "Platform build is NNN days old.",
        Playground: "Playground",
        PleaseEnableCookies: "This site uses cookies. To see how cookies are used, please review our cookie notice. If you agree to our use of cookies, please continue to use our site.",
        PleaseEnterANumber: "Please enter a number 1 - ",
        PleaseLogin: "Please log in using your username and password",
        PleaseLogIntoECLWatch: "Please log into ECL Watch",
        PleasePickADefinition: "Please pick a definition",
        PleaseSelectADynamicESDLService: "Please select a dynamic ESDL service",
        PleaseSelectAGroupToAddUser: "Please select a group to add the user to",
        PleaseSelectAServiceToBind: "Please select a service to bind",
        PleaseSelectATopologyItem: "Please select a target, service or machine.",
        PleaseSelectAUserOrGroup: "Please select a user or a group along with a file name",
        PleaseSelectAUserToAdd: "Please select a user to add",
        PleaseUpgradeToLaterPointRelease: "Please upgrade to a later point release.",
        Plugins: "Plugins",
        PodName: "Pod Name",
        Pods: "Pods",
        PodsAccessError: "Cannot retrieve list of pods",
        Port: "Port",
        PotentialSavings: "Potential Savings",
        Prefix: "Prefix",
        PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
        Preflight: "Preflight",
        PreloadAllPackages: "Preload All Packages",
        PreserveCompression: "Preserve Compression",
        PreserveParts: "Preserve File Parts",
        PressCtrlCToCopy: "Press ctrl+c to copy.",
        Preview: "Preview",
        PreviousSelection: "Previous Selection",
        PreviousWorkunit: "Previous Workunit",
        PrimaryLost: "Primary Lost",
        PrimaryMonitoring: "Primary Monitoring",
        Priority: "Priority",
        Probability: "Probability",
        ProblemNature: "Problem Nature",
        Process: "Process",
        Processes: "Processes",
        ProcessesDown: "Processes Down",
        ProcessFilter: "Process Filter",
        ProcessID: "Process ID",
        ProcessorInformation: "Processor Information",
        ProgressMessage: "Progress Message",
        Project: "Project",
        ProjectPlaceholder: "Jira project key (e.g. HPCC) or leave blank for GitHub",
        Properties: "Properties",
        Property: "Property",
        Protect: "Protect",
        ProtectBy: "Protected by",
        Protected: "Protected",
        Protocol: "Protocol",
        Publish: "Publish",
        Published: "Published",
        PublishedBy: "Published By",
        PublishedByMe: "Published by me",
        PublishedQueries: "Published Queries",
        PushEvent: "Push Event",
        Quarter: "Quarter",
        Queries: "Queries",
        QueriesNoPackage: "Queries without matching package",
        Query: "Query",
        QueryDetailsfor: "Query Details for",
        QueryID: "Query ID",
        QueryIDPlaceholder: "som?q*ry.1",
        QueryName: "Query Name",
        QueryNamePlaceholder: "My?Su?erQ*ry",
        QuerySet: "Query Set",
        Queue: "Queue",
        QuickSelect: "Quick Select",
        Quote: "Quote",
        QuotedTerminator: "Quoted Terminator",
        RawData: "Raw Data",
        RawTextPage: "Raw Text (Current Page)",
        Ready: "Ready",
        ReallyWantToRemove: "Really want to remove?",
        ReAuthenticate: "Reauthenticate to unlock",
        RecentFilters: "Recent Filters",
        RecentFiltersTable: "Recent Filters Table",
        RecordCount: "Record Count",
        RecordLength: "Record Length",
        Records: "Records",
        RecordSize: "Record Size",
        RecordStructurePresent: "Record Structure Present",
        Recover: "Recover",
        RecoverTooltip: "Restart paused / stalled workunit",
        RecreateQuery: "Recreate Query",
        Recursively: "Recursively?",
        Recycling: "Recycling",
        RedBook: "Red Book",
        Refresh: "Refresh",
        RelativeTimeRange: "Relative Time Range",
        ReleaseNotes: "Release Notes",
        Reload: "Reload",
        Remaining: "Remaining",
        RemoteCopy: "Remote Copy",
        RemoteDali: "Remote Dali",
        RemoteDaliIP: "Remote Dali IP Address",
        RemoteStorage: "Remote Storage",
        Remove: "Remove",
        RemoveAttributeQ: "You are about to remove this attribute. Are you sure you want to do this?",
        RemoveAtttributes: "Remove Attribute(s)",
        RemoveFromFavorites: "Remove from favorites",
        RemovePart: "Remove Part",
        RemoveSubfiles: "Remove Subfile(s)",
        RemoveSubfiles2: "Remove Subfile(s)?",
        RemoveUser: "You are about to remove yourself from the group:",
        Rename: "Rename",
        RenderedSVG: "Rendered SVG",
        RenderSVG: "Render SVG",
        Replicate: "Replicate",
        ReplicatedLost: "Replicated Lost",
        ReplicateOffset: "Replicate Offset",
        Report: "Report",
        RepresentsASubset: "represent a subset of the total number of matches. Using a correct filter may reduce the number of matches.",
        RequestSchema: "Request Schema",
        RequiredForFixedSpray: "Required for fixed spray",
        RequiredForXML: "Required for spraying XML",
        Reschedule: "Reschedule",
        Reset: "Reset",
        ResetThisQuery: "Reset This Query?",
        ResetUserSettings: "Reset User Settings",
        ResetViewToSelection: "Reset View to Selection",
        Resource: "Resource",
        Resources: "Resources",
        ResponseSchema: "Response Schema",
        Restart: "Restart",
        Restarted: "Restarted",
        Restarts: "Restarts",
        Restore: "Restore",
        RestoreDFUWorkunit: "Restore DFU Workunit",
        RestoreECLWorkunit: "Restore ECL Workunit",
        Restricted: "Restricted",
        Resubmit: "Resubmit",
        Resubmitted: "Resubmitted",
        ResubmitTooltip: "Resubmit existing workunit",
        Results: "Result(s)",
        Resume: "Resume",
        RetainSuperfileStructure: "Retain Superfile Structure",
        RetainSuperfileStructureReason: "Retain Superfile Structure must be enabled when more than 1 subfile exists.",
        RetypePassword: "Retype Password",
        Reverse: "Reverse",
        RowPath: "Row Path",
        Rows: "Rows",
        RowTag: "Row Tag",
        RoxieCluster: "Roxie Cluster",
        RoxieFileCopy: "Roxie Files Copy Status",
        RoxieState: "Roxie State",
        RunningServerStrain: "Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?",
        Sample: "Sample",
        SampleRequest: "Sample Request",
        SampleResponse: "Sample Response",
        Sasha: "Sasha",
        Save: "Save",
        SaveAs: "Save As",
        Scope: "Scope",
        ScopeColumns: "Scope Columns",
        ScopeTypes: "Scope Types",
        SearchResults: "Search Results",
        Seconds: "Seconds",
        SecondsRemaining: "Seconds Remaining",
        Security: "Security",
        SecurityMessageHTML: "Only view HTML from trusted users.  This workunit was created by \"{__placeholder__}\".  \nRender HTML?",
        SecurityWarning: "Security Warning",
        SeeConfigurationManager: "See Configuration Manager",
        SelectA: "Select a",
        SelectAll: "Select All",
        SelectAnOption: "Select an option",
        SelectDateRange: "Select date range",
        Selected: "Selected",
        SelectEllipsis: "Select...",
        SelectPackageFile: "Select Package File",
        SelectValue: "Select a value",
        SelectWorkunitToRestore: "Please select one or more workunits to restore.",
        SendEmail: "Send Email",
        Separators: "Separators",
        Sequence: "Sequence",
        Server: "Server",
        ServiceName: "Service Name",
        Services: "Services",
        ServiceType: "Service Type",
        SetBanner: "Set Banner",
        SetLogicalFileAttribute: "Set Logical File Attribute",
        SetProtected: "Set Protected",
        SetTextError: "Failed to display text (too large?).  Use &lsquo;helpers&rsquo; to download.",
        SetToFailed: "Set To Failed",
        SetToolbar: "Set Toolbar",
        SetToolbarColor: "Set Toolbar Color",
        SetUnprotected: "Set Unprotected",
        SetValue: "Set Value",
        Severity: "Severity",
        ShareWorkunit: "Share Workunit URL",
        Show: "Show",
        ShowPassword: "Show Password",
        ShowProcessesUsingFilter: "Show Processes Using Filter",
        ShowSVG: "Show SVG",
        Size: "Size",
        SizeEstimateInMemory: "Size Estimate in Memory",
        SizeMeanPeakMemory: "Size Mean Peak Memory",
        SizeOnDisk: "Size on Disk",
        Skew: "Skew",
        SkewNegative: "Skew(-)",
        SkewPositive: "Skew(+)",
        SLA: "SLA",
        SlaveLogs: "Worker Logs",
        SlaveNumber: "Worker Number",
        Slaves: "Workers",
        SlowPerformance: "Slow Performance",
        Smallest: "Smallest",
        SmallestFile: "Smallest File",
        SmallestSize: "Smallest Size",
        SOAP: "SOAP",
        SomeDescription: "Some*Description",
        somefile: "*::somefile*",
        Sort: "Sort",
        Source: "Source",
        SourceCode: "Source Code",
        SourceLogicalFile: "Source Logical Name",
        SourcePath: "Source Path (Wildcard Enabled)",
        SourceProcess: "Source Process",
        Span: "Span",
        SparkThor: "SparkThor",
        Spill: "Spill",
        SplitPrefix: "Split Prefix",
        Spray: "Spray",
        SQL: "SQL",
        Start: "Start",
        Started: "Started",
        Starting: "Starting",
        StartTime: "Start Time",
        State: "State",
        Statistics: "Statistics",
        Stats: "Stats",
        Status: "Status",
        StatusPlaceholder: "e.g. 'To Do', 'Backlog', or label for GitHub",
        Stopped: "Stopped",
        Stopping: "Stopping",
        StorageInformation: "Storage Information",
        Story: "Story",
        Subfiles: "Subfiles",
        Subgraph: "Subgraph",
        SubgraphLabel: "Subgraph Label",
        Subgraphs: "Subgraphs",
        Submit: "Submit",
        Subtype: "Subtype",
        SuccessfullySaved: "Successfully Saved",
        Summary: "Summary",
        SummaryMessage: "Summary Message",
        SummaryStatistics: "Summary Statistics",
        SuperFile: "Super File",
        Superfile: "Superfile",
        SuperFiles: "Super Files",
        Superfiles: "Superfiles",
        SuperFilesBelongsTo: "Member of Superfile(s)",
        SuperfilesOnly: "Superfiles Only",
        SuperOwner: "Super Owner",
        Suspend: "Suspend",
        Suspended: "Suspended",
        SuspendedBy: "Suspended By",
        SuspendedByAnyNode: "Suspended By Any Node",
        SuspendedByCluster: "Suspended By Cluster",
        SuspendedByFirstNode: "Suspended By First Node",
        SuspendedByUser: "Suspended By User",
        SuspendedReason: "Suspended Reason",
        SVGSource: "SVG Source",
        SwitchToLocalTime: "Switch to Local Time",
        SwitchToUTCTime: "Switch to UTC Time",
        SyncSelection: "Sync To Selection",
        Syntax: "Syntax",
        SystemServers: "System Servers",
        Table: "Table",
        tag: "tag",
        Target: "Target",
        TargetClusters: "Target Clusters",
        TargetClustersLegacy: "Target Clusters (legacy)",
        TargetName: "Target Name",
        TargetNamePlaceholder: "some::logical::name",
        TargetPlane: "Target Plane",
        TargetRowTagRequired: "You must supply a target row tag",
        Targets: "Targets",
        TargetScope: "Target Scope",
        TargetWuid: "Target/Wuid",
        Task: "Task",
        TechPreview: "Tech Preview",
        Terminators: "Terminators",
        TestPages: "Test Pages",
        Text: "Text",
        Theme: "Theme",
        TheReturnedResults: "The returned results",
        ThorMasterAddress: "Thor Master Address",
        ThorNetworkAddress: "Thor Network Address",
        ThorProcess: "Thor Process",
        ThreadID: "Thread ID",
        Time: "Time",
        Timeline: "Timeline",
        TimeMaxTotalExecuteMinutes: "Time Max Total Execute Minutes",
        TimeMeanTotalExecuteMinutes: "Time Mean Total Execute Minutes",
        TimeMinTotalExecuteMinutes: "Time Min Total Execute Minutes",
        TimePenalty: "Time Penalty",
        Timers: "Timers",
        TimeSeconds: "Time (Seconds)",
        TimeStamp: "Time Stamp",
        TimeStarted: "Time Started",
        TimeStopped: "Time Stopped",
        Timings: "Timings",
        TimingsMap: "Timings Map",
        title_ActiveGroupPermissions: "Active Group Permissions",
        title_ActivePermissions: "Active Permissions",
        title_Activity: "Activity",
        title_AvailableGroupPermissions: "Available Group Permissions",
        title_AvailablePermissions: "Available Permissions",
        title_BindingConfiguration: "Binding Configuration",
        title_BindingDefinition: "Binding Definition",
        title_Blooms: "Blooms",
        title_ClusterInfo: "Groups",
        title_Clusters: "Clusters",
        title_CodeGeneratorPermissions: "Code Generator Permissions",
        title_DefinitionExplorer: "Definition Explorer",
        title_Definitions: "Definitions",
        title_DESDL: "Dynamic ESDL",
        title_DFUQuery: "Logical Files",
        title_DFUWUDetails: "DFU Workunit",
        title_DirectoriesFor: "Directories for",
        title_DiskUsage: "Disk Usage",
        title_ECLPlayground: "ECL Playground",
        title_ErrorsWarnings: "Errors/Warnings for",
        title_EventScheduleWorkunit: "Event Scheduler",
        title_FileScopeDefaultPermissions: "Default permissions of files",
        title_FilesPendingCopy: "Files pending copy",
        title_FoundFilesFor: "Found files for",
        title_GetDFUWorkunits: "DFU Workunits",
        title_Graph: "Graph",
        title_GraphPage: "title",
        title_Graphs: "Graphs",
        title_GridDetails: "Change Me",
        title_History: "History",
        title_HPCCPlatformECL: "ECL Watch - Home",
        title_HPCCPlatformFiles: "ECL Watch - Files",
        title_HPCCPlatformMain: "ECL Watch - Home",
        title_HPCCPlatformOps: "ECL Watch - Operations",
        title_HPCCPlatformRoxie: "ECL Watch - Roxie",
        title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
        title_Inputs: "Inputs",
        title_LFDetails: "Logical File Details",
        title_LibrariesUsed: "Libraries Used",
        title_Log: "Log File",
        title_LostFilesFor: "Lost files for",
        title_LZBrowse: "Landing Zones",
        title_MemberOf: "Member Of",
        title_Members: "Members",
        title_Methods: "Methods",
        title_OrphanFilesFor: "Orphan files for",
        title_PackageParts: "Package Parts",
        title_Permissions: "Permissions",
        title_Preflight: "System Metrics",
        title_PreflightResults: "Preflight Results",
        title_ProtectBy: "Protected By",
        title_QuerySetDetails: "Query Details",
        title_QuerySetErrors: "Errors",
        title_QuerySetLogicalFiles: "Logical Files",
        title_QuerySetQuery: "Queries",
        title_QuerySetSuperFiles: "Super Files",
        title_QueryTest: "Super Files",
        title_Result: "Activity",
        title_Results: "Outputs",
        title_SearchResults: "Search Results",
        title_SourceFiles: "",
        title_SystemServers: "System Servers",
        title_SystemServersLegacy: "System Servers (legacy)",
        title_TargetClusters: "Target Clusters",
        title_Topology: "Topology",
        title_TpThorStatus: "Thor Status",
        title_UserPermissions: "User Permissions",
        title_UserQuery: "Permissions",
        title_WorkunitScopeDefaultPermissions: "Default permissions of workunits",
        title_WUDetails: "ECL Workunit Details",
        title_WUQuery: "ECL Workunits",
        TLS: "TLS",
        To: "To",
        ToDate: "To Date",
        Toenablegraphviews: "To enable graph views, please install the Graph View Control plugin",
        Tooltip: "Tooltip",
        TooManyFiles: "Too many files",
        Top: "Top",
        Topology: "Topology",
        ToSizes: "To Sizes",
        Total: "Total",
        TotalClusterTime: "Total Cluster Time",
        TotalParts: "Total Parts",
        TotalSize: "Total Size",
        ToTime: "To Time",
        Trace: "Trace",
        TransferRate: "Transfer Rate",
        TransferRateAvg: "Transfer Rate (Avg)",
        TransitionGuide: "Transition Guide",
        Tree: "Tree",
        Type: "Type",
        UnableToRetrieveGroups: "Unable to retrieve your group memberships",
        UnavailableInBareMetal: "This is unavailable in a non-containerized environment.",
        UnavailableInContainerized: "This is unavailable in a containerized environment.",
        Unbound: "unbound",
        undefined: "undefined",
        UnexpectedResults: "Unexpected Results",
        Unknown: "Unknown",
        Unlock: "Unlock",
        UnlockSDSLock: "Unlock SDS Lock",
        Unprotect: "Unprotect",
        UnsupportedIE9FF: "Unsupported (IE <= 9, FireFox)",
        Unsuspend: "Unsuspend",
        Unsuspended: "Unsuspended",
        Until: "Until",
        Up: "Up",
        UpdateCloneFrom: "Update Clone From",
        UpdateDFs: "Update DFS",
        UpdateSuperFiles: "Update Super Files",
        Upload: "Upload",
        Uploading: "Uploading",
        UpTime: "Up Time",
        URL: "URL",
        Usage: "Usage",
        Used: "Used",
        UsedByWorkunit: "Used by workunit",
        User: "User",
        UserDetails: "User Details",
        UserID: "User ID",
        UserLogin: "Please log in using your username only",
        UserName: "User Name",
        Username: "Username",
        UserPermissions: "User Permissions",
        Users: "Users",
        UseSingleConnection: "Use Single Connection",
        Validate: "Validate",
        ValidateActivePackageMap: "Validate Active Package Map",
        ValidatePackageContent: "Validate Package Content",
        ValidatePackageMap: "Validate Package Map",
        ValidateResult: "=====Validate Result=====\n\n",
        ValidateResultHere: "(Validation result)",
        Validating: "Validating...",
        ValidationErrorEnterNumber: "Enter a valid number",
        ValidationErrorExpireDaysMinimum: "Should not be less than 1 day",
        ValidationErrorNamePrefix: "Should match pattern \"some::prefix\"",
        ValidationErrorNumberGreater: "Cannot be greater than",
        ValidationErrorNumberLess: "Cannot be less than",
        ValidationErrorRecordSizeNumeric: "Record Length should be a number",
        ValidationErrorRecordSizeRequired: "Record Length is required",
        ValidationErrorRequired: "This field is required",
        ValidationErrorTargetNameInvalid: "Invalid file name",
        ValidationErrorTargetNameRequired: "File name is required",
        Value: "Value",
        Variable: "Variable",
        VariableBigendian: "Variable Big-endian",
        Variables: "Variables",
        VariableSourceType: "Source Type",
        Version: "Version",
        ViewByScope: "View By Scope",
        Views: "Views",
        ViewSparkClusterInfo: "View Spark Cluster Information",
        Visualizations: "Visualizations",
        Visualize: "Visualize",
        WarnIfAvailableDiskSpaceIsUnder: "Warn if available disk space is under",
        WarnIfAvailableMemoryIsUnder: "Warn if available memory is under",
        WarnIfCPUUsageIsOver: "Warn if CPU usage is over",
        Warning: "Warning",
        Warnings: "Warning(s)",
        WarnOldGraphControl: "Warning:  Old Graph Control",
        What: "What",
        Where: "Where",
        Who: "Who",
        Width: "Width",
        WildcardFilter: "Wildcard Filter",
        Workflows: "Workflows",
        WorkType: "Work Type",
        Workunit: "Workunit",
        WorkunitContext: "Workunit Context",
        WorkunitNotFound: "Workunit not found",
        WorkunitOptions: "Workunit Options",
        Workunits: "Workunits",
        WorkUnitScopeDefaultPermissions: "Workunit Scope Default Permissions",
        WorkunitSummarySplitter: "Workunit Summary Splitter",
        Wrap: "Wrap",
        WSDL: "WSDL",
        WUID: "WUID",
        Wuidcannotbeempty: "Wuid Cannot Be Empty.",
        WUSnapshot: "WU Snapshot",
        WUSnapShot: "WU Snapshot",
        WUSnapshots: "WU Snapshots",
        WUSummary: "WU Summary",
        XGMML: "XGMML",
        XLS: "XLS",
        XML: "XML",
        XRef: "XRef",
        Year: "Year",
        YouAreAboutToBeLoggedOut: "You are about to be logged out",
        YouAreAboutToDeleteBinding: "You are about to delete this binding. Are you sure you want to do this?",
        YouAreAboutToDeleteDefinition: "You are about to delete this definition. Are you sure you want to do this?",
        YouAreAboutToDeleteThisFile: "You are about to delete this file. Are you sure you want to do this?",
        YouAreAboutToDeleteThisPart: "You are about to delete this part(s). Are you sure you want to do this?",
        YouAreAboutToDeleteThisQueryset: "You are about to delete this query set. Are you sure you want to do this?",
        YouAreAboutToDeleteThisWorkunit: "You are about to delete this workunit. Are you sure you want to do this?",
        YouAreAboutToRemoveUserFrom: "You are about to remove a user(s) from this group. Do you wish to continue?",
        YourBrowserMayNotSupport: "Your browser may not support file(s) of this size",
        YourScreenWasLocked: "Your screen was locked by ESP. Please re-fetch your data, as it may be stale.",
        ZAP: "Z.A.P",
        ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)",
        Zip: "Zip",
        ZippedAnalysisPackage: "Zipped Analysis Package",
        Zoom: "Zoom",
        Zoom100Pct: "Zoom 100%",
        ZoomAll: "Zoom All",
        ZoomMinus: "Zoom -",
        ZoomPlus: "Zoom +",
        ZoomSelection: "Zoom Selection",
        ZoomWidth: "Zoom Width"
    },
    "bs": true,
    "es": true,
    "fr": true,
    "hu": true,
    "hr": true,
    "pt-br": true,
    "sr": true,
    "zh": true
}
