#!/usr/bin/env python

'''
/*#############################################################################

    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
############################################################################ */
'''

import argparse
import logging
import os
import platform
import atexit
import traceback
import glob

from hpcc.regression.regress import Regression
from hpcc.util.ecl.file import ECLFile
from hpcc.util.util import checkPqParam,  getVersionNumbers

prog_version = "0.0.10"

if __name__ == "__main__":

    prog = "regress v:"+prog_version
    description = 'HPCC Platform Regression suite'
    pythonVer = getVersionNumbers()

    if (pythonVer['main'] <= 2) and (pythonVer['minor'] <=6) and (pythonVer['patch'] <6):
        print "\nError!"
        print "Your system has Python version "+platform.python_version()
        print "To run "+description+", you need version: 2.6.6 or higher, but less than 3.x!\n"
        exit()

    if pythonVer['main'] >= 3:
        print "\nError!"
        print "Your system has Python version "+platform.python_version()
        print "Actually "+description+", supports version >= 2.6.6 and <= 2.7.x\n"
        exit()

    if (pythonVer['main'] >= 2) and (pythonVer['minor'] >= 7):
        atexit.register(logging.shutdown)

    parser = argparse.ArgumentParser(prog=prog, description=description)
    parser.add_argument('--version', '-v', action='version',
                        version='%(prog)s')
    parser.add_argument('--config', help="config file to use. Default: regress.json",
                        nargs='?', default="regress.json")
    parser.add_argument('--loglevel', help="set the log level. Use debug for more detailed logfile.",
                        nargs='?', default="info",
                        choices=['info', 'debug'])
    parser.add_argument('--suiteDir', '-s', help="suiteDir to use. Default value is the current directory and it can handle relative path.",
                        nargs='?', default=".")
    parser.add_argument('--timeout', '-t', help="timeout for query execution in sec. Use -1 to disable timeout. Default value defined in regress.json config file.",
                        nargs='?', default="0")

    subparsers = parser.add_subparsers(help='sub-command help')
    parser_list = subparsers.add_parser('list', help='list help')
    parser_list.add_argument('clusters', help="Print clusters from config (regress.json by default).",
                             action='store_true')

    parser_run = subparsers.add_parser('run', help='run help')
    parser_run.add_argument('cluster', help="Run the cluster suite. Default value is setup.",
                            nargs='?', type=str,  default='setup')
    parser_run.add_argument('--pq', help="Parallel query execution with threadNumber threads. (If threadNumber is '-1' on a single node system then threadNumer = numberOfLocalCore * 2 )",
                            type=checkPqParam,  default = 0,   metavar="threadNumber")

    parser_query = subparsers.add_parser('query', help='query help')
    parser_query.add_argument('query', help="Name of a single ECL query. It can contain wildcards. (mandatory).",
                              nargs='?', metavar="ECL query")
    parser_query.add_argument('cluster', help="Cluster for single query run. If cluster = 'all' then run single query on all clusters. Default value is thor.",
                            nargs='?', default='thor', metavar="target_cluster | all")
    parser_query.add_argument('--publish', help="Publish compiled query instead of run.",
                            action='store_true')

    args = parser.parse_args()

    suiteDir = ""
    if 'suiteDir' in args:
        suiteDir = args.suiteDir
    timeout = -1
    if 'timeout' in args:
        timeout = args.timeout
    # Resolve Regression Suite starting path for regress.json config file
    # It is necessary when Regression Suite doesn't started from its home directory
    regressionSuiteMainDir = os.path.dirname(__file__)
    regressionSuiteFullPath = os.path.realpath(regressionSuiteMainDir)
    args.config = str(os.path.join(regressionSuiteFullPath, args.config))
    regress = None
    try:
        if 'clusters' in args:
            Clusters = ['setup']
            regress = Regression(args.config, args.loglevel, suiteDir)
            for cluster in regress.config.Clusters:
                Clusters.append(str(cluster))
            print "Avaliable Clusters: "
            for i in Clusters:
                print i
        if 'query' in args:
            if not args.query:
                print "\nMissing ECL query file!\n"
                parser_query.print_help()
                exit()
            regress = Regression(args.config, args.loglevel, suiteDir,  timeout)
            eclfiles=[]   # List for ECL filenames to be executed
            if  ('*' in args.query) or ('?' in args.query):
                # There is any wildcard in ECL file name, resolve it
                eclwild = os.path.join(regress.dir_ec, args.query)
                eclfiles = glob.glob(eclwild)

                # Sort ECL filenames to ensure correct execution order
                eclfiles.sort()

            else:
                # We have only one ECL file in parameter list, put it on the eclfile list
                ecl = os.path.join(regress.dir_ec, args.query)
                eclfiles.append(ecl)

            targetClusters = []
            if 'all' in args.cluster:
                for cluster in regress.config.Clusters:
                    targetClusters.append(str(cluster))
            else:
                targetClusters.append(args.cluster)
            # Go through the cluster list
            for cluster in targetClusters:
                try:
                    # Execute ECL files one by one on the cluster
                    for ecl in eclfiles:
                        eclfile = ECLFile(ecl, regress.dir_a, regress.dir_ex, regress.dir_r)
                        # Check if this query is not skip on this cluster and not part of setup
                        if (not eclfile.testSkip(cluster)['skip']) and (not eclfile.testSkip('setup')['skip'] ):
                            if not eclfile.testExclusion(cluster):
                                regress.runSuiteQ(cluster, eclfile)
                            else:
                                logging.warn("%s. %s excluded on %s cluster." % (1,  eclfile.getBaseEcl(), cluster))
                        else:
                            logging.warn("%s. %s skipped on %s cluster." % (1, eclfile.getBaseEcl(), cluster))
                except IOError:
                    logging.error("%s. Query %s does not exist!" % (1,  eclfile.getBaseEcl()))
                    exit()
            print("End.")
        elif 'cluster' in args:
            regress = Regression(args.config, args.loglevel, suiteDir,  timeout,  args.pq)
            regress.bootstrap(args.cluster)
            if 'setup' in args.cluster:
                regress.runSuite('setup', regress.Setup())
            else:
                if  args.pq :
                    regress.runSuiteP(args.cluster, regress.suites[args.cluster])
                else:
                    regress.runSuite(args.cluster, regress.suites[args.cluster])
            print("End.")
    except Exception as e:
        logging.critical(e)
        logging.critical(traceback.format_exc())
        print "Abend."
    except KeyboardInterrupt:
        logging.critical("Keyboard Interrupt Caught.")
        regress.StopTimeoutThread()

    exit()
