define(
    ({
        Abort: "Aborte",
        AbortedBy: "Abortado por",
        AbortedTime: "Abortado a las",
        About: "Acerca",
        AboutGraphControl: "Acerca del controlador gráfico",
        AboutHPCCSystems: "Acerca de HPCC Systems®",
        AboutHPCCSystemsGraphControl: "Acerca del controlador gráfico de HPCC Systems®",
        AboutToLoseSessionInformation: "Está a punto de cerrar la sesión y perder toda la información de la sesión. ¿Desea continuar?",
        Account: "Cuenta",
        Action: "Acción",
        Activate: "Activar",
        Activated: "Activado",
        ActivateQuery: "Activar Consulta",
        ActivateQueryDeletePrevious: "Activar Consulta, ¿Borrar anterior?",
        ActivateQuerySuspendPrevious: "Activar Consulta, suspender  anterior?",
        Active: "Activo",
        ActivePackageMap: "&lsquo;Package Map&rsquo; Activo",
        ActiveWorkunit: "Unidad activa",
        Activities: "Actividades",
        Activity: "Actividad",
        ActivityMap: "Mapa de Actividades",
        ActualSize: "Tamaño real",
        Add: "Agregar",
        AddAttributes: "Agregar atributos/valores a su método",
        AddAttributes2: "Agregar atributos",
        AddBinding: "Agregar conexión",
        AddFile: "Añadir Archivo",
        AddGroup: "Agregar Grupo",
        AdditionalResources: "Recursos  Adicionales",
        AddPart: "Agregar Parte",
        AddProcessMap: "Agregar &lsquo;Package Map&rsquo;",
        AddTheseFilesToDali: "¿Agregar estos archivos a Dali?",
        AddtionalProcessesToFilter: "Procesos adicionales a filtrar",
        AddToExistingSuperfile: "Agregar a un superarchivo existente",
        AddToSuperfile: "Agregar al Super-archivo",
        AddUser: "Aggregar Usuario",
        Advanced: "Advanzado",
        All: "Todos",
        AllowAccess: "<center>Permitir<br>Acceso</center>",
        AllowForeignFiles: "Permitir Archivo sExtranjeros",
        AllowFull: "<center>Permitir<br>Completo</center>",
        AllowRead: "<center>Permitir<br>Leer</center>",
        AllowWrite: "<center>Permitir<br>Escribir</center>",
        AllQueuedItemsCleared: "Todos los items encolados han sido eliminados. El trabajo en ejecución continuará corriendo",
        Analyze: "Analizar",
        ANY: "CUALQUIER",
        AnyAdditionalProcessesToFilter: "Procesos adicionales a filtrar",
        Append: "Agregar",
        AppendCluster: "Agregar Sistema",
        Apply: "Aplicar",
        ArchivedOnly: "Solo archivado",
        ArchivedWarning: "Advertencia: Por favor especifique rango de fechas corto. O si no, la recuperacion de workunits puede ser demorada.",
        Attach: "Adjuntar",
        Attribute: "Atributo",
        AttributesAreRequired: "Atributos son necesarios",
        Audience: "Audiencia",
        AuditLogs: "Registros de auditoría",
        AutoRefresh: "Actualizar Automaticamente",
        AutoRefreshEvery: "Auto-refrescar cada x minutos",
        AutoRefreshIncrement: "Incrementar auto-refresco",
        Back: "Atras",
        BannerColor: "Color de Banner",
        BannerMessage: "Mensaje del Banner",
        BannerScroll: "Desplazamiento del Banner",
        BannerSize: "Tamaño del Banner",
        BinaryInstalls: "Binarios instalables",
        Bind: "Conectar",
        Binding: "Conexión",
        BindingDeleted: "Conexión eliminada",
        Blob: "BLOB",
        BlobPrefix: "Prefijo de BLOB",
        Bottom: "Abajo",
        BoundBy: "Obligado por",
        Busy: "Ocupado",
        Cancel: "Cancelar",
        CancelAll: "Cancelar todo",
        CancelAllMessage: "Abortar trabajos en ejecución y limpiar la cola. Desearía continuar?",
        Chart: "Gráfico",
        CheckAllNodes: "Escoger todos los Nodos",
        CheckFilePermissions: "Escoger permisos de Archivo",
        CheckSingleNode: "Escoja un Archivo",
        Clear: "Despejar",
        ClearPermissionsCache: "Despejar Los Permisos Del Cache",
        ClearPermissionsCacheConfirm: "Esta seguro que desea despejar los permisos del Cache de DALI y ESP? Workunits en executo pueden demorarse asta que los Caches se actualicen",
        Clone: "Clonar",
        ClonedWUID: "WUID Clonado",
        CloneTooltip: "Duplicar Workunit",
        Close: "Cerrar",
        Cluster: "Sistema",
        ClusterName: "Nombre del sistema",
        ClusterPlaceholder: "r?x*",
        ClusterProcesses: "Procesos de sistema",
        Code: "Código",
        CodeGenerator: "Generador de Código",
        Col: "Columna",
        CollapseAll: "Colapsar Todo",
        Command: "Comando",
        Comment: "Comentario",
        Compiled: "Compilado",
        Compiling: "Compilando",
        Completed: "Completado",
        ComplexityWarning: "Mas de {threshold} actividades ({activityCount}) - ¿suprimir primer visualización?",
        Component: "Componente",
        ComponentLogs: "Registros de componentes",
        Compress: "Comprimir",
        Compressed: "Comprimido",
        CompressedFileSize: "Tamaño de Archivo Comprimido",
        ComputerUpTime: "Tiempo de trabajo de computadora",
        Condition: "Condición",
        Configuration: "Configuracion",
        ConfigureService: "Configurar servicio",
        ConfirmPassword: "Confirme la Contraseña",
        ConfirmRemoval: "¿Seguro que quieres hacer esto?",
        ContactAdmin: "Si quiere renombrar este grupo, por favor contacte su administrador de LDAP",
        Content: "Contenido",
        Contents: "Contenidos",
        ContentType: "Tipo de Contenido",
        ContinueWorking: "Sigue trabajando",
        Copied: "Copiado",
        Copy: "Copia",
        CopyToClipboard: "Copiar al portapapeles",
        CopyURLToClipboard: "Copia URL al portapapeles",
        CopyWUIDs: "Copiar WUIDs al portapapeles",
        CopyWUIDToClipboard: "Copia WUID al portapapeles",
        Count: "Número",
        CPULoad: "Carga de CPU",
        Create: "Crear",
        CreateANewFile: "Crear un nuevo superarchivo",
        Created: "Creado",
        CreatedBy: "Creado por",
        CreatedByWorkunit: "Creado por workunit",
        CreatedTime: "Tiempo creado",
        Creating: "Creando",
        Critical: "Crítico",
        CSV: "CSV",
        Dali: "Dali",
        DaliIP: "IP de Dali",
        DataPatterns: "Patrones de datos",
        DataPatternsNotStarted: "Análisis no se encuntra. Para comenzar, oprima el botón Analizar encima.",
        DataPatternsStarted: "Analizando. Cuando el reporte este completo se mostrará aquí.",
        dataset: ":=dataset*",
        Date: "Fecha",
        Day: "Dia",
        Deactivate: "Deactivar",
        Debug: "Depurar",
        DEF: "DEF",
        Defaults: "Valores por defecto",
        Definition: "Definición",
        DefinitionDeleted: "Definición eliminada",
        DefinitionID: "ID de definición",
        Definitions: "Definiciones",
        DelayedReplication: "Replicación retrasada",
        Delete: "Eliminar",
        DeleteBinding: "Eliminar conexión",
        Deleted: "Borrado",
        DeletedBinding: "Conexión eliminada",
        DeleteDirectories: "Eliminar directorios vaciós. Quiere continuar?",
        DeleteEmptyDirectories: "Eliminar directorios vaciós?",
        DeletePrevious: "Eliminar previo",
        DeleteSelectedDefinitions: "¿Eliminar definiciónes seleccionadas?",
        DeleteSelectedFiles: "¿Borrar archivos seleccionados?",
        DeleteSelectedGroups: "Eliminar  grupo(s) escojido(s)?",
        DeleteSelectedPackages: "Paqutes",
        DeleteSelectedPermissions: "Borrar permiso(s) escojido(s)?",
        DeleteSelectedQueries: "¿Borrar queries seleccionados?",
        DeleteSelectedUsers: "Eliminar Usuario(s) escojido(s)?",
        DeleteSelectedWorkunits: "¿Borrar unidades de trabajo seleccionadas?",
        DeleteSuperfile: "¿Borrar super-archivo?",
        DeleteSuperfile2: "¿Borrar Super-Archivo?",
        DeleteThisPackage: "Eliminar este paquete?",
        Delimited: "Delimitado",
        DenyAccess: "<center>Negar<br>Access</center>",
        DenyFull: "<center>Negar<br>Completo</center>",
        DenyRead: "<center>Negar<br>Leer</center>",
        DenyWrite: "<center>Negar<br>Escribir</center>",
        Depth: "Profundidad",
        DepthTooltip: "Máxima Profundidad de Subgrafo",
        Deschedule: "Eliminar del plan de ejecución",
        DescheduleSelectedWorkunits: "Desprogramar Workunit(s) escojida(s)?",
        Description: "Descripción",
        DESDL: "ESDL dinámico",
        Despray: "Despray",
        Details: "Detalles",
        DFUServerName: "Nombre del servidor de DFU",
        DFUWorkunit: "Unidad de Trabajo de DFU",
        Directories: "Directorios",
        Directory: "Directorio",
        DisableScopeScanConfirm: "Esta seguro que desea inhabilitar Scope Scans? Cuando DALI se reinicie, las opciones cambiadas se revierten a las opciones de la configuración.",
        DisableScopeScans: "Inhabilitar Scope Scans",
        DiskUsage: "Utilización del disco",
        Distance: "Distancia",
        DistanceTooltip: "Maxima Actividad Distancia de Vecindario",
        Dll: "Dll",
        Documentation: "Documentación",
        Domain: "Dominio",
        DoNotActivateQuery: "¿No activar consulta?",
        DoNotRepublish: "¿No volver a publicar?",
        DOT: "DOT",
        DOTAttributes: "Atributos DOT",
        Down: "Abajo",
        Download: "Descargar",
        Downloads: "Descargas",
        DownloadToCSV: "Bajar en formato CSV",
        DropZone: "Zona de carga",
        DueToInctivity: "Se desconectará de todas las sesiones de ECL Watch en 3 minutos debido a inactividad.",
        Duration: "Duración",
        DynamicNoServicesFound: "No se han encontrado servicios",
        EBCDIC: "EBCDIC",
        ECL: "ECL",
        ECLWatchRequiresCookies: "ECL Watch requiere cookies habilitadas para continuar.",
        ECLWatchSessionManagement: "Gestión de sesiones de ECL Watch",
        ECLWorkunit: "Unidad de Trabajo de ECL",
        Edges: "Bordes",
        Edit: "Editar",
        EditDOT: "Editar DOT",
        EditGraphAttributes: "Editar atributos gráficos",
        EditXGMML: "Editar XGMML",
        EmailBody: "Cuerpo del correo electronico",
        EmailFrom: "Dirección de correo electrónico (de)",
        EmailSubject: "Asunto",
        EmailTo: "Dirección de correo electrónico (a)",
        EmployeeID: "Identificador del empleado",
        EmployeeNumber: "Numero de empleado",
        Empty: "(Vacío)",
        Enable: "Habilitar",
        EnableScopeScans: "Activar Scope Scans",
        EnableScopeScansConfirm: "Esta seguro que desea activar Scope Scans?  Cuando DALI se reinicie, las opciones cambiadas se revierten a las opciones de la configuración.",
        EnglishQ: "Ingles?",
        EnterAPercentage: "Entre un porcentaje",
        EnterAPercentageOrMB: "Entre un porcentaje o MB",
        EraseHistory: "Borrar Historia",
        EraseHistoryQ: "Borrar historia de archivo:",
        Error: "Error",
        Errorparsingserverresult: "Error analizando los resultados del servidor",
        Errors: "Errores",
        ErrorsStatus: "Errores/Estado",
        ErrorUploadingFile: "Error subiendo archivo(s). Verifique los permisos",
        ErrorWarnings: "Error/Advertencia(s)",
        Escape: "Escapar",
        ESPBindings: "Conexiónes de ESP",
        ESPBuildVersion: "Versión de ESP",
        ESPNetworkAddress: "Dirección de red de ESP",
        ESPProcessName: "Nombre del proceso ESP",
        EventName: "Nombre del Evento",
        EventNamePH: "eventname",
        EventScheduler: "Planificador de eventos",
        EventText: "Texto del Evento",
        EventTextPH: "Texto del evento",
        Exception: "Excepción",
        Executed: "Ejecutado",
        Executing: "Ejecutando",
        ExpandAll: "Expandir Todo",
        ExpireDays: "Se vence en (días)",
        Export: "Exportar",
        ExportSelectionsToList: "Exportar selecciones a lista",
        FailIfNoSourceFile: "Falla si no hay archivo de origen",
        Fatal: "Fatal",
        Fetched: "Obtenido",
        FetchingData: "Obteniendo Data...",
        fetchingresults: "obteniendo resultados",
        File: "Archivo",
        FileCluster: "Racimo de archivos",
        FileCounts: "Numero de Archivos",
        FileName: "Nombre de archivo",
        FileParts: "Partes de archivos",
        FilePath: "Camino del archivo",
        FilePermission: "Permisos de Archivos",
        Files: "Archivos",
        FileScopeDefaultPermissions: "Permisos por defecto de alcance de archivos",
        FileScopes: "Ámbitos de Archivos",
        FileSize: "Tamaño de archivo",
        FilesNoPackage: "Archivos sin",
        FilesPending: "Archivos pendientes",
        FilesWarning: "La cantidad de archivos devueltos es demasiado grande. Solo se devolvieron los primeros 100000 archivos ordenados por fecha / hora modificada. Si desea limitar los resultados, configure un filtro.",
        FilesWithUnknownSize: "Archivos sin tamaño desconocido.",
        FileType: "Tipo de Archivo",
        FileUploader: "Subidor de archivo",
        FileUploadStillInProgress: "Carga de archivos todavia esta progresando",
        Filter: "Filtro",
        FilterSet: "Filtro definido",
        Find: "Encontrar",
        FindNext: "Encontrar próximo",
        FindPrevious: "Encontrar previo",
        Finished: "Terminado",
        FirstN: "PrimerosN",
        FirstName: "Primer Nombre",
        FirstNRows: "Primeras N Filas",
        Fixed: "Fijo",
        Folder: "Carpeta",
        Format: "Formato",
        Forums: "Foros",
        Forward: "Adelante",
        FoundFile: "Archivo encontrado",
        FoundFileMessage: "Todas las partes en disco del archivo encontrado no estan referenciadas en el servidor Dali. Todas las partes se han encontrado asi que pueden ser agregadas de nuevo al Servidor Dali. Las partes tambien pueden ser removidas del cluster, si es necesario.",
        FromDate: "Desde Fecha",
        FromSizes: "Desde Tamaños",
        FromTime: "Tiempo de Comenzar",
        FullName: "Nombre Entero",
        Generate: "Generar",
        GetPart: "Obtener parte",
        GetSoftwareInformation: "Obtener informacion del software",
        Graph: "Gráfico",
        GraphControl: "Control de gráficos",
        Graphs: "Gráficos",
        GraphView: "Vista del gráfico",
        Group: "Grupo",
        GroupBy: "Ordenar Por",
        GroupDetails: "Detalles del Grupo",
        Grouping: "Agrupacion",
        GroupName: "Nombre del grupo",
        GroupPermissions: "Permisos del Grupo",
        Groups: "Grupos",
        GZip: "GZip",
        help: "Esta área muestra el mapa de árbol de el/los gráfico(s) en esta unidad de trabajo. El tamaño y el tinte indican la duración de cada gráfico (más grande y más oscuro indica un porcentaje mayor de tiempo tomado.)",
        Helper: "Ayudador",
        Helpers: "Ayudantes",
        Hex: "exadecimal",
        HideSpills: "Esconder derrames",
        High: "Alto",
        History: "Historia",
        HPCCSystems: "HPCC Systems®",
        Icon: "Icono",
        ID: "ID",
        Inactive: "Inactivo",
        IncludeSlaveLogs: "Incluir slave logs",
        Index: "Indice",
        Info: "información",
        InfoDialog: "Diálogo informativo",
        Informational: "Informativo",
        InheritedPermissions: "Heredar Permisos",
        Inputs: "Entradas",
        InUse: "En uso",
        InvalidResponse: "(Respuesta invalida)",
        InvalidUsernamePassword: "Nombre de usuario o contraseña inválidos, inténtalo de nuevo",
        IP: "IP",
        IPAddress: "Dirección de IP",
        IsCompressed: "Está comprimido",
        IsLibrary: "Es biblioteca",
        IsReplicated: "Es Replicado",
        IssueReporting: "Informes de errores",
        JobName: "Nombre del trabajo",
        Jobname: "Nombre del trabajo",
        jsmi: "jsmi*",
        JSmith: "JSmit*",
        JSON: "JSON",
        KeyFile: "Archivo llave",
        KeyType: "Tipo de llave",
        Label: "Etiqueta",
        LandingZone: "Zona de descarga",
        LandingZones: "Zonas de aterrizaje",
        LanguageFiles: "Archivos de idiomas",
        Largest: "Mas Grande",
        LargestFile: "Archivo mas Grande",
        LargestSize: "Tomaño mas Grande",
        LastEdit: "Última edición",
        LastEditedBy: "Última edición por:",
        LastEditTime: "Última hora de edición",
        LastMessage: "Ultimo mensaje",
        LastName: "Apellido",
        LastNDays: "ULtimos N días",
        LastNHours: "Ultimas N Horas",
        LastNRows: "Ultimas N Filas",
        LastRun: "Ultima ejecución",
        LDAPWarning: "<b>Error en Servicios de LDAP:</b>  &lsquo;Demasiados Usuarios&rsquo; - Por favor aplique un Filtro.",
        LearnMore: "Aprende más",
        LegacyForm: "Forma histórica",
        Legend: "Leyanda",
        LibrariesUsed: "Bibliotecas usadas",
        LibraryName: "Nombre de Biblioteca",
        Line: "Línea",
        LineTerminators: "Terminadores de línea",
        Links: "Vínculos",
        Loading: "Cargando...",
        LoadingCachedLayout: "Cargando  Diseño de Memoria...",
        LoadingData: "Cargando data...",
        loadingMessage: "...Cargando...",
        LoadPackageContentHere: "(Cargar aqui el contenido del paquete)",
        LoadPackageFromFile: "Cargar paquete con contenido de archivo",
        Local: "Local",
        LocalFileSystemsOnly: "Sistema de archivos locales solamente",
        Location: "Ubicación",
        Lock: "Cerrar",
        Log: "Registro",
        log_analysis_1: "log_analysis_1*",
        LogDirectory: "Directorio de logs",
        LogFile: "Archivo de registro",
        LoggedInAs: "Conectado como",
        LoggingOut: "Saliendo",
        LogicalFile: "Archivo Lógico",
        LogicalFiles: "Archivos lógicos",
        LogicalFilesAndSuperfiles: "Archivo lógico y Superfiles",
        LogicalFilesOnly: "Archivos logicos Solamente",
        LogicalFileType: "Tipo de archivo lógico",
        LogicalName: "Nombre lógico",
        Login: "Iniciar sesión",
        Logout: "Cerrar sesión",
        Logs: "Registros",
        LogVisualization: "Visualización de registros",
        LogVisualizationUnconfigured: "La visualización del registro no está configurada, verifique las configuraciones de su administrador de configuración.",
        LostFile: "Archivo perdido",
        LostFile2: "Archivos perdidos",
        LostFileMessage: "Un archivo lógico ha perdido al menos una de sus partes en ambas ubicaciones, primary y replicada. El archivo lógico aún está referenciado en el servidor Dali. Eliminando este archivo se remueven la referencia en el servidor Dali y todas las partes existentes en disco.",
        Low: "Bajo",
        MachineInformation: "Información de las máquinas",
        Machines: "Máquinas",
        Major: "Mayor",
        ManagedBy: "Manejado por",
        ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
        ManualCopy: "Oprima Crtl_C",
        ManualOverviewSelection: "Seleccion manual sera requirida",
        ManualTreeSelection: "Seleccion manual de arbol sera requirida",
        Mappings: "Mapeados",
        Mask: "Máscara",
        Max: "Máx",
        MaximizeRestore: "Maximizar / Restaurar",
        MaximumNumberOfSlaves: "Numero de esclavo",
        MaxNode: "Nodo máximo",
        MaxRecordLength: "Máx largo de registros",
        MaxSize: "Tamaňo máximo",
        MaxSkew: "Sesgo máximo",
        MaxSkewPart: "Sesgo máximo por parte",
        Mean: "Media",
        MemberOf: "Miembro de",
        Members: "Miembros",
        Message: "Mensaje",
        MethodConfiguration: "Configuracion de Método",
        Methods: "Métodos",
        Min: "Minimo",
        Mine: "Mío",
        MinNode: "Nodo mínimo",
        Minor: "Menor",
        MinSize: "Tamaňo mínimo",
        MinSkew: "Sesgo mínimo",
        MinSkewPart: "Sesgo minimo por parte",
        Missing: "Falta",
        MixedNodeStates: "Estado mixto de nodo",
        Modification: "Modificación",
        Modified: "modificado",
        ModifiedUTCGMT: "Modificado (UTC/GMT)",
        Modify: "Modificar",
        MonitorEventName: "Nombre del evento monitor",
        Monitoring: "Monitoreando",
        MonitorShotLimit: "Límite de disparos del monitor",
        MonitorSub: "Sub monitor",
        Month: "Mez",
        More: "Mas",
        MustContainUppercaseAndSymbol: "Debe Contener mayúscula y símbolo",
        NA: "No Applica",
        Name: "Nombre",
        NamePrefix: "Prefijo del nombre",
        NamePrefixPlaceholder: "algun::prefijo",
        NetworkAddress: "Dirección de red",
        Newest: "El Mas Nuevo",
        NewPassword: "Nueva Contraseña",
        NoContent: "(No hay contenido)",
        noDataMessage: "...Zero Filas...",
        Node: "Nodo",
        NodeGroup: "Grupo de Nodos",
        NoErrorFound: "Ningun Error Detectado",
        NoFilterCriteriaSpecified: "No especificó criterio de filtro.",
        None: "Ninguno",
        NoPublishedSize: "Tamaňo no publicado",
        Normal: "Normal",
        NoScheduledEvents: "Ningun evento programado.",
        NoSplit: "No corte",
        NotActive: "Inacivado",
        NothingSelected: "Nada Seleccionado",
        NotInSuperfiles: "No en las Superfiles",
        NotSuspendedbyUser: "No suspendido por el Usario",
        NoWarningFound: "Ninguna Advertencia Detectada",
        NumberofParts: "Número de partes",
        NumberofSlaves: "Numero de esclavos",
        OK: "Aceptar",
        Oldest: "Mas Antiguo",
        OldPassword: "Contraseña Antigua",
        OmitSeparator: "Omite Separador",
        Only1PackageFileAllowed: "Solo un archivo de paquetes permitido",
        Open: "Abrir",
        OpenConfiguration: "Abrir Configuración",
        OpenInNewPage: "Open In New Page",
        OpenInNewPageNoFrame: "Abrir en nueva pagina (No Marco)",
        OpenLegacyECLWatch: "Abrir ECL Watch viejo",
        OpenLegacyMode: "Abrir (legacia)",
        OpenNativeMode: "Abrir (nativo)",
        OpenSafeMode: "Abrir (modo seguro)",
        OpenSource: "Código Abierto",
        OpenTreeMode: "Abrir (vista en arbol)",
        Operation: "Operación",
        Operations: "Operaciones",
        Optimize: "Optimizar",
        Options: "Opciones",
        OriginalFile: "Archivo Original",
        OrphanFile: "Archivos huérfanos",
        OrphanFile2: "Archivo huérfano",
        OrphanMessage: "Un archivo huérfano tiene solo algunas de sus partes en disco. Sin embargo, el conjunto completo de partes no esta disponible para construir un archivo logico completo. No hay referencias a estas partes de archivo en el servidor Dali.",
        Outputs: "Salidas",
        Overview: "Visión de conjunto",
        Overwrite: "Sobreescribir",
        OverwriteMessage: "Algunos archivos estan presentes. Por favor Seleccione la casilla de verificación para continuar.",
        Owner: "Dueño",
        PackageContent: "Contenidos del Paquete",
        PackageContentNotSet: "Los Contenidos del Paquete no este definido",
        PackageMap: "Mapa del paquete",
        PackageMaps: "Mapas del paquete",
        PackagesNoQuery: "Paqutes sin correspondiente consulta",
        ParameterXML: "Parámetro XML",
        Part: "Parte",
        PartMask: "Máscara de parte",
        PartName: "Nombre de parte",
        Parts: "Partes",
        PartsFound: "Partes encontradas",
        PartsLost: "Partes perdidas",
        Password: "Contraseña",
        PasswordExpiration: "Expiración de Contraseñas",
        PasswordExpired: "Su contraseña expiro. Por favor cambiela.",
        PasswordExpirePostfix: " dia(s). Desea cambiarla?",
        PasswordExpirePrefix: "Su contraseña expira en",
        PasswordOpenZAP: "Contraseña para abrir ZAP (opcional)",
        PasswordsDoNotMatch: "Las Contraseñas No Coinciden",
        Path: "Camino",
        PathMask: "Máscara del camino",
        Pause: "Pausa",
        PauseNow: "Pausar",
        PctComplete: "% completado",
        PercentCompressed: "Porcentaje comprimido",
        PercentDone: "Porcentaje completado",
        PercentUsed: "% Usado",
        PerformingLayout: "Generando disposición...",
        Permission: "Permiso",
        PermissionName: "Nombre del Permiso",
        Permissions: "Permisos",
        PhysicalFiles: "Archivo físico",
        PlaceholderFindText: "Wuid, usuario, mas...",
        PlaceholderFirstName: "John",
        PlaceholderLastName: "Smith",
        Platform: "Plataforma",
        Playground: "Patio de juegos",
        PleaseEnableCookies: "ECL Watch requiere que las cookies esten habilitadas para poder continuar.",
        PleaseEnterANumber: "Por favor escriba un numero 1 -",
        PleaseLogin: "Por favor inicie sesión usando su nombre de usuario y contraseña",
        PleaseLogIntoECLWatch: "Por favor inicie sesión de ECL Watch",
        PleasePickADefinition: "Por favor seleccione una definición",
        PleaseSelectADynamicESDLService: "Por favor seleccione un servicio de ESDL dinámico",
        PleaseSelectAGroupToAddUser: "Por favor escoja un grupo al cual agregar el usario",
        PleaseSelectAServiceToBind: "Seleccione un servicio para conectar",
        PleaseSelectATopologyItem: "Por favor seleccione un destino, servicio o máquina",
        PleaseSelectAUserOrGroup: "Por favor escoja un usario o grupo y nombre de archivo",
        PleaseSelectAUserToAdd: "Por favor escoja el usario para agregar",
        Plugins: "Complementos",
        Port: "Puerto",
        Prefix: "Prefijo",
        PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
        Preflight: "Pre-volado",
        PreloadAllPackages: "Precargar todos los paquetes",
        PreserveCompression: "Preservar Compression",
        PressCtrlCToCopy: "Oprima ctrl+c para copiar",
        Preview: "Presentación Preliminar",
        PrimaryLost: "Primario perdido",
        PrimaryMonitoring: "Monitoreado Principal",
        Priority: "Prioridad",
        Process: "Proceso",
        Processes: "Procesos",
        ProcessFilter: "Filtro de Procesos",
        ProcessorInformation: "Información del procesador",
        ProgressMessage: "Mensaje de progreso",
        Properties: "Propiedades",
        Property: "Propiedad",
        Protect: "Proteger",
        Protected: "Protegido",
        Protocol: "Protocolo",
        Publish: "Publicar",
        Published: "Publicado",
        PublishedBy: "Publicado por",
        PublishedByMe: "Publicado por mí",
        PublishedQueries: "Queries publicados",
        PushEvent: "Evento de Inserción",
        Quarter: "Cuarto",
        Queries: "Consultas",
        QueriesNoPackage: "Consultas sin correspondiente paquete",
        Query: "Consulta",
        QueryDetailsfor: "Detalles de Consulta por",
        QueryID: "ID de la Consulta",
        QueryIDPlaceholder: "som?q*ry.1",
        QueryName: "Nombre de la Consulta",
        QueryNamePlaceholder: "My?Su?erQ*ry",
        QuerySet: "Grupo de Consulta",
        Queue: "Cola",
        Quote: "Comilla",
        QuotedTerminator: "Terminador Encomillado",
        RawData: "Datos Actual",
        RawTextPage: "Texto (Pagina Actual)",
        Ready: "Listo",
        ReallyWantToRemove: "Confirme que quiere eliminar",
        ReAuthenticate: "Reafirmar para abrir",
        RecordCount: "Número de registros",
        RecordLength: "Largo de registro",
        Records: "Registros",
        RecordSize: "Tamaño del registro",
        RecordStructurePresent: "Estructura del Registro esta presente",
        Recover: "Recuperar",
        RecoverTooltip: "Reiniciar workunit en pausa / estancado",
        RecreateQuery: "Recrear consulta",
        Recycling: "Reciclando",
        RedBook: "Red Book",
        Refresh: "Actualizar",
        ReleaseNotes: "Notas de la versión",
        Reload: "Recargar",
        Remaining: "Restante",
        RemoteCopy: "Copia Remota",
        RemoteDali: "Dali remoto",
        RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
        Remove: "Remover",
        RemoveAttributeQ: "Está por eliminar este atributo. Está seguro de que desea continuar?",
        RemoveAtttributes: "Eliminar atributo(s)",
        RemovePart: "Eliminar parte(s)",
        RemoveSubfiles: "Quitar Sub-Archivo(s)",
        RemoveSubfiles2: "Quitar subarchivo(s)",
        RemoveUser: "Esta apunto de excluirse del grupo:",
        Rename: "Renombrar",
        RenderedSVG: "SVG creado",
        RenderSVG: "Crear SVG",
        Replicate: "Replicar",
        ReplicatedLost: "Réplica perdida",
        ReplicateOffset: "Offset de Reproducción",
        Report: "Reporte",
        ReportAnError: "Reportar un error",
        ReportError: "Informe de error",
        RepresentsASubset: "Representar un subconjunto de todas los casamientos. Usando un filtro correcto puede reducir el numero de casamientos",
        RequestSchema: "Esquema del requerimiento",
        RequiredForFixedSpray: "Obligatorio para spray fijo",
        RequiredForXML: "Obligatorio para spray data en XML",
        Reschedule: "Re-planear ejecución",
        Reset: "Origen",
        ResetThisQuery: "Reajustar esta Consulta",
        ResetViewToSelection: "Reajustar Vista a la Seleccion",
        Resource: "Recurso",
        Resources: "Recursos",
        ResponseSchema: "Esquema de la respuesta",
        Restart: "Empezar de nuevo",
        Restarted: "Reiniciado",
        Restore: "Restaurar",
        Restricted: "Restringido",
        Resubmit: "Reenviar",
        Resubmitted: "Reenviado",
        ResubmitTooltip: "Someter workunit de nuevo",
        Results: "Resultado(s)",
        Resume: "Continuar",
        RetainSuperfileStructure: "Retener estructura del super-archivo",
        RetypePassword: "Confirme la contraseña",
        Reverse: "Marchar Atrás",
        RowPath: "Ruta de Fila",
        Rows: "Líneas",
        RowTag: "Etiqueta de línea",
        RoxieCluster: "Sistema Roxie",
        RoxieFileCopy: "Estado de copia de archivos de Roxie",
        RoxieState: "Estado de Roxie",
        RunningServerStrain: "La ejecución de este proceso puede tomar un tiempo largo y pondrá una carga significativa en los servidores. Desea continuar?",
        Sample: "Ejemplo",
        SampleRequest: "Ejemplo del requerimiento",
        SampleResponse: "Ejemplo de la respuesta",
        Save: "Guardar",
        Scope: "Ámbito",
        SearchResults: "Resultados de búsqueda",
        SecondsRemaining: "Segundos que faltan",
        Security: "Seguridad",
        SelectPackageFile: "Seleccione &lsquo;Package File&rsquo;",
        SendEmail: "Enviar correo electrónico",
        Separators: "Seperadores",
        Server: "Servidor",
        ServiceName: "Nombre del servicio",
        Services: "Servicios",
        ServiceType: "Tipo de servicio",
        SetBanner: "Configurar la bandera",
        SetTextError: "No se pudo visualizar el texto (muy grande?). Use &lsquo;helpers&rsquo; para descargar.",
        SetToFailed: "Marcar como fallado",
        Severity: "Severidad",
        ShareWorkunit: "Compartir workunit",
        Show: "Mostrar",
        ShowProcessesUsingFilter: "Mostrar procesos usando filtro",
        ShowSVG: "Mostrar SVG",
        Size: "Tamaño",
        Skew: "Desbalance",
        SkewNegative: "Desbalanceado(-)",
        SkewPositive: "Desbalanceado(+)",
        SLA: "SLA",
        SlaveLogs: "Slave logs",
        SlaveNumber: "Numero de esclavo",
        Slaves: "Esclavos",
        Smallest: "El Mas Pequeño",
        SmallestFile: "Archivo mas Pequeño",
        SmallestSize: "Tamaño mas Pequeño",
        SOAP: "SOAP",
        SomeDescription: "Alguna*Descripcion",
        somefile: "*::archivo*",
        Source: "Origen",
        SourceCode: "Código fuente",
        SourceLogicalFile: "Nombre logico",
        SourcePath: "Directorio (Se puede usar Asterisco)",
        SourceProcess: "Processo de Origen",
        SparkThor: "SparkThor",
        Spill: "Regar",
        SplitPrefix: "Corte prefijo",
        Spray: "Rociar",
        Start: "Comienzo",
        Started: "Comenzado",
        Starting: "Comenzando",
        State: "Estado",
        Stats: "Estatísticas",
        Status: "Estado",
        Stopped: "Detenido",
        Stopping: "Deteniendo",
        StorageInformation: "Información del almacenamiento",
        Subgraph: "Subgrafo",
        Subgraphs: "Sub-gráficos",
        Submit: "Enviar",
        Subtype: "Subtipo",
        SuccessfullySaved: "Guardado",
        Summary: "Resumen",
        SummaryMessage: "Mensaje resumido",
        SuperFile: "Super File",
        Superfile: "Superfile",
        Superfiles: "Super-Archivos",
        SuperFiles: "Superfiles",
        SuperFilesBelongsTo: "Miembro de Super-Archivo(s)",
        SuperfilesOnly: "Solo Superfiles",
        SuperOwner: "Dueño de Superfiles",
        Suspend: "Suspender",
        Suspended: "Suspendido",
        SuspendedBy: "Suspendido por",
        SuspendedByCluster: "Suspendido  por el Clúster",
        SuspendedByUser: "Suspendido por el Usuario",
        SuspendedReason: "Rason porque se suspendio",
        SVGSource: "Origen del SVG",
        Sync: "Sincronizar",
        SyncSelection: "Sincronizar",
        SystemServers: "Servidores de sistema",
        Table: "Tabla",
        tag: "etiqueta",
        Target: "Destino",
        TargetClusters: "Sistemas de destino",
        TargetClustersLegacy: "Sistemas de destino (legado)",
        TargetName: "Nombre del &lsquo;Target&rsquo;",
        TargetNamePlaceholder: "nombre::dealgunl::archivo::logico",
        TargetRowTagRequired: "Es necesario suministrar el código de fila",
        Targets: "Destinos",
        TargetScope: "Ámbito Objetivo",
        TargetWuid: "Wuid del Objecto",
        Terminators: "Terminadores",
        TestPages: "Páginas de prueba",
        Text: "Texto",
        TheReturnedResults: "Los resultados regresados",
        ThorMasterAddress: "Direccion del Thor Master",
        ThorNetworkAddress: "Dirección de red de Thor",
        ThorProcess: "Proceso de Thor",
        Time: "Tiempo",
        Timers: "Cronómetros",
        TimeSeconds: "Tiempo (Segundos)",
        TimeStamp: "Marca de tiempo",
        TimeStarted: "Tiempo empezado",
        TimeStopped: "Tiempo detenido",
        Timings: "Tiempos",
        TimingsMap: "Mapa de tiempos",
        title_ActiveGroupPermissions: "Permisos del Grupo Vigente",
        title_ActivePermissions: "Permisos Vigentes",
        title_Activity: "Actividad",
        title_AvailableGroupPermissions: "Permisos de Grupo disponibles",
        title_AvailablePermissions: "Permisos Disponibles",
        title_BindingConfiguration: "Configuración de conexión",
        title_BindingDefinition: "Definición de conexión",
        title_ClusterInfo: "Grupos",
        title_Clusters: "Sistemas",
        title_CodeGeneratorPermissions: "Permisos de generador de codigo",
        title_DefinitionExplorer: "Explorador de Definiciónes",
        title_Definitions: "Definiciónes",
        title_DESDL: "ESDL dinámico",
        title_DFUQuery: "Archivos Lógicos",
        title_DFUWUDetails: "Unidad de trabajo DFU",
        title_DirectoriesFor: "Directorios para",
        title_DiskUsage: "Utilización del disco",
        title_ECLPlayground: "ECL Playground",
        title_ErrorsWarnings: "Errores/Advertencias de",
        title_EventScheduleWorkunit: "Planificador de Eventos",
        title_FileScopeDefaultPermissions: "Permisos de archive por defecto",
        title_FilesPendingCopy: "Archivos pendientes para copiar",
        title_FoundFilesFor: "Archivos encontrados para",
        title_GetDFUWorkunits: "Unidades de trabajo DFU",
        title_Graph: "Gráficos",
        title_GraphPage: "título",
        title_Graphs: "Gráficos",
        title_GridDetails: "Cámbieme",
        title_History: "Historia",
        title_HPCCPlatformECL: "ECL Watch - Hogar",
        title_HPCCPlatformFiles: "ECL Watch - Archivos",
        title_HPCCPlatformMain: "ECL Watch - Hogar",
        title_HPCCPlatformOps: "ECL Watch - Operaciones",
        title_HPCCPlatformRoxie: "ECL Watch - Roxie",
        title_HPCCPlatformServicesPlugin: "ECL Watch - dispositivo opcional",
        title_Inputs: "Entradas",
        title_LFDetails: "Detalles de archivos lógicos",
        title_LibrariesUsed: "Librerias Usadas",
        title_Log: "Archivo de Registro",
        title_LostFilesFor: "Archivos perdidos para",
        title_LZBrowse: "Zonas de descarga",
        title_MemberOf: "Miembros de",
        title_Members: "Miembros",
        title_Methods: "Métodos",
        title_OrphanFilesFor: "Archivos huérfanos para",
        title_PackageParts: "Partes de paquete",
        title_Permissions: "Permisos",
        title_Preflight: "Métricas del sistema",
        title_PreflightResults: "Resultados de pre-volado",
        title_QuerySetDetails: "Detalles de Consulta",
        title_QuerySetErrors: "Errores",
        title_QuerySetLogicalFiles: "Archivos lógicos",
        title_QuerySetQuery: "Consultas",
        title_QuerySetSuperFiles: "Super archivos",
        title_QueryTest: "Super Archivos",
        title_Result: "Actividad",
        title_Results: "Salidas",
        title_SearchResults: "Resultados de búsqueda",
        title_SourceFiles: "Archivo de origen",
        title_SystemServers: "Servidor del sistema",
        title_SystemServersLegacy: "Servidor del sistema (legacia)",
        title_TargetClusters: "Sistemas de destino",
        title_Topology: "Topología",
        title_TpThorStatus: "Estatus de Thor",
        title_UserPermissions: "Permisos del Usuario",
        title_UserQuery: "Permisos",
        title_WorkunitScopeDefaultPermissions: "Permisos de workunits por defecto",
        title_WUDetails: "Detalles de las unidades de trabajo ECL",
        title_WUQuery: "Unidades de trabajo ECL",
        To: "A:",
        ToDate: "Hasta fecha",
        Toenablegraphviews: "Para habilitar vista de gráficos, instale el plugin Graph View Control",
        Tooltip: "Globo de información",
        TooManyFiles: "Demasiados archivos",
        Top: "Arriva",
        Topology: "Topología",
        ToSizes: "A tamaño",
        Total: "Total",
        TotalClusterTime: "Tiempo Total del Cluster",
        TotalParts: "Total de partes",
        TotalSize: "Tamaño Total",
        TotalThorTime: "Tiempo total de Thor",
        TransitionGuide: "Guía de transición",
        Tree: "Arbol",
        Type: "Tipo",
        Unbound: "No esta consolidado",
        undefined: "no definido",
        Unknown: "Desconocido",
        Unlock: "Abrir",
        Unprotect: "Desproteger",
        UnsupportedIE9FF: "No se ofrece soporte (IE <= 9, FireFox)",
        Unsuspend: "De-suspender",
        Unsuspended: "Des-suspendido",
        Up: "Arriba",
        UpdateCloneFrom: "Actualizar clon de",
        UpdateDFs: "Actualizar DFS",
        UpdateSuperFiles: "Actualizar superfile",
        Upload: "Subir",
        UpTime: "Tiempo de trabajo",
        URL: "URL",
        Usage: "Utilización",
        Used: "Usado",
        UsedByWorkunit: "Usado por workunit",
        User: "Usuario",
        UserDetails: "Detalles del Usuario",
        UserID: "ID del Usuarion",
        UserLogin: "Por favor inicie sesión usando solo su nombre de usuario",
        UserName: "Nombre de Usario",
        Username: "NombreDeUsario",
        UserPermissions: "Permisos del Usuario",
        Users: "Usuarios",
        UseSingleConnection: "Use una sola conexión",
        Validate: "Validar",
        ValidateActivePackageMap: "Validar Package Map Activo",
        ValidatePackageContent: "Validar Contenido de Paquete",
        ValidatePackageMap: "Validar el Package Map",
        ValidateResult: "=====Velida el Resultado=====\n\n",
        ValidateResultHere: "(resultado de la validación)",
        Value: "Valor",
        Variable: "Variable",
        VariableBigendian: "Variable &lsquo;Big-endian&rsquo;",
        Variables: "Variables",
        VariableSourceType: "Formato",
        Version: "Versión",
        ViewByScope: "&lsquo;Ver Por Ámbito&rsquo;",
        Views: "Vistas",
        ViewSparkClusterInfo: "Ver Información de Sistema Spark",
        Visualize: "Visualizar",
        WarnIfAvailableDiskSpaceIsUnder: "Advertencia si disco disponible esta debajo de",
        WarnIfAvailableMemoryIsUnder: "Advertencia si memoria disponible esta debajo de",
        WarnIfCPUUsageIsOver: "Advertencia si uso de CPU esta arriba de",
        Warning: "Advertencia",
        Warnings: "Advertencias",
        WarnOldGraphControl: "Advertencia: Controlador de Graphicas antiguo",
        What: "Que",
        Where: "Donde",
        Who: "Quien",
        Width: "Ancho",
        Workflows: "Flujos de Trabajo",
        Workunit: "Unidad de trabajo",
        Workunits: "Unidades de trabajo",
        WorkUnitScopeDefaultPermissions: "Permisos por defect de alcaces de Workunit",
        Wrap: "Envolver",
        WSDL: "WSDL",
        WUID: "WUID",
        Wuidcannotbeempty: "Wuid no puede estar vacío.",
        WUSnapShot: "Captura de Unidad de trabajo",
        XGMML: "XGMML",
        XLS: "XLS",
        XML: "XML",
        XRef: "Referencias cruzadas",
        Year: "Año",
        YouAreAboutToBeLoggedOut: "Estás a punto de ser desconectado",
        YouAreAboutToDeleteBinding: "Está a punto de eliminar esta conexión. Desea continuar?",
        YouAreAboutToDeleteDefinition: "Estás a punto de eliminar esta definición. ¿Estás seguro que quieres hacer esto?",
        YouAreAboutToDeleteThisFile: "Usted esta a punto de eliminar este archivo. ¿Desea continuar?",
        YouAreAboutToDeleteThisPart: "Usted esta a punto de eliminar esta parte. ¿Desea continuar?",
        YouAreAboutToDeleteThisQueryset: "Usted esta a punto de eliminar este grupo de consulta. ¿Desea continuar?",
        YouAreAboutToDeleteThisWorkunit: "Usted esta a punto de eliminar este workunit. ¿Desea continuar?",
        YouAreAboutToRemoveUserFrom: "Usted esta a punto de quitar un(os) usuario(s) de este grupo. ¿Desea continuar?",
        YourBrowserMayNotSupport: "Es posible que su navegador no soporta archivos de este tamaño",
        YourScreenWasLocked: "Tu pantalla fue bloqueada por ESP. Por favor, vuelve a buscar sus datos, que puede estar obsoleto.",
        ZAP: "Z.A.P.",
        ZeroLogicalFilesCheckFilter: "Archivos logicos a cero (chequee filtro)",
        Zip: "Zip",
        ZippedAnalysisPackage: "Paquete de análisis en formato Zip",
        Zoom: "Enfocar",
        Zoom100Pct: "Aumentar a 100%",
        ZoomAll: "Aumentar todo",
        ZoomMinus: "Enfocar menos",
        ZoomPlus: "Enfocar más",
        ZoomWidth: "Aumentar al ancho"
    })
);
