define(
({
    Abort: "Aborte",
    About: "Acerca",
    AboutGraphControl: "Acerca del controlador gráfico",
    AboutHPCCSystemsGraphControl: "Acerca del controlador gráfico de HPCC Systems®",
    Account: "Cuenta",
    Action: "Acción",
    Activate: "Activar",
    Activated: "Activado",
    Active: "Activo",
    ActivePackageMap: "'Package Map' Activo",
    ActiveWorkunit: "Unidad activa",
    Activities: "Actividades",
    Activity: "Actividad",
    ActivityMap: "Mapa de Actividades",
    ActualSize: "Tamaño real",
    Add: "Agregar",
    AddFile: "Añadir Archivo",
    AddGroup: "Agregar Grupo",
    AdditionalResources: "Recursos  Adicionales",
    AddProcessMap: "Agregar 'Package Map'",
    AddToSuperfile: "Agregar al Super-archivo",
    AddUser: "Aggregar Usuario",
    Advanced: "Advanzado",
    All: "Todos",
    AllowAccess: "<center>Permitir<br>Acceso</center>",
    AllowForeignFiles: "Permitir Archivo sExtranjeros",
    AllowFull: "<center>Permitir<br>Completo</center>",
    AllowRead: "<center>Permitir<br>Leer</center>",
    AllowWrite: "<center>Permitir<br>Escribir</center>",
    ANY: "CUALQUIER",
    Append: "Agregar",
    Apply: "Aplicar",
    ArchivedOnly: "Solo archivado",
    ArchivedWarning: "Advertencia: Por favor especifique rango de fechas corto. O si no, la recuperacion de workunits puede ser demorada.",
    AutoRefresh: "Actualizar Automaticamente",
    Back: "Atras",
    BannerColor: "Color de Banner",
    BannerMessage: "Mensaje del Banner",
    BannerScroll: "Desplazamiento del Banner",
    BannerSize: "Tamaño del Banner",
    BinaryInstalls: "Binarios instalables",
    Blob: "BLOB",
    BlobPrefix: "Prefijo de BLOB",
    Bottom: "Abajo",
    Cancel: "Cancelar",
    CheckAllNodes: "Escoger todos los Nodos",
    CheckFilePermissions: "Escoger permisos de Archivo",
    CheckSingleNode: "Escoja un Archivo",
    Clear: "Borrar",
    Clear: "Despejar",
    ClearPermissionsCache: "Despejar Los Permisos Del Cache",
    ClearPermissionsCacheConfirm: "Esta seguro que desea despejar los permisos del Cache de DALI y ESP? Workunits en executo pueden demorarse asta que los Caches se actualicen",
    Clone: "Clonar",
    CloneTooltip: "Duplicar Workunit",
    ClonedWUID: "WUID Clonado",
    Close: "Cerrar",
    Cluster: "Sistema",
    ClusterName: "Nombre del sistema",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesos de sistema",
    Code: "Código",
    CodeGenerator: "Generador de Código",
    Col: "Columna",
    CollapseAll: "Colapsar Todo",
    Command: "Comando",
    Comment: "Comentario",
    Completed: "Completado",
    ComplexityWarning: "Mas de {threshold} actividades ({activityCount}) - ¿suprimir primer visualización?",
    Component: "Componente",
    Compress: "Comprimir",
    Compressed: "Comprimido",
    CompressedFileSize: "Tamaño de Archivo Comprimido",
    Configuration: "Configuracion",
    ConfirmPassword: "Confirme la Contraseña",
    ConfirmRemoval: "¿Seguro que quieres hacer esto?",
    Content: "Contenido",
    Contents: "Contenidos",
    ContentType: "Tipo de Contenido",
    Copy: "Copia",
    Count: "Número",
    Created: "Creado",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Fecha",
    Day: "Dia",
    Deactivate: "Deactivar",
    Debug: "Depurar",
    DEF: "DEF",
    Defaults: "Valores por defecto",
    Delete: "Eliminar",
    Deleted: "Borrado",
    DeleteSelectedFiles: "¿Borrar archivos seleccionados?",
    DeleteSelectedGroups: "Eliminar  grupo(s) escojido(s)?",
    DeleteSelectedPermissions: "Borrar permiso(s) escojido(s)?",
    DeleteSelectedQueries: "¿Borrar queries seleccionados?",
    DeleteSelectedUsers: "Eliminar Usuario(s) escojido(s)?",
    DeleteSelectedWorkunits: "¿Borrar unidades de trabajo seleccionadas?",
    DeleteSuperfile2: "¿Borrar Super-Archivo?",
    DeleteSuperfile: "¿Borrar super-archivo?",
    DeleteThisPackage: "Eliminar este paquete?",
    Delimited: "Delimitado",
    DenyAccess: "<center>Negar<br>Access</center>",
    DenyFull: "<center>Negar<br>Completo</center>",
    DenyRead: "<center>Negar<br>Leer</center>",
    DenyWrite: "<center>Negar<br>Escribir</center>",
    Depth: "Profundidad",
    DepthTooltip: "Máxima Profundidad de Subgrafo",
    Deschedule: "Eliminar del plan de ejecución",
    DescheduleSelectedWorkunits: "Desprogramar Workunit(s) escojida(s)?",
    Description: "Descripción",
    Despray: "Despray",
    Details: "Detalles",
    DFUServerName: "Nombre del servidor de DFU",
    DFUWorkunit: "Unidad de Trabajo de DFU",
    Directory: "Directorio",
    DisableScopeScanConfirm: "Esta seguro que desea inhabilitar Scope Scans? Cuando DALI se reinicie, las opciones cambiadas se revierten a las opciones de la configuración.",
    DisableScopeScans: "Inhabilitar Scope Scans",
    DiskUsage: "Utilización del disco",
    Distance: "Distancia",
    DistanceTooltip: "Maxima Actividad Distancia de Vecindario",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "Atributos DOT",
    Down: "Abajo",
    Download: "Descargar",
    Downloads: "Descargas",
    DropZone: "Zona de carga",
    Duration: "Duración",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "Unidad de Trabajo de ECL",
    Edges: "Bordes",
    Edit: "Editar",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar atributos gráficos",
    EditXGMML: "Editar XGMML",
    Empty: "(Vacío)",
    Enable: "Habilitar",
    EnableScopeScans: "Activar Scope Scans",
    EnableScopeScansConfirm: "Esta seguro que desea activar Scope Scans?  Cuando DALI se reinicie, las opciones cambiadas se revierten a las opciones de la configuración.",
    EnglishQ: "Ingles?",
    Error: "Error",
    Errorparsingserverresult: "Error analizando los resultados del servidor",
    Errors: "Errores",
    ErrorsStatus: "Errores/Estado",
    ErrorWarnings: "Error/Advertencia(s)",
    Escape: "Escapar",
    ESPBuildVersion: "Versión de ESP",
    ESPNetworkAddress: "Dirección de red de ESP",
    EventName: "Nombre del Evento",
    EventNamePH: "eventname",
    EventScheduler: "Planificador de eventos",
    EventText: "Texto del Evento",
    EventTextPH: "Texto del evento",
    Exception: "Excepción",
    ExpandAll: "Expandir Todo",
    Export: "Exportar",
    FailIfNoSourceFile: "Falla si no hay archivo de origen",
    FetchingData: "Obteniendo Data...",
    fetchingresults: "obteniendo resultados",
    File: "Archivo",
    FileCluster: "Racimo de archivos",
    FileCounts: "Numero de Archivos",
    FileName: "Nombre de archivo",
    FileParts: "Partes de archivos",
    FilePath: "Camino del archivo",
    FilePermission: "Permisos de Archivos",
    Files: "Archivos",
    FileScopes: "Ámbitos de Archivos",
    FileScopeDefaultPermissions: "Permisos por defecto de alcance de archivos",
    FileSize: "Tamaño de archivo",
    FilesNoPackage: "Archivos sin ",
    FilesWithUnknownSize: "Archivos sin tamaño desconocido.",
    FileType: "Tipo de Archivo",
    FileUploader: "Subidor de archivo",
    FileUploadStillInProgress: "Carga de archivos todavia esta progresando",
    Filter: "Filtro",
    FilterSet: "Filtro definido",
    Find: "Encontrar",
    FindNext: "Encontrar próximo",
    FindPrevious: "Encontrar previo",
    Finished: "Terminado",
    FirstName: "Primer Nombre",
    FirstNRows: "Primeras N Filas",
    Fixed: "Fijo",
    Folder: "Carpeta",
    Format: "Formato",
    Forward: "Adelante",
    Forums: "Foros",
    FromDate: "Desde Fecha",
    FromSizes: "Desde Tamaños",
    FromTime: "Tiempo de Comenzar",
    FullName: "Nombre Entero",
    Graph: "Gráfico",
    Graphs: "Gráficos",
    GraphView: "Vista del gráfico",
    Group: "Grupo",
    GroupBy: "Ordenar Por",
    GroupDetails: "Detalles del Grupo",
    Grouping: "Agrupacion",
    GroupName: "Nombre del grupo",
    GroupPermissions: "Permisos del Grupo",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Esta área muestra el mapa de árbol de el/los gráfico(s) en esta unidad de trabajo. El tamaño y el tinte indican la duración de cada gráfico (más grande y más oscuro indica un porcentaje mayor de tiempo tomado.)",
    Helper: "Ayudador",
    Helpers: "Ayudantes",
    Hex: "exadecimal",
    HideSpills: "Esconder derrames",
    High: "Alto",
    History: "Historia",
    HPCCSystems: "HPCC Systems®",
    Icon: "Icono",
    ID: "ID",
    Inactive: "Inactivo",
    IncludeSlaveLogs: "Incluir slave logs",
    Index: "Indice",
    Info: "información ",
    InfoDialog: "Diálogo informativo",
    InheritedPermissions: "Heredar Permisos",
    Inputs: "Entradas",
    InvalidResponse: "(Respuesta invalida)",
    IP: "IP",
    IPAddress: "Dirección de IP",
    IsLibrary: "Es biblioteca",
    IsReplicated: "Es Replicado",
    IssueReporting: "Informes de errores",
    Jobname: "Nombre del trabajo",
    JobName: "Nombre del trabajo",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Etiqueta",
    LandingZone: "Zona de descarga",
    LandingZones: "Zonas de aterrizaje",
    LanguageFiles: "Archivos de idiomas",
    Largest: "Mas Grande",
    LargestFile: "Archivo mas Grande",
    LargestSize: "Tomaño mas Grande",
    LastName: "Apellido",
    LastNDays: "ULtimos N días",
    LastNHours: "Ultimas N Horas",
    LastNRows: "Ultimas N Filas",
    LDAPWarning: "<b>Error en Servicios de LDAP:</b>  'Demasiados Usuarios' - Por favor aplique un Filtro.",
    LegacyForm: "Forma histórica",
    LibrariesUsed: "Bibliotecas usadas",
    LibraryName: "Nombre de Biblioteca",
    Line: "Línea",
    LineTerminators: "Terminadores de línea",
    Links: "Vínculos",
    Loading: "Cargando...",
    LoadingCachedLayout: "Cargando  Diseño de Memoria...",
    LoadingData: "Cargando data...",
    loadingMessage: "...Cargando...",
    LoadPackageContentHere: "(Cargar aqui el contenido del paquete)",
    LoadPackageFromFile: "Cargar paquete con contenido de archivo",
    Local: "Local",
    Log: "Registro",
    LogFile: "Archivo de registro",
    LoggedInAs: "Conectado como",
    LogicalFile: "Archivo Lógico",
    LogicalFiles: "Archivos lógicos",
    LogicalFilesAndSuperfiles: "Archivo lógico y Superfiles",
    LogicalFilesOnly: "Archivos logicos Solamente",
    LogicalFileType: "Tipo de archivo lógico",
    LogicalName: "Nombre lógico",
    Logs: "Registros",
    log_analysis_1: "log_analysis_1*",
    Low: "Bajo",
    ManagedBy: "Manejado por",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Oprima Crtl_C",
    ManualOverviewSelection: "Seleccion manual sera requirida",
    ManualTreeSelection: "Seleccion manual de arbol sera requirida",
    Mappings: "Mapeados",
    Mask: "Máscara",
    Max: "Máx",
    MaximumNumberOfSlaves: "Numero de esclavo",
    MaxRecordLength: "Máx largo de registros",
    MemberOf: "Miembro de",
    Members: "Miembros",
    Message: "Mensaje",
    Min: "Minimo",
    Missing: "Falta",
    MixedNodeStates: "Estado mixto de nodo",
    Modification: "Modificación",
    Modified: "modificado",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nombre del evento monitor",
    Monitoring: "Monitoreando",
    MonitorShotLimit: "Límite de disparos del monitor",
    MonitorSub: "Sub monitor",
    Month: "Mez",
    More: "Mas",
    MustContainUppercaseAndSymbol: "Debe Contener mayúscula y símbolo",
    NA: "No Applica",
    Name: "Nombre",
    NamePrefix: "Prefijo del nombre",
    NamePrefixPlaceholder: "algun::prefijo",
    Newest: "El Mas Nuevo",
    NewPassword: "Nueva Contraseña",
    NoContent: "(No hay contenido)",
    noDataMessage: "...Zero Filas...",
    Node: "Nodo",
    NodeGroup: "Grupo de Nodos",
    NoErrorFound: "Ningun Error Detectado",
    NoFilterCriteriaSpecified: "No especificó criterio de filtro.",
    None: "Ninguno",
    Normal: "Normal",
    NoScheduledEvents: "Ningun evento programado.",
    NoSplit: "No corte",
    NotActive: "Inacivado",
    NothingSelected: "Nada Seleccionado",
    NotInSuperfiles: "No en las Superfiles",
    NotSuspendedbyUser: "No suspendido por el Usario",
    NoWarningFound: "Ninguna Advertencia Detectada",
    NumberofParts: "Número de partes",
    NumberofSlaves: "Numero de esclavos",
    OK: "Aceptar",
    Oldest: "Mas Antiguo",
    OldPassword: "Contraseña Antigua",
    OmitSeparator: "Omite Separador",
    Only1PackageFileAllowed: "Solo un archivo de paquetes permitido",
    Open: "Abrir",
    OpenInNewPage: "Open In New Page",
    OpenInNewPageNoFrame: "Abrir en nueva pagina (No Marco)",
    OpenLegacyECLWatch: "Abrir ECL Watch viejo",
    OpenLegacyMode: "Abrir (legacia)",
    OpenNativeMode: "Abrir (nativo)",
    OpenSafeMode: "Abrir (modo seguro)",
    OpenSource: "Código Abierto",
    OpenTreeMode: "Abrir (vista en arbol)",
    Operations: "Operaciones",
    Options: "Opciones",
    OriginalFile: "Archivo Original",
    Outputs: "Salidas",
    Overview: "Visión de conjunto",
    Overwrite: "Sobreescribir",
    OverwriteMessage: "Algunos archivos estan presentes. Por favor Seleccione la casilla de verificación para continuar.",
    Owner: "Dueño",
    PackageContent: "Contenidos del Paquete",
    PackageContentNotSet: "Los Contenidos del Paquete no este definido",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Packages without matching queries",
    PackagesNoQuery: "Paqutes sin correspondiente consulta",
    ParameterXML: "Parámetro XML",
    Part: "Parte",
    Parts: "Partes",
    Password: "Contraseña",
    PasswordExpiration: "Expiración de Contraseñas",
    PasswordExpired: "Su contraseña expiro. Por favor cambiela.",
    PasswordExpirePostfix: " dia(s). Desea cambiarla?",
    PasswordExpirePrefix: "Su contraseña expira en",
    PasswordOpenZAP: "Contraseña para abrir ZAP (opcional)",
    PasswordsDoNotMatch: "Las Contraseñas No Coinciden",
    Path: "Camino",
    PathMask: "Máscara del camino",
    Pause: "Pausa",
    PauseNow: "Pausar",
    PctComplete: "% completado",
    PercentDone: "Porcentaje completado",
    PerformingLayout: "Generando disposición...",
    Permission: "Permiso",
    PermissionName: "Nombre del Permiso",
    Permissions: "Permisos",
    PhysicalFiles: "Archivo físico",
    PlaceholderFindText: "Wuid, usuario, mas...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Patio de juegos",
    PleaseEnterANumber: "Por favor escriba un numero 1 -",
    PleaseSelectAUserOrGroup: "Por favor escoja un usario o grupo y nombre de archivo",
    Plugins: "Plugins",
    Port: "Puerto",
    Prefix: "Prefijo",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    PreserveCompression: "Preservar Compression",
    Preview: "Presentación Preliminar",
    PrimaryMonitoring: "Monitoreado Principal",
    Priority: "Prioridad",
    Process: "Proceso",
    ProcessFilter: "Filtro de Procesos",
    ProgressMessage: "Mensaje de progreso",
    Properties: "Propiedades",
    Property: "Propiedad",
    Protect: "Proteger",
    Protected: "Protegido",
    Publish: "Publicar",
    Published: "Publicado",
    PublishedBy: "Publicado por",
    PublishedQueries: "Queries publicados",
    PushEvent: "Evento de Inserción",
    Quarter: "Cuarto",
    Queries: "Consultas",
    QueriesNoPackage: "Consultas sin correspondiente paquete",
    Query: "Consulta",
    QueryDetailsfor: "Detalles de Query por",
    QueryID: "ID de la Consulta",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Nombre de la Consulta",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Grupo de Query",
    Queue: "Cola",
    Quote: "Comilla",
    QuotedTerminator: "Terminador Encomillado",
    RawTextPage: "Texto (Pagina Actual)",
    ReallyWantToRemove: "Confirme que quiere eliminar",
    RecordCount: "Número de registros",
    RecordLength: "Largo de registro",
    Records: "Registros",
    RecordSize: "Tamaño del registro",
    RecordStructurePresent: "Estructura del Registro esta presente",
    Recover: "Recuperar",
    RecoverTooltip: "Reiniciar workunit en pausa / estancado",
    RedBook: "Red Book",
    Refresh: "Actualizar",
    ReleaseNotes: "Notas de la versión",
    Reload: "Recargar",
    Remaining: "Restante",
    RemoteCopy: "Copia Remota",
    RemoteDali: "Dali remoto",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "Remover",
    RemoveSubfiles: "Borrar Sub-Archivo(s)",
    RemoveUser: "Esta apunto de excluirse del grupo:",
    Rename: "Renombrar",
    RenderedSVG: "SVG creado",
    RenderSVG: "Crear SVG",
    Replicate: "Replicar",
    ReplicateOffset: "Replicate Offset",
    RepresentsASubset: "Representar un subconjunto de todas los casamientos. Usando un filtro correcto puede reducir el numero de casamientos",
    RequestSchema: "Esquema del requerimiento",
    RequiredForXML: "Obligatorio para spray data en XML",
    Reschedule: "Re-planear ejecución",
    Reset: "Origen",
    ResetThisQuery: "Reajustar esta Consulat",
    ResetViewToSelection: "Reajustar Vista a la Seleccion",
    Resource: "Recurso",
    Resources: "Recursos",
    ResponseSchema: "Esquema de la respuesta",
    Restart: "Empezar de nuevo",
    Restarted: "Reiniciado",
    Restore: "Restaurar",
    Resubmit: "Reenviar",
    Resubmitted: "Reenviado",
    ResubmitTooltip: "Someter workunit de nuevo ",
    Results: "Resultado(s)",
    Resume: "Continuar",
    RetainSuperfileStructure: "Retener estructura del super-archivo",
    RetypePassword: "Confirme la contraseña",
    Reverse: "Marchar Atrás",
    RowPath: "Ruta de Fila",
    Rows: "Líneas",
    RowTag: "Etiqueta de línea",
    RoxieCluster: "Sistema Roxie",
    Sample: "Ejemplo",
    SampleRequest: "Ejemplo del requerimiento",
    SampleResponse: "Ejemplo de la respuesta",
    Save: "Guardar",
    Scope: "Ámbito",
    SearchResults: "Resultados de búsqueda",
    SecondsRemaining: "Segundos que faltan",
    Security: "Seguridad",
    SelectPackageFile: "Seleccione 'Package File'",
    Separators: "Seperadores",
    SetBanner: "Configurar la bandera",
    SetTextError: "No se pudo visualizar el texto (muy grande?). Use 'helpers' para descargar.",
    SetToFailed: "Marcar como fallado",
    Severity: "Severidad",
    Show: "Mostrar",
    ShowSVG: "Mostrar SVG",
    Size: "Tamaño",
    Skew: "Desbalance",
    SLA: "SLA",
    Slaves: "Esclavos",
    SlaveLogs: "Slave logs",
    SlaveNumber: "Numero de esclavo",
    Smallest: "El Mas Pequeño",
    SmallestFile: "Archivo mas Pequeño",
    SmallestSize: "Tamaño mas Pequeño",
    SOAP: "SOAP",
    SomeDescription: "Alguna*Descripcion",
    somefile: "*::archivo*",
    Source: "Origen",
    SourceCode: "Código fuente",
    SourceLogicalFile: "Nombre logico",
    SourcePath: "Directorio (Se puede usar Asterisco)",
    SourceProcess: "Processo de Origen",
    Spill: "Regar",
    SplitPrefix: "Corte prefijo",
    Spray: "Rociar",
    Start: "Comienzo",
    Started: "Comenzado",
    State: "Estado",
    Stats: "Estatísticas",
    Status: "Estado",
    Stopped: "Detenido",
    Subgraph: "Subgrafo",
    Subgraphs: "Sub-gráficos",
    Submit: "Enviar",
    Subtype: "Subtipo",
    Summary: "Resumen",
    SummaryMessage: "Mensaje resumido",
    Superfile: "Superfile",
    SuperFile: "Super File",
    Superfiles: "Super-Archivos",
    SuperFiles: "Superfiles",
    SuperFilesBelongsTo: "Miembro de Super-Archivo(s)",
    SuperfilesOnly: "Solo Superfiles",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SuspendedByCluster: "Suspendido  por el Clúster",
    SuspendedByUser: "Suspendido por el Usuario",
    SuspendedReason: "Rason porque se suspendio",
    SVGSource: "Origen del SVG",
    Sync: "Sincronizar",
    SyncSelection: "Sincronizar",
    SystemServers: "Servidores de sistema",
    tag: "etiqueta",
    Target: "Destino",
    TargetClusters: "Sistemas de destino",
    TargetName: "Nombre del 'Target'",
    TargetNamePlaceholder: "nombre::dealgunl::archivo::logico",
    TargetRowTagRequired: "Es necesario suministrar el código de fila",
    TargetScope: "Ámbito Objetivo",
    TargetWuid: "Wuid del Objecto",
    Terminators: "Terminadores",
    TestPages: "Páginas de prueba",
    Text: "Texto",
    TheReturnedResults: "Los resultados regresados ",
    ThorMasterAddress: "Direccion del Thor Master",
    ThorNetworkAddress: "Dirección de red de Thor",
    ThorProcess: "Proceso de Thor",
    Time: "Tiempo",
    Timers: "Cronómetros",
    TimeSeconds: "Tiempo (Segundos)",
    TimeStarted: "Tiempo empezado",
    TimeStopped: "Tiempo detenido",
    Timings: "Tiempos",
    TimingsMap: "Mapa de tiempos",
    title_ActivePermissions: "Permisos Vigentes",
    title_ActiveGroupPermissions: "Permisos del Grupo Vigente",
    title_Activity: "Actividad",
    title_AvailableGroupPermissions: "Permisos de Grupo disponibles",
    title_AvailablePermissions: "Permisos Disponibles",
    title_ClusterInfo: "Grupos",
    title_CodeGeneratorPermissions: "Permisos de generador de codigo",
    title_DFUQuery: "Archivos Lógicos",
    title_DFUWUDetails: "Unidad de trabajo DFU",
    title_DiskUsage: "Utilización del disco",
    title_ECLPlayground: "ECL Playground",
    title_EventScheduleWorkunit: "Planificador de Eventos",
    title_FileScopeDefaultPermissions: "Permisos de archive por defecto",
    title_GetDFUWorkunits: "Unidades de trabajo DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Cámbieme",
    title_HPCCPlatformECL: "ECL Watch - Hogar",
    title_HPCCPlatformFiles: "ECL Watch - Archivos",
    title_HPCCPlatformMain: "ECL Watch - Hogar",
    title_HPCCPlatformOps: "ECL Watch - Operaciones",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
    title_Inputs: "Entradas",
    title_LFDetails: "Detalles de archivos lógicos",
    title_LibrariesUsed: "Librerias Usadas",
    title_Log: "Archivo de Registro",
    title_LZBrowse: "Zonas de descarga",
    title_MemberOf: "Miembros de",
    title_Members: "Miembros",
    title_Permissions: "Permisos",
    title_QuerySetDetails: "Detalles de Query",
    title_QuerySetErrors: "Errores",
    title_QuerySetLogicalFiles: "Archivos lógicos",
    title_QuerySetQuery: "Consultas",
    title_QuerySetSuperFiles: "Super archivos",
    title_QueryTest: "Super Archivos",
    title_Result: "Actividad",
    title_Results: "Salidas",
    title_SearchResults: "Resultados de búsqueda ",
    title_SourceFiles: "Archivo de origen",
    title_Topology: "Topología",
    title_TpThorStatus: "Estatus de Thor",
    title_UserPermissions: "Permisos del Usuario",
    title_UserQuery: "Permisos",
    title_WorkunitScopeDefaultPermissions: "Permisos de workunits por defecto",
    title_WUDetails: "Detalles de las unidades de trabajo ECL",
    title_WUQuery: "Unidades de trabajo ECL",
    To: "A:",
    ToDate: "Hasta fecha",
    Toenablegraphviews: "Para habilitar vista de gráficos, instale el plugin Graph View Control",
    TooManyFiles: "Demasiados archivos",
    Tooltip: "Tooltip",
    Top: "Arriva",
    Topology: "Topología",
    ToSizes: "A tamaño",
    TotalClusterTime: "Tiempo Total del Cluster",
    TotalSize: "Tamaño Total",
    TotalThorTime: "Tiempo total de Thor",
    TransitionGuide: "Guía de transición",
    Tree: "Arbol",
    Type: "Tipo",
    undefined: "no definido",
    Unknown: "Desconocido",
    Unprotect: "Desproteger",
    UnsupportedIE9FF: "No se ofrece soporte (IE <= 9, FireFox)",
    Unsuspend: "De-suspender",
    Unsuspended: "Des-suspendido",
    Up: "Arriba",
    UpdateSuperFiles: "Actualizar superfile",
    Upload: "Subir",
    Usage: "Utilización",
    Used: "Usado",
    User: "Usuario",
    UserDetails: "Detalles del Usuario",
    UserID: "ID del Usuarion",
    Username: "NombreDeUsario",
    UserName: "Nombre de Usario",
    UserPermissions: "Permisos del Usuario",
    Users: "Usuarios",
    UseSingleConnection: "Use una sola conexión",
    Validate: "Validar",
    ValidateActivePackageMap: "Validar Package Map Activo",
    ValidatePackageContent: "Validar Contenido de Paquete",
    ValidatePackageMap: "Validar el Package Map",
    ValidateResult: "=====Velida el Resultado=====\n\n",
    ValidateResultHere: "(resultado de la validación)",
    Value: "Valor",
    Variable: "Variable",
    VariableBigendian: "Variable 'Big-endian'",
    Variables: "Variables",
    VariableSourceType: "Formato",
    Version: "Versión",
    ViewByScope: "'Ver Por Ámbito'",
    Views: "Vistas",
    Visualize: "Visualizar",
    Warnings: "Advertencias",
    WarnOldGraphControl: "Advertencia: Controlador de Graphicas antiguo",
    What: "Que",
    Where: "Donde",
    Who: "Quien",
    Width: "Ancho",
    Workflows: "Flujos de Trabajo",
    Workunit: "Unidad de trabajo",
    Workunits: "Unidades de trabajo",
    WorkUnitScopeDefaultPermissions: "Permisos por defect de alcaces de Workunit",
    Wrap: "Envolver",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid no puede estar vacío.",
    WUSnapShot: "Captura de Unidad de trabajo",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "Referencias cruzadas",
    Year: "Año",
    YourBrowserMayNotSupport: "Es posible que su navegador no soporta archivos de este tamaño",
    ZAP: "Z.A.P.",
    ZeroLogicalFilesCheckFilter: "Archivos logicos a cero (chequee filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Paquete de análisis en formato Zip",
    Zoom: "Zoom",
    Zoom100Pct: "Aumentar a 100%",
    ZoomAll: "Aumentar todo",
    ZoomWidth: "Aumentar al ancho"
})
);
