define(
({
    Abort: "Aborte",
    AbortedBy: "Abortado por",
    AbortedTime: "Abortado a las",
    About: "Acerca",
    AboutGraphControl: "Acerca del controlador gráfico",
    AboutHPCCSystemsGraphControl: "Acerca del controlador gráfico de HPCC Systems®",
    Account: "Cuenta",
    Action: "Acción",
    Activate: "Activar",
    Activated: "Activado",
    Active: "Activo",
    ActivePackageMap: "&lsquo;Package Map&rsquo; Activo",
    ActiveWorkunit: "Unidad activa",
    Activities: "Actividades",
    Activity: "Actividad",
    ActivityMap: "Mapa de Actividades",
    ActualSize: "Tamaño real",
    Add: "Agregar",
    AddAttributes2: "Agregar atributos",
    AddAttributes: "Agregar atributos/valores a su método",
    AddBinding: "Agregar conexión",
    AddFile: "Añadir Archivo",
    AddGroup: "Agregar Grupo",
    AdditionalResources: "Recursos  Adicionales",
    AddProcessMap: "Agregar &lsquo;Package Map&rsquo;",
    AddtionalProcessesToFilter: "Procesos adicionales a filtrar",
    AddToExistingSuperfile: "Agregar a un superarchivo existente",
    AddToSuperfile: "Agregar al Super-archivo",
    AddUser: "Aggregar Usuario",
    Advanced: "Advanzado",
    All: "Todos",
    AllowAccess: "<center>Permitir<br>Acceso</center>",
    AllowForeignFiles: "Permitir Archivo sExtranjeros",
    AllowFull: "<center>Permitir<br>Completo</center>",
    AllowRead: "<center>Permitir<br>Leer</center>",
    AllowWrite: "<center>Permitir<br>Escribir</center>",
    AllQueuedItemsCleared: "Todos los items encolados han sido eliminados. El trabajo en ejecución continuará corriendo",
    ANY: "CUALQUIER",
    AnyAdditionalProcessesToFilter: "Procesos adicionales a filtrar",
    Append: "Agregar",
    Apply: "Aplicar",
    ArchivedOnly: "Solo archivado",
    ArchivedWarning: "Advertencia: Por favor especifique rango de fechas corto. O si no, la recuperacion de workunits puede ser demorada.",
    Attribute: "Atributo",
    AttributesAreRequired: "Atributos son necesarios",
    AutoRefresh: "Actualizar Automaticamente",
    AutoRefreshEvery: "Auto-refrescar cada x minutos",
    AutoRefreshIncrement: "Incrementar auto-refresco",
    Back: "Atras",
    BannerColor: "Color de Banner",
    BannerMessage: "Mensaje del Banner",
    BannerScroll: "Desplazamiento del Banner",
    BannerSize: "Tamaño del Banner",
    BinaryInstalls: "Binarios instalables",
    Binding: "Conexión",
    BindingDeleted: "Conexión eliminada",
    Blob: "BLOB",
    BlobPrefix: "Prefijo de BLOB",
    Bottom: "Abajo",
    Busy: "Ocupado",
    Cancel: "Cancelar",
    CancelAll: "Cancelar todo",
    CancelAllMessage: "Abortar trabajos en ejecución y limpiar la cola. Desearía continuar?",
    CheckAllNodes: "Escoger todos los Nodos",
    CheckFilePermissions: "Escoger permisos de Archivo",
    CheckSingleNode: "Escoja un Archivo",
    Clear: "Despejar",
    ClearPermissionsCache: "Despejar Los Permisos Del Cache",
    ClearPermissionsCacheConfirm: "Esta seguro que desea despejar los permisos del Cache de DALI y ESP? Workunits en executo pueden demorarse asta que los Caches se actualicen",
    Clone: "Clonar",
    ClonedWUID: "WUID Clonado",
    CloneTooltip: "Duplicar Workunit",
    Close: "Cerrar",
    Cluster: "Sistema",
    ClusterName: "Nombre del sistema",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesos de sistema",
    Code: "Código",
    CodeGenerator: "Generador de Código",
    Col: "Columna",
    CollapseAll: "Colapsar Todo",
    Command: "Comando",
    Comment: "Comentario",
    Completed: "Completado",
    ComplexityWarning: "Mas de {threshold} actividades ({activityCount}) - ¿suprimir primer visualización?",
    Component: "Componente",
    Compress: "Comprimir",
    Compressed: "Comprimido",
    CompressedFileSize: "Tamaño de Archivo Comprimido",
    Condition: "Condición",
    Configuration: "Configuracion",
    ConfirmPassword: "Confirme la Contraseña",
    ConfirmRemoval: "¿Seguro que quieres hacer esto?",
    ContactAdmin: "Si quiere renombrar este grupo, por favor contacte su administrador de LDAP",
    Content: "Contenido",
    Contents: "Contenidos",
    ContentType: "Tipo de Contenido",
    Copy: "Copia",
    Count: "Número",
    CreateANewFile: "Crear un nuevo superarchivo",
    Created: "Creado",
    Critical: "Crítico",
    CSV: "CSV",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Fecha",
    Day: "Dia",
    Deactivate: "Deactivar",
    Debug: "Depurar",
    DEF: "DEF",
    Defaults: "Valores por defecto",
    Definition: "Definición",
    Delete: "Eliminar",
    DeleteBinding: "Eliminar conexión",
    Deleted: "Borrado",
    DeletedBinding: "Conexión eliminada",
    DeleteDirectories: "Eliminar directorios vaciós. Quiere continuar?",
    DeleteEmptyDirectories: "Eliminar directorios vaciós?",
    DeleteSelectedFiles: "¿Borrar archivos seleccionados?",
    DeleteSelectedGroups: "Eliminar  grupo(s) escojido(s)?",
    DeleteSelectedPermissions: "Borrar permiso(s) escojido(s)?",
    DeleteSelectedQueries: "¿Borrar queries seleccionados?",
    DeleteSelectedUsers: "Eliminar Usuario(s) escojido(s)?",
    DeleteSelectedWorkunits: "¿Borrar unidades de trabajo seleccionadas?",
    DeleteSuperfile2: "¿Borrar Super-Archivo?",
    DeleteSuperfile: "¿Borrar super-archivo?",
    DeleteThisPackage: "Eliminar este paquete?",
    Delimited: "Delimitado",
    DenyAccess: "<center>Negar<br>Access</center>",
    DenyFull: "<center>Negar<br>Completo</center>",
    DenyRead: "<center>Negar<br>Leer</center>",
    DenyWrite: "<center>Negar<br>Escribir</center>",
    Depth: "Profundidad",
    DepthTooltip: "Máxima Profundidad de Subgrafo",
    Deschedule: "Eliminar del plan de ejecución",
    DescheduleSelectedWorkunits: "Desprogramar Workunit(s) escojida(s)?",
    Description: "Descripción",
    DESDL: "ESDL dinámico",
    Despray: "Despray",
    Details: "Detalles",
    DFUServerName: "Nombre del servidor de DFU",
    DFUWorkunit: "Unidad de Trabajo de DFU",
    Directories: "Directorios",
    Directory: "Directorio",
    DisableScopeScanConfirm: "Esta seguro que desea inhabilitar Scope Scans? Cuando DALI se reinicie, las opciones cambiadas se revierten a las opciones de la configuración.",
    DisableScopeScans: "Inhabilitar Scope Scans",
    DiskUsage: "Utilización del disco",
    Distance: "Distancia",
    DistanceTooltip: "Maxima Actividad Distancia de Vecindario",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "Atributos DOT",
    Down: "Abajo",
    Download: "Descargar",
    Downloads: "Descargas",
    DownloadToCSV: "Bajar en formato CSV",
    DropZone: "Zona de carga",
    Duration: "Duración",
    DynamicNoServicesFound: "No se han encontrado servicios",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "Unidad de Trabajo de ECL",
    Edges: "Bordes",
    Edit: "Editar",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar atributos gráficos",
    EditXGMML: "Editar XGMML",
    EmployeeID: "Identificador del empleado",
    Empty: "(Vacío)",
    Enable: "Habilitar",
    EnableScopeScans: "Activar Scope Scans",
    EnableScopeScansConfirm: "Esta seguro que desea activar Scope Scans?  Cuando DALI se reinicie, las opciones cambiadas se revierten a las opciones de la configuración.",
    EnglishQ: "Ingles?",
    EnterAPercentage: "Entre un porcentaje",
    EnterAPercentageOrMB: "Entre un porcentaje o MB",
    Error: "Error",
    Errorparsingserverresult: "Error analizando los resultados del servidor",
    Errors: "Errores",
    ErrorsStatus: "Errores/Estado",
    ErrorUploadingFile: "Error subiendo archivo(s). Verifique los permisos",
    ErrorWarnings: "Error/Advertencia(s)",
    Escape: "Escapar",
    ESPBuildVersion: "Versión de ESP",
    ESPNetworkAddress: "Dirección de red de ESP",
    EventName: "Nombre del Evento",
    EventNamePH: "eventname",
    EventScheduler: "Planificador de eventos",
    EventText: "Texto del Evento",
    EventTextPH: "Texto del evento",
    Exception: "Excepción",
    ExpandAll: "Expandir Todo",
    Export: "Exportar",
    ExportSelectionsToList: "Exportar selecciones a lista",
    FailIfNoSourceFile: "Falla si no hay archivo de origen",
    Fatal: "Fatal",
    Fetched: "Obtenido",
    FetchingData: "Obteniendo Data...",
    fetchingresults: "obteniendo resultados",
    File: "Archivo",
    FileCluster: "Racimo de archivos",
    FileCounts: "Numero de Archivos",
    FileName: "Nombre de archivo",
    FileParts: "Partes de archivos",
    FilePath: "Camino del archivo",
    FilePermission: "Permisos de Archivos",
    Files: "Archivos",
    FilesPending: "Archivos pendientes",
    FileScopeDefaultPermissions: "Permisos por defecto de alcance de archivos",
    FileScopes: "Ámbitos de Archivos",
    FileSize: "Tamaño de archivo",
    FilesNoPackage: "Archivos sin ",
    FilesWithUnknownSize: "Archivos sin tamaño desconocido.",
    FileType: "Tipo de Archivo",
    FileUploader: "Subidor de archivo",
    FileUploadStillInProgress: "Carga de archivos todavia esta progresando",
    Filter: "Filtro",
    FilterSet: "Filtro definido",
    Find: "Encontrar",
    FindNext: "Encontrar próximo",
    FindPrevious: "Encontrar previo",
    Finished: "Terminado",
    FirstName: "Primer Nombre",
    FirstNRows: "Primeras N Filas",
    Fixed: "Fijo",
    Folder: "Carpeta",
    Format: "Formato",
    Forums: "Foros",
    Forward: "Adelante",
    FoundFile: "Archivo encontrado",
    FoundFileMessage: "Todas las partes en disco del archivo encontrado no estan referenciadas en el servidor Dali. Todas las partes se han encontrado asi que pueden ser agregadas de nuevo al Servidor Dali. Las partes tambien pueden ser removidas del cluster, si es necesario.",
    FromDate: "Desde Fecha",
    FromSizes: "Desde Tamaños",
    FromTime: "Tiempo de Comenzar",
    FullName: "Nombre Entero",
    Generate: "Generar",
    GetSoftwareInformation: "Obtener informacion del software",
    Graph: "Gráfico",
    Graphs: "Gráficos",
    GraphView: "Vista del gráfico",
    Group: "Grupo",
    GroupBy: "Ordenar Por",
    GroupDetails: "Detalles del Grupo",
    Grouping: "Agrupacion",
    GroupName: "Nombre del grupo",
    GroupPermissions: "Permisos del Grupo",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Esta área muestra el mapa de árbol de el/los gráfico(s) en esta unidad de trabajo. El tamaño y el tinte indican la duración de cada gráfico (más grande y más oscuro indica un porcentaje mayor de tiempo tomado.)",
    Helper: "Ayudador",
    Helpers: "Ayudantes",
    Hex: "exadecimal",
    HideSpills: "Esconder derrames",
    High: "Alto",
    History: "Historia",
    HPCCSystems: "HPCC Systems®",
    Icon: "Icono",
    ID: "ID",
    Inactive: "Inactivo",
    IncludeSlaveLogs: "Incluir slave logs",
    Index: "Indice",
    Info: "información ",
    InfoDialog: "Diálogo informativo",
    InheritedPermissions: "Heredar Permisos",
    Inputs: "Entradas",
    InvalidResponse: "(Respuesta invalida)",
    IP: "IP",
    IPAddress: "Dirección de IP",
    IsCompressed: "Está comprimido",
    IsLibrary: "Es biblioteca",
    IsReplicated: "Es Replicado",
    IssueReporting: "Informes de errores",
    JobName: "Nombre del trabajo",
    Jobname: "Nombre del trabajo",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    KeyFile: "Archivo llave",
    Label: "Etiqueta",
    LandingZone: "Zona de descarga",
    LandingZones: "Zonas de aterrizaje",
    LanguageFiles: "Archivos de idiomas",
    Largest: "Mas Grande",
    LargestFile: "Archivo mas Grande",
    LargestSize: "Tomaño mas Grande",
    LastMessage: "Ultimo mensaje",
    LastName: "Apellido",
    LastNDays: "ULtimos N días",
    LastNHours: "Ultimas N Horas",
    LastNRows: "Ultimas N Filas",
    LastRun: "Ultima ejecución",
    LDAPWarning: "<b>Error en Servicios de LDAP:</b>  &lsquo;Demasiados Usuarios&rsquo; - Por favor aplique un Filtro.",
    LegacyForm: "Forma histórica",
    LibrariesUsed: "Bibliotecas usadas",
    LibraryName: "Nombre de Biblioteca",
    Line: "Línea",
    LineTerminators: "Terminadores de línea",
    Links: "Vínculos",
    Loading: "Cargando...",
    LoadingCachedLayout: "Cargando  Diseño de Memoria...",
    LoadingData: "Cargando data...",
    loadingMessage: "...Cargando...",
    LoadPackageContentHere: "(Cargar aqui el contenido del paquete)",
    LoadPackageFromFile: "Cargar paquete con contenido de archivo",
    Local: "Local",
    LocalFileSystemsOnly: "Sistema de archivos locales solamente",
    Location: "Ubicación",
    Log: "Registro",
    LogFile: "Archivo de registro",
    LoggedInAs: "Conectado como",
    LogicalFile: "Archivo Lógico",
    LogicalFiles: "Archivos lógicos",
    LogicalFilesAndSuperfiles: "Archivo lógico y Superfiles",
    LogicalFilesOnly: "Archivos logicos Solamente",
    LogicalFileType: "Tipo de archivo lógico",
    LogicalName: "Nombre lógico",
    Logs: "Registros",
    log_analysis_1: "log_analysis_1*",
    LostFile2: "Archivos perdidos",
    LostFile: "Archivo perdido",
    LostFileMessage: "Un archivo lógico ha perdido al menos una de sus partes en ambas ubicaciones, primary y replicada. El archivo lógico aún está referenciado en el servidor Dali. Eliminando este archivo se remueven la referencia en el servidor Dali y todas las partes existentes en disco.",
    Low: "Bajo",
    MachineInformation: "Información de las máquinas",
    Machines: "Máquinas",
    Major: "Mayor",
    ManagedBy: "Manejado por",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Oprima Crtl_C",
    ManualOverviewSelection: "Seleccion manual sera requirida",
    ManualTreeSelection: "Seleccion manual de arbol sera requirida",
    Mappings: "Mapeados",
    Mask: "Máscara",
    Max: "Máx",
    MaximumNumberOfSlaves: "Numero de esclavo",
    MaxNode: "Nodo máximo",
    MaxRecordLength: "Máx largo de registros",
    MaxSize: "Tamaňo máximo",
    MemberOf: "Miembro de",
    Members: "Miembros",
    Message: "Mensaje",
    Methods: "Métodos",
    Min: "Minimo",
    MinNode: "Nodo mínimo",
    Minor: "Menor",
    MinSize: "Tamaňo mínimo",
    Missing: "Falta",
    MixedNodeStates: "Estado mixto de nodo",
    Modification: "Modificación",
    Modified: "modificado",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nombre del evento monitor",
    Monitoring: "Monitoreando",
    MonitorShotLimit: "Límite de disparos del monitor",
    MonitorSub: "Sub monitor",
    Month: "Mez",
    More: "Mas",
    MustContainUppercaseAndSymbol: "Debe Contener mayúscula y símbolo",
    NA: "No Applica",
    Name: "Nombre",
    NamePrefix: "Prefijo del nombre",
    NamePrefixPlaceholder: "algun::prefijo",
    Newest: "El Mas Nuevo",
    NewPassword: "Nueva Contraseña",
    NoContent: "(No hay contenido)",
    noDataMessage: "...Zero Filas...",
    Node: "Nodo",
    NodeGroup: "Grupo de Nodos",
    NoErrorFound: "Ningun Error Detectado",
    NoFilterCriteriaSpecified: "No especificó criterio de filtro.",
    None: "Ninguno",
    NoPublishedSize: "Tamaňo no publicado",
    Normal: "Normal",
    NoScheduledEvents: "Ningun evento programado.",
    NoSplit: "No corte",
    NotActive: "Inacivado",
    NothingSelected: "Nada Seleccionado",
    NotInSuperfiles: "No en las Superfiles",
    NotSuspendedbyUser: "No suspendido por el Usario",
    NoWarningFound: "Ninguna Advertencia Detectada",
    NumberofParts: "Número de partes",
    NumberofSlaves: "Numero de esclavos",
    OK: "Aceptar",
    Oldest: "Mas Antiguo",
    OldPassword: "Contraseña Antigua",
    OmitSeparator: "Omite Separador",
    Only1PackageFileAllowed: "Solo un archivo de paquetes permitido",
    Open: "Abrir",
    OpenInNewPage: "Open In New Page",
    OpenInNewPageNoFrame: "Abrir en nueva pagina (No Marco)",
    OpenLegacyECLWatch: "Abrir ECL Watch viejo",
    OpenLegacyMode: "Abrir (legacia)",
    OpenNativeMode: "Abrir (nativo)",
    OpenSafeMode: "Abrir (modo seguro)",
    OpenSource: "Código Abierto",
    OpenTreeMode: "Abrir (vista en arbol)",
    Operations: "Operaciones",
    Options: "Opciones",
    OriginalFile: "Archivo Original",
    OrphanFile2: "Archivo huérfano",
    OrphanFile: "Archivos huérfanos",
    OrphanMessage: "Un archivo huérfano tiene solo algunas de sus partes en disco. Sin embargo, el conjunto completo de partes no esta disponible para construir un archivo logico completo. No hay referencias a estas partes de archivo en el servidor Dali.",
    Outputs: "Salidas",
    Overview: "Visión de conjunto",
    Overwrite: "Sobreescribir",
    OverwriteMessage: "Algunos archivos estan presentes. Por favor Seleccione la casilla de verificación para continuar.",
    Owner: "Dueño",
    PackageContent: "Contenidos del Paquete",
    PackageContentNotSet: "Los Contenidos del Paquete no este definido",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Paqutes sin correspondiente consulta",
    ParameterXML: "Parámetro XML",
    Part: "Parte",
    PartMask: "Máscara de parte",
    Parts: "Partes",
    PartsFound: "Partes encontradas",
    PartsLost: "Partes perdidas",
    Password: "Contraseña",
    PasswordExpiration: "Expiración de Contraseñas",
    PasswordExpired: "Su contraseña expiro. Por favor cambiela.",
    PasswordExpirePostfix: " dia(s). Desea cambiarla?",
    PasswordExpirePrefix: "Su contraseña expira en",
    PasswordOpenZAP: "Contraseña para abrir ZAP (opcional)",
    PasswordsDoNotMatch: "Las Contraseñas No Coinciden",
    Path: "Camino",
    PathMask: "Máscara del camino",
    Pause: "Pausa",
    PauseNow: "Pausar",
    PctComplete: "% completado",
    PercentDone: "Porcentaje completado",
    PerformingLayout: "Generando disposición...",
    Permission: "Permiso",
    PermissionName: "Nombre del Permiso",
    Permissions: "Permisos",
    PhysicalFiles: "Archivo físico",
    PlaceholderFindText: "Wuid, usuario, mas...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Patio de juegos",
    PleaseEnterANumber: "Por favor escriba un numero 1 -",
    PleasePickADefinition: "Por favor seleccione una definición",
    PleaseSelectADynamicESDLService: "Por favor seleccione un servicio de ESDL dinámico",
    PleaseSelectAGroupToAddUser: "Por favor escoja un grupo al cual agregar el usario",
    PleaseSelectATopologyItem: "Por favor seleccione un destino, servicio o máquina",
    PleaseSelectAUserOrGroup: "Por favor escoja un usario o grupo y nombre de archivo",
    PleaseSelectAUserToAdd: "Por favor escoja el usario para agregar",
    Plugins: "Plugins",
    Port: "Puerto",
    Prefix: "Prefijo",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preflight: "Pre-volado",
    PreserveCompression: "Preservar Compression",
    Preview: "Presentación Preliminar",
    PrimaryLost: "Primario perdido",
    PrimaryMonitoring: "Monitoreado Principal",
    Priority: "Prioridad",
    Process: "Proceso",
    ProcessFilter: "Filtro de Procesos",
    ProcessorInformation: "Información del procesador",
    ProgressMessage: "Mensaje de progreso",
    Properties: "Propiedades",
    Property: "Propiedad",
    Protect: "Proteger",
    Protected: "Protegido",
    Publish: "Publicar",
    Published: "Publicado",
    PublishedBy: "Publicado por",
    PublishedQueries: "Queries publicados",
    PushEvent: "Evento de Inserción",
    Quarter: "Cuarto",
    Queries: "Consultas",
    QueriesNoPackage: "Consultas sin correspondiente paquete",
    Query: "Consulta",
    QueryDetailsfor: "Detalles de Query por",
    QueryID: "ID de la Consulta",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Nombre de la Consulta",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Grupo de Query",
    Queue: "Cola",
    Quote: "Comilla",
    QuotedTerminator: "Terminador Encomillado",
    RawTextPage: "Texto (Pagina Actual)",
    Ready: "Listo",
    ReallyWantToRemove: "Confirme que quiere eliminar",
    RecordCount: "Número de registros",
    RecordLength: "Largo de registro",
    Records: "Registros",
    RecordSize: "Tamaño del registro",
    RecordStructurePresent: "Estructura del Registro esta presente",
    Recover: "Recuperar",
    RecoverTooltip: "Reiniciar workunit en pausa / estancado",
    Recycling: "Reciclando",
    RedBook: "Red Book",
    Refresh: "Actualizar",
    ReleaseNotes: "Notas de la versión",
    Reload: "Recargar",
    Remaining: "Restante",
    RemoteCopy: "Copia Remota",
    RemoteDali: "Dali remoto",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "Remover",
    RemoveAttributeQ: "Está por eliminar este atributo. Está seguro de que desea continuar?",
    RemoveAtttributes: "Eliminar atributo(s)",
    RemoveSubfiles2: "Remover subarchivo(s)",
    RemoveSubfiles: "Borrar Sub-Archivo(s)",
    RemoveUser: "Esta apunto de excluirse del grupo:",
    Rename: "Renombrar",
    RenderedSVG: "SVG creado",
    RenderSVG: "Crear SVG",
    Replicate: "Replicar",
    ReplicatedLost: "Réplica perdida",
    ReplicateOffset: "Replicate Offset",
    RepresentsASubset: "Representar un subconjunto de todas los casamientos. Usando un filtro correcto puede reducir el numero de casamientos",
    RequestSchema: "Esquema del requerimiento",
    RequiredForXML: "Obligatorio para spray data en XML",
    Reschedule: "Re-planear ejecución",
    Reset: "Origen",
    ResetThisQuery: "Reajustar esta Consulat",
    ResetViewToSelection: "Reajustar Vista a la Seleccion",
    Resource: "Recurso",
    Resources: "Recursos",
    ResponseSchema: "Esquema de la respuesta",
    Restart: "Empezar de nuevo",
    Restarted: "Reiniciado",
    Restore: "Restaurar",
    Resubmit: "Reenviar",
    Resubmitted: "Reenviado",
    ResubmitTooltip: "Someter workunit de nuevo ",
    Results: "Resultado(s)",
    Resume: "Continuar",
    RetainSuperfileStructure: "Retener estructura del super-archivo",
    RetypePassword: "Confirme la contraseña",
    Reverse: "Marchar Atrás",
    RoxieFileCopy: "Estado de copia de archivos de Roxie",
    RowPath: "Ruta de Fila",
    Rows: "Líneas",
    RowTag: "Etiqueta de línea",
    RoxieCluster: "Sistema Roxie",
    RunningServerStrain: "La ejecución de este proceso puede tomar un tiempo largo y pondrá una carga significativa en los servidores. Desea continuar?",
    Sample: "Ejemplo",
    SampleRequest: "Ejemplo del requerimiento",
    SampleResponse: "Ejemplo de la respuesta",
    Save: "Guardar",
    Scope: "Ámbito",
    SearchResults: "Resultados de búsqueda",
    SecondsRemaining: "Segundos que faltan",
    Security: "Seguridad",
    SelectPackageFile: "Seleccione &lsquo;Package File&rsquo;",
    Separators: "Seperadores",
    Services: "Servicios",
    SetBanner: "Configurar la bandera",
    SetTextError: "No se pudo visualizar el texto (muy grande?). Use &lsquo;helpers&rsquo; para descargar.",
    SetToFailed: "Marcar como fallado",
    Severity: "Severidad",
    Show: "Mostrar",
    ShowProcessesUsingFilter: "Mostrar procesos usando filtro",
    ShowSVG: "Mostrar SVG",
    Size: "Tamaño",
    Skew: "Desbalance",
    SkewNegative: "Desbalanceado(-)",
    SkewPositive: "Desbalanceado(+)",
    SLA: "SLA",
    SlaveLogs: "Slave logs",
    SlaveNumber: "Numero de esclavo",
    Slaves: "Esclavos",
    Smallest: "El Mas Pequeño",
    SmallestFile: "Archivo mas Pequeño",
    SmallestSize: "Tamaño mas Pequeño",
    SOAP: "SOAP",
    SomeDescription: "Alguna*Descripcion",
    somefile: "*::archivo*",
    Source: "Origen",
    SourceCode: "Código fuente",
    SourceLogicalFile: "Nombre logico",
    SourcePath: "Directorio (Se puede usar Asterisco)",
    SourceProcess: "Processo de Origen",
    Spill: "Regar",
    SplitPrefix: "Corte prefijo",
    Spray: "Rociar",
    Start: "Comienzo",
    Started: "Comenzado",
    Starting: "Comenzando",
    State: "Estado",
    Stats: "Estatísticas",
    Status: "Estado",
    Stopped: "Detenido",
    Stopping: "Deteniendo",
    StorageInformation: "Información del almacenamiento",
    Subgraph: "Subgrafo",
    Subgraphs: "Sub-gráficos",
    Submit: "Enviar",
    Subtype: "Subtipo",
    Summary: "Resumen",
    SummaryMessage: "Mensaje resumido",
    SuperFile: "Super File",
    Superfile: "Superfile",
    Superfiles: "Super-Archivos",
    SuperFiles: "Superfiles",
    SuperFilesBelongsTo: "Miembro de Super-Archivo(s)",
    SuperfilesOnly: "Solo Superfiles",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SuspendedByCluster: "Suspendido  por el Clúster",
    SuspendedByUser: "Suspendido por el Usuario",
    SuspendedReason: "Rason porque se suspendio",
    SVGSource: "Origen del SVG",
    Sync: "Sincronizar",
    SyncSelection: "Sincronizar",
    SystemServers: "Servidores de sistema",
    tag: "etiqueta",
    Target: "Destino",
    TargetClusters: "Sistemas de destino",
    TargetName: "Nombre del &lsquo;Target&rsquo;",
    TargetNamePlaceholder: "nombre::dealgunl::archivo::logico",
    TargetRowTagRequired: "Es necesario suministrar el código de fila",
    Targets: "Destinos",
    TargetScope: "Ámbito Objetivo",
    TargetWuid: "Wuid del Objecto",
    Terminators: "Terminadores",
    TestPages: "Páginas de prueba",
    Text: "Texto",
    TheReturnedResults: "Los resultados regresados ",
    ThorMasterAddress: "Direccion del Thor Master",
    ThorNetworkAddress: "Dirección de red de Thor",
    ThorProcess: "Proceso de Thor",
    Time: "Tiempo",
    Timers: "Cronómetros",
    TimeSeconds: "Tiempo (Segundos)",
    TimeStarted: "Tiempo empezado",
    TimeStopped: "Tiempo detenido",
    Timings: "Tiempos",
    TimingsMap: "Mapa de tiempos",
    title_ActiveGroupPermissions: "Permisos del Grupo Vigente",
    title_ActivePermissions: "Permisos Vigentes",
    title_Activity: "Actividad",
    title_AvailableGroupPermissions: "Permisos de Grupo disponibles",
    title_AvailablePermissions: "Permisos Disponibles",
    title_ClusterInfo: "Grupos",
    title_CodeGeneratorPermissions: "Permisos de generador de codigo",
    title_DESDL: "ESDL dinámico",
    title_DFUQuery: "Archivos Lógicos",
    title_DFUWUDetails: "Unidad de trabajo DFU",
    title_DirectoriesFor: "Directorios para",
    title_DiskUsage: "Utilización del disco",
    title_ECLPlayground: "ECL Playground",
    title_ErrorsWarnings: "Errores/Advertencias de",
    title_EventScheduleWorkunit: "Planificador de Eventos",
    title_FilesPendingCopy: "Archivos pendientes para copiar",
    title_FileScopeDefaultPermissions: "Permisos de archive por defecto",
    title_FoundFilesFor: "Archivos encontrados para",
    title_GetDFUWorkunits: "Unidades de trabajo DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Cámbieme",
    title_HPCCPlatformECL: "ECL Watch - Hogar",
    title_HPCCPlatformFiles: "ECL Watch - Archivos",
    title_HPCCPlatformMain: "ECL Watch - Hogar",
    title_HPCCPlatformOps: "ECL Watch - Operaciones",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
    title_Inputs: "Entradas",
    title_LFDetails: "Detalles de archivos lógicos",
    title_LibrariesUsed: "Librerias Usadas",
    title_Log: "Archivo de Registro",
    title_LostFilesFor: "Archivos perdidos para",
    title_LZBrowse: "Zonas de descarga",
    title_MemberOf: "Miembros de",
    title_Members: "Miembros",
    title_OrphanFilesFor: "Archivos huérfanos para",
    title_Permissions: "Permisos",
    title_PreflightResults: "Resultados de pre-volado",
    title_QuerySetDetails: "Detalles de Query",
    title_QuerySetErrors: "Errores",
    title_QuerySetLogicalFiles: "Archivos lógicos",
    title_QuerySetQuery: "Consultas",
    title_QuerySetSuperFiles: "Super archivos",
    title_QueryTest: "Super Archivos",
    title_Result: "Actividad",
    title_Results: "Salidas",
    title_SearchResults: "Resultados de búsqueda ",
    title_SourceFiles: "Archivo de origen",
    title_Topology: "Topología",
    title_TpThorStatus: "Estatus de Thor",
    title_UserPermissions: "Permisos del Usuario",
    title_UserQuery: "Permisos",
    title_WorkunitScopeDefaultPermissions: "Permisos de workunits por defecto",
    title_WUDetails: "Detalles de las unidades de trabajo ECL",
    title_WUQuery: "Unidades de trabajo ECL",
    To: "A:",
    ToDate: "Hasta fecha",
    Toenablegraphviews: "Para habilitar vista de gráficos, instale el plugin Graph View Control",
    Tooltip: "Tooltip",
    TooManyFiles: "Demasiados archivos",
    Top: "Arriva",
    Topology: "Topología",
    ToSizes: "A tamaño",
    TotalClusterTime: "Tiempo Total del Cluster",
    TotalParts: "Total de partes",
    TotalSize: "Tamaño Total",
    TotalThorTime: "Tiempo total de Thor",
    TransitionGuide: "Guía de transición",
    Tree: "Arbol",
    Type: "Tipo",
    undefined: "no definido",
    Unknown: "Desconocido",
    Unprotect: "Desproteger",
    UnsupportedIE9FF: "No se ofrece soporte (IE <= 9, FireFox)",
    Unsuspend: "De-suspender",
    Unsuspended: "Des-suspendido",
    Up: "Arriba",
    UpdateSuperFiles: "Actualizar superfile",
    Upload: "Subir",
    URL: "URL",
    Usage: "Utilización",
    Used: "Usado",
    User: "Usuario",
    UserDetails: "Detalles del Usuario",
    UserID: "ID del Usuarion",
    UserName: "Nombre de Usario",
    Username: "NombreDeUsario",
    UserPermissions: "Permisos del Usuario",
    Users: "Usuarios",
    UseSingleConnection: "Use una sola conexión",
    Validate: "Validar",
    ValidateActivePackageMap: "Validar Package Map Activo",
    ValidatePackageContent: "Validar Contenido de Paquete",
    ValidatePackageMap: "Validar el Package Map",
    ValidateResult: "=====Velida el Resultado=====\n\n",
    ValidateResultHere: "(resultado de la validación)",
    Value: "Valor",
    Variable: "Variable",
    VariableBigendian: "Variable &lsquo;Big-endian&rsquo;",
    Variables: "Variables",
    VariableSourceType: "Formato",
    Version: "Versión",
    ViewByScope: "&lsquo;Ver Por Ámbito&rsquo;",
    Views: "Vistas",
    Visualize: "Visualizar",
    WarnIfAvailableDiskSpaceIsUnder: "Advertencia si disco disponible esta debajo de",
    WarnIfAvailableMemoryIsUnder: "Advertencia si memoria disponible esta debajo de",
    WarnIfCPUUsageIsOver: "Advertencia si uso de CPU esta arriba de",
    Warning: "Advertencia",
    Warnings: "Advertencias",
    WarnOldGraphControl: "Advertencia: Controlador de Graphicas antiguo",
    What: "Que",
    Where: "Donde",
    Who: "Quien",
    Width: "Ancho",
    Workflows: "Flujos de Trabajo",
    Workunit: "Unidad de trabajo",
    Workunits: "Unidades de trabajo",
    WorkUnitScopeDefaultPermissions: "Permisos por defect de alcaces de Workunit",
    Wrap: "Envolver",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid no puede estar vacío.",
    WUSnapShot: "Captura de Unidad de trabajo",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "Referencias cruzadas",
    Year: "Año",
    YouAreAboutToDeleteBinding: "Está a punto de eliminar esta conexión. Desea continuar?",
    YouAreAboutToRemoveUserFrom: "Usted esta a punto de quitar un(os) usuario(s) de este grupo. ¿Desea continuar?",
    YouAreAboutToDeleteThisFile: "Usted esta a punto de eliminar este archivo. ¿Desea continuar?",
    YouAreAboutToDeleteThisQueryset: "Usted esta a punto de eliminar este grupo de consulta. ¿Desea continuar?",
    YouAreAboutToDeleteThisWorkunit: "Usted esta a punto de eliminar este workunit. ¿Desea continuar?",
    YourBrowserMayNotSupport: "Es posible que su navegador no soporta archivos de este tamaño",
    ZAP: "Z.A.P.",
    ZeroLogicalFilesCheckFilter: "Archivos logicos a cero (chequee filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Paquete de análisis en formato Zip",
    Zoom100Pct: "Aumentar a 100%",
    Zoom: "Zoom",
    ZoomAll: "Aumentar todo",
    ZoomWidth: "Aumentar al ancho"
})
);
