#!/bin/bash

run_bash=true
[ "$1" = "-d" ] && run_bash=false

VERSION=$(dpkg -l | grep hpccsystems-platform | awk '{print $3}')

cat << EOM

Welcome to HPCCSystems Platform Docker Version $VERSION

EclWatch: http://localhost:<mapped port on host>
The <mapped port on host> is the one when this container is
started with option "-p <host port>:8010"


EOM

if [ "$run_bash" = "true" ]
then
  echo "Start sshd ..."
  service ssh start
fi

echo ""
echo "Start HPCCSystems Platform ..."
echo ""

/etc/init.d/hpcc-init start


if [ "$run_bash" = "true" ]
then
  bash
else
  /usr/sbin/sshd -D
fi
