global:
  tracing:
    sampler:
    - type: Ratio     //Head sampling based on simple ratio
    - argument: "0.1" //only sample 10% of traces/spans
    - parentBased: true
    exporters:
    - type: OTLP-HTTP
      endpoint: "localhost:4318/v1/traces"
      consoleDebug: true