#!/bin/bash

if [ $# -lt 2 ]; then
    echo "$0: <processes> <testname>"
    exit 1
fi

processes=$1
thetest=$2
let "startn = 9000"
let "endn = 9000 + ${processes} - 1"

rm -f hosts
for port in `seq ${startn} ${endn}`;
do
 echo ".:${port}" >> hosts
done

for port in `seq ${startn} ${endn}`;
do
 ./Debug/bin/mptest ${port} -f hosts -t ${thetest} ${@:3} &
done

wait

