# Overrides for http-connect secrets in hpcc.
# NB: The "hpcc-connect-testsecret" should be created before installing the helm chart.

secrets:
  ecl:
    http-connect-basicsecret: "http-connect-basicsecret"
  eclUser:
    k8s-example: "k8s-example"

vaults:
  storage:
    - name: my-storage-vault
      #Note the data node in the URL is there for the REST APIs use. The path inside the vault starts after /data
      url: http://${env.VAULT_SERVICE_HOST}:${env.VAULT_SERVICE_PORT}/v1/secret/data/storage/${secret}
      kind: kv-v2
  ecl:
    #vault using kubernetes auth
    - name: my-ecl-vault
      #Note the data node in the URL is there for the REST APIs use. The path inside the vault starts after /data
      url: http://${env.VAULT_SERVICE_HOST}:${env.VAULT_SERVICE_PORT}/v1/secret/data/ecl/${secret}
      kind: kv-v2
  eclUser:
    #vault using kubernetes auth
    - name: my-eclUser-vault
      #Note the data node in the URL is there for the REST APIs use. The path inside the vault starts after /data
      url: http://${env.VAULT_SERVICE_HOST}:${env.VAULT_SERVICE_PORT}/v1/secret/data/eclUser/${secret}
      kind: kv-v2
  authn:
    - name: my-authn-vault
      #Note the data node in the URL is there for the REST APIs use. The path inside the vault starts after /data
      url: http://${env.VAULT_SERVICE_HOST}:${env.VAULT_SERVICE_PORT}/v1/secret/data/authn/${secret}
      kind: kv-v2
    #vault using provided token auth
#    - name: ecl-vault-direct-auth
       #Note the data node in the URL is there for the REST APIs use. The path inside the vault starts after /data
#      url: http://${env.VAULT_SERVICE_HOST}:${env.VAULT_SERVICE_PORT}/v1/secret/data/ecl/${secret}
#      kind: kv-v2
#      client-secret: "hpcc-vault-client"
