# Default values for hpcc-efs.
common:
  mountPrefix: "/var/lib/HPCCSystems"
  efsID:

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  category: dali
  apID:
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  category: dll
  rwmany: true
  apID:
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  category: sasha
  apID:
- name: data
  subPath: hpcc-data
  size: 3Gi
  category: data # NB: all "data" planes will be auto mounted by engine components and others that require access to data
  rwmany: true
  apID:
- name: mydropzone
  subPath: dropzone
  size: 1Gi
  rwmany: true
  category: lz
  apID: