define(
({
    Abort: "Megszakít",
    About: "Névjegy",
    AboutGraphControl: "'Graph Control' információk",
    AboutHPCCSystemsGraphControl: "'HPCC Systems® Graph Control' információk",
    Action: "Művelet",
    Activate: "Aktivál",
    Activated: "Aktivizált",
    Active: "Aktív",
    ActivePackageMap: "Aktív csomagtérkép",
    ActiveWorkunit: "Aktív feladat",
    Activities: "Tevékenységek",
    Activity: "Tevékenység",
    ActualSize: "Aktuális méret",
    Add: "Hozzáad",
    AddFile: "Fájl hozzáadás",
    AddGroup: "Csoport hozzáadás",
    AdditionalResources: "További erőforrások",
    AddProcessMap: "Csomagtérkép hozzáadás",
    AddToSuperfile: "Superfile-hoz ad",
    AddUser: "Felhasználó hozzáadás",
    Advanced: "Haladó",
    All: "Összes",
    AllowAccess: "<center>Hozzáférés<br>Engedélyezés</center>",
    AllowForeignFiles: "Idegen fájlok engedélyezése",
    AllowFull: "<center>Teljes<br>Hozzáférés</center>",
    AllowRead: "<center>Olvasás<br>Engedélyezés</center>",
    AllowWrite: "<center>Írás<br>Engedélyezés</center>",
    ANY: "Bármelyik",
    Append: "Hozzáfűz",
    Apply: "Alkalmaz",
    ArchivedOnly: "Csak tárolt.",
    ArchivedWarning: "Figyelem: Adjon meg rövidebb időintervallumot! Ellenkező esetben a feladatok lekérdezése hosszabb ideig tarthat, mint amit az Ön bőngésző programja engedélyez.",
    AutoRefresh: "Automatikus frissítés",
    Back: "Vissza",
    BannerColor: "Fejléc szín",
    BannerMessage: "Fejléc szövege",
    BannerScroll: "Fejléc görgetés",
    BannerSize: "Fejléc méret",
    BinaryInstalls: "Bináris telepítőkészlet",
    Blob: "BLOB",
    BlobPrefix: "BLOB előtag",
    Bottom: "Legalsó",
    Cancel: "Mégsem",
    Clear: "Mezők törlése",
    ClearPermissionsCache: "Törli a hozzáférés engedélyek gyorsítótárát",
    ClearPermissionsCacheConfirm: "Biztos, hogy törölni akarja a DALI és az ESP hozzáférési engedélyek gyorsítótárát? A futó feladatok teljesítménye jelentősen csökkenhet, amig a gyorsítótárak tartalma újratöltődik. ",
    Clone: "Klónozás",
    ClonedWUID: "Klónozott WUID",
    Close: "Bezárás",
    Cluster: "Klaszter",
    ClusterName: "Klaszter név",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Klaszter feldolgozások",
    Code: "Kód",
    CodeGenerator: "Kód generátor",
    Col: "Oszlop",
    CollapseAll: "Összes bezárása",
    Command: "Parancs",
    Comment: "Megjegyzés",
    Completed: "Kész",
    ComplexityWarning: "Több mint {threshold} aktivitás ({activityCount}) - elnyomjuk a kezdeti megjelenítést?",
    Component: "Komponens",
    Compress: "Tömörít",
    Compressed: "Tömörített",
    CompressedFileSize: "Tömörített fájl méret",
    Configuration: "Beállítások",
    ConfirmPassword: "Jelszó jóváhagyás",
    ConfirmRemoval: "Biztos, hogy ezt akarja csinálni?",
    Content: "Tartalom",
    Contents: "Tartalom",
    ContentType: "Tartalom típusa",
    Copy: "Másolat",
    Count: "Darab (Count)",
    Created: "Létrehozva",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Dátum",
    Day: "Nap",
    Deactivate: "Hatástalanít",
    Debug: "Hibakeresés",
    DEF: "DEF",
    Delete: "Törlés",
    Deleted: "Törölt",
    DeleteSelectedFiles: "Töröljük a kiválasztott fájlokat?",
    DeleteSelectedGroups: "Törölni akarja a kijelölt csoporto(ka)t?",
    DeleteSelectedPermissions: "Törli a kiválasztott hozzáférési engedélyeket?",
    DeleteSelectedQueries: "Töröljük a kiválasztott lekérdezéseket?",
    DeleteSelectedUsers: "Törölni akarja a kijelölt felhasználó(ka)t?",
    DeleteSelectedWorkunits: "Törölni akarja a kiválasztott feladatokat?",
    DeleteSuperfile2: "Szuper-fájl törlése",
    DeleteSuperfile: "Töröljük a Superfile-t?",
    DeleteThisPackage: "Törölni akarja ezt a csomagot?",
    Delimited: "Határolt",
    DenyAccess: "<center>Hozzáférés<br>Tiltása</center>",
    DenyFull: "<center>Műveletek<br>Tiltása</center>",
    DenyRead: "<center>Olvasás<br>Tiltása</center>",
    DenyWrite: "<center>Írás<br>Tiltása</center>",
    Depth: "Mélység",
    DepthTooltip: "Maximális al-gráf mélység",
    Deschedule: "Ütemezés törlése",
    DescheduleSelectedWorkunits: "Megszűnteti a kijelőlt feladat ütemezését?",
    Description: "Leírás",
    Despray: "Összegyűjt",
    Details: "Részletek",
    DFUServerName: "DFU Szerver név",
    DFUWorkunit: "DFU-munkaegység",
    Directory: "Könyvtár",
    DisableScopeScanConfirm: "Biztos, hogy letíltja a hatókör vizsgálatot? DALI újraíndításakor ezek a változtatások elvesznek.",
    DisableScopeScans: "Hatókör vizsgálat letiltása",
    DiskUsage: "Lemez használat",
    Distance: "Távolság",
    DistanceTooltip: "Legnagyobb aktivitás-szomszéd távolság",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Attribútumok",
    Down: "Le",
    Download: "Letöltés",
    DropZone: "Gyűjtőhely",
    Duration: "Időtartam",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "ECL-munkaegység",
    Edges: "Élek",
    Edit: "Szerkesztés",
    EditDOT: "DOT szerkesztés",
    EditGraphAttributes: "Gráf attribútumok szerkesztése",
    EditXGMML: "XGMML szerkesztés",
    Empty: "(Üres)",
    Enable: "Engedélyezés",
    EnableScopeScans: "Hatókör vizsgálat engedélyezése",
    EnableScopeScansConfirm: "Biztos, hogy engedélyezi a hatókör vizsgálatot? DALI újraíndításakor ezek a változtatások elvesznek.",
    EnglishQ: "Angolul?",
    Error: "Hiba",
    Errorparsingserverresult: "Hiba a szerver válasz feldolgozásban",
    Errors: "Error(s)",
    Errors: "Hibák",
    ErrorsStatus: "Hibák/Figyelmeztetések",
    ErrorWarnings: "Hiba/Figyelmeztetés",
    Escape: "Megszakít",
    ESPBuildVersion: "ESP Build verzió",
    ESPNetworkAddress: "ESP hálózati címe",
    EventName: "Esemény neve",
    EventNamePH: "eventname",
    EventScheduler: "Esemény ütemező",
    EventText: "Esemény szövege",
    EventTextPH: "Esemény szövege",
    Exception: "Kivétel",
    ExpandAll: "Összes kinyitása",
    Export: "Exportálás",
    FailIfNoSourceFile: "Hibajelzés, ha nincs bemeneti file",
    FetchingData: "Adat lekérdezés...",
    fetchingresults: "eredemény lekérdezés",
    File: "Fájl",
    FileCounts: "Fájlok száma",
    FileName: "Fájl név",
    FileParts: "Fájl részek",
    FilePath: "Fájl útvonal",
    Files: "Fájlok",
    FileScopes: "Fájl keresési hatókörök",
    FileSize: "Fájl méret",
    FilesNoPackage: "Csomagdefiníció nélküli fájlok",
    FilesWithUnknownSize: "Ismeretlen méretű fájlok",
    FileType: "Fájl típus",
    FileUploader: "Fájl feltöltő",
    FileUploadStillInProgress: "Fájl feltöltés folyamatban",
    Filter: "Szűrő",
    Find: "Keresés",
    FindNext: "Következőt",
    FindPrevious: "Előzőt",
    Finished: "Befejezett",
    FirstName: "Keresztnév",
    FirstNRows: "Első N rekord",
    Fixed: "Állandó rekordméret",
    Folder: "Könyvtár",
    Format: "Formátum",
    Forward: "Előre",
    FromDate: "Dátumtól",
    FromSizes: "Mérettől",
    FromTime: "Időponttól",
    FullName: "Teljes név",
    Graph: "Gráf",
    Graphs: "Gráfok",
    GraphView: "Gráf nézet",
    Group: "Csoport",
    GroupBy: "Csoportosítva",
    GroupDetails: "Csoport jellemzők",
    Grouping: "Csoportosítás",
    GroupName: "Csoport név",
    GroupPermissions: "Csoport engedélyek",
    Groups: "Csoportok",
    GZip: "GZip",
    help: "Ezen a területen a munkaegység gráfjai láthatók. Az egyes blokkok mérete és színe az adott blokk végrehajtási idejével arányos (a nagyobb es sötétebb terület a hosszabb időtartamot jelzi).",
    Helpers: "Segédletek",
    Hex: "Hexa nézet",
    High: "Magas",
    History: "Történet",
    HPCCSystems: "HPCC Systems®",
    ID: "Azonosító",
    Inactive: "Inaktív",
    Index: "Index",
    Info: "Információ",
    InfoDialog: "Információk",
    Inputs: "Bemenet",
    InvalidResponse: "(Érvénytelen válasz)",
    IP: "IP",
    IPAddress: "IP cím",
    IsLibrary: "Könyvtár?",
    IsReplicated: "Készült másodpéldány?",
    JobName: "Munka azonosító",
    Jobname: "Munka azonosító",
    jsmi: "jkis*",
    JSmith: "JKis*",
    JSON: "JSON",
    Label: "Címke",
    LandingZone: "Lerakat",
    LandingZones: "Lerakatok",
    LanguageFiles: "Nyelvi fájlok",
    Largest: "Legnagyobb",
    LargestFile: "Legnagyobb fájl",
    LargestSize: "Legnagyobb méret",
    LastName: "Vezetéknév",
    LastNDays: "Az utolsó N nap",
    LastNHours: "Utolsó N óra",
    LastNRows: "Utolsó N rekord",
    LDAPWarning: "<b>LDAP szolgáltatás hiba:</b>  'Túl sok felhasználó' - Kérem, használjon szűrést!",
    LegacyForm: "Örökölt űrlap (Legacy Form)",
    LibrariesUsed: "Használt könyvtárak",
    LibraryName: "Library név",
    Line: "Sor",
    LineTerminators: "Sorvég karakterek",
    Links: "Linkek",
    Loading: "Betöltés",
    LoadingCachedLayout: "Tárolt elrendezés betöltése",
    LoadingData: "Adat betöltés...",
    loadingMessage: "Betöltés folyamatban...",
    LoadPackageContentHere: "(Csomag tartalmának betöltése erre a helyre)",
    LoadPackageFromFile: "Csomag betöltése fájlból",
    Local: "Helyi",
    Log: "Log",
    LogFile: "Log fájl",
    LoggedInAs: "Bejelentkezve mint ",
    LogicalFile: "Logikai fájl",
    LogicalFile: "Logikai fájl neve",
    LogicalFiles: "Logikai fájlok",
    LogicalFilesAndSuperfiles: "Logikai és szuper fájlok",
    LogicalFilesOnly: "Csak a logikai fájlokat",
    LogicalFileType: "Logikai fájl típusa",
    LogicalName: "Logikai név",
    Logs: "Logok",
    log_analysis_1: "log_elemzés_1*",
    Low: "Alacsony",
    ManualCopy: "Használja a Ctr+C-t",
    ManualOverviewSelection: "Gyorsnézet manuális kiválasztása szükséges",
    ManualTreeSelection: "Manuális fa kiválasztás szükséges",
    Mappings: "Leképezések",
    Mask: "Maszk",
    Max: "Maximum",
    MaxRecordLength: "Maximális rekord méret",
    MemberOf: "Tagja a",
    Members: "Tagok",
    Message: "Üzenet",
    Min: "Minimum",
    Missing: "Hiányzó",
    MixedNodeStates: "Több komponenst tartalmazó csomópont állapota",
    Modification: "Módosítás",
    Modified: "Módosított",
    ModifiedUTCGMT: "Módosítva (UTC/GMT)",
    Modify: "Módosít",
    MonitorEventName: "Monitor esemény név",
    Monitoring: "Felügyelet",
    MonitorShotLimit: "Monitor találatok limitje",
    MonitorSub: "Almonitor",
    Month: "Hónap",
    More: "Tovább",
    MustContainUppercaseAndSymbol: "Csak nagybetűket és jeleket tartalmazhat",
    NA: "N/A",
    Name: "Név",
    NamePrefix: "Név előtag",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Legújabb",
    NewPassword: "Új jelszó",
    NoContent: "(Nincs tartalom)",
    noDataMessage: "Nincs a feltételeknek megfelelő adat...",
    Node: "Csomópont",
    NodeGroup: "Node csoport",
    NoErrorFound: "Nincs hiba",
    NoFilterCriteriaSpecified: "Nincs szűrőfeltétel megadva.",
    None: "Semmi",
    Normal: "Normál",
    NoScheduledEvents: "Nincs ütmezett esemény",
    NoSplit: "Együtt tart",
    NotActive: "Nem aktív",
    NothingSelected: "Nincs kiválasztva…",
    NotInSuperfiles: "Nincs a szuper fájlban",
    NotSuspendedbyUser: "Nem a felhasználó által felfüggesztett",
    NoWarningFound: "Nincs figyelmeztetés",
    NumberofParts: "Részek száma",
    OK: "Rendben",
    Oldest: "Legrégebbi",
    OldPassword: "Régi jelszó",
    OmitSeparator: "Elválasztójel mellőzése",
    Only1PackageFileAllowed: "Csak egy csomagfájl engedélyezett",
    Open: "Megnyitás",
    OpenInNewPage: "Megnyitás új lapon",
    OpenInNewPageNoFrame: "Megnyitás új lapon (nem keretben)",
    OpenLegacyECLWatch: "Legacy ECL Watch megnyitása",
    OpenSafeMode: "Megnyitás (biztonságos módban)",
    OpenSource: "Nyílt forráskódú",
    OpenTreeMode: "Nyitva (fa nézetben)",
    Operations: "Műveletek",
    Options: "Opciók",
    Outputs: "Kimenet",
    Overview: "Áttekintés",
    Overwrite: "Fellülírás",
    OverwriteMessage: "Néhány fájl már létezik! A folytatáshoz engedélyezze a fellülírást!",
    Owner: "Tulajdonos",
    PackageContent: "Csomag tartalma",
    PackageContentNotSet: "Csomag tartalma nincs megadva",
    PackageMap: "Csomagtérkép",
    PackageMaps: "Csomagtérképek",
    PackagesNoQuery: "Csomagok hozzátartozó lekérdezés nélkül",
    ParameterXML: "Paraméter XML fájl",
    Part: "Rész",
    Parts: "Részek",
    Password: "Jelszó",
    PasswordExpiration: "Jelszó lejár",
    PasswordExpired: "A jelszava lejárt! Adjon meg újat!",
    PasswordExpirePostfix: "napon bellül. Meg akarja változtatni?",
    PasswordExpirePrefix: "Jelszava lejár",
    PasswordOpenZAP: "Jelszó a ZAP megnyitásához (opciónális)",
    PasswordsDoNotMatch: "Jelszó nem egyezik",
    Path: "Útvonal",
    PathMask: "Útvonal maszk",
    Pause: "Szüneteltetés",
    PauseNow: "Azonnali felfüggesztés",
    PctComplete: "% kész",
    PercentDone: "% kész",
    PerformingLayout: "Elrendezés generálása...",
    PermissionName: "Hozzáférési jog megnevezése",
    Permissions: "Jogosultságok",
    PlaceholderFindText: "Wuid, felhasználók, egyebek...",
    PlaceholderFirstName: "József",
    PlaceholderLastName: "Kiss",
    Playground: "ECL teszt labor",
    Plugins: "Betölthető modulok",
    Port: "Port",
    Prefix: "Előtag",
    PrefixPlaceholder: "fájlnév{:hossz}, fájlméret{:[B|L][1-8]}",
    PreserveCompression: "Tartalom tömörtés megőrzése",
    Preview: "Előnézet",
    PrimaryMonitoring: "Elsődleges felügyelet",
    Priority: "Prioritás",
    Process: "Feldolgozás",
    ProcessFilter: "Process&nbsp;Filter",
    ProgressMessage: "Állapot",
    Properties: "Tulajdonságok",
    Property: "Tulajdonság",
    Protect: "Megvéd",
    Protected: "Védett",
    Publish: "Publikál",
    Published: "Közzétett",
    PublishedBy: "Közzétette",
    PublishedQueries: "Publikált lekérdezések",
    PushEvent: "Push event",
    Quarter: "Negyed",
    Queries: "Lekérdezések",
    QueriesNoPackage: "Lekérdezések hozzátartozó csomag nélkül",
    Query: "Lekérdezés",
    QueryDetailsfor: "A lekérdezés paraméterei",
    QueryID: "Lekérdezés azonosító",
    QueryIDPlaceholder: "som?q*ry.1'",
    QueryName: "Lekérdezés név",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Lekérdezés készlet",
    Queue: "Sor",
    Quote: "Idézőjel",
    QuotedTerminator: "A fájl idézőjelek közötti rekordhatároló karaktert tartalmaz",
    RawTextPage: "Formázatlan szöveg (aktuális lap)",
    RecordCount: "Rekord szám",
    RecordLength: "Rekord méret",
    Records: "Rekordok száma",
    RecordSize: "Rekord méret",
    RecordStructurePresent: "CSV rekord struktúra definiált az fájl első sorában",
    Recover: "Helyreállít",
    Refresh: "Frissítés",
    ReleaseNotes: "Verzió információk (Release Notes)",
    Reload: "Újratölt",
    Remaining: "Hátralévő",
    RemoteCopy: "Távoli másolat",
    RemoteDali: "Távoli Dali hálózati címe",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "Eltávolít",
    RemoveSubfiles: "Al-fájl(ok) eltávolítása",
    RemoveUser: "Arra készül, hogy eltávolítsa a felhasználói nevét a csoportból!",
    Rename: "Átnevez",
    RenderedSVG: "Generált SVG",
    RenderSVG: "SVG generálás",
    Replicate: "Másolat",
    RequestSchema: "Igénylő séma (Request Schema)",
    Reschedule: "Újraütemez",
    Reset: "Forrás",
    ResetThisQuery: "Vissza akarja állítani ezt a lekérdezést az allapállapotába?",
    ResetViewToSelection: "Vissza akarja állítani ezt a nézetet a kiválasztott elemekre?",
    Resource: "Erőforrás",
    Resources: "Erőforrások",
    ResponseSchema: "Válasz séma (Response Schema)",
    Restart: "Újraindít",
    Restarted: "Újraindított",
    Restore: "Visszaállítás",
    Resubmit: "Újraküld",
    Resubmitted: "Újraküldött",
    Results: "Eredmény(ek)",
    Resume: "Tovább folytat",
    RetainSuperfileStructure: "Superfile szerkezetének megőrzése",
    RetypePassword: "Jelszó mégegyszer",
    Reverse: "Visszafelé",
    RowPath: "Rekord útvonal",
    Rows: "Sor",
    RowTag: "Sor azonositó",
    RoxieCluster: "Roxie klaszter",
    Sample: "Minta",
    SampleRequest: "Minta igénylés (Sample Request)",
    SampleResponse: "Minta válasz (Sample Response)",
    Save: "Mentés",
    Scope: "Hatókör",
    SearchResults: "Keresések",
    SecondsRemaining: "másodperc maradt",
    Security: "Biztonság",
    SelectPackageFile: "Csomagfájl választás",
    Separators: "Elválasztó jelek",
    SetBanner: "Fejléc megadása",
    SetTextError: "Nem sikerült a szöveget megjeleníteni. Lehetséges, hogy túl hosszú. Használja a 'segédleteket' a letöltéshez.",
    SetToFailed: "Elront",
    Severity: "Probléma mértéke",
    Show: "Megjelenít",
    ShowSVG: "SVG megjelenítés",
    Size: "Méret",
    Skew: "Asszimmetrikus (Skew)",
    SLA: "SLA",
    Slaves: "Kiszolgáló",
    Smallest: "Legkisebb",
    SmallestFile: "Legkisebb fájl",
    SmallestSize: "Legkisebb méret",
    SOAP: "SOAP",
    SomeDescription: "Valamennyi leírás",
    somefile: "*::somefile",
    somefile: "*::somefile*",
    Source: "Forrás",
    SourceCode: "Forráskód",
    SourcePath: "Forrás útvonal (joker karakter engedélyezett)",
    SourceProcess: "Forrás feldolgozás",
    SplitPrefix: "Elválasztó előtag",
    Spray: "Szétoszt",
    Start: "Indítás",
    Started: "Elindítva",
    State: "Állapot",
    Stats: "Statisztika",
    Status: "Állapot",
    Stopped: "Megállítva",
    Subgraph: "Al-gráf",
    Subgraphs: "Algráf",
    Submit: "Elküld",
    Subtype: "Altípus",
    Summary: "Összegzés",
    SummaryMessage: "Összegzés",
    SuperFile: "Szuper-fájl",
    Superfile: "Szuper-fájl",
    Superfiles: "Szuper-fájlok",
    SuperFiles: "Szuperfájlok",
    SuperFilesBelongsTo: "Szuperfájl(ok)hoz tartozik",
    SuperfilesOnly: "Kizárólag szuperfájl",
    Suspend: "Felfüggeszt",
    Suspended: "Felfüggesztve",
    SuspendedBy: "Felfüggesztette",
    SuspendedByCluster: "A klaszter által felfüggesztett",
    SuspendedByUser: "Felhansználó által felfüggesztett",
    SuspendedReason: "A felfüggesztés oka",
    SVGSource: "SVG forrás",
    Sync: "Szinkronizálás",
    SyncSelection: "Szinkronizálás a kiválasztottakhoz",
    SystemServers: "Rendszer kiszolgálók",
    tag: "jel",
    Target: "Cél",
    TargetClusters: "Cél klaszterek",
    TargetName: "Cél neve",
    TargetNamePlaceholder: "valamilyen::logikai::fájlnév",
    TargetScope: "Cél hatókör",
    TargetWuid: "Cél/WUID",
    Terminators: "Rekord lezáró jelek",
    TestPages: "Tesztlapok",
    Text: "Szöveg",
    ThorMasterAddress: "Thor Master hálózati címe",
    ThorNetworkAddress: "Thor hálózati címe",
    Time: "Idő",
    Timers: "Időzítések",
    TimeSeconds: "Idő (másodperc)",
    TimeStarted: "Kezdés",
    TimeStopped: "Befejezés",
    Timings: "Időzítések",
    TimingsMap: "Időzítés térkép",
    title_Activity: "Tevékenység",
    title_ClusterInfo: "Csoportok",
    title_DFUQuery: "Logikai fájlok",
    title_DFUWUDetails: "DFU munka",
    title_DiskUsage: "Lemez használat",
    title_ECLPlayground: "ECL teszt labor",
    title_EventScheduleWorkunit: "Esemény ütemező",
    title_GetDFUWorkunits: "DFU feladatok",
    title_Graph: "Gráfok",
    title_GraphPage: "Cím",
    title_Graphs: "Gráfok",
    title_GridDetails: "Változtass meg!",
    title_HPCCPlatformECL: "ECL Watch - Kezdőlap",
    title_HPCCPlatformFiles: "ECL Watch - Fájlok",
    title_HPCCPlatformMain: "ECL Watch - Kezdőlap",
    title_HPCCPlatformOps: "ECL Watch - Műveletek",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Watch betölthető modulok",
    title_Inputs: "Bementek",
    title_LFDetails: "Logikai fájl információk",
    title_LibrariesUsed: "Felhasznált kódkönyvtárak",
    title_Log: "Log fájl",
    title_LZBrowse: "Lerakatok",
    title_MemberOf: "Tagja a",
    title_Members: "Tagok",
    title_QuerySetDetails: "Lekérdezés paraméterei",
    title_QuerySetErrors: "Hibák",
    title_QuerySetLogicalFiles: "Logikai fájlok",
    title_QuerySetQuery: "Lekérdezések",
    title_QuerySetSuperFiles: "Szuper fájlok",
    title_QueryTest: "Szuper fájlok",
    title_Result: "Tevékenység",
    title_Results: "Kimenet",
    title_SearchResults: "Keresés eredménye",
    title_SourceFiles: "Forrás fájlok",
    title_Topology: "Topológia",
    title_TpThorStatus: "Thor állapot",
    title_UserPermissions: "Felhasználó engedélyei",
    title_UserQuery: "Engedélyek",
    title_WUDetails: "ECL feladat jellemzők",
    title_WUQuery: "ECL feladatok",
    To: "-ig",
    ToDate: "Dátumig",
    Toenablegraphviews: "A gráfok megjelenítéshez telepiteni kell a 'Graph View Control' bővítményt.",
    Top: "Felső",
    Topology: "Topológia",
    ToSizes: "Méretig",
    TotalClusterTime: "Teljes cluster idő",
    TotalSize: "Összméret",
    TotalThorTime: "Összes Thor idő",
    TransitionGuide: "Átmenet útmutató",
    Tree: "Fa",
    Type: "Típus",
    undefined: "nem definiált",
    Unknown: "Ismeretlen",
    Unprotect: "Védelem nélkül",
    UnsupportedIE9FF: "Nem támogatott böngészőprogram (IE <= 9, FireFox )",
    Unsuspend: "Folytat",
    Unsuspended: "Folytatva",
    Up: "Fel",
    Upload: "Feltöltés",
    Usage: "Használat",
    Used: "Használva",
    User: "Felhasználó",
    UserDetails: "Felhasználó adatai",
    UserID: "Felhasználó azonosítója",
    UserName: "Felhasználó neve",
    Username: "Felhasználó neve",
    UserPermissions: "Felhasználó engedélyei",
    Users: "Felhasználók",
    UseSingleConnection: "Egy kapcsolat használatával",
    Validate: "Ellenőriz",
    ValidateActivePackageMap: "Csomag-térkép ellenőrzés",
    ValidatePackageContent: "Csomag tartalom ellenőrzés",
    ValidatePackageMap: "Csomagtérkép ellenőrzés",
    ValidateResult: " =====Eredmény ellenőrzés=====",
    ValidateResultHere: "(Az ellenőrzés eredménye)",
    Value: "Érték",
    Variable: "Változó",
    VariableBigendian: "Big-endián változó",
    Variables: "Változók",
    VariableSourceType: "Forrás típus",
    Version: "Verzió",
    ViewByScope: "Megjelenítés hatókör szerint",
    Views: "Nézetek",
    Visualize: "Grafikus megjelenítés",
    Warnings: "Figyelmeztetések",
    WarnOldGraphControl: "Figyelem: A Graph Control modul elavult!",
    What: "Mit?",
    Where: "Hol?",
    Who: "Ki?",
    Width: "Szélesség",
    Workflows: "Munkafolyamat",
    Workunit: "Feladat",
    Workunits: "Feladatok",
    Wrap: "Csomagol (Wrap)",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid megadása kötelező!",
    WUSnapShot: "WU pillanatfelvétel",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "Keresztreferencia (XRef)",
    Year: "Év",
    YourBrowserMayNotSupport: "Előfordulhat, hogy az Ön böngészőprogramja nem támogatja az ekkora méretű fájlokat.",
    ZAP: "Z.A.P.",
    ZeroLogicalFilesCheckFilter: "Nincs a megadott feltételnek megfelelő adat! (A jó a szűrőfeltétel?)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Tömörített elemzési csomag",
    Zoom: "Nagyítás",
    Zoom100Pct: "Nagyítás 100%-ra",
    ZoomAll: "Teljes gráf ablakba méretezése",
    ZoomWidth: "Gráf nagyítása az ablak szélességére"
})
);
