    "_",
    "/",
    ".",
    "",
    "* * * * *",
    "*",
    "\\,",
    "0 secs",
    "-1"
    "1:1",
    "1:M",
    "* 2 * * *",
    "* 3 * * *",
    "aaalibrary2",
    "aaalibrary2.1",
    "aaalibrary3a",
    "aaalibrary3a.1",
    "aaalibrary3b",
    "aaalibrary4",
    "aaalibrary4.1",
    "aaalibrary5",
    "Access to cluster topology",
    "Access to despraying of files",
    "Access to DFU",
    "Access to DFU exceptions",
    "Access to DFU workunits",
    "Access to DFU XRef",
    "Access to ECL direct service",
    "Access to ECL Direct service",
    "Access to ESDL configuration service",
    "Access to files in dropzone",
    "Access to machine information",
    "Access to own workunits",
    "Access to permissions for file scopes",
    "Access to roxie control commands",
    "Access to SMC service",
    "Access to SNMP metrics information",
    "Access to spraying files",
    "Access to thor queues",
    "Access to upload files to dropzone",
    "Access to workunits owned by others",
    "Access to WS ECL service",
    "Access to WS Logging service",
    "Action",
    "Action #1",
    "Action #2",
    "active",
    "activities",
    "Aggregate",
    "Alias",
    "All Denormalize",
    "All Denormalize Group",
    "All Join",
    "anderson",
    "anderson_xxx",
    "any",
    "anyone",
    "Application",
    "archive",
    "ASSERT",
    "Associated",
    "atftpd",
    "Attr",
    "auto2",
    "auto4",
    "auto6",
    "auto8",
    "b",
    "bands",
    "Begin Loop",
    "blank",
    "blocked",
    "Blocked by fileservice activity: Copy",
    "Body",
    "bytes",
    "c",
    "c1",
    "c2",
    "c3",
    "c4",
    "calculated",
    "canstall",
    "ca.pem",
    "cd",
    "ce2",
    "certificate.cer",
    "checkasserts",
    "Child",
    "Child Dataset",
    "childfile",
    "_childGraph",
    "Client",
    "Cluster",
    "ClusterLock",
    "ClusterTopologyAccess",
    "cnt",
    "coLocal",
    "color1",
    "color2",
    "color3",
    "color4",
    "compile",
    "compile:compile c++",
    "compiled",
    "compile:generate c++",
    "compile:generate PARSE",
    "compile:generate PARSE:analyse",
    "compile:generate PARSE:compile",
    "compile:generate PARSE:create structure",
    "compile:generate PARSE:generate",
    "compile:generate PARSE:optimize",
    "compile:generate PARSE:prepare",
    "compile:global implicit projects",
    "compile:implicit projects",
    "compile:optimize graph",
    "compile:parseTime",
    "compile:peephole optimize",
    "compile:resource graph",
    "compile:tree transform",
    "compile:tree transform: check dependency",
    "compile:tree transform: compound activity",
    "compile:tree transform: convert logical",
    "compile:tree transform: convert SetResult to Extract",
    "compile:tree transform: expand delayed calls",
    "compile:tree transform: global fold",
    "compile:tree transform: hoist nested compound",
    "compile:tree transform: merge thor",
    "compile:tree transform: migrate",
    "compile:tree transform: normalize",
    "compile:tree transform: normalize.annotations",
    "compile:tree transform: normalize.DFStransform",
    "compile:tree transform: normalize.initial",
    "compile:tree transform: normalize.KeyedProjectTransformer",
    "compile:tree transform: normalize.linkedChildRows",
    "compile:tree transform: normalize result",
    "compile:tree transform: normalize.scope",
    "compile:tree transform: optimize activities",
    "compile:tree transform: optimize disk read",
    "compile:tree transform: spot global cse",
    "compile:tree transform: stored results",
    "compile:tree transform: substituteClusterSize",
    "compile:tree transform: thor hole",
    "compile:write c++",
    "compiling",
    "completed",
    "componentfiles/configxml",
    "componentfiles/dafilesrv",
    "componentfiles/dali",
    "componentfiles/dfuplus",
    "componentfiles/dfuserver",
    "componentfiles/DropZone",
    "componentfiles/eclagent",
    "componentfiles/ecldirect",
    "componentfiles/eclminus",
    "componentfiles/eclplus",
    "componentfiles/esdlsvcengine",
    "componentfiles/esp",
    "componentfiles/esploggingagent",
    "componentfiles/espsmc",
    "componentfiles/ftslave",
    "componentfiles/hqltest",
    "componentfiles/ldapServer",
    "componentfiles/loggingmanager",
    "componentfiles/sasha",
    "componentfiles/SiteCertificate",
    "componentfiles/soapplus",
    "componentfiles/thor",
    "componentfiles/topology",
    "componentfiles/ws_ecl",
    "componentfiles/wslogging",
    "condition",
    "conf",
    "copy",
    "Count",
    "Count Project",
    "cpp",
    "created_by",
    "created_for",
    "CRON",
    "csv",
    "Csv Write",
    "Customer of HPCCSystems",
    "d",
    "d1",
    "d2",
    "da",
    "dafilesrv",
    "DafilesrvProcess",
    "DaFileSrv process",
    "dafilesrv.xsd",
    "dali",
    "DaliServerProcess",
    "dali.xsd",
    "data",
    "data2",
    "data3",
    "data4",
    "date",
    "db",
    "dc",
    "dd",
    "de",
    "Debug",
    "decfive",
    "decfour",
    "decone",
    "decthree",
    "dectwo",
    "Dedup",
    "definition",
    "Degroup",
    "Denormalize",
    "Denormalize Group",
    "Dependency",
    "_dependsOn",
    "deploy_map.xml",
    "deserialized",
    "Destination",
    "/dev*,/sys,/proc/*",
    "dfu",
    "DfuAccess",
    "DFUcopy",
    "DfuExceptions",
    "DfuExceptionsAccess",
    "dfuplus",
    "DfuplusProcess",
    "dfuplus.xsd",
    "dfuserver",
    "DFUserver",
    "DFU Server",
    "dfuserver_monitor_queue",
    "DfuServerProcess",
    "dfuserver_queue",
    "dfuserver.xsd",
    "DfuWorkunitsAccess",
    "DfuXrefAccess",
    "dhcpd",
    "_diskAccessRequired",
    "DiskUsageStats",
    "Disk Write",
    "dll",
    "done",
    "DropZone",
    "DropZone process",
    "dropzone.xsd",
    "DynamicESDL",
    "e",
    "ecl",
    "ECL",
    "eclagent",
    "EclAgent",
    "ECLagent",
    "EclAgentBuild",
    "eclagent_config.xsd",
    "EclAgent process",
    "EclAgentProcess",
    "eclcc",
    "eclcc-dalgo-0",
    "eclcc-dmultipart-0",
    "eclcc-dscale-0",
    "eclcc-duselocal-1",
    "eclcc-dusesequential-1",
    "eclcc-dusetranslation-1",
    "eclccserver",
    "ECLCCserver",
    "eclccserver_deploy_map.xml",
    "EclCCServer process",
    "EclCCServerProcess",
    "eclccserver.xsd",
    "ecl.common",
    "ecldirect",
    "EclDirectAccess",
    "EclDirectSoapBinding",
    "eclminus",
    "eclplus",
    "EclPlusProcess",
    "eclplus.xsd",
    "eclscheduler",
    "eclscheduler_deploy_map.xml",
    "EclScheduler process",
    "EclSchedulerProcess",
    "eclscheduler.xsd",
    "ecl.setup",
    "EclWatch",
    "Edition",
    "End Loop",
    "Environment_Initialize",
    "EsdlBinding",
    "ESDLConfigAccess",
    "esdl_svc_engine",
    "esdlsvcengine.xsd",
    "esp",
    "esploggingagent",
    "ESPLoggingAgent",
    "esploggingagent.xsd",
    "EspProcess",
    "ESP server",
    "ESPserver",
    "EspService",
    "ESPservice",
    "esp_service_ecldirect.xsd",
    "esp_service_module",
    "ESP services for SMC",
    "esp_service_wsecl2.xsd",
    "espsmc",
    "espsmcservice.xsd",
    "esp.xsd",
    "Exception",
    "Exceptions",
    "expandpersistinputdependencies",
    "f",
    "fAddFileRelationship",
    "fAddSuperFile",
    "failed",
    "failonleaks",
    "failure",
    "false",
    "False",
    "falseval",
    "farm1",
    "farm2",
    "fCreateSuperFile",
    "fDeleteLogicalFile",
    "fDeleteSuperFile",
    "fFileExists",
    "fFinishSuperFileTransaction",
    "fgetParseTree",
    "fGetSuperFileSubCount",
    "file",
    "File",
    "FileDesprayAccess",
    "_file_dynamic",
    "FileIOAccess",
    "_fileName",
    "__filepos",
    "filepos",
    "__fileposition__",
    "files",
    "Files",
    "/Files[1]",
    "/Files[1]/Relationships[1]",
    "/Files[1]/Scope[1]",
    "FileScopeAccess",
    "fileservices",
    "FileSprayAccess",
    "FilesRead",
    "FileUploadAccess",
    "Filter",
    "Filtered Project",
    "finished",
    "Firstn",
    "five",
    "flat",
    "float",
    "Format",
    "four",
    "fRemoveSuperFile",
    "_fromChild",
    "fSetColumnMapping",
    "fStartSuperFileTransaction",
    "fSuperFileExists",
    "ftslave",
    "ftslave_linux.xsd",
    "FTSlave process",
    "FTSlaveProcess",
    "function",
    "Funnel",
    "/GeneratedDlls[1]",
    "GenesisServerProcess",
    "gl01",
    "gl2",
    "gl4",
    "gl6",
    "gl8",
    "glA",
    "glC",
    "glE",
    "glG",
    "glI",
    "glK",
    "glM",
    "glO",
    "global",
    "_globalUsageCount",
    "glQ",
    "glS",
    "glU",
    "graph",
    "Graph",
    "graphBin",
    "_graphid",
    "_graphId",
    "_graphIndependent",
    "/GraphProgress[1]/",
    "Graphs",
    "Group",
    "grouped",
    "Grouped Aggregate",
    "Grouped Dedup",
    "Grouped Filter",
    "Grouped Iterate",
    "Grouped Normalize",
    "Grouped Process",
    "Grouped Project",
    "Grouped Rollup",
    "Grouped Sort",
    "Grouped Split",
    "Hash Aggregate",
    "Hash Dedup",
    "Hash Distribute",
    "$HOME/.ssh/id_rsa",
    "hpcc",
    "hpccinternal",
    "HPCCSystems",
    "hqltest",
    "HqlTestProcess",
    "hthor",
    "hthor.agent",
    "hthor.agent,thor.agent",
    "hthor.eclserver",
    "hthor.eclserver,thor.eclserver,roxie.eclserver,thor_roxie.eclserver",
    "HThorServer",
    "http",
    "httpd",
    "http://hpccsystems.com/download",
    "http://www.w3.org/1999/XMLSchema-instance",
    "id",
    "If",
    "ignore",
    "import",
    "in",
    "_indexFileName",
    "Index Write",
    "inds",
    "infile",
    "initial",
    "Inline Dataset",
    "Inline Row",
    "inputs",
    "_internal",
    "isokay",
    "_isSpill",
    "_isTransformSpill",
    "Item",
    "Iterate",
    "j",
    "j1",
    "j2",
    "j3",
    "Job",
    "/JobQueues[1]/Queue[1]",
    "/JobQueues[1]/Queue[10]",
    "/JobQueues[1]/Queue[11]",
    "/JobQueues[1]/Queue[12]",
    "/JobQueues[1]/Queue[3]",
    "/JobQueues[1]/Queue[4]",
    "/JobQueues[1]/Queue[5]",
    "/JobQueues[1]/Queue[6]",
    "/JobQueues[1]/Queue[7]",
    "/JobQueues[1]/Queue[8]",
    "/JobQueues[1]/Queue[9]",
    "jobtemp",
    "Join",
    "json",
    "KB",
    "kerberos",
    "key",
    "_kind",
    "lang",
    "layouttranslationenabled",
    "ldapServer",
    "LDAPServerProcess",
    "ldapserver.xsd",
    "LDS",
    "LEFT",
    "lhs",
    "lib_fileservices",
    "libfileservices.so",
    "lib_parselib",
    "libparselib.so",
    "lib_stringlib",
    "libstringlib.so",
    "lib_unicodelib",
    "libunicodelib.so",
    "libworkunitservices.so",
    "Lightweight Self Join",
    "link",
    "linux",
    "Linux",
    "linuxmachine",
    "local",
    "Local Dedup",
    "localdomain",
    "Local Group",
    "localhost",
    "Local Index Write",
    "Local Join",
    "Local Result",
    "Local Sort",
    "Local Sorted",
    "location",
    "lock",
    "/_Locks[1]/SuperOwnerLock[1]",
    "log",
    "loggingmanager",
    "LoggingManager",
    "loggingmanager.xsd",
    "loggingservice_binding",
    "logicalName",
    "lookupjoin",
    "Lookup Join",
    "Loop",
    "_loopid",
    "m1",
    "MachineInfoAccess",
    "makechildren",
    "makedataset",
    "master",
    "matches",
    "MatchSmith",
    "maxcompilethreads",
    "maxCompileThreads",
    "maxseeklookahead",
    "maybesort",
    "Merge",
    "Merge Join",
    "MetricsAccess",
    "mf1",
    "mf2",
    "mf3",
    "mf4",
    "mf5",
    "mf6",
    "mf7",
    "mf8",
    "mf9",
    "mfA",
    "mfB",
    "mfC",
    "mfD",
    "mfE",
    "mfF",
    "mfG",
    "mfH",
    "mfH1",
    "mfI",
    "mfJ",
    "mfK",
    "mfL",
    "mfM",
    "mfN",
    "mfO",
    "mfP",
    "mfR",
    "mfS",
    "mfT",
    "mfV",
    "minus1",
    "mirror",
    "Monitor",
    "msg",
    "msgs",
    "multi",
    "name",
    "no",
    "node",
    "nofold",
    "none",
    "normal",
    "Normalize",
    "ns",
    "null",
    "Null",
    "NumAllocations",
    "NumAllocationScans",
    "NumAtmostTriggered",
    "NumDiskAccepted",
    "NumDiskRowsRead",
    "NumDiskSeeks",
    "NumGroupMax",
    "NumGroups",
    "NumIndexAccepted",
    "NumIndexMerges",
    "NumIndexNullSkips",
    "NumIndexRejected",
    "NumIndexRowsRead",
    "NumIndexScans",
    "NumIndexSeeks",
    "NumIndexSkips",
    "NumIndexWildSeeks",
    "NumLeafCacheAdds",
    "NumLeafCacheHits",
    "NumNodeCacheAdds",
    "NumNodeCacheHits",
    "numrecs",
    "_numResults",
    "NumRowsProcessed",
    "NumStarted",
    "NumStopped",
    "Nway Graph Input",
    "once",
    "one",
    "one_per_node",
    "OnWarning",
    "OnWarnings",
    "options",
    "Options",
    "ordered",
    "OriginalTextFilesEclPath",
    "OriginalTextFilesIp",
    "OriginalTextFilesOsPath",
    "OrigName",
    "OthersWorkunitsAccess",
    "ou=EclDirectAccess,ou=EspServices,ou=ecl",
    "ou=EspServices,ou=ecl",
    "ou=SMC,ou=EspServices,ou=ecl",
    "outfile",
    "ou=workunits,ou=ecl",
    "ou=WsEcl,ou=EspServices,ou=ecl",
    "OwnWorkunitsAccess",
    "p",
    "p1",
    "p2",
    "parallel",
    "Parameters",
    "_parentActivity",
    "Parse",
    "PARSELIB 1.0.1",
    "Part",
    "partial",
    "Parts",
    "passdfstoeclcc",
    "passDFSToEclcc",
    "peeps",
    "Peeps",
    "/PersistRunLocks[1]",
    "persons",
    "pickbestengine",
    "Pid",
    "Pipe Through",
    "pluck1",
    "Plugin",
    "PluginProcess",
    "Plugins",
    "plugin.xsd",
    "predictedCount",
    "preload",
    "privatekey.cer",
    "Process",
    "progress",
    "Progress",
    "Project",
    "Quantile",
    "query",
    "Query",
    "Queue",
    "queued",
    "Read",
    "Read Local Result",
    "realfive",
    "realfour",
    "realone",
    "realthree",
    "realtwo",
    "_record_layout",
    "recordSize",
    "Recovery",
    "Relationship",
    "Relationships",
    "reqd",
    "resistorcodes",
    "Resource limit spill: Heavyweight (2>1)",
    "result",
    "Result",
    "Results",
    "rhs",
    "RIGHT",
    "ro1",
    "rolledup",
    "Root access to ECL Direct service",
    "Root access to SMC service",
    "Root access to WS ECL service",
    "Root access to WS Logging service",
    "rootGraph",
    "Row",
    "rowCount",
    "roxie",
    "Roxie",
    "Roxie cluster",
    "RoxieCluster",
    "RoxieControlAccess",
    "roxie_deploy_map.xml",
    "roxie_echo",
    "roxie_echo.1",
    "roxie_echo.2",
    "roxie.eclserver",
    "roxie_keepwhitespace",
    "roxie_keepwhitespace.1",
    "roxie_keepwhitespace.2",
    "roxie.roxie",
    "roxie.roxie,thor_roxie.roxie",
    "RoxieServer",
    "roxie.xsd",
    "run",
    "running",
    "Running",
    "s",
    "s1",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "Sample",
    "sasha",
    "SashaServer",
    "Sasha Server process",
    "SashaServerProcess",
    "sasha.xsd",
    "Schedule",
    "SchemaRaw",
    "Scope",
    "sd",
    "sdg_indexfileevens",
    "sdg_varindex",
    "sds",
    "SDS_Initialize",
    "section",
    "seed100",
    "Select Nth",
    "Self Join",
    "sequential",
    "Sequential",
    "Server",
    "ServerList",
    "setup",
    "ShortText",
    "signedBy",
    "single",
    "SiteCertificate",
    "SiteCertificate.xsd",
    "SizePeakMemory",
    "Skip Limit",
    "sld",
    "slda",
    "sli",
    "slr",
    "sls",
    "smart",
    "SmcAccess",
    "soapbase",
    "soapbase.1",
    "soapbase.2",
    "soapplus",
    "SoapPlusProcess",
    "soapplus.xsd",
    "somefile",
    "Sort",
    "sortedids",
    "sortfixed",
    "sortvar",
    "Source",
    "_sourceActivity",
    "_sourceIndex",
    "spill1",
    "spillReason",
    "Split",
    "sq",
    "started",
    "State",
    "Statistic",
    "Statistics",
    "Stats",
    "/Status[1]/Servers[1]",
    "/Status[1]/Servers[1]/Server[10]",
    "/Status[1]/Servers[1]/Server[11]",
    "/Status[1]/Servers[1]/Server[12]",
    "/Status[1]/Servers[1]/Server[13]",
    "/Status[1]/Servers[1]/Server[14]",
    "/Status[1]/Servers[1]/Server[15]",
    "/Status[1]/Servers[1]/Server[16]",
    "/Status[1]/Servers[1]/Server[17]",
    "/Status[1]/Servers[1]/Server[5]",
    "/Status[1]/Servers[1]/Server[7]",
    "/Status[1]/Servers[1]/Server[8]",
    "/Status[1]/Servers[1]/Server[9]",
    "std",
    "std.system",
    "storedtrue",
    "storedvar",
    "str",
    "Str",
    "STRINGLIB 1.1.14",
    "stripprefixlist",
    "Subfile",
    "SubFile",
    "subgraph",
    "submitted",
    "success",
    "summary",
    "SuperFile",
    "SuperOwner",
    "supplied",
    "Switch",
    "sz",
    "_targetActivity",
    "targetclustertype",
    "_targetIndex",
    "targetip",
    "@temp",
    "temp",
    "@temp/esp_service.xsl",
    "templ",
    "Temporaries",
    "temporary",
    "tempr",
    "temps",
    "Text",
    "textsearch",
    "TextSearch",
    "tf01",
    "tf37",
    "tf75",
    "tf76",
    "tf79",
    "tf91",
    "tfB8",
    "tfF6",
    "tfF8",
    "tfFB",
    "tfJ4",
    "tfN7",
    "tfNA",
    "tfR5",
    "tfV6",
    "tfV8",
    "tfV9",
    "thor",
    "Thor",
    "thorlib",
    "Thorlib",
    "ThorMaster",
    "Thor process",
    "ThorQueueAccess",
    "thor_roxie",
    "thor_roxie.eclserver",
    "thor_roxie.roxie",
    "thor_roxie.thor",
    "thor.thor",
    "thor.thor,thor_roxie.thor",
    "thorversion",
    "thor.xsd",
    "three",
    "TimeElapsed",
    "TimeLocalExecute",
    "TimeRemaining",
    "TimeSortElapsed",
    "topLevelKey",
    "Top N",
    "topology",
    "Topology",
    "topology.xsd",
    "Total cluster time",
    "totalRowCount",
    "Total thor time",
    "Tracing",
    "true",
    "True",
    "trueval",
    "truevalue",
    "truval",
    "ts",
    "TS",
    "tst",
    "two",
    "u1",
    "u2",
    "u3",
    "u4",
    "u5",
    "u6",
    "u7",
    "u8",
    "ucolor1",
    "ucolor2",
    "ucolor3",
    "ucolor4",
    "undefined",
    "UNICODELIB 1.1.06",
    "unknown",
    "_updateIfChanged",
    "updown",
    "US",
    "user",
    "utf8n",
    "Value",
    "Variable",
    "Variables",
    "view",
    "wait",
    "wf2",
    "wf6",
    "_when",
    "WhenCompiled",
    "WhenCreated",
    "WhenGraphFinished",
    "WhenGraphStarted",
    "WhenQueryFinished",
    "WhenQueryStarted",
    "WhenWorkunitModified",
    "Windows",
    "word",
    "wordindex",
    "word{set(stringlib.StringToLowerCase,stringlib.StringFilterOut('AEIOU$?.:;,()'))}",
    "word{set(unicodelib.UnicodeToLowerCase)}",
    "Workflow",
    "workunit",
    "WorkUnit",
    "Workunit DLL",
    "workunit:optimize graph",
    "workunit:resource graph",
    "/WorkUnitRunLocks[1]",
    "/WorkUnits[1]",
    "/WorkUnits[1]/global[1]",
    "WORKUNITSERVICES 1.0.2",
    "workunit:tree transform: optimize disk read",
    "ws_access",
    "ws_dfu",
    "ws_dfuxref",
    "ws_ecl",
    "WsEclAccess",
    "WS ECL Service",
    "ws_eclSoapBinding",
    "ws_esdlconfig",
    "ws_fileio",
    "ws_fs",
    "wslogging",
    "WsLoggingAccess",
    "wslogging.xsd",
    "ws_machine",
    "ws_smc",
    "WsSMC",
    "ws_topology",
    "ws_workunits",
    "x",
    "xgmml",
    "xml",
    "xmlValue",
    "xslt",
    "Yes",
    "zero",
