    "/dev*,/sys,/proc/*",
    ">compile",
    ">compile:>compile c++",
    ">compile:>compile c++:link",
    ">compile:>generate",
    ">compile:>generate:>write c++",
    ">compile:>parse",
    ">compile:>parse:>download",
    ">compile:>resource graph",
    ">compile:>transform",
    ">compile:>transform:>peephole",
    ">compile:>transform:>pick engine",
    "@temp/esp_service.xsl",
    "__filepos",
    "__fileposition__",
    "_childGraph",
    "_dependsOn",
    "_diskAccessRequired",
    "_fileName",
    "_fromChild",
    "_globalUsageCount",
    "_graphid",
    "_graphId",
    "_graphIndependent",
    "_indexFileName",
    "_internal",
    "_isSpill",
    "_isTransformSpill",
    "_libraryGraphId",
    "_loopid",
    "_numResults",
    "_parentActivity",
    "_record_layout",
    "_remoteSubGraph",
    "_rtlType",
    "_sourceActivity",
    "_sourceIndex",
    "_targetActivity",
    "_targetIndex",
    "_updateIfChanged",
    "Access to cluster topology",
    "Access to deploy workunits",
    "Access to despraying of files",
    "Access to DFU",
    "Access to DFU exceptions",
    "Access to DFU workunits",
    "Access to DFU XRef",
    "Access to ECL direct service",
    "Access to ECL Direct service",
    "Access to ESDL configuration service",
    "Access to files in dropzone",
    "Access to machine information",
    "Access to own workunits",
    "Access to permissions for file scopes",
    "Access to roxie control commands",
    "Access to SMC service",
    "Access to SNMP metrics information",
    "Access to spraying files",
    "Access to thor queues",
    "Access to upload files to dropzone",
    "Access to workunits owned by others",
    "Access to WS ECL service",
    "Access to WS Logging service",
    "Action #1",
    "Action #2",
    "activities",
    "Aggregate",
    "Application",
    "archive",
    "Associated",
    "Begin Loop",
    "blocked",
    "calculated",
    "canstall",
    "certificate.cer",
    "checkasserts",
    "Child Dataset",
    "childfile",
    "Cluster",
    "ClusterLock",
    "ClusterTopologyAccess",
    "coLocal",
    "compile",
    "compile:>compile c++",
    "compile:>generate",
    "compile:>generate:>write c++",
    "compile:>parse",
    "compile:>parse:>download",
    "compile:>resource graph",
    "compile:>transform",
    "compile:>transform:>peephole",
    "compile:>transform:>pick engine",
    "compiled",
    "Compiler log",
    "compiling",
    "completed",
    "componentfiles/configxml",
    "componentfiles/dafilesrv",
    "componentfiles/dali",
    "componentfiles/dfuplus",
    "componentfiles/dfuserver",
    "componentfiles/DropZone",
    "componentfiles/eclagent",
    "componentfiles/eclminus",
    "componentfiles/eclplus",
    "componentfiles/esdlsvcengine",
    "componentfiles/esp",
    "componentfiles/esploggingagent",
    "componentfiles/espsmc",
    "componentfiles/ftslave",
    "componentfiles/hqltest",
    "componentfiles/ldapServer",
    "componentfiles/loggingmanager",
    "componentfiles/sasha",
    "componentfiles/SiteCertificate",
    "componentfiles/soapplus",
    "componentfiles/thor",
    "componentfiles/topology",
    "componentfiles/ws_ecl",
    "componentfiles/wslogging",
    "condition",
    "CostCompile",
    "CostExecute",
    "CostFileAccess",
    "Count Project",
    "created_by",
    "created_for",
    "Csv Write",
    "dafilesrv",
    "DaFileSrv process",
    "dafilesrv.xsd",
    "DafilesrvProcess",
    "dali.xsd",
    "DaliServerProcess",
    "definition",
    "Degroup",
    "Denormalize",
    "Denormalize Group",
    "Dependency",
    "deploy_map.xml",
    "DeployWorkunitsAccess",
    "deserialized",
    "destClusterName",
    "Destination",
    "DFU Server",
    "DfuAccess",
    "DFUcopy",
    "DfuExceptions",
    "DfuExceptionsAccess",
    "dfuplus",
    "dfuplus.xsd",
    "DfuplusProcess",
    "dfuserver",
    "DFUserver",
    "dfuserver.xsd",
    "dfuserver_monitor_queue",
    "dfuserver_queue",
    "DfuServerProcess",
    "DfuWorkunitsAccess",
    "DfuXrefAccess",
    "Disk Write",
    "DiskUsageStats",
    "DropZone",
    "DropZone process",
    "dropzone.xsd",
    "dropzoneIp",
    "dropzonePath",
    "DynamicESDL",
    "ecl.common",
    "eclagent",
    "EclAgent",
    "ECLagent",
    "EclAgent process",
    "eclagent_config.xsd",
    "EclAgentBuild",
    "EclAgentProcess",
    "eclccserver",
    "ECLCCserver",
    "EclCCServer process",
    "eclccserver.xsd",
    "eclccserver_deploy_map.xml",
    "EclCCServerProcess",
    "eclminus",
    "eclplus",
    "eclplus.xsd",
    "EclPlusProcess",
    "eclscheduler",
    "EclScheduler process",
    "eclscheduler.xsd",
    "eclscheduler_deploy_map.xml",
    "EclSchedulerProcess",
    "EclWatch",
    "Edition",
    "End Loop",
    "Environment_Initialize",
    "esdl_svc_engine",
    "EsdlBinding",
    "ESDLConfigAccess",
    "esdlsvcengine.xsd",
    "ESP server",
    "ESP services for SMC",
    "esp.xsd",
    "esp_service_module",
    "esp_service_wsecl2.xsd",
    "espFileSprayUrl",
    "esploggingagent",
    "ESPLoggingAgent",
    "esploggingagent.xsd",
    "EspProcess",
    "ESPserver",
    "EspService",
    "ESPservice",
    "espsmcservice.xsd",
    "Exception",
    "Exceptions",
    "expandpersistinputdependencies",
    "fAddFileRelationship",
    "fAddSuperFile",
    "failonleaks",
    "failure",
    "falseval",
    "fCreateSuperFile",
    "fDeleteLogicalFile",
    "fDeleteSuperFile",
    "fFileExists",
    "fFinishSuperFileTransaction",
    "fgetParseTree",
    "fGetSuperFileSubCount",
    "FileDesprayAccess",
    "FileIOAccess",
    "filepos",
    "FileScopeAccess",
    "fileservices",
    "FileSprayAccess",
    "FilesRead",
    "FileUploadAccess",
    "Filtered Project",
    "finished",
    "fRemoveSuperFile",
    "fSetColumnMapping",
    "fStartSuperFileTransaction",
    "fSuperFileExists",
    "ftslave",
    "FTSlave process",
    "ftslave_linux.xsd",
    "FTSlaveProcess",
    "function",
    "graphBin",
    "grouped",
    "Grouped Aggregate",
    "Grouped Dedup",
    "Grouped Filter",
    "Grouped Iterate",
    "Grouped Normalize",
    "Grouped Process",
    "Grouped Project",
    "Grouped Rollup",
    "Grouped Sort",
    "Grouped Split",
    "Hash Aggregate",
    "Hash Dedup",
    "Hash Distribute",
    "HPCCSystems",
    "hqltest",
    "HqlTestProcess",
    "HThorServer",
    "http://www.w3.org/1999/XMLSchema-instance",
    "Index Write",
    "initial",
    "Inline Dataset",
    "Inline Row",
    "Iterate",
    "jobtemp",
    "kerberos",
    "layouttranslationenabled",
    "ldapServer",
    "ldapserver.xsd",
    "LDAPServerProcess",
    "lib_fileservices",
    "lib_parselib",
    "lib_stringlib",
    "lib_unicodelib",
    "libfileservices.so",
    "libparselib.so",
    "libstringlib.so",
    "libunicodelib.so",
    "libworkunitservices.so",
    "Lightweight Self Join",
    "linuxmachine",
    "Local Dedup",
    "Local Group",
    "Local Index Write",
    "Local Join",
    "Local Result",
    "Local Sort",
    "Local Sorted",
    "localdomain",
    "localhost",
    "location",
    "loggingmanager",
    "LoggingManager",
    "loggingmanager.xsd",
    "loggingservice_binding",
    "logicalName",
    "Lookup Join",
    "lookupjoin",
    "MachineInfoAccess",
    "makechildren",
    "makedataset",
    "matches",
    "MatchSmith",
    "maxcompilethreads",
    "maxCompileThreads",
    "maxseeklookahead",
    "Merge Join",
    "MetricsAccess",
    "Monitor",
    "Normalize",
    "NumAllocations",
    "NumAllocationScans",
    "NumAtmostTriggered",
    "NumContextSwitches",
    "NumDiskAccepted",
    "NumDiskRowsRead",
    "NumDiskSeeks",
    "NumDuplicateKeys",
    "NumGroupMax",
    "NumGroups",
    "NumIndexAccepted",
    "NumIndexMerges",
    "NumIndexNullSkips",
    "NumIndexRejected",
    "NumIndexRowsRead",
    "NumIndexScans",
    "NumIndexSeeks",
    "NumIndexSkips",
    "NumIndexWildSeeks",
    "NumLeafCacheAdds",
    "NumLeafCacheHits",
    "NumNodeCacheAdds",
    "NumNodeCacheHits",
    "numrecs",
    "NumRowsProcessed",
    "NumStarted",
    "NumStopped",
    "NumSysContextSwitches",
    "Nway Graph Input",
    "OnWarning",
    "OnWarnings",
    "operation",
    "options",
    "Options",
    "ordered",
    "OriginalTextFilesEclPath",
    "OriginalTextFilesIp",
    "OriginalTextFilesOsPath",
    "OrigName",
    "OthersWorkunitsAccess",
    "ou=EspServices,ou=ecl",
    "ou=SMC,ou=EspServices,ou=ecl",
    "ou=workunits,ou=ecl",
    "ou=WsEcl,ou=EspServices,ou=ecl",
    "OwnWorkunitsAccess",
    "PackageMapAccess",
    "parallel",
    "Parameters",
    "partial",
    "Pipe Through",
    "plugin.xsd",
    "PluginProcess",
    "Plugins",
    "predictedCount",
    "preload",
    "privatekey.cer",
    "Process",
    "progress",
    "Progress",
    "Project",
    "Quantile",
    "Read Local Result",
    "recordSize",
    "Recovery",
    "Relationship",
    "Relationships",
    "Results",
    "rolledup",
    "Root access to ECL Direct service",
    "Root access to SMC service",
    "Root access to WS ECL service",
    "Root access to WS Logging service",
    "rootGraph",
    "rowCount",
    "Roxie cluster",
    "roxie.xsd",
    "roxie_deploy_map.xml",
    "RoxieCluster",
    "RoxieControlAccess",
    "RoxieServer",
    "running",
    "Running",
    "Sasha Server process",
    "sasha.xsd",
    "SashaServer",
    "SashaServerProcess",
    "Schedule",
    "SchemaRaw",
    "SDS_Initialize",
    "section",
    "Select Nth",
    "Self Join",
    "sequential",
    "Sequential",
    "ServerList",
    "ShortText",
    "SiteCertificate",
    "SiteCertificate.xsd",
    "SizeMemory",
    "SizePeakMemory",
    "SizePeakRowMemory",
    "Skip Limit",
    "SmcAccess",
    "soapplus",
    "soapplus.xsd",
    "SoapPlusProcess",
    "somefile",
    "sortedids",
    "sortfixed",
    "sortvar",
    "spillReason",
    "started",
    "Statistic",
    "Statistics",
    "std.system",
    "stripprefixlist",
    "Subfile",
    "SubFile",
    "subgraph",
    "submitted",
    "success",
    "summary",
    "SuperFile",
    "SuperOwner",
    "supplied",
    "targetclustertype",
    "targetip",
    "Temporaries",
    "temporary",
    "textsearch",
    "TextSearch",
    "Thor process",
    "thor.xsd",
    "thorlib",
    "Thorlib",
    "ThorMaster",
    "ThorQueueAccess",
    "thorversion",
    "TimeAgentWait",
    "TimeBlocked",
    "TimeElapsed",
    "TimeLocalExecute",
    "TimeOsSystem",
    "TimeOsTotal",
    "TimeOsUser",
    "TimeRemaining",
    "TimeSortElapsed",
    "TimeSystem",
    "TimeTotalExecute",
    "TimeUser",
    "topLevelKey",
    "topology",
    "Topology",
    "topology.xsd",
    "Total cluster time",
    "Total thor time",
    "totalRowCount",
    "Tracing",
    "undefined",
    "unknown",
    "Variable",
    "Variables",
    "WhenCompiled",
    "WhenCreated",
    "WhenDequeued",
    "WhenFinished",
    "WhenFirstRow",
    "WhenGraphFinished",
    "WhenGraphStarted",
    "WhenQueryFinished",
    "WhenQueryStarted",
    "WhenQueued",
    "WhenStarted",
    "WhenWorkunitModified",
    "Windows",
    "Workflow",
    "workflow",
    "workunit",
    "WorkUnit",
    "Workunit DLL",
    "workunit:optimize graph",
    "workunit:resource graph",
    "workunit:tree transform: optimize disk read",
    "WS ECL Service",
    "ws_access",
    "ws_dfuxref",
    "ws_eclSoapBinding",
    "ws_esdlconfig",
    "ws_fileio",
    "ws_machine",
    "ws_topology",
    "ws_workunits",
    "WsEclAccess",
    "wslogging",
    "wslogging.xsd",
    "WsLoggingAccess",
    "xmlValue",
