export = {
    Abort: "Прекините",
    AbortedBy: "Прекинуто од стране",
    AbortedTime: "време прекида",
    AbortSelectedWorkunits: "Желите да зауставите изабране радне јединице? Ваш ИД за пријаву ће бити забележен за ову радњу у оквиру изабраних радних јединица.",
    About: "О Апликацији",
    AboutGraphControl: "О Графичкој Контроли",
    AboutHPCCSystems: "О ХПЦЦ Системс®-у",
    AboutHPCCSystemsGraphControl: "О Графичкој Контроли ХПЦЦ Система",
    AboutToLoseSessionInformation: "Ако се одјавите, изгубићете све информације о сесији. Да ли желите да наставите?",
    Account: "Рачун",
    AccountDisabled: "Налог је онемогућен. Обратите се администратору система.",
    Action: "Акција",
    Activate: "Активирајте",
    Activated: "Активиран",
    ActivateQuery: "Активирајте упит",
    ActivateQueryDeletePrevious: "Активирајте упит и избришите претходни",
    ActivateQuerySuspendPrevious: "Активирајте упит, суспендујте претходни",
    Active: "Активан",
    ActivePackageMap: "Активна Мапа Пакета",
    ActiveWorkunit: "Активна Радна Јединица",
    Activities: "Активности",
    Activity: "Активност",
    ActivityLabel: "Ознака активности",
    ActivityMap: "Mапа Активности",
    ActualSize: "Тачна Величина",
    Add: "Додајте",
    AddAttributes: "Додајте атрибуте / вредности вашем методу",
    AddAttributes2: "Додајте Атрибут(е)",
    AddBinding: "Додајте Везивање",
    AddFile: "Додајте Датотеку",
    AddGroup: "Додајте Групу",
    AdditionalResources: "Додатни Ресурси",
    AddPart: "Додајте део",
    AddProcessMap: "Додајте Мапу Пакета",
    AddResource: "Додај ресурс",
    AddTheseFilesToDali: "Додајте Те Датотеке на Дали",
    AddtionalProcessesToFilter: "Додатни Процеси За Филтрирање",
    AddToExistingSuperfile: "Додајте на постојећи суперфајл",
    AddToFavorites: "Додај у фаворите",
    AddToSuperfile: "Додајте на Супердатотеку",
    AddUser: "Додајте Корисника",
    Advanced: "Вишег Нивоа",
    Age: "Старост",
    All: "Сви",
    AllowAccess: "Дозволите Приступ",
    AllowForeignFiles: "Дозволите Кориштење  Датотека Са Других Кластера",
    AllowFull: "Дозволите Потпун",
    AllowRead: "Дозволите Читање",
    AllowWrite: "Дозволите Писање",
    AllQueries: "Сви упити",
    AllQueuedItemsCleared: "Сви послови из реда чекања су очишћени. Тренутно активни посао наставња са извршавањем.",
    Analyze: "Анализирај",
    ANY: "Било Који",
    AnyAdditionalProcessesToFilter: "Има ли још процеса за филтрирање",
    Append: "Додајте",
    AppendCluster: "Додајте Кластер",
    Apply: "Примените",
    Apps: "Апликације",
    ArchiveDFUWorkunit: "Архивирај ДФУ радну јединицу",
    ArchivedOnly: "Само Архивиран",
    ArchivedWarning: "Упозорење: користите кратак временски период. Ако користите дужи временски период, претраживање радних јединица може трајати дуже од дозвиљеног времена за претраживање.",
    ArchiveECLWorkunit: "Архивирај ЕЦЛ радну јединицу",
    AreYouSureYouWantToResetTheme: "Јесте ли сигурни да се желите вратити на задану тему",
    Attach: "Причврстите",
    Attribute: "Атрибут",
    AttributesAreRequired: "Атрибути су потребни",
    Audience: "Публика",
    Audit: "Провера",
    AuditLogs: "Дневник за ревизију",
    AutoRefresh: "Освежи",
    AutoRefreshEvery: "Аутоматско освеживање сваких к минута",
    AutoRefreshIncrement: "Аутоматски корак освежавања",
    Back: "Назад",
    BackupDFUWorkunit: "Резервна ДФУ радна јединица",
    BackupECLWorkunit: "Резервна ЕЦЛ радна јединица", 
    BannerColor: "Боја Рекламног Блока",
    BannerColorTooltip: "Промените боју позадине горње навигације",
    BannerMessage: "Порука за Рекламни Блок",
    BannerMessageTooltip: "Промените наслов приказан у горњој навигацији",
    BannerScroll: "Кретање Рекламног Блока",
    BannerSize: "Величина Рекламног Блока",
    BinaryInstalls: "Бинарне Инсталације",
    Bind: "Вежите",
    Binding: "Везивање",
    BindingDeleted: "Везивање Избрисанo",
    Blob: "БЛОБ",
    BlobPrefix: "БЛОБ Префикс",
    Blobs: "БЛОБс",
    Blooms: "Блумс",
    Bottom: "Крај",
    BoundBy: "ограничено од:",
    Branches: "Филијале",
    BrowserStats: "Статистика Прегледача",
    BuildDate: "Датум изградње",
    Busy: "заузет",
    CallerID: "ИД позиваоца",
    Cancel: "Поништите",
    CancelAll: "Укините Све",
    CancelAllMessage: "Прекините текуће послове и очистите ред чекања. Желите ли наставити?",
    Category: "Категорија",
    Channel: "Канал",
    Chart: "дијаграм",
    CheckAllNodes: "Проверите све чворове",
    CheckFilePermissions: "Проверите дозволе за приступ филу",
    CheckSingleNode: "Проверите Један НОД",
    Class: "Класа",
    Clear: "Очистите",
    ClearPermissionsCache: "Избришите Запамћене Дозволе За Приступ",
    ClearPermissionsCacheConfirm: "Да ли сте сигурни да желите да избришете запамћене дозволе за приступ на ДАЛИ и ЕСП? То може значајно успорити извршавање радних јединица.",
    Client: "Клијент",
    Clone: "Клонирајте",
    ClonedWUID: "Клонирани WУИД",
    CloneTooltip: "Копирање радне јединице",
    Close: "Затворите",
    CloseModal: "Затвори модал",
    Cluster: "Кластер",
    ClusterName: "Име Кластера",
    ClusterPH: "r?x*",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Процеси На Кластеру",
    Code: "Код",
    CodeGenerator: "Код Генератор",
    Col: "Колона",
    CollapseAll: "Сузите све",
    ColumnMode: "Режим колоне",
    Columns: "Колоне",
    Command: "Команда",
    Comment: "Коментар",
    Compilation: "Компилација",
    CompileCost: "Трошкови компилације",
    Compiled: "Компајлирано",
    Compiling: "У процесу компајлирања",
    Completed: "Комплетиран",
    ComplexityWarning: "Више од прага {threshold} активности ({activityCount}) - прекините приказ података?",
    Component: "Компонента",
    ComponentLogs: "Дневник компонената",
    Components: "Компоненте",
    Compress: "Сабијте",
    Compressed: "Компримирани",
    CompressedFileSize: "Компримирана Величина Датотеке",
    CompressedSize: "Компримована величина",
    Compression: "Компресија",
    ComputerUpTime: "Време рачунара",
    Condition: "услов",
    Configuration: "Конфигурација",
    ConfigureService: "Сервис за Конфигурацију",
    ConfirmPassword: "Потврдите Лозинку",
    ConfirmRemoval: "Јесте ли сигурни да то желите учинити?",
    ConnectionID: "Идентификатор везе",
    ContactAdmin: "Ако желите променити назив ове групе, контактирајте администратора ЛДАП.",
    Container: "Контејнер",
    ContainerName: "Назив контејнера",
    Content: "Садржај",
    Contents: "Садржаји",
    ContentType: "Врста Садржаја",
    ContinueWorking: "Наставите са радом",
    Cookies: "Колачићи",
    CookiesAcceptButtonText: "Дозволи колачиће",
    CookiesNoticeLinkText: "Наше обавештење о колачићима",
    Copied: "Копирано!",
    Copy: "Копирајте",
    CopyLogicalFilename: "Копирај назив логичке датотеке",
    CopyLogicalFiles: "Копирајте логичке фајлове у клипборд",
    CopyOpenTelemetry: "Копирај отворену телеметрију",
    CopySelectionToClipboard: "Копирај избор у привремену меморију",
    CopyToClipboard: "Копирај у клипборд",
    CopyURLToClipboard: "Копирај УРЛ у клипборд",
    CopyWUID: "Копирајте ВУИД",
    CopyWUIDs: "Копирај ВУИД-ове у клипборд",
    CopyWUIDToClipboard: "Копирај ВУИД у клипборд",
    Cost: "Цена",
    Costs: "Цене",
    Count: "Избројте",
    CountFailed: "Бројање није успело",
    CountTotal: "Укупно броји",
    CPULoad: "Учитавање процесора",
    Create: "Креирај",
    CreateANewFile: "Креирајте нови суперфајл",
    Created: "Произведен",
    CreatedBy: "Аутор",
    CreatedByWorkunit: "Направљено радном јединицом",
    CreatedTime: "Време стварања",
    Creating: "У процесу креирањa",
    Critical: "Критично",
    CrossTab: "Kрос Таб",
    CSV: "ЦСВ",
    CustomLogColumns: "Колоне за специјализоване уносе",
    Dali: "Дали",
    DaliAdmin: "Дали Администратор",
    DaliIP: "Дали ИП адресa",
    DaliPromptConfirm: "Да ли сте сигурни? Дали администраторске пријаве су трајне и не могу се опозвати.",
    Dashboard: "Командна табла",
    Data: "Подаци",
    DataPatterns: "Узорци података",
    DataPatternsDefnNotFound: "Дефиниција фајлa није пронађена. Узорци података се не могу анализирати",
    DataPatternsNotStarted: "Резултати анализе нису пронађени. Да бисте започели нову анализу, притисните дугме Анализа.",
    DataPatternsStarted: "Анализа је у току. Када заврши, овде ће бити приказан цео извештај.",
    dataset: ":=датасет*",
    Date: "Датум",
    Day: "Дан",
    Deactivate: "Искљућите",
    Debug: "Отклоните Неисправности",
    DEF: "ДЕФ",
    Default: "Подразумевано",
    Defaults: "Унапред Дефинисане Вредности",
    Definition: "Дефиниција",
    DefinitionDeleted: "Дефиниција је избрисана",
    DefinitionID: "ИД",
    Definitions: "Дефиниције",
    DelayedReplication: "Одложена репликација",
    Delete: "Обришите",
    DeleteBinding: "Избришите Везивање",
    Deleted: "Избрисан",
    DeletedBinding: "Избрисано Везивање",
    DeleteDirectories: "Елиминишите празан директириј. Желите ли наставити?",
    DeleteEmptyDirectories: "Желите ли избрисати празне директорије?",
    DeletePrevious: "Избришите Претходни",
    DeleteSelectedDefinitions: "Обришите изабране дефиниције?",
    DeleteSelectedFiles: "Обришите Одабране Датотеке?",
    DeleteSelectedGroups: "Обришите одабрану(е) групу(е)?",
    DeleteSelectedPackages: "Желите ли да избришете изабране пакете?",
    DeleteSelectedPermissions: "Обришите Одабране Дозволе За Приступ",
    DeleteSelectedQueries: "Обришите Одабране Захтјеве?",
    DeleteSelectedUsers: "Обришите Одабране Кориснике?",
    DeleteSelectedWorkunits: "Обришите Одабране Радне Јединице?",
    DeleteSuperfile: "Обришите Супердатотеке?",
    DeleteSuperfile2: "Избришите Супер Датотеку",
    DeleteThisPackage: "Обришите Овај Пакет?",
    Delimited: "Разграничен",
    DenyAccess: "Забраните Приступ",
    DenyFull: "Забраните Потпун",
    DenyRead: "Забраните Читање",
    DenyWrite: "Забраните Писање",
    Depth: "Дубина",
    DepthTooltip: "&lsquo;Највећа Дубина Подграфа",
    Deschedule: "Избаците Ис Реда За Извршавање",
    DescheduleSelectedWorkunits: "Избаците Одабране Радне Јединице Из Реда За Извршавање?",
    Description: "Опис",
    DESDL: "Динамички ЕСДЛ",
    Despray: "Поново Обjедините Датотеку",
    Details: "Детаљи",
    DFSCheck: "ДФС провера",
    DFSExists: "ДФС постоји",
    DFSLS: "ДФС ЛС",
    DFUServerName: "Име ДФУ Сервера",
    DFUWorkunit: "ДФУ РаднаЈединицa",
    Directories: "директорије",
    Directory: "Директориј",
    DisableScopeScanConfirm: "Да ли сте сигурни да желите онемогућити сканирање опсега? Промене ће бити прихваћене после рестарта ДАЛИја",
    DisableScopeScans: "Онемогућите Сканирање Опсега",
    DiskSize: "Величина диска",
    DiskUsage: "Искориштеност Диска",
    Distance: "Раздаљина",
    DistanceTooltip: "Максимална Величина Подграфа За Одабрану Активност",
    Dll: "Длл",
    Documentation: "Документација",
    Domain: "Домен",
    DoNotActivateQuery: "Не активирајте упит",
    DoNotRepublish: "Не објављујте?",
    DOT: "ДОТ",
    DOTAttributes: "ДОТ Атрибути",
    Down: "Неактиван",
    Download: "Добавите",
    Downloads: "Преузимање",
    DownloadSelectionAsCSV: "Преузми избор као ЦСВ",
    DownloadToCSV: "Преузмите у ЦСВ формату",
    DownloadToCSVNonFlatWarning: "Напомена: преузимање датотека које садрже угнежђене скупове података као податке раздвојене зарезима можда неће бити форматирано како је очекивано",
    DownloadToDOT: "Преузми на ДОТ",
    DropZone: "Зона Пријема",
    DueToInctivity: "Бићете одјављени из свих ЕЦЛ Вач сесија за 3 минута због неактивности.",
    Duration: "Трајање",
    DynamicNoServicesFound: "Сервиси Нису Пронађени",
    EBCDIC: "ЕБЦДИK",
    ECL: "ЕЦЛ",
    ECLWatchRequiresCookies: "ЕЦЛ Вач захтијева да колачићи буду омогућени за наставак",
    ECLWatchSessionManagement: "Управљање ЕЦЛ  Вачом",
    ECLWatchVersion: "ЕЦЛ Ватцх верзија",
    ECLWorkunit: "ЕЦЛ РаднаЈединица",
    EdgeLabel: "Ознака ивице",
    Edges: "Ивице",
    Edit: "Едитујте",
    EditDOT: "Едитујте ДОТ",
    EditGraphAttributes: "Едитујте Атрибуте Графова",
    EditXGMML: "Едитујте XГММЛ",
    EmailBody: "Садржај е-поште",
    EmailFrom: "Адреса е-поште (пошиљалац)",
    EmailSubject: "Предмет е-поште",
    EmailTo: "Адреса е-поште (прималац)",
    EmployeeID: "ИД Радника",
    EmployeeNumber: "Број радника",
    Empty: "(Празан)",
    Enable: "Омогућите",
    EnableBannerText: "Активирај текст",
    EnableScopeScans: "Омогућите Сканирање Опсега",
    EnableScopeScansConfirm: "Да ли сте сигурни да желите омогућити сканирање опсега? Промене ће бити прихваћене после рестарта ДАЛИја",
    EndPoint: "Крајња тачка",
    EndTime: "Време завршетка",
    EnglishQ: "Енглески?",
    EnterAPercentage: "Унесите проценат",
    EnterAPercentageOrMB: "Унесите Проценат или МБ",
    EraseHistory: "Избришите историју",
    EraseHistoryQ: "Избришите Историју За",
    Error: "Грешка",
    Errorparsingserverresult: "Грешка у анализи резултата са сервера",
    Errors: "Грешкe",
    ErrorsStatus: "Грешкe/Стање",
    ErrorUploadingFile: "Грешка приликом преноса фајла(а). Покушајте провјерити дозволе за пренос",
    ErrorWarnings: "Грешка/Упозорења",
    Escape: "Ескејп",
    ESPBindings: "ЕСП везе",
    ESPBuildVersion: "ЕСП Тренутна Верзија",
    ESPNetworkAddress: "ЕСП Нетворк Адреса",
    ESPProcessName: "Назив ЕСП процеса",
    EventName: "Име Догађаја",
    EventNamePH: "имедогађаја",
    EventScheduler: "Распоређивач Догађаја",
    EventText: "Опис Догађаја",
    EventTextPH: "Текст О Догађају",
    Exception: "Неочекивани Проблем",
    ExcludeIndexes: "Изузми индексе",
    ExecuteCost: "Трошкови извршења",
    Executed: "Извршено",
    Executing: "У процесу извршавања",
    ExpandAll: "Проширите све",
    ExpirationDate: "Датум Истека",
    ExpireDays: "Истиче за (у данима)",
    Export: "Извезите",
    ExportSelectionsToList: "Извeзите Одабране Ствари у Листу",
    FactoryReset: "Фацтори Ресет",
    FailIfNoSourceFile: "Неуспех Уколико Датотека Не Постоји",
    Fatal: "фаталан",
    Favorites: "Фаворити",
    Fetched: "Преузет",
    FetchingData: "У Процесу Добављња Података...",
    fetchingresults: "добијени ресултати",
    FieldNames: "Имена колона",
    File: "Датотека",
    FileAccessCost: "Цена приступа фајлу",
    FileCluster: "Кластер Фајл",
    FileCostAtRest: "Цена фајлa у мировању",
    FileCounts: "Број Датотека",
    FileName: "Име Датотеке",
    FileParts: "Дио Датотеке",
    FilePath: "Локација Датотеке",
    FilePermission: "Дозвола за приступ фајлу",
    FilePermissionError: "Дошло је до грешке приликом приступа датотеци дозвола",
    Files: "Датотеке",
    FileScopeDefaultPermissions: "Предефинисанe дозволе за простор Фајлова",
    FileScopes: "Скоп Датотека",
    FileSize: "Величина Датотеке",
    FilesNoPackage: "Датотеке које не припадају пакету",
    FilesPending: "Датотеке у току",
    FilesWarning: "Број враћених датотека је превелики. Враћено је само првих 100.000 датотека сортираних по датуму / времену. Ако желите ограничити резултате, подесите филтер.",
    FilesWithUnknownSize: "Датотеке Са Непознатим Величинама",
    FileType: "Тип Датотеке",
    FileUploader: "Процес за премештање Датотеке на Сервер (Aплоyдер)",
    FileUploadStillInProgress: "Учитавање Датотека је у Току",
    Filter: "Филтер",
    FilterDetails: "Опис филтра",
    FilterMetricsTooltip: "Ово ће подразумевано филтрирати на основу колоне „Опсег“. Да бисте филтрирали било коју другу колону, користите назив колоне као префикс за претрагу, нпр.: „Име датотеке: проливање",
    FilterSet: "Дефинисање Филтерa",
    Find: "Нађите",
    FindNext: "Нађите Следећи",
    FindPrevious: "Нађите Претходни",
    Finished: "Завршен",
    FirstN: "Првих Н",
    FirstName: "Име",
    FirstNRows: "Првих Н Редова",
    FirstNSortBy: "Сортирајте по",
    Fixed: "Фиксни",
    Folder: "Фасцикла",
    Form: "Форма",
    Format: "Формат",
    Forums: "Форуми",
    Forward: "Напред",
    FoundFile: "Фајл Је Пронађен",
    FoundFileMessage: "Пронађени фајл има све своје делове на диску, или делови нису познати Дали серверу. Сви делови фајлa могу да бити додани назад на Дали серверу. Делови могу да бити и обрисани са kлaстерa aко је то потребно.",
    FromDate: "Од Датума",
    FromSizes: "Од Величине",
    FromTime: "Од Времена",
    FullName: "Име и Презиме",
    Generate: "Генеришите",
    GetDFSCSV: "ДФС ЦСВ",
    GetDFSMap: "ДФС Mапа",
    GetDFSParents: "ДФС Родитељи",
    GetLastServerMessage: "Преузми последњу поруку сервера",
    GetLogicalFile: "Логички Фајл",
    GetLogicalFilePart: "Део Логичке Датотеке",
    GetPart: "Добавите Део",
    GetProtectedList: "Заштићена Листа",
    GetSoftwareInformation: "Желите ли да добијетe информације о софтверу",
    GetValue: "Вредност",
    GetVersion: "Преузмите верзију",
    Graph: "Граф",
    GraphControl: "Контрола графика",
    Graphs: "Графикони",
    GraphView: "Слика Графикона",
    GridAbortMessage: "Мрежа поништава застарели захтев",
    Group: "Група",
    GroupBy: "Групишите По",
    GroupDetails: "Детаљи о Групи",
    Grouping: "Груписање",
    GroupName: "Назив Групе",
    GroupPermissions: "Дозволе за Приступ Групе",
    Groups: "Групе",
    GZip: "ГЗип",
    help: "Овdе је приказан графикон извршавања ове радне јединице. Величина и нијанса указују на време извршавања сваког графикона (Већи и тамнији графикон узима већи проценат cелокупног времена извршавања.)",
    Helper: "Помоћник",
    Helpers: "Помагаћи",
    Hex: "База16",
    HideSpills: "Сакријте записе на диск",
    High: "Висок",
    History: "Историја",
    Homepage: "Почетна страница",
    Hotspots: "Приступне Тачке Интернету",
    HPCCSystems: "ХПЦЦ Системс",
    HTML: "ХТМЛ",
    Icon: "Икона",
    ID: "Идентификатор",
    IFrameErrorMsg: "Подаци се не могу учитати, покушајте поново.",
    IgnoreGlobalStoreOutEdges: "Занемари глобалне ивице",
    Import: "Увоз",
    Inactive: "Неактиван",
    IncludePendingItems: "Укључи ставке на чекању",
    IncludePerComponentLogs: "Укључите записе по компоненти",
    IncludeRelatedLogs: "Укључите релевантне записе",
    IncludeSlaveLogs: "Укључите Извештаје Са Нодова Извршилаца",
    IncludeSubFileInfo: "Укључити информације о поддатотеци?",
    Index: "Индекс",
    Indexes: "Индекси",
    IndexesOnly: "Само индекси",
    Info: "Информација",
    InfoDialog: "Диалог Информације",
    Informational: "Информативно",
    Infos: "Подаци",
    InheritedPermissions: "Наслеђене Дозволе",
    Inputs: "Уноси",
    InUse: "У употреби",
    InvalidResponse: "(Неисправан Одговор)",
    InvalidUsernamePassword: "Неисправно корисничко име или лозинка, покушајте поново.",
    IP: "ИП",
    IPAddress: "ИП Адреса",
    IsCompressed: "Је ли Сабијен",
    IsLibrary: "Је Библиотека",
    IsReplicated: "Pеплициран",
    IssueReporting: "Извештавање о Проблемима",
    JobID: "ИД посла",
    JobName: "Назив Радне Јединице",
    Jobname: "Називраднејединице",
    jsmi: "јсми*",
    JSmith: "ЈСмит*",
    JSON: "ЈСОН",
    KeyFile: "Индексирани Фајл",
    KeyType: "Тип кључа",
    Label: "Етикета",
    LandingZone: "Зона за Претовар",
    LandingZones: "Зонe за Претовар",
    LanguageFiles: "Датотеке О Језику",
    Largest: "Највећи",
    LargestFile: "Највећа Датотека",
    LargestSize: "Највећа величина",
    LastAccessed: "Последњи приступ",
    LastEdit: "Последња измена",
    LastEditedBy: "Аутор последње измене",
    LastEditTime: "Време последњих промена",
    LastMessage: "Задња порука",
    LastName: "Презиме",
    LastNDays: "Последњих Н Дана",
    LastNHours: "Последњих Н Сати",
    LastNRows: "Последњих Н Редова",
    LastRun: "Задњи Ран",
    LatestReleases: "Најновија издања",
    Layout: "Распоред",
    LDAPWarning: "<б>Грешка ЛДАП Сервица:</б>  &lsquo;Превише корисника&rsquo; - Молимо користите филтер.",
    LearnMore: "Научите више",
    Leaves: "Листови",
    LegacyForm: "Стари Превазиђени Формулар",
    LegacyGraphLayout: "Стари графички изглед",
    LegacyGraphWidget: "Стари графички симбол",
    Legend: "Легенда",
    Length: "Дужина",
    LibrariesUsed: "Библиотеке у Кориштењу",
    LibraryName: "Име Библиотеке",
    Limit: "Лимит",
    Line: "Линија",
    LineTerminators: "Крајеви Линија",
    Links: "Линкови",
    Loading: "Учитавање...",
    LoadingCachedLayout: "Учитавање Кеширане Структуре...",
    LoadingData: "Учитавање Података...",
    loadingMessage: "...Учитавање...",
    LoadPackageContentHere: "(Добавите овамо садржај пакета)",
    LoadPackageFromFile: "Добавите Пакет из Датотеке",
    Local: "Локални",
    LocalFileSystemsOnly: "Само Локални Фајл Системи",
    Location: "Локација",
    Lock: "закључаjтe",
    log_analysis_1: "лог_аналисис_1*",
    Log: "Дневник (Лог)",
    LogAccess_GenericException: "вс_логаццесс::ГетЛогАццессИнфо, догодио се изузетак.",
    LogAccess_LoggingNotConfigured: "Машина за евидентирање није конфигурисана.",
    LogAccessType: "Тип приступа дневнику",
    LogDirectory: "Директориј за логирање података",
    LogEventType: "Унесите тип догађаја",
    LogFile: "Датотека Активности",
    LogFilterComponentsFilterTooltip: "Укључите евиденције само из изабране компоненте/контејнера",
    LogFilterCustomColumnsTooltip: "Укључите наведене колоне дневника",
    LogFilterEndDateTooltip: "Укључите редове дневника у датом временском опсегу",
    LogFilterEventTypeTooltip: "Укључите само уносе за дати тип догађаја",
    LogFilterFormatTooltip: "Формат дневника: ЦСВ, ЈСОН или КСМЛ",
    LogFilterLineLimitTooltip: "Број редова дневника које треба укључити",
    LogFilterLineStartFromTooltip: "Укључите редове дневника који почињу од овог броја реда",
    LogFilterRelativeTimeRangeTooltip: "Време временског опсега који окружује радну јединицу, +/- (у секундама)",
    LogFilters: "Филтери дневника",
    LogFilterSelectColumnModeTooltip: "Одредите које колоне треба укључити у датотеку евиденције",
    LogFilterSortByTooltip: "АСЦ - прво најстарији, ДЕСЦ - прво најновији",
    LogFilterStartDateTooltip: "Укључите редове дневника од почетка датог временског опсега",
    LogFilterTimeRequired: 'Изаберите или "Од и до датума" или "Релативни временски опсег"',
    LogFilterWildcardFilterTooltip: "Текст који се користи за филтрирање дневника",
    LogFormat: "Формат дневника",
    LoggedInAs: "Пријављен као",
    LoggingOut: "Одјављивањe",
    LogicalFile: "Логичка Датотека",
    LogicalFiles: "Логичке Датотеке",
    LogicalFilesAndSuperfiles: "Логичке Датотеке и Супердатотеке",
    LogicalFilesOnly: "Само Логичке Датотеке",
    LogicalFileType: "Тип Логичке Датотеке",
    LogicalName: "Име Логичке Датотеке",
    LogicalNameMask: "Маска Логичког Имена",
    Login: "Пријавите се",
    LogLineLimit: "Ограничење линијa дневника",
    LogLineStartFrom: "Почетни ред за писање у дневник",
    Logout: "Одјавитe се",
    Logs: "Дневници",
    LogsDisabled: "Евидентирање онемогућено",
    LogVisualization: "Региструјте визуализацију",
    LogVisualizationUnconfigured: "Визуелизација логa није конфигурирана, проверите како је конфигурацијски менаџер подешен",
    LostFile: "Изгубљени Фајл",
    LostFile2: "Изгубљени Фајлови",
    LostFileMessage: "Логички фајл коме недостаје бар један део или на примарној или на реплицираној локацији на диску. Логички фајл је још увек под контролом Дали сервера. Брисање фајлa прекида контролу Дали сервера над фајлом као и над свим преосталим деловима фајлa на диску.",
    Low: "Низак",
    MachineInformation: "Информација о машине",
    Machines: "Машине",
    Major: "Главни",
    ManagedBy: "Управљан",
    ManagedByPlaceholder: "цн = ХПЦЦАдмин, ОУ = Усерс, оу = ХПЦЦ, ДЦ = Мицо, ДЦ = локални",
    ManualCopy: "Притисните Ctrl+C",
    ManualOverviewSelection: "Нопходно Је Одабрати Преглед",
    ManualTreeSelection: "Нопходно Је Одабрати Дрво",
    Mappings: "Мапирања",
    Mask: "Маска",
    MatchCase: "Координате велика и мала слова",
    Max: "Максимум",
    MaxConnections: "Максимални број веза",
    MaximizeRestore: "Максимизирај / Врати претходни статус",
    MaximumNumberOfSlaves: "Максималан Број Извршилаца",
    MaxNode: "Максимални НОД / чвор",
    MaxRecordLength: "Максимална Дужина Рекорда",
    MaxSize: "Максимална величина",
    MaxSkew: "Максимално изобличење",
    MaxSkewPart: "Максимални Ску Дио",
    Mean: "средња вредност",
    MeanBytesOut: "Просечан број бајтова",
    MemberOf: "Члан Од",
    Members: "Чланови",
    MemorySize: "Величина меморије",
    Message: "Поруке",
    MethodConfiguration: "Конфигурација метода",
    Methods: "Методи",
    MetricOptions: "Метричке опције",
    Metrics: "Метрике",
    MetricsGraph: "Метрика/графикон",
    MetricsSQL: "Метрика (СКЛ)",
    Min: "Минимум",
    Mine: "Moj",
    MinNode: "Минимални НОД / чвор",
    Minor: "Миноран",
    MinSize: "Минимална Величина",
    MinSkew: "Минимално изобличење",
    MinSkewPart: "Минимални Ску Дио",
    Missing: "Недостаје",
    MixedNodeStates: "Сви Нодови Немају Исти Статус",
    Modification: "Промена",
    Modified: "Модификован",
    ModifiedUTCGMT: "Промењен (УТЦ/ГМТ)",
    Modify: "Промени",
    MonitorEventName: "Надгледајте Име Догађаја",
    Monitoring: "Hадгледање",
    MonitorShotLimit: "Надгледајте Шот Лимит",
    MonitorSub: "Надгледајте Суб",
    Month: "Месец",
    More: "Наставите",
    Move: "Помери",
    MustContainUppercaseAndSymbol: "Мораte укључити велико слово и симбол",
    NA: "Н/A",
    Name: "Име",
    NameOfEnvironment: "Име окружења",
    NamePrefix: "Префикс Имена",
    NamePrefixPlaceholder: "неки::префиks",
    NetworkAddress: "Нетворк адреса",
    Newest: "Најнивији",
    NewPassword: "Нова Лозинка",
    NextSelection: "Следећи Избор",
    NextWorkunit: "Следећа радна јединица",
    NoCommon: "Није уобичајено",
    NoContent: "(Без садржаја)",
    NoContentPleaseSelectItem: "Нема садржаја - изаберите ставку",
    noDataMessage: "...Нема Редова...",
    Node: "Чвор (Нод)",
    NodeGroup: "Група Чворова",
    NoErrorFound: "Без нађених грешака\n",
    NoFilterCriteriaSpecified: "Критериј за филтрирање није специфициран.",
    None: "Ниједан",
    NoPublishedSize: "Величина Није Објављена",
    NoRecentFiltersFound: "Нема филтера",
    Normal: "Нормалан",
    NoScheduledEvents: "Нема Дефинисаних Догађаја (ивентс) на Распореду.",
    NoSplit: "Нема Подијела (Сплит)",
    NotActive: "Није Активан",
    NotAvailable: "Није доступно",
    NothingSelected: "Ништа Није Изабрано...",
    NotInSuperfiles: "Није Дио Супердатотеке",
    NotSuspended: "Није суспендовано",
    NotSuspendedbyUser: "Није Суспендован Од Стране Корисника",
    NoWarningFound: "Поруке Упозорења (вoрнингс) нису нађене\n",
    NumberOfNodes: "Број чворова",
    NumberofParts: "Број Делова",
    NumberofSlaves: "Број Извршилаца",
    Of: "Oд",
    Off: "Искључено",
    OK: "OK",
    Oldest: "Најстарији",
    OldPassword: "Стара Лозинка",
    OmitSeparator: "Изоставите Сепаратор",
    On: "Укључено",
    Only1PackageFileAllowed: "Дозвољен је само један пакет",
    Open: "Отворен",
    OpenConfiguration: "Отвори конфигурацију",
    OpenInNewPage: "Отворите на Новој Страници",
    OpenInNewPageNoFrame: "Отворите на Новој Страници",
    OpenLegacyECLWatch: "Отворите Стари Превазиђени ЕЦЛ Вoч",
    OpenLegacyMode: "Отворите Застарели Мод",
    OpenModernECLWatch: "Отворите модерну ЕЦЛ контролну страницу",
    OpenNativeMode: "Отворите Нормални Мод",
    OpenSafeMode: "Отворите (сигурни мод)",
    OpenSource: "Отворени Код",
    OpenTreeMode: "Отворите (као дрво)",
    Operation: "Операција",
    Operations: "Операције",
    Optimize: "Оптимизуј",
    Options: "Опције",
    OriginalFile: "Оригинална датотека",
    OriginalSize: "Оригинална величина",
    OrphanFile: "Непотребни Фајлови",
    OrphanFile2: "Непотребaн Фајл",
    OrphanMessage: "Непотребни фајл има неке делове на диску. Али cви делови датотеке не постоје да би се могaо комплетирати логички фајл. Не постоји референца на непостијеће делове фајлa са Дали сервера.",
    OSStats: "ОС Статистика",
    Other: "Други",
    Others: "Други",
    Outputs: "Излази",
    Overview: "Преглед",
    Overwrite: "Препишите",
    OverwriteMessage: "Неке Датотеке већ постоје. Да бисте наставили морате дозвилити писање преко постојећих датотека",
    Owner: "Власник",
    PackageContent: "Садржај Пакета",
    PackageContentNotSet: "Садржај Пакета није дефинисан",
    PackageMap: "Мапа Пакета",
    PackageMaps: "Мапe Пакета",
    PackagesNoQuery: "Пакети за које нису дефинисани упити (kуериз)",
    PageSize: "Величина странице",
    ParameterXML: "Параметар XМЛ",
    Part: "Дио",
    PartMask: "Делимична Маска",
    PartName: "Име Дела",
    PartNumber: "Број Дела",
    Parts: "Делови",
    PartsFound: "Делови Су Пронађени",
    PartsLost: "Делови Су Изгубљени",
    Password: "Лозинка",
    PasswordExpiration: "Лозинка Истиће",
    PasswordExpired: "Ваша лозинка је истекла И мора бити промењена",
    PasswordExpirePostfix: "дан(а). Желите ли је сада променити?",
    PasswordExpirePrefix: "Ваша лозинка ће истећи за",
    PasswordNeverExpires: "Лозинка никада не истиче",
    PasswordOpenZAP: "Унесите Лозинку За ЗАП (необавезно)",
    PasswordsDoNotMatch: "Погрешна Лозинка.",
    Path: "Пут",
    PathAndNameOnly: "Само пут и име?",
    PathMask: "Маска за Пут",
    Pause: "Пауза",
    PauseNow: "Зауставите Одмах",
    PctComplete: "% Комплетиран",
    PercentCompressed: "Процент Компресије",
    PercentCompression: "Проценат компресије",
    PercentDone: "Проценат Завршен",
    Percentile97: "97 процената",
    Percentile97Estimate: "Процена 97 процената",
    PercentUsed: "Проценат употребе",
    PerformingLayout: "Извршава Лejaут...",
    Permission: "Дозвола",
    PermissionName: "Назив Дозволе За Приступ",
    Permissions: "Дозволе за Приступ",
    PhysicalFiles: "Физички Фајлови",
    PhysicalMemory: "Физичка меморија",
    PlaceholderFindText: "Pjид (Wuid), Корисник, Даље...",
    PlaceholderFirstName: "Џон",
    PlaceholderLastName: "Смит",
    Platform: "Платформа",
    PlatformBuildIsNNNDaysOld: "Верзија платформе је стара ННН дана",
    Playground: "Игралиште",
    PleaseEnableCookies: "ЕЦЛ Вач захтијева да колачићи буду омогућени за наставак",
    PleaseEnterANumber: "Унестите Број 1 -",
    PleaseLogin: "Молимо пријавите се користећи своје корисничко име и лозинку",
    PleaseLogIntoECLWatch: "Молимо пријавите се у ЕЦЛ Вач",
    PleasePickADefinition: "Изаберите дефиницију",
    PleaseSelectADynamicESDLService: "Одаберите Динамички ЕСДЛ сервис",
    PleaseSelectAGroupToAddUser: "Изаберите групу у коју желите да додате корисника",
    PleaseSelectAServiceToBind: "Изаберите Сервис за везивање",
    PleaseSelectATopologyItem: "Одаберите циљну платформу, сервис или машину.",
    PleaseSelectAUserOrGroup: "Изаберите Корисника или Групу заједно са Именом Фајла",
    PleaseSelectAUserToAdd: "Изаберите корисника којeг желите да додате",
    PleaseUpgradeToLaterPointRelease: "Пређите на касније издање",
    Plugins: "Допуне",
    PodName: "Подназив",
    Pods: "Групе контејнера",
    PodsAccessError: "Није могуће преузети листу подова",
    Port: "Порт",
    PotentialSavings: "Потенцијалне уштеде",
    Prefix: "Префикс",
    PrefixPlaceholder: "имедатотеке{:дужина}, величинадатотеке{:[B|L][1-8]}",
    Preflight: "Провера пре испоруке",
    PreloadAllPackages: "Учитајте све пакете",
    PreserveCompression: "Сачувајте Компресију",
    PreserveParts: "Сачувајте делове фајлова",
    PressCtrlCToCopy: "Притисните цтрл + ц да бисте копирали.",
    Preview: "Преглед",
    PreviousSelection: "Претходни Избор",
    PreviousWorkunit: "Претходна радна јединица",
    PrimaryLost: "Примарни Је Изгубљен",
    PrimaryMonitoring: "Основно Надгледање",
    Priority: "Приоритет",
    Probability: "Вероватноћа",
    Process: "Процес",
    Processes: "Процеси",
    ProcessesDown: "Неактивни процеси",
    ProcessFilter: "Процес&nbsp;Филтер",
    ProcessID: "ИД процеса",
    ProcessorInformation: "Информација о процесору",
    ProgressMessage: "Порука о Прогресу",
    Properties: "Својства",
    Property: "Својствo",
    Protect: "Заштитите",
    ProtectBy: "Заштићено од",
    Protected: "Заштићен",
    Protocol: "Протокол",
    Publish: "Објавите",
    Published: "Објављен",
    PublishedBy: "Објављивач",
    PublishedByMe: "Моjи Сервиси",
    PublishedQueries: "Објављени Упити",
    PushEvent: "Пуш Догађај",
    Quarter: "Четвртина",
    Queries: "Упити",
    QueriesNoPackage: "Упити без одговарајућег пакета",
    Query: "Упит",
    QueryDetailsfor: "Детаљи о Упиту",
    QueryID: "Идентификатор Упита",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Име Упита",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Колекција Упита",
    Queue: "Ред (Kjу)",
    Quote: "Цитат",
    QuotedTerminator: "Завршни Карактер",
    RawData: "Сирови подаци",
    RawTextPage: "Необрађен Текст (Текућа Страница)",
    Ready: "Cпреман",
    ReallyWantToRemove: "Заиста желите уклонити?",
    ReAuthenticate: "Молимо пријавите се опет",
    RecentFilters: "Употребљени филтeри",
    RecentFiltersTable: "Табела коришћених филтера",
    RecordCount: "Број Рекорда",
    RecordLength: "Дужина Рекорда",
    Records: "Рекорди",
    RecordSize: "Величина Рекорда",
    RecordStructurePresent: "Структура Рекорда Постоји",
    Recover: "Вратите Натраг",
    RecoverTooltip: "Покрените заустављену радну јединицу",
    RecreateQuery: "Креирај упит",
    Recursively: "Рекурзивно?",
    Recycling: "Рециклажа",
    RedBook: "Црвена Књига",
    Refresh: "Освежите",
    RelativeLogTimeRange: "Релативни временски опсег евиденције",
    RelativeTimeRange: "Релативни временски опсег",
    ReleaseNotes: "Напомена о Издању",
    Reload: "Поново Учитајте",
    Remaining: "Преостали",
    RemoteCopy: "Копија са удаљеног сервера",
    RemoteDali: "Далеки Дали",
    RemoteDaliIP: "Далеки&nbsp;Дали&nbsp;ИП&nbsp;Адреса",
    RemoteStorage: "Даљинско складиштење",
    Remove: "Уклоните",
    RemoveAttributeQ: "Изабрани атрибута ће бити уклоњен. Да ли сте сигурни да то желите?",
    RemoveAtttributes: "Уклоните Атрибут(е)",
    RemoveFromFavorites: "Уклони из омиљених",
    RemovePart: "Уклоните Дeо",
    RemoveSubfiles: "Уклоните Поддатотеку",
    RemoveSubfiles2: "Желите ли да уклоните субфајл(ове)?",
    RemoveUser: "Уклоните Корисника",
    Rename: "Преименујте",
    RenderedSVG: "Донесене СВГ",
    RenderSVG: "Донесите СВГ",
    Replicate: "Реплицирајте",
    ReplicatedLost: "Изгубљене Репликације",
    ReplicateOffset: "Реплицирајте Офсет",
    Report: "Извештај",
    ReportAnError: "Пријавите грешку",
    ReportError: "Пријавите грешку",
    RepresentsASubset: "Представља подскуп од укупног броја упарених резултата .Промена филтера може смањити број упарених резултата",
    RequestSchema: "Шема Захтева",
    RequiredForFixedSpray: "Потребно за фиксни спреј",
    RequiredForXML: "Потребно за дистрибуцију XМЛ",
    Reschedule: "Поново Ставите На Распоред",
    Reset: "Ресетујте",
    ResetThisQuery: "Ресетујте Текући Упит",
    ResetUserSettings: "Ресетуј корисничка подешавања",
    ResetViewToSelection: "Ресетујте Одабрани Вју",
    Resource: "Ресурс",
    Resources: "Ресурси",
    ResponseSchema: "Шема Одговора",
    Restart: "Поново Покрените",
    Restarted: "Поново Поктернут",
    Restarts: "Поново покрени",
    Restore: "Вратите на Старо Стање",
    RestoreDFUWorkunit: "Врати ДФУ радну јединицу",
    RestoreECLWorkunit: "Врати ЕЦЛ радну јединицу",
    Restricted: "Ограничен",
    Resubmit: "Поново Поднесите",
    Resubmitted: "Поново Послат",
    ResubmitTooltip: "Реактивирајте ову радну јединицу",
    Results: "Резултат(и)",
    Resume: "Наставите",
    RetainSuperfileStructure: "Задржите Структуру Супердатотеке",
    RetainSuperfileStructureReason: "Опција да се структура суперфила задржи мора бити активирана када постоји више од једног подфила.",
    RetypePassword: "Поновите Лозинку",
    Reverse: "Идите Уназад",
    RowPath: "Пут До Рекорда",
    Rows: "Редови",
    RowTag: "Етикета Реда",
    RoxieCluster: "Роkcи Кластер",
    RoxieFileCopy: "Статус Копирања Роxие Датотека",
    RoxieState: "Рокси стање",
    RunningServerStrain: "Извршавање овог процеса може да траје дуго времена и веома оптерети сервере. Желите ли да наставите?",
    Sample: "Пример",
    SampleRequest: "Пример Захтева",
    SampleResponse: "Пример Одговора",
    Sasha: "Саша",
    Save: "Сачувајте",
    SaveAs: "Сачувај као",
    Scope: "Подручје",
    ScopeColumns: "Истражите колоне",
    ScopeTypes: "Типови опсега",
    SearchResults: "Резултати Претраживања",
    Seconds: "Cекунде",
    SecondsRemaining: "Преостало Секунди",
    Security: "Сигурност",
    SecurityMessageHTML: "Погледајте ХТМЛ само од поузданих корисника. Ову радну јединицу је направио '{__плацехолдер__}'. Прикажи ХТМЛ?",
    SecurityWarning: "Безбедносно упозорење",
    SeeConfigurationManager: "Погледајте конфигурацију",
    SelectA: "Изаберите",
    SelectAnOption: "Изаберите опцију",
    Selected: "Изабрано",
    SelectEllipsis: "Изабери ...",
    SelectPackageFile: "Изаберитe Пакет",
    SelectValue: "Изаберите вредност",
    SendEmail: "Шаљи имејл",
    Separators: "Сеператори",
    Sequence: "Секвенца",
    Server: "Сервер",
    ServiceName: "Име Сервисa",
    Services: "Сервиси",
    ServiceType: "Врста услуге",
    SetBanner: "Поставите Заставицу",
    SetLogicalFileAttribute: "Подесите логички атрибут датотеке",
    SetProtected: "Поставите заштићено",
    SetTextError: "Неуспешно приказивање текста (да ли је текст предуг?). Користите &lsquo;помагаче&rsquo; за преузимање датотека.",
    SetToFailed: "Поставите На Неуспешан",
    SetToolbar: "Сет Тулбар",
    SetToolbarColor: "Подеси боју  траке са алаткама",
    SetUnprotected: "Поставите незаштићено",
    SetValue: "Подесите вредност",
    Severity: "Озбиљност",
    ShareWorkunit: "Дели Воркунит УРЛ",
    Show: "Прокажите",
    ShowPassword: "Покажи лозинку",
    ShowProcessesUsingFilter: "Прикажи процесе користећи филтер",
    ShowSVG: "Прокажите СВГ",
    Size: "Величина",
    SizeEstimateInMemory: "Процена величине у меморији",
    SizeMeanPeakMemory: "Просечна величина ударних употреба меморије",
    SizeOnDisk: "Величина на диску",
    Skew: "Скју",
    SkewNegative: "Скју (-)",
    SkewPositive: "Скју (+)",
    SLA: "СЛА",
    SlaveLogs: "Извештаји Извршилаца",
    SlaveNumber: "Број Извршилаца",
    Slaves: "Робови (Слejвс)",
    Smallest: "Најмањи",
    SmallestFile: "Најмања Датотека",
    SmallestSize: "Најмања Величина",
    SOAP: "СОАП",
    SomeDescription: "Неки*Опис",
    somefile: "*::некифajл*",
    Sort: "Сортирајте",
    Source: "Изворна Верзија",
    SourceCode: "Изворна Верзија Кода",
    SourceLogicalFile: "Име Изворног Фајла",
    SourcePath: "Изворна Верзија Пута (са омогућеним *)",
    SourceProcess: "Изворни Процес",
    Span: "Спан",
    SparkThor: "СпаркТхор",
    Spill: "Запис на Диск",
    SplitPrefix: "Сплит Префикс",
    Spray: "Разбацајте (Спрej)",
    SQL: "СКЛ",
    Start: "Почните",
    Started: "Почео",
    Starting: "Полазак",
    StartTime: "Почетно време",
    State: "Стање",
    Statistics: "Статистика",
    Stats: "Статистике",
    Status: "Статус",
    Stopped: "Заустављен",
    Stopping: "Заустављање",
    StorageInformation: "Информација о диск простору",
    Subfiles: "Подфајлови",
    Subgraph: "ПодГраф",
    SubgraphLabel: "Ознака подграфа",
    Subgraphs: "Подграфикон",
    Submit: "Поднесите",
    Subtype: "ПодВрста",
    SuccessfullySaved: "Успешно Сачуван",
    Summary: "Кратак Преглед",
    SummaryMessage: "Сажета Порука",
    SummaryStatistics: "Збирна статистика",
    SuperFile: "Супер Датотека",
    Superfile: "Супер Датотека",
    SuperFiles: "Супер Датотеке",
    Superfiles: "СуперДатотеке",
    SuperFilesBelongsTo: "Припадник Супердатотеке",
    SuperfilesOnly: "Само Супердатотеке",
    SuperOwner: "Супер Власник",
    Suspend: "Суспендујте",
    Suspended: "Суспендован",
    SuspendedBy: "Суспендован Од",
    SuspendedByAnyNode: "Зауставља било који чвор",
    SuspendedByCluster: "Суспендован од стране кластера",
    SuspendedByFirstNode: "Зауставља први чвор",
    SuspendedByUser: "Суспендован Од Стране Корисника",
    SuspendedReason: "Разлог за Суспендовање",
    SVGSource: "СВГ Извор",
    SyncSelection: "Синхронизујте Са Одабраним",
    Syntax: "Синтакса",
    SystemServers: "Систем Сервера",
    Table: "табела",
    tag: "таг",
    Target: "Циљ",
    TargetClusters: "Циљни Кластери",
    TargetClustersLegacy: "Циљни кластер (као раније)",
    TargetName: "Назив Циља",
    TargetNamePlaceholder: "неко::логићко::име",
    TargetPlane: "Дестинација за посао",
    TargetRowTagRequired: "Морате ознацити циљни ред у табели",
    Targets: "Циљне Платформе",
    TargetScope: "Циљни Обим",
    TargetWuid: "Циљ/Pjид",
    TechPreview: "Технички преглед",
    Terminators: "Терминатори",
    TestPages: "Тест Странице",
    Text: "Текст",
    Theme: "Тема",
    TheReturnedResults: "Враћени Резултати",
    ThorMasterAddress: "Адреса Главног Тора",
    ThorNetworkAddress: "Нетворк Адреса Торa",
    ThorProcess: "Тор Процес",
    ThreadID: "ИД Тхредa",
    Time: "Време",
    Timeline: "Временска линија",
    TimeMaxTotalExecuteMinutes: "Максимално укупно време извршавања у минутима",
    TimeMeanTotalExecuteMinutes: "Просечно укупно време извршавања у минутима",
    TimeMinTotalExecuteMinutes: "Минимално укупно време извршавања у минутима",
    TimePenalty: "Bременска Kазна",
    Timers: "Мерачи Времена",
    TimeSeconds: "Време (Секунде)",
    TimeStamp: "Временска Ознака",
    TimeStarted: "Време Почетка",
    TimeStopped: "Време Краја",
    Timings: "Времена",
    TimingsMap: "Мапа Времена",
    title_ActiveGroupPermissions: "Дозволе активнe групe",
    title_ActivePermissions: "Активнe Дозволе",
    title_Activity: "Активности",
    title_AvailableGroupPermissions: "Доступне Дозволе групе",
    title_AvailablePermissions: "Расположиве Дозволе",
    title_BindingConfiguration: "Конфигурација  Везивањa",
    title_BindingDefinition: "Дефиниција Везивањa",
    title_Blooms: "Блумс",
    title_ClusterInfo: "Групе",
    title_Clusters: "Кластери",
    title_CodeGeneratorPermissions: "Дозволе за генератор кода",
    title_DefinitionExplorer: "Истраживач Дефиниција",
    title_Definitions: "Дефиниције",
    title_DESDL: "Динамичани ЕСДЛ",
    title_DFUQuery: "Логичке Датотеке",
    title_DFUWUDetails: "ДФУ Радна Јединица",
    title_DirectoriesFor: "Директорији за",
    title_DiskUsage: "Искориштеност Диска",
    title_ECLPlayground: "ЕЦЛ Игралиште",
    title_ErrorsWarnings: "Грешке / упозорења за",
    title_EventScheduleWorkunit: "Распоређивач Догађаја",
    title_FileScopeDefaultPermissions: "Предефинисанe дозволе за фајл систем",
    title_FilesPendingCopy: "Датотеке на чекању за копирање",
    title_FoundFilesFor: "Пронађен фајл за",
    title_GetDFUWorkunits: "ДФУ Радне Јединице",
    title_Graph: "Графикон",
    title_GraphPage: "наслов",
    title_Graphs: "Графикони",
    title_GridDetails: "Промени Ме",
    title_History: "Историја",
    title_HPCCPlatformECL: "ECL Watch - Главна Страница",
    title_HPCCPlatformFiles: "ECL Watch - Датотеке",
    title_HPCCPlatformMain: "ECL Watch - Главна Страница",
    title_HPCCPlatformOps: "ECL Watch - Управљње",
    title_HPCCPlatformRoxie: "ECL Watch - Роkcи",
    title_HPCCPlatformServicesPlugin: "ЕЦЛ Монитор - Допуне",
    title_Inputs: "Уноси",
    title_LFDetails: "Детаљи о Логичкоj Датотеци",
    title_LibrariesUsed: "Библиотеке У Кориштењу",
    title_Log: "Лог Фајл",
    title_LostFilesFor: "Изгубљени фајлови за",
    title_LZBrowse: "Зона за Претовар",
    title_MemberOf: "Члан Од",
    title_Members: "Чланови",
    title_Methods: "Методе",
    title_OrphanFilesFor: "Непотребни фајлови за",
    title_PackageParts: "Делови пакета",
    title_Permissions: "Дозволе",
    title_Preflight: "Метрика Система",
    title_PreflightResults: "Резултати провере",
    title_ProtectBy: "Заштићено од",
    title_QuerySetDetails: "Детаљи Упита",
    title_QuerySetErrors: "Грешке",
    title_QuerySetLogicalFiles: "Логичке Датотеке",
    title_QuerySetQuery: "Упити (Kуериз)",
    title_QuerySetSuperFiles: "Супер Датотеке",
    title_QueryTest: "Супер Датотеке",
    title_Result: "Ацктивност",
    title_Results: "Резултати",
    title_SearchResults: "Резултати Претраживања",
    title_SourceFiles: "Оригиналне Датотеке",
    title_SystemServers: "Системски сервери",
    title_SystemServersLegacy: "Системски сервери (стари)",
    title_TargetClusters: "Циљни кластери",
    title_Topology: "Топологија",
    title_TpThorStatus: "Стање Тора",
    title_UserPermissions: "Корисничке Дозвиле за Приступ",
    title_UserQuery: "Права Приступа",
    title_WorkunitScopeDefaultPermissions: "Унапред Дефинисане Дозвиле за Aктивности",
    title_WUDetails: "ЕЦЛ Детаљи о Радној Јединици",
    title_WUQuery: "ЕЦЛ Радне Јединице",
    TLS: "ТЛС",
    To: "Према",
    ToDate: "До Сада",
    Toenablegraphviews: "Да бисте могли видети графиконе, мораћете инсталисати Граф Вjу Kонтрол плaгин",
    Tooltip: "Савет",
    TooManyFiles: "Превише Фајлова",
    Top: "Врх",
    Topology: "Топологија",
    ToSizes: "До Величина",
    Total: "Укупно",
    TotalClusterTime: "Укупно Време Кластера",
    TotalParts: "Укупан број делова",
    TotalSize: "Укупна Величина",
    TotalThorTime: "Укупно Време Тора",
    ToTime: "До времена",
    Trace: "Откриј",
    TransferRate: "Стопа преноса",
    TransferRateAvg: "Просечна брзина преноса",
    TransitionGuide: "Водич",
    Tree: "Дрво",
    Type: "Тип",
    UnavailableInContainerized: "Ово није доступно у контејнерском окружењу.",
    Unbound: "невезан",
    undefined: "недефинисан",
    Unknown: "Непознат",
    Unlock: "Откључај",
    UnlockSDSLock: "Откључај СДС Лоцк",
    Unprotect: "Укините Заштиту",
    UnsupportedIE9FF: "Нису Подржани (ИЕ <= 9, ФиреФоx)",
    Unsuspend: "Укините Суспензију",
    Unsuspended: "Суспензија Укинута",
    Up: "На Горе",
    UpdateCloneFrom: "Ажурирајте Клон Користећи",
    UpdateDFs: "Ажурирајте ДФС",
    UpdateSuperFiles: "Ажурирајте Супер Фајл",
    Upload: "Aплоyд",
    Uploading: "Учитавање",
    UpTime: "Време Радa",
    URL: "УРЛ",
    Usage: "Употреба",
    Used: "Кориштен",
    UsedByWorkunit: "Користи се са радном јединицом",
    User: "Корисник",
    UserDetails: "Детаљи о Кориснику",
    UserID: "Корисницки ИД",
    UserLogin: "Пријавите се само користећи своје корисничко име",
    UserName: "Име Корисника",
    Username: "Имекорисника",
    UserPermissions: "Дозволе за Корисников Приступ",
    Users: "Корисници",
    UseSingleConnection: "Користите Само Једaн Прикључак (конекшн)",
    Validate: "Потврдите",
    ValidateActivePackageMap: "Валидирајте Мапу Активног Пакета",
    ValidatePackageContent: "Валидирајте Саржај Пакета",
    ValidatePackageMap: "Потврдите Мапу Пакета",
    ValidateResult: "=====Потврдите Резултaт=====\n\n",
    ValidateResultHere: "(Резултати Валидирања)",
    Validating: "Проверавање ...",
    ValidationErrorEnterNumber: "Унесите важећи број",
    ValidationErrorExpireDaysMinimum: "Не би требало да буде мање од једног дана",
    ValidationErrorNamePrefix: "Требало би да се узорак подудара са нешто :: префикс",
    ValidationErrorNumberGreater: "Не може бити веће од",
    ValidationErrorNumberLess: "Не може бити мање од",
    ValidationErrorRecordSizeNumeric: "Дужина записа треба да буде број",
    ValidationErrorRecordSizeRequired: "Потребна дужина записа",
    ValidationErrorRequired: "Ово поље је обавезно",
    ValidationErrorTargetNameInvalid: "Непостојеће име фајла",
    ValidationErrorTargetNameRequired: "Име фајла је обавезно",
    Value: "Вредност",
    Variable: "Варијабла",
    VariableBigendian: "Варијабла Биг-ендиан",
    Variables: "Вариабле",
    VariableSourceType: "Тип Извора",
    Version: "Верзија",
    ViewByScope: "Поглед према Скопу",
    Views: "Погледи",
    ViewSparkClusterInfo: "Погледајте Информације о Спарк кластеру",
    Visualizations: "Визуализације",
    Visualize: "Визуализујте",
    WarnIfAvailableDiskSpaceIsUnder: "Упозори aко расположиви диск простор спадне испод",
    WarnIfAvailableMemoryIsUnder: "Упозори aко расположива меморија спадне испод",
    WarnIfCPUUsageIsOver: "Упозори ако је искориштеност процесора преко",
    Warning: "Упозорење",
    Warnings: "Упозорење(а)",
    WarnOldGraphControl: "Упозорење:  Стара Графичка Контрола",
    What: "Шта",
    Where: "Где",
    Who: "Ко",
    Width: "Ширина",
    WildcardFilter: "Вилдцард филтер",
    Workflows: "Токови послова",
    Workunit: "Радна Јединица",
    WorkunitNotFound: "Радна јединица није пронађена",
    WorkunitOptions: "Опције радне јединице",
    Workunits: "Радне Јединице",
    WorkUnitScopeDefaultPermissions: "Унапред Дефинисане Дозвиле за Простор за Радне Јединице",
    Wrap: "Замотајте",
    WSDL: "WSDL",
    WUID: "PJИД",
    Wuidcannotbeempty: "Pjид Не Може Бити Празан.",
    WUSnapshot: "Снимак радне јединице",
    WUSnapShot: "Тренутна Слика Радне Јединице",
    WUSnapshots: "Снимци радне јединице",
    XGMML: "XГММЛ",
    XLS: "XЛС",
    XML: "XМЛ",
    XRef: "XРеф",
    Year: "Година",
    YouAreAboutToBeLoggedOut: "Ви ћете бити одјављени",
    YouAreAboutToDeleteBinding: "Одабрано везивање ће бити обрисано. Да ли сте сигурни да желите да то урадите?",
    YouAreAboutToDeleteDefinition: "У процесу је брисање ове дефиниције. Да ли сте сигурни да желите то учинити?",
    YouAreAboutToDeleteThisFile: "Да ли ћете обрисати ову датотеку",
    YouAreAboutToDeleteThisPart: "Да ли ћете обрисати овај дeо",
    YouAreAboutToDeleteThisQueryset: "Да ли ћете обрисати овај сет упита",
    YouAreAboutToDeleteThisWorkunit: "Да ли ћете обрисати ову радну јединицу",
    YouAreAboutToRemoveUserFrom: "тражили сте да уклоните корисника(е) из ове групе. Да ли желите да наставите?",
    YourBrowserMayNotSupport: "Ваш претраживач можда не подржава датотеку (е) ове величине",
    YourScreenWasLocked: "ЕСП је закључао ваш екран. Подаци су застарели",
    ZAP: "З.А.П.",
    ZeroLogicalFilesCheckFilter: "Нема ни једане Логичке Датотеке(проверите филтер)",
    Zip: "Запакујте (Зип)",
    ZippedAnalysisPackage: "Запаковани Пакет са Анализама",
    Zoom: "Зум",
    Zoom100Pct: "Зумирајте 100%",
    ZoomAll: "Зумирајте Све",
    ZoomMinus: "Зум -",
    ZoomPlus: "Зум +",
    ZoomSelection: "Избор зумирања",
    ZoomWidth: "Зумирајте Ширину"
}