---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
data:
  file.system.id: {{ .Values.efs.id }}
  aws.region: {{ .Values.efs.region }}
  provisioner.name: aws.io/aws-efs
  dns.name: ""
---
kind: Deployment
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
metadata:
  name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
  template:
    metadata:
      labels:
        app: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
    spec:
      containers:
        - name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
          image: {{ .Values.efs.image }}
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
                  key: aws.region
            - name: DNS_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
                  key: dns.name
                  optional: true
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "efs-provisioner-%s" (include "hpcc-efs.fullname" $) }}
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: {{ .Values.efs.id }}.efs.{{ .Values.efs.region }}.amazonaws.com
            path: /
