/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from allversionreport.xml. ***/
/*===================================================*/


EXPORT allversionreport := MODULE

EXPORT t_FooBar := RECORD
	UTF8 Foo {XPATH('Foo')};
	UTF8 Bar {XPATH('Bar')};
END;

EXPORT t_AllVersionArrays := RECORD
	SET OF UTF8 StringArray {XPATH('StringArray/Item'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
	DATASET(t_FooBar) FooBarArray {XPATH('FooBarArray/FooBar'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
	DATASET(t_FooBar) NamedItemFooBarArray {XPATH('NamedItemFooBarArray/NamedItem'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
END;

EXPORT t_AllVersionReportRequest := RECORD
	UTF8 OptionalDeveloperStringVal {XPATH('OptionalDeveloperStringVal')};//hidden[developer]
	INTEGER Annotate20ColsIntVal {XPATH('Annotate20ColsIntVal')};
	t_AllVersionArrays Arrays {XPATH('Arrays')};
	UTF8 UnrelentingForce {XPATH('UnrelentingForce')}; //values['1','2','3','']
END;

EXPORT t_AllVersionReportResponse := RECORD
	UTF8 ResultVal {XPATH('ResultVal')};
	t_AllVersionArrays ResultArrays {XPATH('ResultArrays')};
END;


END;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from allversionreport.xml. ***/
/*===================================================*/

