/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from ws_test.xml. ***/
/*===================================================*/


EXPORT ws_test := MODULE

EXPORT t_MinVersionReportRequest := RECORD
	UTF8 RequestString {XPATH('RequestString')};
END;

EXPORT t_VersionRangeReportRequest := RECORD
	UTF8 RequestString {XPATH('RequestString')};
END;

EXPORT t_VersionRangeReportResponse := RECORD
	UTF8 ResponseString {XPATH('ResponseString')};
END;

/*Empty record generated from empty EsdlRequest
EXPORT t_WsTestPingRequest := RECORD
END;
*/

EXPORT t_MinVersionReportResponse := RECORD
	UTF8 ResponseString {XPATH('ResponseString')};
END;

/*Empty record generated from empty EsdlResponse
EXPORT t_WsTestPingResponse := RECORD
END;
*/


END;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from ws_test.xml. ***/
/*===================================================*/

