# Overrides for filestore storage in hpcc, using custom StorageClass'
# NB: The "hpcc-filestore" helm charts should be installed 1st.
# The "hpcc-filestore" helm chart provisions and creates the
# PVC's required by HPCC.
# The pvc names are dynamic based on the install name.
# In this example the install name was "gcpstorage"

storage:
  planes:
  - name: dali
    pvc: dali-gcpstorage-hpcc-filestore-pvc
    prefix: "/var/lib/HPCCSystems/dalistorage"
    category: dali

  - name: dll
    pvc: dll-gcpstorage-hpcc-filestore-pvc
    prefix: "/var/lib/HPCCSystems/queries"
    category: dll

  - name: sasha
    pvc: sasha-gcpstorage-hpcc-filestore-pvc
    prefix: "/var/lib/HPCCSystems/sasha"
    category: sasha

  - name: data
    pvc: data-gcpstorage-hpcc-filestore-pvc
    prefix: "/var/lib/HPCCSystems/hpcc-data"
    category: data # NB: if not set, this would be the default

sasha:
  wu-archiver:
    plane: sasha
  dfuwu-archiver:
    plane: sasha
