eck-stack:
  eck-elasticsearch:
    enabled: true
    # Name of the Elasticsearch instance.
    #
    fullnameOverride: elasticsearch
    nodeSets:
    - name: default
      count: 1
      # Comment out when setting the vm.max_map_count via initContainer, as these are mutually exclusive.
      # For production workloads, it is strongly recommended to increase the kernel setting vm.max_map_count to 262144
      # and leave node.store.allow_mmap unset.
      # ref: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
      #
      config:
        node.store.allow_mmap: false
    lifecycle:
    postStart:
      exec:
        command:
          - bash
          - -c
          - |
            PIPELINE_NAME=hpccpipeline
            ES_URL=http://localhost:9200
            PIPELINE_REQ_PATH=_ingest/pipeline
            [ -z ${WAIT_ES_READY_IN_SEC} ] && WAIT_ES_READY_IN_SEC=120
            END_TIME=$(expr $(date +%s) \+ ${WAIT_ES_READY_IN_SEC})
            START_FILE=/tmp/.es_start_file
            while [[ $(date +%s) -le ${END_TIME} ]]; do
              [ -f "${START_FILE}" ] && break
              sleep 1
            done
            if [ -f "${START_FILE}" ]; then
              echo 'Cluster is ready to add hpccpipeline'
            else
              echo 'Cluster health check timeout. Will try to add hpccpipeline anyway.'
            fi
            # Need wait elasticsearch container ready to test the hostname with ordinal
            # Only add pipeline in the first elasticsearch master
            if [ ${HOSTNAME##*-} -eq 0 ]; then
              curl -s -X PUT "$ES_URL/$PIPELINE_REQ_PATH/$PIPELINE_NAME/" -H 'Content-Type: application/json' \
                -d'{ "description": "Parses and formats HPCC Systems component log entries", "version": 10213, "processors": [ { "grok": { "field": "message", "patterns": [ "(?m)%{BASE16NUM:hpcc.log.sequence}\\s+%{HPCC_LOG_AUDIENCE:hpcc.log.audience}\\s+%{HPCC_LOG_CLASS:hpcc.log.class}\\s+%{TIMESTAMP_ISO8601:hpcc.log.timestamp}\\s+%{POSINT:hpcc.log.procid}\\s+%{POSINT:hpcc.log.threadid}\\s+%{HPCC_LOG_WUID:hpcc.log.jobid}(\\s+%{OTEL_TRACE_ID:hpcc.log.traceid})?(\\s+%{OTEL_SPAN_ID:hpcc.log.spanid})?\\s+\"%{GREEDYDATA:hpcc.log.message}\"" ], "pattern_definitions": { "OTEL_TRACE_ID": "([a-f0-9]){32}|(UNK)", "OTEL_SPAN_ID": "([a-f0-9]){16}|(UNK)", "HPCC_LOG_WUID": "([A-Z][0-9]{8}-[0-9]{6}(-[0-9]+)?)|(UNK)", "HPCC_LOG_CLASS": "DIS|ERR|WRN|INF|PRO|MET|UNK", "HPCC_LOG_AUDIENCE": "OPR|USR|PRG|AUD|UNK" } } }, { "date": { "field": "hpcc.log.timestamp", "formats": [ "yyyy-MM-dd HH:mm:ss.SSS" ], "timezone": "UTC" } } ], "on_failure": [ { "set": { "field": "hpccpipeline.error.message", "value": "{{ _ingest.on_failure_message }}" } } ] }'
              rc=$?
              if [ ${rc} -eq 0 ]; then
                echo 'Successfully added hpccpipeline !'
              else
                echo 'Failed to add hpccpipeline.'
              fi
            fi
  eck-apm-server:
    ssl.verification_mode: none
    enabled: true
    # Count of APM Server replicas to create.
    #
    count: 1
    # Reference to ECK-managed Elasticsearch resource.
    #
    elasticsearchRef:
      name: elasticsearch
    kibanaRef:
      name: kibana
    spec:
      config:
        output:
          elasticsearch:
            username: "elastic"
            protocol: "https"
            ssl.verification_mode: "none"
    http:
      service:
        spec:
          ports:
          - name: http
            port: 8200
            targetPort: 8200
  eck-kibana:
    enabled: true
    # Name of the Kibana instance.
    #
    fullnameOverride: kibana
    spec:
      config:
        xpack.fleet.packages:
        - name: apm
          version: latest
    http:
      service:
        spec:
          type: LoadBalancer # default is ClusterIP
    ingress:
      annotations: {}
      enabled: true
      hosts:
      - host: localhost
        path: /
      labels: {}
      pathType: Prefix
      tls:
        enabled: false
  eck-beats:
    enabled: true
    #extraEnvs:
    #- name: ELASTIC_USER_PASSWORD
    #  valueFrom:
    #    secretKeyRef:
    #      name: elasticsearch-es-elastic-user
    #      key: elastic
    metadata:
      name: filebeat
    spec:
      type: filebeat
      elasticsearchRef:
        name: elasticsearch
      kibanaRef:
        name: kibana
      config:
        #Required if targeting non-default index (filebeat-%{[agent.version]}-%{+yyyy.MM.dd}) such as hpccsystems-%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}, etc.
        #setup.template.name: "hpcc-logs"
        #setup.template.pattern: "hpcc-logs-*"
        #setup.ilm.enabled: true
        #setup.ilm.rollover_alias: "hpcc-logs"
        #setup.ilm.pattern: "{now/d}-000001"
        #setup.ilm.policy_name: "Standard-Index"
        filebeat.inputs:
        - type: filestream
          paths:
          - /var/log/containers/esdl-sandbox-*.log
          - /var/log/containers/eclwatch-*.log
          - /var/log/containers/mydali-*.log
          - /var/log/containers/eclqueries-*.log
          - /var/log/containers/sql2ecl-*.log
          - /var/log/containers/eclservices-*.log
          - /var/log/containers/dfuserver-*.log
          - /var/log/containers/eclscheduler-*.log
          - /var/log/containers/hthor-*.log
          - /var/log/containers/myeclccserver-*.log
          - /var/log/containers/roxie-*.log
          - /var/log/containers/sasha-*.log
          - /var/log/containers/thor-*.log
          - /var/log/containers/spray-service-*.log
          - /var/log/containers/dfs-*.log
          #parsers:
          #- container: ~
          prospector:
            scanner:
              fingerprint.enabled: true
              symlinks: true
          file_identity.fingerprint: ~
          multiline.type: pattern
          multiline.pattern: '^([A-Z-0-9]{8})\s+'
          multiline.negate: true
          multiline.match: after
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
#        - add_host_metadata: {}
#        - add_cloud_metadata: {}
        output.elasticsearch:
        #  hosts: ["https://elasticsearch-es-http.default.svc:9200"]
          #username: "elastic"
          #password: "${env:ELASTIC_USER_PASSWORD}"
        #  ssl.verification_mode: "none"
          #pipeline: 'hpccpipeline'
          #index: "hpcc-logs-%{+yyyy.MM.dd}"
    daemonSet:
      podTemplate:
        spec:
          serviceAccount: elastic-beat-filebeat
          automountServiceAccountToken: true
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true # Allows to provide richer host metadata
          containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              privileged: true
            volumeMounts:
            - name: varlogcontainers
              mountPath: /var/log/containers
            - name: varlogpods
              mountPath: /var/log/pods
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
opentelemetry-collector:
  mode: daemonset
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 400Mi
  image:
    repository: otel/opentelemetry-collector-k8s
    tag: "0.123.0"
  extraEnvs:
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: eck-apm-eck-apm-server-apm-token
          key: secret-token
  extraVolumes:
  - name: apm-certs
    secret:
      defaultMode: 420
      optional: false
      secretName: eck-apm-eck-apm-server-apm-http-certs-public 
  extraVolumeMounts:
  - name: apm-certs
    mountPath: /etc/ca-certificates/tls.crt
    subPath: tls.crt
    readOnly: true
# Enable Kubernetes attributes enrichment
  presets:
    kubernetesAttributes:
      enabled: true

# Collector configuration
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - http://*
                - https://*

    processors:
      batch:
        send_batch_size: 8192
        timeout: 5s
      memory_limiter:
        check_interval: 5s
        limit_mib: 800
        spike_limit_mib: 150
      k8sattributes: # Processor to enrich spans with Kubernetes attributes
        passthrough: false # If set to true, the processor will not enrich the spans with Kubernetes attributes.
        extract:
          metadata:
          - k8s.pod.name
          #- k8s.namespace.name
          #- k8s.node.name
          #- k8s.pod.uid
          #- k8s.pod.start_time
          #- k8s.deployment.name
          #- k8s.statefulset.name
          #- k8s.daemonset.name
          #- k8s.cronjob.name
          #- k8s.job.name
          #- k8s.container.name
          #- k8s.cluster.name

    exporters:
      #Full otlphttp config options documented here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/config.go
      otlphttp:
        endpoint: https://eck-apm-eck-apm-server-apm-http.default.svc:8200
        headers:
          Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"
        tls:
          ca_file: "/etc/ca-certificates/tls.crt"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, k8sattributes]
          exporters: [otlphttp]
  service:
  # Enable the creation of a Service.
  # By default, it's enabled on mode != daemonset.
  # However, to enable it on mode = daemonset, its creation must be explicitly enabled
    enabled: true

    type: LoadBalancer
    # trafficDistribution: PreferClose

