define(
({
    Abort: "Прекините",
    About: "О Апликацији",
    AboutGraphControl: "О Графичкој Контроли",
    AboutHPCCSystemsGraphControl: "О Графичкој Контроли ХПЦЦ Система",
    Action: "Акција",
    Activate: "Активирајте",
    Activated: "Активиран",
    Active: "Активан",
    ActivePackageMap: "Активна Мапа Пакета",
    ActiveWorkunit: "Активна Радна Јединица",
    Activities: "Активности",
    Activity: "Активност",
    ActualSize: "Тачна Величина",
    Add: "Додајте",
    AddFile: "Додајте Датотеку",
    AddGroup: "Додајте Групу",
    AdditionalResources: "Додатни Ресурси",
    AddProcessMap: "Додајте Мапу Пакета",
    AddToSuperfile: "Додајте на Супердатотеку",
    AddUser: "Додајте Корисника",
    Advanced: "Вишег Нивоа",
    All: "Сви",
    AllowAccess: "<center>Дозволите<br>Приступ</center>",
    AllowForeignFiles: "Дозволите Кориштење  Датотека Са Других Кластера",
    AllowFull: "<center>Дозволите<br>Потпун</center>",
    AllowRead: "<center>Дозволите<br>Читање</center>",
    AllowWrite: "<center>Дозволите<br>Писање</center>",
    ANY: "Било Који",
    Append: "Додајте",
    Apply: "Примените",
    ArchivedOnly: "Само Архивиран",
    ArchivedWarning: "Упозорење: користите кратак временски период. Ако користите дужи временски период, претраживање радних јединица може трајати дуже од дозвиљеног времена за претраживање.",
    AutoRefresh: "Освежи",
    Back: "Назад",
    BannerColor: "Боја Рекламног Блока",
    BannerMessage: "Порука за Рекламни Блок",
    BannerScroll: "Кретање Рекламног Блока",
    BannerSize: "Величина Рекламног Блока",
    BinaryInstalls: "Бинарне Инсталације",
    Blob: "БЛОБ",
    BlobPrefix: "БЛОБ Префикс",
    Bottom: "Крај",
    Cancel: "Поништите",
    Clear: "Очистите",
    ClearPermissionsCache: "Избришите Запамћене Дозволе За Приступ",
    ClearPermissionsCacheConfirm: "Да ли сте сигурни да желите да избришете запамћене дозволе за приступ на ДАЛИ и ЕСП? То може значајно успорити извршавање радних јединица.",
    Clone: "Клонирајте",
    ClonedWUID: "Клонирани WУИД",
    Close: "Затворите",
    Cluster: "Кластер",
    ClusterName: "Име Кластера",
    ClusterPH: "r?x*",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Процеси На Кластеру",
    Code: "Код",
    CodeGenerator: "Код Генератор",
    Col: "Колона",
    CollapseAll: "Сузите све",
    Command: "Команда",
    Comment: "Коментар",
    Completed: "Комплетиран",
    ComplexityWarning: "Више од прага {threshold} активности ({activityCount}) - прекините приказ података?",
    Component: "Компонента",
    Compress: "Сабијте",
    Compressed: "Компримирани",
    CompressedFileSize: "Компримирана Величина Датотеке",
    Configuration: "Конфигурација",
    ConfirmPassword: "Потврдите Лозинку",
    ConfirmRemoval: "Јесте ли сигурни да то желите учинити?",
    Content: "Садржај",
    Contents: "Садржаји",
    ContentType: "Врста Садржаја",
    Copy: "Копирајте",
    Count: "Избројте",
    Created: "Произведен",
    Dali: "Дали",
    dataset: ":=датасет*",
    Date: "Датум",
    Day: "Дан",
    Deactivate: "Искљућите",
    Debug: "Отклоните Неисправности",
    DEF: "ДЕФ",
    Delete: "Обришите",
    Deleted: "Избрисан",
    DeleteSelectedFiles: "Обришите Одабране Датотеке?",
    DeleteSelectedGroups: "Обришите одабрану(е) групу(е)?",
    DeleteSelectedPermissions: "Обришите Одабране Дозволе За Приступ",
    DeleteSelectedQueries: "Обришите Одабране Захтјеве?",
    DeleteSelectedUsers: "Обришите Одабране Кориснике?",
    DeleteSelectedWorkunits: "Обришите Одабране Радне Јединице?",
    DeleteSuperfile2: "Избришите Супер Датотеку",
    DeleteSuperfile: "Обришите Супердатотеке?",
    DeleteThisPackage: "Обришите Овај Пакет?",
    Delimited: "Разграничен",
    DenyAccess: "<center>Забраните<br>Приступ</center>",
    DenyFull: "<center>Забраните<br>Потпун</center>",
    DenyRead: "<center>Забраните<br>Читање</center>",
    DenyWrite: "<center>Забраните<br>Писање</center>",
    Depth: "Дубина",
    DepthTooltip: "'Највећа Дубина Подграфа",
    Deschedule: "Избаците Ис Реда За Извршавање",
    DescheduleSelectedWorkunits: "Избаците Одабране Радне Јединице Из Реда За Извршавање?",
    Description: "Опис",
    Despray: "Поново Обjедините Датотеку",
    Details: "Детаљи",
    DFUServerName: "Име ДФУ Сервера",
    DFUWorkunit: "ДФУ РаднаЈединицa",
    Directory: "Директориј",
    DisableScopeScanConfirm: "Да ли сте сигурни да желите онемогућити сканирање опсега? Промене ће бити прихваћене после рестарта ДАЛИја",
    DisableScopeScans: "Онемогућите Сканирање Опсега",
    DiskUsage: "Искориштеност Диска",
    Distance: "Раздаљина",
    DistanceTooltip: "Максимална Величина Подграфа За Одабрану Активност",
    Dll: "Длл",
    DOT: "ДОТ",
    DOTAttributes: "ДОТ Атрибути",
    Down: "Неактиван",
    Download: "Добавите",
    DropZone: "Зона Пријема",
    Duration: "Трајање",
    EBCDIC: "ЕБЦДИK",
    ECL: "ЕЦЛ",
    ECLWorkunit: "ЕЦЛ РаднаЈединица",
    Edges: "Ивице",
    Edit: "Едитујте",
    EditDOT: "Едитујте ДОТ",
    EditGraphAttributes: "Едитујте Атрибуте Графова",
    EditXGMML: "Едитујте XГММЛ",
    Empty: "(Празан)",
    Enable: "Омогућите",
    EnableScopeScans: "Омогућите Сканирање Опсега",
    EnableScopeScansConfirm: "Да ли сте сигурни да желите омогућити сканирање опсега? Промене ће бити прихваћене после рестарта ДАЛИја",
    EnglishQ: "Енглески?",
    Error: "Грешка",
    Errorparsingserverresult: "Грешка у анализи резултата са сервера",
    Errors: "Грешкe",
    ErrorsStatus: "Грешкe/Стање",
    ErrorWarnings: "Грешка/Упозорења",
    Escape: "Ескејп",
    ESPBuildVersion: "ЕСП Тренутна Верзија",
    ESPNetworkAddress: "ЕСП Нетворк Адреса",
    EventName: "Име Догађаја",
    EventNamePH: "имедогађаја",
    EventScheduler: "Распоређивач Догађаја",
    EventText: "Опис Догађаја",
    EventTextPH: "Текст О Догађају",
    Exception: "Неочекивани Проблем",
    ExpandAll: "Проширите све",
    Export: "Извезите",
    FailIfNoSourceFile: "Неуспех Уколико Датотека Не Постоји",
    FetchingData: "У Процесу Добављња Података...",
    fetchingresults: "добијени ресултати",
    File: "Датотека",
    FileCounts: "Број Датотека",
    FileName: "Име Датотеке",
    FileParts: "Дио Датотеке",
    FilePath: "Локација Датотеке",
    Files: "Датотеке",
    FileScopes: "Скоп Датотека",
    FileSize: "Величина Датотеке",
    FilesNoPackage: "Датотеке које не припадају пакету",
    FilesWithUnknownSize: "Датотеке Са Непознатим Величинама",
    FileType: "Тип Датотеке",
    FileUploader: "Процес за премештање Датотеке на Сервер (Aплоyдер)",
    FileUploadStillInProgress: "Учитавање Датотека је у Току",
    Filter: "Филтер",
    Find: "Нађите",
    FindNext: "Нађите Следећи",
    FindPrevious: "Нађите Претходни",
    Finished: "Завршен",
    FirstName: "Име",
    FirstNRows: "Првих Н Редова",
    Fixed: "Фиксни",
    Folder: "Фасцикла",
    Format: "Формат",
    Forward: "Напред",
    FromDate: "Од Датума",
    FromSizes: "Од Величине",
    FromTime: "Од Времена",
    FullName: "Име и Презиме",
    Graph: "Граф",
    Graphs: "Графикони",
    GraphView: "Слика Графикона",
    Group: "Група",
    GroupBy: "Групишите По",
    GroupDetails: "Детаљи о Групи",
    Grouping: "Груписање",
    GroupName: "Назив Групе",
    GroupPermissions: "Дозволе за Приступ Групе",
    Groups: "Групе",
    GZip: "ГЗип",
    help: "Овdе је приказан графикон извршавања ове радне јединице. Величина и нијанса указују на време извршавања сваког графикона (Већи и тамнији графикон узима већи проценат cелокупног времена извршавања.)",
    Helpers: "Помагаћи",
    Hex: "База16",
    High: "Висок",
    History: "Историја",
    HPCCSystems: "ХПЦЦ Системс",
    ID: "Идентификатор",
    Inactive: "Неактиван",
    Index: "Индекс",
    Info: "Информација",
    InfoDialog: "Диалог Информације",
    Inputs: "Уноси",
    InvalidResponse: "(Неисправан Одговор)",
    IP: "ИП",
    IPAddress: "ИП Адреса",
    IsLibrary: "Је Библиотека",
    JobName: "Назив Радне Јединице",
    Jobname: "Називраднејединице",
    jsmi: "јсми*",
    JSmith: "ЈСмит*",
    JSON: "ЈСОН",
    Label: "Етикета",
    LandingZone: "Зона за Претовар",
    LandingZones: "Зонe за Претовар",
    LanguageFiles: "Датотеке О Језику",
    Largest: "Највећи",
    LargestFile: "Највећа Датотека",
    LargestSize: "Највећа величина",
    LastName: "Презиме",
    LastNDays: "Последњих Н Дана",
    LastNHours: "Последњих Н Сати",
    LastNRows: "Последњих Н Редова",
    LDAPWarning: "<б>Грешка ЛДАП Сервица:</б>  'Превише корисника' - Молимо користите филтер.",
    LegacyForm: "Стари Превазиђени Формулар",
    LibrariesUsed: "Библиотеке у Кориштењу",
    LibraryName: "Име Библиотеке",
    Line: "Линија",
    LineTerminators: "Крајеви Линија",
    Links: "Линкови",
    Loading: "Учитавање...",
    LoadingCachedLayout: "Учитавање Кеширане Структуре...",
    LoadingData: "Учитавање Података...",
    loadingMessage: "...Учитавање...",
    LoadPackageContentHere: "(Добавите овамо садржај пакета)",
    LoadPackageFromFile: "Добавите Пакет из Датотеке",
    Local: "Локални",
    Log: "Дневник (Лог)",
    LogFile: "Датотека Активности",
    LoggedInAs: "Пријављен као",
    LogicalFile: "Логичка Датотека",
    LogicalFiles: "Логичке Датотеке",
    LogicalFilesAndSuperfiles: "Логичке Датотеке и Супердатотеке",
    LogicalFilesOnly: "Само Логичке Датотеке",
    LogicalFileType: "Тип Логичке Датотеке",
    LogicalName: "Име Логичке Датотеке",
    Logs: "Дневници",
    log_analysis_1: "лог_аналисис_1*",
    Low: "Низак",
    ManualCopy: "Притисните Ctrl+C",
    ManualOverviewSelection: "Нопходно Је Одабрати Преглед",
    ManualTreeSelection: "Нопходно Је Одабрати Дрво",
    Mappings: "Мапирања",
    Mask: "Маска",
    Max: "Максимум",
    MaxRecordLength: "Максимална Дужина Рекорда",
    MemberOf: "Члан Од",
    Members: "Чланови",
    Message: "Поруке",
    Min: "Минимум",
    Missing: "Недостаје",
    MixedNodeStates: "Сви Нодови Немају Исти Статус",
    Modification: "Промена",
    Modified: "Модификован",
    ModifiedUTCGMT: "Промењен (УТЦ/ГМТ)",
    Modify: "Промени",
    MonitorEventName: "Надгледајте Име Догађаја",
    MonitorShotLimit: "Надгледајте Шот Лимит",
    MonitorSub: "Надгледајте Суб",
    Month: "Месец",
    More: "Наставите",
    MustContainUppercaseAndSymbol: "Мораte укључити велико слово и симбол",
    NA: "Н/A",
    Name: "Име",
    NamePrefix: "Префикс Имена",
    NamePrefixPlaceholder: "неки::префиks",
    Newest: "Најнивији",
    NewPassword: "Нова Лозинка",
    NoContent: "(Без садржаја)",
    noDataMessage: "...Нема Редова...",
    Node: "Чвор (Нод)",
    NodeGroup: "Група Чворова",
    NoErrorFound: "Без нађених грешака\n",
    NoFilterCriteriaSpecified: "Критериј за филтрирање није специфициран.",
    None: "Ниједан",
    Normal: "Нормалан",
    NoScheduledEvents: "Нема Дефинисаних Догађаја (ивентс) на Распореду.",
    NoSplit: "Нема Подијела (Сплит)",
    NotActive: "Није Активан",
    NothingSelected: "Ништа Није Изабрано...",
    NotInSuperfiles: "Није Дио Супердатотеке",
    NotSuspendedbyUser: "Није Суспендован Од Стране Корисника",
    NoWarningFound: "Поруке Упозорења (вoрнингс) нису нађене\n",
    NumberofParts: "Број Делова",
    OK: "OK",
    Oldest: "Најстарији",
    OldPassword: "Стара Лозинка",
    OmitSeparator: "Изоставите Сепаратор",
    Only1PackageFileAllowed: "Дозвољен је само један пакет",
    Open: "Отворен",
    OpenInNewPage: "Отворите на Новој Страници",
    OpenInNewPageNoFrame: "Отворите на Новој Страници",
    OpenLegacyECLWatch: "Отворите Стари Превазиђени ЕЦЛ Вoч",
    OpenSafeMode: "Отворите (сигурни мод)",
    OpenSource: "Отворени Код",
    OpenTreeMode: "Отворите (као дрво)",
    Operations: "Операције",
    Options: "Опције",
    Outputs: "Излази",
    Overview: "Преглед",
    Overwrite: "Препишите",
    OverwriteMessage: "Неке Датотеке већ постоје. Да бисте наставили морате дозвилити писање преко постојећих датотека",
    Owner: "Власник",
    PackageContent: "Садржај Пакета",
    PackageContentNotSet: "Садржај Пакета није дефинисан",
    PackageMap: "Мапа Пакета",
    PackageMaps: "Мапe Пакета",
    PackagesNoQuery: "Пакети за које нису дефинисани упити (kуериз)",
    ParameterXML: "Параметар XМЛ",
    Part: "Дио",
    Parts: "Делови",
    Password: "Лозинка",
    PasswordExpiration: "Лозинка Истиће",
    PasswordExpired: "Ваша лозинка је истекла И мора бити промењена",
    PasswordExpirePostfix: "дан(а). Желите ли је сада променити?",
    PasswordExpirePrefix: "Ваша лозинка ће истећи за",
    PasswordOpenZAP: "Унесите Лозинку За ЗАП (необавезно)",
    PasswordsDoNotMatch: "Погрешна Лозинка.",
    Path: "Пут",
    PathMask: "Маска за Пут",
    Pause: "Пауза",
    PauseNow: "Зауставите Одмах",
    PctComplete: "% Комплетиран",
    PercentDone: "Проценат Завршен",
    PerformingLayout: "Извршава Лejaут...",
    PermissionName: "Назив Дозволе За Приступ",
    Permissions: "Дозволе за Приступ",
    PlaceholderFindText: "Pjид (Wuid), Корисник, Даље...",
    PlaceholderFirstName: "Џон",
    PlaceholderLastName: "Смит",
    Playground: "Игралиште",
    Plugins: "Допуне",
    Port: "Порт",
    Prefix: "Префикс",
    PrefixPlaceholder: "имедатотеке{:дужина}, величинадатотеке{:[B|L][1-8]}",
    Preview: "Преглед",
    Priority: "Приоритет",
    Process: "Процес",
    ProcessFilter: "Процес&nbsp;Филтер",
    ProgressMessage: "Порука о Прогресу",
    Properties: "Својства",
    Property: "Својствo",
    Protect: "Заштитите",
    Protected: "Заштићен",
    Publish: "Објавите",
    Published: "Објављен",
    PublishedBy: "Објављивач",
    PublishedQueries: "Објављени Упити",
    PushEvent: "Пуш Догађај",
    Quarter: "Четвртина",
    Queries: "Упити",
    QueriesNoPackage: "Упити без одговарајућег пакета",
    Query: "Упит",
    QueryDetailsfor: "Детаљи о Упиту",
    QueryID: "Идентификатор Упита",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Име Упита",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Колекција Упита",
    Queue: "Ред (Kjу)",
    Quote: "Цитат",
    QuotedTerminator: "Завршни Карактер",
    RawTextPage: "Необрађен Текст (Текућа Страница)",
    RecordCount: "Број Рекорда",
    RecordLength: "Дужина Рекорда",
    Records: "Рекорди",
    RecordSize: "Величина Рекорда",
    RecordStructurePresent: "Структура Рекорда Постоји",
    Recover: "Вратите Натраг",
    Refresh: "Освежите",
    ReleaseNotes: "Напомена о Издању",
    Reload: "Поново Учитајте",
    Remaining: "Преостали",
    RemoteCopy: "Копија са удаљеног сервера",
    RemoteDali: "Далеки Дали",
    RemoteDaliIP: "Далеки&nbsp;Дали&nbsp;ИП&nbsp;Адреса",
    Remove: "Уклоните",
    RemoveSubfiles: "Уклоните Поддатотеку",
    RemoveUser: "Уклоните Корисника",
    Rename: "Преименујте",
    RenderedSVG: "Донесене СВГ",
    RenderSVG: "Донесите СВГ",
    Replicate: "Реплицирајте",
    RequestSchema: "Шема Захтева",
    Reschedule: "Поново Ставите На Распоред",
    Reset: "Ресетујте",
    ResetThisQuery: "Ресетујте Текући Упит",
    ResetViewToSelection: "Ресетујте Одабрани Вју",
    Resource: "Ресурс",
    Resources: "Ресурси",
    ResponseSchema: "Шема Одговора",
    Restart: "Поново Покрените",
    Restarted: "Поново Поктернут",
    Restore: "Вратите на Старо Стање",
    Resubmit: "Поново Поднесите",
    Resubmitted: "Поново Послат",
    Results: "Резултат(и)",
    Resume: "Наставите",
    RetainSuperfileStructure: "Задржите Структуру Супердатотеке",
    RetypePassword: "Поновите Лозинку",
    Reverse: "Идите Уназад",
    RowPath: "Пут До Рекорда",
    Rows: "Редови",
    RowTag: "Етикета Реда",
    RoxieCluster: "Роkcи Кластер",
    Sample: "Пример",
    SampleRequest: "Пример Захтева",
    SampleResponse: "Пример Одговора",
    Save: "Сачувајте",
    Scope: "Подручје",
    SearchResults: "Резултати Претраживања",
    SecondsRemaining: "Преостало Секунди",
    Security: "Сигурност",
    SelectPackageFile: "Изаберитe Пакет",
    Separators: "Сеператори",
    SetBanner: "Поставите Заставицу",
    SetTextError: "Неуспешно приказивање текста (да ли је текст предуг?). Користите 'помагаче' за преузимање датотека.",
    SetToFailed: "Поставите На Неуспешан",
    Severity: "Озбиљност",
    Show: "Прокажите",
    ShowSVG: "Прокажите СВГ",
    Size: "Величина",
    Skew: "Скју",
    SLA: "СЛА",
    Slaves: "Робови (Слejвс)",
    Smallest: "Најмањи",
    SmallestFile: "Најмања Датотека",
    SmallestSize: "Најмања Величина",
    SOAP: "СОАП",
    SomeDescription: "Неки*Опис",
    somefile: "*::некифajл*",
    Source: "Изворна Верзија",
    SourceCode: "Изворна Верзија Кода",
    SourcePath: "Изворна Верзија Пута (са омогућеним *)",
    SourceProcess: "Изворни Процес",
    SplitPrefix: "Сплит Префикс",
    Spray: "Разбацајте (Спрej)",
    Start: "Почните",
    Started: "Почео",
    State: "Стање",
    Stats: "Статистике",
    Status: "Статус",
    Stopped: "Заустављен",
    Subgraph: "ПодГраф",
    Subgraphs: "Подграфикон",
    Submit: "Поднесите",
    Subtype: "ПодВрста",
    Summary: "Кратак Преглед",
    SummaryMessage: "Сажета Порука",
    SuperFile: "Супер Датотека",
    Superfile: "Супер Датотека",
    SuperFiles: "Супер Датотеке",
    Superfiles: "СуперДатотеке",
    SuperFilesBelongsTo: "Припадник Супердатотеке",
    SuperfilesOnly: "Само Супердатотеке",
    Suspend: "Суспендујте",
    Suspended: "Суспендован",
    SuspendedBy: "Суспендован Од",
    SuspendedByCluster: "Суспендован од стране кластера",
    SuspendedByUser: "Суспендован Од Стране Корисника",
    SuspendedReason: "Разлог за Суспендовање",
    SVGSource: "СВГ Извор",
    SyncSelection: "Синхронизујте Са Одабраним",
    SystemServers: "Систем Сервера",
    tag: "таг",
    Target: "Циљ",
    TargetClusters: "Циљни Кластери",
    TargetName: "Назив Циља",
    TargetNamePlaceholder: "неко::логићко::име",
    TargetWuid: "Циљ/Pjид",
    Terminators: "Терминатори",
    TestPages: "Тест Странице",
    Text: "Текст",
    ThorMasterAddress: "Адреса Главног Тора",
    ThorNetworkAddress: "Нетворк Адреса Торa",
    Time: "Време",
    Timers: "Мерачи Времена",
    TimeSeconds: "Време (Секунде)",
    TimeStarted: "Време Почетка",
    TimeStopped: "Време Краја",
    Timings: "Времена",
    TimingsMap: "Мапа Времена",
    title_Activity: "Активности",
    title_ClusterInfo: "Групе",
    title_DFUQuery: "Логичке Датотеке",
    title_DFUWUDetails: "ДФУ Радна Јединица",
    title_DiskUsage: "Искориштеност Диска",
    title_ECLPlayground: "ЕЦЛ Игралиште",
    title_EventScheduleWorkunit: "Распоређивач Догађаја",
    title_GetDFUWorkunits: "ДФУ Радне Јединице",
    title_Graph: "Графикон",
    title_GraphPage: "наслов",
    title_Graphs: "Графикони",
    title_GridDetails: "Промени Ме",
    title_HPCCPlatformECL: "ECL Watch - Главна Страница",
    title_HPCCPlatformFiles: "ECL Watch - Датотеке",
    title_HPCCPlatformMain: "ECL Watch - Главна Страница",
    title_HPCCPlatformOps: "ECL Watch - Управљње",
    title_HPCCPlatformRoxie: "ECL Watch - Роkcи",
    title_HPCCPlatformServicesPlugin: "ЕЦЛ Монитор - Допуне",
    title_Inputs: "Уноси",
    title_LFDetails: "Детаљи о Логичкоj Датотеци",
    title_LibrariesUsed: "Библиотеке У Кориштењу",
    title_Log: "Лог Фајл",
    title_LZBrowse: "Зона за Претовар",
    title_MemberOf: "Члан Од",
    title_Members: "Чланови",
    title_QuerySetDetails: "Детаљи Упита",
    title_QuerySetErrors: "Грешке",
    title_QuerySetLogicalFiles: "Логичке Датотеке",
    title_QuerySetQuery: "Упити (Kуериз)",
    title_QuerySetSuperFiles: "Супер Датотеке",
    title_QueryTest: "Супер Датотеке",
    title_Result: "Ацктивност",
    title_Results: "Резултати",
    title_SearchResults: "Резултати Претраживања",
    title_SourceFiles: "Оригиналне Датотеке",
    title_Topology: "Топологија",
    title_TpThorStatus: "Стање Тора",
    title_UserPermissions: "Корисничке Дозвиле за Приступ",
    title_UserQuery: "Права Приступа",
    title_WUDetails: "ЕЦЛ Детаљи о Радној Јединици",
    title_WUQuery: "ЕЦЛ Радне Јединице",
    To: "Према",
    ToDate: "До Сада",
    Toenablegraphviews: "Да бисте могли видети графиконе, мораћете инсталисати Граф Вjу Kонтрол плaгин",
    Top: "Врх",
    Topology: "Топологија",
    ToSizes: "До Величина",
    TotalClusterTime: "Укупно Време Кластера",
    TotalSize: "Укупна Величина",
    TotalThorTime: "Укупно Време Тора",
    TransitionGuide: "Водич",
    Tree: "Дрво",
    Type: "Тип",
    undefined: "недефинисан",
    Unknown: "Непознат",
    Unprotect: "Укините Заштиту",
    UnsupportedIE9FF: "Нису Подржани (ИЕ <= 9, ФиреФоx)",
    Unsuspend: "Укините Суспензију",
    Unsuspended: "Суспензија Укинута",
    Up: "На Горе",
    Upload: "Aплоyд",
    Usage: "Употреба",
    Used: "Кориштен",
    User: "Корисник",
    UserDetails: "Детаљи о Кориснику",
    UserID: "Корисницки ИД",
    UserName: "Име Корисника",
    Username: "Имекорисника",
    UserPermissions: "Дозволе за Корисников Приступ",
    Users: "Корисници",
    UseSingleConnection: "Користите Само Једaн Прикључак (конекшн)",
    Validate: "Потврдите",
    ValidateActivePackageMap: "Валидирајте Мапу Активног Пакета",
    ValidatePackageContent: "Валидирајте Саржај Пакета",
    ValidatePackageMap: "Потврдите Мапу Пакета",
    ValidateResult: "=====Потврдите Резултaт=====\n\n",
    ValidateResultHere: "(Резултати Валидирања)",
    Value: "Вредност",
    Variable: "Варијабла",
    VariableBigendian: "Варијабла Биг-ендиан",
    Variables: "Вариабле",
    VariableSourceType: "Тип Извора",
    Version: "Верзија",
    ViewByScope: "Поглед према Скопу",
    Views: "Погледи",
    Visualize: "Визуализујте",
    Warnings: "Упозорење(а)",
    WarnOldGraphControl: "Упозорење:  Стара Графичка Контрола",
    What: "Шта",
    Where: "Где",
    Who: "Ко",
    Width: "Ширина",
    Workflows: "Токови послова",
    Workunit: "Радна Јединица",
    Workunits: "Радне Јединице",
    Wrap: "Замотајте",
    WSDL: "WSDL",
    WUID: "PJИД",
    Wuidcannotbeempty: "Pjид Не Може Бити Празан.",
    WUSnapShot: "Тренутна Слика Радне Јединице",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Година",
    YourBrowserMayNotSupport: "Ваш претраживач можда не подржава датотеку (е) ове величине",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Нема ни једане Логичке Датотеке(проверите филтер)",
    Zip: "Запакујте (Зип)",
    ZippedAnalysisPackage: "Запаковани Пакет са Анализама",
    Zoom100Pct: "Зумирајте 100%",
    ZoomAll: "Зумирајте Све",
    ZoomWidth: "Зумирајте Ширину"
})
);
