#!/bin/bash

function _esp-api {

    local AVAILABLE_SERVICES=$(esp-api list-services 2>/dev/null)

    COMPREPLY=()
    local CURRENT_WORD=${COMP_WORDS[COMP_CWORD]}
    local SERVICE_NAME=${COMP_WORDS[2]}

    if [ "${COMP_CWORD}" -eq 1 ]; then
        COMPREPLY=($(compgen -W "describe test" -- $CURRENT_WORD))
    elif [ "${COMP_CWORD}"  -eq 2 ]
    then
        COMPREPLY=($( compgen -W "$AVAILABLE_SERVICES" -- $CURRENT_WORD ))
    elif [[ "${COMP_CWORD}" -eq 3 ]]
    then
        local METHODS=$(esp-api list-methods $SERVICE_NAME 2>/dev/null)
        if [ -n "$METHODS" ]; then
            COMPREPLY=($(compgen -W "$METHODS" -- $CURRENT_WORD))
        fi
    fi

}

complete -F _esp-api esp-api