#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################


if [ $# -lt 5 ]; then
    echo usage: $0 workdir newkeyfile oldkeyfile patchfile flagfile
    exit 1
fi
cd `dirname $0`
deploydir=`pwd`
mkdir -p $1
cd $1
rm -f $5
export PATH=$PATH:$deploydir
export LD_LIBRARY_PATH=$deploydir
keydiff -o -c $3 $2 $4 &>$5.log 
errcode = $?
if [ $errcode -ne 0 ]; then
   echo error=$errcode deploydir=$deploydir >> $5.log
   echo cmd = keydiff -o -c $3 $2 $4 >> $5.log
fi
mv -f $5.log $5
