# Values file to use when installing the hpcc-localfile chart that adds a plane
# for esdl bundles.

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  category: dali
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  category: dll
  rwmany: true
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  category: sasha
- name: debug
  subPath: debug
  size: 5Gi
  rwmany: true
  category: debug
- name: data
  subPath: hpcc-data # cannot currently be changed
  size: 3Gi
  category: data # NB: all "data" planes will be auto mounted by engine components and others that require access to data
  rwmany: true
- name: mydropzone
  subPath: mydropzone
  size: 1Gi
  rwmany: true
  category: lz
- name: esdl
  subPath: esdl
  size: 1Gi
  category: data
