#!/bin/sh
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################


ulimit -c unlimited

# dont lower limit
moflim=$(ulimit -n 2>/dev/null)
if [ -n "$moflim" ]
then
    if [ "$moflim" != "unlimited" ]
    then
        if [ $moflim -lt 8192 ]
        then
            ulimit -n 8192
        fi
    fi
else
    ulimit -n 8192
fi

export SENTINEL="eclagent.sentinel"
nohup hthor $* &
