/*##############################################################################

    Copyright (C) 2011 HPCC Systems.

    All rights reserved. This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################## */

pattern employee := [
        'Adam Rubin',
        'Agnes Jasik',
        'Agustin Bruno',
        'Ajit Deshpante',
        'Alan Matlock',
        'Alastair Measure',
        'Allan Botwinick',
        'Alan Jackson',
        'Amparin Querido',
        'Andrea Roman',
        'Andrei Wilson',
        'Ani Chahande',
        'Anthony Fishbeck',
        'Anthony Scott',
        'Anthony Tyson',
        'Armando Escalante',
        'Ashasa Fail',
        'Barbara Johnson',
        'Barry Messner',
        'Ben Patipa',
        'Ben Ray    ',
        'Benjamin Ng',
        'Bill Haas',
        'Bill Ostrander',
        'Bill Rodriquez',
        'Bill Shrewsbury',
        'Bill Vilanueva',
        'Billy McCauley',
        'Bonnie Turner',
        'Brad Johnson',
        'Brandon Amchin',
        'Brennon Hamilton',
        'Brian Conte',
        'Brian Knowles',
        'Brian Neill',
        'Bruce Goldberg',
        'Bruce McQueary',
        'Caren Galiardo',
        'Carol Nosek',
        'Carolyn Anderson',
        'Caryn Cipes',
        'Cathy DeMarco',
        'Chantalle Poitras',
        'Charles Morton',
        'Charles Pettola',
        'Charlie Schmidt',
        'Charmaine Lowe',
        'Chris Duffield',
        'Chris Niemer',
        'Christiane Breton',
        'Christina Heintz',
        'Chuck Tiner',
        'Chuck Tyner',
        'Clare Southcombe',
        'Claudia Hwang',
        'Claudio Amaral',
        'Dale Jundt',
        'Dale Renner',
        'Dan Bauer',
        'Dan Latham',
        'Dan McGuire',
        'Dara McGrath',
        'Darryl Goodwin',
        'David Bayliss',
        'David Boudreau',
        'David Ferber',
        'David Fuselier',
        'Dawn Roman',
        'Deborah Brown',
        'Debra Winkleman',
        'Derek Plansky',
        'Dermot O',
        'Desiree Asher',
        'Diana Santiago',
        'Dmitry Hudyakov',
        'Don Lowe',
        'Don Wiesenmiller',
        'Donald Nappi',
        'Dong Lam',
        'Dwight Gorall',
        'Ed Epperson',
        'Ed Hazen',
        'Ed McNally',
        'Elyssa Neiberg',
        'Emily Coulter',
        'Eric Montanez',
        'Eric Palomino',
        'Eric Robbins',
        'Erika Husemann',
        'Fernando Meleon',
        'Fernando Uceta',
        'Flavio Villanute',
        'Gary Arnold',
        'Gavin Halliday',
        'George Cardile',
        'Glenn Putchel',
        'Gordon Smith',
        'Greg Anderson',
        'Greg Concors',
        'Greg Fortman',
        'Greg Fries',
        'Greg Wood',
        'Gregg Strauss',
        'Hank Asher',
        'Heath Owens',
        'Helen Fries',
        'Helen Fuselier',
        'Jack Carchio',
        'Jack Rand',
        'Jackie Spence',
        'Jaclyn Beamer',
        'Jacob Scherer',
        'Jake Smith',
        'James Clark',
        'James DeFabia',
        'James Diamond',
        'Jan Repko',
        'Jarod Jacobs',
        'Jason Hess',
        'Jay Gann',
        'Jay Roth   ',
        'Jay Scherer',
        'Jay Smouse',
        'Jeanine Lembo',
        'Jeff Dell  ',
        'Jeff Bisbee',
        'Jeff Granitz',
        'Jeff Portz',
        'Jeron Kelley',
        'Jerry Lerner',
        'Jessica Jacobson',
        'Jiafu Gao',
        'Jianjun Oung',
        'Jill Tolbert',
        'Jim Barnes',
        'Jim Swift',
        'Joe Van',
        'John Abdo',
        'John Lofquist',
        'John Moore',
        'John Nash',
        'John Windle',
        'Jon Burger',
        'Jon Rosenberg',
        'Jorge Hurtado',
        'Jorge Mon',
        'Jose Bouza',
        'Joseph Anguille',
        'Joseph Lezcano',
        'Joseph Lofquist',
        'Joseph Selma',
        'Joshua Rubin',
        'Joy Itoman',
        'Juan Medina',
        'Karen Kaufman',
        'Karl Scherer',
        'Keith Brown',
        'Kelly Hamilton',
        'Kelly Ramsey',
        'Ken Bryson',
        'Ken Foglia',
        'Ken Kurzweil',
        'Ken Schwartz',
        'Ken Wagner',
        'Kevin Barry',
        'Kevin Cavanaugh',
        'Khandra Mayorga',
        'Kim Hester',
        'Kimberly Lynch',
        'Kurt France',
        'Lac Cosentine',
        'Latoya Boland',
        'Lavinia Ricketts',
        'Lawrence Klein',
        'Lee Lindquest',
        'Leon Gorkovenko',
        'Leslie Cosentine',
        'Lewis Stone',
        'Lika Ciocanel',
        'Lisa Indelicato',
        'Lisa Liberski',
        'Lisa Simmons',
        'Lloyd Lande',
        'Lon Mannes',
        'London Fax',
        'Lorie Kornfeld',
        'Luciana Gandarillo',
        'Luciane Barroca',
        'Lynn Dalmer',
        'Mac McCauley',
        'Marian Jackson',
        'Marie Molinaro',
        'Mark Loizzo',
        'Martin Clary',
        'Marty Hackett',
        'Mary Ann',
        'Matthew Porter',
        'Maureen Smith',
        'Michael Cooper',
        'Michael Finn',
        'Michael Sareceno',
        'Michele Rosen',
        'Michelle Biglow',
        'Michelle Kessler',
        'Michelle Owens',
        'Mike Berk',
        'Mike Boocher',
        'Mike Kozlowski',
        'Mike Ledet',
        'Mike Wyman',
        'Mike Yeschek',
        'Misty Clary',
        'Monet Colbert',
        'Mourad Mechour',
        'Nan Rooney',
        'Nick Finelli',
        'Nigel Hicks',
        'Nitza Miro',
        'Nora Martinez',
        'Pam Oppenheim',
        'Paul Avella',
        'Paul Cameron',
        'Paul Kapp',
        'Paulette Ankeney',
        'Peter Bellomo',
        'Peter Waterman',
        'Phil Parr  ',
        'Prakash Kailasa',
        'Rachael Seifer',
        'Rajeev Moondhra',
        'Ray Cherry',
        'Reggie Beavers',
        'Roeeie Stennett',
        'Rhonda Rosen',
        'Richard Blake',
        'Richard Chapman',
        'Richard Farretta',
        'Richard Valente',
        'Rick Castillo',
        'Rick Trainor',
        'Robert Altadonna',
        'Robert Baron',
        'Robert Burke',
        'Robert Cohen',
        'Robin Starr',
        'Roger Walker',
        'Robert Van',
        'Robin Starr',
        'Ron Holbrook',
        'Ron Snyder',
        'Ronald Harp',
        'Roni Kaylin',
        'Rosario Alfaya',
        'Roy Bourdeaux',
        'Roy Hawkes',
        'Satish Shankarappa',
        'Scott Brutsche',
        'Scott Farretta',
        'Scott Kelley',
        'Scott Kelly',
        'Scott Pfeffer',
        'Scott Reveh',
        'Scott Schneck',
        'Scott Wagner',
        'Security Desk',
        'Selim Esen',
        'Shari Mallett',
        'Shep Parke',
        'Shirley Vega',
        'Stephanie Burke',
        'Steve Racioppo',
        'Stuart Ort',
        'Susan Reed',
        'Susan Sanabria',
        'Suzanne Louissainte',
        'Tammy Saville',
        'Telra Moore',
        'Temen Williams',
        'Tim Klipsic',
        'Thomas Hardy',
        'Todd Hinton',
        'Tom Gallow',
        'Tom Gardner',
        'Thomas Hardy',
        'Tony Middleton',
        'Tom Moseley',
        'Tony Ratti',
        'Trenton Kriete',
        'Troy Groover',
        'Uzra Khandker',
        'Valerie Prokop',
        'Vannessa Mattesich',
        'Vern Bentley',
        'Vesa Niemela',
        'Victor Tavernini',
        'Walter Purvis',
        'Wayne Schlegel',
        'William Rodriguez',
        'Yamille Del',
        'Yanrui Ma'
        ];


pattern search := (first|' ') employee (last|[' ','.','?']);

infile := dataset([
        {''},
        {'Adam Rubin'},
        {'Adam Rubin'},
        {'Adam Rubin'},
        {' Adam Rubin'},
        {' Adam Rubin'},
        {' Adam Rubin'},
        {'I hate gavin Halliday, at least i think I do said Yanrui Ma.'},
        {'Richard Chapman, David Bayliss and Nigel Hicks cause the most trouble.'},
        {'I think it was Tom Moseley who started it all off, but maybe it was Tammy Saville'}
        ], { string text });


results := 
    record
        (string50)MATCHTEXT(employee);
    end;

x := PARSE(infile,text,search,results,scan,nocase);

output(x);
