#The values file can be used to add the filebeat.filebeatConfig.filebeat.yml[output.elasticsearch.pipeline]: 'hpccpipeline' setting
#Which instructs filebeat to process all messages destined to Elastic Search to be processed by the pipeline 'hpccpipeline'.
#Warning: hpccpipeline must exist on target Elastic Search, or log data loss could occur
##See https://github.com/hpcc-systems/HPCC-Platform/blob/master/helm/managed/logging/elastic/README.md
filebeat:
  description: "HPCC Managed filebeat"
  ##See https://github.com/elastic/helm-charts/blob/master/filebeat/values.yaml for all available options
  labels: {"managedby" : "HPCC"}
  ## Allows you to add any config files in /usr/share/filebeat
  ## such as filebeat.yml
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/esdl-sandbox-*.log
          - /var/log/containers/eclwatch-*.log
          - /var/log/containers/mydali-*.log
          - /var/log/containers/eclqueries-*.log
          - /var/log/containers/sql2ecl-*.log
          - /var/log/containers/eclservices-*.log
          - /var/log/containers/dfuserver-*.log
          - /var/log/containers/eclscheduler-*.log
          - /var/log/containers/hthor-*.log
          - /var/log/containers/myeclccserver-*.log
          - /var/log/containers/roxie-*.log
          - /var/log/containers/sasha-*.log
          - /var/log/containers/thor-*.log
        #exclude_files: ['(myelk-kibana|myelk-filebeat)+(.*).log']
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
       #Required if targeting non-default index (filebeat-%{[agent.version]}-%{+yyyy.MM.dd}) such as hpcc-log-%{+yyyy.MM.dd}, etc.
       #setup.ilm.enabled: false
       #setup.template.overwrite: true
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
      #NOTE: Pipeline could be used to provide Log structure and therefore enhance search capabilities of HPCC component log entries
      #      Pipeline must be manually inserted either via Elastic Search API, or Kibana Pipeline ingest UI.
      #      See https://github.com/hpcc-systems/HPCC-Platform/blob/master/helm/managed/logging/elastic/README.md
        pipeline: 'hpccpipeline'
      #  index: "hpccsystems-%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}"
      #setup.template.name: hpccsystems
      #setup.template.pattern: hpccsystems-*
      #setup.template.enabled: true