define({ root:
//begin v1.x content
({
    title: "Logical Files",

    Add: "Add",
    AddToSuperfile: "Add To Superfile",
    Append: "Append",
    Cluster: "Cluster",
    Compress: "Compress",
    Copy: "Copy",
    Dali: "Dali",
    DeleteSelectedFiles: "Delete Selected Files?",
    Delimited: "Delimited",
    Description: "Description",
    Despray: "Despray",
    DropZone: "Drop Zone",
    Escape: "Escape",
    FileType: "File Type",
    Fixed: "Fixed",
    Format: "Format",
    FromDate: "From Date",
    FromSizes: "From Sizes",
    Group: "Group",
    Import: "Import",
    IP: "IP",
    IPAddress: "IP Address",
    JSmith: "JSmit*",
    Label: "Label",
    Largest: "Largest",
    LastNDays: "Last N Days",
    LineTerminators: "Line Terminators",
    LogicalFile: "Logical File",
    LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
    LogicalFilesOnly: "Logical Files Only",
    LogicalName: "Logical Name",
    Mask: "Mask",
    MaxRecordLength: "Max Record Length",
    ModifiedUTCGMT: "Modified (UTC/GMT)",
    NA: "N/A",
    Name: "Name",
    Newest: "Newest",
    NoFilterCriteriaSpecified: "No filter criteria specified.",
    NoSplit: "No Split",
    NoSplit: "No Split",
    NotInSuperfiles: "Not in Superfiles",
    Oldest: "Oldest",
    OmitSeparator: "Omit Separator",
    Options: "Options",
    Overwrite: "Overwrite",
    Owner: "Owner",
    Parts: "Parts",
    Password: "Password",
    Path: "Path",
    Prefix: "Prefix",
    Quote: "Quote",
    RecordLength: "Record Length",
    Records: "Records",
    Rename: "Rename",
    Replicate: "Replicate",
    RetainSuperfileStructure: "Retain Superfile Structure",
    RowTag: "Row Tag",
    Seperators: "Seperators",
    Size: "Size",
    Smallest: "Smallest",
    SomeDescription: "Some*Description",
    somefile: "*::somefile*",
    Source: "Source",
    SplitPrefix: "Split Prefix",
    Spray: "Spray",
    SuperFile: "Super File",
    SuperfilesOnly: "Superfiles Only",
    tag: "tag",
    Target: "Target",
    TargetName: "Target Name",
    ToDate: "To Date",
    ToSizes: "To Sizes",
    UserID: "User ID",
    UseSingleConnection: "Use Single Connection",
    Wrap: "Wrap",
    XML: "XML",
    ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)"
})
//end v1.x content
,
"es": true,
"zh": true,
"hu": true
});
