define({ root:
//begin v1.x content
({
    title: "Landing Zones",

    Compress: "Compress",
    Date: "Date",
    DeleteSelectedFiles: "Delete Selected Files?",
    Delimited: "Delimited",
    Download: "Download",
    Errorparsingserverresult: "Error parsing server result",
    Escape: "Escape",
    FileUploader: "File Uploader",
    Fixed: "Fixed",
    Format: "Format",
    Group: "Group",
    HexPreview: "Hex Preview",
    RECFM: "RECFM",
    RECFMPrefix: "RECFM Prefix",
    RECFMSourceType: "RECFM Source Type",
    Label: "Label",
    LandingZone: "Landing Zone",
    LineTerminators: "Line Terminators",
    Mask: "Mask",
    MaxRecordLength: "Max Record Length",
    Name: "Name",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    NoSplit: "No Split",
    OmitSeparator: "Omit Separator",
    Options: "Options",
    Overwrite: "Overwrite",
    Prefix: "Prefix",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Quote: "Quote",
    RecordLength: "Record Length",
    RowTag: "Row Tag",
    Seperators: "Seperators",
    Size: "Size",
    Source: "Source",
    Spray: "Spray",
    Start: "Start",
    tag: "tag",
    Target: "Target",
    TargetName: "Target Name",
    Upload: "Upload",
    XML: "XML"
})
//end v1.x content
,
"es": true,
"zh": true
});
