define({ root:
//begin v1.x content
({
    title: "Permissions",

    Add: "Add",
    AddGroup: "Add Group",
    AddUser: "Add User",
    AllowAccess: "<center>Allow<br>Access",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    Cancel: "Cancel",
    ConfirmPassword: "Confirm Password",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DenyAccess: "<center>Deny<br>Access",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Edit: "Edit",
    FirstName: "First Name",
    FullName: "Full Name",
    GroupDetails: "Group Details",
    GroupName: "Group Name",
    GroupPermissions: "Group Permissions",
    Groups: "Groups",
    LastName: "Last Name",
    MemberOf: "Member Of",
    Members: "Members",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    Name: "Name",
    NewPassword: "New Password",
    Open: "Open",
    Password: "Password",
    PasswordsDoNotMatch: "Passwords do not match.",
    PasswordExpiration: "Password Expiration",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Resource: "Resource",
    RetypePassword: "Retype Password",
    Save: "Save",
    Summary: "Summary",
    UserDetails: "User Details",
    UserID: "User ID",
    UserName: "User Name",
    Username: "Username",
    UserPermissions: "User Permissions",
    Users: "Users"
})
//end v1.x content
,
"es": true,
"zh": true,
"hu": true
});
