# Overrides for storage in hpcc, using host directories.
# NB: The "hpcc-localfile" helm charts should be installed 1st.
# The "hpcc-localfile" helm chart provisions and creates the
# PVC's required by HPCC mapped to directories on the host.
# The pvc names are dynamic based on the install name.
# In this example the install name was "localfile"

#The following is a generated values yaml that you can capture and feed to the hpcc helm chart when installing.
#it will configure the hpcc storage to use the planes and pvcs installed by this chart.
#e.g.:
#helm install myhpcc hpcc/hpcc --set global.image.version=latest --values values-localfile.yaml

storage:
  planes:
  - name: dali
    pvc: dali-localfile-hpcc-localfile-pvc
    prefix: "/var/lib/HPCCSystems/dalistorage"
    labels:
    - dali

  - name: dll
    pvc: dll-localfile-hpcc-localfile-pvc
    prefix: "/var/lib/HPCCSystems/queries"
    labels:
    - dll

  - name: sasha
    pvc: sasha-localfile-hpcc-localfile-pvc
    prefix: "/var/lib/HPCCSystems/sasha"
    labels:
    - sasha

  - name: data
    pvc: data-localfile-hpcc-localfile-pvc
    prefix: "/var/lib/HPCCSystems/hpcc-data"
    labels:
    - data # NB: if not set, this would be the default

  - name: mydropzone
    pvc: mydropzone-localfile-hpcc-localfile-pvc
    prefix: "/var/lib/HPCCSystems/dropzone"
    labels:
    - lz


  daliStorage:
    plane: dali

  dllStorage:
    plane: dll

  dataStorage:
    plane: data

sasha:
  wu-archiver:
    storage:
      plane: sasha
  dfuwu-archiver:
    storage:
      plane: sasha
