#! /usr/bin/perl

################################################################################
#
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems(R).
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#################################################################################

use strict;
use warnings;
use FindBin qw/$Bin/;
use lib ($Bin);
use IndexMetadata;

die('Usage: readmeta indexfile [indexfile2 ...]') unless(@ARGV);
print("$_:\n", IndexMetadata::readfile($_) || "no metadata\n") foreach(@ARGV);
