# Overrides for storage in hpcc hpcc, using efs PVC's.
# NB: The "hpcc-efs" helm charts should be installed 1st.
#
# The "hpcc-efs" helm chart provisions and creates the
# PVC's required by HPCC.
# The pvc names are dynamic based on the install name.
# In this example the install name was "efsstorage"

storage:
  dllStorage:
    existingClaim: dll-efsstorage-hpcc-efs-pvc

  daliStorage:
    existingClaim: dali-efsstorage-hpcc-efs-pvc

  dataStorage:
    existingClaim: data-efsstorage-hpcc-efs-pvc
