{{ range $.Values.eclccserver -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      run: {{ .name | quote }}
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
    spec:
      serviceAccountName: hpcc
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 600 }}
      {{- include "hpcc.checkDllServerHostMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ .name | quote }}
        args: [
                {{ include "hpcc.configArg" . }},
                {{ include "hpcc.daliArg" $ }}
              ]
{{ include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "eclccserver") | indent 8 }}
{{ include "hpcc.addVolumeMounts" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigVolume" . | indent 6 }}
{{ include "hpcc.addVolumes" $ | indent 6 }}
---
{{- include "hpcc.generateConfigMap" (dict "root" $ "component" "eclccserver" "me" .) }}
      queues:
{{- range $.Values.eclagent }}
      - name: {{ .name }}
        type: {{ .type | default "hthor" }}
        prefix: {{ .prefix | default "null" }}
{{- end -}}
{{- range $.Values.roxie }}
      - name: {{ .name }}
        type: roxie 
        prefix: {{ .prefix | default "null" }}
{{- end -}}
{{- range $.Values.thor }}
      - name: {{ .name }}
        type: thor
        prefix: {{ .prefix | default "null" }}
{{- end }}
  eclccserver-jobspec.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: %jobname
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: %jobname
            image: {{ include "hpcc.imageName" (dict "root" $ "me" . "imagename" "eclccserver") }}
            resources:
              requests:
                #request-memory
                #request-cpu
              limits:
                #limit-memory
                #limit-cpu
            command: [
                        "eclccserver",
                        {{ include "hpcc.configArg" . }},
                        {{ include "hpcc.daliArg" $ }},
                        %args
                     ]
{{ include "hpcc.addVolumeMounts" . | indent 12 }}
          volumes:
{{ include "hpcc.addConfigVolume" . | indent 10 }}
{{ include "hpcc.addVolumes" $ | indent 10 }}
          restartPolicy: Never
      backoffLimit: 0
      
---
{{- end }}
