{{ range $roxie := $.Values.roxie -}}
{{- if not $roxie.disabled  -}}
{{- if $roxie.localSlave -}}
{{- $name := $roxie.name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $roxie.name | quote }}
spec:
  replicas: {{ $roxie.serverReplicas | default 1 }}
  selector:
    matchLabels:
      run: {{ $roxie.name | quote }}
  template:
    metadata:
      labels:
        run: {{ $roxie.name | quote }}
    spec:
      {{- include "hpcc.checkDataStorageHostMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ $roxie.name | quote }}
        args: [
                {{ include "hpcc.configArg" $roxie }},
                {{ include "hpcc.daliArg" $ }},
                "--serverPorts={{ template "hpcc.portListToCommas" $roxie.ports }}", 
                "--localSlave=true",
                "--resolveLocally=false"
              ]
{{- include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "roxie") | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" . | indent 8 }}
{{ include "hpcc.addDataVolumeMount" . | indent 8 }}
{{ include "hpcc.addDllserverVolumeMount" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigMapVolume" . | indent 6 }}
{{ include "hpcc.addDataVolume" $ | indent 6 }}
{{ include "hpcc.addDllserverVolume" $ | indent 6 }}
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ $roxie.name }}-configmap 
data:
  {{ $roxie.name }}.yaml: |
    version: 1.0
    roxie:
{{ toYaml $roxie | indent 6 }}
    global:
{{ include "hpcc.generateGlobalConfigMap" $ | indent 6 }}
---
{{- end }}
{{- end }}
{{- end }}
