{{ range $roxie := $.Values.roxie -}}
{{- if not $roxie.disabled -}}
{{- if not $roxie.localSlave -}}
{{- $toponame := printf "%s-toposerver" $roxie.name -}}
{{- $numChannels := $roxie.numChannels | int | default 1 -}}
{{- $topoport := $roxie.topoport | int | default 9004 -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $toponame | quote }}
spec:
  replicas: {{ $roxie.topoReplicas | default 1 }}
  selector:
    matchLabels:
      run: {{ $toponame | quote }}
  template:
    metadata:
      labels:
        run: {{ $toponame | quote }}
    spec:
      containers:
      - name: {{ $toponame | quote }}
{{- include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" $roxie "imagename" "toposerver") | indent 8 }}
        volumeMounts:
        - name: {{ .name }}-configmap-volume
          mountPath: /etc/config
      volumes:
      - name: {{ .name }}-configmap-volume
        configMap:
          name: {{ .name }}-configmap
---

apiVersion: v1
kind: Service
metadata:
  name: {{ $toponame | quote }}
spec:
  ports:
  - port: {{ $topoport  }}
    protocol: TCP
    targetPort: {{ $topoport }}
  selector:
    run: {{ $toponame | quote }}
  clusterIP: None # Headless service

---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ $roxie.name }}-configmap 
data:
  {{ $roxie.name }}.yaml: |
    version: 1.0
    roxie:
{{ toYaml $roxie | indent 6 }}
    global:
{{ include "hpcc.generateGlobalConfigMap" $ | indent 6 }}
---

{{ if $roxie.serverReplicas -}}
{{- $servername := printf "%s-server" $roxie.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $servername | quote }}
spec:
  replicas: {{ $roxie.serverReplicas }}
  selector:
    matchLabels:
      run: {{ $servername | quote }}
  template:
    metadata:
      labels:
        run: {{ $servername | quote }}
    spec:
      {{- include "hpcc.checkDataStorageHostMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ $servername | quote }}
        args: [
                {{ include "hpcc.configArg" . }},
                {{ include "hpcc.daliArg" $ }},
                "--numChannels={{ $numChannels }}",
                "--serverPorts={{ template "hpcc.portListToCommas" $roxie.ports }}", 
                "--topologyServers={{ $toponame }}:{{ $roxie.topoport }}",
                "--resolveLocally=false"
              ]
{{ include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" $roxie "imagename" "roxie") | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" $roxie | indent 8 }}
{{ include "hpcc.addDataVolumeMount" . | indent 8 }}
{{ include "hpcc.addDllserverVolumeMount" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigMapVolume" $roxie | indent 6 }}
{{ include "hpcc.addDataVolume" $ | indent 6 }}
{{ include "hpcc.addDllserverVolume" $ | indent 6 }}
---

{{ end -}}
{{ range $c, $e := until ($roxie.numChannels|int) -}}
{{- $channel := add $c 1 -}}
{{- $name := printf "%s-slave-%d" $roxie.name $channel -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name | quote}}
spec:
  replicas: {{ $roxie.channelReplicas | default 2 }}
  selector:
    matchLabels:
      run: {{ $name | quote}}
  template:
    metadata:
      labels:
        run: {{ $name | quote}}
    spec:
      {{- include "hpcc.checkDataStorageHostMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ $name | quote}}
        args: [ 
                {{ include "hpcc.configArg" $roxie }},
                {{ include "hpcc.daliArg" $ }},
                "--channels={{ $channel }}", 
                "--serverPorts={{ if not $roxie.serverReplicas }}{{ template "hpcc.portListToCommas" $roxie.ports }}{{ end }}",
                "--numChannels={{ $numChannels }}",
                "--topologyServers={{ $toponame }}:{{ $roxie.topoport }}",
              ]
{{ include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" $roxie "imagename" "roxie") | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" $roxie | indent 8 }}
{{ include "hpcc.addDataVolumeMount" $roxie | indent 8 }}
{{ include "hpcc.addDllserverVolumeMount" $roxie | indent 8 }}
      volumes:
{{ include "hpcc.addConfigMapVolume" $roxie | indent 6 }}
{{ include "hpcc.addDataVolume" $ | indent 6 }}
{{ include "hpcc.addDllserverVolume" $ | indent 6 }}

---

{{- end }}
{{- end }}
{{- end }}
{{- end }}
 
