{{ range $thor := $.Values.thor -}}
{{- if not $thor.disabled -}}
{{- $masterPort := $thor.masterport | default 20000 -}}
{{- $slavePort := $thor.slaveport | default 20100 -}}
{{- $eclagentName := printf "%s-agent" .name }}
{{- $slaveName := printf "%s-slave" .name }}
{{- $serviceName := printf "%s-svc" .name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $eclagentName | quote }}
spec:
  replicas: {{ $thor.eclagent.replicas | default 1 }}
  selector:
    matchLabels:
      run: {{ $eclagentName | quote }}
  template:
    metadata:
      labels:
        run: {{ $eclagentName | quote }}
    spec:
      serviceAccountName: hpcc
      containers:
      - name: {{ $eclagentName | quote }}
        ports:
          - containerPort: {{ $masterPort }}
        args: [
                {{ include "hpcc.configArg" . }},
                {{ include "hpcc.daliArg" $ }}
              ]
{{ include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "eclagent") | indent 8 }}
{{ include "hpcc.addVolumeMounts" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigVolume" . | indent 6 }}
{{ include "hpcc.addVolumes" $ | indent 6 }}
---
{{- include "hpcc.generateConfigMap" (dict "root" $ "component" "thor" "me" .) }}
{{- if $thor.eclagent }}
    eclagent:
      name: {{ .name }}
{{ toYaml $thor.eclagent | indent 6 }}
{{- end }}
  eclagent-jobspec.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: %jobname
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          serviceAccountName: hpcc
          {{- include "hpcc.checkDataStorageHostMount" (dict "root" $) | indent 10 }}
          containers:
          - name: %jobname
            image: {{ include "hpcc.imageName" (dict "root" $ "me" . "imagename" "eclagent") }}
            resources:
              requests:
                #request-memory
                #request-cpu
              limits:
                #limit-memory
                #limit-cpu
            command: [
                        "eclagent",
                        {{ include "hpcc.configArg" . }},
                        {{ include "hpcc.daliArg" $ }},
                        %args
                     ]
{{ include "hpcc.addVolumeMounts" . | indent 12 }}
          volumes:
{{ include "hpcc.addConfigVolume" . | indent 10 }}
{{ include "hpcc.addVolumes" $ | indent 10 }}
          restartPolicy: Never
      backoffLimit: 0
  thormaster-jobspec.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: %jobname
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          serviceAccountName: hpcc
          {{- include "hpcc.checkDataStorageHostMount" (dict "root" $) | indent 10 }}
          containers:
          - name: %jobname
{{ include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 12 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "thormaster") | indent 12 }}
            args: [
                    {{ include "hpcc.configArg" . }},
                    {{ include "hpcc.daliArg" $ }},
                    %args
                  ]
{{ include "hpcc.addVolumeMounts" . | indent 12 }}
          volumes:
{{ include "hpcc.addConfigVolume" . | indent 10 }}
{{ include "hpcc.addVolumes" $ | indent 10 }}
          restartPolicy: Never
      backoffLimit: 0
  thorslave-jobspec.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: %jobname
    spec:
      parallelism: {{ $thor.numSlaves }}
      ttlSecondsAfterFinished: 100
      template:
        spec:
          serviceAccountName: hpcc
          containers:
          - name: %jobname
{{ include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 12 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "thorslave") | indent 12 }}
            args: [
                    {{ include "hpcc.configArg" . }},
                    {{ include "hpcc.daliArg" $ }},
                    %args
                  ]
{{ include "hpcc.addVolumeMounts" . | indent 12 }}
          volumes:
{{ include "hpcc.addConfigVolume" . | indent 10 }}
{{ include "hpcc.addVolumes" $ | indent 10 }}
          restartPolicy: Never
      backoffLimit: 0
---
{{- end }}
{{- end }}
