# Overrides for storage in hpcc hpcc, using nfs PVC's.
# NB: The "hpcc-nfs" helm charts should be installed 1st.
#
# The "hpcc-nfs" helm chart provisions and creates the
# PVC's required by HPCC.
# The pvc names are dynamic based on the install name.
# In this example the install name was "nfsstorage"
storage:
  planes:
  - name: dali
    pvc: dali-nfsstorage-hpcc-nfs-pvc
    prefix: "/var/lib/HPCCSystems/dalistorage"
    category: dali

  - name: dll
    pvc: dll-nfsstorage-hpcc-nfs-pvc
    prefix: "/var/lib/HPCCSystems/queries"
    category: dll

  - name: sasha
    pvc: sasha-nfsstorage-hpcc-nfs-pvc
    prefix: "/var/lib/HPCCSystems/sasha"
    category: sasha
    forcePermissions: true

  - name: data
    pvc: data-nfsstorage-hpcc-nfs-pvc
    prefix: "/var/lib/HPCCSystems/hpcc-data"
    category: data

sasha:
  wu-archiver:
    plane: sasha
  dfuwu-archiver:
    plane: sasha
