define(
({
    Abort: "Prekinite",
    About: "O Aplikaciji",
    AboutGraphControl: "O Grafičkoj Kontroli",
    AboutHPCCSystemsGraphControl: "O Grafičkoj Kontroli HPCC Sistema",
    Action: "Akcija",
    Activate: "Aktivirajte",
    Activated: "Aktiviran",
    Active: "Aktivan",
    ActivePackageMap: "Aktivna Mapa Paketa",
    ActiveWorkunit: "Aktivna Radna Jedinica",
    Activities: "Aktivnosti",
    Activity: "Aktivnost",
    ActualSize: "Tačna Veličina",
    Add: "Dodajte",
    AddGroup: "Dodajte Grupu",
    AddProcessMap: "Dodajte Mapu Paketa",
    AddToSuperfile: "Dodajte na Superdatoteku",
    AddUser: "Dodajte Korisnika",
    Advanced: "Višeg Nivoa",
    AllowAccess: "<center>Dozvolite<br>Pristup",
    AllowFull: "<center>Dozvolite<br>Potpun</center>",
    AllowRead: "<center>Dozvolite<br>čitanje</center>",
    AllowWrite: "<center>Dozvolite<br>Pisanje</center>",
    ANY: "Bilo Koji",
    Append: "Dodajte",
    Apply: "Primijenite",
    ArchivedOnly: "Samo Arhiviran",
    BinaryInstalls: "Binarne Instalacije",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefiks",
    Cancel: "Poništite",
    Clear: "Očistite",
    Clone: "Klonirajte",
    Close: "Zatvorite",
    Cluster: "Klaster",
    ClusterName: "Ime Klastera",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesi Na Klasteru",
    Code: "Kod",
    Col: "Kolona",
    Command: "Komanda",
    Comment: "Komentar",
    Completed: "Kompletiran",
    Component: "Komponenta",
    Compress: "Sabijte",
    ConfirmPassword: "Potvrdite Lozinku",
    Contents: "Sadržaji",
    Copy: "Kopirajte",
    Count: "Izbrojte",
    Created: "Proizveden",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Datum",
    Deactivate: "Iskljućite",
    DEF: "DEF",
    Delete: "Obrišite",
    DeleteSelectedFiles: "Obrišite Odabrane Datoteke?",
    DeleteSelectedGroups: "Obrišite odabranu(e) grupu(e)?",
    DeleteSelectedQueries: "Obrišite Odabrane Zahtjeve?",
    DeleteSelectedUsers: "Obrišite Odabrane Korisnike?",
    DeleteSelectedWorkunits: "Obrišite Odabrane Radne Jedinice?",
    DeleteSuperfile: "Obrišite Superdatoteke?",
    DeleteThisPackage: "Obrišite ovaj paket?",
    Delimited: "Razgraničen",
    DenyAccess: "<center>Zabranite<br>Pristup",
    DenyFull: "<center>Zabranite<br>Potpun</center>",
    DenyRead: "<center>Zabranite<br>čitanje</center>",
    DenyWrite: "<center>Zabranite<br>Pisanje</center>",
    Depth: "Dubina",
    Deschedule: "Izbacite Is Reda Za Izvršavanje",
    DescheduleSelectedWorkunits: "Izbacite Odabrane Radne Jedinice Is Reda Za Izvršavanje?",
    Description: "Opis",
    Despray: "Ponovo Objedinite Datoteku",
    DFUServerName: "Ime DFU Servera",
    Directory: "Direktorij",
    Distance: "Razdaljina",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Atributi",
    Download: "Dobavite",
    DropZone: "Zona Prijema",
    Duration: "Trajanje",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "Ivice",
    Edit: "Editujte",
    EditDOT: "Editujte DOT",
    EditGraphAttributes: "Editujte Atribute Grafova",
    EditXGMML: "Editujte XGMML",
    Empty: "(Prazan)",
    Error: "Greška",
    Errorparsingserverresult: "Greška u analizi rezultata sa servera",
    Errors: "Greška(e)",
    Errors: "Greške",
    ErrorsStatus: "Greške/Stanje",
    ErrorWarnings: "Greška/Upozorenja",
    Escape: "Escape",
    ESPBuildVersion: "ESP Trenutna Verzija",
    ESPNetworkAddress: "ESP Netvork Adresa",
    EventName: "Ime Događaja",
    EventNamePH: "imedogađaja",
    EventScheduler: "Raspoređivać Događaja",
    EventText: "Opis Događaja",
    Exception: "Neočekivani Problem",
    FetchingData: "U Procesu Dobavljnja Podataka...",
    fetchingresults: "dobijeni resultati",
    File: "Datoteka",
    FileName: "Ime Datoteke",
    FileParts: "Dio Datoteke",
    FilePath: "Lokacija Datoteke",
    Files: "Datoteke",
    FileSize: "Veličina Datoteke",
    FilesNoPackage: "Datoteke koje ne pripadaju paketu",
    FileType: "Tip Datoteke",
    FileUploader: "Proces za premiještanje Datoteke na Server (Uploader)",
    Filter: "Filter",
    Find: "Nađite",
    FindNext: "Nađite Slijedeći",
    FindPrevious: "Nađite Prethodni",
    FirstName: "Ime",
    Fixed: "Fiksni",
    Format: "Format",
    FromDate: "Od Datuma",
    FromSizes: "Od Veličine",
    FullName: "Ime i Prezime",
    Graphs: "Grafikoni",
    GraphView: "Slika Grafikona",
    Group: "Grupa",
    GroupDetails: "Detalji o Grupi",
    GroupName: "Naziv Grupe",
    GroupPermissions: "Dozvole za Pristup Grupe",
    Groups: "Grupe",
    GZip: "GZip",
    help: "Ovdje je prikazan grafikon izvršavanja ove radne jedinice. Veličina i nijansa ukazuju na vrijeme izvršavanja svakog grafikona (Veći i tamniji grafikon uzima veći procenat cjelokupnog vremena izvrštavanja.)",
    Helpers: "Pomagaći",
    Hex: "Baza16",
    History: "Istorija",
    HPCCSystems: "HPCC Systems",
    ID: "Identifikator",
    Import: "Uvoz",
    Info: "Informacija",
    InfoDialog: "Dijalog Informacije",
    Inputs: "Unosi",
    InvalidResponse: "(Neispravan Odgovor)",
    IP: "IP",
    IPAddress: "IP Adresa",
    IsLibrary: "Je Biblioteka",
    Jobname: "Nazivradnejedinice",
    JobName: "Naziv Radne Jedinice",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Etiketa",
    LandingZone: "Zona za Pretovar",
    LandingZones: "Zone za Pretovar",
    Largest: "Najveći",
    LastName: "Prezime",
    LastNDays: "Poslijednjih N Dana",
    LegacyForm: "Stari Prevaziđeni Formular",
    LibrariesUsed: "Biblioteke u Korištenju",
    Line: "Linija",
    LineTerminators: "Krajevi Linija",
    Links: "Linkovi",
    Loading: "Učitavanje...",
    LoadingCachedLayout: "Učitavanje Keširane Strukture (Cached Layout)...",
    LoadingData: "Učitavanje Podataka...",
    loadingMessage: "...Učitavanje...",
    Local: "Lokalni",
    LoggedInAs: "Prijavljen kao",
    LogicalFile: "Logička Datoteka",
    LogicalFiles: "Logičke Datoteke",
    LogicalFilesAndSuperfiles: "Logičke Datoteke i Superdatoteke",
    LogicalFilesOnly: "Samo Logičke Datoteke",
    LogicalFileType: "Tip Logičke Datoteke",
    LogicalName: "Ime Logičke Datoteke",
    log_analysis_1: "log_analysis_1*",
    Mappings: "Mapiranja",
    Mask: "Maska",
    Max: "Maksimum",
    MaxRecordLength: "Maksimalna Dužina Rekorda",
    MemberOf: "Član Od",
    Members: "Članovi",
    Message: "Poruke",
    Min: "Minimum",
    Modification: "Promijena",
    ModifiedUTCGMT: "Promijenjen (UTC/GMT)",
    Modify: "Promijeni",
    MonitorEventName: "Nadgledajte Ime Događaja",
    MonitorShotLimit: "Nadgledajte Shot Limit",
    MonitorSub: "Nadgledajte Sub",
    MustContainUppercaseAndSymbol: "Mora uključiti veliko slovo i simbol",
    NA: "N/A",
    Name: "Ime",
    NamePrefix: "Prefiks Imena",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Najniviji",
    NewPassword: "Nova Lozinka",
    NoContent: "(Bez sadržaja)",
    noDataMessage: "...Nema Redova...",
    Node: "čvor (Node)",
    NoErrorFound: "Bez nađenih grešaka\n",
    NoFilterCriteriaSpecified: "Kriterij za filtriranje nije specificiran.",
    NoScheduledEvents: "Nema Definisanih Događaja na Rasporedu.",
    NoSplit: "Nema Podijela (Split)",
    NotActive: "Nije Aktivan",
    NothingSelected: "Ništa Nije Izabrano...",
    NotInSuperfiles: "Nije Dio Superdatoteke",
    NoWarningFound: "Poruke Upozorenja (warnings) nisu nađene\n",
    NumberofParts: "Broj Dijelova",
    OK: "OK",
    Oldest: "Najstariji",
    OmitSeparator: "Izostavite Separator",
    Only1PackageFileAllowed: "Dozvoljen je samo jedan paket",
    Open: "Otvoren",
    OpenInNewPage: "Otvorite na Novoj Stranici",
    OpenLegacyECLWatch: "Otvorite Stari Prevaziđeni ECL Watch",
    OpenSafeMode: "Otvorite (sigurni mod)",
    Operations: "Operacije",
    Options: "Opcije",
    Outputs: "Izlazi",
    Overview: "Pregled",
    Overwrite: "Prepišite",
    Owner: "Vlasnik",
    PackageContent: "Sadržaj Paketa",
    PackageContentNotSet: "Sadržaj Paketa nije definisan",
    PackageMap: "Mapa Paketa",
    PackageMaps: "Mape Paketa",
    PackagesNoQuery: "Paketi za koje nisu definisani upiti (queries)",
    ParameterXML: "Parametar XML",
    Parts: "Dijelovi",
    Password: "Lozinka",
    PasswordExpiration: "Lozinka Istiće",
    PasswordsDoNotMatch: "Pogrešna Lozinka.",
    Path: "Put",
    PathMask: "Maska za Put",
    PctComplete: "% Kompletiran",
    PercentDone: "Procenat Završen",
    PerformingLayout: "Izvršava Layout...",
    Permissions: "Dozvole za Pristup",
    PlaceholderFindText: "Wuid, Korisnik, Dalje...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Igralište",
    Prefix: "Prefiks",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preview: "Pregled",
    Priority: "Prioritet",
    Process: "Proces",
    ProcessFilter: "Process&nbsp;Filter",
    ProgressMessage: "Poruka o Progresu",
    Properties: "Svojstva",
    Property: "Svojstvo",
    Protect: "Zaštitite",
    Protected: "Zašticen",
    Publish: "Objavite",
    PublishedBy: "Objavljivač",
    PublishedQueries: "Objavljeni Upiti",
    Queries: "Upiti",
    QueriesNoPackage: "Upiti bez odgovarajućeg paketa",
    QueryDetailsfor: "Detalji o Upitu",
    QuerySet: "Kolekcija Upita",
    Queue: "Red (Queue)",
    Quote: "Citat",
    RecordCount: "Broj Rekorda",
    RecordLength: "Dužina Rekorda",
    Records: "Rekordi",
    RecordSize: "Veličina Rekorda",
    Refresh: "Osviježite",
    ReleaseNotes: "Napomena o Izdanju",
    Reload: "Ponovo Učitajte",
    RemoteDali: "Daleki Dali",
    RemoteDaliIP: "Daleki&nbsp;Dali&nbsp;IP&nbsp;Adresa",
    Remove: "Uklonite",
    Rename: "Preimenujte",
    RenderedSVG: "Donesene SVG",
    RenderSVG: "Donesite SVG",
    Replicate: "Replicirajte",
    RequestSchema: "Shema Zahtjeva",
    Reschedule: "Ponovo Stavite Na Raspored",
    Reset: "Resetujte",
    Resource: "Resurs",
    Resources: "Resursi",
    ResponseSchema: "Shema Odgovora",
    Restart: "Ponovo Pokrenite",
    Resubmit: "Ponovo Podnesite",
    Results: "Rezultat(i)",
    RetainSuperfileStructure: "Zadržite Strukturu Superdatoteke",
    RetypePassword: "Ponovite Lozinku",
    Rows: "Redovi",
    RowTag: "Etiketa Reda",
    RoxieCluster: "Roxie Klaster",
    Sample: "Primjer",
    SampleRequest: "Primjer Zahtjeva",
    SampleResponse: "Primjer Odgovora",
    Save: "Sačuvajte",
    Scope: "Područje",
    SearchResults: "Rezultati Pretraživanja",
    SecondsRemaining: "Preostalo Sekundi",
    SelectPackageFile: "Izaberi Paket",
    Seperators: "Seperatori",
    SetBanner: "Postavite Zastavicu",
    SetToFailed: "Postavite Na Neuspješan",
    Severity: "Ozbiljnost",
    Show: "Prokažite",
    ShowSVG: "Prokažite SVG",
    Size: "Veličina",
    Skew: "Skju (Skew)",
    Slaves: "Robovi (Slaves)",
    Smallest: "Najmanji",
    SOAP: "SOAP",
    SomeDescription: "Neki*Opis",
    somefile: "*::nekifile*",
    Source: "Izvorna Verzija",
    SourceCode: "Izvorna Verzija Koda",
    SourcePath: "Izvorna Verzija Puta (sa omogucenim *)",
    SplitPrefix: "Split Prefiks",
    Spray: "Razbacajte (Spray)",
    Start: "Počnite",
    Started: "Počeo",
    State: "Stanje",
    Stopped: "Zaustavljen",
    Subgraphs: "Podgrafikon",
    Submit: "Podnesite",
    Summary: "Kratak Pregled",
    SummaryMessage: "Sažeta Poruka",
    SuperFile: "Super Datoteka",
    SuperfilesOnly: "Samo Superdatoteke",
    Suspend: "Suspendujte",
    Suspended: "Suspendovan",
    SuspendedBy: "Suspendovan Od",
    SVGSource: "SVG Izvor",
    SyncSelection: "Sinhronizujte Sa Odabranim",
    SystemServers: "Sistem Servera",
    tag: "tag",
    Target: "Cilj",
    TargetClusters: "Ciljni Klasteri",
    TargetName: "Naziv Cilja",
    TargetNamePlaceholder: "neko::logicko::ime",
    TargetWuid: "Cilj/Wuid",
    Terminators: "Terminatori",
    TestPages: "Test Stranice",
    ThorNetworkAddress: "Thor Netvork Adresa",
    Time: "Vrijeme",
    TimeSeconds: "Vrijeme (Sekunde)",
    TimeStarted: "Vrijeme Pocetka",
    TimeStopped: "Vrijeme Kraja",
    Timings: "Vremena",
    TimingsMap: "Mapa Vremena",
    title_Activity: "Aktivnosti",
    title_DFUQuery: "Logičke Datoteke",
    title_DFUWUDetails: "DFU Radna Jedinica",
    title_ECLPlayground: "ECL Igralište",
    title_EventScheduleWorkunit: "Respoređivać Događaja",
    title_GetDFUWorkunits: "DFU Radne Jedinice",
    title_Graph: "Grafikon",
    title_GraphPage: "naslov",
    title_Graphs: "Grafikoni",
    title_GridDetails: "Promijeni Me",
    title_HPCCPlatformECL: "HPCC Platform - Glavna Stranica",
    title_HPCCPlatformFiles: "HPCC Platform - Datoteke",
    title_HPCCPlatformMain: "HPCC Platform - Glavna Stranica",
    title_HPCCPlatformOps: "HPCC Platform - Upravljnje",
    title_HPCCPlatformRoxie: "HPCC Platform - Roxie",
    title_LFDetails: "Detalji o Logičkol Datoteci",
    title_LZBrowse: "Zona za Pretovar",
    title_QuerySetDetails: "Detalji Upita",
    title_QuerySetErrors: "Greške",
    title_QuerySetLogicalFiles: "Logičke Datoteke",
    title_QuerySetQuery: "Upiti (Queries)",
    title_QuerySetSuperFiles: "Super Datoteke",
    title_QueryTest: "Super Datoteke",
    title_Result: "Acktivnost",
    title_Results: "Rezultati",
    title_SearchResults: "Rezultati Pretraživanja",
    title_SourceFiles: "",
    title_UserQuery: "Prava Pristupa",
    title_WUDetails: "ECL Detalji o Radnoj Jedinici",
    title_WUQuery: "ECL Radne Jedinice",
    ToDate: "Do Sada",
    Toenablegraphviews: "Da biste mogli vidjeli grafikone, moraćete instalisati Graph View Control plugin",
    ToSizes: "Do Velićina",
    TotalThorTime: "Ukupno Vrijeme Thor-a",
    Type: "Tip",
    undefined: "nedefinisan",
    Unknown: "Nepoznat",
    Unprotect: "Ukinite Zaštitu",
    Unsuspend: "Ukinite Suspenziju",
    Unsuspended: "Suspenzija Ukinuta",
    Upload: "Upload",
    Used: "Korišten",
    User: "Korisnik",
    UserDetails: "Detalji o Korisniku",
    UserID: "Korisnicki ID",
    Username: "Imekorisnika",
    UserName: "Ime Korisnika",
    UserPermissions: "Dozvole za Korisnikov Pristup",
    Users: "Korisnici",
    UseSingleConnection: "Koristite Samo Jednu Priključak (Connection)",
    Validate: "Potvrdite",
    ValidatePackageMap: "Potvrdite Mapu Paketa",
    ValidateResult: "=====Potvrdite Result=====\n\n",
    Value: "Vrijednost",
    Variable: "Varijabla",
    VariableBigendian: "Varijabla Big-endian",
    VariableSourceType: "Tip Izvora",
    Version: "Verzija",
    Views: "Pogledi",
    Visualize: "Visualizujte",
    Warnings: "Upozorenje(a)",
    WarnOldGraphControl: "Upozorenje:  Stara Graficka Kontrola",
    Width: "Širina",
    Workunit: "Radna Jedinica",
    Workunits: "Radne Jedinice",
    Wrap: "Zamotajte",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Ne Može Biti Prazan.",
    WUSnapShot: "Trenutna Slika Radne Jedinice",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nema ni jedane Logičke Datoteke(provjerite filter)",
    Zip: "Zapakujte (Zip)",
    ZippedAnalysisPackage: "Zapakovani Paket sa Analizama",
    Zoom100Pct: "Zumirajte 100%",
    ZoomAll: "Zumirajte Sve",
    ZoomWidth: "Zumirajte Širinu"
})
);
