define(
({
    Abort: "Prekinite",
    AbortedBy: "Prekinuto od strane",
    AbortedTime: "Vrijeme prekida",
    About: "O Aplikaciji",
    AboutGraphControl: "O Grafičkoj Kontroli",
    AboutHPCCSystemsGraphControl: "O Grafičkoj Kontroli HPCC Sistema",
    Account: "Račun",
    Action: "Akcija",
    Activate: "Aktivirajte",
    Activated: "Aktiviran",
    Active: "Aktivan",
    ActivePackageMap: "Aktivna Mapa Paketa",
    ActiveWorkunit: "Aktivna Radna Jedinica",
    Activities: "Aktivnosti",
    Activity: "Aktivnost",
    ActivityMap: "Mapa Aktivnosti",
    ActualSize: "Tačna Veličina",
    Add: "Dodajte",
    AddAttributes2: "Dodajte Atribut(e)",
    AddAttributes: "Dodajte atribute/vrijednosti vašem metodu",
    AddBinding: "Dodajte Vezivanje",
    AddFile: "Dodajte Datoteku",
    AddGroup: "Dodajte Grupu",
    AdditionalResources: "Dodatni Resursi",
    AddPart: "Dodajte Dio",
    AddProcessMap: "Dodajte Mapu Paketa",
    AddtionalProcessesToFilter: "Dodatni Procesi Za Filtriranje",
    AddTheseFilesToDali: "Dodajte Te Datoteke na Dali",
    AddToExistingSuperfile: "Dodajte na postojeći superfajl",
    AddToSuperfile: "Dodajte na Superdatoteku",
    AddUser: "Dodajte Korisnika",
    Advanced: "Višeg Nivoa",
    All: "Svi",
    AllowAccess: "<center>Dozvolite<br>Pristup</center>",
    AllowForeignFiles: "Dozvolite Korištenje  Datoteka Sa Drugih Klastera",
    AllowFull: "<center>Dozvolite<br>Potpun</center>",
    AllowRead: "<center>Dozvolite<br>Čitanje</center>",
    AllowWrite: "<center>Dozvolite<br>Pisanje</center>",
    AllQueuedItemsCleared: "Svi poslovi iz reda čekanja su očišćeni. Trenutno aktivni posao nastavnja sa izvršavanjem.",
    ANY: "Bilo Koji",
    AnyAdditionalProcessesToFilter: "Ima li još procesa za filtriranje",
    Append: "Dodajte",
    AppendCluster: "Dodajte Klaster",
    Apply: "Primjenite",
    ArchivedOnly: "Samo Arhiviran",
    ArchivedWarning: "Upozorenje: koristite kratak vremenski period. Ako koristite duži vremenski period, pretraživanje radnih jedinica može trajati duže od dozviljenog vremena za pretraživanje .",
    Attach: "Prikačite",
    Attribute: "Atribut",
    AttributesAreRequired: "Atributi su potrebni",
    AutoRefresh: "Osvježi",
    AutoRefreshEvery: "Automatsko osvježivanje svakih x minuta",
    AutoRefreshIncrement: "Automatski korak osvježivanja",
    Back: "Nazad",
    BannerColor: "Boja Reklamnog Bloka",
    BannerMessage: "Poruka za Reklamni Blok",
    BannerScroll: "Kretanje Reklamnog Bloka",
    BannerSize: "Veličina Reklamnog Bloka",
    BinaryInstalls: "Binarne Instalacije",
    Binding: "Vezivanje",
    BindingDeleted: "Vezivanje Obrisano",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefiks",
    Bottom: "Kraj",
    Busy: "Zauzet",
    Cancel: "Poništite",
    CancelAll: "Ukinite Sve",
    CancelAllMessage: "Prekinite tekuće poslove i očistite red čekanja. Želite li nastaviti?",
    CheckAllNodes: "Provjerite Sve Nodove/Čvorove",
    CheckFilePermissions: "Provjerite Dozvole za Pristup Datoteci",
    CheckSingleNode: "Provjerite Jedan Nod/Čvor",
    Clear: "Očistite",
    ClearPermissionsCache: "Izbrišite Zapamćene Dozvole Za Pristup",
    ClearPermissionsCacheConfirm: "Da li ste sigurni da želite da izbrišete zapamćene dozvole za pristup na DALI i ESP? To može značajno usporiti izvršavanje radnih jedinica.",
    Clone: "Klonirajte",
    ClonedWUID: "Klonirani WUID",
    CloneTooltip: "Kopirajte Radnu Jedinicu",
    Close: "Zatvorite",
    Cluster: "Klaster",
    ClusterName: "Ime Klastera",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesi Na Klasteru",
    Code: "Kod",
    CodeGenerator: "Kod Generator",
    Col: "Kolona",
    CollapseAll: "Suzite sve",
    Command: "Komanda",
    Comment: "Komentar",
    Completed: "Kompletiran",
    ComplexityWarning: "Više od praga {threshold} aktivnosti ({activityCount}) - zaustavite prikaz podataka?",
    Component: "Komponenta",
    Compress: "Sabijte",
    Compressed: "Komprimirani",
    CompressedFileSize: "Komprimirana Veličina Datoteke",
    Condition: "Uslov",
    Configuration: "Konfiguracija",
    ConfirmPassword: "Potvrdite Lozinku",
    ConfirmRemoval: "Jeste li sigurni da to želite učiniti?",
    ContactAdmin: "Ako želite promijeniti naziv ove grupe, kontaktirajte administratora LDAP.",
    Content: "Sadržaj",
    Contents: "Sadržaji",
    ContentType: "Vrsta Sadržaja",
    Copy: "Kopirajte",
    Count: "Izbrojte",
    CreateANewFile: "Kreirajte novi superfile",
    Created: "Proizveden",
    Critical: "Kritično",
    CSV: "CSV",
    Dali: "Dali",
    DaliIP: "Dali IP adresa",
    dataset: ":=dataset*",
    Date: "Datum",
    Day: "Dan",
    Deactivate: "Isključite",
    Debug: "Otklonite Neispravnosti",
    DEF: "DEF",
    Defaults: "Unaprijed Definisane Vrijednosti",
    Definition: "Definicija",
    Definitions: "Definicije",
    Delete: "Obrišite",
    DeleteBinding: "Izbrišite Vezivanje",
    Deleted: "Izbrisan",
    DeletedBinding: "Izbrisano Vezivanje",
    DeleteDirectories: "Eliminišite prazne direktirije. Želite li nastaviti?",
    DeleteEmptyDirectories: "Želite li izbrisati prazne direktorije?",
    DeletePrevious: "Izbrišite Prethodni",
    DeleteSelectedFiles: "Obrišite Odabrane Datoteke?",
    DeleteSelectedGroups: "Obrišite odabranu(e) grupu(e)?",
    DeleteSelectedPermissions: "Obrišite Odabrane Dozvole Za Pristup",
    DeleteSelectedQueries: "Obrišite Odabrane Zahtjeve?",
    DeleteSelectedUsers: "Obrišite Odabrane Korisnike?",
    DeleteSelectedWorkunits: "Obrišite Odabrane Radne Jedinice?",
    DeleteSuperfile2: "Izbrišite Super Datoteku",
    DeleteSuperfile: "Obrišite Superdatoteke?",
    DeleteThisPackage: "Obrišite ovaj paket?",
    Delimited: "Razgraničen",
    DenyAccess: "<center>Zabranite<br>Pristup</center>",
    DenyFull: "<center>Zabranite<br>Potpun</center>",
    DenyRead: "<center>Zabranite<br>Čitanje</center>",
    DenyWrite: "<center>Zabranite<br>Pisanje</center>",
    Depth: "Dubina",
    DepthTooltip: "Najveća Dubina Podgrafa",
    Deschedule: "Izbacite Is Reda Za Izvršavanje",
    DescheduleSelectedWorkunits: "Izbacite Odabrane Radne Jedinice Is Reda Za Izvršavanje?",
    Description: "Opis",
    DESDL: "Dinamički ESDL",
    Despray: "Ponovo Objedinite Datoteku",
    Details: "Detalji",
    DFUServerName: "Ime DFU Servera",
    DFUWorkunit: "DFU RadnaJedinica",
    Directories: "Direktorije",
    Directory: "Direktorij",
    DisableScopeScanConfirm: "Da li ste sigurni da želite da onemogućite skaniranje opsega? Promjene će biti prihvaćene poslije restarta DALIja",
    DisableScopeScans: "Onemogućite Skaniranje Opsega",
    DiskUsage: "Iskorištenost Diska",
    Distance: "Razdaljina",
    DistanceTooltip: "Maksimalna Veličina Podgrafa Za Izabranu Aktivnost",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "DOT Atributi",
    Down: "Neaktivan",
    Download: "Dobavite",
    Downloads: "Preuzimanje",
    DownloadToCSV: "Preuzmite u CSV formatu",
    DropZone: "Zona Prijema",
    Duration: "Trajanje",
    DynamicNoServicesFound: "Servisi Nisu Pronađeni",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    ECLWorkunit: "ECL RadnaJedinica",
    Edges: "Ivice",
    Edit: "Editujte",
    EditDOT: "Editujte DOT",
    EditGraphAttributes: "Editujte Atribute Grafova",
    EditXGMML: "Editujte XGMML",
    EmployeeID: "ID Radnika",
    Empty: "(Prazan)",
    Enable: "Omogućite",
    EnableScopeScans: "Omogućite Skaniranje Opsega",
    EnableScopeScansConfirm: "Da li ste sigurni da želite da omogućite skaniranje opsega? Promjene će biti prihvaćene poslije restarta DALIja",
    EnglishQ: "Engleski?",
    EnterAPercentage: "Unesite procenat",
    EnterAPercentageOrMB: "Unesite Procenat ili MB",
    EraseHistory: "Izbrišite Istoriju",
    EraseHistoryQ: "Izbrišite Istoriju Za",
    Error: "Greška",
    Errorparsingserverresult: "Greška u analizi rezultata sa servera",
    Errors: "Greške",
    ErrorsStatus: "Greške/Stanje",
    ErrorUploadingFile: "Greška prilikom prenosa datoteke(a). Pokušajte provjeriti dozvole za prenos.",
    ErrorWarnings: "Greška/Upozorenja",
    Escape: "Escape",
    ESPBuildVersion: "ESP Trenutna Verzija",
    ESPNetworkAddress: "ESP Netvork Adresa",
    EventName: "Ime Događaja",
    EventNamePH: "imedogađaja",
    EventScheduler: "Raspoređivač Događaja",
    EventText: "Opis Događaja",
    EventTextPH: "Tekst O Događaju",
    Exception: "Neočekivani Problem",
    ExpandAll: "Proširite sve",
    Export: "Izvezite",
    ExportSelectionsToList: "Izvezite Odabrane Stvari u Listu",
    FailIfNoSourceFile: "Neuspjeh Ukoliko Datoteka Ne Postoji",
    Fatal: "Fatalan",
    Fetched: "Preuzet",
    FetchingData: "U Procesu Dobavljnja Podataka...",
    fetchingresults: "dobijeni resultati",
    File: "Datoteka",
    FileCluster: "Klaster Datoteka",
    FileCounts: "Broj Datoteka",
    FileName: "Ime Datoteke",
    FileParts: "Dio Datoteke",
    FilePath: "Lokacija Datoteke",
    FilesPending: "Datoteke u toku",
    FilePermission: "Dozvola Za Pristup Datoteci",
    Files: "Datoteke",
    FileScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor Datoteka",
    FileScopes: "Skop Datoteka",
    FileSize: "Veličina Datoteke",
    FilesNoPackage: "Datoteke koje ne pripadaju paketu",
    FilesWithUnknownSize: "Datoteke Sa Nepoznatim Veličinama",
    FileType: "Tip Datoteke",
    FileUploader: "Proces za premiještanje Datoteke na Server (Uploader)",
    FileUploadStillInProgress: "Učitavanje Datoteka je u Toku",
    Filter: "Filter",
    FilterSet: "Definisanje Filtera",
    Find: "Nađite",
    FindNext: "Nađite Slijedeći",
    FindPrevious: "Nađite Prethodni",
    Finished: "Završen",
    FirstName: "Ime",
    FirstNRows: "Prvih N Redova",
    Fixed: "Fiksni",
    Folder: "Fascikla",
    Format: "Format",
    Forums: "Forumi",
    Forward: "Naprijed",
    FoundFile: "Fajl Je Pronađen",
    FoundFileMessage: "Pronađeni fajl ima sve svoje dijelove na disku, ali dijelovi nisu poznati Dali serveru. Svi dijelovi fajla mogu biti dodani nazad na Dali server. Dijelovi mogu biti I obrisani sa klastera ako je to potrebno.",
    FromDate: "Od Datuma",
    FromSizes: "Od Veličine",
    FromTime: "Od Vremena",
    FullName: "Ime i Prezime",
    Generate: "Generišite",
    GetPart: "Dobavite Dio",
    GetSoftwareInformation: "Želite li dobiti informacije o softveru",
    Graph: "Graf",
    Graphs: "Grafikoni",
    GraphView: "Slika Grafikona",
    Group: "Grupa",
    GroupBy: "Grupišite Po",
    GroupDetails: "Detalji o Grupi",
    Grouping: "Grupisanje",
    GroupName: "Naziv Grupe",
    GroupPermissions: "Dozvole za Pristup Grupe",
    Groups: "Grupe",
    GZip: "GZip",
    help: "Ovdje je prikazan grafikon izvršavanja ove radne jedinice. Veličina i nijansa ukazuju na vrijeme izvršavanja svakog grafikona (Veći i tamniji grafikon uzima veći procenat cjelokupnog vremena izvrštavanja.)",
    Helper: "Pomoćnik",
    Helpers: "Pomagači",
    Hex: "Baza16",
    HideSpills: "Sakrijte Upotrebu Diska",
    High: "Visok",
    History: "Istorija",
    HPCCSystems: "HPCC Systems®",
    Icon: "Ikona",
    ID: "Identifikator",
    Inactive: "Neaktivan",
    IncludeSlaveLogs: "Uključite Izvještaje Sa Nodova Izvršilaca",
    Index: "Indeks",
    Info: "Informacija",
    InfoDialog: "Dijalog Informacije",
    InheritedPermissions: "Naslijeđene Dozvole",
    Inputs: "Unosi",
    InvalidResponse: "(Neispravan Odgovor)",
    IP: "IP",
    IPAddress: "IP Adresa",
    IsCompressed: "Je li Sabijen",
    IsLibrary: "Jeli Biblioteka",
    IsReplicated: "Repliciran",
    IssueReporting: "Izvještavanje o Problemima",
    Jobname: "Nazivradnejedinice",
    JobName: "Naziv Radne Jedinice",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    KeyFile: "Indeksirana Datoteka",
    Label: "Etiketa",
    LandingZone: "Zona za Pretovar",
    LandingZones: "Zone za Pretovar",
    LanguageFiles: "Datoteke O Jeziku",
    Largest: "Najveći",
    LargestFile: "Najveća Datoteka",
    LargestSize: "Najveća veličina",
    LastMessage: "Zadnja Poruka",
    LastName: "Prezime",
    LastNDays: "Poslijednjih N Dana",
    LastNHours: "Posljednjih N Sati",
    LastNRows: "Posljednjih N Redova",
    LastRun: "Zadnji Ran",
    LDAPWarning: "<b>Greška LDAP Servica:</b>  &lsquo;Previše korisnika&rsquo; - Molimo koristite filter.",
    LegacyForm: "Stari Prevaziđeni Formular",
    LibrariesUsed: "Biblioteke u Korištenju",
    LibraryName: "Ime Biblioteke",
    Line: "Linija",
    LineTerminators: "Krajevi Linija",
    Links: "Linkovi",
    Loading: "Učitavanje...",
    LoadingCachedLayout: "Učitavanje Keširane Strukture (Cached Layout)...",
    LoadingData: "Učitavanje Podataka...",
    loadingMessage: "...Učitavanje...",
    LoadPackageContentHere: "(Dobavite ovamo sadržaj paketa)",
    LoadPackageFromFile: "Dobavite Paket iz Datoteke",
    Local: "Lokalni",
    LocalFileSystemsOnly: "Samo Lokalni Fajl Sistemi",
    Location: "Lokacija",
    Log: "Dnevnik (Log)",
    LogFile: "Datoteka Aktivnosti",
    LoggedInAs: "Prijavljen kao",
    LogicalFile: "Logička Datoteka",
    LogicalFiles: "Logičke Datoteke",
    LogicalFilesAndSuperfiles: "Logičke Datoteke i Superdatoteke",
    LogicalFilesOnly: "Samo Logičke Datoteke",
    LogicalFileType: "Tip Logičke Datoteke",
    LogicalName: "Ime Logičke Datoteke",
    Logs: "Dnevnici",
    log_analysis_1: "log_analysis_1*",
    LostFile2: "Izgubljeni Fajlovi",
    LostFile: "Izgubljeni Fajl",
    LostFileMessage: "Logički fajl kome nedostaje bar jedan dio ili na primarnoj ili na repliciranoj lokaciji na disku.  Logički file je još uvijek pod kontrolom Dali servera. Brisanje fajla prekida kontrolu Dali servera nad fajlom kao i nad svim preostalim dijelovima fajla na disku.",
    Low: "Nizak",
    MachineInformation: "Informacija o Mašini",
    Machines: "Mašine",
    Major: "Glavni",
    ManagedBy: "Upravljan",
    ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
    ManualCopy: "Pritisnite Ctrl+C",
    ManualOverviewSelection: "Nophodno Je Odabrati Pregled",
    ManualTreeSelection: "Nophodno Je Odabrati Drvo",
    Mappings: "Mapiranja",
    Mask: "Maska",
    Max: "Maksimum",
    MaximumNumberOfSlaves: "Maksimalan Broj Izvršilaca",
    MaxNode: "Maksimalni Nod/čvor",
    MaxRecordLength: "Maksimalna Dužina Rekorda",
    MaxSize: "Maksimalna Veličina",
    MemberOf: "Član Od",
    Members: "Članovi",
    Message: "Poruke",
    MethodConfiguration: "Konfiguracija metoda",
    Methods: "Metodi",
    Min: "Minimum",
    MinNode: "Minimalni Nod/čvor",
    Minor: "Minoran",
    MinSize: "Minimalna Veličina",
    Missing: "Nedostaje",
    MixedNodeStates: "Svi Nodovi Nemaju Isti Status ",
    Modification: "Promijena",
    Modified: "Modifikovan",
    ModifiedUTCGMT: "Promijenjen (UTC/GMT)",
    Modify: "Promijeni",
    MonitorEventName: "Nadgledajte Ime Događaja",
    Monitoring: "Nadgledanje",
    MonitorShotLimit: "Nadgledajte Shot Limit",
    MonitorSub: "Nadgledajte Sub",
    Month: "Mjesec",
    More: "Nastavite",
    MustContainUppercaseAndSymbol: "Mora uključiti veliko slovo i simbol",
    NA: "N/A",
    Name: "Ime",
    NamePrefix: "Prefiks Imena",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Najnoviji",
    NewPassword: "Nova Lozinka",
    NoContent: "(Bez sadržaja)",
    noDataMessage: "...Nema Redova...",
    Node: "Čvor (Node)",
    NodeGroup: "Grupa Čvorova",
    NoErrorFound: "Bez nađenih grešaka\n",
    NoFilterCriteriaSpecified: "Kriterij za filtriranje nije specificiran.",
    None: "Nijedan",
    NoPublishedSize: "Veličina Nije Objavljena",
    Normal: "Normalan",
    NoScheduledEvents: "Nema Definisanih Događaja na Rasporedu.",
    NoSplit: "Nema Podijela (Split)",
    NotActive: "Nije Aktivan",
    NothingSelected: "Ništa Nije Izabrano...",
    NotInSuperfiles: "Nije Dio Superdatoteke",
    NotSuspendedbyUser: "Nije Suspendovan Od Strane Korisnika",
    NoWarningFound: "Poruke Upozorenja (warnings) nisu nađene\n",
    NumberofParts: "Broj Dijelova",
    NumberofSlaves: "Broj Izvršilaca",
    OK: "OK",
    Oldest: "Najstariji",
    OldPassword: "Stara Lozinka",
    OmitSeparator: "Izostavite Separator",
    Only1PackageFileAllowed: "Dozvoljen je samo jedan paket",
    Open: "Otvoren",
    OpenInNewPage: "Otvorite na Novoj Stranici",
    OpenInNewPageNoFrame: "Otvorite na Novoj Stranici",
    OpenLegacyECLWatch: "Otvorite Stari Prevaziđeni ECL Watch",
    OpenLegacyMode: "Otvorite Zastarjeli Mod",
    OpenNativeMode: "Otvorite Normalni Mod",
    OpenSafeMode: "Otvorite (sigurni mod)",
    OpenSource: "Otvoreni Kod",
    OpenTreeMode: "Otvorite (kao drvo)",
    Operation: "Operacija",
    Operations: "Operacije",
    Options: "Opcije",
    OriginalFile: "Originalna datoteka",
    OrphanFile2: "Nepotrebna Datoteka",
    OrphanFile: "Nepotrebne Datoteke",
    OrphanMessage: "Nepotrebni fajl ima neke dijelove na disku. Ali svi dijelovi fajla ne postoje da bi se moglo kompletirati logički fajl. Ne postoji referenca ne nepostijeće dijelove fajla sa Dali servera.",
    Outputs: "Izlazi",
    Overview: "Pregled",
    Overwrite: "Prepišite",
    OverwriteMessage: "Neke Datoteke već postoje. Da biste nastavili morate dozviliti pisanje preko postojećih datoteka ",
    Owner: "Vlasnik",
    PackageContent: "Sadržaj Paketa",
    PackageContentNotSet: "Sadržaj Paketa nije definisan",
    PackageMap: "Mapa Paketa",
    PackageMaps: "Mape Paketa",
    PackagesNoQuery: "Paketi za koje nisu definisani upiti (queries)",
    ParameterXML: "Parametar XML",
    Part: "Dio",
    PartMask: "Djelimična Maska",
    PartName: "Ime Dijela",
    Parts: "Dijelovi",
    PartsFound: "Dijelovi Su Pronađeni",
    PartsLost: "Dijelovi Su Izgubljeni",
    Password: "Lozinka",
    PasswordExpiration: "Lozinka Istiće",
    PasswordExpired: "Vaša lozinka je istekla I mora biti promijenjena",
    PasswordExpirePostfix: "dan(a). Želite li je sada promijeniti?",
    PasswordExpirePrefix: "Vaša lozinka će isteći za",
    PasswordOpenZAP: "Unesite Lozinku Za ZAP (opcionalno)",
    PasswordsDoNotMatch: "Pogrešna Lozinka.",
    Path: "Put",
    PathMask: "Maska za Put",
    Pause: "Pauza",
    PauseNow: "Zaustavite Odmah",
    PctComplete: "% Kompletiran",
    PercentCompressed: "Procenat Kompresije",
    PercentDone: "Procenat Završen",
    PerformingLayout: "Izvršava Layout...",
    Permission: "Dozvola",
    PermissionName: "Naziv Dozvole Za Pristup",
    Permissions: "Dozvole za Pristup",
    PhysicalFiles: "Fizičke Datoteke",
    PlaceholderFindText: "Wuid, Korisnik, Dalje...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Igralište",
    PleaseEnterANumber: "Unestite Broj 1 -",
    PleasePickADefinition: "Izaberite Definiciju",
    PleaseSelectADynamicESDLService: "Izaberite Dinamički ESDL Servis",
    PleaseSelectAGroupToAddUser: "Izaberite grupu u koju želite da dodate ovog korisnika",
    PleaseSelectATopologyItem: "Izaberite ciljnu platformu, servis ili mašinu.",
    PleaseSelectAUserOrGroup: "Izaberite Korisnika ili Grupu zajedno sa Imenom Datoteke",
    PleaseSelectAUserToAdd: "Izaberite korisnika kojeg  želite da dodate",
    Plugins: "Dopune",
    Port: "Port",
    Prefix: "Prefiks",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preflight: "Provjera prije isporuke",
    PreloadAllPackages: "Učitajte sve pakete",
    PreserveCompression: "Sačuvajte Kompresiju",
    Preview: "Pregled",
    PrimaryLost: "Primarni Je Izgubljen",
    PrimaryMonitoring: "Primarni Nadzor",
    Priority: "Prioritet",
    Process: "Proces",
    Processes: "Procesi",
    ProcessFilter: "Process&nbsp;Filter",
    ProcessorInformation: "Informacija o Procesoru",
    ProgressMessage: "Poruka o Progresu",
    Properties: "Svojstva",
    Property: "Svojstvo",
    Protect: "Zaštitite",
    Protected: "Zašticen",
    Publish: "Objavite",
    Published: "Objavljen",
    PublishedBy: "Objavljivač",
    PublishedQueries: "Objavljeni Upiti",
    PushEvent: "Puš Događaj",
    Quarter: "Četvrtina",
    Queries: "Upiti",
    QueriesNoPackage: "Upiti bez odgovarajućeg paketa",
    Query: "Upit",
    QueryDetailsfor: "Detalji o Upitu",
    QueryID: "Identifikator Upita",
    QueryIDPlaceholder: "som?q*ry.1",
    QueryName: "Ime Upita",
    QueryNamePlaceholder: "My?Su?erQ*ry",
    QuerySet: "Kolekcija Upita",
    Queue: "Red (Queue)",
    Quote: "Citat",
    QuotedTerminator: "Završni Karakter",
    RawTextPage: "Neobrađen Tekst (Tekuća Stranica)",
    Ready: "Spreman",
    ReallyWantToRemove: "Zaista želite ukloniti?",
    RecordCount: "Broj Rekorda",
    RecordLength: "Dužina Rekorda",
    Records: "Rekordi",
    RecordSize: "Veličina Rekorda",
    RecordStructurePresent: "Struktura Rekorda Postoji",
    Recover: "Vratite Natrag",
    RecoverTooltip: "Pokrenite zaustavljenu radnu jedinicu",
    Recycling: "Recikliranje",
    RedBook: "Crvena Knjiga",
    Refresh: "Osviježite",
    ReleaseNotes: "Napomena o Izdanju",
    Reload: "Ponovo Učitajte",
    Remaining: "Preostali",
    RemoteCopy: "Kopija sa udaljenog servera",
    RemoteDali: "Daleki Dali",
    RemoteDaliIP: "Daleki&nbsp;Dali&nbsp;IP&nbsp;Adresa",
    Remove: "Uklonite",
    RemovePart: "Uklonite Dio",
    RemoveAttributeQ: "Izabrani atribut će biti uklonjen. Da li ste sigurni da to želite?",
    RemoveAtttributes: "Uklonite Atribut(e)",
    RemoveSubfiles2: "Da li želite ukloniti subfajl(ove)?",
    RemoveSubfiles: "Uklonite Pod-Datoteku",
    RemoveUser: "Uklonite Korisnika",
    Rename: "Preimenujte",
    RenderedSVG: "Donesene SVG",
    RenderSVG: "Donesite SVG",
    Replicate: "Replicirajte",
    ReplicatedLost: "Izgubljene Replikacije",
    ReplicateOffset: "Replicirajte Ofset",
    RepresentsASubset: "Predstavlja podskup od ukupnog broja uparenih rezultata .Promjena filtera može smanjiti broj uparenih rezultata",
    RequestSchema: "Shema Zahtjeva",
    RequiredForXML: "Potrebno za distribuciju XML",
    Reschedule: "Ponovo Stavite Na Raspored",
    Reset: "Resetujte",
    ResetThisQuery: "Resetujte Tekući Upit",
    ResetViewToSelection: "Resetujte Odabrani Prikaz",
    Resource: "Resurs",
    Resources: "Resursi",
    ResponseSchema: "Shema Odgovora",
    Restart: "Ponovo Pokrenite",
    Restarted: "Ponovo Pokternut",
    Restore: "Vratite na Staro Stanje",
    Resubmit: "Ponovo Podnesite",
    Resubmitted: "Ponovo Poslat",
    ResubmitTooltip: "Reaktivirajte ovu radnu jedinicu",
    Results: "Rezultat(i)",
    Resume: "Nastavite",
    RetainSuperfileStructure: "Zadržite Strukturu Superdatoteke",
    RetypePassword: "Ponovite Lozinku",
    Reverse: "Idite Unazad",
    RowPath: "Put Do Rekorda",
    Rows: "Redovi",
    RowTag: "Etiketa Reda",
    RoxieCluster: "Roxie Klaster",
    RoxieFileCopy: "Status Kopiranja Roxie Datoteka",
    RunningServerStrain: "Izvršavanje ovog procesa može potrajati dugo vremena i veoma optereti servere. Da li želite nastaviti?",
    Sample: "Primjer",
    SampleRequest: "Primjer Zahtjeva",
    SampleResponse: "Primjer Odgovora",
    Save: "Sačuvajte",
    Scope: "Područje",
    SearchResults: "Rezultati Pretraživanja",
    SecondsRemaining: "Preostalo Sekundi",
    Security: "Sigurnost",
    SelectPackageFile: "Izaberi Paket",
    Separators: "Seperatori",
    Server: "Server",
    Services: "Servisi",
    SetBanner: "Postavite Zastavicu",
    SetTextError: "Neuspješno prikazivanje teksta (da li je tekst predug?). Koristite &lsquo;pomagače&rsquo; za preuzimanje datoteka.",
    SetToFailed: "Postavite Na Neuspješan",
    Severity: "Ozbiljnost",
    Show: "Pokažite",
    ShowProcessesUsingFilter: "Prikažite procese koristeći filter",
    ShowSVG: "Pokažite SVG",
    Size: "Veličina",
    Skew: "Skju (Skew)",
    SkewNegative: "Skju(-)",
    SkewPositive: "Skju(+)",
    SLA: "SLA",
    SlaveLogs: "Izvjestaji Izvršilaca",
    SlaveNumber: "Broj Izvršilaca",
    Slaves: "Robovi (Slaves)",
    Smallest: "Najmanji",
    SmallestFile: "Najmanja Datoteka",
    SmallestSize: "Najmanja Veličina",
    SOAP: "SOAP",
    SomeDescription: "Neki*Opis",
    somefile: "*::nekifile*",
    Source: "Izvorna Verzija",
    SourceCode: "Izvorna Verzija Koda",
    SourceLogicalFile: "Ime Izvorne Datoteke",
    SourcePath: "Izvorna Verzija Puta (sa omogucenim *)",
    SourceProcess: "Izvorni Proces",
    Spill: "Zapis na Disk",
    SplitPrefix: "Split Prefiks",
    Spray: "Razbacajte (Spray)",
    Start: "Počnite",
    Started: "Počeo",
    Starting: "Polazak",
    State: "Stanje",
    Stats: "Statistike",
    Status: "Status",
    Stopped: "Zaustavljen",
    Stopping: "Zaustavljanje",
    StorageInformation: "Informacija o prostoru",
    Subgraph: "Pod-Graf",
    Subgraphs: "Podgrafikon",
    Submit: "Podnesite",
    Subtype: "Pod-Vrsta",
    SuccessfullySaved: "Uspješno Sačuvan",
    Summary: "Kratak Pregled",
    SummaryMessage: "Sažeta Poruka",
    Superfile: "Super Datoteka",
    SuperFile: "Super Datoteka",
    Superfiles: "SuperDatoteke",
    SuperFiles: "Super Datoteke",
    SuperFilesBelongsTo: "Pripadnik Superdatoteke",
    SuperfilesOnly: "Samo Superdatoteke",
    SuperOwner: "Super Vlasnik",
    Suspend: "Suspendujte",
    Suspended: "Suspendovan",
    SuspendedBy: "Suspendovan Od",
    SuspendedByCluster: "Suspendovan od strane klastera",
    SuspendedByUser: "Suspendovan Od Strane Korisnika",
    SuspendedReason: "Razlog za Suspendovanje",
    SVGSource: "SVG Izvor",
    SyncSelection: "Sinhronizujte Sa Odabranim",
    SystemServers: "Sistem Servera",
    tag: "tag",
    Target: "Cilj",
    TargetClusters: "Ciljni Klasteri",
    TargetName: "Naziv Cilja",
    TargetNamePlaceholder: "neko::logicko::ime",
    TargetRowTagRequired: "Morate označiti ciljni red u tabeli",
    Targets: "Ciljne Platforme",
    TargetScope: "Ciljni Opseg",
    TargetWuid: "Cilj/Wuid",
    Terminators: "Terminatori",
    TestPages: "Test Stranice",
    Text: "Tekst",
    TheReturnedResults: "Vraćeni Rezultati",
    ThorMasterAddress: "Adresa Glavnog Thora",
    ThorNetworkAddress: "Netvork Adresa Thora",
    ThorProcess: "Tor Proces",
    Time: "Vrijeme",
    Timers: "Mjerači Vremena",
    TimeSeconds: "Vrijeme (Sekunde)",
    TimeStamp: "Vremenska Oznaka",
    TimeStarted: "Vrijeme Početka",
    TimeStopped: "Vrijeme Kraja",
    Timings: "Vremena",
    TimingsMap: "Mapa Vremena",
    title_ActiveGroupPermissions: "Dozvole Aktivne Grupe",
    title_ActivePermissions: "Aktivne Dozvole",
    title_Activity: "Aktivnosti",
    title_AvailableGroupPermissions: "Dostupne Dozvole Grupe",
    title_AvailablePermissions: "Dostupne Dozvole",
    title_ClusterInfo: "Grupe",
    title_CodeGeneratorPermissions: "Dozvole Kod Generatora",
    title_Definitions: "Definicije",
    title_DefinitionExplorer: "Istraživač Definicija",
    title_DESDL: "Dinamičani ESDL",
    title_DFUQuery: "Logičke Datoteke",
    title_DFUWUDetails: "DFU Radna Jedinica",
    title_DirectoriesFor: "Direktoriji za",
    title_DiskUsage: "Iskorištenost Diska",
    title_ECLPlayground: "ECL Igralište",
    title_ErrorsWarnings: "Pogreške/Upozorenja za",
    title_EventScheduleWorkunit: "Respoređivač Događaja",
    title_FileScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor za Datoteke",
    title_FilesPendingCopy: "Datoteke na čekanju za kopiranje",
    title_FoundFilesFor: "Pronađen fajl za",
    title_GetDFUWorkunits: "DFU Radne Jedinice",
    title_Graph: "Grafikon",
    title_GraphPage: "naslov",
    title_Graphs: "Grafikoni",
    title_GridDetails: "Promijeni Me",
    title_History: "Istorija",
    title_HPCCPlatformECL: "ECL Watch Platform - Glavna Stranica",
    title_HPCCPlatformFiles: "ECL Watch - Datoteke",
    title_HPCCPlatformMain: "ECL Watch - Glavna Stranica",
    title_HPCCPlatformOps: "ECL Watch - Upravljnje",
    title_HPCCPlatformRoxie: "ECL Watch - Roxie",
    title_HPCCPlatformServicesPlugin: "ECL Monitor - Dopune",
    title_Inputs: "Unosi",
    title_LFDetails: "Detalji o Logičkol Datoteci",
    title_LibrariesUsed: "Biblioteke U Korištenju",
    title_Log: "Log Fajl",
    title_LostFilesFor: "Izgubljeni fajlovi za",
    title_LZBrowse: "Zona za Pretovar",
    title_MemberOf: "Član Od",
    title_Members: "Članovi",
    title_Methods: "Metode",
    title_OrphanFilesFor: "Nepotrebni fajlovi za",
    title_PackageParts: "Dijelovi paketa",
    title_Permissions: "Dozvole",
    title_PreflightResults: "Rezultati Provjere",
    title_QuerySetDetails: "Detalji Upita",
    title_QuerySetErrors: "Greške",
    title_QuerySetLogicalFiles: "Logičke Datoteke",
    title_QuerySetQuery: "Upiti (Queries)",
    title_QuerySetSuperFiles: "Super Datoteke",
    title_QueryTest: "Super Datoteke",
    title_Result: "Acktivnost",
    title_Results: "Rezultati",
    title_SearchResults: "Rezultati Pretraživanja",
    title_SourceFiles: "Originalni Fajlovi",
    title_Topology: "Topologija",
    title_TpThorStatus: "Stanje Thora",
    title_UserPermissions: "Korisničke Dozvile za Pristup",
    title_UserQuery: "Prava Pristupa",
    title_WorkunitScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor za Radne Jedinice",
    title_WUDetails: "ECL Detalji o Radnoj Jedinici",
    title_WUQuery: "ECL Radne Jedinice",
    To: "Prema",
    ToDate: "Do Sada",
    Toenablegraphviews: "Da biste mogli vidjeli grafikone, moraćete instalisati Graph View Control plugin",
    Tooltip: "Savjet",
    TooManyFiles: "Previše Datoteka",
    Top: "Vrh",
    Topology: "Topologija",
    ToSizes: "Do Velićina",
    TotalClusterTime: "Ukupno Vrijeme Klastera",
    TotalParts: "Ukupan Broj Dijelova",
    TotalSize: "Totalna Veličina",
    TotalThorTime: "Ukupno Vrijeme Thor-a",
    TransitionGuide: "Vodič",
    Tree: "Drvo",
    Type: "Tip",
    undefined: "nedefinisan",
    Unknown: "Nepoznat",
    Unprotect: "Ukinite Zaštitu",
    UnsupportedIE9FF: "Nisu Podržani (IE <= 9, FireFox)",
    Unsuspend: "Ukinite Suspenziju",
    Unsuspended: "Suspenzija Ukinuta",
    Up: "Na Gore",
    UpdateCloneFrom: "Ažurirajte Klon Koristeći",
    UpdateSuperFiles: "Ažurirajte Super Datoteke",
    Upload: "Upload",
    URL: "URL",
    Usage: "Upotreba",
    Used: "Korišten",
    User: "Korisnik",
    UserDetails: "Detalji o Korisniku",
    UserID: "Korisnicki ID",
    UserName: "Ime Korisnika",
    Username: "Imekorisnika",
    UserPermissions: "Dozvole za Korisnikov Pristup",
    Users: "Korisnici",
    UseSingleConnection: "Koristite Samo Jedan Priključak (Connection)",
    Validate: "Potvrdite",
    ValidateActivePackageMap: "Validirajte Mapu Aktivnog Paketa",
    ValidatePackageContent: "Validirajte Saržaj Paketa",
    ValidatePackageMap: "Potvrdite Mapu Paketa",
    ValidateResult: "=====Potvrdite Result=====\n\n",
    ValidateResultHere: "(Rezultati Validiranja)",
    Value: "Vrijednost",
    Variable: "Varijabla",
    VariableBigendian: "Varijabla Big-endian",
    Variables: "Varijable",
    VariableSourceType: "Tip Izvora",
    Version: "Verzija",
    ViewByScope: "Pogled prema Skopu",
    Views: "Pogledi",
    Visualize: "Visualizujte",
    WarnIfAvailableDiskSpaceIsUnder: "Upozori ako raspoloživi disk prostor spadne ispod",
    WarnIfAvailableMemoryIsUnder: "Upozori ako raspoloživa memorija spadne ispod",
    WarnIfCPUUsageIsOver: "Upozori ako je iskorištenost procesora preko",
    Warning: "Upozorenje",
    Warnings: "Upozorenje(a)",
    WarnOldGraphControl: "Upozorenje:  Stara Grafička Kontrola",
    What: "Šta",
    Where: "Gdje",
    Who: "Ko",
    Width: "Širina",
    Workflows: "Tokovi poslova",
    Workunit: "Radna Jedinica",
    Workunits: "Radne Jedinice",
    WorkUnitScopeDefaultPermissions: "Unaprijed Definisane Dozvole za Prostor za Radne Jedinice",
    Wrap: "Zamotajte",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid Ne Može Biti Prazan.",
    WUSnapShot: "Trenutna Slika Radne Jedinice",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "XRef",
    Year: "Godina",
    YouAreAboutToDeleteBinding: "Odabrano vezivanje/binding će biti izbrisano. Jeste li sigurni da želite to učiniti?",
    YouAreAboutToDeleteThisFile: "Da li ćete obrisati ovu datoteku",
    YouAreAboutToDeleteThisPart: "Da li ćete obrisati ovaj dio",
    YouAreAboutToDeleteThisQueryset: "Da li ćete obrisati ovaj set upita",
    YouAreAboutToDeleteThisWorkunit: "Da li ćete obrisati ovu radnu jedinicu",
    YouAreAboutToRemoveUserFrom: "Tražili ste da odstranite korisnika(e) iz ove grupe. Da li želite nastaviti?",
    YourBrowserMayNotSupport: "Vaš pretraživač možda ne podržava datoteku (e) ove veličine",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Nema ni jedane Logičke Datoteke(provjerite filter)",
    Zip: "Zapakujte (Zip)",
    ZippedAnalysisPackage: "Zapakovani Paket sa Analizama",
    Zoom100Pct: "Zumirajte 100%",
    Zoom: "Zum",
    ZoomAll: "Zumirajte Sve",
    ZoomWidth: "Zumirajte Širinu"
})
);
