define(
({
    title: "Archivos Lógicos",

    Add: "Agregar",
    AddToSuperfile: "Agregar al Super-archivo",
    Append: "Agregar",
    Cluster: "Agrupar",
    Compress: "Comprimir",
    DeleteSelectedFiles: "¿Borrar archivos seleccionados?",
    Delimited: "Delimitado",
    Description: "Descripción",
    Despray: "Despray",
    DropZone: "Zona de carga",
    Escape: "Escape",
    Fixed: "Fijo",
    Format: "Formato",
    FromDate: "Desde Fecha",
    FromSizes: "Desde Tamaños",
    Group: "Grupo",
    IP: "IP",
    IPAddress: "Dirección de IP",
    JSmith: "JSmit*",
    Label: "Etiqueta",
    LastNDays: "Ultimos N días",
    LineTerminators: "Terminadores de Línea",
    LogicalFile: "Archivo Lógico",
    LogicalName: "Nombre Lógico",
    Mask: "Máscara",
    MaxRecordLength: "Máx. largo de registro",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    NA: "N/A",
    Name: "Nombre",
    NoFilterCriteriaSpecified: "No especificó criterio de filtro.",
    NoSplit: "No corte",
    OmitSeparator: "Omite Separador",
    Options: "Opciones",
    Overwrite: "Sobreescribir",
    Owner: "Dueño",
    Parts: "Partes",
    Path: "Camino",
    Prefix: "Prefijo",
    Quote: "Comilla",
    RecordLength: "Largo de registro",
    Records: "Registros",
    RowTag: "Etiqueta de línea",
    Seperators: "Seperadores",
    Size: "Tamaño",
    somefile: "*::archivo*",
    Source: "Origen",
    SplitPrefix: "Corte prefijo",
    Spray: "Spray",
    tag: "etiqueta",
    Target: "Destino",
    ToDate: "A fecha",
    ToSizes: "A tamaño",
    UseSingleConnection: "Use una sola conexión",
    XML: "XML",
    ZeroLogicalFilesCheckFilter: "Archivos logicos a cero (chequee filtro)"
})
);
