define(
({
    title: "Logical Files",

    Add: "Add",
    AddToSuperfile: "Add To Superfile",
    Append: "Append",
    Cluster: "Cluster",
    Compress: "Compress",
    DeleteSelectedFiles: "Delete Selected Files?",
    Delimited: "Delimited",
    Description: "Description",
    Despray: "Despray",
    DropZone: "Drop Zone",
    Escape: "Escape",
    Fixed: "Fixed",
    Format: "Format",
    FromDate: "From Date",
    FromSizes: "From Sizes",
    Group: "Group",
    IP: "IP",
    IPAddress: "IP Address",
    JSmith: "JSmit*",
    Label: "Label",
    LastNDays: "Last N Days",
    LineTerminators: "Line Terminators",
    LogicalFile: "Logical File",
    LogicalName: "Logical Name",
    Mask: "Mask",
    MaxRecordLength: "Max Record Length",
    ModifiedUTCGMT: "Modified (UTC/GMT)",
    NA: "N/A",
    Name: "Name",
    NoFilterCriteriaSpecified: "No filter criteria specified.",
    NoSplit: "No Split",
    NoSplit: "No Split",
    OmitSeparator: "Omit Separator",
    Options: "Options",
    Overwrite: "Overwrite",
    Owner: "Owner",
    Parts: "Parts",
    Path: "Path",
    Prefix: "Prefix",
    Quote: "Quote",
    RecordLength: "Record Length",
    Records: "Records",
    RowTag: "Row Tag",
    Seperators: "Seperators",
    Size: "Size",
    somefile: "*::somefile*",
    Source: "Source",
    SplitPrefix: "Split Prefix",
    Spray: "Spray",
    tag: "tag",
    Target: "Target",
    ToDate: "To Date",
    ToSizes: "To Sizes",
    UseSingleConnection: "Use Single Connection",
    XML: "XML",
    ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)"
})
);
