define(
({
    title: "DFU Workunit",

    Abort: "Abort",
    ClusterName: "Cluster Name",
    Command: "Command",
    Compress: "Compress",
    Dali: "Dali",
    DFUServerName: "DFU Server Name",
    Directory: "Directory",
    Escape: "Escape",
    FilePath: "File Path",
    Format: "Format",
    GroupName: "Group Name",
    ID: "ID",
    IP: "IP",
    JobName: "Job Name",
    LogicalName: "Logical Name",
    Modify: "Modify",
    MonitorEventName: "Monitor Event Name",
    MonitorShotLimit: "Monitor Shot Limit",
    MonitorSub: "Monitor Sub",
    NumberofParts: "Number of Parts",
    Overwrite: "Overwrite",
    PercentDone: "Percent Done",
    ProgressMessage: "Progress Message",
    Protected: "Protected",
    Queue: "Queue",
    Quote: "Quote",
    RecordSize: "Record Size",
    Replicate: "Replicate",
    Resubmit: "Resubmit",
    RowTag: "Row Tag",
    SecondsRemaining: "Seconds Remaining",
    Seperators: "Seperators",
    Source: "Source",
    State: "State",
    Summary: "Summary",
    SummaryMessage: "Summary Message",
    Target: "Target",
    Terminators: "Terminators",
    TimeStarted: "Time Started",
    TimeStopped: "Time Stopped",
    User: "User"
})
);
