define(
({
    title: "Unidad de trabajo DFU",

    Abort: "Aborte",
    ClusterName: "Nombre del systema",
    Command: "Comando",
    Compress: "Comprimir",
    Dali: "Dali",
    DFUServerName: "Nombre del servidor de DFU",
    Directory: "Directorio",
    Escape: "Escape",
    FilePath: "Camino del archivo",
    Format: "Formato",
    GroupName: "Nombre del grupo",
    ID: "ID",
    IP: "IP",
    JobName: "Nombre del trabajo",
    LogicalName: "Nombre lógico",
    Modify: "Modificar",
    MonitorEventName: "Nombre del evento monitor",
    MonitorShotLimit: "Límite de disparos del monitor",
    MonitorSub: "Sub monitor",
    NumberofParts: "Número de partes",
    Overwrite: "Sobreescribir",
    PercentDone: "Porcentaje completado",
    ProgressMessage: "Mensaje de progreso",
    Protected: "Protegido",
    Queue: "Cola",
    Quote: "Comilla",
    RecordSize: "Tamaño del registro",
    Replicate: "Replicar",
    Resubmit: "Reenviar",
    RowTag: "Etiqueta de línea",
    SecondsRemaining: "Segundos que faltan",
    Seperators: "Seperadores",
    Source: "Origen",
    State: "Estado",
    Summary: "Resumen",
    SummaryMessage: "Mensaje resumido",
    Target: "Destino",
    Terminators: "Terminadores",
    TimeStarted: "Tiempo empezado",
    TimeStopped: "Tiempo detenido",
    User: "Usuario"
})
);
