define(
({
    title: "título",

    AboutGraphControl: "Acerca del controlador gráfico",
    AboutHPCCSystemsGraphControl: "Acerca del controlador gráfico de HPCC Systems",
    Activities: "Actividades",
    Advanced: "Advanzado",
    Depth: "Profundidad",
    Distance: "Distancia",
    DOT: "DOT",
    DOTAttributes: "Atributos DOT",
    ECL: "ECL",
    Edges: "Bordes",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar atributos gráficos",
    EditXGMML: "Editar XGMML",
    FetchingData: "Obteniendo Data...",
    Find: "Encontrar",
    FindNext: "Encontrar próximo",
    FindPrevious: "Encontrar previo",
    ID: "ID",
    InfoDialog: "Diálogo informativo",
    Label: "Etiqueta",
    Local: "Local",
    Overview: "Visión de conjunto",
    PerformingLayout: "Generando disposición...",
    Properties: "Propiedades",
    RenderedSVG: "SVG creado",
    RenderSVG: "Crear SVG",
    ShowSVG: "Mostrar SVG",
    Subgraphs: "Sub-gráficos",
    SVGSource: "Origen del SVG",
    Sync: "Sincronizar",
    Timings: "Tiempos",
    TimingsMap: "Mapa de tiempos",
    Version: "Versión",
    XGMML: "XGMML"
})
);
