define(
({
    Abort: "Aborte",
    About: "Acerca",
    AboutGraphControl: "Acerca del controlador gráfico",
    AboutHPCCSystemsGraphControl: "Acerca del controlador gráfico de HPCC Systems",
    Action: "Acción",
    Activate: "Activar",
    Activated: "Activado",
    Active: "Activo",
    ActivePackageMap: "Active Package Map",
    ActiveWorkunit: "Unidad activa",
    Activities: "Actividades",
    Activity: "Actividad",
    ActualSize: "Tamaño real",
    Add: "Agregar",
    AddGroup: "Add Group",
    AddProcessMap: "Add Package Map",
    AddToSuperfile: "Agregar al Super-archivo",
    AddUser: "Add User",
    Advanced: "Advanzado",
    AllowAccess: "<center>Allow<br>Access",
    AllowFull: "<center>Allow<br>Full</center>",
    AllowRead: "<center>Allow<br>Read</center>",
    AllowWrite: "<center>Allow<br>Write</center>",
    ANY: "ANY",
    Append: "Agregar",
    Apply: "Apply",
    ArchivedOnly: "Solo archivado",
    BinaryInstalls: "Binarios instalables",
    Blob: "BLOB",
    BlobPrefix: "BLOB Prefix",
    Cancel: "Cancelar",
    Clear: "Clear",
    Clone: "Clonar",
    Close: "Cerrar",
    Cluster: "Sistema",
    ClusterName: "Nombre del sistema",
    ClusterPlaceholder: "r?x*",
    ClusterProcesses: "Procesos de sistema",
    Code: "Código",
    Col: "Col",
    Command: "Comando",
    Comment: "Comentario",
    Completed: "Completado",
    Component: "Componente",
    Compress: "Comprimir",
    ConfirmPassword: "Confirm Password",
    Contents: "Contenidos",
    Copy: "Copia",
    Count: "Número",
    Created: "Creado",
    Dali: "Dali",
    dataset: ":=dataset*",
    Date: "Fecha",
    Deactivate: "Deactivar",
    DEF: "DEF",
    Delete: "Delete",
    DeleteSelectedFiles: "¿Borrar archivos seleccionados?",
    DeleteSelectedGroups: "Delete selected group(s)?",
    DeleteSelectedQueries: "¿Borrar queries seleccionados?",
    DeleteSelectedUsers: "Delete selected user(s)?",
    DeleteSelectedWorkunits: "¿Borrar unidades de trabajo seleccionadas?",
    DeleteSuperfile: "¿Borrar super-archivo?",
    DeleteThisPackage: "Delete this package?",
    Delimited: "Delimitado",
    DenyAccess: "<center>Deny<br>Access",
    DenyFull: "<center>Deny<br>Full</center>",
    DenyRead: "<center>Deny<br>Read</center>",
    DenyWrite: "<center>Deny<br>Write</center>",
    Depth: "Profundidad",
    Deschedule: "Eliminar del plan de ejecución",
    DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
    Description: "Descripción",
    Despray: "Despray",
    DFUServerName: "Nombre del servidor de DFU",
    Directory: "Directorio",
    Distance: "Distancia",
    Dll: "Dll",
    DOT: "DOT",
    DOTAttributes: "Atributos DOT",
    Download: "Descargar",
    DropZone: "Zona de carga",
    Duration: "Duración",
    EBCDIC: "EBCDIC",
    ECL: "ECL",
    Edges: "Bordes",
    Edit: "Edit",
    EditDOT: "Editar DOT",
    EditGraphAttributes: "Editar atributos gráficos",
    EditXGMML: "Editar XGMML",
    Empty: "(Empty)",
    Error: "Error",
    Errorparsingserverresult: "Error analizando los resultados del servidor",
    Errors: "Error(s)",
    Errors: "Errores",
    ErrorsStatus: "Errores/Estado",
    ErrorWarnings: "Error/Advertencia(s)",
    Escape: "Escape",
    ESPBuildVersion: "Versión de ESP",
    ESPNetworkAddress: "Dirección de red de ESP",
    EventName: "Event Name",
    EventNamePH: "eventname",
    EventScheduler: "Planificador de eventos",
    EventText: "Event Text",
    Exception: "Exception",
    FetchingData: "Obteniendo Data...",
    fetchingresults: "obteniendo resultados",
    File: "Archivo",
    FileName: "Nombre de archivo",
    FileParts: "Partes de archivos",
    FilePath: "Camino del archivo",
    Files: "Archivos",
    FileSize: "Tamaño de archivo",
    FilesNoPackage: "Files without matching package definitions",
    FileType: "File Type",
    FileUploader: "Subidor de archivo",
    Filter: "Filter",
    Find: "Encontrar",
    FindNext: "Encontrar próximo",
    FindPrevious: "Encontrar previo",
    FirstName: "First Name",
    Fixed: "Fijo",
    Format: "Formato",
    FromDate: "Desde Fecha",
    FromSizes: "Desde Tamaños",
    FullName: "Full Name",
    Graphs: "Gráficos",
    GraphView: "Vista del gráfico",
    Group: "Grupo",
    GroupDetails: "Group Details",
    GroupName: "Nombre del grupo",
    GroupPermissions: "Group Permissions",
    Groups: "Grupos",
    GZip: "GZip",
    help: "Esta área muestra el mapa de árbol de el/los gráfico(s) en esta unidad de trabajo. El tamaño y el tinte indican la duración de cada gráfico (más grande y más oscuro indica un porcentaje mayor de tiempo tomado.)",
    Helpers: "Ayudantes",
    Hex: "exadecimal",
    History: "Historia",
    HPCCSystems: "HPCC Systems",
    ID: "ID",
    Import: "Import",
    Info: "Info",
    InfoDialog: "Diálogo informativo",
    Inputs: "Entradas",
    InvalidResponse: "(Invalid response)",
    IP: "IP",
    IPAddress: "Dirección de IP",
    IsLibrary: "Es biblioteca",
    Jobname: "Nombre del trabajo",
    JobName: "Nombre del trabajo",
    jsmi: "jsmi*",
    JSmith: "JSmit*",
    JSON: "JSON",
    Label: "Etiqueta",
    LandingZone: "Zona de descarga",
    LandingZones: "Zonas de aterrizaje",
    Largest: "Largest",
    LastName: "Last Name",
    LastNDays: "ULtimos N días",
    LegacyForm: "Forma histórica",
    LibrariesUsed: "Bibliotecas usadas",
    Line: "Línea",
    LineTerminators: "Terminadores de línea",
    Links: "Vínculos",
    Loading: "Loading...",
    LoadingCachedLayout: "Loading Cached Layout...",
    LoadingData: "Cargando data...",
    loadingMessage: "...Loading...",
    Local: "Local",
    LoggedInAs: "Conectado como",
    LogicalFile: "Archivo Lógico",
    LogicalFile: "Archivo lógico",
    LogicalFiles: "Archivos lógicos",
    LogicalFiles: "Arvhivos lógicos",
    LogicalFileType: "Tipo de archivo lógico",
    LogicalName: "Nombre lógico",
    log_analysis_1: "log_analysis_1*",
    Mappings: "Mapeados",
    Mask: "Máscara",
    Max: "Máx",
    MaxRecordLength: "Máx largo de registros",
    MemberOf: "Member Of",
    Members: "Members",
    Message: "Message",
    Min: "Min",
    Modification: "Modificación",
    ModifiedUTCGMT: "Modificado (UTC/GMT)",
    Modify: "Modificar",
    MonitorEventName: "Nombre del evento monitor",
    MonitorShotLimit: "Límite de disparos del monitor",
    MonitorSub: "Sub monitor",
    MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
    NA: "N/A",
    Name: "Nombre",
    NamePrefix: "Name Prefix",
    NamePrefixPlaceholder: "some::prefix",
    Newest: "Newest",
    NewPassword: "New Password",
    NoContent: "(No content)",
    noDataMessage: "...Zero Rows...",
    Node: "Nodo",
    NoErrorFound: "No errors found\n",
    NoFilterCriteriaSpecified: "No especificó criterio de filtro.",
    NoScheduledEvents: "No Scheduled Events.",
    NoSplit: "No corte",
    NotActive: "Not active",
    NothingSelected: "Nothing Selected...",
    NotInSuperfiles: "Not in Superfiles",
    NoWarningFound: "No warnings found\n",
    NumberofParts: "Número de partes",
    OK: "Aceptar",
    Oldest: "Oldest",
    OmitSeparator: "Omite Separador",
    Only1PackageFileAllowed: "Only one package file allowed",
    Open: "Open",
    OpenInNewPage: "Open In New Page",
    OpenLegacyECLWatch: "Abrir ECL Watch viejo",
    OpenSafeMode: "Abrir (modo seguro)",
    Operations: "Operaciones",
    Options: "Opciones",
    Outputs: "Salidas",
    Overview: "Visión de conjunto",
    Overwrite: "Sobreescribir",
    Owner: "Dueño",
    PackageContent: "Package Content",
    PackageContentNotSet: "Package content not set",
    PackageMap: "Package Map",
    PackageMaps: "Package Maps",
    PackagesNoQuery: "Packages without matching queries",
    ParameterXML: "Parámetro XML",
    Parts: "Partes",
    Password: "Password",
    PasswordExpiration: "Password Expiration",
    PasswordsDoNotMatch: "Passwords do not match.",
    Path: "Camino",
    PathMask: "Máscara del camino",
    PctComplete: "% completado",
    PercentDone: "Porcentaje completado",
    PerformingLayout: "Generando disposición...",
    Permissions: "Permisos",
    PlaceholderFindText: "Wuid, usuario, mas...",
    PlaceholderFirstName: "John",
    PlaceholderLastName: "Smith",
    Playground: "Patio de juegos",
    Prefix: "Prefijo",
    PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
    Preview: "Preview",
    Priority: "Prioridad",
    Process: "Process",
    ProcessFilter: "Process&nbsp;Filter",
    ProgressMessage: "Mensaje de progreso",
    Properties: "Propiedades",
    Property: "Propiedad",
    Protect: "Proteger",
    Protected: "Protegido",
    Publish: "Publicar",
    PublishedBy: "Publicado por",
    PublishedQueries: "Queries publicados",
    Queries: "Queries",
    QueriesNoPackage: "Queries without matching package",
    QueryDetailsfor: "Detalles de Query por",
    QuerySet: "Grupo de Query",
    Queue: "Cola",
    Quote: "Comilla",
    RecordCount: "Número de registros",
    RecordLength: "Largo de registro",
    Records: "Registros",
    RecordSize: "Tamaño del registro",
    Refresh: "Refresh",
    ReleaseNotes: "Notas de la versión",
    Reload: "Reload",
    RemoteDali: "Dali remoto",
    RemoteDaliIP: "Remote&nbsp;Dali&nbsp;IP&nbsp;Address",
    Remove: "Remover",
    Rename: "Renombrar",
    RenderedSVG: "SVG creado",
    RenderSVG: "Crear SVG",
    Replicate: "Replicar",
    RequestSchema: "Esquema del requerimiento",
    Reschedule: "Re-planear ejecución",
    Reset: "Origen",
    Resource: "Resource",
    Resources: "Recursos",
    ResponseSchema: "Esquema de la respuesta",
    Restart: "Empezar de nuevo",
    Resubmit: "Reenviar",
    Results: "Resultado(s)",
    RetainSuperfileStructure: "Retener estructura del super-archivo",
    RetypePassword: "Retype Password",
    Rows: "Líneas",
    RowTag: "Etiqueta de línea",
    RoxieCluster: "Sistema Roxie",
    Sample: "Ejemplo",
    SampleRequest: "Ejemplo del requerimiento",
    SampleResponse: "Ejemplo de la respuesta",
    Save: "Guardar",
    Scope: "Alcance",
    SearchResults: "Resultados de búsqueda",
    SecondsRemaining: "Segundos que faltan",
    SelectPackageFile: "Select Package File",
    Seperators: "Seperadores",
    SetBanner: "Configurar la bandera",
    SetToFailed: "Marcar como fallado",
    Severity: "Severidad",
    Show: "Mostrar",
    ShowSVG: "Mostrar SVG",
    Size: "Tamaño",
    Skew: "Desbalance",
    Slaves: "Esclavos",
    Smallest: "Smallest",
    SOAP: "SOAP",
    SomeDescription: "Some*Description",
    somefile: "*::archivo*",
    Source: "Origen",
    SourceCode: "Código fuente",
    SourcePath: "Source Path (Wildcard Enabled)",
    SplitPrefix: "Corte prefijo",
    Spray: "Spray",
    Start: "Comienzo",
    Started: "Comenzado",
    State: "Estado",
    Stopped: "Detenido",
    Subgraphs: "Sub-gráficos",
    Submit: "Enviar",
    Summary: "Resumen",
    SummaryMessage: "Mensaje resumido",
    SuperFile: "Super File",
    SuperfilesOnly: "Superfiles Only",
    Suspend: "Suspender",
    Suspended: "Suspendido",
    SuspendedBy: "Suspendido por",
    SVGSource: "Origen del SVG",
    Sync: "Sincronizar",
    SystemServers: "Servidores de sistema",
    tag: "etiqueta",
    Target: "Destino",
    TargetClusters: "Sistemas de destino",
    TargetName: "Target Name",
    TargetNamePlaceholder: "some::logical::name",
    TargetWuid: "Target/Wuid",
    Terminators: "Terminadores",
    TestPages: "Páginas de prueba",
    ThorNetworkAddress: "Dirección de red de Thor",
    Time: "Tiempo",
    TimeSeconds: "Tiempo (Segundos)",
    TimeStarted: "Tiempo empezado",
    TimeStopped: "Tiempo detenido",
    Timings: "Tiempos",
    TimingsMap: "Mapa de tiempos",
    title_Activity: "Actividad",
    title_DFUQuery: "Archivos Lógicos",
    title_DFUWUDetails: "Unidad de trabajo DFU",
    title_ECLPlayground: "ECL Playground",
    title_EventScheduleWorkunit: "Event Scheduler",
    title_GetDFUWorkunits: "Unidades de trabajo DFU",
    title_Graph: "Gráficos",
    title_GraphPage: "título",
    title_Graphs: "Gráficos",
    title_GridDetails: "Cámbieme",
    title_HPCCPlatformECL: "Plataforma HPCC - Hogar",
    title_HPCCPlatformFiles: "Platforma HPCC - Archivos",
    title_HPCCPlatformMain: "Plataforma HPCC - Hogar",
    title_HPCCPlatformOps: "Plataforma HPCC - Operaciones",
    title_HPCCPlatformRoxie: "Plataforma HPCC - Roxie",
    title_Inputs: "Inputs",
    title_LFDetails: "Detalles de archivos lógicos",
    title_LZBrowse: "Zonas de descarga",
    title_MemberOf: "Member Of",
    title_Members: "Members",
    title_QuerySetDetails: "Detalles de Query",
    title_QuerySetErrors: "Errores",
    title_QuerySetLogicalFiles: "Archivos lógicos",
    title_QuerySetQuery: "Queries",
    title_QuerySetSuperFiles: "Super archivos",
    title_QueryTest: "Super Archivos",
    title_Result: "Actividad",
    title_Results: "Salidas",
    title_SearchResults: "",
    title_SourceFiles: "",
    title_UserQuery: "Permissions",
    title_UserPermissions: "User Permissions",
    title_WUDetails: "Detalles de las unidades de trabajo ECL",
    title_WUQuery: "Unidades de trabajo ECL",
    ToDate: "Hasta fecha",
    Toenablegraphviews: "Para habilitar vista de gráficos, instale el plugin Graph View Control",
    ToSizes: "A tamaño",
    TotalThorTime: "Tiempo total de Thor",
    Type: "Tipo",
    undefined: "no definido",
    Unknown: "Desconocido",
    Unprotect: "Desproteger",
    Unsuspend: "De-suspender",
    Unsuspended: "Des-suspendido",
    Upload: "Subir",
    Used: "Usado",
    User: "Usuario",
    UserDetails: "User Details",
    UserID: "User ID",
    Username: "Username",
    UserName: "User Name",
    UserPermissions: "User Permissions",
    Users: "Usuarios",
    UseSingleConnection: "Use conexión individual",
    UseSingleConnection: "Use una sola conexión",
    Validate: "Validate",
    ValidatePackageMap: "Validate Package Map",
    ValidateResult: "=====Validate Result=====\n\n",
    Value: "Valor",
    Variable: "Variable",
    VariableBigendian: "Variable Big-endian",
    VariableSourceType: "Source Type",
    Version: "Versión",
    Views: "Vistas",
    Visualize: "Visualizar",
    Warnings: "Advertencias",
    WarnOldGraphControl: "Warning:  Old Graph Control",
    Width: "Ancho",
    Workunit: "Unidad de trabajo",
    Workunits: "Unidades de trabajo",
    Wrap: "Envolver",
    WSDL: "WSDL",
    WUID: "WUID",
    Wuidcannotbeempty: "Wuid no puede estar vacío.",
    WUSnapShot: "Captura de Unidad de trabajo",
    XGMML: "XGMML",
    XLS: "XLS",
    XML: "XML",
    XRef: "Referencias cruzadas",
    ZAP: "Z.A.P",
    ZeroLogicalFilesCheckFilter: "Archivos logicos a cero (chequee filtro)",
    Zip: "Zip",
    ZippedAnalysisPackage: "Paquete de análisis en formato Zip",
    Zoom100Pct: "Aumentar a 100%",
    ZoomAll: "Aumentar todo",
    ZoomWidth: "Aumentar al ancho"
})
);
