define(
({
    title: "Logical File Details",

    ActualSize: "Actual Size",
    ClusterName: "Cluster Name",
    Compress: "Compress",
    Contents: "Contents",
    Copy: "Copy",
    DEF: "DEF",
    Description: "Description",
    Despray: "Despray",
    Directory: "Directory",
    DropZone: "Drop Zone",
    ECL: "ECL",
    FileParts: "File Parts",
    FileSize: "File Size",
    Group: "Group",
    IPAddress: "IP Address",
    JobName: "Job Name",
    LogicalFile: "Logical File",
    Modification: "Modification",
    NoSplit: "No Split",
    Overwrite: "Overwrite",
    Owner: "Owner",
    Path: "Path",
    PathMask: "Path Mask",
    RecordCount: "Record Count",
    RecordSize: "Record Size",
    Rename: "Rename",
    RetainSuperfileStructure: "Retain Superfile Structure",
    Source: "Source",
    SplitPrefix: "Split Prefix",
    Summary: "Summary",
    Target: "Target",
    UseSingleConnection: "Use Single Connection",
    Workunit: "Workunit",
    Wrap: "Wrap",
    XML: "XML"
})
);
