define(
({
    title: "Detalles de archivos lógicos",

    ActualSize: "Tamaño real",
    ClusterName: "Nombre del sistema",
    Compress: "Comprimir",
    Contents: "Contenidos",
    Copy: "Copia",
    DEF: "DEF",
    Description: "Descripción",
    Despray: "Despray",
    Directory: "Directorio",
    DropZone: "Zona de carga",
    ECL: "ECL",
    FileParts: "Partes de archivos",
    FileSize: "Tamaño de archivo",
    Group: "Grupo",
    IPAddress: "Dirección de IP",
    JobName: "Nombre del trabajo",
    LogicalFile: "Archivo lógico",
    Modification: "Modificación",
    NoSplit: "No cortar",
    Overwrite: "Sobreescribir",
    Owner: "Dueño",
    Path: "Camino",
    PathMask: "Máscara del camino",
    RecordCount: "Número de registros",
    RecordSize: "Record Size",
    Rename: "Renombrar",
    RetainSuperfileStructure: "Retener estructura del super-archivo",
    Source: "Origen",
    SplitPrefix: "Prefijo de corte",
    Summary: "Resumen",
    Target: "Destino",
    UseSingleConnection: "Use conexión individual",
    Workunit: "Unidad de trabajo",
    Wrap: "Envolver",
    XML: "XML"
})
);
