define(
({
    title: "Landing Zones",

    Compress: "Compress",
    Date: "Date",
    DeleteSelectedFiles: "Delete Selected Files?",
    Delimited: "Delimited",
    Download: "Download",
    Errorparsingserverresult: "Error parsing server result",
    Escape: "Escape",
    FileUploader: "File Uploader",
    Fixed: "Fixed",
    Format: "Format",
    Group: "Group",
    HexPreview: "Hex Preview",
    Label: "Label",
    LandingZone: "Landing Zone",
    LineTerminators: "Line Terminators",
    Mask: "Mask",
    MaxRecordLength: "Max Record Length",
    Name: "Name",
    NoSplit: "No Split",
    OmitSeparator: "Omit Separator",
    Options: "Options",
    Overwrite: "Overwrite",
    Prefix: "Prefix",
    Quote: "Quote",
    RecordLength: "Record Length",
    RowTag: "Row Tag",
    Seperators: "Seperators",
    Size: "Size",
    Source: "Source",
    Spray: "Spray",
    SpraySourceType: "Spray Source Type",
    Start: "Start",
    tag: "tag",
    Target: "Target",
    Upload: "Upload",
    XML: "XML"
})
);
