define(
({
    title: "Zonas de descarga",

    Compress: "Comprimir",
    Date: "Fecha",
    DeleteSelectedFiles: "Borrar archivos seleccionados?",
    Delimited: "Delimitado",
    Download: "Descargar",
    Errorparsingserverresult: "Error analizando los resultados del servidor",
    Escape: "Escape",
    FileUploader: "Subidor de archivo",
    Fixed: "Fijo",
    Format: "Formato",
    Group: "Grupo",
    HexPreview: "Pre-vista exadecimal",
    Label: "Etiqueta",
    LandingZone: "Zona de descarga",
    LineTerminators: "Terminadores de línea",
    Mask: "Máscara",
    MaxRecordLength: "Máx largo de registros",
    Name: "Nombre",
    NoSplit: "No cortar",
    OmitSeparator: "Omitir separador",
    Options: "Opciones",
    Overwrite: "Sobreescribir",
    Prefix: "Prefijo",
    Quote: "Comilla",
    RecordLength: "Largo de registro",
    RowTag: "Etiqueta de línea",
    Seperators: "Seperadores",
    Size: "Tamaño",
    Source: "Origen",
    Spray: "Spray",
    SpraySourceType: "Tipo de origen de Spray",
    Start: "Comienzo",
    tag: "etiqueta",
    Target: "Destino",
    Upload: "Subir",
    XML: "XML"
})
);
