define(
({
    title: "Detalles de las unidades de trabajo ECL",

    Abort: "Abortar",
    Action: "Acción",
    Clone: "Clonar",
    Cluster: "Sistema",
    Description: "Descripción",
    Duration: "Duración",
    ECL: "ECL",
    ESPBuildVersion: "Versión de ESP",
    ESPNetworkAddress: "Dirección de red de ESP",
    Graphs: "Gráficos",
    Helpers: "Ayudantes",
    History: "Historia",
    Inputs: "Entradas",
    JobName: "Nombre del trabajo",
    Outputs: "Salidas",
    Owner: "Dueño",
    Playground: "Patio de juegos",
    Protected: "Protegido",
    Publish: "Publicar",
    RemoteDali: "Dali remoto",
    Restart: "Empezar de nuevo",
    Resubmit: "Reenviar",
    Scope: "Alcance",
    SetToFailed: "Marcar como fallado",
    State: "Estado",
    Submit: "Enviar",
    Summary: "Resumen",
    ThorNetworkAddress: "Dirección de red de Thor",
    Timings: "Tiempos",
    Visualize: "Visualizar",
    WUID: "WUID",
    XML: "XML",
    ZAP: "Z.A.P",
    ZippedAnalysisPackage: "Paquete de análisis en formato Zip"
})
);
