#!/bin/bash
################################################################################
#    Copyright (C) 2011 HPCC Systems.
#
#    All rights reserved. This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################


PATH_PRE=`type -path hpcc_setenv`
source ${PATH_PRE}
PID_NAME="$PID/`basename $PWD`.pid"

ulimit -c unlimited
ulimit -n 8192
ulimit -s 512

export LANG=en_US

echo rerun > dfuserver_sentinel.txt
dfuserver 1>/dev/null 2>/dev/null &
echo $! > $PID_NAME
wait
while [ -e dfuserver_sentinel.txt ]; do
        sleep 5
        if [ -e dfuserver_sentinel.txt ]; then
        dfuserver 1>/dev/null 2>/dev/null &
        echo $! > $PID_NAME
        wait
        fi
done
