#!/bin/bash

DEBIAN_FRONTEND=noninteractive apt-get -y install libboost-regex1.46.1 libicu48 libxalan110 libxerces-c28 binutils libldap-2.4-2 openssl zlib1g g++ openssh-client openssh-server expect libarchive12 rsync
