#!/bin/bash

DEBIAN_FRONTEND=noninteractive apt-get -y install libboost-regex1.53.0 libicu48 libxalan-c111 libxerces-c3.1 binutils libldap-2.4-2 openssl zlib1g g++ openssh-client openssh-server expect libarchive13 rsync
