export = {
    root: {
        Abort: "Abort",
        AbortedBy: "Aborted by",
        AbortedTime: "Aborted time",
        About: "About",
        AboutGraphControl: "About Graph Control",
        AboutHPCCSystems: "About HPCC Systems®",
        AboutHPCCSystemsGraphControl: "About HPCC Systems® Graph Control",
        AboutToLoseSessionInformation: "You are about to log out and lose all session information. Do you wish to continue?",
        Account: "Account",
        Action: "Action",
        Activate: "Activate",
        ActivateQuery: "Activate Query",
        ActivateQueryDeletePrevious: "Activate query, delete previous",
        ActivateQuerySuspendPrevious: "Activate query, suspend previous",
        Activated: "Activated",
        Active: "Active",
        ActivePackageMap: "Active Package Map",
        ActiveWorkunit: "Active Workunit",
        Activities: "Activities",
        Activity: "Activity",
        ActivityMap: "Activity Map",
        ActualSize: "Actual Size",
        Add: "Add",
        AddAttributes: "Add attributes/values to your method",
        AddAttributes2: "Add Attribute(s)",
        AddBinding: "Add Binding",
        AddFile: "Add File",
        AddGroup: "Add Group",
        AddtionalProcessesToFilter: "Addtional Processes To Filter",
        AdditionalResources: "Additional Resources",
        AddPart: "Add Part",
        AddProcessMap: "Add Package Map",
        AddTheseFilesToDali: "Add these files to Dali?",
        AddToSuperfile: "Add To Superfile",
        AddToExistingSuperfile: "Add to an existing superfile",
        AddUser: "Add User",
        Advanced: "Advanced",
        All: "All",
        AllowAccess: "<center>Allow<br>Access</center>",
        AllowForeignFiles: "Allow Foreign Files",
        AllowFull: "<center>Allow<br>Full</center>",
        AllQueries: "All Queries",
        AllowRead: "<center>Allow<br>Read</center>",
        AllowWrite: "<center>Allow<br>Write</center>",
        AllQueuedItemsCleared: "All Queued items have been cleared. The current running job will continue to execute.",
        Analyze: "Analyze",
        ANY: "ANY",
        AnyAdditionalProcessesToFilter: "Any Addtional Processes To Filter",
        Append: "Append",
        AppendCluster: "Append Cluster",
        Apply: "Apply",
        AreYouSureYouWantToResetTheme: "Are you sure you want to reset to the default theme?",
        ArchivedOnly: "Archived Only",
        ArchivedWarning: "Warning: please specify a small date range. If not, it may take some time to retrieve the workunits and the browser may be timed out.",
        Attach: "Attach",
        Audience: "Audience",
        AuditLogs: "Audit Log",
        BinaryInstalls: "Binary Installs",
        Attribute: "Attribute",
        AttributesAreRequired: "Attributes are required",
        AutoRefresh: "Auto Refresh",
        AutoRefreshIncrement: "Auto Refresh Increment",
        AutoRefreshEvery: "Auto refresh every x minutes",
        Back: "Back",
        BannerColor: "Banner Colour",
        BannerMessage: "Banner Message",
        BannerScroll: "Banner Scroll",
        BannerSize: "Banner Size",
        Bind: "Bind",
        Binding: "Binding",
        BindingDeleted: "Binding Deleted",
        Blob: "BLOB",
        BlobPrefix: "BLOB Prefix",
        Blooms: "Blooms",
        Bottom: "Bottom",
        BoundBy: "bound by:",
        BrowserStats: "Browser Stats",
        Busy: "Busy",
        Cancel: "Cancel",
        CancelAll: "Cancel All",
        CancelAllMessage: "Abort running jobs and clear queue. Do you wish to continue?",
        Chart: "Chart",
        Channel: "Channel",
        CheckAllNodes: "Check All Nodes",
        CheckFilePermissions: "Check File Permissions",
        CheckSingleNode: "Check Single Node",
        Clear: "Clear",
        Client: "Client",
        Clone: "Clone",
        CloneTooltip: "Duplicate workunit",
        Close: "Close",
        Cluster: "Cluster",
        ClusterName: "Cluster Name",
        ClusterPlaceholder: "r?x*",
        ClusterProcesses: "Cluster Processes",
        Code: "Code",
        CodeGenerator: "Code Generator",
        Col: "Col",
        CollapseAll: "Collapse All",
        Command: "Command",
        Comment: "Comment",
        Compiled: "Compiled",
        Compiling: "Compiling",
        Completed: "Completed",
        ComplexityWarning: "More than {threshold} activities ({activityCount}) - suppress initial display?",
        CompressedFileSize: "Compressed File Size",
        Component: "Component",
        ComponentLogs: "Component Log",
        Compress: "Compress",
        Compressed: "Compressed",
        ComputerUpTime: "Computer Up Time",
        Condition: "Condition",
        ConfigureService: "Configure service",
        Configuration: "Configuration",
        ConfirmPassword: "Confirm Password",
        ConfirmRemoval: "Are you sure you want to do this?",
        ContactAdmin: "If you wish to rename this group, please contact your LDAP admin.",
        ContinueWorking: "Continue Working",
        Content: "Content",
        Contents: "Contents",
        ContentType: "Content Type",
        Copy: "Copy",
        CopyToClipboard: "Copy to clipboard",
        CopyURLToClipboard: "Copy URL to clipboard",
        CopyWUIDs: "Copy WUIDs to clipboard",
        CopyWUIDToClipboard: "Copy WUID to clipboard",
        CopyLogicalFiles: "Copy Logical Files to clipboard",
        Copied: "Copied!",
        Count: "Count",
        CPULoad: "CPU Load",
        Create: "Create",
        CreateANewFile: "Create a new superfile",
        Created: "Created",
        CreatedByWorkunit: "Created by workunit",
        Creating: "Creating",
        CreatedBy: "Created By",
        CreatedTime: "Created Time",
        Critical: "Critical",
        ClearPermissionsCache: "Clear Permissions Cache",
        ClearPermissionsCacheConfirm: "Are you sure you want to clear the DALI and ESP permissions caches? Running workunit performance might degrade significantly until the caches have been refreshed.",
        ClonedWUID: "Cloned WUID",
        CSV: "CSV",
        Dali: "Dali",
        DaliIP: "DaliIP",
        DataPatterns: "Data Patterns",
        DataPatternsNotStarted: "Analysis not found.  To start, press Analyze button above.",
        DataPatternsStarted: "Analyzing.  Once complete report will display here.",
        dataset: ":=dataset*",
        Date: "Date",
        Day: "Day",
        Deactivate: "Deactivate",
        Debug: "Debug",
        DEF: "DEF",
        Defaults: "Defaults",
        Definition: "Definition",
        DefinitionID: "Definition ID",
        Definitions: "Definitions",
        DefinitionDeleted: "Definition deleted",
        DelayedReplication: "Delayed replication",
        Delete: "Delete",
        DeleteBinding: "Delete Binding",
        DeletedBinding: "Deleted Binding",
        Deleted: "Deleted",
        DeleteEmptyDirectories: "Delete empty directories?",
        DeleteDirectories: "Remove empty directories. Do you wish to continue?",
        DeletePrevious: "Delete Previous",
        DeleteSelectedDefinitions: "Delete selected definitions?",
        DeleteSelectedFiles: "Delete Selected Files?",
        DeleteSelectedGroups: "Delete selected group(s)?",
        DeleteSelectedPackages: "Delete selected packages?",
        DeleteSelectedPermissions: "Delete selected permission(s)?",
        DeleteSelectedQueries: "Delete Selected Queries?",
        DeleteSelectedUsers: "Delete selected user(s)?",
        DeleteSelectedWorkunits: "Delete Selected Workunits?",
        DeleteSuperfile: "Delete Superfile?",
        DeleteSuperfile2: "Delete Superfile",
        DeleteThisPackage: "Delete this package?",
        Delimited: "Delimited",
        DenyAccess: "<center>Deny<br>Access</center>",
        DenyFull: "<center>Deny<br>Full</center>",
        DenyRead: "<center>Deny<br>Read</center>",
        DenyWrite: "<center>Deny<br>Write</center>",
        Depth: "Depth",
        DepthTooltip: "Maximum Subgraph Depth",
        Deschedule: "Deschedule",
        DescheduleSelectedWorkunits: "Deschedule Selected Workunits?",
        Description: "Description",
        DESDL: "Dynamic ESDL",
        Despray: "Despray",
        Details: "Details",
        DFUServerName: "DFU Server Name",
        DFUWorkunit: "DFU Workunit",
        Directories: "Directories",
        Directory: "Directory",
        DisableScopeScans: "Disable Scope Scans",
        DisableScopeScanConfirm: "Are you sure you want to disable Scope Scans?  Changes will revert to configuration settings on DALI reboot.",
        DiskUsage: "Disk Usage",
        Distance: "Distance",
        DistanceTooltip: "Maximum Activity Neighbourhood Distance",
        Dll: "Dll",
        DoNotActivateQuery: "Do not activate query",
        DoNotRepublish: "Do not republish?",
        Documentation: "Documentation",
        Domain: "Domain",
        DOT: "DOT",
        DOTAttributes: "DOT Attributes",
        Down: "Down",
        Download: "Download",
        Downloads: "Downloads",
        DownloadToCSV: "Download to CSV",
        DropZone: "Drop Zone",
        DueToInctivity: "You will be logged out of all ECL Watch sessions in 3 minutes due to inactivity.",
        Duration: "Duration",
        DynamicNoServicesFound: "No services found",
        EBCDIC: "EBCDIC",
        ECL: "ECL",
        ECLWatchRequiresCookies: "ECL Watch requires cookies enabled to continue.",
        ECLWatchSessionManagement: "ECL Watch session management",
        ECLWorkunit: "ECL Workunit",
        Edges: "Edges",
        Edit: "Edit",
        EditDOT: "Edit DOT",
        EditGraphAttributes: "Edit Graph Attributes",
        EditXGMML: "Edit XGMML",
        EmailTo: "Email Address (To)",
        EmailFrom: "Email Address (From)",
        EmailBody: "Email Body",
        EmailSubject: "Email Subject",
        EmployeeID: "Employee ID",
        EmployeeNumber: "Employee Number",
        Empty: "(Empty)",
        Enable: "Enable",
        EnableBannerText: "Enable Environment Text",
        EnableScopeScans: "Enable Scope Scans",
        EnableScopeScansConfirm: "Are you sure you want to enable Scope Scans? Changes will revert to configuration settings on DALI reboot.",
        EnglishQ: "English?",
        EnterAPercentage: "Enter a percentage",
        EnterAPercentageOrMB: "Enter A Percentage or MB",
        EraseHistory: "Erase History",
        EraseHistoryQ: "Erase history for:",
        Error: "Error",
        Errorparsingserverresult: "Error parsing server result",
        Errors: "Error(s)",
        ErrorsStatus: "Errors/Status",
        ErrorUploadingFile: "Error uploading file(s). Try checking permissions.",
        ErrorWarnings: "Error/Warning(s)",
        Escape: "Escape",
        ESPBindings: "ESP Bindings",
        ESPBuildVersion: "ESP Build Version",
        ESPProcessName: "ESP Process Name",
        ESPNetworkAddress: "ESP Network Address",
        EventName: "Event Name",
        EventNamePH: "Event Name",
        EventScheduler: "Event Scheduler",
        EventText: "Event Text",
        EventTextPH: "Event Text",
        Exception: "Exception",
        ExpireDays: "Expire in (days)",
        FailIfNoSourceFile: "Fail If No Source File",
        Fatal: "Fatal",
        Fetched: "Fetched",
        FetchingData: "Fetching Data...",
        fetchingresults: "fetching results",
        Executed: "Executed",
        Executing: "Executing",
        ExpandAll: "Expand All",
        Export: "Export",
        ExportSelectionsToList: "Export Selections to List",
        FieldNames: "Field Names",
        File: "File",
        FileCluster: "File Cluster",
        FileCounts: "File Counts",
        FileName: "File Name",
        FileParts: "File Parts",
        FilePath: "File Path",
        Files: "Files",
        FilesPending: "Files pending",
        FileScopes: "File Scopes",
        FileScopeDefaultPermissions: "File Scope Default Permissions",
        FileSize: "File Size",
        FilesNoPackage: "Files without matching package definitions",
        FilePermission: "<b>File Permission</b>",
        FilesWarning: "The number of files returned is too large. Only the first 100,000 files sorted by date/time modified were returned. If you wish to limit results, set a filter.",
        FilesWithUnknownSize: "Files With Unknown Size",
        FileType: "File Type",
        FileUploader: "File Uploader",
        FileUploadStillInProgress: "File upload still in progress",
        Filter: "Filter",
        FilterDetails: "Filter Details",
        FilterSet: "Filter Set",
        Find: "Find",
        Finished: "Finished",
        FindNext: "Find Next",
        FindPrevious: "Find Previous",
        FirstN: "First N",
        FirstNSortBy: "Sort By",
        FirstName: "First Name",
        FirstNRows: "First N Rows",
        Fixed: "Fixed",
        Folder: "Folder",
        Format: "Format",
        Forums: "Forums",
        Forward: "Forward",
        FoundFile: "Found Files",
        FoundFileMessage: "A found file has all of its parts on disk that are not referenced in the Dali server. All the file parts are accounted for so they can be added back to the Dali server. They can also be deleted from the cluster, if required.",
        FromDate: "From Date",
        FromSizes: "From Sizes",
        FromTime: "From Time",
        FullName: "Full Name",
        Generate: "Generate",
        GetPart: "Get Part",
        GetSoftwareInformation: "Get Software Information",
        Graph: "Graph",
        Graphs: "Graphs",
        GraphControl: "Graph Control",
        GraphView: "Graph View",
        Group: "Group",
        GroupBy: "Group By",
        Grouping: "Grouping",
        GroupDetails: "Group Details",
        GroupName: "Group Name",
        GroupPermissions: "Group Permissions",
        Groups: "Groups",
        GZip: "GZip",
        help: "This area displays the treemap for the graph(s) in this workunit. The size and hue indicate the duration of each graph (Larger and darker indicates a greater percentage of the time taken.)",
        Helper: "Helper",
        Helpers: "Helpers",
        Hex: "Hex",
        HideSpills: "Hide Spills",
        High: "High",
        History: "History",
        HPCCSystems: "HPCC Systems®",
        Icon: "Icon",
        ID: "ID",
        Inactive: "Inactive",
        IncludeSlaveLogs: "Include slave logs",
        Index: "Index",
        Info: "Info",
        Informational: "Informational",
        InfoDialog: "Info Dialog",
        InheritedPermissions: "Inherited permission:",
        Inputs: "Inputs",
        InUse: "In Use",
        InvalidResponse: "(Invalid response)",
        InvalidUsernamePassword: "Invalid username or password, try again.",
        IP: "IP",
        IPAddress: "IP Address",
        IsCompressed: "Is Compressed",
        IsLibrary: "Is Library",
        IsReplicated: "Is Replicated",
        IssueReporting: "Issue Reporting",
        Jobname: "Jobname",
        JobName: "Job Name",
        jsmi: "jsmi*",
        JSmith: "JSmit*",
        JSON: "JSON",
        KeyFile: "Key File",
        KeyType: "Key Type",
        Label: "Label",
        LandingZone: "Landing Zone",
        LandingZones: "Landing Zones",
        LanguageFiles: "Language Files",
        Largest: "Largest",
        LargestFile: "Largest File",
        LargestSize: "Largest Size",
        LastEdit: "Last Edit",
        LastEditedBy: "Last Edited By",
        LastEditTime: "Last Edit Time",
        LastMessage: "Last Message",
        LastName: "Last Name",
        LastNDays: "Last N Days",
        LastNHours: "Last N Hours",
        LastNRows: "Last N Rows",
        LastRun: "Last Run",
        LearnMore: "Learn More",
        LegacyForm: "Legacy Form",
        LegacyGraphWidget: "Legacy Graph Widget",
        LegacyGraphLayout: "Legacy Graph Layout",
        Legend: "Legend",
        LDAPWarning: "<b>LDAP Services Error:</b>  &lsquo;Too Many Users&rsquo; - Please use a Filter.",
        LibrariesUsed: "Libraries Used",
        LibraryName: "Library Name",
        Limit: "Limit",
        Line: "Line",
        LineTerminators: "Line Terminators",
        Links: "Links",
        LoadPackageContentHere: "(Load package content here)",
        LoadPackageFromFile: "Load Package from a file",
        Loading: "Loading...",
        LoadingCachedLayout: "Loading Cached Layout...",
        LoadingData: "Loading Data...",
        loadingMessage: "...Loading...",
        Local: "Local",
        LocalFileSystemsOnly: "Local File Systems Only",
        Location: "Location",
        Lock: "Lock",
        LogDirectory: "Log Directory",
        LogFile: "Log File",
        LoggedInAs: "Logged in as",
        LogicalFile: "Logical File",
        LogicalFiles: "Logical Files",
        LogicalFilesAndSuperfiles: "Logical Files and Superfiles",
        LogicalFilesOnly: "Logical Files Only",
        LogicalFileType: "Logical File Type",
        LogicalName: "Logical Name",
        Log: "Log",
        LoggingOut: "Logging out",
        Login: "Login",
        Logout: "Log Out",
        Logs: "Logs",
        LogVisualization: "Log Visualization",
        LogVisualizationUnconfigured: "Log Visualization is not configured, please check your configuration manager settings.",
        log_analysis_1: "log_analysis_1*",
        LostFile: "Lost Files",
        LostFile2: "Lost Files",
        LostFileMessage: "A logical file that is missing at least one file part on both the primary and replicated locations in storage. The logical file is still referenced in the Dali server. Deleting the file removes the reference from the Dali server and any remaining parts on disk.",
        Low: "Low",
        Machines: "Machines",
        MachineInformation: "Machine Information",
        Major: "Major",
        ManagedBy: "Managed By",
        ManagedByPlaceholder: "CN=HPCCAdmin,OU=users,OU=hpcc,DC=MyCo,DC=local",
        ManualCopy: "Press Ctrl+C",
        ManualOverviewSelection: "(Manual overview selection will be required)",
        ManualTreeSelection: "(Manual tree selection will be required)",
        Mappings: "Mappings",
        Mask: "Mask",
        Max: "Max",
        MaxNode: "Max Node",
        MaxSize: "Max Size",
        MaxSkew: "Max Skew",
        MaxSkewPart: "Max Skew Part",
        MaximizeRestore: "Maximize/Restore",
        MaximumNumberOfSlaves: "Slave Number",
        MaxRecordLength: "Max Record Length",
        Mean: "Mean",
        MemberOf: "Member Of",
        Members: "Members",
        MethodConfiguration: "Method Configuration",
        Message: "Message",
        Methods: "Methods",
        Min: "Min",
        Mine: "Mine",
        MinNode: "Min Node",
        MinSize: "Min Size",
        MinSkew: "Min Skew",
        MinSkewPart: "Min Skew Part",
        Minor: "Minor",
        Missing: "Missing",
        MixedNodeStates: "Mixed Node States",
        Modified: "Modified",
        Modification: "Modification",
        ModifiedUTCGMT: "Modified (UTC/GMT)",
        Modify: "Modify",
        Monitoring: "Monitoring",
        MonitorEventName: "Monitor Event Name",
        MonitorShotLimit: "Monitor Shot Limit",
        MonitorSub: "Monitor Sub",
        Month: "Month",
        More: "more",
        MustContainUppercaseAndSymbol: "Must contain uppercase and symbol",
        NA: "N/A",
        Name: "Name",
        NameOfEnvironment: "Name Of Environment",
        NamePrefix: "Name Prefix",
        NamePrefixPlaceholder: "some::prefix",
        NetworkAddress: "Network Address",
        Newest: "Newest",
        NewPassword: "New Password",
        NoContent: "(No content)",
        NoCommon: "No Common",
        noDataMessage: "...Zero Rows...",
        Node: "Node",
        NodeGroup: "Node Group",
        None: "None",
        NoErrorFound: "No errors found\n",
        NoFilterCriteriaSpecified: "No filter criteria specified.",
        NoPublishedSize: "No published size",
        NoRecentFiltersFound: "No recent filters found.",
        NoScheduledEvents: "No Scheduled Events.",
        NoSplit: "No Split",
        NotActive: "Not active",
        NothingSelected: "Nothing Selected...",
        NotInSuperfiles: "Not in Superfiles",
        Normal: "Normal",
        NotSuspended: "Not Suspended",
        NotSuspendedbyUser: "Not Suspended By User",
        NoWarningFound: "No warnings found\n",
        NumberofParts: "Number of Parts",
        NumberofSlaves: "Number of Slaves",
        OK: "OK",
        Oldest: "Oldest",
        OldPassword: "Old Password",
        OmitSeparator: "Omit Separator",
        Only1PackageFileAllowed: "Only one package file allowed",
        Open: "Open",
        OpenConfiguration: "Open Configuration",
        OpenInNewPage: "Open in New Page",
        OpenInNewPageNoFrame: "Open in New Page (No Frame)",
        OpenLegacyECLWatch: "Open Legacy ECL Watch",
        OpenLegacyMode: "Open (legacy)",
        OpenNativeMode: "Open (native)",
        OpenSource: "Open Source",
        Operation: "Operation",
        Operations: "Operations",
        Options: "Options",
        Optimize: "Optimize",
        OriginalFile: "Original File",
        OrphanFile: "Orphan Files",
        OrphanFile2: "Orphan File",
        OrphanMessage: "An orphan file has partial file parts on disk. However, a full set of parts is not available to construct a complete logical file. There is no reference to these file parts in the Dali server.",
        OSStats: "OS Stats",
        Outputs: "Outputs",
        Overview: "Overview",
        Overwrite: "Overwrite",
        OverwriteMessage: "Some file(s) already exist. Please check overwrite box to continue.",
        Owner: "Owner",
        PackageContent: "Package Content",
        PackageContentNotSet: "Package content not set",
        PackageMap: "Package Map",
        PackageMaps: "Package Maps",
        PackagesNoQuery: "Packages without matching queries",
        ParameterXML: "Parameter XML",
        Part: "Part",
        PartName: "Part Name",
        PartMask: "Part Mask",
        Parts: "Parts",
        PartsFound: "Parts Found",
        PartsLost: "Parts Lost",
        Password: "Password",
        PasswordExpiration: "Password Expiration",
        PasswordOpenZAP: "Password to open ZAP (optional)",
        PasswordsDoNotMatch: "Passwords do not match.",
        PasswordExpired: "Your password has expired.  Please change now.",
        PasswordExpirePrefix: "Your password will expire in ",
        PasswordExpirePostfix: " day(s). Do you want to change it now?",
        Path: "Path",
        PathMask: "Path Mask",
        Pause: "Pause",
        PauseNow: "Pause Now",
        PctComplete: "% Complete",
        PercentCompressed: "Percent Compressed",
        PercentDone: "Percent Done",
        PercentUsed: "% Used",
        PerformingLayout: "Performing Layout...",
        PermissionName: "Permission Name",
        Permission: "Permission",
        Permissions: "Permissions",
        PhysicalFiles: "Physical Files",
        PhysicalMemory: "Physical Memory",
        PlaceholderFindText: "Wuid, User, (ecl:*, file:*, dfu:*, query:*)...",
        PlaceholderFirstName: "John",
        PlaceholderLastName: "Smith",
        Platform: "Platform",
        Playground: "Playground",
        PleaseEnableCookies: "ECL Watch requires cookies enabled to continue.",
        PleaseLogIntoECLWatch: "Please log into ECL Watch",
        PleasePickADefinition: "Please pick a definition",
        PleaseSelectAGroupToAddUser: "Please select a group to add the user to",
        PleaseSelectAUserOrGroup: "Please select a user or a group along with a file name",
        PleaseSelectAUserToAdd: "Please select a user to add",
        PleaseSelectADynamicESDLService: "Please select a dynamic ESDL service",
        PleaseSelectAServiceToBind: "Please select a service to bind",
        PleaseSelectATopologyItem: "Please select a target, service or machine.",
        Plugins: "Plugins",
        PleaseEnterANumber: "Please enter a number 1 - ",
        PleaseLogin: "Please log in using your username and password",
        Port: "Port",
        Prefix: "Prefix",
        PrefixPlaceholder: "filename{:length}, filesize{:[B|L][1-8]}",
        Preflight: "Preflight",
        PreloadAllPackages: "Preload All Packages",
        PreserveCompression: "Preserve Compression",
        PreserveParts: "Preserve File Parts",
        PressCtrlCToCopy: "Press ctrl+c to copy.",
        Preview: "Preview",
        PrimaryLost: "Primary Lost",
        PrimaryMonitoring: "Primary Monitoring",
        Priority: "Priority",
        Probability: "Probability",
        Process: "Process",
        Processes: "Processes",
        ProcessesDown: "Processes Down",
        ProcessFilter: "Process Filter",
        ProcessorInformation: "Processor Information",
        ProgressMessage: "Progress Message",
        Properties: "Properties",
        Property: "Property",
        Protect: "Protect",
        ProtectBy: "Protected by",
        Protected: "Protected",
        Protocol: "Protocol",
        Publish: "Publish",
        Published: "Published",
        PublishedBy: "Published By",
        PublishedByMe: "Published by me",
        PublishedQueries: "Published Queries",
        PushEvent: "Push Event",
        Quarter: "Quarter",
        Queries: "Queries",
        QueriesNoPackage: "Queries without matching package",
        Query: "Query",
        QueryDetailsfor: "Query Details for",
        QueryID: "Query ID",
        QueryIDPlaceholder: "som?q*ry.1",
        QueryName: "Query Name",
        QueryNamePlaceholder: "My?Su?erQ*ry",
        QuerySet: "Query Set",
        Queue: "Queue",
        Quote: "Quote",
        QuotedTerminator: "Quoted Terminator",
        RawData: "Raw Data",
        RawTextPage: "Raw Text (Current Page)",
        Ready: "Ready",
        ReallyWantToRemove: "Really want to remove?",
        ReAuthenticate: "Reauthenticate to unlock",
        RecentFilters: "Recent Filters",
        RecentFiltersTable: "Recent Filters Table",
        RecreateQuery: "Recreate Query",
        RecordCount: "Record Count",
        RecordLength: "Record Length",
        Records: "Records",
        RecordSize: "Record Size",
        RecordStructurePresent: "Record Structure Present",
        Recover: "Recover",
        RecoverTooltip: "Restart paused / stalled workunit",
        Recycling: "Recycling",
        RedBook: "Red Book",
        Refresh: "Refresh",
        ReleaseNotes: "Release Notes",
        Reload: "Reload",
        Remaining: "Remaining",
        RemoteCopy: "Remote Copy",
        RemoteDali: "Remote Dali",
        RemoteDaliIP: "Remote Dali IP Address",
        Remove: "Remove",
        RemoveAtttributes: "Remove Attribute(s)",
        RemoveAttributeQ: "You are about to remove this attribute. Are you sure you want to do this?",
        RemovePart: "Remove Part",
        RemoveSubfiles: "Remove Subfile(s)",
        RemoveSubfiles2: "Remove Subfile(s)?",
        RemoveUser: "You are about to remove yourself from the group:",
        Rename: "Rename",
        RenderedSVG: "Rendered SVG",
        RenderSVG: "Render SVG",
        Replicate: "Replicate",
        ReplicatedLost: "Replicated Lost",
        ReplicateOffset: "Replicate Offset",
        Report: "Report",
        RepresentsASubset: "represent a subset of the total number of matches. Using a correct filter may reduce the number of matches.",
        RequestSchema: "Request Schema",
        RequiredForFixedSpray: "Required for fixed spray",
        RequiredForXML: "Required for spraying XML",
        Reschedule: "Reschedule",
        Reset: "Reset",
        ResetThisQuery: "Reset This Query?",
        ResetViewToSelection: "Reset View to Selection",
        Resource: "Resource",
        Resources: "Resources",
        Restricted: "Restricted",
        ResponseSchema: "Response Schema",
        Restart: "Restart",
        Restarted: "Restarted",
        Restore: "Restore",
        Resubmit: "Resubmit",
        ResubmitTooltip: "Resubmit existing workunit",
        Resubmitted: "Resubmitted",
        Results: "Result(s)",
        Resume: "Resume",
        RetainSuperfileStructure: "Retain Superfile Structure",
        RetainSuperfileStructureReason: "Retain Superfile Structure must be enabled when more than 1 subfile exists.",
        RetypePassword: "Retype Password",
        Reverse: "Reverse",
        RoxieFileCopy: "Roxie Files Copy Status",
        RoxieState: "Roxie State",
        Rows: "Rows",
        RowPath: "Row Path",
        RowTag: "Row Tag",
        RoxieCluster: "Roxie Cluster",
        RunningServerStrain: "Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?",
        Sample: "Sample",
        SampleRequest: "Sample Request",
        SampleResponse: "Sample Response",
        Save: "Save",
        Scope: "Scope",
        SearchResults: "Search Results",
        SecondsRemaining: "Seconds Remaining",
        Security: "Security",
        SelectPackageFile: "Select Package File",
        SendEmail: "Send Email",
        Separators: "Separators",
        ServiceName: "Service Name",
        Services: "Services",
        ServiceType: "Service Type",
        Server: "Server",
        SetBanner: "Set Banner",
        SetTextError: "Failed to display text (too large?).  Use &lsquo;helpers&rsquo; to download.",
        SetToFailed: "Set To Failed",
        SetToolbar: "Set Toolbar",
        Severity: "Severity",
        ShareWorkunit: "Share Workunit URL",
        Show: "Show",
        ShowProcessesUsingFilter: "Show Processes Using Filter",
        ShowSVG: "Show SVG",
        Size: "Size",
        Skew: "Skew",
        SkewNegative: "Skew(-)",
        SkewPositive: "Skew(+)",
        SLA: "SLA",
        Slaves: "Slaves",
        SlaveLogs: "Slave Logs",
        SlaveNumber: "Slave Number",
        Smallest: "Smallest",
        SmallestFile: "Smallest File",
        SmallestSize: "Smallest Size",
        SOAP: "SOAP",
        SomeDescription: "Some*Description",
        somefile: "*::somefile*",
        Source: "Source",
        SourceCode: "Source Code",
        SourceLogicalFile: "Source Logical Name",
        SourcePath: "Source Path (Wildcard Enabled)",
        SourceProcess: "Source Process",
        SparkThor: "SparkThor",
        Spill: "Spill",
        SplitPrefix: "Split Prefix",
        Spray: "Spray",
        Start: "Start",
        Starting: "Starting",
        Started: "Started",
        State: "State",
        Status: "Status",
        Stats: "Stats",
        Stopped: "Stopped",
        Stopping: "Stopping",
        StorageInformation: "Storage Information",
        Subgraph: "Subgraph",
        Subgraphs: "Subgraphs",
        Submit: "Submit",
        Subtype: "Subtype",
        SuccessfullySaved: "Successfully Saved",
        Summary: "Summary",
        SummaryMessage: "Summary Message",
        Superfile: "Superfile",
        Superfiles: "Superfiles",
        SuperFile: "Super File",
        SuperFiles: "Super Files",
        SuperFilesBelongsTo: "Member of Superfile(s)",
        SuperfilesOnly: "Superfiles Only",
        SuperOwner: "Super Owner",
        Suspend: "Suspend",
        Suspended: "Suspended",
        SuspendedBy: "Suspended By",
        SuspendedByAnyNode: "Suspended By Any Node",
        SuspendedByCluster: "Suspended By Cluster",
        SuspendedByFirstNode: "Suspended By First Node",
        SuspendedByUser: "Suspended By User",
        SuspendedReason: "Suspended Reason",
        SVGSource: "SVG Source",
        SyncSelection: "Sync To Selection",
        SystemServers: "System Servers",
        tag: "tag",
        Target: "Target",
        Targets: "Targets",
        TargetClusters: "Target Clusters",
        TargetClustersLegacy: "Target Clusters (legacy)",
        TargetName: "Target Name",
        TargetNamePlaceholder: "some::logical::name",
        TargetRowTagRequired: "You must supply a target row tag",
        TargetScope: "Target Scope",
        TargetWuid: "Target/Wuid",
        Terminators: "Terminators",
        TestPages: "Test Pages",
        TheReturnedResults: "The returned results",
        ThorNetworkAddress: "Thor Network Address",
        ThorMasterAddress: "Thor Master Address",
        ThorProcess: "Thor Process",
        Table: "Table",
        Time: "Time",
        TimeStamp: "Time Stamp",
        TimeSeconds: "Time (Seconds)",
        TimeStarted: "Time Started",
        TimeStopped: "Time Stopped",
        Timers: "Timers",
        Timings: "Timings",
        TimingsMap: "Timings Map",
        title_Activity: "Activity",
        title_ActivePermissions: "Active Permissions",
        title_ActiveGroupPermissions: "Active Group Permissions",
        title_AvailablePermissions: "Available Permissions",
        title_AvailableGroupPermissions: "Available Group Permissions",
        title_BindingConfiguration: "Binding Configuration",
        title_BindingDefinition: "Binding Definition",
        title_Blooms: "Blooms",
        title_ClusterInfo: "Groups",
        title_Clusters: "Clusters",
        title_CodeGeneratorPermissions: "Code Generator Permissions",
        title_DirectoriesFor: "Directories for",
        title_Definitions: "Definitions",
        title_DefinitionExplorer: "Definition Explorer",
        title_DESDL: "Dynamic ESDL",
        title_DFUQuery: "Logical Files",
        title_DFUWUDetails: "DFU Workunit",
        title_DiskUsage: "Disk Usage",
        title_ECLPlayground: "ECL Playground",
        title_ErrorsWarnings: "Errors/Warnings for",
        title_EventScheduleWorkunit: "Event Scheduler",
        title_FileScopeDefaultPermissions: "Default permissions of files",
        title_FilesPendingCopy: "Files pending copy",
        title_FoundFilesFor: "Found files for",
        title_GetDFUWorkunits: "DFU Workunits",
        title_Graph: "Graph",
        title_GraphPage: "title",
        title_Graphs: "Graphs",
        title_GridDetails: "Change Me",
        title_HPCCPlatformECL: "ECL Watch - Home",
        title_HPCCPlatformFiles: "ECL Watch - Files",
        title_HPCCPlatformMain: "ECL Watch - Home",
        title_HPCCPlatformOps: "ECL Watch - Operations",
        title_HPCCPlatformRoxie: "ECL Watch - Roxie",
        title_HPCCPlatformServicesPlugin: "ECL Watch - Plugins",
        title_History: "History",
        title_Inputs: "Inputs",
        title_Log: "Log File",
        title_LFDetails: "Logical File Details",
        title_LZBrowse: "Landing Zones",
        title_Methods: "Methods",
        title_MemberOf: "Member Of",
        title_Members: "Members",
        title_LostFilesFor: "Lost files for",
        title_LibrariesUsed: "Libraries Used",
        title_OrphanFilesFor: "Orphan files for",
        title_Permissions: "Permissions",
        title_ProtectBy: "Protected By",
        title_QuerySetDetails: "Query Details",
        title_QuerySetErrors: "Errors",
        title_QuerySetLogicalFiles: "Logical Files",
        title_QuerySetQuery: "Queries",
        title_QuerySetSuperFiles: "Super Files",
        title_QueryTest: "Super Files",
        title_Result: "Activity",
        title_Results: "Outputs",
        title_PackageParts: "Package Parts",
        title_Preflight: "System Metrics",
        title_PreflightResults: "Preflight Results",
        title_SearchResults: "Search Results",
        title_SourceFiles: "",
        title_SystemServers: "System Servers",
        title_SystemServersLegacy: "System Servers (legacy)",
        title_TargetClusters: "Target Clusters",
        title_Topology: "Topology",
        title_TpThorStatus: "Thor Status",
        title_UserQuery: "Permissions",
        title_UserPermissions: "User Permissions",
        title_WUDetails: "ECL Workunit Details",
        title_WorkunitScopeDefaultPermissions: "Default permissions of workunits",
        title_WUQuery: "ECL Workunits",
        To: "To",
        ToDate: "To Date",
        Toenablegraphviews: "To enable graph views, please install the Graph View Control plugin",
        Tooltip: "Tooltip",
        TooManyFiles: "Too many files",
        Top: "Top",
        Topology: "Topology",
        ToSizes: "To Sizes",
        Total: "Total",
        TotalParts: "Total Parts",
        TotalSize: "Total Size",
        TotalClusterTime: "Total Cluster Time",
        ToTime: "To Time",
        TransitionGuide: "Transition Guide",
        Text: "Text",
        Tree: "Tree",
        Type: "Type",
        Unbound: "unbound",
        undefined: "undefined",
        Unknown: "Unknown",
        Unlock: "Unlock",
        Unprotect: "Unprotect",
        UnsupportedIE9FF: "Unsupported (IE <= 9, FireFox)",
        Unsuspend: "Unsuspend",
        Unsuspended: "Unsuspended",
        Up: "Up",
        UpdateCloneFrom: "Update Clone From",
        UpdateDFs: "Update DFS",
        UpdateSuperFiles: "Update Super Files",
        Upload: "Upload",
        UpTime: "Up Time",
        URL: "URL",
        Usage: "Usage",
        Used: "Used",
        UsedByWorkunit: "Used by workunit",
        User: "User",
        UserDetails: "User Details",
        UserID: "User ID",
        UserLogin: "Please log in using your username only",
        Username: "Username",
        UserName: "User Name",
        UserPermissions: "User Permissions",
        Users: "Users",
        UseSingleConnection: "Use Single Connection",
        Validate: "Validate",
        Validating: "Validating...",
        ValidateActivePackageMap: "Validate Active Package Map",
        ValidatePackageContent: "Validate Package Content",
        ValidatePackageMap: "Validate Package Map",
        ValidateResult: "=====Validate Result=====\n\n",
        ValidateResultHere: "(Validation result)",
        Value: "Value",
        Variable: "Variable",
        Variables: "Variables",
        VariableBigendian: "Variable Big-endian",
        VariableSourceType: "Source Type",
        Version: "Version",
        ViewByScope: "View By Scope",
        Views: "Views",
        ViewSparkClusterInfo: "View Spark Cluster Information",
        Visualize: "Visualize",
        Warning: "Warning",
        Warnings: "Warning(s)",
        WarnIfCPUUsageIsOver: "Warn if CPU usage is over",
        WarnIfAvailableMemoryIsUnder: "Warn if available memory is under",
        WarnIfAvailableDiskSpaceIsUnder: "Warn if available disk space is under",
        WarnOldGraphControl: "Warning:  Old Graph Control",
        What: "What",
        Where: "Where",
        Who: "Who",
        Width: "Width",
        Workflows: "Workflows",
        Workunit: "Workunit",
        Workunits: "Workunits",
        WorkUnitScopeDefaultPermissions: "Workunit Scope Default Permissions",
        Wrap: "Wrap",
        WSDL: "WSDL",
        WUID: "WUID",
        Wuidcannotbeempty: "Wuid Cannot Be Empty.",
        WUSnapShot: "WU Snap Shot",
        XGMML: "XGMML",
        XLS: "XLS",
        XML: "XML",
        XRef: "XRef",
        Year: "Year",
        YouAreAboutToBeLoggedOut: "You are about to be logged out",
        YouAreAboutToRemoveUserFrom: "You are about to remove a user(s) from this group. Do you wish to continue?",
        YouAreAboutToDeleteBinding: "You are about to delete this binding. Are you sure you want to do this?",
        YouAreAboutToDeleteDefinition: "You are about to delete this definition. Are you sure you want to do this?",
        YouAreAboutToDeleteThisFile: "You are about to delete this file. Are you sure you want to do this?",
        YouAreAboutToDeleteThisPart: "You are about to delete this part(s). Are you sure you want to do this?",
        YouAreAboutToDeleteThisQueryset: "You are about to delete this query set. Are you sure you want to do this?",
        YouAreAboutToDeleteThisWorkunit: "You are about to delete this workunit. Are you sure you want to do this?",
        YourBrowserMayNotSupport: "Your browser may not support file(s) of this size",
        YourScreenWasLocked: "Your screen was locked by ESP. Please re-fetch your data, as it may be stale.",
        ZAP: "Z.A.P",
        ZeroLogicalFilesCheckFilter: "Zero Logical Files(check filter)",
        Zip: "Zip",
        ZippedAnalysisPackage: "Zipped Analysis Package",
        Zoom: "Zoom",
        ZoomPlus: "Zoom +",
        ZoomMinus: "Zoom -",
        Zoom100Pct: "Zoom 100%",
        ZoomAll: "Zoom All",
        ZoomWidth: "Zoom Width"
    },
    "bs": true,
    "es": true,
    "fr": true,
    "hu": true,
    "hr": true,
    "pt-br": true,
    "sr": true,
    "zh": true
}
