/*##############################################################################

    Copyright (C) 2011 HPCC Systems.

    All rights reserved. This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################## */
#include "platform.h"
#include "jlib.hpp"
#include "jexcept.hpp"
#include "jmisc.hpp"
#include "javahash.hpp"
#include "eclhelper.hpp"

#include "hql.hpp"
#include "hqlatoms.hpp"
#include "hqlcatom.hpp"

_ATOM activeActivityMarkerAtom;
_ATOM activeMatchTextAtom;
_ATOM activeMatchUnicodeAtom;
_ATOM activeMatchUtf8Atom;
_ATOM activeProductionMarkerAtom;
_ATOM activeValidateMarkerAtom;
_ATOM activityIdMarkerAtom;
_ATOM acosAtom;
_ATOM addAggregateRowAtom;
_ATOM addAllAtom;
_ATOM addRangeAtom;
_ATOM addWorkunitAssertFailureAtom;
_ATOM addWorkunitExceptionAtom;
_ATOM an2bAtom;
_ATOM an2fAtom;
_ATOM an2l4Atom;
_ATOM an2l8Atom;
_ATOM an2ls4Atom;
_ATOM an2ls8Atom;
_ATOM appendRowsToRowsetAtom;
_ATOM appendSetXAtom;
_ATOM ascii2ebcdicAtom;
_ATOM asinAtom;
_ATOM atan2Atom;
_ATOM atanAtom;
_ATOM balancedAtom;
_ATOM bitfieldOffsetAtom;
_ATOM blobHelperAtom;
_ATOM bool2DataAtom;
_ATOM bool2StrAtom;
_ATOM bool2StrXAtom;
_ATOM bool2VStrAtom;
_ATOM bool2VStrXAtom;
_ATOM branchAtom;
_ATOM castIntAtom[9][2];
_ATOM checkFieldOverflowAtom;
_ATOM checkPersistMatchesAtom;
_ATOM checkpointAtom;
_ATOM checkRowOverflowAtom;
_ATOM childAtom;
_ATOM classAtom;
_ATOM clearAtom;
_ATOM __clearHelperAtom;
_ATOM clearPersistAtom;
_ATOM clibExpIdAtom;
_ATOM codeGeneratorAtom;
_ATOM codepage2UnicodeAtom;
_ATOM codepage2UnicodeXAtom;
_ATOM codepageToUtf8Atom;
_ATOM codepageToUtf8XAtom;
_ATOM codepage2VUnicodeAtom;
_ATOM codepage2VUnicodeXAtom;
_ATOM columnGetBoolAtom;
_ATOM columnGetDataAtom;
_ATOM columnGetDataXAtom;
_ATOM columnGetIntAtom;
_ATOM columnGetQStringAtom;
_ATOM columnGetSetIsAllAtom;
_ATOM columnGetStringAtom;
_ATOM columnGetStringXAtom;
_ATOM columnGetUnicodeXAtom;
_ATOM columnGetUtf8XAtom;
_ATOM columnReadBoolAtom;
_ATOM columnReadDataAtom;
_ATOM columnReadDataXAtom;
_ATOM columnReadIntAtom;
_ATOM columnReadQStringAtom;
_ATOM columnReadSetIsAllAtom;
_ATOM columnReadStringAtom;
_ATOM columnReadStringXAtom;
_ATOM columnReadUnicodeXAtom;
_ATOM columnReadUtf8XAtom;
_ATOM compareDataDataAtom;
_ATOM compareEStrEStrAtom;
_ATOM compareQStrQStrAtom;
_ATOM compareStrBlankAtom;
_ATOM compareStrStrAtom;
_ATOM compareUnicodeUnicodeAtom;
_ATOM compareUnicodeUnicodeStrengthAtom;
_ATOM compareUtf8Utf8Atom;
_ATOM compareUtf8Utf8StrengthAtom;
_ATOM compareVStrVStrAtom;
_ATOM compareVUnicodeVUnicodeAtom;
_ATOM compareVUnicodeVUnicodeStrengthAtom;
_ATOM concatAtom;
_ATOM concatExtendAtom;
_ATOM concatStr2StrAtom;
_ATOM concatStrFAtom;
_ATOM concatUnicodeAtom;
_ATOM concatUnicodeFAtom;
_ATOM concatUnicodeToUnicodeAtom;
_ATOM concatUtf8Atom;
_ATOM concatUtf8ToUtf8Atom;
_ATOM concatVStr2StrAtom;
_ATOM concatVStrAtom;
_ATOM concatVStrFAtom;
_ATOM concatVUnicodeAtom;
_ATOM concatVUnicodeFAtom;
_ATOM concatVUnicodeToUnicodeAtom;
_ATOM _conditionalRowMarker_Atom;
_ATOM containerAtom;
_ATOM cosAtom;
_ATOM coshAtom;
_ATOM countIndexAtom;
_ATOM countProviderAtom;
_ATOM countRoxieDiskFileAtom;
_ATOM countRowsAtom;
_ATOM countToSizeAtom;
_ATOM crcDataAtom;
_ATOM crcUnicodeAtom;
_ATOM crcUtf8Atom;
_ATOM crcVStrAtom;
_ATOM crcVUnicodeAtom;
_ATOM createBlobAtom;
_ATOM createDataRangeLowAtom;
_ATOM createDataRangeHighAtom;
_ATOM createOrderAtom;
_ATOM createQStrRangeLowAtom;
_ATOM createQStrRangeHighAtom;
_ATOM createQuotedStringAtom;
_ATOM createRangeLowAtom;
_ATOM createRangeHighAtom;
_ATOM createRowFromXmlAtom;
_ATOM createStrRangeLowAtom;
_ATOM createStrRangeHighAtom;
_ATOM createUnicodeRangeLowAtom;
_ATOM createUnicodeRangeHighAtom;
_ATOM createRegexAtom;
_ATOM createWRegexAtom;
_ATOM creatorAtom;
_ATOM csvReadMarkerAtom;
_ATOM csvStr2BoolAtom;
_ATOM ctxGetRowXmlAtom;
_ATOM currentAtom;
_ATOM data2BoolAtom;
_ATOM dataset2DatasetXAtom;
_ATOM dataset2RowsetXAtom;
_ATOM DecAbsAtom;
_ATOM DecAddAtom;
_ATOM DecCompareDecimalAtom;
_ATOM DecCompareUDecimalAtom;
_ATOM DecCompareNullAtom;
_ATOM DecDistinctAtom;
_ATOM DecDistinctRAtom;
_ATOM DecDivideAtom;
_ATOM decimalAtom;
_ATOM declareAtom;
_ATOM DecModulusAtom;
_ATOM DecMulAtom;
_ATOM DecNegateAtom;
_ATOM DecPopDecimalAtom;
_ATOM DecPopInt64Atom;
_ATOM DecPopLongAtom;
_ATOM DecPopRealAtom;
_ATOM DecPopStringAtom;
_ATOM DecPopStringXAtom;
_ATOM DecPopUDecimalAtom;
_ATOM DecPopVStringAtom;
_ATOM DecPopVStringXAtom;
_ATOM DecPushCStringAtom;
_ATOM DecPushDecimalAtom;
_ATOM DecPushInt64Atom;
_ATOM DecPushLongAtom;
_ATOM DecPushQStringAtom;
_ATOM DecPushRealAtom;
_ATOM DecPushStringAtom;
_ATOM DecPushUDecimalAtom;
_ATOM DecPushUInt64Atom;
_ATOM DecPushUnicodeAtom;
_ATOM DecPushUtf8Atom;
_ATOM DecRoundAtom;
_ATOM DecRoundUpAtom;
_ATOM DecRoundToAtom;
_ATOM DecSetPrecisionAtom;
_ATOM DecSubAtom;
_ATOM DecTruncateAtom;
_ATOM DecTruncateAtAtom;
_ATOM DecValidAtom;
_ATOM delayedAtom;
_ATOM deleteFileAtom;
_ATOM dependencyAtom;
_ATOM deserializerAtom;
_ATOM deserializeRawAtom;
_ATOM deserializeCStringXAtom;
_ATOM deserializeDataXAtom;
_ATOM deserializeDatasetXAtom;
_ATOM deserializeGroupedDatasetXAtom;
_ATOM deserializeQStrXAtom;
_ATOM deserializeRowAtom;
_ATOM deserializeRowsetXAtom;
_ATOM deserializeGroupedRowsetXAtom;
_ATOM deserializeSetAtom;
_ATOM deserializeStringXAtom;
_ATOM deserializeUnicodeXAtom;
_ATOM deserializeUtf8XAtom;
_ATOM deserializeVUnicodeXAtom;
_ATOM deserializerRowsetHelperAtom;
_ATOM deserializerReadNAtom;
_ATOM deserializerReadPackedIntAtom;
_ATOM deserializerReadSizeAtom;
_ATOM deserializerReadUtf8Atom;
_ATOM deserializerReadVStrAtom;
_ATOM deserializerReadVUniAtom;
_ATOM deserializerPeekAtom;
_ATOM deserializerBeginNestedAtom;
_ATOM deserializerFinishedNestedAtom;
_ATOM deserializerSkipNAtom;
_ATOM deserializerSkipPackedIntAtom;
_ATOM deserializerSkipUtf8Atom;
_ATOM deserializerSkipVStrAtom;
_ATOM deserializerSkipVUniAtom;
_ATOM destroyRegexAtom;
_ATOM destroyWRegexAtom;
_ATOM destructMetaMemberAtom;
_ATOM doNotifyAtom;
_ATOM doNotifyTargetAtom;
_ATOM ebcdic2asciiAtom;
_ATOM eclAtom;
_ATOM en2fAtom;
_ATOM en2l4Atom;
_ATOM en2l8Atom;
_ATOM en2ls4Atom;
_ATOM en2ls8Atom;
_ATOM endAtom;
_ATOM ensureCapacityAtom;
_ATOM ensureRowAvailableAtom;
_ATOM __eogAtom;
_ATOM estr2EStrAtom;
_ATOM estr2VStrAtom;
_ATOM estr2VStrXAtom;
_ATOM evaluateChildQueryInstanceAtom;
_ATOM ex2fAtom;
_ATOM executeGraphAtom;
_ATOM executeChildQueryInstanceAtom;
_ATOM extractAtom;
_ATOM f2anAtom;
_ATOM f2axAtom;
_ATOM f2vnAtom;
_ATOM f2vxAtom;
_ATOM _failIdAtom;
_ATOM fileAtom;
_ATOM fileExistsAtom;
_ATOM finalizeRowClearAtom;
_ATOM finishPersistAtom;
_ATOM forceAllCheckAtom;
_ATOM freeAtom;
_ATOM freeExceptionAtom;
_ATOM getBytesFromBuilderAtom;
_ATOM getChildQueryLinkedResultAtom;
_ATOM getChildQueryResultAtom;
_ATOM getClusterSizeAtom;
_ATOM getDatasetHashAtom;
_ATOM getECLAtom;
_ATOM getEnvAtom;
_ATOM getEventExtraAtom;
_ATOM getEventNameAtom;
_ATOM getExpandLogicalNameAtom;
_ATOM getFailMessageAtom;
_ATOM getFilePositionAtom;
_ATOM getGraphLoopCounterAtom;
_ATOM getIsValidAtom;
_ATOM getLocalFailMessageAtom;
_ATOM getLocalFilePositionAtom;
_ATOM getLocalLinkedResultAtom;
_ATOM getLocalResultAtom;
_ATOM getMatchedAtom;
_ATOM getMatchLengthAtom;
_ATOM getMatchPositionAtom;
_ATOM getMatchRowAtom;
_ATOM getMatchTextAtom;
_ATOM getMatchUnicodeAtom;
_ATOM getMatchUtf8Atom;
_ATOM getPackedSignedAtom;
_ATOM getPackedSizeAtom;
_ATOM getPackedUnsignedAtom;
_ATOM getProductionResultAtom;
_ATOM getProductionTextAtom;
_ATOM getProductionUnicodeAtom;
_ATOM getProductionUtf8Atom;
_ATOM getRecoveringCountAtom;
_ATOM getResultBoolAtom;
_ATOM getResultDataAtom;
_ATOM getResultDatasetAtom;
_ATOM getResultDecimalAtom;
_ATOM getResultHashAtom;
_ATOM getResultIntAtom;
_ATOM getResultQStringAtom;
_ATOM getResultRealAtom;
_ATOM getResultRowsetAtom;
_ATOM getResultSetAtom;
_ATOM getResultStringAtom;
_ATOM getResultStringFAtom;
_ATOM getResultUnicodeAtom;
_ATOM getResultVarStringAtom;
_ATOM getResultVarUnicodeAtom;
_ATOM getRootResultAtom;
_ATOM getWorkflowIdAtom;
_ATOM getWuidAtom;
_ATOM goAtom;
_ATOM groupedDataset2RowsetXAtom;
_ATOM guardAtom;
_ATOM hash32DataAtom;
_ATOM hash32Data1Atom;
_ATOM hash32Data2Atom;
_ATOM hash32Data3Atom;
_ATOM hash32Data4Atom;
_ATOM hash32Data5Atom;
_ATOM hash32Data6Atom;
_ATOM hash32Data7Atom;
_ATOM hash32Data8Atom;
_ATOM hash32UnicodeAtom;
_ATOM hash32Utf8Atom;
_ATOM hash32VStrAtom;
_ATOM hash32VUnicodeAtom;
_ATOM hash64DataAtom;
_ATOM hash64UnicodeAtom;
_ATOM hash64Utf8Atom;
_ATOM hash64VStrAtom;
_ATOM hash64VUnicodeAtom;
_ATOM hashDataAtom;
_ATOM hashDataNCAtom;
_ATOM hashMd5FinishAtom;
_ATOM hashMd5InitAtom;
_ATOM hashMd5DataAtom;
_ATOM hashUnicodeAtom;
_ATOM hashUtf8Atom;
_ATOM hashVStrAtom;
_ATOM hashVStrNCAtom;
_ATOM hashVUnicodeAtom;
_ATOM helperAtom;
_ATOM IIndirectMemberVisitor_visitRowAtom;
_ATOM IIndirectMemberVisitor_visitRowsetAtom;
_ATOM implicitAtom;
_ATOM inAtom;
_ATOM indexLayoutMarkerAtom;
_ATOM initAtom;
_ATOM initProcessAtom;
_ATOM insideOnCreateAtom;
_ATOM insideOnStartAtom;
_ATOM instanceAtom;
_ATOM intFormatAtom;
_ATOM isLastBitfieldAtom;
_ATOM isResultAtom;
_ATOM iteratorAtom;
_ATOM keyUnicodeXAtom;
_ATOM keyUnicodeStrengthXAtom;
_ATOM killRangeAtom;
_ATOM l42anAtom;
_ATOM l42axAtom;
_ATOM l42vnAtom;
_ATOM l42vxAtom;
_ATOM l82anAtom;
_ATOM l82axAtom;
_ATOM l82vnAtom;
_ATOM l82vxAtom;
_ATOM linkdataset2linkdatasetAtom;
_ATOM linkRowAtom;
_ATOM linkRowsetAtom;
_ATOM lnAtom;
_ATOM loadResourceAtom;
_ATOM log10Atom;
_ATOM lookupBlobAtom;
_ATOM _loop_Atom;
_ATOM ls42anAtom;
_ATOM ls42axAtom;
_ATOM ls42vnAtom;
_ATOM ls42vxAtom;
_ATOM ls82anAtom;
_ATOM ls82axAtom;
_ATOM ls82vnAtom;
_ATOM ls82vxAtom;
_ATOM mainprototypesAtom;
_ATOM memcmpAtom;
_ATOM memcpyAtom;
_ATOM memsetAtom;
_ATOM multiInstanceAtom;
_ATOM newWhenActionArgAtom;
_ATOM newDegroupArgAtom;
_ATOM newFunnelArgAtom;
_ATOM newGraphLoopResultWriteArgAtom;
_ATOM newLocalResultSpillArgAtom;
_ATOM newMemorySpillReadArgAtom;
_ATOM newMemorySpillSplitArgAtom;
_ATOM newNullArgAtom;
_ATOM newSplitArgAtom;
_ATOM newWorkUnitReadArgAtom;
_ATOM newWorkUnitWriteArgAtom;
_ATOM _noAccess_Atom;
_ATOM _noReplicate_Atom;
_ATOM _normalized_Atom;
_ATOM noSetAtom;
_ATOM _noVirtual_Atom;
_ATOM numResultsAtom;
_ATOM offsetProviderAtom;
_ATOM outputXmlBeginNestedAtom;
_ATOM outputXmlBoolAtom;
_ATOM outputXmlDataAtom;
_ATOM outputXmlDecimalAtom;
_ATOM outputXmlEndNestedAtom;
_ATOM outputXmlIntAtom;
_ATOM outputXmlQStringAtom;
_ATOM outputXmlRealAtom;
_ATOM outputXmlSetAllAtom;
_ATOM outputXmlStringAtom;
_ATOM outputXmlUIntAtom;
_ATOM outputXmlUnicodeAtom;
_ATOM outputXmlUtf8Atom;
_ATOM packingAtom;
_ATOM parentHelpersAtom;
_ATOM pathAtom;
_ATOM _physical_Atom;
_ATOM powerAtom;
_ATOM prefetcherInstanceMarkerAtom;
_ATOM prefixDiffStrAtom;
_ATOM prefixDiffUnicodeAtom;
_ATOM processFieldBoolAtom;
_ATOM processFieldDataAtom;
_ATOM processFieldDecimalAtom;
_ATOM processFieldIntAtom;
_ATOM processFieldQStringAtom;
_ATOM processFieldRealAtom;
_ATOM processFieldStringAtom;
_ATOM processFieldUIntAtom;
_ATOM processFieldUnicodeAtom;
_ATOM processFieldUtf8Atom;
_ATOM processFieldSetAllAtom;
_ATOM processFieldBeginSetAtom;
_ATOM processFieldBeginDatasetAtom;
_ATOM processFieldBeginRowAtom;
_ATOM processFieldEndSetAtom;
_ATOM processFieldEndDatasetAtom;
_ATOM processFieldEndRowAtom;
_ATOM prototypeAtom;
_ATOM qstr2BoolAtom;
_ATOM qstr2DataAtom;
_ATOM qstr2DataXAtom;
_ATOM qstrToQStrAtom;
_ATOM qstrToQStrXAtom;
_ATOM qstr2StrAtom;
_ATOM qstr2StrXAtom;
_ATOM qstr2VStrAtom;
_ATOM qstrLengthAtom;
_ATOM qstrSizeAtom;
_ATOM queryFailCodeAtom;
_ATOM queryLocalFailCodeAtom;
_ATOM queryLocalResultAtom;
_ATOM queryLogicalFilenameAtom;
_ATOM quickAtom;
_ATOM rankedFromOrderAtom;
_ATOM rankFromOrderAtom;
_ATOM readIntAtom[9][2];
_ATOM readSwapIntAtom[9][2];
_ATOM realFormatAtom;
_ATOM _regexFindInstance_Atom;
_ATOM regexFindXAtom;
_ATOM regexGetFindStrAtom;
_ATOM _regexInstance_Atom;
_ATOM regexNewSetStrPatternAtom;
_ATOM regexNewSetUStrPatternAtom;
_ATOM regexNewStrFindAtom;
_ATOM regexNewStrFoundAtom;
_ATOM regexNewStrFoundXAtom;
_ATOM regexNewStrReplaceXAtom;
_ATOM regexNewUStrFindAtom;
_ATOM regexNewUStrFoundAtom;
_ATOM regexNewUStrFoundXAtom;
_ATOM regexNewUStrReplaceXAtom;
_ATOM regexReplaceXAtom;
_ATOM releaseRowAtom;
_ATOM releaseRowsetAtom;
_ATOM reportFieldOverflowAtom;
_ATOM reportRowOverflowAtom;
_ATOM responseinfoAtom;
_ATOM restoreClusterAtom;
_ATOM returnAtom;
_ATOM returnPersistVersionAtom;
_ATOM reverseIntAtom[9][2];
_ATOM roundAtom;
_ATOM roundToAtom;
_ATOM roundupAtom;
_ATOM rowAllocatorMarkerAtom;
_ATOM rowset2DatasetXAtom;
_ATOM rtlDeserializeRowAtom;
_ATOM rtlDeserializeToBuilderAtom;
_ATOM rtlFieldKeyMarkerAtom;
_ATOM rtlMaxAtom;
_ATOM rtlMinAtom;
_ATOM rtlRandomAtom;
_ATOM rtlSerializeRowAtom;
_ATOM rtlSerializeToBuilderAtom;
_ATOM searchTableInteger4Atom;
_ATOM searchTableInteger8Atom;
_ATOM searchTableUInteger4Atom;
_ATOM searchTableUInteger8Atom;
_ATOM searchUnicodeTableAtom;
_ATOM searchUtf8TableAtom;
_ATOM searchVUnicodeTableAtom;
_ATOM selectClusterAtom;
_ATOM _selfJoinPlaceholder_Atom;
_ATOM serializerAtom;
_ATOM serializeCStringXAtom;
_ATOM serializeDataXAtom;
_ATOM serializeDatasetXAtom;
_ATOM serializeGroupedDatasetXAtom;
_ATOM serializeStringXAtom;
_ATOM serializeBoolAtom;
_ATOM serializeFixedDataAtom;
_ATOM serializeFixedStringAtom;
_ATOM serializeLPDataAtom;
_ATOM serializeLPQStringAtom;
_ATOM serializeLPStringAtom;
_ATOM serializeQStrXAtom;
_ATOM serializeRawAtom;
_ATOM serializeReal4Atom;
_ATOM serializeReal8Atom;
_ATOM serializeRowAtom;
_ATOM serializeRowsetXAtom;
_ATOM serializeGroupedRowsetXAtom;
_ATOM serializeSetAtom;
_ATOM serializeUnicodeXAtom;
_ATOM serializeUtf8XAtom;
_ATOM serializerPutAtom;
_ATOM serializerRowsetHelperAtom;
_ATOM serializerBeginNestedAtom;
_ATOM serializerEndNestedAtom;
_ATOM serializerInstanceMarkerAtom;
_ATOM setConditionCodeAtom;
_ATOM setMethodAtom;
_ATOM setOwnMethodAtom;
_ATOM setPackedSignedAtom;
_ATOM setPackedUnsignedAtom;
_ATOM setResultBoolAtom;
_ATOM setResultDataAtom;
_ATOM setResultDatasetAtom;
_ATOM setResultDecimalAtom;
_ATOM setResultIntAtom;
_ATOM setResultQStringAtom;
_ATOM setResultRawAtom;
_ATOM setResultRealAtom;
_ATOM setResultSetAtom;
_ATOM setResultStringAtom;
_ATOM setResultUIntAtom;
_ATOM setResultUnicodeAtom;
_ATOM setResultVarStringAtom;
_ATOM setResultVarUnicodeAtom;
_ATOM setWorkflowConditionAtom;
_ATOM set2SetXAtom;
_ATOM sinAtom;
_ATOM sinhAtom;
_ATOM skipActionMarkerAtom;
_ATOM skipReturnMarkerAtom;
_ATOM speedAtom;
_ATOM spillAtom;
_ATOM _spill_Atom;
_ATOM _spillReason_Atom;
_ATOM sqrtAtom;
_ATOM startPersistAtom;
_ATOM _steppedMeta_Atom;
_ATOM str2DataAtom;
_ATOM str2DataXAtom;
_ATOM strToQStrAtom;
_ATOM strToQStrXAtom;
_ATOM str2StrAtom;
_ATOM str2StrXAtom;
_ATOM str2VStrAtom;
_ATOM str2VStrXAtom;
_ATOM strcpyAtom;
_ATOM strlenAtom;
_ATOM subDataFTAtom;
_ATOM subDataFTXAtom;
_ATOM subDataFXAtom;
_ATOM subgraphAtom;
_ATOM subQStrFTAtom;
_ATOM subQStrFTXAtom;
_ATOM subQStrFXAtom;
_ATOM subStrFTAtom;
_ATOM subStrFTXAtom;
_ATOM subStrFXAtom;
_ATOM sysFailAtom;
_ATOM tanAtom;
_ATOM tanhAtom;
_ATOM _tempCount_Atom;
_ATOM _translated_Atom;
_ATOM trimAllAtom;
_ATOM trimBothAtom;
_ATOM trimLeftAtom;
_ATOM trimRightAtom;
_ATOM trimStrLenAtom;
_ATOM trimUnicodeAllAtom;
_ATOM trimUnicodeBothAtom;
_ATOM trimUnicodeLeftAtom;
_ATOM trimUnicodeRightAtom;
_ATOM trimUnicodeStrLenAtom;
_ATOM trimUtf8AllAtom;
_ATOM trimUtf8BothAtom;
_ATOM trimUtf8LeftAtom;
_ATOM trimUtf8RightAtom;
_ATOM trimUtf8StrLenAtom;
_ATOM trimVAllAtom;
_ATOM trimVBothAtom;
_ATOM trimVLeftAtom;
_ATOM trimVRightAtom;
_ATOM trimVStrLenAtom;
_ATOM trimVUnicodeAllAtom;
_ATOM trimVUnicodeBothAtom;
_ATOM trimVUnicodeLeftAtom;
_ATOM trimVUnicodeRightAtom;
_ATOM trimVUnicodeStrLenAtom;
_ATOM truncateAtom;
_ATOM UCharAtom;
_ATOM unicode2CodepageAtom;
_ATOM unicode2CodepageXAtom;
_ATOM unicode2DataAtom;
_ATOM unicode2DataXAtom;
_ATOM unicode2UnicodeAtom;
_ATOM unicode2UnicodeXAtom;
_ATOM unicodeToUtf8Atom;
_ATOM unicodeToUtf8XAtom;
_ATOM unicode2VCodepageAtom;
_ATOM unicode2VCodepageXAtom;
_ATOM unicode2VUnicodeAtom;
_ATOM unicode2VUnicodeXAtom;
_ATOM unicodeNullTerminateAtom;
_ATOM unicodeStrcpyAtom;
_ATOM unicodeStrlenAtom;
_ATOM unicodeSubStrFXAtom;
_ATOM unicodeSubStrFTXAtom;
_ATOM updatePersistAtom;
_ATOM utf8Atom;
_ATOM utf82CodepageAtom;
_ATOM utf82CodepageXAtom;
_ATOM utf82DataAtom;
_ATOM utf82DataXAtom;
_ATOM utf82UnicodeAtom;
_ATOM utf82UnicodeXAtom;
_ATOM utf8ToUtf8Atom;
_ATOM utf8ToUtf8XAtom;
_ATOM utf8LengthAtom;
_ATOM utf8SizeAtom;
_ATOM utf8SubStrFTXAtom;
_ATOM utf8SubStrFXAtom;
_ATOM validRealAtom;
_ATOM vcodepage2UnicodeAtom;
_ATOM vcodepage2UnicodeXAtom;
_ATOM vcodepage2VUnicodeAtom;
_ATOM vcodepage2VUnicodeXAtom;
_ATOM vn2bAtom;
_ATOM vn2fAtom;
_ATOM vn2l4Atom;
_ATOM vn2l8Atom;
_ATOM vn2ls4Atom;
_ATOM vn2ls8Atom;
_ATOM vstr2DataAtom;
_ATOM vstr2StrAtom;
_ATOM vstr2VStrAtom;
_ATOM vunicode2CodepageAtom;
_ATOM vunicode2CodepageXAtom;
_ATOM vunicode2DataAtom;
_ATOM vunicode2DataXAtom;
_ATOM vunicode2UnicodeAtom;
_ATOM vunicode2UnicodeXAtom;
_ATOM vunicode2VCodepageAtom;
_ATOM vunicode2VCodepageXAtom;
_ATOM vunicode2VUnicodeAtom;
_ATOM vunicode2VUnicodeXAtom;
_ATOM walkIndirectMetaMemberAtom;
_ATOM wrapperAtom;
_ATOM wregexFindXAtom;
_ATOM wregexGetFindStrAtom;
_ATOM wregexReplaceXAtom;
_ATOM writeEbcdicAtom;
_ATOM writeIntAtom[9];
_ATOM writeRealAtom;
_ATOM writeSignedAtom;
_ATOM writeStringAtom;
_ATOM writeUnicodeAtom;
_ATOM writeUnsignedAtom;
_ATOM writeUtf8Atom;
_ATOM xmlColumnProviderAtom;
_ATOM xmlDecodeStrAtom;
_ATOM xmlDecodeUStrAtom;
_ATOM xmlEncodeStrAtom;
_ATOM xmlEncodeUStrAtom;
_ATOM xmlReadMarkerAtom;

//===========================================================================

//MORE: Need to change many MAKEATOM to MAKEID in this file, and most of the explicit calls should be removed/changed

#define MAKEATOM(x) x##Atom = createLowerCaseAtom(#x)
#define MAKESYSATOM(x)  _##x##_Atom = createSystemAtom("$_" #x "_")
#define MAKEID(x)   x##IdAtom = createIdentifierAtom(#x)

MODULE_INIT(INIT_PRIORITY_HQLATOM)
{
    MAKEATOM(activeActivityMarker);
    MAKEATOM(activeMatchText);
    MAKEATOM(activeMatchUnicode);
    MAKEATOM(activeMatchUtf8);
    MAKEATOM(activeProductionMarker);
    MAKEATOM(activeValidateMarker);
    MAKEATOM(activityIdMarker);
    acosAtom = createAtom("_acos");
    MAKEATOM(addAggregateRow);
    MAKEATOM(addAll);
    MAKEATOM(addRange);
    MAKEATOM(addWorkunitAssertFailure);
    MAKEATOM(addWorkunitException);
    MAKEATOM(an2b);
    MAKEATOM(an2f);
    MAKEATOM(an2l4);
    MAKEATOM(an2l8);
    MAKEATOM(an2ls4);
    MAKEATOM(an2ls8);
    MAKEATOM(appendRowsToRowset);
    MAKEATOM(appendSetX);
    MAKEATOM(ascii2ebcdic);
    asinAtom = createAtom("_asin");
    atan2Atom = createAtom("_atan2");
    atanAtom = createAtom("_atan");
    MAKEATOM(balanced);
    MAKEATOM(bitfieldOffset);
    MAKEATOM(blobHelper);
    MAKEATOM(bool2Data);
    MAKEATOM(bool2Str);
    MAKEATOM(bool2StrX);
    MAKEATOM(bool2VStr);
    MAKEATOM(bool2VStrX);
    MAKEATOM(branch);
    _clear(castIntAtom);
    castIntAtom[3][true] = createAtom("castInt3");
    castIntAtom[5][true] = createAtom("castInt5");
    castIntAtom[6][true] = createAtom("castInt6");
    castIntAtom[7][true] = createAtom("castInt7");
    castIntAtom[3][false] = createAtom("castUInt3");
    castIntAtom[5][false] = createAtom("castUInt5");
    castIntAtom[6][false] = createAtom("castUInt6");
    castIntAtom[7][false] = createAtom("castUInt7");
    MAKEATOM(checkFieldOverflow);
    MAKEATOM(checkPersistMatches);
    MAKEATOM(checkpoint);
    MAKEATOM(checkRowOverflow);
    MAKEATOM(child);
    MAKEATOM(class);
    MAKEATOM(clear);
    MAKEATOM(__clearHelper);
    MAKEATOM(clearPersist);
    MAKEID(clibExp);
    MAKEATOM(codeGenerator);
    MAKEATOM(codepage2Unicode);
    MAKEATOM(codepage2UnicodeX);
    MAKEATOM(codepageToUtf8);
    MAKEATOM(codepageToUtf8X);
    MAKEATOM(codepage2VUnicode);
    MAKEATOM(codepage2VUnicodeX);
    MAKEATOM(columnGetBool);
    MAKEATOM(columnGetData);
    MAKEATOM(columnGetDataX);
    MAKEATOM(columnGetInt);
    MAKEATOM(columnGetQString);
    MAKEATOM(columnGetSetIsAll);
    MAKEATOM(columnGetString);
    MAKEATOM(columnGetStringX);
    MAKEATOM(columnGetUnicodeX);
    MAKEATOM(columnGetUtf8X);
    MAKEATOM(columnReadBool);
    MAKEATOM(columnReadData);
    MAKEATOM(columnReadDataX);
    MAKEATOM(columnReadInt);
    MAKEATOM(columnReadQString);
    MAKEATOM(columnReadSetIsAll);
    MAKEATOM(columnReadString);
    MAKEATOM(columnReadStringX);
    MAKEATOM(columnReadUnicodeX);
    MAKEATOM(columnReadUtf8X);
    MAKEATOM(compareDataData);
    MAKEATOM(compareEStrEStr);
    MAKEATOM(compareQStrQStr);
    MAKEATOM(compareStrBlank);
    MAKEATOM(compareStrStr);
    MAKEATOM(compareUnicodeUnicode);
    MAKEATOM(compareUnicodeUnicodeStrength);
    MAKEATOM(compareUtf8Utf8);
    MAKEATOM(compareUtf8Utf8Strength);
    MAKEATOM(compareVStrVStr);
    MAKEATOM(compareVUnicodeVUnicode);
    MAKEATOM(compareVUnicodeVUnicodeStrength);
    MAKEATOM(concat);
    MAKEATOM(concatExtend);
    MAKEATOM(concatStr2Str);
    MAKEATOM(concatStrF);
    MAKEATOM(concatUnicode);
    MAKEATOM(concatUnicodeF);
    MAKEATOM(concatUnicodeToUnicode);
    MAKEATOM(concatUtf8);
    MAKEATOM(concatUtf8ToUtf8);
    MAKEATOM(concatVStr2Str);
    MAKEATOM(concatVStr);
    MAKEATOM(concatVStrF);
    MAKEATOM(concatVUnicode);
    MAKEATOM(concatVUnicodeF);
    MAKEATOM(concatVUnicodeToUnicode);
    MAKESYSATOM(conditionalRowMarker);
    MAKEATOM(container);
    cosAtom = createAtom("_cos");
    coshAtom = createAtom("_cosh");
    MAKEATOM(countIndex);
    MAKEATOM(countProvider);
    MAKEATOM(countRoxieDiskFile);
    MAKEATOM(countRows);
    MAKEATOM(countToSize);
    MAKEATOM(crcData);
    MAKEATOM(crcUnicode);
    MAKEATOM(crcUtf8);
    MAKEATOM(crcVStr);
    MAKEATOM(crcVUnicode);
    MAKEATOM(createBlob);
    MAKEATOM(createDataRangeLow);
    MAKEATOM(createDataRangeHigh);
    MAKEATOM(createOrder);
    MAKEATOM(createQStrRangeLow);
    MAKEATOM(createQStrRangeHigh);
    MAKEATOM(createQuotedString);
    MAKEATOM(createRangeLow);
    MAKEATOM(createRangeHigh);
    MAKEATOM(createRegex);
    MAKEATOM(createRowFromXml);
    MAKEATOM(createStrRangeLow);
    MAKEATOM(createStrRangeHigh);
    MAKEATOM(createUnicodeRangeLow);
    MAKEATOM(createUnicodeRangeHigh);
    MAKEATOM(createWRegex);
    MAKEATOM(creator);
    MAKEATOM(csvReadMarker);
    MAKEATOM(csvStr2Bool);
    MAKEATOM(ctxGetRowXml);
    MAKEATOM(current);
    MAKEATOM(data2Bool);
    MAKEATOM(dataset2DatasetX);
    MAKEATOM(dataset2RowsetX);
    MAKEATOM(DecAbs);
    MAKEATOM(DecAdd);
    MAKEATOM(DecCompareDecimal);
    MAKEATOM(DecCompareUDecimal);
    MAKEATOM(DecCompareNull);
    MAKEATOM(DecDistinct);
    MAKEATOM(DecDistinctR);
    MAKEATOM(DecDivide);
    MAKEATOM(decimal);
    MAKEATOM(declare);
    MAKEATOM(DecModulus);
    MAKEATOM(DecMul);
    MAKEATOM(DecNegate);
    MAKEATOM(DecPopDecimal);
    MAKEATOM(DecPopInt64);
    MAKEATOM(DecPopLong);
    MAKEATOM(DecPopReal);
    MAKEATOM(DecPopString);
    MAKEATOM(DecPopStringX);
    MAKEATOM(DecPopUDecimal);
    MAKEATOM(DecPopVString);
    MAKEATOM(DecPopVStringX);
    MAKEATOM(DecPushCString);
    MAKEATOM(DecPushDecimal);
    MAKEATOM(DecPushInt64);
    MAKEATOM(DecPushLong);
    MAKEATOM(DecPushReal);
    MAKEATOM(DecPushQString);
    MAKEATOM(DecPushString);
    MAKEATOM(DecPushUDecimal);
    MAKEATOM(DecPushUInt64);
    MAKEATOM(DecPushUnicode);
    MAKEATOM(DecPushUtf8);
    MAKEATOM(DecRound);
    MAKEATOM(DecRoundUp);
    MAKEATOM(DecRoundTo);
    MAKEATOM(DecSetPrecision);
    MAKEATOM(DecSub);
    MAKEATOM(DecTruncate);
    MAKEATOM(DecTruncateAt);
    MAKEATOM(DecValid);
    MAKEATOM(delayed);
    MAKEATOM(deleteFile);
    MAKEATOM(dependency);
    MAKEATOM(deserializer);
    MAKEATOM(deserializeRaw);
    MAKEATOM(deserializeCStringX);
    MAKEATOM(deserializeDataX);
    MAKEATOM(deserializeDatasetX);
    MAKEATOM(deserializeGroupedDatasetX);
    MAKEATOM(deserializeQStrX);
    MAKEATOM(deserializeRow);
    MAKEATOM(deserializeRowsetX);
    MAKEATOM(deserializeGroupedRowsetX);
    MAKEATOM(deserializeSet);
    MAKEATOM(deserializeStringX);
    MAKEATOM(deserializeUnicodeX);
    MAKEATOM(deserializeUtf8X);
    MAKEATOM(deserializeVUnicodeX);
    MAKEATOM(deserializerRowsetHelper);
    MAKEATOM(deserializerReadN);
    MAKEATOM(deserializerReadPackedInt);
    MAKEATOM(deserializerReadSize);
    MAKEATOM(deserializerReadUtf8);
    MAKEATOM(deserializerReadVStr);
    MAKEATOM(deserializerReadVUni);
    MAKEATOM(deserializerPeek);
    MAKEATOM(deserializerBeginNested);
    MAKEATOM(deserializerFinishedNested);
    MAKEATOM(deserializerSkipN);
    MAKEATOM(deserializerSkipPackedInt);
    MAKEATOM(deserializerSkipUtf8);
    MAKEATOM(deserializerSkipVStr);
    MAKEATOM(deserializerSkipVUni);
    MAKEATOM(destroyRegex);
    MAKEATOM(destroyWRegex);
    MAKEATOM(destructMetaMember);
    MAKEATOM(doNotify);
    MAKEATOM(doNotifyTarget);
    MAKEATOM(ebcdic2ascii);
    MAKEATOM(ecl);
    MAKEATOM(en2f);
    MAKEATOM(en2l4);
    MAKEATOM(en2l8);
    MAKEATOM(en2ls4);
    MAKEATOM(en2ls8);
    MAKEATOM(end);
    MAKEATOM(ensureCapacity);
    MAKEATOM(ensureRowAvailable);
    MAKEATOM(__eog);
    estr2EStrAtom = createAtom("eStr2EStr");
    estr2VStrAtom = createAtom("eStr2VStr");
    estr2VStrXAtom = createAtom("EStr2VStrX");
    MAKEATOM(evaluateChildQueryInstance);
    MAKEATOM(ex2f);
    MAKEATOM(executeGraph);
    MAKEATOM(executeChildQueryInstance);
    MAKEATOM(extract);
    MAKEATOM(f2an);
    f2axAtom = createAtom("_f2ax");
    MAKEATOM(f2vn);
    MAKEATOM(f2vx);
    MAKEID(_fail);
    MAKEATOM(file);
    MAKEATOM(fileExists);
    MAKEATOM(finalizeRowClear);
    MAKEATOM(finishPersist);
    MAKEATOM(forceAllCheck);
    MAKEATOM(free);
    MAKEATOM(freeException);
    MAKEATOM(getBytesFromBuilder);
    MAKEATOM(getChildQueryLinkedResult);
    MAKEATOM(getChildQueryResult);
    MAKEATOM(getClusterSize);
    MAKEATOM(getDatasetHash);
    MAKEATOM(getECL);
    MAKEATOM(getEnv);
    MAKEATOM(getEventExtra);
    MAKEATOM(getEventName);
    MAKEATOM(getExpandLogicalName);
    MAKEATOM(getFailMessage);
    MAKEATOM(getFilePosition);
    MAKEATOM(getGraphLoopCounter);
    MAKEATOM(getIsValid);
    MAKEATOM(getLocalFailMessage);
    MAKEATOM(getLocalFilePosition);
    MAKEATOM(getLocalLinkedResult);
    MAKEATOM(getLocalResult);
    MAKEATOM(getMatched);
    MAKEATOM(getMatchLength);
    MAKEATOM(getMatchPosition);
    MAKEATOM(getMatchRow);
    MAKEATOM(getMatchText);
    MAKEATOM(getMatchUnicode);
    MAKEATOM(getMatchUtf8);
    MAKEATOM(getPackedSigned);
    MAKEATOM(getPackedSize);
    MAKEATOM(getPackedUnsigned);
    MAKEATOM(getProductionResult);
    MAKEATOM(getProductionText);
    MAKEATOM(getProductionUnicode);
    MAKEATOM(getProductionUtf8);
    MAKEATOM(getRecoveringCount);
    MAKEATOM(getResultBool);
    MAKEATOM(getResultData);
    MAKEATOM(getResultDataset);
    MAKEATOM(getResultDecimal);
    MAKEATOM(getResultHash);
    MAKEATOM(getResultInt);
    MAKEATOM(getResultQString);
    MAKEATOM(getResultReal);
    MAKEATOM(getResultRowset);
    MAKEATOM(getResultSet);
    MAKEATOM(getResultString);
    MAKEATOM(getResultStringF);
    MAKEATOM(getResultUnicode);
    MAKEATOM(getResultVarString);
    MAKEATOM(getResultVarUnicode);
    MAKEATOM(getRootResult);
    MAKEATOM(getWorkflowId);
    MAKEATOM(getWuid);
    MAKEATOM(groupedDataset2RowsetX);
    MAKEATOM(go);
    MAKEATOM(guard);
    MAKEATOM(hash32Data);
    MAKEATOM(hash32Data1);
    MAKEATOM(hash32Data2);
    MAKEATOM(hash32Data3);
    MAKEATOM(hash32Data4);
    MAKEATOM(hash32Data5);
    MAKEATOM(hash32Data6);
    MAKEATOM(hash32Data7);
    MAKEATOM(hash32Data8);
    MAKEATOM(hash32VStr);
    MAKEATOM(hash32Unicode);
    MAKEATOM(hash32Utf8);
    MAKEATOM(hash32VUnicode);
    MAKEATOM(hash64Data);
    MAKEATOM(hash64VStr);
    MAKEATOM(hash64Unicode);
    MAKEATOM(hash64Utf8);
    MAKEATOM(hash64VUnicode);
    MAKEATOM(hashData);
    MAKEATOM(hashDataNC);
    MAKEATOM(hashMd5Finish);
    MAKEATOM(hashMd5Init);
    MAKEATOM(hashMd5Data);
    MAKEATOM(hashVStr);
    MAKEATOM(hashVStrNC);
    MAKEATOM(hashUnicode);
    MAKEATOM(hashUtf8);
    MAKEATOM(hashVUnicode);
    MAKEATOM(helper);
    MAKEATOM(IIndirectMemberVisitor_visitRow);
    MAKEATOM(IIndirectMemberVisitor_visitRowset);
    MAKEATOM(implicit);
    MAKEATOM(in);
    MAKEATOM(indexLayoutMarker);
    MAKEATOM(init);
    MAKEATOM(insideOnCreate);
    MAKEATOM(insideOnStart);
    MAKEATOM(instance);
    intFormatAtom = createAtom("_intformat");
    MAKEATOM(isLastBitfield);
    MAKEATOM(isResult);
    MAKEATOM(iterator);
    MAKEATOM(keyUnicodeX);
    MAKEATOM(keyUnicodeStrengthX);
    MAKEATOM(killRange);
    MAKEATOM(l42an);
    MAKEATOM(l42ax);
    MAKEATOM(l42vn);
    MAKEATOM(l42vx);
    MAKEATOM(l82an);
    MAKEATOM(l82ax);
    MAKEATOM(l82vn);
    MAKEATOM(l82vx);
    MAKEATOM(linkdataset2linkdataset);
    MAKEATOM(linkRow);
    MAKEATOM(linkRowset);
    lnAtom = createAtom("_ln");
    MAKEATOM(loadResource);
    MAKEATOM(lookupBlob);
    MAKESYSATOM(loop);
    log10Atom = createAtom("_log10");
    MAKEATOM(ls42an);
    MAKEATOM(ls42ax);
    MAKEATOM(ls42vn);
    MAKEATOM(ls42vx);
    MAKEATOM(ls82an);
    MAKEATOM(ls82ax);
    MAKEATOM(ls82vn);
    MAKEATOM(ls82vx);
    MAKEATOM(mainprototypes);
    MAKEATOM(memcmp);
    MAKEATOM(memcpy);
    MAKEATOM(memset);
    MAKEATOM(multiInstance);
    MAKEATOM(newWhenActionArg);
    MAKEATOM(newDegroupArg);
    MAKEATOM(newFunnelArg);
    MAKEATOM(newGraphLoopResultWriteArg);
    MAKEATOM(newLocalResultSpillArg);
    MAKEATOM(newMemorySpillReadArg);
    MAKEATOM(newMemorySpillSplitArg);
    MAKEATOM(newNullArg);
    MAKEATOM(newSplitArg);
    MAKEATOM(newWorkUnitReadArg);
    MAKEATOM(newWorkUnitWriteArg);
    MAKESYSATOM(noAccess);
    MAKESYSATOM(noReplicate);
    MAKESYSATOM(normalized);
    MAKEATOM(noSet);
    MAKESYSATOM(noVirtual);
    MAKEATOM(numResults);
    MAKEATOM(offsetProvider);
    MAKEATOM(outputXmlBeginNested);
    MAKEATOM(outputXmlBool);
    MAKEATOM(outputXmlData);
    MAKEATOM(outputXmlDecimal);
    MAKEATOM(outputXmlEndNested);
    MAKEATOM(outputXmlInt);
    MAKEATOM(outputXmlQString);
    MAKEATOM(outputXmlReal);
    MAKEATOM(outputXmlSetAll);
    MAKEATOM(outputXmlString);
    MAKEATOM(outputXmlUInt);
    MAKEATOM(outputXmlUnicode);
    MAKEATOM(outputXmlUtf8);
    MAKEATOM(packing);
    MAKEATOM(parentHelpers);
    MAKEATOM(path);
    MAKESYSATOM(physical);
    powerAtom = createAtom("_power");
    MAKEATOM(prefetcherInstanceMarker);
    MAKEATOM(prefixDiffStr);
    MAKEATOM(prefixDiffUnicode);
    MAKEATOM(processFieldBool);
    MAKEATOM(processFieldData);
    MAKEATOM(processFieldDecimal);
    MAKEATOM(processFieldInt);
    MAKEATOM(processFieldQString);
    MAKEATOM(processFieldReal);
    MAKEATOM(processFieldString);
    MAKEATOM(processFieldUInt);
    MAKEATOM(processFieldUnicode);
    MAKEATOM(processFieldUtf8);
    MAKEATOM(processFieldSetAll);
    MAKEATOM(processFieldBeginSet);
    MAKEATOM(processFieldBeginDataset);
    MAKEATOM(processFieldBeginRow);
    MAKEATOM(processFieldEndSet);
    MAKEATOM(processFieldEndDataset);
    MAKEATOM(processFieldEndRow);
    MAKEATOM(prototype);
    MAKEATOM(qstr2Bool);
    MAKEATOM(qstr2Data);
    MAKEATOM(qstr2DataX);
    MAKEATOM(qstrToQStr);
    MAKEATOM(qstrToQStrX);
    MAKEATOM(qstr2Str);
    MAKEATOM(qstr2StrX);
    MAKEATOM(qstr2VStr);
    MAKEATOM(qstrLength);
    MAKEATOM(qstrSize);
    MAKEATOM(queryFailCode);
    MAKEATOM(queryLocalFailCode);
    MAKEATOM(queryLocalResult);
    MAKEATOM(queryLogicalFilename);
    MAKEATOM(quick);
    MAKEATOM(rankedFromOrder);
    MAKEATOM(rankFromOrder);
    readIntAtom[3][true] = createAtom("readInt3");
    readIntAtom[5][true] = createAtom("readInt5");
    readIntAtom[6][true] = createAtom("readInt6");
    readIntAtom[7][true] = createAtom("readInt7");
    readIntAtom[3][false] = createAtom("readUInt3");
    readIntAtom[5][false] = createAtom("readUInt5");
    readIntAtom[6][false] = createAtom("readUInt6");
    readIntAtom[7][false] = createAtom("readUInt7");
    readSwapIntAtom[3][true] = createAtom("readSwapInt3");
    readSwapIntAtom[5][true] = createAtom("readSwapInt5");
    readSwapIntAtom[6][true] = createAtom("readSwapInt6");
    readSwapIntAtom[7][true] = createAtom("readSwapInt7");
    readSwapIntAtom[3][false] = createAtom("readSwapUInt3");
    readSwapIntAtom[5][false] = createAtom("readSwapUInt5");
    readSwapIntAtom[6][false] = createAtom("readSwapUInt6");
    readSwapIntAtom[7][false] = createAtom("readSwapUInt7");
    realFormatAtom = createAtom("_realformat");
    MAKESYSATOM(regexFindInstance);
    MAKEATOM(regexFindX);
    MAKEATOM(regexGetFindStr);
    MAKESYSATOM(regexInstance);
    MAKEATOM(regexNewSetStrPattern);
    MAKEATOM(regexNewSetUStrPattern);
    MAKEATOM(regexNewStrFind);
    MAKEATOM(regexNewStrFound);
    MAKEATOM(regexNewStrFoundX);
    MAKEATOM(regexNewStrReplaceX);
    MAKEATOM(regexNewUStrFind);
    MAKEATOM(regexNewUStrFound);
    MAKEATOM(regexNewUStrFoundX);
    MAKEATOM(regexNewUStrReplaceX);
    MAKEATOM(regexReplaceX);
    MAKEATOM(releaseRow);
    MAKEATOM(releaseRowset);
    MAKEATOM(reportFieldOverflow);
    MAKEATOM(reportRowOverflow);
    MAKEATOM(responseinfo);
    MAKEATOM(restoreCluster);
    MAKEATOM(return);
    MAKEATOM(returnPersistVersion);

    reverseIntAtom[2][false] = createAtom("revUInt2");
    reverseIntAtom[3][false] = createAtom("revUInt3");
    reverseIntAtom[4][false] = createAtom("revUInt4");
    reverseIntAtom[5][false] = createAtom("revUInt5");
    reverseIntAtom[6][false] = createAtom("revUInt6");
    reverseIntAtom[7][false] = createAtom("revUInt7");
    reverseIntAtom[8][false] = createAtom("revUInt8");
    reverseIntAtom[2][true] = createAtom("revInt2");
    reverseIntAtom[3][true] = createAtom("revInt3");
    reverseIntAtom[4][true] = createAtom("revInt4");
    reverseIntAtom[5][true] = createAtom("revInt5");
    reverseIntAtom[6][true] = createAtom("revInt6");
    reverseIntAtom[7][true] = createAtom("revInt7");
    reverseIntAtom[8][true] = createAtom("revInt8");

    roundAtom = createAtom("_round");
    MAKEATOM(roundTo);
    roundupAtom = createAtom("_roundup");
    MAKEATOM(rowAllocatorMarker);
    MAKEATOM(rowset2DatasetX);
    MAKEATOM(rtlDeserializeRow);
    MAKEATOM(rtlDeserializeToBuilder);
    MAKEATOM(rtlFieldKeyMarker);
    MAKEATOM(rtlMax);
    MAKEATOM(rtlMin);
    MAKEATOM(rtlRandom);
    MAKEATOM(rtlSerializeRow);
    MAKEATOM(rtlSerializeToBuilder);
    MAKEATOM(searchTableInteger4);
    MAKEATOM(searchTableInteger8);
    MAKEATOM(searchTableUInteger4);
    MAKEATOM(searchTableUInteger8);
    MAKEATOM(searchUnicodeTable);
    MAKEATOM(searchVUnicodeTable);
    MAKEATOM(searchUtf8Table);
    MAKEATOM(selectCluster);
    MAKESYSATOM(selfJoinPlaceholder);
    MAKEATOM(serializer);
    MAKEATOM(serializeCStringX);
    MAKEATOM(serializeDataX);
    MAKEATOM(serializeDatasetX);
    MAKEATOM(serializeGroupedDatasetX);
    MAKEATOM(serializeStringX);
    MAKEATOM(serializeBool);
    MAKEATOM(serializeFixedData);
    MAKEATOM(serializeFixedString);
    MAKEATOM(serializeLPData);
    MAKEATOM(serializeLPQString);
    MAKEATOM(serializeLPString);
    MAKEATOM(serializeQStrX);
    MAKEATOM(serializeRaw);
    MAKEATOM(serializeReal4);
    MAKEATOM(serializeReal8);
    MAKEATOM(serializeRow);
    MAKEATOM(serializeRowsetX);
    MAKEATOM(serializeGroupedRowsetX);
    MAKEATOM(serializeSet);
    MAKEATOM(serializeUnicodeX);
    MAKEATOM(serializeUtf8X);
    MAKEATOM(serializerRowsetHelper);
    MAKEATOM(serializerPut);
    MAKEATOM(serializerBeginNested);
    MAKEATOM(serializerEndNested);
    MAKEATOM(serializerInstanceMarker);
    MAKEATOM(setConditionCode);
    MAKEATOM(setMethod);
    MAKEATOM(setOwnMethod);
    MAKEATOM(setPackedSigned);
    MAKEATOM(setPackedUnsigned);
    MAKEATOM(setResultBool);
    MAKEATOM(setResultData);
    MAKEATOM(setResultDataset);
    MAKEATOM(setResultDecimal);
    MAKEATOM(setResultInt);
    MAKEATOM(setResultQString);
    MAKEATOM(setResultRaw);;
    MAKEATOM(setResultReal);
    MAKEATOM(setResultSet);
    MAKEATOM(setResultString);
    MAKEATOM(setResultUInt);
    MAKEATOM(setResultUnicode);
    MAKEATOM(setResultVarString);
    MAKEATOM(setResultVarUnicode);
    MAKEATOM(setWorkflowCondition);
    MAKEATOM(set2SetX);
    sinAtom = createAtom("_sin");
    sinhAtom = createAtom("_sinh");
    MAKEATOM(skipActionMarker);
    MAKEATOM(skipReturnMarker);
    MAKEATOM(speed);
    MAKEATOM(spill);
    MAKESYSATOM(spill);
    MAKESYSATOM(spillReason);
    sqrtAtom = createAtom("_sqrt");
    MAKEATOM(startPersist);
    MAKESYSATOM(steppedMeta);
    MAKEATOM(str2Data);
    MAKEATOM(str2DataX);
    MAKEATOM(strToQStr);
    MAKEATOM(strToQStrX);
    MAKEATOM(str2Str);
    MAKEATOM(str2StrX);
    MAKEATOM(str2VStr);
    MAKEATOM(str2VStrX);
    MAKEATOM(strcpy);
    MAKEATOM(strlen);
    MAKEATOM(subDataFT);
    MAKEATOM(subDataFTX);
    MAKEATOM(subDataFX);
    MAKEATOM(subgraph);
    MAKEATOM(subQStrFT);
    MAKEATOM(subQStrFTX);
    MAKEATOM(subQStrFX);
    MAKEATOM(subStrFX);
    MAKEATOM(subStrFT);
    MAKEATOM(subStrFTX);
    MAKEATOM(sysFail);
    tanAtom = createAtom("_tan");
    tanhAtom = createAtom("_tanh");
    MAKESYSATOM(tempCount);
    MAKESYSATOM(translated);
    MAKEATOM(trimAll);
    MAKEATOM(trimBoth);
    MAKEATOM(trimLeft);
    MAKEATOM(trimRight);
    MAKEATOM(trimStrLen);
    MAKEATOM(trimUnicodeAll);
    MAKEATOM(trimUnicodeBoth);
    MAKEATOM(trimUnicodeLeft);
    MAKEATOM(trimUnicodeRight);
    MAKEATOM(trimUnicodeStrLen);
    MAKEATOM(trimUtf8All);
    MAKEATOM(trimUtf8Both);
    MAKEATOM(trimUtf8Left);
    MAKEATOM(trimUtf8Right);
    MAKEATOM(trimUtf8StrLen);
    MAKEATOM(trimVAll);
    MAKEATOM(trimVBoth);
    MAKEATOM(trimVLeft);
    MAKEATOM(trimVRight);
    MAKEATOM(trimVStrLen);
    MAKEATOM(trimVUnicodeAll);
    MAKEATOM(trimVUnicodeBoth);
    MAKEATOM(trimVUnicodeLeft);
    MAKEATOM(trimVUnicodeRight);
    MAKEATOM(trimVUnicodeStrLen);
    truncateAtom = createAtom("_truncate");
    MAKEATOM(UChar);
    MAKEATOM(unicode2Codepage);
    MAKEATOM(unicode2CodepageX);
    MAKEATOM(unicode2Data);
    MAKEATOM(unicode2DataX);
    MAKEATOM(unicode2CodepageX);
    MAKEATOM(unicode2Unicode);
    MAKEATOM(unicode2UnicodeX);
    MAKEATOM(unicodeToUtf8);
    MAKEATOM(unicodeToUtf8X);
    MAKEATOM(unicode2VCodepage);
    MAKEATOM(unicode2VCodepageX);
    MAKEATOM(unicode2VUnicode);
    MAKEATOM(unicode2VUnicodeX);
    MAKEATOM(unicodeNullTerminate);
    MAKEATOM(unicodeStrcpy);
    MAKEATOM(unicodeStrlen);
    MAKEATOM(unicodeSubStrFX);
    MAKEATOM(unicodeSubStrFTX);
    MAKEATOM(updatePersist);
    utf8Atom = createAtom("utf-8");
    MAKEATOM(utf82Codepage);
    MAKEATOM(utf82CodepageX);
    MAKEATOM(utf82Data);
    MAKEATOM(utf82DataX);
    MAKEATOM(utf82Unicode);
    MAKEATOM(utf82UnicodeX);
    MAKEATOM(utf8ToUtf8);
    MAKEATOM(utf8ToUtf8X);
    MAKEATOM(utf8Length);
    MAKEATOM(utf8Size);
    MAKEATOM(utf8SubStrFX);
    MAKEATOM(utf8SubStrFTX);
    MAKEATOM(validReal);
    MAKEATOM(vcodepage2Unicode);
    MAKEATOM(vcodepage2UnicodeX);
    MAKEATOM(vcodepage2VUnicode);
    MAKEATOM(vcodepage2VUnicodeX);
    MAKEATOM(vn2b);
    MAKEATOM(vn2f);
    MAKEATOM(vn2l4);
    MAKEATOM(vn2l8);
    MAKEATOM(vn2ls4);
    MAKEATOM(vn2ls8);
    MAKEATOM(vstr2Data);
    MAKEATOM(vstr2Str);
    MAKEATOM(vstr2VStr);
    MAKEATOM(vunicode2Codepage);
    MAKEATOM(vunicode2CodepageX);
    MAKEATOM(vunicode2Data);
    MAKEATOM(vunicode2DataX);
    MAKEATOM(vunicode2Unicode);
    MAKEATOM(vunicode2UnicodeX);
    MAKEATOM(vunicode2VCodepage);
    MAKEATOM(vunicode2VCodepageX);
    MAKEATOM(vunicode2VUnicode);
    MAKEATOM(vunicode2VUnicodeX);
    MAKEATOM(walkIndirectMetaMember);
    MAKEATOM(wrapper);
    MAKEATOM(wregexFindX);
    MAKEATOM(wregexGetFindStr);
    MAKEATOM(wregexReplaceX);
    MAKEATOM(writeEbcdic);
    writeIntAtom[3] = createAtom("writeInt3");
    writeIntAtom[5] = createAtom("writeInt5");
    writeIntAtom[6] = createAtom("writeInt6");
    writeIntAtom[7] = createAtom("writeInt7");
    MAKEATOM(writeReal);
    MAKEATOM(writeSigned);
    MAKEATOM(writeString);
    MAKEATOM(writeUnicode);
    MAKEATOM(writeUnsigned);
    MAKEATOM(writeUtf8);
    MAKEATOM(xmlColumnProvider);
    MAKEATOM(xmlDecodeStr);
    MAKEATOM(xmlDecodeUStr);
    MAKEATOM(xmlEncodeStr);
    MAKEATOM(xmlEncodeUStr);
    MAKEATOM(xmlReadMarker);
    return true;
}
