# This is a basic workflow to help you get started with Actions

name: buildit-using-docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
      - master-ch1
      - master-ch2
  pull_request:
    branches:
      - main
      - master
      - master-ch1
      - master-ch2

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#        with:
#          submodules: recursive
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USER }}
#          password: ${{ secrets.DOCKER_HUB_PASS }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .github/workflows
          file: .github/workflows/Dockerfile
          pull: true
          push: false
#          cache-from: type=registry,ref=hustakin/hello-world-docker-action:latest
#          cache-to: type=inline
#          tags: hustakin/hello-world-docker-action:latest
          build-args: |
            BASE_BRANCH=master
            BUILD_BRANCH=master-ch1
