name: Build ECL Watch (build-eclwatch.yml)

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: 'Operating System'
        required: false
        default: 'ubuntu-22.04'
      asset-name:
        type: string
        description: 'Asset name'

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    name: "Build eclwatch"
    runs-on: ${{ inputs.os }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: esp/src
        run: npm ci

      - name: Build
        working-directory: esp/src
        run: npm run build-nightly
        
      - name: Upload Package
        if: ${{ inputs.asset-name }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.asset-name }}
          path: |
            esp/src/build/dist-nightly/
          if-no-files-found: error
