# JiraBot - Process PR (Privileged)
# This workflow runs on workflow_run and has write permissions and secrets
name: jirabot-process

on:
  workflow_run:
    workflows: ["jirabot"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  jirabot:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "Checkout base branch"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 1
          
      - name: "Download PR Info"
        uses: actions/github-script@v7
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr-info"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr-info.zip', Buffer.from(download.data));
            
      - name: "Extract PR Info"
        run: |
          unzip pr-info.zip
          echo "PR_NUMBER=$(cat number)" >> $GITHUB_ENV
          echo "PR_TITLE=$(cat title)" >> $GITHUB_ENV
          echo "PR_AUTHOR=$(cat author)" >> $GITHUB_ENV
          echo "PR_URL=$(cat url)" >> $GITHUB_ENV
          echo "PR_COMMENTS_URL=$(cat comments_url)" >> $GITHUB_ENV
          
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.8"
          
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade atlassian-python-api
          python -m pip --version
          
      - name: "Run Jirabot Script"
        env:
          JIRABOT_USERNAME: ${{ secrets.JIRABOT_USERNAME }}
          JIRABOT_PASSWORD: ${{ secrets.JIRABOT_PASSWORD }}
          JIRA_URL: ${{ vars.JIRA_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHUB_JIRA_USER_MAP: ${{ vars.GHUB_JIRA_USER_MAP }}
          JIRA_ISSUE_PROPERTY_MAP: ${{ vars.JIRA_ISSUE_PROPERTY_MAP }}
        run: python .github/scripts/jirabot.py
        shell: bash
