
name: Check that eclhelper interface has not changed

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"

jobs:
  build:
    name: "Check eclhelper interface"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: check-skips
        nneds: Checkout
        run: echo '::set-output name=should-skip::`git diff HEAD^ --exit-code -- rtl/include/eclhelper.hpp && echo false || echo true`'
        shell: bash
      - name: Do it all
        needs: check-skips
        if: ${{ needs.check-skips.outputs.should_skip != 'true' }}
        run: echo "I ran!"

        
